### ISSUE TITLE
ActivityPub Endpoints

### ISSUE THREAD

**Issue by dansup** [pixelfed/pixelfed#1]
- [x] ~Actor Object (/users/username)~
- [x] ~Actor Inbox (/users/username/inbox)~
- [x] ~Actor Outbox (/users/username/outbox)~
- [x] ~Following (/users/username/following)~
- [x] ~Followers (/users/username/followers)~

**Comment by BenLubar** [comment]
A few things I noticed with the currently-implemented ActivityPub stuff:

1. It seems to be converting single newlines to paragraph breaks and double newlines to a blank paragraph. This should probably be one newline -> line break, more than one -> paragraph break, or at the very least, wrapping the entire post in a single paragraph and just having newlines equal line breaks.

2. The "toot count" shown in Mastodon seems to be the total number of media files attached to the account, not the total number of statuses.
