### ISSUE TITLE
Notification for liking comment says "liked your photo"

### ISSUE THREAD

**Issue by dnno** [pixelfed/pixelfed#1004]
Thanks for your awesome work with pixelfed, I'm really enjoying it! I noticed a small text inconsistency today. When somebody favs a comment, the notification should read "...liked your comment" instead of "...liked your photo". Also the thumbnail accompanying thumbnail is unsuitable. I'm attaching a screenshot for your convenience!
![Screenshot_20190310-154204__01](https://user-images.githubusercontent.com/2003552/54086799-0e1f8400-434d-11e9-9c4d-71efb04bdb31.jpg)

**Comment by trwnh** [comment]
Notifications now say "post", I think.
