### ISSUE TITLE
Lightbox can be smaller than image in post

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1017]
This makes the feature kind of useless at certain sizes
![image](https://user-images.githubusercontent.com/10606431/54180355-68ae0280-4469-11e9-94e0-624aa8559c95.png)

**Comment by trwnh** [comment]
Suggested fix: 

```
#lightbox .modal-dialog {
  max-width: 100vw !important;
  max-height: 100vh !important;
}
```

**Comment by trev-dev** [comment]
@trwnh If max-width and max-height are set this way, would you have to worry about the image ratio/distortion?

Also for having lightbox images fill the maximum width/height. Another option would be to have a div container that's 100vh/100vh and setting the background of that div to the image. This way you could use background-size: contain;

**Comment by trwnh** [comment]
@trev-dev I don't think so? The modal-dialog is merely a wrapper for modal-content which wraps modal-body, etc.
![image](https://user-images.githubusercontent.com/10606431/54332194-1b599e80-45eb-11e9-85bc-08122fdcfd49.png)

The "problem class" currently is `.modal-lg` which has `max-width: 800px`. I put the max-height in there because I suspect tall images might cause a problem on certain screens, but I haven't tested it 100%. It might even be unnecessary, because what currently controls the height is `.modal-dialog-centered::before`, which sets a height of `100vh - 3.5 rem` explicitly.

I doubt the actual fix will end up being exactly what I posted above, but that was a quick hack that worked in a limited case. I'm sure there's a better way to do it...

EDIT: OK, yeah, the max-width only works up until the image dimensions right now. I think it might be better not to use Bootstrap for this.

EDIT: forgot to mentions this too, but divs with background images are bad for accessibility. The images are img elements with alt text

**Comment by trwnh** [comment]
Rev 2:

```
#lightbox .modal-dialog {max-width: 100vw; margin: 0}
#lightbox .modal-content {display: block; width: auto}
#lightbox .modal-dialog-centered .modal-content {margin: auto}
#lightbox .modal-dialog img {max-height: calc(100vh)}
```

Result: 
![image](https://user-images.githubusercontent.com/10606431/54333157-67a6dd80-45ef-11e9-8898-8a5eb60ab75f.png)

I'm not entirely sure if the current lightbox modal makes sense on mobile, unless there's a way to zoom a modal without zooming the page. Images are already 100% width on mobile, although it does allow tall images to scale down to fit a screen, or at least to be shown above the header/tab-bar:

![image](https://user-images.githubusercontent.com/10606431/54333217-a8065b80-45ef-11e9-8fb3-2cbf60e0c6d4.png)

Extremely small screen:
![image](https://user-images.githubusercontent.com/10606431/54333329-1519f100-45f0-11e9-88ea-759bbd792cf8.png)

Current limitation: if an image is exactly the aspect ratio of the viewport, you cannot exit the modal by clicking, as there is nowhere you can click outside of it. You can only escape by hitting Escape on a keyboard.

**Comment by hellcp** [comment]
> Current limitation: if an image is exactly the aspect ratio of the viewport, you cannot exit the modal by clicking, as there is nowhere you can click outside of it. You can only escape by hitting Escape on a keyboard.

Overlaying X somewhere would be nice, although would block the view. Maybe clicking on image should close it as well?

**Comment by trwnh** [comment]
I think being able to swipe the lightbox out of view makes sense on smaller screens. On larger screens there can be a bit of margin for a topbar with an x and other controls.

**Comment by todoneunl** [comment]
Since the latest commit, I can't open the lightbox anymore.

**Comment by trwnh** [comment]
lightbox has been temporarily disabled due to conflicting with
double-click-to-like. it will be re-added as a button

**Comment by todoneunl** [comment]
OK, good to hear (although IMO it's logically to only use the like button for likes). Hopefully the lightbox will have a larger resolution when the button is added.

**Comment by trwnh** [comment]
Closing because the old lightbox was deprecated; new lightbox should be fullscreen with controls
