### ISSUE TITLE
Lightbox should allow navigating through album posts

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1019]
Currently, opening an album post in the lightbox only lets you view that one image. To view another image in the lightbox, you have to go back to the timeline and navigate to the next image in the post, and click again to view it in a lightbox.

**Comment by dansup** [comment]
I don't know about this, the lightbox should only contain a single photo because of the context.

**Comment by trwnh** [comment]
Lightbox should show one photo *at a time*, but allow navigation through one *set*, imo. In pixelfed terms, our set is one post; in other galleries, it may be one album/folder.

**Comment by trwnh** [comment]
Related: #344

**Comment by trwnh** [comment]
Closing because the old lightbox was deprecated
