### ISSUE TITLE
Lightbox should show overlays with more info

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1020]
Would be nice to have an overlay at the bottom of the lightbox that appears when you click/tap the lightbox. This overlay could show image descriptions / alt text, potentially tagged people if that gets implemented, etc.

**Comment by dansup** [comment]
@trwnh I'm not sure about this, the lightbox is just a bootstrap modal. We would have duplicated carousel logic if lightbox supported carousels.
