### ISSUE TITLE
Search bar is too small on mobile

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1021]
At small widths common on mobile devices, there is not enough space to show a full search bar. Instead, there should be a search icon that loads a search overlay. Alternatively, search can be integrated into Discover, maybe? This is how Instagram does it, so there could be value to that approach. The icon for Discover would have to be changed to a magnifying glass instead.

**Comment by dansup** [comment]
This is the updated navbar refactor with an improved search bar, what do you think?

<img width="379" alt="Screen Shot 2019-04-02 at 6 41 08 PM" src="https://user-images.githubusercontent.com/877217/55445122-f2d41d00-5576-11e9-98a0-54c79713b67a.png">

**Comment by trwnh** [comment]
imo i still think it should be part of the discover page. that top bar looks crowded. search deserves to be a modal or overlay, i think

**Comment by dansup** [comment]
@trwnh I think search and discovery deserves more than an icon and modal. I am confident the current  search bar in the mobile web UI is a good balance between limited space and value.

**Comment by trwnh** [comment]
Mockup:

![image](https://imgur.com/fJJoLf5.png)
