### ISSUE TITLE
Notifications list has improper padding and layout breaks on mobile

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1022]
![image](https://user-images.githubusercontent.com/10606431/54181764-9432ec00-446d-11e9-8c1c-0b02c23cf82e.png)

**Comment by dansup** [comment]
@trwnh @hellcp I think we should reduce padding on smaller break points but we should rethink the current layout.

Should we remove the avatars from notifications to keep it on a single line?

**Comment by hellcp** [comment]
I wouldn't remove all the styling from the list-group, it looks way better with it and provides better background than grey (also the topbar nav takes less space there :P )

![Screenshot from 2019-04-03 03-02-16](https://user-images.githubusercontent.com/30577011/55445722-fb4f4680-55bc-11e9-8e9f-130deab3276f.png)
![Screenshot from 2019-04-03 03-02-29](https://user-images.githubusercontent.com/30577011/55445723-fb4f4680-55bc-11e9-8488-70507096f70e.png)

**Comment by hellcp** [comment]
Actually it might be even better to create a bottombar nav (the opposite of topbar nav) and put it directly above the list group

**Comment by dansup** [comment]
Fixed in v0.9.0 iirc
