### ISSUE TITLE
Confirmation email

### ISSUE THREAD

**Issue by Victor-Morel** [pixelfed/pixelfed#1025]
Hello,  
I just installed pixelfed, on Debian stable/apache2/mariadb.  
I'm having troubles in receiving conformation email: I don't know whether it has been send or not.  
Can you give me some clues so as to sort this issue?  
Thanks

**Comment by trwnh** [comment]
This sounds like an issue with your mail server configuration, or your mail provider's incoming filters. Can you give some more details on how you set up emails?

**Comment by dansup** [comment]
Mail is handled by the laravel framework, you can find more information on setting it up [here](https://laravel.com/docs/5.8/mail#introduction).

**Comment by downeym** [comment]
Are the mail settings in `.env` ignored or should we be editing `config/mail.php` in this case?

**Comment by kkretsch** [comment]
For me the standard settings didn't work under debian. I had to change the line in the .env file to:
```
MAIL_DRIVER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=25
```
