### ISSUE TITLE
Regression: Shared posts on Mastodon are not detected by pixelfed

### ISSUE THREAD

**Issue by renatolond** [pixelfed/pixelfed#1029]
Previously, when a post was boosted on Mastodon, it showed up as "shared" on Pixelfed (though I think it never notified), as it can be seen here:
https://pixelfed.social/p/renatolond/40138 / https://masto.donte.com.br/@renatolond/101749127561585489

However, recently it started not showing the shared numbers anymore:
https://pixelfed.social/p/renatolond/11783357952299008 / https://masto.donte.com.br/@renatolond/101749132045466504

The comments I left to get the mastodon links, however, show on the posts, so it's not a complete federation issue.
No errors can be seen on Mastodon's side.

**Comment by dansup** [comment]
@renatolond This is not a regression, we have not changed any federation code. This is more likely an issue specific to that boost activity. 

You mention that replies work as expected, if you notice boosts are still not showing up on pixelfed please feel free to re-open this issue!
