### ISSUE TITLE
Option to allow non-members (guests) to view picture detail

### ISSUE THREAD

**Issue by elobdr** [pixelfed/pixelfed#1036]
Hi,

I was thinking about a new feature for PixelFed. Allowing non-members (guests) to access photo details.

The thing is, I would like people who don't have an account to be able to see, not only my profile but my individual pictures as well. Because one of my friend who doesn't have an account on PixelFed tried to click on one of my photos and it said that she needed an account to access the photo.
That could be a switch in the account settings, so not everyone would be impacted by this feature. Or it could be an instance setting as well.

So, would it be possible for non-members to see a individual pictures like in the screenshot below ? :)

Nonetheless you did an amazing job, I left Instagram thanks to you!

![Capture d’écran 2019-03-16 à 22 47 46](https://user-images.githubusercontent.com/48631908/54482061-d8433980-483d-11e9-849d-7c1be9629c83.png)

**Comment by trwnh** [comment]
You should be able to view individual pictures even while logged out... at least, provided that they are public. What was the privacy setting on the image?

**Comment by dansup** [comment]
@elobdr If a post is private, you need to be logged in.

**Comment by elobdr** [comment]
Okay it works ;) thank you!
