### ISSUE TITLE
Landing page layout issues

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1043]
Not properly responsive

pic 1 | pic 2
--- | ---
![image](https://user-images.githubusercontent.com/10606431/54497530-c1e2bf80-48c9-11e9-9db0-cece7c3a3077.png) | ![image](https://user-images.githubusercontent.com/10606431/54497539-e2ab1500-48c9-11e9-89e8-b3e23faaa68d.png)
 
A more specific issue seems to be that the device frames are not scaling at all to fit their container, due to using absolute positioning and explicit pixel sizing:

pic 1 | pic 2
--- | ---
![image](https://user-images.githubusercontent.com/10606431/54497604-8e546500-48ca-11e9-9329-772efef233b9.png) | ![image](https://user-images.githubusercontent.com/10606431/54497608-a330f880-48ca-11e9-82d7-83f91b490b61.png)

Also at `min-width: 1200px` the `.container` has two `max-width`s set, at both `935px` and `1140px`. Disabling the `935px` rule causes the `1200px` layout to show properly:

![image](https://user-images.githubusercontent.com/10606431/54497576-23a32980-48ca-11e9-8519-4c41e172cf47.png)

**Comment by trwnh** [comment]
Per #1091: this is an issue due to the Chromium-only zoom() CSS, and is currently being worked on.

**Comment by dansup** [comment]
Fixed in 04d7af0e
