### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by JanWerder** [pixelfed/pixelfed#1054]
The API documentation is missing. This would be key for any client development.

**Comment by daknuett** [comment]
While there is no API documentation, where can one find the API implementation to look some stuff up?

**Comment by trwnh** [comment]
Current API implementation is basically Mastodon v1 API, but it's also a work in progress so you can't expect every method to be implemented yet. Full documentation will be ready with the release of v1.0.0!

**Comment by janboddez** [comment]
Meanwhile, there's `app/Http/Controllers/Api/BaseApiController.php` and `app/Http/Controllers/InternalApiController.php`, as made clear by `routes/web.php`.

**Comment by mvolpato** [comment]
Is there a file we can check for the list of implemented api access points? Because I tried the app registration https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#apps and got 404.

**Comment by trwnh** [comment]
@mvolpato So far it's just this: https://github.com/pixelfed/pixelfed/blob/ccef4d09392c8f0f9422a67534fe8cf60686aafa/routes/web.php#L66-L104

**Comment by mvolpato** [comment]
It looks like it still misses a way to authenticate. I will watch this file for changes. Thanks!

**Comment by amazzoccone** [comment]
Maybe [Swagger](https://swagger.io) would be useful?

**Comment by patcon** [comment]
Maybe http://zircote.com/swagger-php/Getting-started.html ?

**Comment by janboddez** [comment]
Kinda curious as to how/where this is now covered... 'Official' docs still empty. I was half expecting Laravel Passport routes to just work, but it'd depend on the instance settings.
