### ISSUE TITLE
Irregularities and vagueness in the Terms of Use, Section 2

### ISSUE THREAD

**Issue by chlorinatedsugar** [pixelfed/pixelfed#1059]
I have several issues concerning the Terms of Use, a lot of them in section 2.

In section _2.a_, a reference is made to 'the materials'. However, it is unclear what 'the materials' means in this context. In parentheses behind the word, it says 'information or software'. However, this is a vaguely broad term, as well as an unclear term as to what type of materials are included in this definition. This is mainly a concern because the following terms _2.a.i-v_ are very restrictive, and this seems to be inappropriate for some types of materials.

For example, what is meant by 'information'? Images, including those uploaded by users, could be treated as 'information'. In this case, restrictions seem to govern the user's own content, never acknowledging that their copyright remains theirs.

Therefore, a clear and brief section explaining the scope of 'the materials' should be present in the Terms of Use.

**'The materials' meaning 'software'**
For now, I'll focus on the software aspect of 'the materials'. In this case, the use license is overly restrictive and not compliant with the GNU Affero General Public License currently used in the software.

- Section _2.a.i_ says that it's prohibited to modify or copy the materials, despite being specifically allowed in the license of the software.
- Section _2.a.ii_ says that the materials may not be used commercially nor used for public display.
- Section _2.a.iii_ says it's not allowed to decompile or reverse engineer the software contained, which is strange, considering the source code is available and decompilation or reverse engineering shouldn't pose a threat.
- Section _2.a.iv_ seems to be okay, considering it's only about copyright and other proprietary notations on the materials, which should in any case be present.
- Section _2.a.v_ prohibits copying of materials to another person or server. What is the rationale behind this prohibition in the case of the software? It's free and open-source, and shouldn't be under these strict rules.

Furthermore, in the initial section of section _2.a_, it is mentioned that "permission is granted to download one copy of the materials [...], for personal, non-commercial transitory viewing only". In the case of software, this again seems to be against the license. What was the rationale behind this section?

**'The materials' meaning 'user content'**
Considering that the term 'information' is used in defining 'the materials' as well, this could include user content. In this case, the terms _2.a.i_, _2.a.ii_ and _2.a.v_ restrict the user's options beyond reason. For example, _2.a.i_ and _2.a.ii_ prohibit the use of a Creative Commons license for user content. _2.a.v_ prohibits the user from posting content on any other server beyond the one initially posted, which is entirely against the easy-to-switch nature of federated software.

**Proposed solution**
At the very least, the entire section should be revisited and thoroughly adjusted to avoid the problems listed. However, I do not think it's a wise idea to extend the length of the Terms of Use much beyond the amount of text currently present, since reading Terms of Use and License Agreements is a rather daunting task in and of itself to many users. In fact, I think that the current length is already rather large, and part of the open nature of FOSS products is to be able to read the license agreements without risking missing something or requiring a legal degree to do so.

Having said that, either the section containing the restrictions should be removed, or 'the materials' should get a proper definition. In the latter case, it would be best to split the section up into a part about the software, a part about the instance's materials used on its website, and a part about the user content. It should be explicitly mentioned that the user is responsible for his/her content, and that he/she remains the copyright owner of the content, in the case that restrictions are placed upon the user's content. This also means that it should be written down in a brief, friendly, and non-jargon manner, while remaining legally true.

**Comment by dansup** [comment]
@chlorinatedsugar I used some Terms of Service generator and looking back this was probably not the best solution for our project.

I agree with everything you have pointed out, and look forward to releasing an updated Terms of Service!

**Comment by ghost** [comment]
Each admin should be able to customize and/or replace the Terms of Use. An open source project doesn't want to be playing lawyer with local jurisdictional law. 😉

**Comment by trwnh** [comment]
Superseded by #1465

**Comment by chlorinatedsugar** [comment]
Please reopen this issue, #1465 does not supersede it. #1465 has been closed several times now, and these issues haven't been resolved at all both times. It's currently open again, but still doesn't address this issue in any way.

**Comment by chlorinatedsugar** [comment]
Perhaps the entirety of Section 2 can be replaced with a short notice like:

> Pixelfed is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the [GNU Affero General Public License](https://github.com/pixelfed/pixelfed/blob/dev/LICENSE) for more details.

This notice was adapted from the bottom of this document here: https://www.gnu.org/licenses/agpl-3.0.en.html. Perhaps it could be made even shorter to make it more readable, but this is at least a safe route.

Note that I refer to "Pixelfed" as _software_ here, and the rest of the Terms of Use do not do so, so proper definitions should be put forth first.

**Comment by trwnh** [comment]
The reason I closed this as superseded by #1465 was that we were/are planning to replace these Terms of Use entirely, due to multiple issues with the default text. It would be better to have all discussion happening on #1465 as to what a proper Terms of Use should look like, so let's move the conversation there, if you don't mind.
