### ISSUE TITLE
Regression: Posts in timeline do not show bookmark button

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1064]
I noticed that Timeline.vue only includes like/comment/share, whereas the PostComponent.vue has like/comment/share/bookmark.

Also, it might be a good idea to create a separate component just for these buttons, so that consistency is automatic in the future.

**Comment by dansup** [comment]
@trwnh It was removed from timelines to improve performance and reduce database queries. After I refactor the timeline logic to use redis, it should be ok to bring back to timelines!
