### ISSUE TITLE
Unable to open api/nodeinfo/2.0.json

### ISSUE THREAD

**Issue by sanjibnarzary** [pixelfed/pixelfed#1066]
Unable to find servername/api/nodeinfo/2.0.json for which I am not being able to see the registration and login option for my freshly installed pixelfed.

I tried updating node but it did not help.

**Comment by dansup** [comment]
@sanjibnarzary Hi, can you provide more information?

Please run the ```php artisan self-diagnosis``` command and report the results here.

**Comment by sanjibnarzary** [comment]
The problem is gone on the latest pull. However login and registration endpoint does not seem to work.

**Comment by sanjibnarzary** [comment]
`$php artisan self-diagnosis
|-------------------------------------
| Common Checks
|-------------------------------------
Running check 1/11: App key is set...  ✔
Running check 2/11: The correct PHP version is installed...  ✔
Running check 3/11: The database can be accessed...  ✔
Running check 4/11: All directories have the correct permissions...  ✔
Running check 5/11: The environment file exists...  ✔
Running check 6/11: The example environment variables are set...  ✔
Running check 7/11: Required locales are installed...  ✘
Running check 8/11: Maintenance mode is not enabled...  ✔
Running check 9/11: The migrations are up to date...  ✔
Running check 10/11: The required PHP extensions are installed...  ✔
Running check 11/11: The storage directory is linked...  ✔

|-------------------------------------
| Environment Specific Checks (local)
|-------------------------------------
Running check 1/4: Composer dependencies (including dev) are up to date...  ✔
Running check 2/4: Configuration is not cached...  ✔
Running check 3/4: Routes are not cached...  ✔
Running check 4/4: The example environment variables are up-to-date...  ✔

The following checks failed:
The following locales are missing:
en_US`

**Comment by sanjibnarzary** [comment]
My locale settings
`locale
LANG=en_IN
LANGUAGE=en_IN:en
LC_CTYPE="en_IN"
LC_NUMERIC="en_IN"
LC_TIME="en_IN"
LC_COLLATE="en_IN"
LC_MONETARY="en_IN"
LC_MESSAGES="en_IN"
LC_PAPER="en_IN"
LC_NAME="en_IN"
LC_ADDRESS="en_IN"
LC_TELEPHONE="en_IN"
LC_MEASUREMENT="en_IN"
LC_IDENTIFICATION="en_IN"
LC_ALL=`

**Comment by dansup** [comment]
@sanjibnarzary Hi, a recent comment changed the landing page and does not require that API endpoint. Are you running the latest code from ```dev``` branch?

**Comment by carbontwelve** [comment]
I had the same issue, upon looking at the laravel error log I noticed it was complaining that `exec` was disabled. I enabled that in my php-fpm config for the pixelfed pool and the endpoint now works as expected.

@dansup I would like to suggest adding a check to the `self-diagnosis` for functions that are often disabled such as `exec`.

**Comment by sanjibnarzary** [comment]
@dansup the latest dev branch. This works fine whenever I tried with `php artisan server` but whenver I used it with apache virtualhost the login and register does not work. I donno my laravel.log also not appearing in storage/logs/laravel.log

**Comment by carbontwelve** [comment]
@sanjibnarzary does the process running apache have permission to write to the `storage/logs` path?
