### ISSUE TITLE
Can't upload multiple files

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#1071]
Hello,

I'm forced to upload my files one per one, because when i try to upload multiple files, it does nothing. After clicking on the validation button, it is as if i did absolutly nothing.

**Comment by trwnh** [comment]
Multiple file upload is working for me, in both of the post composers. Can you provide more details about what exactly you are trying?

**Comment by stemy2** [comment]
I tried to upload 20 at the same time, but after validation, the number of posted medias stayed to 0. But it seems to work when i post less images at the same time (it does multiple images in one post).

**Comment by trwnh** [comment]
The maximum number of attachments to one post is not 20. The uploader tells you that there is a limit of 6 photos per post.
