### ISSUE TITLE
[Enhancement] Advanced search

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#1073]
Hello,

The search engine is now very basic, an advanced search would allow user to search with some other options, like sorting, search by name, (de)-activate nsfw results, and more.

**Comment by dansup** [comment]
@stemy2 The search bar is undergoing a massive refactor with a proper results page. Some of the features you listed will be shipping in the next few days and the rest in the future!

**Comment by carbontwelve** [comment]
@dansup you're probably already aware of https://github.com/lorisleiva/laravel-search-string but it looks like it would help quickly add powerful advance search capability to pixelfed.
