### ISSUE TITLE
Media Toolbar appears blurry

### ISSUE THREAD

**Issue by ricardojmendez** [pixelfed/pixelfed#1078]
No idea what's causing this, but on Pixelfed.social the Media Toolbar is appearing blurry on macOS Chrome Version 73.0.3683.86 (Official Build) (64-bit).

This is still the case if I close the media toolbar and then re-open it. 

See screenshot below.

![Screenshot 2019-03-26 at 15 51 23](https://user-images.githubusercontent.com/31263/55007230-58f0fb00-4fdf-11e9-9706-6f1599b9e357.png)

Everything else works as expected and I can interact with the elements in it.

![Screenshot 2019-03-26 at 15 54 53](https://user-images.githubusercontent.com/31263/55007342-8dfd4d80-4fdf-11e9-9be2-dc448fe6ab32.png)

**Comment by dansup** [comment]
Fixed in latest commits!
