### ISSUE TITLE
web UI does not show posts anymore on iPhone 4S with iOS 9.3.5

### ISSUE THREAD

**Issue by stragu** [pixelfed/pixelfed#1088]
Using Safari or Brave, there is no visible content (i.e. posts) in Home, Public timeline or Discover.

The "+" button does not bring up the upload menu, although it does grey out the page.

Notifications view work, notifications are listed as expected.

Everything worked fine a few weeks ago, but not sure which version introduced the issue.

I understand it is hard to support older hardware / software, but there are still quite a few people around the world using this device.
Let me know if I can help troubleshoot.

Instance: pixelfed.social
Pixelfed version: 0.8.4

iOS version: 9.3.5

Home view screenshot:

![image](https://user-images.githubusercontent.com/1747497/55043574-9b1f4880-5082-11e9-819d-4811bf76a52a.png)

**Comment by dansup** [comment]
Pixelfed only supports evergreen browsers. I have heard reports that Brave conflicts with pixelfed, I recommend disabling that extension if you want to use pixelfed.

**Comment by stragu** [comment]
Thanks for the reply, dansup.

I see. I'm new to the term "evergreen", but assume you mean that Safari is not one because it only updates when iOS updates?

Brave is not an extension, it is a browser in itself on this phone. It would qualify as an evergreen browser, but it doesn't provide updates for this iOS version anymore, just like Chrome, Firefox and Edge, so I assume iPhone 4's are out for Pixelfed's web view.

As a last resort, I tried two browser that supposedly still support this version of iOS: Opera Mini, and Puffin Browser, and both have the exact same issue as Safari and Brave.
