### ISSUE TITLE
Search omits user names as long as there are tags matching the search term

### ISSUE THREAD

**Issue by Chaos99** [pixelfed/pixelfed#1092]
When entering a search term, the results show only matching tags, not users, as long as the entered substring matches at least one tag.

You have to input more characters until no tag matches any more, then matching user names are returned.

This (together with the undocumented behavior of returning nothing for less than three characters) is surprising to the user and makes him think a username does not exist. If a username also exists as a tag or part of a tag, it's completely impossible to search for it.
If the next matching character is a special character, the username is also un-searchable.
(see #784 )

**Comment by dansup** [comment]
@Chaos99 Yeah the SearchController really needs to be refactored, will see if I can get it done this weekend!

**Comment by Chaos99** [comment]
Tags and Profiles are now listed separately in 0.8.5, this is solved.
