### ISSUE TITLE
New UI issues on Android mobile

### ISSUE THREAD

**Issue by Codercise** [pixelfed/pixelfed#1094]
I've recently been trying to use the new Pixelfed UI on Android mobile (Oppo A57). The UI does not show an image's upload progress and I'm fairly sure was just failing totally without any errors.

**Comment by dansup** [comment]
@Haydos585 Yeah the current UX is not ideal, will work on progress indicator with better error handling!

**Comment by dansup** [comment]
@Haydos585 Fixed in latest commits!
