### ISSUE TITLE
"Load more comments" shown in unnecessary contexts

### ISSUE THREAD

**Issue by Vertux** [pixelfed/pixelfed#1095]
If I have a post without comment, it looks like that

![Bildschirmfoto 2019-03-30 um 12 39 11](https://user-images.githubusercontent.com/10457918/55275687-dcfdf800-52e9-11e9-9e40-d4a257806d5a.png)

If I write a comment, it looks like that:

![Bildschirmfoto 2019-03-30 um 12 39 49](https://user-images.githubusercontent.com/10457918/55275692-f4d57c00-52e9-11e9-9f94-c043c90b052f.png)

Only after reload of the page, the comment will be displayed correctly. But the link "show more comments" is obsolete, because there are no other comments.

![Bildschirmfoto 2019-03-30 um 12 40 02](https://user-images.githubusercontent.com/10457918/55275707-3a924480-52ea-11e9-91d2-b7fe340a428c.png)

If I delete the comment, the link "show more comments" does not disappear:

![Bildschirmfoto 2019-03-30 um 12 40 28](https://user-images.githubusercontent.com/10457918/55275746-d623b500-52ea-11e9-9172-78d806e40ce2.png)

Only after I reloaded the page again, the link disappears:

![Bildschirmfoto 2019-03-30 um 12 39 11](https://user-images.githubusercontent.com/10457918/55275753-ffdcdc00-52ea-11e9-98cc-9c54b3d723a8.png)

This was tested on [https://pixelfed.social](https://pixelfed.social ) today, I do not know which Pixelfed version it is running there at the moment.

**Comment by dansup** [comment]
@Vertux This is fixed in the ```PostComponent.vue``` refactor, which is due to be released within the next few days!

**Comment by Vertux** [comment]
@dansup Great, thank you for the info.

**Comment by dansup** [comment]
Fixed in 5a80c06 and shipping in #1136
