### ISSUE TITLE
The "gallery counter" is not updated while slideshow

### ISSUE THREAD

**Issue by Vertux** [pixelfed/pixelfed#1097]
As you can see on the screenshots in issue #1096 the counter shows always the same numbers during the whole slideshow. It is only updated if you manually switch the images by clicking.

Tested on [https://pixelfed.de](https://pixelfed.de) today

**Comment by trwnh** [comment]
Duplicate of #796

**Comment by dansup** [comment]
@Vertux I have reproduced this bug, it will be fixed in the next batch of commits!

**Comment by dansup** [comment]
We no longer use this album UI
