### ISSUE TITLE
Cannot post new photo with empty caption

### ISSUE THREAD

**Issue by ansuz** [pixelfed/pixelfed#110]
Posting with no caption returns the error: `The caption must be a string.`

**Comment by kpcyrd** [comment]
The fix for this is probably very similar to #114, I'm not sure if uploads with no caption are supported. Maybe @dansup knows? :)

**Comment by trwnh** [comment]
Clicking "Create post" now simply closes the modal and refreshes the page, causing the image and any modifications to be lost.

**Comment by ellotheth** [comment]
Adding `nullable` to [this](https://github.com/pixelfed/pixelfed/blob/7192c11355224b287f47dc708214c8d6a499ee65/app/Http/Controllers/StatusController.php#L60) might fix it, but I haven't gotten a dev instance running yet to test.

**Comment by trwnh** [comment]
This can be closed; captions are now optional. @dansup 

edit: maybe only through the experimental UI? it's acting weird with the classic uploading UI...

**Comment by dansup** [comment]
@trwnh Yes, its only possible in the experimental UI. Will be replacing the old uploader soon enough!

**Comment by thomas-kuntz** [comment]
Indeed, omitting the caption works with the new experimental UI but makes the upload fail silently with the old uploader.
