### ISSUE TITLE
Can't put "_" in usernames

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1106]
Hello,

Actually if you try to create an account with a undercore `_` in the beginning of your username it doesn't work. The XHR request hang up and the register button keep turning in vain.

Is there something to do to fix this?

Thanks,

**Comment by dansup** [comment]
@mathiasblc Pixelfed has some unique username constraints, I will update the landing page with better client side validation and error handling to let the user know!

**Comment by dansup** [comment]
Fixed in latest commits!
