### ISSUE TITLE
[UI] comments aren't properly displayed

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1108]
Hello,

When you post a comment, the text is truncated and so on, can't be properly read. See the screenshot bellow:

<img width="254" alt="Screenshot 2019-04-02 at 15 06 05" src="https://user-images.githubusercontent.com/41020854/55404830-0f615c80-5559-11e9-92e4-f54b0ccc3e89.png">

Verified on Safari & Google Chrome, both last releases.

Thanks,

**Comment by dansup** [comment]
@mathiasblc Yes I fixed this by changing ```word-break``` to ```overflow-wrap: break-word;```. It will be released in the next batch of commits!

**Comment by ghost** [comment]
Hi,

I just updated to v0.8.5, it's fixed.
Many thanks!
