### ISSUE TITLE
Missing option to mute or block a profile on the main profile page

### ISSUE THREAD

**Issue by Vertux** [pixelfed/pixelfed#1129]
If you click a user name you get to its main profile page, but there is no option available to mute or block the profile:

![Bildschirmfoto 2019-04-05 um 20 50 24](https://user-images.githubusercontent.com/10457918/55650197-5a8f9f80-57e5-11e9-9133-94893fe74602.png)

Tested on [https://pixelfed.social](https://pixelfed.social)

**Comment by dansup** [comment]
Added in 77ee8086
