### ISSUE TITLE
Suggestion: A seperate input field for tags

### ISSUE THREAD

**Issue by Vertux** [pixelfed/pixelfed#1137]
I think it would be nice and more polished to offer a special input field for tags to separate them from the rest of the content (description, caption). At the moment users have no idea if and where you can add a tag - so it would increase the useability and would motivate the users to use tags to structure the content. As additional feature the input field could offer auto-completion.

It would be nice to display tags as badges, which looks very neat e.g.:

![Bildschirmfoto 2019-04-07 um 13 11 03](https://user-images.githubusercontent.com/10457918/55684173-9a22cc80-5948-11e9-8492-2c03e84de5eb.png)

![Bildschirmfoto 2019-04-07 um 13 08 08](https://user-images.githubusercontent.com/10457918/55684176-9ee78080-5948-11e9-83f4-3d1357e17171.png)

These screenshots were taken from instances of lobsters ([source](https://github.com/lobsters/lobsters)) and wallabag ([source](https://github.com/wallabag/wallabag))

**Comment by dansup** [comment]
Unlike lobsters or wallabag, hashtags on pixelfed can be valuable in the caption of a post and separating them at this point would be too confusing. Thanks for the suggestion though!
