### ISSUE TITLE
Resolution limit?

### ISSUE THREAD

**Issue by dermike** [pixelfed/pixelfed#1138]
Hi!

I'm testing Pixelfed on my own server. I probably don't know what I'm doing, so this could all be because of some misconfiguration or something...

When I try to upload photos from an iPhone, I get an unexpected error (500 error from /v1/media).
Same thing when I transferred the photo to my computer and trying to upload.
I'm using the standard MAX_PHOTO_SIZE=15000 setting, so file size shouldn't be the problem.

It works when I lowered the resolution from 4032x3024 to half.

**Comment by dansup** [comment]
@dermike Hello,

You can set the ```MAX_PHOTO_SIZE``` and ```IMAGE_QUALITY``` .env settings. You need to run ```php artisan config:cache``` whenever you edit .env for the changes to take effect.

For more info, checkout the [configuration documentation](https://docs.pixelfed.org/master/configuration.html#pixelfed-configuration).

**Comment by dermike** [comment]
If anyone else have this problem, changing upload_max_size in php.ini solved it for me!
