### ISSUE TITLE
AWS S3 Support for file storage

### ISSUE THREAD

**Issue by shleeable** [pixelfed/pixelfed#1139]
Basic: My Mastodon Instance use S3 to storage all data "offsite".. this has a number of benefits
1) If my server dies, as long as the database is backed up, I can store the server and continue from there.
2) Cloud provider can handle disk/storage (infinite growth) and IO.. Backups are generally covered and safe. AWS S3 for example is cached globally via their CDN blah blah blah blah blah

So please allow me to follow this pattern. :)

Advanced: Uploading of video to S3 could allow us to use Lamdba to trigger transcoding to different formats on demand in the cloud instead of locally....

**Comment by shleeable** [comment]
As discussed, there is no major problem.. the code is partially there.
It currently saves to local, then uploads to cloud storage and video doesn't support cloud yet.

**Comment by cnf** [comment]
I'd say object-storage in general would be nice. S3, but also Azure Blob storage, backblaze B2 etc. (so basically an abstraction layer to storage)

Thanks!

**Comment by dansup** [comment]
@cnf We are using [flysystem](https://flysystem.thephpleague.com/docs/) (filesystem abstraction layer), the services you mentioned will be supported out of the box!

**Comment by ghost** [comment]
hello,

what about this feature? is [the s3 adapter](https://flysystem.thephpleague.com/v1/docs/adapter/aws-s3-v2/) supported now? i can't find anything related to this in the docs.

thanks in advance,

**Comment by dansup** [comment]
S3 has been supported for a while. Closing this.
