### ISSUE TITLE
Federated comments not appearing

### ISSUE THREAD

**Issue by kvibber** [pixelfed/pixelfed#1141]
I seem to remember this used to work, but comments from Mastodon no longer show up on Pixelfed. I noticed it with a brief discussion last week, and thought I'd test it again to be sure.

Here's my original post on Pixelfed.social:
https://pixelfed.social/p/KelsonV/22057628964360192

Here's my reply on Wandering.shop (Mastodon):
https://wandering.shop/@KelsonV/101909604851104480
As you can see, the OP has federated to Mastodon, but my reply didn't make it back to Pixelfed.

**Comment by dansup** [comment]
@kvibber I can confirm there is a regression in the ActivityPub logic that is failing to properly store the replies. Working on a fix.

**Comment by kvibber** [comment]
Good to know. Thanks!
