### ISSUE TITLE
Updated profile photos don't federate

### ISSUE THREAD

**Issue by sturmen** [pixelfed/pixelfed#1142]
I use an account on https://pixelfed.social and use a Mastodon account to follow myself. A few days ago I updated my Pixelfed profile photo, but when viewing my profile via Mastodon, it still has my older profile photo. I wasn't sure whether this was a bug on the Pixelfed side or the Mastodon side, but I figured I'd start here.

Thanks for all the hard work!

**Comment by carbontwelve** [comment]
I noticed this too - same with changing public name. 

I wondered whether it was because mastodon aggressively cache the avatars/profile information until prompted to refresh; because my pleroma instances all picked up the changes.
