### ISSUE TITLE
Pixelfed Version in template or header

### ISSUE THREAD

**Issue by shleeable** [pixelfed/pixelfed#1146]
Hey,

I'd love to be able to quickly figure out which version my server is running.... can we get it placed on the primary template? or maybe on the about page?

**Comment by dansup** [comment]
@Shleeble The version is included in the footer!

https://github.com/pixelfed/pixelfed/blob/9f5d31ec01100f4b0e3636ca40582b435899c2a6/resources/views/layouts/partial/footer.blade.php#L11

**Comment by ChameleonScales** [comment]
Nice!
It took me this issue to find it though. I would suggest putting it in plain text directly on the footer.
"Powered by Pixelfed" did not really give me a hint that the version number was hidden as a tooltip.
I mean it's not **that** hidden but I don't think putting it like this would be too ugly:
Powered by Pixelfed (v 0.10.6)
Many websites do it this way (incl. mastodon).
