### ISSUE TITLE
[Docker] New Compose failing with failed images and 401 status

### ISSUE THREAD

**Issue by Shleeble** [pixelfed/pixelfed#1148]
The classic compose works.. the new one fails.

the preview URL results in a 401 Unauthorized.
https://pixelfed.aus.party/i/media/preview/2/33?expires=1555482635&signature=583d3148903a4ca121bb1515203d4b1fefc5d07ebcd346d1209284084ace05e7

<img width="519" alt="image" src="https://user-images.githubusercontent.com/17537000/56263324-1a99b800-6115-11e9-8df0-3247d97137dc.png">

debug
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17537000/56263391-5f255380-6115-11e9-8bd1-6643318b51cf.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17537000/56263399-65b3cb00-6115-11e9-8a2b-e1abef2619de.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17537000/56263410-6c424280-6115-11e9-9c85-d1e378c2a2e7.png">

**Comment by dansup** [comment]
This is likely a misconfigured instance, or permission issues.

**Comment by dansup** [comment]
The solution is to add ```trustedproxy="*"``` to .env, confirmed that it fixed the issue with @Shleeble's instance
