### ISSUE TITLE
[Docker with Postgres] Admin delete user failing

### ISSUE THREAD

**Issue by shleeable** [pixelfed/pixelfed#1149]
As per the video in the riot.

1) https://pixelfed.aus.party/i/admin/profiles/list
2) edit
3) click delete
4) error

trying to delete a user results in a error page with the cat
-> https://pixelfed.aus.party/i/admin/users/moderation/update

**Comment by shleeable** [comment]
https://matrix.org/_matrix/media/v1/download/matrix.org/jbLjrpOGpptCRuAJNjwVZZTM

**Comment by dansup** [comment]
You have to delete a user via CLI
