### ISSUE TITLE
notebook icon confusing

### ISSUE THREAD

**Issue by Sigafoos** [pixelfed/pixelfed#115]
On my timeline the "notebook" icon is clickable but doesn't seem to do anything. There's no indication what it does. From the html it appears to be a permalink but there's no data associated with it.

This is further supported by it not being clickable on a post page.

**Comment by trwnh** [comment]
The notebook is for Saved Posts, and that button is currently broken because you can only save (with no indication), and you can't unsave. Related: #64

**Comment by Sigafoos** [comment]
In that case this is covered by #116 and #64, so I'll close this.
