### ISSUE TITLE
self-diagnosis doesn't error when intl extension is missing

### ISSUE THREAD

**Issue by carbontwelve** [pixelfed/pixelfed#1154]
> Pixelfed: 0.9.0
> PHP 7.3.4

Running `php artisan self-diagnosis` give me `Running check 10/11: The required PHP extensions are installed...  ✔` However I began getting the following error:

> `Call to undefined function locale_get_display_language() (View: /srv/www/pixelfed/resources/views/site/language.blade.php)`

Installing `php7.3-intl` fixes the issue of the undefined function; interestingly the documentation https://docs.pixelfed.org/master/requirements.html#dependencies doesn't seem to mention the need for the intl PHP extension (it may be a normal thing to install.)

I'd like to propose adding the check to `self-diagnosis`, updating the documentation to reflect the requirement and possibly even adding `"ext-intl" : "*"` to the projects composer.json (which would have caught this long before it gave me a 3MB error log)

**Edit**

I just noticed that while the documentation repository does have the _Internationalization PHP Extension_ set as a dependency it doesn't seem to have been deployed to the documentation website.

**Comment by dansup** [comment]
Fixed in #1155
