### ISSUE TITLE
Compose button missing from 600px - 767px

### ISSUE THREAD

**Issue by keverets** [pixelfed/pixelfed#1157]
When viewing https://pixelfed.social/ from my phone (running fennec 66.0.1 from f-droid) with the default mode/theme/etc, there's an action ribbon along the bottom including buttons for "Home", "Timeline", "Post", "Discover", and "Notifications".

However, when using Firefox 66.0.2 on my tablet (viewport of 600x890) that ribbon bar is missing and there's no obvious way to post a photo. I can "Request Desktop Site" at which point it zooms out quite a bit and the ribbon bar will appear on the top-right (between the "Search" bar and the Account button).

Without using the Desktop Site option, I'd expect the ribbon bar to either be at the bottom like on the phone, or in the header on the top-right (though it looks as though there's insufficient size for it to be visible there... maybe it is and it's hidden?)

**Comment by keverets** [comment]
Rotating the tablet does reveal the buttons in the upper right.

**Comment by dansup** [comment]
In addition to the button on mobile/desktop breakpoints, there is a nav menu link in the dropdown.

**Comment by trwnh** [comment]
arguably a nav menu link is not very discoverable...
