### ISSUE TITLE
Icons don't have help text

### ISSUE THREAD

**Issue by Sigafoos** [pixelfed/pixelfed#116]
This seemed different enough from #115 to deserve its own issue.

There are three icons for each image but no indication of what they are or do. 

- The heart meaning "like" is fairly intuitive
- I assume icon-speech is to comment, but there's nowhere that I've found that it's clickable
- As I mentioned in #115 I assume the notebook is for permalink but never seems to work

Regardless of how intuitive these are to someone who works in web development, there need to be aria/etc labels for these icons.

**Comment by faissaloo** [comment]
We should switch the notebook for a floppy disk.

**Comment by dansup** [comment]
Fixed in latest commits
