### ISSUE TITLE
Upload UI broken on many devices

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1160]
Hello,

The upload UI (as in PixelFed v0.9.0) is broken on many devices because of the size of the previews. For exemple it’s completely unusable on iPhone SE.

Thanks in advance for fixing this.

**Comment by ghost** [comment]
Here is a screen record showing this.

![7DBF4F13-1C01-4120-98EB-9E72ED874CB9](https://user-images.githubusercontent.com/41020854/56429260-8f5e2500-62c2-11e9-9fbe-9d5dcfa6aa5f.gif)

**Comment by ghost** [comment]
Another problem with new upload UI — when trying to "click here to add photos" nothing happens. Browser (PaleMoon 28.4.1) console says this:

```
 ReferenceError: event is not defined
Stack trace:
addMedia@https://pixelfed.social/js/compose.js?id=9436fc6ceea845e5bd62:1:10106
click@https://pixelfed.social/js/compose.js?id=9436fc6ceea845e5bd62:1:15355
Vt@https://pixelfed.social/js/components.js?id=7e2c0820d0ca5af5aeaa:1:199039
n@https://pixelfed.social/js/components.js?id=7e2c0820d0ca5af5aeaa:1:200750
qi/o._wrapper@https://pixelfed.social/js/components.js?id=7e2c0820d0ca5af5aeaa:1:235610
  
components.js:1:199376
	Ut https://pixelfed.social/js/components.js:1:199376
	zt https://pixelfed.social/js/components.js:1:199300
	Ht https://pixelfed.social/js/components.js:1:198977
	Vt https://pixelfed.social/js/components.js:1:199152
	n https://pixelfed.social/js/components.js:1:200750
	qi/o._wrapper
```

**Comment by ghost** [comment]
Thanks @dansup it’s working now

**Comment by sefsh** [comment]
Not sure why this was closed. Both bugs, background scrolling and dead image chooser action is very much present on 0.9. iOS 12.3.1, iPhone SE.
