### ISSUE TITLE
Link to "somebody commented on your post" broken

### ISSUE THREAD

**Issue by dadall** [pixelfed/pixelfed#1161]
Issue : 
- Post a photo
- Somebody post a comment
- A notification appears telling you there's a comment
- In that notification, the link to the commented post in broken (404)

**Comment by dansup** [comment]
@dadall Yes there is something strange happening, will investigate!

**Comment by kvibber** [comment]
Has this fix been deployed to pixelfed.social yet? What I'm seeing isn't exactly the same: instead of a broken link, the notification just doesn't link to the post at all.

**Comment by narFnarF** [comment]
The issue still occur on pixelfed.social as of today
https://cdn.discordapp.com/attachments/419947426263072778/580048492865781771/image.png
