### ISSUE TITLE
Usernames seem to be case sensitive - Let's not

### ISSUE THREAD

**Issue by Shleeble** [pixelfed/pixelfed#1177]
https://pixelfed.aus.party/Shlee vs https://pixelfed.aus.party/shlee
I want both of those to work but only Shlee does.... thanks

**Comment by dansup** [comment]
@Shleeble You need to use a case insensitive database collation like ```utf8mb4_unicode_ci```

Example: https://pixelfed.social/dAnSup and https://pixelfed.social/dansup
