### ISSUE TITLE
502 Bad Gateway-error in Nginx?

### ISSUE THREAD

**Issue by olliware** [pixelfed/pixelfed#1178]
As I am currently digging through the install of Pixelfed I finally went the "Composer"-way and the backend work seemed to be okay - no error at the post install. Also the Nginx-installation went well (took the sample configuration from https://docs.pixelfed.org/master/deployment.html) just like the Let's Encrypt-thing.

Unfortunately, each time I try to visit the site I get a "502 Bad Gateway"-error in Nginx. The log tells:

> 2019/04/23 17:08:49 [error] 4479#4479: *4 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: AAA.BBB.CCC.DDD, server: pixelfed.mydevhost.info, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "pixelfed.mydevhost.info"

PHP7.3-fpm is running well with other applications so this cannot be the problem.

Did anyone of you encounter a similar problem or can push me towards the right direction? Any help is appreciated very well - thanks in advance!

Oliver

**Comment by carbontwelve** [comment]
One thing off the top of my head, does `/var/run/php/php7.3-fpm.sock` exist?

What does your nginx config for your pixelfed subdomain look like? Here is mine for comparison:

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.xxx.xxx xxx.xxx;

    root /srv/www/xxx.xxx/httpdocs/public;
    index index.php index.html index.htm;
    client_max_body_size 15M;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php73-fpm-xxx.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    access_log /srv/www/xxx.xxx/logs/access.log;
    error_log /srv/www/xxx.xxx/logs/error.log;

    ssl_certificate /etc/letsencrypt/live/xxx.xxx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xxx.xxx/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
```

**Comment by olliware** [comment]
Yeah, the socket does exist as there are other Nginx-subdomains with applications like Searx or Nextcloud running and using that socket. I went with the original Nginx-configuration from docs.pixelfed.org and adopted just the PHP-version, host and certificates to suit my needs:

> server {
>     listen 443 ssl http2;
>     listen [::]:443 ssl http2;
>     server_name my.pixelfeddomain.tld;
>     root /home/pixelfed/public;
> 
>     ssl_certificate /etc/nginx/ssl/server.crt;
>     ssl_certificate_key /etc/nginx/ssl/server.key;
> 
>     ssl_protocols TLSv1.2;
>     ssl_ciphers EECDH+AESGCM:EECDH+CHACHA20:EECDH+AES;
>     ssl_prefer_server_ciphers on;
> 
>     add_header X-Frame-Options "SAMEORIGIN";
>     add_header X-XSS-Protection "1; mode=block";
>     add_header X-Content-Type-Options "nosniff";
> 
>     index index.html index.htm index.php;
> 
>     charset utf-8;
> 
>     location / {
>         try_files $uri $uri/ /index.php?$query_string;
>     }
> 
>     location = /favicon.ico { access_log off; log_not_found off; }
>     location = /robots.txt  { access_log off; log_not_found off; }
> 
>     error_page 404 /index.php;
> 
>     location ~ \.php$ {
>         fastcgi_split_path_info ^(.+\.php)(/.+)$;
>         fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
>         fastcgi_index index.php;
>         include fastcgi_params;
>     }
> 
>     location ~ /\.(?!well-known).* {
>         deny all;
>     }
> }

May give it a try with your config though, maybe I am still missing something. Thank you so far!

Best regards,

Oliver

**Comment by olliware** [comment]
@carbontwelve Don't know what was different (no real time to check each line) but with your config everything seemed to work the way it should. Now diggin' further as the registration doesn't seem to work yet - need to give this another check. Thanks for your config anyway - this shapens my own tutorial I may share here once it's finished!

Best regards,

Oliver
![Bildschirmfoto 2019-04-27 um 09 44 29](https://user-images.githubusercontent.com/42076599/56846622-aa87f080-68d1-11e9-82f1-19f16d0386d3.jpg)

![Bildschirmfoto 2019-04-27 um 09 47 15](https://user-images.githubusercontent.com/42076599/56846602-7ca2ac00-68d1-11e9-9997-c480fe4cca7a.jpg)
