### ISSUE TITLE
Image Dimensions

### ISSUE THREAD

**Issue by DeadSuperHero** [pixelfed/pixelfed#118]
One interesting problem is that at the moment, different views get slapped with images that are of inconsistent size dimensions. 

For the timeline itself, this isn't much of a problem since the layout largely compensates it. 
![pixelfed](https://user-images.githubusercontent.com/401560/40858192-63a95e6c-6592-11e8-82e9-c86480089cd8.jpg)

For anything containing a grid, though, the lack of visual consistency can look fairly jarring.
![pixelfed](https://user-images.githubusercontent.com/401560/40858230-852416d6-6592-11e8-9ed9-982c5ab792c8.jpg)

Card sizes are handled with the class `.card-img-top`. Unfortunately, this makes visually adjusting the element challenging, as not all views will necessarily treat the element the same way. The post view and timeline view have different layouts than the grid views, and forcing every single view to be the exact same square on the grid can be detrimental to the timeline and post views.

### Solution 1: force all images to be a square aspect ratio
This is probably a straightforward solution, but the downside is that it might negatively affect people who uploaded non-square images already. You'd basically have to enforce some kind of cropping step when it comes to image uploads, which would require a lot more code.

### Solution 2: Use different classes for cards on timeline view / other views
One possible workaround here may be to set up different classes as alternatives to `.card-img-top`, for the purpose of different view types. The stream view might be called `.card-top-stream` where as `.card-top-grid` might apply more to anything that needs to be lined up as a grid of square thumbnails.

An example of how `.card-top-grid` might work would be:
```
.card-top-grid {
height: 300px;
object-fit: cover;
}
```

That would set a square card, and would adjust the image so that it neatly covers the size of the element. It ends up looking like this:

![pixelfed](https://user-images.githubusercontent.com/401560/40859460-c48b8ab2-6596-11e8-818d-ec15c860f204.jpg)

The benefit of doing things this way is that the timeline view and the single-post view remain unaffected by this CSS rule; allowing for PixelFed to have the best of both types of view without obstructing each other.

**Comment by DeadSuperHero** [comment]
The only half-great thing about solution 2 is that the images will still get stretched out to non-square dimensions when the page is at various breakpoints, but tbh it doesn't look horrible as-is.

You could get away with using media queries for those breakpoints to maintain a square aspect ratio at different page widths, if that's something you'd want to investigate. I guess the upside is that it could be optimized for mobile that way.

**Comment by trwnh** [comment]
Solution 2 is probably better in the long run. Square thumbnails enforces conformity in what should be an infinitely scrolling list -- it allows all columns and rows to be the same size. Concerns about cropping should be handled with a "focal point" feature, similar to Mastodon or Koken.

**Comment by dansup** [comment]
I am tracking profile changes in #152

**Comment by jaranta** [comment]
I'm not sure if this is related, but at least this one picture is getting stretched out in the discover view to veeeeery long dimensions. When I look at it in the image view, it shows much shorter version.

Discover view:

![kuvakaappaus - 2018-06-03 13-07-23](https://user-images.githubusercontent.com/5079912/40885475-5d05b2b0-672f-11e8-96bc-df106b0d83c1.png)

Image view:

![kuvakaappaus - 2018-06-03 13-09-07](https://user-images.githubusercontent.com/5079912/40885476-6066d308-672f-11e8-9522-1be2724a1f5f.png)

The image in question: https://pixelfed.social/p/hellcp/1506

**Comment by moshpirit** [comment]
I was going to report the exact same picture here. [Look at the scroll-bar](https://imgur.com/a/dEybaqR).

BTW, Quitim uses [a different format](https://quit.im/main/popular). I think we should crop instead of using this one so we're more coherent with the other styles but it's an idea anyway :) 

![](https://i.imgur.com/qgZueid.png)

**Comment by dansup** [comment]
Fixed in #152
