### ISSUE TITLE
[Enhancement] Support for TOTP

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#1185]
Hello,

The authentification would be more secure if there was TOTP.

**Comment by dansup** [comment]
@stemy2 Pixelfed has supported this for a while.

**Comment by stemy2** [comment]
Why did you removed it ?

**Comment by dansup** [comment]
@stemy2 It has not been removed?

https://github.com/pixelfed/pixelfed/blob/93492f0052dcb1f9396e2912a2b95a9cd4d57dae/app/Http/Controllers/Settings/SecuritySettings.php#L39-L58
