### ISSUE TITLE
Subdirectory in APP_URL is ignored

### ISSUE THREAD

**Issue by efelon** [pixelfed/pixelfed#1188]
Hi,

after following you on friendica for a while I couldn't help myself to try and install my own instance on a raspbian stretch, nginx, php7.3, mariadb combo, since I have this running anyway.

After following mainly [this little](https://github.com/pixelfed/pixelfed/issues/18#issuecomment-394091987) howto I managed to get a test instance running locally. Accessible using a URL like this:  **`http://192.168.0.21:8042`** (`APP_URL=http://192.168.0.21:8042/`)

For the final result I would like to have it in a subfolder of mydomain.de:
**`https://mydomain.de/pixel`**

As first step I tried `APP_URL=https://mydomain.de/pixel` and put a proxy_pass in my main server box. They same schema is used successfully for other web applications (e.g. roundcube) on the same system.

```
location /pixel/ {
	    proxy_pass  http://192.168.0.21:8042/;
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header X-Forwarded-Proto https;
	    proxy_redirect    off;
    }
```

But it looks like this:

![image](https://user-images.githubusercontent.com/10722552/56686790-118c8600-66d5-11e9-876a-388138f33b69.png)

In all URLs like "login" the sub folder "/pixel" is missing.

Best regards
efelon

P.S.: My fist try where the page is displayed correctly I can't register because after pressing "register" on the registry form. The browser is forced to "https" and doesn't complete the registration.

**Comment by dansup** [comment]
@efelon Hi, please make sure you have set the ```root``` directory to the ```public/``` directory. You can see an example nginx config [here](https://docs.pixelfed.org/master/requirements.html#webserver-configuration)

**Comment by efelon** [comment]
I have. This is what I get in the first part of my ticket (working quiet good as it seems):

![image](https://user-images.githubusercontent.com/10722552/56688025-ef483780-66d7-11e9-8c4c-29282dafc8ab.png)

```
upstream php-handler-pixel {
    server unix:/var/run/php/php7.3-fpm.sock;
}

server {
    listen 8042;
    listen [::]:8042;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";


    # Path to the root of your installation
    root /var/www/pixelfed/public;
    index index.php index.html;

    charset utf-8;

    location / {
	try_files $uri $uri/ /$is_args$args;
    }

    location ~ \.php$ {
	try_files $uri =404;
	fastcgi_split_path_info ^(.+\.php)(/.+)$;
	fastcgi_pass php-handler-pixel;
	fastcgi_index index.php;
	include fastcgi_params;
	fastcgi_param SCRIPT_FILENAME $request_filename;
	fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```
But trying to **proxy_pass** there with the config posted above (to get https), I can't get the subfolder "pixel" to work.

I hope this clarifies my problem.
