### ISSUE TITLE
Swiping on mobile doesn't affect numbers

### ISSUE THREAD

**Issue by ahstro** [pixelfed/pixelfed#1191]
If I'm viewing an album, there's a tiny X/Y in the top right corner, showing which image I'm on, e.g. 1/3. If I click the right arrow, the image would transition and the number change to 2/3. If I instead swipe, only the image changes, not the number. Now, if I try to click the arrows, I get some strange behavior, like visually transitioning between multiple images or white space.

Edit: I'm using pixelfed.social, not sure if they're up to date.

**Comment by trwnh** [comment]
Duplicate of #1097
