### ISSUE TITLE
All images broken

### ISSUE THREAD

**Issue by c3x** [pixelfed/pixelfed#1197]
Hi.
All images (post, avatar) are broken.
The images are stored under 

storage/app/public/avatars
storage/app/public/m

but they will be loaded from 
/storage/avatars/
/storage/m/

so all images will be show as broken.

It's an fresh pixelfed installation from today.

**Comment by efelon** [comment]
I believe this #141 should solve your problem.

`php artisan storage:link`

**Comment by c3x** [comment]
Thanks - works now.
