### ISSUE TITLE
proxy_pass to subfolder with nginx, need help

### ISSUE THREAD

**Issue by efelon** [pixelfed/pixelfed#1198]
Hi,

I installed pixelfed successfully for testing locally on a pi (raspbian, mariadb, nginx, php7.3) using the URL: `http://192.168.0.21:8042`
![image](https://user-images.githubusercontent.com/10722552/56688025-ef483780-66d7-11e9-8c4c-29282dafc8ab.png)

I have a central nginx installation which proxy_pass to several other web applications like roundcube or piwigo successfully. That's what I wanted to do with pixelfed. What I did:

1. **Create the config on the https proxy:**
```
location /pixel/ {
	    proxy_pass  http://192.168.0.21:8042/;
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header X-Forwarded-Proto https;
	    proxy_redirect    off;
    }
```
`service nginx restart`

2. **Change APP_URL**
`APP_URL=https://mydomain.de/pixel` i also tried `APP_URL=https://mydomain.de/pixel/`
`ADMIN_DOMAIN="mydomain.de"`
`APP_DOMAIN="mydomain.de"`
`SESSION_DOMAIN="mydomain.de"`
followed by
`php artisan config:cache`

3. **The browser doesn't show any pictures, only text links are presented when I open `https://mydomain.de/pixel`**:
Login points to 
`https://mydomain.de/login` 
instead of 
`https://mydomain.de/pixel/login`

Did I misunderstand the APP_URL usage?
Any help would be appreciated.

**Comment by efelon** [comment]
Little update
Using a subdomain (pixelfed.mydomain.de) instead of subfolder and the same proxy_pass configuration as stated above, everything is working fine.

**Comment by asonix** [comment]
@efelon 

Just so you know, Pixelfed doesn't support 32bit platforms, and you will have issues with status IDs not having enough bits, and overflowing. If you have a pi3 or a pi3+ I would recommend trying a 64bit OS on it, even though they're not as well-supported.

**Comment by efelon** [comment]
@asonix 

Big thanks for pointing out the incompatibility to 32 bit platforms. IMHO this should be one of the first things in the documentation as dependency. 

This would explain occasional URLs trying to refer to negativ hashes like:
`https://pixel.mydomain.eu/p/efelon/-1547563008`
after upload, which throws a "page not found" obviously.

I'm sure a lot of people choose small energy efficient PCs like raspberry for selfhosting. I personally like the well supported raspbian system. I invest enough private time already to be independent with selfhosting basic needs and keeping everything up to date. This inconvenience is a little bit to much for my environment.  In this case, until I find another small scale PC with a well supported 64-bit OS or pixelfed supporting 32 bit platforms, I will uninstall pixelfed for now.

Anyway, what I've seen so far is very impressive and I wish you all the best and great success.

Good luck
efelon

See you around in the Fediverse
P.S.: My test with following users on pixelfed from friendica were successful.

**Comment by asonix** [comment]
@efelon I would personally recommend the Rock64 for a 64bit $35 computer. the ayufan ubuntu build for it works really well in my experience. I'm using two of these right now in my own self-hosting setup, but I don't have a spare one for pixelfed, unfortunately.

**Comment by trwnh** [comment]
>Using a subdomain (pixelfed.mydomain.de) instead of subfolder and the same proxy_pass configuration as stated above, everything is working fine.

Currently I think Pixelfed requires base URL to be a root domain/subdomain, so anyone wishing to use proxy_pass for subdirectories should probably still host pixelfed on a subdomain and just use the appropriate rewrite URLs -- at least, for now. This is because routes currently need to be consistent for many things (API, ActivityPub, etc), and `/storage` is not the same as `/pixel/storage` unless you rewrite the `/pixel` out of the request in nginx while you're passing it.

**Comment by teotikalki** [comment]
So, it's been a year. I just spent a few hours trying to setup PixelFed and in the end I discovered this issue. Any word on progress?
