### ISSUE TITLE
Infinite loading duplicates albums

### ISSUE THREAD

**Issue by ahstro** [pixelfed/pixelfed#1200]
When going to a profile that only has a single album post, like [this one](https://pixelfed.social/reklaim), the post duplicates infinitely. I didn't see this on users with a single regular post, so assuming it has something to do with mismatching when counting posts and images.

This happens on page load. If I keep scrolling, it keeps loading infinitely.
![duplicate-load](https://user-images.githubusercontent.com/3090888/56723869-1f302300-674a-11e9-82ad-6b2795c52acb.png)

Edit: N.B. This happens in my home timeline as well. Assuming `infiniteTimeline` is the culprit, both in [`Profile.vue`](https://github.com/pixelfed/pixelfed/blob/36929de8dabc092375f31e1482bcf5c6e7216f85/resources/assets/js/components/Profile.vue#L582) and [`Timeline.vue`](https://github.com/pixelfed/pixelfed/blob/36929de8dabc092375f31e1482bcf5c6e7216f85/resources/assets/js/components/Timeline.vue#L438). I don't have time to setup my own dev environment right now, so unfortunately can't take a stab at fixing it myself. Hope my investigations helped to some degree and didn't just seem like me trying to be a know-it-all and possibly failing totally :sweat_smile:

**Comment by c3x** [comment]
Same here. Happens also, if user has more than 1 post.

**Comment by dansup** [comment]
@ahstro @c3x Fixed in latest commits!
