### ISSUE TITLE
IPFS support for public media for backups & CDN?

### ISSUE THREAD

**Issue by Mikaela** [pixelfed/pixelfed#1208]
I think if Pixelfed (also?) stored media on [IPFS] and offered the hash somewhere in the UI, users could pin their media for faster access even if the Pixelfed instance was down. If Pixelfed also loaded content from there, [IPFS] users could also function as a CDN for popular content.

[IPFS]:https://ipfs.io/

*I read some of the issue tracker out of curiosity, but I haven't created an account to any instance yet as I don't think I take enough photos so my profile would be just empty unless I restored old Instagram export from time before I removed that account.*

**Comment by dansup** [comment]
@Mikaela We [considered IPFS support](https://mastodon.social/@pixelfed/100060427067278571) early in the project, will be reconsidering it after the v1.0 release.

**Comment by v1rtl** [comment]
Is using IPFS for the content-addressing layer on the table? I'd like to host my photos on IPFS but provide a nice layout of Pixelfed at the same time
