### ISSUE TITLE
Caption limit hit, no warning, cleared what I tried to post/write

### ISSUE THREAD

**Issue by mal0ki** [pixelfed/pixelfed#121]
"The caption may not be greater than 150 characters" Which I wasn't warned about until after I had tried posting a bigger one. And everything was cleared when I tried to post.

Suggestion:
* Character counter / countdown
* Don't clear all the submitted data, ie, save the draft I guess?

Bonus:
* Possibly more than 150 characters, even if the focus is on photos, sometimes we have a lot to say about a work of art, or a photo or something.

![image](https://user-images.githubusercontent.com/28316305/40860005-049dc168-65e4-11e8-9354-8cbb63c942c2.png)

**Comment by trwnh** [comment]
related to #59 (which is for bios instead of captions)
