### ISSUE TITLE
Cannot register

### ISSUE THREAD

**Issue by olliware** [pixelfed/pixelfed#1210]
Thanks to @carbontwelve I managed to finally get my PixelFed-instance running with Nginx. Now I am just struggling to create a user - when registration is open and enabled, I can enter all the desired data and then nothing happens except a page reload.

Installed everything via Composer and running the latest packages. I think I have nearly reached my desired goal but still this register-thing is the last obstacle...

Can anyone of you help here?

Thanks in advance and best regards,

Oliver

**Comment by olliware** [comment]
Is there, BTW, any way to deploy the first user directly with a SQL-statement maybe? 🤔

**Comment by c3x** [comment]
Maybe it helps you

```
id = 1
name = Peter
username = peter
email = peter@peter.peter
status = NULL
password = $2y$10$Gwpg2i/1rw7OrSZQiML0C.Fhpl50.ffCiMsq/Htt0jNdZiaQJ3spq
remember_token = NULL
is_admin = 1
email_verified_at = 2019-04-27 12:12:12
created_at = 2019-04-27 12:12:12
updated_at = 2019-04-27 12:12:12
deleted_at = NULL
2fa_enabled = 0
2fa_secret = NULL
2fa_backup_codes = NULL
2fa_setup_at = NULL
delete_after = NULL
```

Passwort is 123456
is_admin = 1 if user should have admin rights, if not, set to 0

**Comment by olliware** [comment]
@c3x Would have been a great move - unfortunately it doesn't matter when I try to login. Seems as if something in the backend isn't working as expected. At least the frontend is visible now but behind there must be still something broken in my installation. Thanks for the help so far!

Oliver

**Comment by dansup** [comment]
@olliware Please run ```php artisan self-diagnosis```. You can also register a new user using the CLI by running ```php artisan user:create```

**Comment by olliware** [comment]
@dansup The "create"-thing worked quite well, the user has now been added to the database. So far, so good but nothing happens after the login (same as register, a click on the button doesn't kick off any process).

Self-Diagnosis so far on my Debian 9-system:

> |-------------------------------------
> | Common Checks
> |-------------------------------------
> Running check 1/11: App key is set...  ✔
> Running check 2/11: The correct PHP version is installed...  ✔
> Running check 3/11: The database can be accessed...  ✔
> Running check 4/11: All directories have the correct permissions...  ✔
> Running check 5/11: The environment file exists...  ✔
> Running check 6/11: The example environment variables are set...  ✔
> Running check 7/11: Required locales are installed...  ✘
> Running check 8/11: Maintenance mode is not enabled...  ✔
> Running check 9/11: The migrations are up to date...  ✔
> Running check 10/11: The required PHP extensions are installed...  ✔
> Running check 11/11: The storage directory is linked...  ✔
> 
> |-------------------------------------
> | Environment Specific Checks (production)
> |-------------------------------------
> Running check 1/5: Composer dependencies (without dev) are up to date...  ✘
> Running check 2/5: Configuration is cached...  ✔
> Running check 3/5: Debug mode is not enabled...  ✔
> Running check 4/5: Unwanted PHP extensions are disabled...  ✔
> Running check 5/5: Routes are cached...  ✔
> 
> The following checks failed:
> The following locales are missing:
> en_US
> 
> Your composer dependencies are not up to date. Call "composer install" to update them. Do not run Composer as root/super user! See https://getcomposer.org/root for details
> Loading composer repositories with package information
> Installing dependencies from lock file
> Package operations: 0 installs, 0 updates, 32 removals
>   - Uninstalling webmozart/assert (1.4.0)
>   - Uninstalling theseer/tokenizer (1.1.2)
>   - Uninstalling sebastian/version (2.0.1)
>   - Uninstalling sebastian/resource-operations (2.0.1)
>   - Uninstalling sebastian/recursion-context (3.0.0)
>   - Uninstalling sebastian/object-reflector (1.1.1)
>   - Uninstalling sebastian/object-enumerator (3.0.3)
>   - Uninstalling sebastian/global-state (2.0.0)
>   - Uninstalling sebastian/exporter (3.1.0)
>   - Uninstalling sebastian/environment (4.2.1)
>   - Uninstalling sebastian/diff (3.0.2)
>   - Uninstalling sebastian/comparator (3.0.2)
>   - Uninstalling sebastian/code-unit-reverse-lookup (1.0.1)
>   - Uninstalling phpunit/phpunit (7.5.9)
>   - Uninstalling phpunit/php-token-stream (3.0.1)
>   - Uninstalling phpunit/php-timer (2.1.1)
>   - Uninstalling phpunit/php-text-template (1.2.1)
>   - Uninstalling phpunit/php-file-iterator (2.0.2)
>   - Uninstalling phpunit/php-code-coverage (6.1.4)
>   - Uninstalling phpspec/prophecy (1.8.0)
>   - Uninstalling phpdocumentor/type-resolver (0.4.0)
>   - Uninstalling phpdocumentor/reflection-docblock (4.3.0)
>   - Uninstalling phpdocumentor/reflection-common (1.0.1)
>   - Uninstalling phar-io/version (2.0.1)
>   - Uninstalling phar-io/manifest (1.0.3)
>   - Uninstalling nunomaduro/collision (v2.1.1)
>   - Uninstalling myclabs/deep-copy (1.9.1)
>   - Uninstalling mockery/mockery (1.2.2)
>   - Uninstalling hamcrest/hamcrest-php (v2.0.0)
>   - Uninstalling fzaninotto/faker (v1.8.0)
>   - Uninstalling filp/whoops (2.3.1)
>   - Uninstalling doctrine/instantiator (1.2.0)

**Comment by dansup** [comment]
@olliware Sounds like a session issue, did you set the ```APP_DOMAIN``` and ```APP_URL``` in .env and then run ```php artisan config:cache``` ?

**Comment by olliware** [comment]
> @olliware Sounds like a session issue, did you set the `APP_DOMAIN` and `APP_URL` in .env and then run `php artisan config:cache` ?

Yeah, both are set as "pixelfed.mydomain.tld" while the APP_URL is set to "https://pixelfeld.mydomain.tld".

Furthermore,

> SESSION_DOMAIN="${APP_DOMAIN}"
> SESSION_SECURE_COOKIE=true

are set (standard entries in .env.)

**Comment by carbontwelve** [comment]
Are you able to clear the laravel log, repeat the failed action and then share with us the content of the laravel log file (as found in `storage/logs/laravel.log`. That should contain details of the error your seeing.

**Comment by olliware** [comment]
After wiping the laraval log a new one isn't created. The last output from the past one was

> [stacktrace]
> #0 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(28): Illuminate\\Encryption\\Encrypter->__construct('\\x8A\\x05kT\\xE1+\\x17o\\x1C\\xB8\\xD0]'\\xDF\\x8E...', 'AES-256-CBC')
> #1 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(791): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
> #2 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\\Container\\Container->build(Object(Closure))
> #3 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\\Container\\Container->resolve('encrypter', Array)
> #4 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\\Container\\Container->make('encrypter', Array)
> #5 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(929): Illuminate\\Foundation\\Application->make('encrypter')
> #6 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(857): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
> #7 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(822): Illuminate\\Container\\Container->resolveDependencies(Array)
> #8 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
> #9 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array)
> #10 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
> #11 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(215): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
> #12 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
> #13 /home/pixelfed/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
> #14 {main}
> "}

Further upwards, I do also see this message:

[2019-04-27 07:43:47] production.ERROR: The only supported ciphers are AES-128-CBC and AES-

> 256-CBC with the correct key lengths. {"exception":"[object] (RuntimeException(code: 0): The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. at /home/pixelfed/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43)

**Comment by dansup** [comment]
@olliware Looks like an invalid ```APP_KEY``` in .env, to fix please run ```php artisan key:generate``` and then ```php artisan config:cache```

**Comment by olliware** [comment]
> @olliware Looks like an invalid `APP_KEY` in .env, to fix please run `php artisan key:generate` and then `php artisan config:cache`

Did so, @dansup - unfortunately no change. Could the webserver be the reason maybe?

**Comment by olliware** [comment]
Apparently, setting

> RECAPTCHA_ENABLED=

to

"false"

solved the problem. Login and registration is possible now, need top fix the SMTP-settings so far, but this is yet another problem ...

**Comment by olliware** [comment]
As it works, I am closing this for now - thanks for all your thoughts & ideas!

Best regards,

Oliver
