### ISSUE TITLE
Remove the exec function

### ISSUE THREAD

**Issue by shleeable** [pixelfed/pixelfed#1213]
Hey,
we're using exec() to pull the current git commit id.. but for security reasons, I'd just disable exec completely due to the common use with webshells.

The current version is mode than enough for nodeinfo.

**Comment by carbontwelve** [comment]
I agree, from the web side of things. My PHP-FPM pools normally have `exec` disabled; however my command line php doesn't. 

Pixelfed could have a new `cache:version` command added that uses `exec` to grab the git details and cache them for the web side to use if needed. That would remove the need for enabling exec in a web context while keeping the current functionality.

**Comment by shleeable** [comment]
exec() might be used by the composer which is a little bit annoying... composer throws the classic disables out of the window :)

**Comment by shleeable** [comment]
Thanks.
