### ISSUE TITLE
How to launch php artisan horizon on my server ?

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#1220]
Hello,

I created my instance on a Yunohost server. Everything working like a charm but I must to launch php artisan horizon in SSH, and I don't know how to execute it everytime on my server.

I know, it's looks like simple. I tried this from https://olivier.dossmann.net/2018/09/installation-de-pixelfed-une-alternative-%C3%A0-instagram/

![phpartisan](https://user-images.githubusercontent.com/49836486/56926561-4e3fef00-6ad2-11e9-8c6c-8b7c34d52d12.jpg)

But it doesn't work. 

Any idea here ? Thank you, and congratulation for Pixelfed !

**Comment by dansup** [comment]
@raphgilles Hello, please replace ```WorkingDirectory``` and ```ExecStart``` with ```ExecStart=/usr/bin/php /srv/http/pixelfed/artisan horizon```

**Comment by raphgilles** [comment]
Ok, thank you for your answer !

So I have now :

```
[Unit]
Description=Service horizon pour PixelFed
After=network.target

[Service]
Type=simple
User=http
ExecStart=/usr/bin/php7.2 /var/www/pixelfed/artisan horizon
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

/usr/bin/php7.2 is my php directory
 /var/www/pixelfed/ is my Pixelfed directory

But it still don't work.

**Comment by raphgilles** [comment]
That's ok !

I just removed the "User" line. And everything is fine now. Thank you for your help @dansup !
