### ISSUE TITLE
Some hashtags give a «page not found»

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#1248]
Hello,

I searched for some hashtags, but some of them (for exemple, the hashtag «#nsfw») bring me to the «page not found» page, even when the hashtag is not empty.

**Comment by dansup** [comment]
@stemy2 After looking into it, have realized its working as expected. You can only see hashtags that contain at least 1 public post that is not CW'd/NSFW

**Comment by stemy2** [comment]
OK, so if i want to see NSFW or CW post, what must i do ?
