### ISSUE TITLE
Support 32 bit platforms

### ISSUE THREAD

**Issue by efelon** [pixelfed/pixelfed#1253]
Hi,

from the discussion in https://github.com/pixelfed/pixelfed/issues/1198#issuecomment-486696482 I've been told, that 32 bit OSs/Platforms are not supported.

Please see this feature request out of pure admiration to pixelfed being the only successor to sites like instagram and already looking so great I would like to see 32 bit platforms to be supported. I really believe it would widen your future installation base and get you more users. 

I chose raspbian + raspberry pi as my self-hosting system for private purposes, working on and with them now for several years. For me it's just a pity not being able to use pixelfed alongside friendica, nextcloud, gitea, ..., without additional effort.

Only the best wishes and regards,
efelon

**Comment by efelon** [comment]
Hi dansup,

since you closed this issue without comment. Would you mind elaborate a little bit on your decision. If it is still considered, rejected or even already implemented?

Thanks

**Comment by dansup** [comment]
We use 64bit snowflake ids, we cannot support 32bit arch anymore.
