### ISSUE TITLE
Previews are not generated? No Hashtags available?

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1261]
After passing the struggles at the very beginning I now have managed to get my profile working. Apparently, no preview images of the uploaded pictures are being generated. May I fix this somehow by myself or is this a known issue?

![Bildschirmfoto 2019-05-04 um 09 02 02](https://user-images.githubusercontent.com/42076599/57175373-a1f06680-6e4b-11e9-90a3-443fb8897743.jpg)

Additionally the Admin-backend tells me there are no used hashtags although I have used quite a lot in the first four posts. Any ideas on that?

Thanks and best regards,

Oliver

**Comment by c3x** [comment]
@olliware 
See my post at 
#1201 

> Hashtags and create of thumbs are working, when I start manually "php artisan queue:work" from shell.

**Comment by ghost** [comment]
> @olliware
> See my post at
> #1201
> 
> > Hashtags and create of thumbs are working, when I start manually "php artisan queue:work" from shell.

Thanks. The good: It worked although ending in a loop. The bad: "php artisan queue:work" forced the first picture I posted to repeat endlessly. Had this problem with an old install yesterday, now it's back so there's still the need for fixing some basic things... 🤨
![Bildschirmfoto 2019-05-04 um 09 58 35](https://user-images.githubusercontent.com/42076599/57176026-3b6f4680-6e53-11e9-86e4-5267610e247b.jpg)

**Comment by dansup** [comment]
@olliware This has been fixed in the latest commits. Feel free to re-open if you still have issues with this.

**Comment by ghost** [comment]
Does a "composer update" fetch these latest commits? ATM, I did this (and the post-install procedures) and the effect is still there - what am I doing wrong here?

**Comment by Farbod29** [comment]
Has anyone can share to the commit code or the branch for this issue? 

we are a nonprofit research organisation that uses PixelFed in our organisation after installation we have this issue(No preview) in the UI.

**Comment by Mennaruuk** [comment]
Hi @dansup ! I'm still facing the same issue. The image kinda flashes for a second before I see the alt text. Then this "Preview not available" image takes its place. I'm on pixelfed.social.
![image](https://user-images.githubusercontent.com/52135169/110873797-8a346580-82a0-11eb-9211-a100f068a797.png)
