### ISSUE TITLE
Make FontAwesome configurable -- Ability to use newer builds, Pro accounts, or FontAwesome CDN

### ISSUE THREAD

**Issue by lexpierce** [pixelfed/pixelfed#1262]
Sometimes the FontAwesome version built in won't be the latest, won't include all the brands, or just doesn't have the flexibilty desired. Allow users to copy in their own fontawesome assets, or even better, deliver them from the fontawesome CDN if they have it available.

**Comment by trwnh** [comment]
Worth noting that FontAwesome may be removed in a future build; we currently don't use many icons out of it, and the few icons we do use are not always stylistically ideal. FontAwesome is currently used only for rapid iteration, and we are exploring replacing it with SVG icons as we get closer to v1.0 stable release.

**Comment by lexpierce** [comment]
Ok. That makes sense. Thanks!
