### ISSUE TITLE
Sass asset compilation not documented, requires assets outside of code tree

### ISSUE THREAD

**Issue by lexpierce** [pixelfed/pixelfed#1263]
the asset compilation for sass requires elements outside of the code tree (a couple of bootstrap items, plyr, and others).

**Comment by dansup** [comment]
@lexpierce The assets are pre-compiled in ```public/```, they are listed here:

https://github.com/pixelfed/pixelfed/blob/35f0e73b607d79b915ec884b4bc5efb1df3790f0/package.json#L13-L49

To compile them yourself, you need to run ```npm install``` and then ```npm run production```
