### ISSUE TITLE
timeline/public and timeline/personal blade files should be merged

### ISSUE THREAD

**Issue by andriussev** [pixelfed/pixelfed#128]
Most of the logic is the same, and there does not seem to be a big reason why that would change soon.

Parts of those files could be extracted and used to keep the templates tidier. DRY!

https://github.com/dansup/pixelfed/blob/dev/resources/views/timeline/personal.blade.php
https://github.com/dansup/pixelfed/blob/dev/resources/views/timeline/public.blade.php

**Comment by dansup** [comment]
Fixed in latest commits
