### ISSUE TITLE
[Feature] Mobile Application

### ISSUE THREAD

**Issue by asddsaz** [pixelfed/pixelfed#1280]
**Feature**: Dedicated FLOSS mobile application for all major platforms
(Android, IOS, Ubuntu Touch, Sailfish OS, e.c.t).

_______

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/73845285-feature-mobile-application)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by trwnh** [comment]
This is out of scope for this repo, which pertains only to the Pixelfed server. Once APIs are implemented, various community members have already expressed interest in developing applications for Pixelfed.
