### ISSUE TITLE
Endless pictures still looping...

### ISSUE THREAD

**Issue by olliware** [pixelfed/pixelfed#1283]
As @dansup stated in https://github.com/pixelfed/pixelfed/issues/1261#issuecomment-489498836 this should already been fixed. How may I fix this with my instance? Pictures are still repeating and repeating and I don't know how to change that...

Thanks in advance,

Oliver

**Comment by trwnh** [comment]
What is the output of `php artisan horizon:status`? What do you see in the dashboard at `domain.tld/horizon`?

**Comment by olliware** [comment]
> What is the output of `php artisan horizon:status`? What do you see in the dashboard at `domain.tld/horizon`?

Just tried this with a new install - by default, the website couldn't be reached. After doing

`php artisan horizon:install` and
`php artisan horizon:assets`

at least the website /horizon was reachable (didn't knew it exists anyway ;-) ) ! Tasks like uploading and optimizing an avatar were logged there - connection seems to work though!

![Bildschirmfoto 2019-05-12 um 08 49 22](https://user-images.githubusercontent.com/42076599/57578786-f40c3a00-7492-11e9-9e73-20e25cfe8820.jpg)

Besides, `php artisan horizon:status` just shows

Horizon is inactive.

Is this an error?

Thanks in advance,

Oliver

**Comment by trwnh** [comment]
OK, I think I ran into this on a test setup. You need to be running Horizon as the same user as PHP / WWW. By default, running Horizon in a terminal will probably run it as the user you're currently logged in as. I think the Docker image runs everything as the user `pixelfed`, whereas most systems will probably be running under something like `http` or, if using systemd services, the system.slice (basically limited `root`).

Assuming you use systemd to manage services like `nginx`, `php-fpm`, `redis`, and `mysql`/`mariadb`, you could probably use something like this:

`$ cat /etc/systemd/system/pixelfed.service `
```
[Unit]
Description=Pixelfed task queueing via Laravel Horizon
After=network.target
Requires=php-fpm.service
Requires=redis.service
Requires=mariadb.service
Wants=nginx.service

[Service]
Type=simple
ExecStart=/usr/bin/php /srv/http/pixelfed/artisan horizon
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by olliware** [comment]
Sounds like an idea. On my Debian 9-system I tried

`sudo -u www-data php artisan horizon`

and indeed some jobs were processed. I'll give it a try with the service, at least I am turning into the proper direction now - thanks 👍 !!!

Oliver

**Comment by olliware** [comment]
Small update: That did it, after enabling the service, reloading the systemd-daemon via `systemctl daemon-reload` the whole thing worked directly after starting the system. Thanks @trwnh!!
