### ISSUE TITLE
Not possible to scroll through filters in the new ComposeUI on Chrome

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#1285]
OS: Windows 10 (will check on Linux later)
Instance: Pixelfed.Social
Browser: Google Chrome 74

There is no horizontal scrollbar to scroll through filters in the new ComposeUI
![2019-05-11_19-35-10](https://user-images.githubusercontent.com/2780044/57572920-e1114f80-7429-11e9-9618-768a61d07ba9.png)

However there is a scrollbar on Firefox (latest):
![2019-05-11_19-36-10](https://user-images.githubusercontent.com/2780044/57572923-e9698a80-7429-11e9-820f-4787c1840264.png)

By the way, classic uploader doesn't show uploaded image (but can post it) with both Firefox and Chrome

**Comment by dansup** [comment]
@MasterGroosha The scroll bar is intentionally hidden.

https://github.com/pixelfed/pixelfed/blob/16d8a2d7be20fe4379e717fcbe13b9e8b00d5bcc/resources/assets/js/components/ComposeModal.vue#L219-L221

**Comment by MasterGroosha** [comment]
Then how one is supposed to scroll through filters?
Without scrollbar, user cannot select most of filters

Edit: Tested this on Chromium on Linux as well. Without scrollbar, it's not possible to select the desired filter from the end of filters list.

**Comment by MasterGroosha** [comment]
@dansup I think you've closed the issue too early. 
Tested this on Chromium on Linux as well. Without scrollbar, it's not possible to select the desired filter from the end of filters list.

**Comment by MasterGroosha** [comment]
For anyone else who comes to this issue: in the meantime you can use this userscript for [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) to return filters scrollbar and be able to select _any_ filter, not first five:

https://gist.github.com/MasterGroosha/4c4f0bda7f43dc545227fa9a1a95a9db/raw/c545df5cfa225863479033928bd6e6ce28bedafc/return_filters_scrollbar.user.js 

![screenshot](https://user-images.githubusercontent.com/2780044/57692482-8bb68780-764f-11e9-87f3-00d250ac1d04.png)

I greatly appreciate @dansup's work on Pixelfed, it's awesome, however I still don't understand his desire to break filters selection for PC users without touchscreens. Anyway, it was fun to play with Tampermonkey

**Comment by trwnh** [comment]
If Chrome users can't scroll at all then this is definitely a bug. I'll take a look at why

**Comment by MasterGroosha** [comment]
@trwnh I've encountered such behaviour with Google Chrome 74 (maybe also 73) on Windows 7, Windows 10 and Manjaro KDE latest.
The only way to scroll now is to click on filter and then use left/right arrows (which is really simulating scrolling).

**Comment by trwnh** [comment]
@MasterGroosha I'm able to scroll on a laptop touchpad and on a phone, but I'm not able to reproduce the arrow key behavior unless I click on the filter name instead of the preview. Going to try on an actual mouse when I get to my desktop.

**Comment by trwnh** [comment]
Hmm, looks like it's technically possible on desktop if you click the middle mouse button and drag, but this is not intuitive at all. The scrollbar should definitely be visible, at least on desktops / non-touchonly devices.
