### ISSUE TITLE
SMTP-Settings in .env-File

### ISSUE THREAD

**Issue by olliware** [pixelfed/pixelfed#1288]
Hey everyone,

as I am continuing my PixelFed-voyage step by step (with increasing success thanks to the help here) I was still wondering how I may configure the SMTP-Settings in the .env-file. All tries of getting SSL (465) / TLS (587) to work so far didn't work out so I wonder if these parameters need to be tuned somehow... The standard is

> MAIL_DRIVER=log
> MAIL_HOST=smtp.mailtrap.io
> MAIL_PORT=2525
> MAIL_USERNAME=null
> MAIL_PASSWORD=null
> MAIL_ENCRYPTION=null
> MAIL_FROM_ADDRESS="Pixelfed@example.com"
> MAIL_FROM_NAME="Pixelfed"

as far as the .env-file goes. Which values can I use for `MAIL_ENCRYPTION`? The `MAIL_DRIVER` is set to "smtp" BTW.

Best regards,

Oliver

**Comment by dansup** [comment]
@olliware Hi, please check the [mail config](https://github.com/pixelfed/pixelfed/blob/dev/config/mail.php).
