### ISSUE TITLE
Following from Mastodon

### ISSUE THREAD

**Issue by olliware** [pixelfed/pixelfed#1289]
Hey folks,

when searching my PixelFed-account from my Mastodon-instance, the account is displayed. When I try to follow, Mastodon tells me that the PixelFed-user needs to give his okay.

The parameters 

```
ACTIVITY_PUB=true
REMOTE_FOLLOW=true
```

are set, also 

```
php artisan cache:clear
php artisan optimize:clear
php artisan optimize
```

have been started after doing this change. Anyway, my PixelFed-user gets no message that he should acknowledge the follow.

Any ideas on that?

Thanks in advance,

Oliver

**Comment by dansup** [comment]
@olliware Run ```php artisan config:cache``` every time you update the ```.env``` file.

**Comment by olliware** [comment]
> @olliware Run `php artisan config:cache` every time you update the `.env` file.

Year, that‘s standard but doesn‘t answer my question. Did this quite a lot of times and (of course) with each change - but well, no notification between the instances...
