### ISSUE TITLE
Validate a pending account in command line ?

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#1291]
Hello,

I have a problem with my instance : I don't know why, but I have some error pages on. I think because I try the Yunohost package, so I prefer to wait the v1 to ask for help.

BUT I tried to change the admin mail today, and I discover a new error page (with the cat) when my instance send an email.

I will search for a definitive solution after the v1 if it's still here, but have I a way to force the validation in command line ? :)

Thank you !

(oh and yes, if you have the time, I can't change avatars too. Same page with the cat.)

**Comment by trwnh** [comment]
I think you can do `php artisan user:create`

**Comment by raphgilles** [comment]
So, I have this error.


`PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE)                                in /var/www/pixelfed/vendor/zendframework/zend-diactoros/src/functions/marshal_u                               ri_from_sapi.php on line 83`

**Comment by dansup** [comment]
@raphgilles Please make sure you are running PHP 7.1.3 or later.

**Comment by raphgilles** [comment]
I'm running PHP 7.2.17
