### ISSUE TITLE
Allow licensing own photos

### ISSUE THREAD

**Issue by nicolasmaia** [pixelfed/pixelfed#13]
It'd be nice to be able to release images under a free license that the user can choose from.

**Comment by NFGman** [comment]
A similar discussion was had with regards to Mastodon.  

https://discourse.joinmastodon.org/t/adding-a-default-content-license-for-toots/555/9

Licensing is good, but it has a big impact on new non-savvy users.  The UI becomes more complicated, the smooth user experience is impacted as they're forced to consider things they've probably never, ever given thought to.  

There's obviously no enforcement mechanism, all you need is one rogue instance and all bets are off.

A network-wide license will certainly not work.  Per-user would require more from most users of any social network than they're prepared to commit.  

Perhaps a default license for all posts made on one instance.  That'd make it easy to have a hover-over for images, and the download button could have "Sure you can save this, but do you understand the license?" speedbumps.  New users could have a simple clickthrough "All posts made here are published under this license" etc.

**Comment by nicolasmaia** [comment]
@NFGman maybe a good compromise would be to have the admin option to set a default license for the whole instance, and an option for users to override these and choose their own. That way you don't have to grapple with these concepts unless you see them as options in a settings page.

**Comment by colegota** [comment]
Licensing is not good, it's necessary. First because admins can be forced to respond to claims about proprietary issues, and second because many of us try to improve the world with our own works, the free/libre ones.

I think the admin must have the ability to choose the default license and maybe the users specify another one from a list of allowed licenses.

And to avoid federation problems where a picture can be shown in a node that has a different license will be great if license it's shown always close to the image. Just in small format.
This will be nice too to show users the need and the relevance of license/permisions/copyright/copyleft.

**Comment by joachimesque** [comment]
I also think that licensing is necessary.

As an example, Flickr users can set their pictures’ licences, as a global default setting for all new uploads, and on a photo-to-photo basis.

In the settings
![image](https://user-images.githubusercontent.com/1781070/41194893-58a2f072-6c23-11e8-8780-0dc1108a3994.png)

The page is really well done to explain why it's important

![image](https://user-images.githubusercontent.com/1781070/41194918-cf246956-6c23-11e8-9375-c105f399279a.png)



And here is the photo-by-photo setting at upload time:
![image](https://user-images.githubusercontent.com/1781070/41194858-abef13ec-6c22-11e8-815b-f2577019e804.png)

Or after the upload:
![image](https://user-images.githubusercontent.com/1781070/41194876-00ba7d12-6c23-11e8-8736-975053f7e5ab.png)
![image](https://user-images.githubusercontent.com/1781070/41194863-cdeca356-6c22-11e8-9ecd-98039737ca8e.png)

**Comment by dansup** [comment]
The problem with this is federation. I would rather just have users include the licence in the caption.

**Comment by gegeweb** [comment]
On peertube you can choose the licence. And it is feterated with the json, licence is a property of object.
It would be nice, on user preference, to choose a default licence.

**Comment by dansup** [comment]
I am looking into supporting this feature after realizing that peertube uses it.

**Comment by mike-burns** [comment]
Here's the stalled PR for Mastodon for licenses on statuses: https://github.com/tootsuite/mastodon/pull/5820 .

I'm interested in what you add here (and how PeerTube does it?) for when I resume work on that patch.

**Comment by dansup** [comment]
Added in latest commits.

**Comment by ghost** [comment]
So finally was this implemented? So can I specify the license?
Since, I would like to pick a service like that. Do you know any alternative to Flickr - where I can specify license?
