### ISSUE TITLE
I'm sorry - I have no idea how to start Pixelfed

### ISSUE THREAD

**Issue by dln949** [pixelfed/pixelfed#1307]
Running Ubuntu 18.04.2.  

Downloaded the tar.gz file found here:  [https://github.com/pixelfed/pixelfed/releases/tag/v0.9.0](url) .  

I extracted the directory contained within the tar.gz file.  

Now what do I do?????  How do I start Pixelfed?  I don't see an executable file.

**Comment by trwnh** [comment]
You would need to configure your web server and PHP to point to the directory. Pixelfed is a PHP app.
