### ISSUE TITLE
Apostrophe in comments rendered as &#039;

### ISSUE THREAD

**Issue by voss** [pixelfed/pixelfed#131]
As subject, looks like encoding issue. Example here: https://pixelfed.social/p/y6nH/871

![screenshot 2018-06-02 at 00 55 39](https://user-images.githubusercontent.com/10601/40867919-13cc77b2-6600-11e8-96fe-c88d791db788.png)

**Comment by Skehmatics** [comment]
Using the good 'ol inspect element, it seems like the automatic hashtag link creation is interpreting the HTML entity as a hashtag

![image](https://user-images.githubusercontent.com/5824729/40871653-72fe8bdc-65f4-11e8-98fc-c39a2bf731dd.png)

**Comment by Grazouillis** [comment]
If you use `&apos;` instead `&#039; ` for apostrophes, the code won't take that as hashtags.
