### ISSUE TITLE
Profile page don't load after upgrade

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#1318]
Hello,

I have a problem with my Pixelfed instance. When I upgrade to the 0.9 version the profile pages don't load and stay empty.
Same issue with the single publications page.

So I waited a new version to upgrade, but on my 0.8.6 an user broke his profil by sending a large file : https://pixelfed.fr/julienlecomte
I think it's the same issue so we can work on.

I tried the php artisan purge / optimise ect... commands. Change nothing.

My server is on stretch, php 7.2, prostgres 9.6.13, Laravel 5.8.14.

**Comment by dansup** [comment]
@raphgilles Please update to the latest commit

**Comment by raphgilles** [comment]
Yes but let's take a look. I upgraded for you, and now every profil don't load :
- https://pixelfed.fr/raph
- https://pixelfed.fr/stunt4ever
- https://pixelfed.fr/pixelfed
- ect

And also all single post page :
- https://pixelfed.fr/p/raph/38194248859914240
- https://pixelfed.fr/p/pixelfed/38028089535631360
- https://pixelfed.fr/p/stunt4ever/37942595795685376

But the homepage / public timeline / discover pages works.

**Comment by dansup** [comment]
@raphgilles You are not running the latest commits, v0.9.0 is old. Please run ```git pull``` and then run the [post deployment commands](https://docs.pixelfed.org/master/deployment.html)
