### ISSUE TITLE
Disallow search when there is no search query

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1322]
Clicking on the search icon at the top with blank field will show the following message:

The q field is required.

**Comment by okpierre** [comment]
This issue is not fixed. Please reopen

You can test by going to Settings page and then click on the search button

you will see this
![pixelfed-q-field-is-required](https://user-images.githubusercontent.com/1679025/59660884-96e16380-9177-11e9-8fc3-82968d250427.png)

**Comment by dansup** [comment]
@okpierre Okay it has been fixed in the latest commits!
