### ISSUE TITLE
Ability To Add List of Restricted/Reserved Usernames

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1324]
ability for admin to add list of restricted/reserved usernames

this will prevent anyone from registering them

for example: support, help, admin, administrator, etc

each instance may want their own custom list

**Comment by trwnh** [comment]
Already implemented! https://github.com/pixelfed/pixelfed/blob/dev/app/Util/Lexer/RestrictedNames.php

**Comment by trwnh** [comment]
I can reopen the issue if you want another way for admins to manage this, e.g. via environment variables or an admin page.

**Comment by okpierre** [comment]
Will the file be overwritten with each update if admin edits the file?

**Comment by trwnh** [comment]
It shouldn't be if the admin commits the change to their local git repository, I think. @dansup?
