### ISSUE TITLE
Support text-only posts

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1325]
Instead of posting image sometimes just text will do.

Click on text icon, type out text, select background color, submit

Hope that makes sense

**Comment by trwnh** [comment]
Pixelfed is targeted toward a media-only experience, so this is out-of-scope. However, there are still discussions around how best to handle text from other services.

**Comment by okpierre** [comment]
Example: inspirational message, greeting, quotes, etc.

So instead of creating an image with photoshop, adding text over the image and then uploading it

![evensaltlookslikesugar](https://user-images.githubusercontent.com/1679025/58749209-2507db00-8451-11e9-9619-17c937a6e0e7.png)

this can be created by simply typing text and submitting
