### ISSUE TITLE
Create video posts from URL to video

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1326]
Sometimes you might just want to share a video

Click on video icon, paste link to supported network, submit

Video will now be part of the feed!

What do you think?

**Comment by trwnh** [comment]
Do you mean sharing video posts that are hosted on other platforms?

**Comment by dansup** [comment]
You can upload video by adding ```video/mp4``` to .env ```MEDIA_TYPES```

**Comment by okpierre** [comment]
@trwnh @dansup 

Instead of uploading a **large** video, I'm suggesting an option to share a video from vimeo, youtube, etc. as a pixelfed post

Example: make up tutorial, plumbing tips, bike fixing, etc

**Comment by trwnh** [comment]
OK, that's what I thought you meant. I'll reopen this unless @dansup wants to close it as a wont-fix.

**Comment by dansup** [comment]
@okpierre @trwnh Oh my bad, yes import from YouTube and Coub is on the roadmap.

**Comment by okpierre** [comment]
Wonderful! Another way to be glued to pixelfed! :)

**Comment by adelorenzo** [comment]
> You can upload video by adding `video/mp4` to .env `MEDIA_TYPES`

hey dansup. thank you for the tip. when I add MEDIA_TYPES=video/mp4 to the .env file I can **only** upload videos. if I remove the MEDIA_TYPES from .env I can **only** upload pictures... What am I doing wrong? please help. thank you.

**Comment by ketsapiwiq** [comment]
@adelorenzo According to [this line](https://github.com/pixelfed/pixelfed/blob/1f042dd02f7f8bcf3e398f48ddd568a362103110/config/pixelfed.php#L233) `    'media_types' => env('MEDIA_TYPES', 'image/jpeg,image/png,image/gif'),` in config you should do:
`MEDIA_TYPES=image/jpeg,image/png,image/gif,video/mp4`
