### ISSUE TITLE
Do Not Show Unlisted Media To Non Owner

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1337]
-Add media, choose unlisted, upload
-Logout
-Browse profile
-Media is displayed

**Only the owner** and anyone with URL can view or share but that's not the result with version 0.9.4 

Guests and members should not be able to discover unlisted media under any profile

Am I understanding the term **_unlisted_** incorrectly?

**Comment by dansup** [comment]
Unlisted means unlisted from timelines. Private posts are Followers Only

**Comment by trwnh** [comment]
"Unlisted" currently means the same as Mastodon (shown only in profile and in followers' home feeds), not the same as YouTube (accessible only via direct URL). I agree it's a bit confusing though. #939

**Comment by okpierre** [comment]
@dansup @trwnh 

I would like to suggest an option for unlisted (as in youtube or vimeo)

A way for pixelfed to be used as the 'go to' media share

example scenarios:
-upload unlisted sketch or design and share link to **manager** for approval
-upload unlisted beta video and send link to **beta department** for approval
-upload unlisted photos and provide link to **certain** family members or friends
 
It's one of the reasons why people on IG create different accounts with different permissions. Hopefully those scenarios give a better reason for granular privacy and a chance for pixelfed to be different from IG. 

Just my thoughts. Maybe there is a better way?
