### ISSUE TITLE
Fixed Grid Dimensions To Prevent Uneven Layout

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1339]
When browsing discover loops page I'm imagining when members create long tags or description and causing a messy grid layout. Imagine a media with 30 tags? 

Would it be better to start the fold below the title? Thoughts?

Here's a screen shot:

![pixelfed-loops-grid](https://user-images.githubusercontent.com/1679025/58843720-bfc70c00-8641-11e9-80c6-c03a41352b36.png)

**Comment by dansup** [comment]
Fixed in latest commits

**Comment by okpierre** [comment]
Awesome! Thanks!!
