### ISSUE TITLE
Vue Infinite Loading Error

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1350]
When loading a page getting the following error

executed the callback function more than 10 times for a short time, it looks like searched a wrong scroll wrapper that doest not has fixed height or maximum height, please check it. If you want to force to set a element as scroll wrapper ranther than automatic searching, you can do this:

```
<!-- add a special attribute for the real scroll wrapper -->
<div infinite-wrapper>
  ...
  <!-- set force-use-infinite-wrapper -->
  <infinite-loading force-use-infinite-wrapper></infinite-loading>
</div>
or
<div class="infinite-wrapper">
  ...
  <!-- set force-use-infinite-wrapper as css selector of the real scroll wrapper -->
  <infinite-loading force-use-infinite-wrapper=".infinite-wrapper"></infinite-loading>
</div>
    
more details: https://github.com/PeachScript/vue-infinite-loading/issues/55#issuecomment-316934169 components.js:1:48566
    track https://localhost/js/components.js?id=25d082643150ee79150c:1
    track https://localhost/js/components.js?id=25d082643150ee79150c:1
    attemptLoad https://localhost/js/components.js?id=25d082643150ee79150c:1
    ee https://localhost/js/components.js?id=25d082643150ee79150c:1
    Kt https://localhost/js/components.js?id=25d082643150ee79150c:1
```

​

**Comment by dansup** [comment]
This looks like a deployment issue. 

What page is this happening on?

**Comment by fharper** [comment]
I have this issue on the homepage if there is less than 6 media displayed, or if I scroll down, the app is trying to fetch more. It also causes a 429 at some point since it's looping calls to the api.
