### ISSUE TITLE
"Enable Infinite Scroll" is not persistent

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1351]
Click on the gear, click on Enable Infinite Scroll and then visit another page

Enable Infinite Scroll is switched on again

![pixelfed-enable-infinite-scroll](https://user-images.githubusercontent.com/1679025/58922669-ddf83f00-8709-11e9-8372-e05f6b71099d.png)

**Comment by trwnh** [comment]
possibly similar to #933? @dansup

**Comment by dansup** [comment]
That has been removed in the latest commits. Infinite scroll is the default and we have deprecated the load more button.
