### ISSUE TITLE
Show filter preview strip when editing existing posts

### ISSUE THREAD

**Issue by efelon** [pixelfed/pixelfed#1358]
pixelfed 0.9.4 on ubuntu 64 bit with nginx and php7.2

It would be nice to have a filter preview similar to the compose UI when editing existing posts. Now there is only a drop down with available filter names.

![image](https://user-images.githubusercontent.com/10722552/58942410-fdc94a80-877d-11e9-8d48-c7d1ed70cd7e.png)

It would be enough for me if the selected filter would be previewed on the image.

**Comment by dansup** [comment]
Fixed in Compose UI v4
