### ISSUE TITLE
Discover page not displaying album pictures (category view)

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#1359]
Hi,

On my instance, I have set up a number of discover categories and in each of them the _number of posts_ value is equivalent to the number of pictures in the related hashtags but does not display photos if they are part of an **album**.

For example, the result is that whilst the discover page for "Craft Beer" says that it has 4 posts, only 1 picture is actually displayed. (screenshot attached).

![Screenshot from 2019-06-05 09-39-31](https://user-images.githubusercontent.com/51400674/58942710-32d19f00-8776-11e9-9894-62d2f282f17b.png)

**Comment by trwnh** [comment]
Is this still happening?

**Comment by jk-na** [comment]
Yes, just checked the discover categories and they still do not display album photos and the post count doesn't match the number of displayed images.
