### ISSUE TITLE
.svg's do not preview properly

### ISSUE THREAD

**Issue by oct2pus** [pixelfed/pixelfed#136]
3 of these are SVGs
![image](https://user-images.githubusercontent.com/30452393/40871196-cac2396a-65fc-11e8-8c8d-ec51f9a0e928.png)

here is what top left looks like when I actually enter a post's view
![image](https://user-images.githubusercontent.com/30452393/40871204-e7c05bf0-65fc-11e8-852d-e048e8436bcb.png)

thank you for supporting SVGs, thats unexpected and nice!

**Comment by dansup** [comment]
It looks like the thumbnail job is not working properly. I will investigate.

**Comment by trwnh** [comment]
@dansup it seems to sometimes fail in other ways as well (#67), but in that case it seems to be resolved after some time.

**Comment by kpcyrd** [comment]
svg support is something we might want to drop for security reasons. :/

**Comment by oct2pus** [comment]
why is that? I quite like it because it allows me to share the highest quality versions of vectors without having to relink it to another site.

**Comment by dansup** [comment]
@oct2pus As @kpcyrd pointed out, SVG's are a security concern. They are no longer supported by default.
