### ISSUE TITLE
Deleting a post from permalink/profile does not remove it from timeline until refresh

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1368]
### Steps to reproduce
1. Make a post
2. Go to the post page
3. Delete the post
4. Get automatically taken back to the timeline

### Expected behavior
The timeline should be regenerated

### Actual behavior
The timeline still shows the deleted post until the timeline is refreshed

**Comment by dansup** [comment]
@trwnh This is a race condition, the StatusDelete job isn't finished before the redirect is fired. I will add a delay to the redirect/success message.
