### ISSUE TITLE
Add "delete" functionality to profile page 

### ISSUE THREAD

**Issue by markusg17** [pixelfed/pixelfed#1369]
Need delete button for profile pag to delete photos

**Comment by trwnh** [comment]
I'm not sure what this means. You can already delete photos from the profile by clicking on them then the menu icon and "Delete". Do you mean deleting multiple photos at the same time?

**Comment by dansup** [comment]
<img width="1016" alt="Screen Shot 2019-06-09 at 11 20 25 AM" src="https://user-images.githubusercontent.com/877217/59162102-a2ae9500-8aa8-11e9-9aaf-396b06bb1a3b.png">
