### ISSUE TITLE
[Feature] PixelFed over i2p

### ISSUE THREAD

**Issue by hgjkhg** [pixelfed/pixelfed#1370]
**Objective**: Enabling PixelFed to be used fully over i2p (+ documentation)

**Discussion**: What would it take to run an PixelFed instance with i2p?
Is there an i2p instance for PixelFed? Could it communicate with non-i2p instances?

**Why?**: Mainly for privacy and security but also to promote decentralized web communications.

**Related Links**:
https://www.invidio.us/watch?v=2ylW85vc7SA

https://geti2p.net/

https://git.pleroma.social/pleroma/pleroma/wikis/I2P-Federation

https://www.wikipedia.org/wiki/I2p
_____________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75179210-feature-pixelfed-over-i2p)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by dansup** [comment]
We have no plans to support i2p.
