### ISSUE TITLE
Logged out users see 403 Forbidden when browsing hashtags

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1383]
Click on any hashtag and get 403 Forbidden Error

Can see error using this link 
https://pixelfed.social/discover/tags/pano?src=hash

**Comment by dansup** [comment]
This is intentional. Discover content requires you to be logged in.

**Comment by okpierre** [comment]
@dansup 

- Does this mean you are taking a different approach compared to IG? 
For example IG shows discover for guests: https://www.instagram.com/explore/tags/instagram/

- If so, can this issue be reopened so pixelfed can display a friendlier message instead of 403?

**Comment by realityfabric** [comment]
I agree, this issue should be reopened until the visitor gets a more helpful message. As it is the only content is "403: Forbidden", which doesn't tell me how to fix the problem (or if I can fix it).

I ran into this problem when I was viewing someone's photos and clicked on a hashtag. It linked me to the proper address, and gave me the 403.
