### ISSUE TITLE
Support SMS Mobile Number Verification

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1385]
Support for additional verification via SMS mobile number verification

Add mobile number, receive text, input number from mobile, confirm account

Another layer of security

**Comment by Whaxion** [comment]
It's interesting, but it would need external paid api, so I'm not sure that every instance admin would use that.
And I'm also not really sure that everyone will be okay to give phone number to have access to a pixelfed account

**Comment by okpierre** [comment]
If enabled, option for user to add number similar to other networks - user choice :)

**Comment by trwnh** [comment]
tentatively against this -- it would require not only paid integration with some sms api provider, but it would also require pixelfed instances to ask for / know user phone numbers (especially if you want users to be able to login with their numbers!)

and frankly, better standards already exist. why add dependency on the phone network? email / totp works.

**Comment by okpierre** [comment]
Similar to twitter where you are already signed up and have an account. **_Option_** to add mobile number afterwards to be used for verification and not for login.

**Comment by dansup** [comment]
SMS Verification does not align with our goals of Privacy and Security. We will not implement this.
