### ISSUE TITLE
Change the name of the site / instance

### ISSUE THREAD

**Issue by lesamarien** [pixelfed/pixelfed#1389]
Hello

I would like to know how to change the App Name / Site Name.

Apparently, we can not change it yet in the interface.

I am in version 0.9.4

Thank you for your help

**Comment by trwnh** [comment]
Edit your .env file and change `APP_NAME` to whatever you wish, then run `php artisan config:cache` for changes to take effect.

Admin interface for changing config is currently being worked on, btw!
