### ISSUE TITLE
PNGA (Animated) got frozen

### ISSUE THREAD

**Issue by rhaamo** [pixelfed/pixelfed#139]
Uploaded a PNGA, it seemed to display properly then at some point, after resizing/transformation I guess, It just froze one one frame and shows like that.

Background issue is duplicate of #45 
PNGA (Animated) got frozen would be this issue.

![image](https://user-images.githubusercontent.com/8625/40872256-645c3456-664b-11e8-9a41-54ff1bb40265.png)

**Comment by MasterGroosha** [comment]
Can confirm. Same for me.

**Comment by kpcyrd** [comment]
This issue duplicates #45, closing in favour of the other bug :)

**Comment by rhaamo** [comment]
The background issue is a duplicate, the fact that the PNGA (A for Animated) got still is another, and not duplicate but ok I will open another one then..

**Comment by kpcyrd** [comment]
I assumed A is for alpha channel, I've reopened the issue, sorry. :)

**Comment by rhaamo** [comment]
@kpcyrd I edited to add the duplicate about background and explicitely mentioned the frozen and animated bit.

**Comment by dansup** [comment]
Fixed in b437b62
