### ISSUE TITLE
Notifications do not work with the admin account

### ISSUE THREAD

**Issue by lesamarien** [pixelfed/pixelfed#1391]
Hello

I am in version 0.9.4 and the Notification part does not work with my admin account but works with a simple account.

There, I do not understand.

Thank you for your help

**Comment by raphgilles** [comment]
I have the same issue, and a friend of mine on his instance too.
And not only with the admin account.

**Comment by olliware** [comment]
Same problem than here? https://github.com/pixelfed/pixelfed/issues/1348

Haven't tried it with a non-admin-account so far 🤔 ...

**Comment by oufmilo** [comment]
Yes, i think it's the same problem @olliware 
I try with non-admin-account and it's the same notifications doesn't work

**Comment by dansup** [comment]
@lesamarien This is a deployment issue, Notifications work fine on my instance for admins and non-admins.

Please run ```php artisan self-diagnosis``` and let me know of any failures.

<img width="1015" alt="Screen Shot 2019-06-11 at 1 15 42 PM" src="https://user-images.githubusercontent.com/877217/59299925-1c7e8400-8c4b-11e9-8ce3-829f7ad63878.png">

**Comment by olliware** [comment]
@dansup As I have exactly the same problem in #1348 let me show you my self-diagnosis. BTW, "composer install" doesn't update anything - this self-diagnosis error remains. Deleted the pixelfed-folder completely as well as the PostgreSQL-DB, deployed just another instance: Same error.

> |-------------------------------------
> | Common Checks
> |-------------------------------------
> Running check 1/11: App key is set...  ✔
> Running check 2/11: The correct PHP version is installed...  ✔
> Running check 3/11: The database can be accessed...  ✔
> Running check 4/11: All directories have the correct permissions...  ✔
> Running check 5/11: The environment file exists...  ✔
> Running check 6/11: The example environment variables are set...  ✔
> Running check 7/11: Required locales are installed...  ✘
> Running check 8/11: Maintenance mode is not enabled...  ✔
> Running check 9/11: The migrations are up to date...  ✔
> Running check 10/11: The required PHP extensions are installed...  ✔
> Running check 11/11: The storage directory is linked...  ✔
> 
> |-------------------------------------
> | Environment Specific Checks (production)
> |-------------------------------------
> Running check 1/5: Composer dependencies (without dev) are up to date...  ✘
> Running check 2/5: Configuration is cached...  ✔
> Running check 3/5: Debug mode is not enabled...  ✔
> Running check 4/5: Unwanted PHP extensions are disabled...  ✔
> Running check 5/5: Routes are cached...  ✔
> 
> The following checks failed:
> The following locales are missing:
> en_US
> 
> Your composer dependencies are not up to date. Call "composer install" to update them. Do not run Composer as root/super user! See https://getcomposer.org/root for details
> Loading composer repositories with package information
> Installing dependencies from lock file
> Package operations: 0 installs, 0 updates, 32 removals
>   - Uninstalling webmozart/assert (1.4.0)
>   - Uninstalling theseer/tokenizer (1.1.2)
>   - Uninstalling sebastian/version (2.0.1)
>   - Uninstalling sebastian/resource-operations (2.0.1)
>   - Uninstalling sebastian/recursion-context (3.0.0)
>   - Uninstalling sebastian/object-reflector (1.1.1)
>   - Uninstalling sebastian/object-enumerator (3.0.3)
>   - Uninstalling sebastian/global-state (2.0.0)
>   - Uninstalling sebastian/exporter (3.1.0)
>   - Uninstalling sebastian/environment (4.2.2)
>   - Uninstalling sebastian/diff (3.0.2)
>   - Uninstalling sebastian/comparator (3.0.2)
>   - Uninstalling sebastian/code-unit-reverse-lookup (1.0.1)
>   - Uninstalling phpunit/phpunit (7.5.9)
>   - Uninstalling phpunit/php-token-stream (3.0.1)
>   - Uninstalling phpunit/php-timer (2.1.1)
>   - Uninstalling phpunit/php-text-template (1.2.1)
>   - Uninstalling phpunit/php-file-iterator (2.0.2)
>   - Uninstalling phpunit/php-code-coverage (6.1.4)
>   - Uninstalling phpspec/prophecy (1.8.0)
>   - Uninstalling phpdocumentor/type-resolver (0.4.0)
>   - Uninstalling phpdocumentor/reflection-docblock (4.3.1)
>   - Uninstalling phpdocumentor/reflection-common (1.0.1)
>   - Uninstalling phar-io/version (2.0.1)
>   - Uninstalling phar-io/manifest (1.0.3)
>   - Uninstalling nunomaduro/collision (v2.1.1)
>   - Uninstalling myclabs/deep-copy (1.9.1)
>   - Uninstalling mockery/mockery (1.2.2)
>   - Uninstalling hamcrest/hamcrest-php (v2.0.0)
>   - Uninstalling fzaninotto/faker (v1.8.0)
>   - Uninstalling filp/whoops (2.3.1)
>   - Uninstalling doctrine/instantiator (1.2.0)

"composer install" shows the following:

> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Nothing to install or update
> Generating optimized autoload files
> > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> > @php artisan package:discover --ansi
> Discovered Package: beyondcode/laravel-self-diagnosis
> Discovered Package: fideloper/proxy
> Discovered Package: intervention/image
> Discovered Package: jenssegers/agent
> Discovered Package: laravel/horizon
> Discovered Package: laravel/passport
> Discovered Package: laravel/tinker
> Discovered Package: nesbot/carbon
> Discovered Package: nunomaduro/collision
> Discovered Package: pbmedia/laravel-ffmpeg
> Discovered Package: pixelfed/laravel-snowflake
> Discovered Package: spatie/laravel-backup
> Discovered Package: spatie/laravel-image-optimizer
> Discovered Package: stevebauman/purify
> Package manifest generated successfully.

What is still missing?

Best regards,

Oliver

**Comment by oufmilo** [comment]
Thank you @dansup !

ACTIVITYPUB_INBOX=true
ACTIVITYPUB_SHAREDINBOX=true

 It was in .env.example but wasn't in .env 
php artisan config:clear && php artisan route:clear

Now it's ok, notifications works fine !

**Comment by raphgilles** [comment]
Ok. That's ok for me too.

Many thanks @dansup !

**Comment by olliware** [comment]
> Thank you @dansup !
> 
> ACTIVITYPUB_INBOX=true
> ACTIVITYPUB_SHAREDINBOX=true
> 
> It was in .env.example but wasn't in .env
> php artisan config:clear && php artisan route:clear
> 
> Now it's ok, notifications works fine !

Had both parameters on "true" already - what did you exactly do? Just alter the both parameters?

**Comment by oufmilo** [comment]
Yes I just added these two parameters in.env 
Then empty the caches

**Comment by okpierre** [comment]
Can confirm same problem as @olliware  with **composer install**

Created issue for tracking https://github.com/pixelfed/pixelfed/issues/1393

**Comment by dansup** [comment]
@olliware @okpierre Please try running ```composer update```, you may need to stash the composer-lock file for future updates.

**Comment by olliware** [comment]
Done so - result:

> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 5 installs, 31 updates, 1 removal
>   - Removing symfony/contracts (v1.0.2)
>   - Updating symfony/debug (v4.2.8 => v4.3.1): Loading from cache
>   - Updating symfony/process (v4.2.8 => v4.3.1): Loading from cache
>   - Updating symfony/css-selector (v4.2.8 => v4.3.1): Loading from cache
>   - Updating symfony/var-dumper (v4.2.8 => v4.3.1): Loading from cache
>   - Updating symfony/routing (v4.2.8 => v4.3.1): Loading from cache
>   - Installing symfony/mime (v4.3.1): Loading from cache
>   - Updating symfony/http-foundation (v4.2.8 => v4.3.1): Loading from cache
>   - Installing symfony/event-dispatcher-contracts (v1.1.1): Loading from cache
>   - Updating symfony/event-dispatcher (v4.2.8 => v4.3.1): Loading from cache
>   - Installing symfony/polyfill-php73 (v1.11.0): Loading from cache
>   - Updating symfony/http-kernel (v4.2.8 => v4.3.1): Loading from cache
>   - Updating symfony/finder (v4.2.8 => v4.3.1): Loading from cache
>   - Installing symfony/service-contracts (v1.1.2): Loading from cache
>   - Updating symfony/console (v4.2.8 => v4.3.1): Loading from cache
>   - Updating doctrine/lexer (v1.0.1 => 1.0.2): Loading from cache
>   - Updating egulias/email-validator (2.1.7 => 2.1.8): Loading from cache
>   - Updating opis/closure (3.2.0 => 3.3.0): Loading from cache
>   - Installing symfony/translation-contracts (v1.1.2): Loading from cache
>   - Updating symfony/translation (v4.2.8 => v4.3.1): Loading from cache
>   - Updating nesbot/carbon (2.17.1 => 2.19.2): Loading from cache
>   - Updating league/flysystem (1.0.51 => 1.0.52): Loading from cache
>   - Updating nikic/php-parser (v4.2.1 => v4.2.2): Loading from cache
>   - Updating laravel/framework (v5.8.15 => v5.8.21): Loading from cache
>   - Updating lcobucci/jwt (3.2.5 => 3.3.1): Loading from cache
>   - Updating cakephp/chronos (1.2.5 => 1.2.7): Loading from cache
>   - Updating laravel/horizon (v3.1.2 => v3.2.2): Loading from cache
>   - Updating phpseclib/phpseclib (2.0.15 => 2.0.17): Loading from cache
>   - Updating laravel/passport (v7.2.2 => v7.3.0): Loading from cache
>   - Updating aws/aws-sdk-php (3.93.3 => 3.100.1): Loading from cache
>   - Updating league/flysystem-aws-s3-v3 (1.0.22 => 1.0.23): Loading from cache
>   - Updating jaybizzle/crawler-detect (v1.2.81 => v1.2.83): Loading from cache
>   - Updating phpunit/php-timer (2.1.1 => 2.1.2): Loading from cache
>   - Updating phpunit/phpunit (7.5.9 => 7.5.12): Loading from cache
>   - Updating symfony/filesystem (v4.2.8 => v4.3.1): Loading from cache
>   - Updating tightenco/collect (v5.8.15 => v5.8.21): Loading from cache
>   - Updating spatie/db-dumper (2.14.0 => 2.14.1): Loading from cache
> symfony/event-dispatcher-contracts suggests installing psr/event-dispatcher
> symfony/service-contracts suggests installing symfony/service-implementation
> Writing lock file
> Generating optimized autoload files
> > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> > @php artisan package:discover --ansi
> Discovered Package: beyondcode/laravel-self-diagnosis
> Discovered Package: fideloper/proxy
> Discovered Package: intervention/image
> Discovered Package: jenssegers/agent
> Discovered Package: laravel/horizon
> Discovered Package: laravel/passport
> Discovered Package: laravel/tinker
> Discovered Package: nesbot/carbon
> Discovered Package: nunomaduro/collision
> Discovered Package: pbmedia/laravel-ffmpeg
> Discovered Package: pixelfed/laravel-snowflake
> Discovered Package: spatie/laravel-backup
> Discovered Package: spatie/laravel-image-optimizer
> Discovered Package: stevebauman/purify
> Package manifest generated successfully.

No change as it comes with the "friendly" circle. Is it possible to see any kind of log showing what's wrong with the notifications?

Best regards,

Oliver

**Comment by lesamarien** [comment]
Hello

I set ACTIVITYPUB_INBOX and ACTIVITYPUB_SHAREDINBOX to true
I then did:
php7.2 artisan config: cache
php7.2 artisan config: clear
php7.2 craftsman road: clear
But it does not work, the wheel is still spinning.

Best regards,
JM

**Comment by lesamarien** [comment]
Here is the result of : php artisan self-diagnosis

|-------------------------------------
| Common Checks
|-------------------------------------
Running check 1/11: App key is set...  ✔
Running check 2/11: The correct PHP version is installed...  ✔
Running check 3/11: The database can be accessed...  ✔
Running check 4/11: All directories have the correct permissions...  ✔
Running check 5/11: The environment file exists...  ✔
Running check 6/11: The example environment variables are set...  ✔
Running check 7/11: Required locales are installed...  ✘
Running check 8/11: Maintenance mode is not enabled...  ✔
Running check 9/11: The migrations are up to date...  ✔
Running check 10/11: The required PHP extensions are installed...  ✔
Running check 11/11: The storage directory is linked...  ✔

|-------------------------------------
| Environment Specific Checks (production)
|-------------------------------------
Running check 1/5: Composer dependencies (without dev) are up to date...  ✘
Running check 2/5: Configuration is cached...  ✘
Running check 3/5: Debug mode is not enabled...  ✔
Running check 4/5: Unwanted PHP extensions are disabled...  ✔
Running check 5/5: Routes are cached...  ✘

The following checks failed:
The following locales are missing:
en_US

Your composer dependencies are not up to date. Call "composer install" to update them. sh: 1: exec: '/usr/bin/php7.2': not found

**Comment by oufmilo** [comment]
@lesamarien did you try running composer update?

**Comment by lesamarien** [comment]
Hello
I do not know what happened, but today the notifications work. I do not understand why.

Thank you for your help
