### ISSUE TITLE
Error: Composer dependencies are not up to date 

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1393]
The following checks failed:
Your composer dependencies are not up to date. Call "composer install" to update them. Loading composer repositories with package information

Started **composer install** and allowed it to complete

`Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: beyondcode/laravel-self-diagnosis
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: jenssegers/agent
Discovered Package: laravel/horizon
Discovered Package: laravel/passport
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pbmedia/laravel-ffmpeg
Discovered Package: pixelfed/laravel-snowflake
Discovered Package: spatie/laravel-backup
Discovered Package: spatie/laravel-image-optimizer
Discovered Package: stevebauman/purify
Package manifest generated successfully.`

Same message afterwards. Composer dependencies are not up to date

**Comment by okpierre** [comment]
@dansup both install and update command = message _Nothing to install or update_

**Comment by okpierre** [comment]
Issue marked closed. Does that mean it was fixed?

**Comment by dansup** [comment]
@okpierre This has been closed because this is not a bug in pixelfed. It's okay if the composer deps are not up to date for minor releases.

**Comment by okpierre** [comment]
@dansup Keep seeing it pop up in various issues reported so was worried might've missed something. Thanks for confirming!
