### ISSUE TITLE
Incorrect Dimension For Search Results Cards

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1394]
Stretched? Forced to fit in box?

Search results show cards that have odd image dimension

Could it be trying to resize landscape into a square?

**Comment by trwnh** [comment]
Can you provide steps to reproduce?

**Comment by okpierre** [comment]
upload photo, add description/tag, search for photo

'showing results page' will list the photo and appearance looks odd

here's the result:
![pixelfed-search-results-image](https://user-images.githubusercontent.com/1679025/59325661-e4f6f280-8cb1-11e9-9521-bcb08d57e884.png)
![railway](https://user-images.githubusercontent.com/1679025/59325668-ed4f2d80-8cb1-11e9-9359-96816aa6a4eb.jpg)

**Comment by trwnh** [comment]
Ahh, you have to search for your own photos, ok.

It looks like a sizing issue similar to a few others that have happened in the past -- this one in particular is caused by `height: 180px` being set with javascript for some reason. Disabling that one rule causes the thumbnail to display correctly.
