### ISSUE TITLE
TypeError When Viewing Profile

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1395]
-View timeline
-click link to profile

Error:
TypeError: e.data[0] is undefined 

![pixelfed-profile-typeerror](https://user-images.githubusercontent.com/1679025/59318302-8ff8b380-8c94-11e9-976f-9c4cba790082.png)

**Comment by dansup** [comment]
@okpierre I need more information, what instance is this on?

**Comment by okpierre** [comment]
@dansup login and then browse https://pixelfed.social/pixelfed

The error will output in firefox console

Hope that helps

**Comment by dansup** [comment]
@okpierre Nice find, fixed in latest commits!
