### ISSUE TITLE
Previews not generated / no pic after click

### ISSUE THREAD

**Issue by olliware** [pixelfed/pixelfed#1396]
Hey everyone,

I am really struggling ATM - made my new testing instance yesterday. Uploaded five pics with captions, just four are being displayed here: (https://pixelfed.pifferi.info/olliware.

If I click one, the "big" version should appear - this doesn't happen. First: How may I generate the preview for all media that is here. Second: How do I fix this effect that clicking on a picture brings... nothing? Storage is linked of course.

Thanks for your ideas!

BR,

Oliver

**Comment by trwnh** [comment]
Please make sure Horizon is running with the same privileges as your web server. #1220

**Comment by trwnh** [comment]
Actually, it seems like you've got a more general web routing issue. Your CSS is not loading properly right now. Are you proxying through nginx correctly?

**Comment by olliware** [comment]
Hadn't seen this yet... Will check it out. As for Horizon, what is the best way to get it running all the way in the background? Using the Service pixelfed-horizon.service in /etc/systemd/systemd-way like it is documented?

**Comment by olliware** [comment]
> Actually, it seems like you've got a more general web routing issue. Your CSS is not loading properly right now. Are you proxying through nginx correctly?

Yes, had a typo in the conf at try_files $uri $uri/ /index.php?$query_string; . Works now. Starting over with a fresh instance...

**Comment by trwnh** [comment]
Using a service manager like `systemctl` or `supervisord` is probably the best way to run Horizon in the background, yes -- unless you're just running everything under the same `pixelfed` user, for example.

**Comment by olliware** [comment]
So the ideal service-configuration in my case looks like the following (to whom it may concern):

```
[Unit]
Description=Pixelfed task queueing via Laravel Horizon
After=network.target
Requires=php7.3-fpm.service
Requires=redis.service
Wants=nginx.service

[Service]
Type=simple
ExecStart=/usr/bin/php /var/www/pixelfed/artisan horizon
User=www-data
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

How may I now trigger the re-creation of the preview as both the service and Pixelfed is running with the www-data-user?

Best regards,

Oliver

**Comment by trwnh** [comment]
I think it's `php artisan queue:work`?

**Comment by olliware** [comment]
> I think it's `php artisan queue:work`?

In fact this does nothing (but it should I guess), I even have to cancel the command as there is no output...
