### ISSUE TITLE
Card Body By Line Should Not Be Centered

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1397]
Search for any photo and for each photo listed it will show a card

Below the photo, the author by line is centered and time stamp is floated to the right

What's the best way to improve the style?

byline first row and time stamp second row?
byline to the left and time stamp to the right?

**Comment by trwnh** [comment]
Possibly the center alignment could be removed entirely?

Before | After
--- | ---
![image](https://user-images.githubusercontent.com/10606431/59330031-f2ae7700-8cb5-11e9-95d3-50415076675f.png) | ![image](https://user-images.githubusercontent.com/10606431/59330047-fe9a3900-8cb5-11e9-89a2-0c08b0b87bb8.png)

**Comment by okpierre** [comment]
Curious if there is a reason the card require the byline and timestamp.

Can the search results have the same layout as the profile view to be consistent?

Thoughts?

**Comment by trwnh** [comment]
probably it would load too much information. but it is an idea, certainly
-- searches for statuses could construct a mini timeline.

**Comment by okpierre** [comment]
@dansup @trwnh 

Please reopen. 

Can I suggest the byline be removed entirely and simply display image? 

If visitor has interest in the searched image, once they click on the image, all details will be provided
