### ISSUE TITLE
Easy installer and a one click update button

### ISSUE THREAD

**Issue by jameshh93** [pixelfed/pixelfed#1399]
Part of Wordpress success is the fact that it is easy to install and easy to update (and keep secure).
Creating an easy to use wordpress style installer and a one click update button that handles everything for you in the admin dashboard would make pixelfed a lot more accessible/easier for people with little php knowledge/cannot access command line to make and manage their own instances. 

Pixelfed looks amazing!

**Comment by okpierre** [comment]
I believe this could be the upcoming installer @jameshh93

![pixelfed-installation](https://user-images.githubusercontent.com/1679025/59462115-f7c41100-8df0-11e9-918d-6325cbeb8099.png)

**Comment by trwnh** [comment]
Yes, `php artisan install` is currently WIP, and will be launching soon hopefully. As is the update button... #1216

**Comment by atomical** [comment]
What is the best way to install artisan currently? I'm seeing an error when running `php artisan key:generate`:

```
/pixelfed/vendor/autoload.php): failed to open stream: No such file or directory
```

**Comment by dansup** [comment]
@atomical You need to run ```composer install``` before you can run artisan

**Comment by atomical** [comment]
@dansup Thanks! What's the command to run an instance? I can update the documentation if it's helpful.

https://docs.pixelfed.org/master/running-an-instance/artisan-command.html

**Comment by penartur** [comment]
Maybe this issue was closed by mistake, and @dansup was going to label it instead? 🤔
