### ISSUE TITLE
Unable to log in on mobile iOS/Brave

### ISSUE THREAD

**Issue by MrPetovan** [pixelfed/pixelfed#140]
Trying to log in on my instance at https://pixelfed.mrpetovan.com on Apple iOS/Brave, I'm getting the following page: "The page has expired due to inactivity Please refresh and try again."

I'm able to log in on normally on desktop (Window 10/Vivaldi).

Environment:
- Debian 9
- PHP 7.2.5
- Apache 2.4.25
- MariaDB 10.1.6
- iOS 11.4
- Brave 1.6.2

Excerpt from `.env`:
```
APP_ENV=development
APP_DEBUG=true
LOG_CHANNEL=stack
```

It sounds like a CSRF token issue, is there any debug log I can enable? I assume `LOG_CHANNEL` but I'm unfamiliar with it?

**Edit**: I found `/path/to/pixelfed/storage/logs/laravel.log`

**Comment by trwnh** [comment]
This happens with certain extensions to block scripts/plugins. I used to be using a certain script-blocker until I noticed it wouldn't let me login, so I uninstalled that and installed a simpler plugin that lets me toggle JS only rather than blacklisting all plugins/cookies/scripts for a site.

**Comment by MrPetovan** [comment]
Thanks for the workaround, however I don’t intend on changing mobile browser as I don’t believe javascript should be necessary to log in.

**Comment by trwnh** [comment]
Yeah, it's not the JS that's causing the problem -- I can log in fine without JS. It's when I start blocking cookies and plugins that things start to get weird.

**Comment by MrPetovan** [comment]
Never mind, I found my issue, I was hitting `http://pixelfed.mrpetovan.com` and there was no redirection to `https://pixelfed.mrpetovan.com`.
