### ISSUE TITLE
Card Body Is Outside The Container When Viewed With Chrome

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1401]
The card body that shows the likes, shares, timestamp, etc. extends outside the sidebar when using Chrome to view

See screenshots below for each browser

Firefox
![pixelfed-sidebar-card-body-firefox](https://user-images.githubusercontent.com/1679025/59560168-87c5ae80-8fdb-11e9-954a-0e9cf6482dfd.png)

Chrome
![pixelfed-sidebar-card-body-chrome](https://user-images.githubusercontent.com/1679025/59560167-872d1800-8fdb-11e9-9c4b-42f58fb478cb.png)

**Comment by dansup** [comment]
Fixed in latest commits
