### ISSUE TITLE
Where to set mail parameters?

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1403]
Hey Folks,

were do I finally need to set the mail-parameters? In the .env-file within my Pixelfed-folder or via editing the contents of mail.php in the /config-subfolder?

Thanks for helping me!

Oliver

**Comment by dansup** [comment]
@olliware Hi, you are meant to edit the ```.env``` file and then run ```php artisan config:cache```. While you can update ```config/*``` files directly, the preferred method is to use .env so your configuration does not conflict with git updates.

**Comment by ghost** [comment]
Thanks, sounds like a plan! 👍🏻

**Comment by ghost** [comment]
Worked like a charm BTW- thanks ✌🏻
