### ISSUE TITLE
Show warning when tag limit exceeded in Compose UI

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1416]
Submit post and include tag over the x limit

Currently after submitting, the post will show the entire tag and anything over the limit will not be linked

![pixelfed-tag-limit](https://user-images.githubusercontent.com/1679025/59659933-4f59d800-9175-11e9-875e-99b9c9b02689.png)

Pixelfed should either show hint or warning message prior to submit
 or 
not include the tags that are over the limit so that it looks cleaner

**Comment by dansup** [comment]
No plans to merge.

**Comment by trwnh** [comment]
Why not? There is currently no indication to the user that their tags will not be processed...
