### ISSUE TITLE
Missing image contextual menu when some filters are used

### ISSUE THREAD

**Issue by ra-mon** [pixelfed/pixelfed#1419]
**Steps to reproduce:**
- Upload an image
- Choose _Aden_ filter ( or _Perpetua_ or possibly others, i don't test all of them yet)
- Click _[Publish]_ button
- When your post is displayed, right-click inside your image

**Expected:** Browser _image_ contextual menu to be displayed (open image, save image as..., image porperties, etc... depends on used browser )

**Actual:** Browser _page_ contextual menu is displayed instead, and no way to change this...

Test case : https://pix.diaspodon.fr/p/Pierre/46214038392279040

**Comment by dansup** [comment]
@ra-mon Looks fine to me, what browser are you using?
<img width="959" alt="Screen Shot 2019-06-18 at 12 40 43 PM" src="https://user-images.githubusercontent.com/877217/59710567-67a61300-91c6-11e9-80a3-c94d529b299e.png">

**Comment by ra-mon** [comment]
I use Vivaldi 2.6 (see screenshots on https://mastodon.gougere.fr/@Pierre/102282732051045047 ) and the issue was exactly reproductible in Firefox Nightly and ESR, Chromium 76, Opera 60 & 63 (on Windows).
Seems fixed now...
