### ISSUE TITLE
Hashtags which are prefixed with another hashtag are not processed properly

### ISSUE THREAD

**Issue by neilalexander** [pixelfed/pixelfed#142]
i.e. in https://pixelfed.social/p/bastien/1225

#cat and #cats are both interpreted/linked as #cat. 

Suggest that longer hashtags should be preferred over shorter ones to fix this issue.

**Comment by Grazouillis** [comment]
Same case in here : https://pixelfed.social/p/Lyrilith/782
#goth #gothic

**Comment by dansup** [comment]
Fixed
