### ISSUE TITLE
Do Not Allow Caption To Exceed Character Count

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1427]
**Add new photo, fill out the caption by exceeding the character count, click publish**
==========================================================
![pixelfed-character-count](https://user-images.githubusercontent.com/1679025/59741308-a674b100-9238-11e9-902f-51ea6fa4c286.png)

**The post will still be allowed to be published bypassing the limit shown**
==========================================================

![pixelfed-character-count-exceeded](https://user-images.githubusercontent.com/1679025/59741235-67466000-9238-11e9-84aa-34ac9b26b02c.png)

**Comment by trwnh** [comment]
i think technically this is a ui issue because the caption limit is supposed to be 2200 by default...

**Comment by trwnh** [comment]
Looks like the validator isn't using the max caption length from the config...

https://github.com/pixelfed/pixelfed/blob/a63498c22c4b0a59d358f7a25027fd0ca9b65bdb/app/Http/Controllers/InternalApiController.php#L277-L287

**Comment by dansup** [comment]
Fixed in #1429

**Comment by trwnh** [comment]
Fixed in #1429
