### ISSUE TITLE
Relicence Pixelfed as AGPLv3

### ISSUE THREAD

**Issue by oct2pus** [pixelfed/pixelfed#143]
I would like Pixelfed to follow in the steps of [**Mastodon**](https://github.com/tootsuite/mastodon/blob/master/LICENSE), [**Pleroma**](https://git.pleroma.social/pleroma/pleroma/blob/develop/LICENSE), [**GNUSocial**](https://github.com/foocorp/gnu-social#license), [**Peertube**](https://github.com/Chocobozzz/PeerTube/blob/develop/LICENSE) and [**Friendica**](https://github.com/friendica/friendica/blob/develop/LICENSE) in licencing Pixelfed as APGL.

# Why?

There are numerous reasons why I believe AGPL is a better licence than the MIT licence for such a project, and let me go over my thoughts on the subject.

## Honesty

The AGPL licence would make instances of Pixelfed legally liable to publish their source code if they create any sort of modification, this promotes a culture of honesty present in the majority of the fediverse. 

### Why is Honesty Important?

One of the major reasons people originally moved to the fediverse from places like twitter is because we can't **trust** the twitter corporate to have our best interests  in mind. One of the reasons we can do this is because the majority of the code is open source, and not only that, individual instances also must publish their source code so we can all benefit mutually from each others work and see that nothing that would breach that trust.

## Consistency

Because people are forced to share implimentations, we can achieve a consistent user experience. GPL code discourages proprietary implimentations because they must be shared amongst every other developer, who can then see and impliment either a consistent protocol that works in the same way or to even directly lift code from that developer and impliment it in their own project.

## Code will head upstream

This is more a directly practical example, but you have access to other implimentations that you could merge upstream. This is more the linus argument on the utility of the GPL. 

here is a quote from an [article](https://www.cio.com/article/3112582/linux/linus-torvalds-says-gpl-was-defining-factor-in-linuxs-success.html) on CIO last year by Linus on the GPL and linux.

    Hohndel, who has been involved with the kernel for a very long time, said that during the past 25 years there have been many challenges, and one of the biggest challenges was the possibility of fragmentation. "How do we keep one single kernel?" he asked.

    "I used to be worried about fragmentation, and I used to think that it was inevitable at some point," said Torvalds. “Everyone was looking at the history of Linux and comparing it with UNIX. People would say that it’s going to fail because it's going to fragment. That's what happened before, so why even bother?"

    What made the difference was the license. "FSF [Free Software Foundation] and I don't have a loving relationship, but I love GPL v2," said Torvalds. "I really think the license has been one of the defining factors in the success of Linux because it enforced that you have to give back, which meant that the fragmentation has never been something that has been viable from a technical standpoint."

## Open isn't Free

I left the 'moral' argument for last because I'm not certain where you stand on Free vs Open Source Software. If you do not swap you would be the only permissively licenced relevant implimentation of Activitypub. This would allow easy corporate entry into our ecosphere which is largely dominated by freedom respecting implimentations. Provided they become popular, they could impliment proprietary extensions to the protocol and cause people to race to keep up if they become a major player in the ecosphere. Your implimentation could in essence, be a trojan horse for a much worse player in the ecosphere.

---

Please consider my thoughts and change the licence to AGPLv3.

**Comment by agateblue** [comment]
Hi @oct2pus, and thank you for explaining the issue this carefully. I'm not related to PixelFed at all, but I run Funkwhale (it's another project that I run that is BSD-licensed), your arguments make a lot of sense and I wanted to thank you. I think I will consider Funkwhale's licence to AGPL soon.

**Comment by oct2pus** [comment]
Well at least I did one good thing today! :smiley:

**Comment by MrPetovan** [comment]
I approve, and https://github.com/friendica/friendica I’m working on is under the AGPLv3 as well.

**Comment by ghost** [comment]
I agree and my Mastodon client (https://github.com/halcyon-suite/halcyon) is AGPL 3.0 too.

**Comment by yabirgb** [comment]
Zinat is AGPL too https://github.com/yabirgb/zinat

**Comment by dansup** [comment]
@oct2pus Hello, thank you for your suggestion. I will work on this.

**Comment by BrainBlasted** [comment]
@dansup: at this point, you will need to get permission from all 22 contributors to the code to relicense it. I support changing to AGPL, so good luck :+1:

**Comment by trwnh** [comment]
@dansup - "LGTM"
@j1t - "I'm fine with AGPL"
@hellcp - "Do it!"
@imbsky - "I concur."
@m4sk1n - "You can relicense, but I have nothing against MIT."
@OpenAlgeria - "Do it!"
@moritzheiber - "I concur."
@Grazouillis - "It's ok"
@trwnh - Yes.
@Quenty31 - "I'm okay with" (https://framapiaf.org/@Quenti/100147924679131147)
@moshpirit - "Sure!"
@Nouutilizaire 
@Ahmad-Amsyar - "I agree, this project has to be set free"
@Swedneck - "AGPL is nice, and i'll license my translation under whatever is needed as well."
@timmyrs - "I'm fine with it too. My translation is licensed under whatever license you want."
@DeadSuperHero - "I concur."
@Zatnosk - "I support using AGPL for this project and projects like it."
@neilalexander - "No objections here."
@kpcyrd - "I agree with re-licensing to AGPLv3 or later"
@iah - "Nothing to object about."
@yabirgb - "No problems here"
@qwazix - "I agree and actually prefer AGPL."
@xmgz - "I agree with this change."

Any objections?

**Comment by moritzheiber** [comment]
I concur.

**Comment by DeadSuperHero** [comment]
I concur.

**Comment by Ahmad-Amsyar** [comment]
I agree, this project has to be set free all of us can benefit from this project.

**Comment by neilalexander** [comment]
No objections here.

**Comment by qwazix** [comment]
I agree and actually prefer AGPL.

On June 3, 2018 10:10:55 AM GMT+03:00, trwnh <notifications@github.com> wrote:
>@dansup 
>@j1t 
>@hellcp 
>@imbsky 
>@m4sk1n 
>@OpenAlgeria 
>@moritzheiber 
>@Grazouillis 
>@Quenty31 
>@moshpirit 
>@Nouutilizaire 
>@Ahmad-Amsyar 
>@Swedneck 
>@timmyrs 
>@DeadSuperHero 
>@Zatnosk 
>@neilalexander 
>@kpcyrd 
>@iah 
>@yabirgb 
>@qwazix 
>@xmgz 
>
>Any objections?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dansup/pixelfed/issues/143#issuecomment-394142196

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by moshpirit** [comment]
Sure! No problem :) 

Thanks for the mentions!

**Comment by hellcp** [comment]
Do it!

**Comment by kpcyrd** [comment]
I agree with re-licensing to AGPLv3 or later

**Comment by iah** [comment]
Nothing to object about.

**Comment by xmgz** [comment]
no problem, I agree with this change.


thanks @oct2pus for your proposal and explaining the reasons behind it

**Comment by yabirgb** [comment]
No problems here

**Comment by oct2pus** [comment]
You're welcome, I'm surprised at the wonderful response I've received for it! Two additional projects (@EliotBerriot's [FunkWhale](https://code.eliotberriot.com/funkwhale/funkwhale) and [Unascribe](https://sleeping.town/@unascribed)'s Ionch) at least plan on attempting an AGPLv3 conversion, so I'm glad I took an hour out to try and straighten out my thoughts!

**Comment by mkljczk** [comment]
You can relicense, but I have nothing against MIT.

**Comment by timmyRS** [comment]
I'm fine with it too. My translation is licensed under whatever license you want.

**Comment by ghost** [comment]
AGPL is nice, and i'll license my translation under whatever is needed as well.

**Comment by Grazouillis** [comment]
It's ok :)

**Comment by smorimoto** [comment]
I concur.

**Comment by Zatnosk** [comment]
I support using AGPL for this project and projects like it.

**Comment by nicolasmaia** [comment]
I contributed to translation here and I support the change to "AGPL or later".

**Comment by dansup** [comment]
LGTM 👍

**Comment by trwnh** [comment]
That just leaves

@Nouutilizaire

**Comment by n-haddag** [comment]
Do it!👍

**Comment by j1t** [comment]
I'm fine with AGPL
