### ISSUE TITLE
Duplicate profiles being stored (+ duplicate users in search)

### ISSUE THREAD

**Issue by jonaharagon** [pixelfed/pixelfed#1440]
For some reason I'm seeing duplicate profiles being created in the admin panel:

![image](https://user-images.githubusercontent.com/3637842/59861732-0194c980-9347-11e9-81ba-c37e365cb745.png)

![image](https://user-images.githubusercontent.com/3637842/59861744-08bbd780-9347-11e9-861a-be2b6d548276.png)

And duplicate profiles appearing in search:

![image](https://user-images.githubusercontent.com/3637842/59861778-15403000-9347-11e9-9fbb-6e8c72bcee14.png)

They both link to the same profile from search despite having different profile pictures.

**Comment by dansup** [comment]
@JonahAragon Are you using postgres and the latest commits?

**Comment by jonaharagon** [comment]
I'm using MariaDB and the latest commits at the time I installed this morning.

**Comment by dansup** [comment]
@JonahAragon Looks like a race condition, will investigate.

**Comment by dansup** [comment]
@JonahAragon Fixed in #1446
