### ISSUE TITLE
Avoid Confusion In Help Section With Site Name

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1444]
Currently:
when users go to the Help Center, there will be confusion due to use of site name and also pixelfed

Suggestion:
allow auto update/replace so that any site name change will be reflected in Help Center to replace the mismatch

**Comment by dansup** [comment]
@okpierre It says "POWERED BY PIXELFED" with a link to pixelfed.org in the footer on every page.

**Comment by okpierre** [comment]
@dansup the powered by part is fine. 

The Help Center with the actual articles is where the confusion occurs.

Here is just a quick example but there are several more
![pixelfed-help-center](https://user-images.githubusercontent.com/1679025/59946973-0a19fc80-943a-11e9-9b59-721ab4f176cf.jpg)

Another example:
Please keep in mind that **Pixelfed** is meant for people over the age of 16 or 13 depending on where you live.

So instead of Pixelfed it should say 'ACME Corporation'
