### ISSUE TITLE
Strings should not be hardcoded

### ISSUE THREAD

**Issue by Whaxion** [pixelfed/pixelfed#145]
On some page, the strings are hard coded. It's really bad for internationalization, so, it must be fixed.

I make this issue more just like a "to do", but I think I will try to resolve it myself. :stuck_out_tongue:

**Comment by trwnh** [comment]
Strings should ideally be located in locales/xx/xx.json and integrated with a tool like Weblate.

**Comment by inmysocks** [comment]
Is there any chance that something simpler for non-tech people to edit, like TOML could be used for the files containing the strings? There are many places where admins may want to change the wording used and digging through JSON and trying to make sure that no commas are missing can be a daunting task for people who aren't used to code.
