### ISSUE TITLE
Allow dots in usernames

### ISSUE THREAD

**Issue by nickian** [pixelfed/pixelfed#1450]
Is it possible to allow dots in usernames like Instagram does?

**Comment by dansup** [comment]
@nickian Unfortunately no. The problem is other projects do not allow dots in usernames, so federation wouldn't work properly.

**Comment by trwnh** [comment]
@dansup if you're talking about mastodon, then they only enforce that on local usernames. remote usernames are less strict, and allow letters/numbers/underscores/hyphens/dots.

however, a more compelling reason to disallow dots is that dots in urls are not advisable -- dots usually indicate file extensions and could create conflicts that way.

**Comment by dansup** [comment]
Re-opened because we now allow dots in usernames but we are having issues with mastodon.

Related: https://github.com/tootsuite/mastodon/pull/6844
