### ISSUE TITLE
Cannot create new post after failing to add too-large media

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1462]
Create new post
Add media over size limit
Error message is displayed
Uploading screen remains on screen
Click on create new post and still shows uploading screen 

![pixelfed-uploading-refresh-view](https://user-images.githubusercontent.com/1679025/60053588-3fc31d80-96a6-11e9-9c78-ecdf9525fcdf.png)

It should go back to fresh create new post instead

**Comment by trwnh** [comment]
Is this still happening?

**Comment by MrAn0nym** [comment]
@trwnh Since no one responded this can probably be closed :shrug:

**Comment by dansup** [comment]
This has been fixed!
