### ISSUE TITLE
Do Not Show Navigation Arrows For Single Media

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1464]
Create new post
Upload single media

Preview shows left / right navigation arrows 

![pixelfed-navigation-arrow-single](https://user-images.githubusercontent.com/1679025/60131369-377ee700-9767-11e9-841f-492b5289411a.jpg)

I believe the arrows should only be shown for multiple files

**Comment by dansup** [comment]
@okpierre What commit are you running, is this a public instance and if so can you link it to me?

**Comment by okpierre** [comment]
@dansup updated to the latest dev from Tuesday on two different installs locally. Both having same problem

**Comment by dansup** [comment]
Cannot reproduce

**Comment by okpierre** [comment]
Attaching another screenshot from pixelfed.de to show same issue

![pixelfedde](https://user-images.githubusercontent.com/1679025/61510600-911eae00-a9c1-11e9-9512-def6a3ac56ae.png)
