### ISSUE TITLE
Long portrait images are squished in single image view

### ISSUE THREAD

**Issue by NFGman** [pixelfed/pixelfed#148]
Long portrait oriented images look normal in the 3-column display, but they're vertically compressed in the single image view.

For example, an image that is originally 900 x 1350px becomes 572 x 772px in the single image view, which is 64% of the original width, but only 57% of the original height.

Compare the [single page of this image](https://pixelfed.social/p/NFGphoto/272) with the [thumbnail in the multi-column view](https://pixelfed.social/NFGphoto).

After investigating, I was able to stop this behaviour by removing the 'width=100%' from the **img** contained within the **status-photo** DIV in the single image HTML.  This stops the horizontal stretching of the image, returning it to the proper ratio.

'margin: auto;' (or something similar) should be added to the **img** to center it within the DIV.

--

[Issue 118 ](https://github.com/dansup/pixelfed/issues/118) also deals with image dimensions but only the 3-column view.

**Comment by trwnh** [comment]
#118 I feel is more generic and will pop up in several spots (like #90) -- the sub-issue is that image CSS is improper and should define some missing attributes like object-fit and container height/width.

**Comment by trwnh** [comment]
No longer happening, I think?

**Comment by NFGman** [comment]
Confirmed, seems OK to me.
