### ISSUE TITLE
Private loops still show up on the Discover Loops page

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1481]
I went to click on a loop that I saw on the loops page. After clicking on the Loop I get a "404 Not Found" error. When I tried to access the profile, it showed me that the account was private.

**Comment by dansup** [comment]
@its3ch0 The only way this is possible is if a private account makes a public status.

https://github.com/pixelfed/pixelfed/blob/d05726be4e384ac6b16b88429645f5031b1335db/app/Http/Controllers/DiscoverController.php#L148
