### ISSUE TITLE
Allow searching for NSFW posts

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#1482]
Hello,

I know that, by default, nsfw content is not in the search results. This is a bit annoying since i want to search specifically nsfw content. You might add the possibility in the profile parameters.

**Comment by raphgilles** [comment]
More than allow searching NSFW posts, it should be an option "Always show NSFW content".

**Comment by stemy2** [comment]
Apparently, it's working now.

**Comment by mercmobily** [comment]
Where is this setting, in the old OR the new design? I am asking for a friend...
