### ISSUE TITLE
Hashtag status\post count out by one

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#1485]
It seems that the most recent post for a particular hashtag on my instance is not being displayed in the hashtag view but is included in the post count within this view. This is the same whether navigating via the hashtag on a post, via a hashtag search or via the hashtag tab in the admin panel.

On my small instance I have a number of hashtags which have only thus far been used on one post, when I search for these or check the hashtag admin tab they are listed as having 1 post associated but when clicking on the hashtag view there are no photos displayed.  In this case the post count on the hashtag view page says '0 posts' even though there is 1, the admin panel displays 1 status.

Similarly, I have some more regularly used hashtags which appear to display 1 less image than the post counts suggest should be displayed.  The post count indicator in this case is correct, it just appears that one of the images is not being displayed and as it happens on all 1 post hashtags.  Having checked through my timeline for a few of the hashtags I've confirmed that in my case it is the most recent post that isn't included.

So to summarise, single use hashtags display 0 photos, and the post count is 1 less (zero) than the actual hashtag count.
Hashtags used more than once are missing the most recent 1x post in hashtags views but the count is accurate.

STACK:
Pixelfed: 0.9.5
Postgres: 10.9
PHP: 7.2.17
Laravel: 5.8.24

![Screenshot from 2019-07-09 08-34-24](https://user-images.githubusercontent.com/51400674/60868598-4d8bad80-a225-11e9-95ef-4dc834c255f7.png)
![Screenshot from 2019-07-09 08-36-26](https://user-images.githubusercontent.com/51400674/60868599-4d8bad80-a225-11e9-84c6-7c0f73c1ec2d.png)
![Screenshot from 2019-07-09 08-37-02](https://user-images.githubusercontent.com/51400674/60868600-4d8bad80-a225-11e9-82b2-caa49b166e6e.png)
![Screenshot from 2019-07-09 08-37-26](https://user-images.githubusercontent.com/51400674/60868601-4d8bad80-a225-11e9-9561-8f35513c5652.png)

**Comment by jk-na** [comment]
Seems like this might be in some way similar to the previous issue I raised: #1359

**Comment by dansup** [comment]
@jk-na The count includes private/unlisted posts (not displayed) and comments containing that hashtag (not displayed).

**Comment by jk-na** [comment]
> @jk-na The count includes private/unlisted posts (not displayed) and comments containing that hashtag (not displayed).

OK, but all of my posts are public and there are no comments containing hashtags in any of them.

**Comment by okpierre** [comment]
> @jk-na The count includes private/unlisted posts (not displayed) and comments containing that hashtag (not displayed).

@dansup can I suggest to exclude private/unlisted/not displayed to avoid confusion and for a better experience?

**Comment by raphgilles** [comment]
I have exactly the same issue.

**Comment by okpierre** [comment]
Confirming issue exists with today's commit
