### ISSUE TITLE
Hashtag page empty although posts exist

### ISSUE THREAD

**Issue by efelon** [pixelfed/pixelfed#1494]
pixelfed 0.9.6 (update from 0.9.4, performed recommended post update steps without error)
ubuntu server x64

When I search for e.g. "art" in this example, I get the 2 results with hashtag on my instance:
![image](https://user-images.githubusercontent.com/10722552/61030491-c291eb00-a3bd-11e9-9f78-8adbf686dcbb.png)
But when I click on the hashtag result I get "0 posts":
![image](https://user-images.githubusercontent.com/10722552/61030520-db020580-a3bd-11e9-8818-c4ac762c8db1.png)

Both were posted as public with version 0.9.4, and one of them is an album post.

I'm happy to provid more information, just tell me what I can do.

**Comment by raphgilles** [comment]
Have you run `php artisan fix:hashtags` ?

**Comment by efelon** [comment]
I haven't. Thank you for pointing that out.
I'm following pixelfed on friendica and haven't seen the hint there.
