### ISSUE TITLE
Social login

### ISSUE THREAD

**Issue by LuxoftAKutsan** [pixelfed/pixelfed#1495]
Is there planned ability to provide social login?

**Comment by mkljczk** [comment]
Pixelfed is a social networking software, you can use your Pixelfed credentials to login on your Pixelfed instance. Isn’t it enough?

**Comment by dansup** [comment]
@LuxoftAKutsan We do not plan to support this. 

It may be possible with a future package using Laravel Socialite that supports Facebook, Twitter, LinkedIn, Google, GitHub, GitLab and Bitbucket.
