### ISSUE TITLE
Store some configuration items in DB

### ISSUE THREAD

**Issue by techknowlogick** [pixelfed/pixelfed#1508]
Applications such as Mastodon and WordPress store most of their configuration in the database.

Some configuration items such as DB information, and other sensitive information such as email, cache, and queue connection information, and even session requiring a secure cookie  (maybe soon also S3 connection info) should remain in file, but I worry about allowing free form editing of he configuration file. This gives the benefit of providing a user interface to admins to change config values and have descriptions next to them of what they do.

I host several pixelfed instances on kubernetes, and so I have public & storage as mountable volumes, but if I wanted to provide write access to .env then I would require the root directory of the directory to also be mounted into the container, which would prevent easy upgrades by just switching out the container.

**Comment by dansup** [comment]
Added in f2066b74!
