### ISSUE TITLE
Profile UI Refactor

### ISSUE THREAD

**Issue by dansup** [pixelfed/pixelfed#152]
This issue will track the improve-user-profile branch being worked on by @hellcp and myself.

Related PR's:
- [ ] #150 
- [ ] #151 

Todo:

**Comment by hellcp** [comment]
![screenshot from 2018-06-03 17-37-12](https://user-images.githubusercontent.com/30577011/40888276-2265b3c8-6755-11e8-85e9-58cab9677fde.png)

**Comment by hellcp** [comment]
#168 #169 #173 #180 are relevant

**Comment by dansup** [comment]
Fixes were merged
