### ISSUE TITLE
New instance, upload error?

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1522]
Hey everyone,

I want to upload some pics on my new instance which are approximately 6,1 MB large. Somehow I cannot upload them, error message ahead:

![Bildschirmfoto 2019-07-18 um 17 51 11](https://user-images.githubusercontent.com/42076599/61476792-16886b00-a98e-11e9-9114-18d8efc22c9b.jpg)

Did I miss any parameter that is different from standard in the .env-file?

These are

> MAX_PHOTO_SIZE=15000
> MAX_CAPTION_LENGTH=750
> MAX_ALBUM_LENGTH=4
> MAX_BIO_LENGTH=200

Just wondering... all updates are made.

Thanks for any clue and best regards,

Oliver

**Comment by ghost** [comment]
![Bildschirmfoto 2019-07-18 um 20 29 08](https://user-images.githubusercontent.com/42076599/61482394-cbc12000-a99a-11e9-96a9-dc4ca695086a.jpg)

**Comment by ghost** [comment]
Problem solved - new server with non-optimized PHP-settings. Working as expected, I'm out for this time 😉 !

**Comment by ghost** [comment]
Same here with images > 1 M.

What did you do to resolve this problem?

**Comment by AmarOk1412** [comment]
Same here...
