### ISSUE TITLE
Sorry, this page isn't available.

### ISSUE THREAD

**Issue by thistehneisen** [pixelfed/pixelfed#1541]
I've followed all the installation steps, but can't get https://www.pixelfed.me/ any further than this error.

**Comment by HongPong** [comment]
I was able to get an install mostly working on ubuntu this weekend (only thumbnails fail silently without errors). my thoughts:

from the install's root directory can you get the result of 
`php artisan self-diagnosis`

i also noticed that the self diagnosis indicates database credentials seem to be retained in a cache or something (as i would change env username and it didn't pick up right away). if the database is not connecting on self diagnosis it won't on the app either i think.

also errors may appear in the laravel app log and the apache error log (for example write failures)

i'm thinking about trying to update the docs to cover a bit of this but things are changing fast so not sure if it makes sense right now.

**Comment by dansup** [comment]
@thistehneisen Since this is a deployment error, I'm going to close this issue. If you need assistance, please join the #pixelfed IRC channel on freenode.

**Comment by thistehneisen** [comment]
@dansup I am trying the fourth time on IRC, but there are zero responses so far.
