### ISSUE TITLE
Read More doesn't show enough context for many comments.

### ISSUE THREAD

**Issue by kvibber** [pixelfed/pixelfed#1544]
I've run into two problems with the option to hide longer comments behind a Read More link:

1. Turning it off in the Labs page doesn't seem to make a difference.
2. It cuts off most comments way too early. It's not usually an issue, but I had a post go viral through the fediverse and I got around a dozen remote comments. A lot of them look like this:

"commenter_handle(truncated):
replying_to_handle a couple of words
Read More"

Some of them don't even have room for a few words after the two usernames.

I found it easier to read the comments remotely from my Mastodon account, though I made a point of coming back to Pixelfed to reply.

The post where I noticed this, which has several examples:
https://pixelfed.social/p/KelsonV/55447535166296064

**Comment by dansup** [comment]
@kvibber Sorry about that, I have shipped a fix!
