### ISSUE TITLE
[Enhancement] Default to /timeline for logged in users

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#155]
Currently, loading "pixelfed.social" as a URL while logged in just leads to a landing page with nothing more than "Federated Image Sharing - Powered by ActivityPub and the fediverse." For logged-in users, this should redirect to /timeline (or /home, if that becomes the new default view), so that they can start using the app immediately.

**Comment by MrPetovan** [comment]
For admins, it goes to the dashboard, but I still think it should go to the timeline as well.

**Comment by dansup** [comment]
Fixed in latest commits
