### ISSUE TITLE
Cannot upload a photo if the size is more than 

### ISSUE THREAD

**Issue by benpro** [pixelfed/pixelfed#1554]
![Screenshot_20190727_161639](https://user-images.githubusercontent.com/1057913/61995517-f17cb200-b089-11e9-9f7d-92ea8a2ef088.png)

If I upload a photo with a size superior to 1900kB it produce error.

Steps to reproduce:
* Get a big picture
* Compress to 1900kB `jpegoptim -S1900`
* Upload
* It works

* Get a big picture
* Keep it superior to 1900kB, i.e. 2000kB `jpegoptim -S2000`
* Upload
* It fails.

Logs:

```
[2019-07-27 14:15:59] production.ERROR: The "" file does not exist or is not readable. {"userId":1,"exception":"[object] (Symfony\\Component\\Mime\\Exception\\InvalidArgumentException(code: 0): The \"\" file does not exist or is not readable. at /home/pixelfed/vendor/symfony/mime/FileinfoMimeTypeGuesser.php:52)
[stacktrace]
#0 /home/pixelfed/vendor/symfony/mime/MimeTypes.php(136): Symfony\\Component\\Mime\\FileinfoMimeTypeGuesser->guessMimeType('')
#1 /home/pixelfed/vendor/symfony/http-foundation/File/File.php(73): Symfony\\Component\\Mime\\MimeTypes->guessMimeType('')
#2 /home/pixelfed/app/Http/Controllers/Api/BaseApiController.php(249): Symfony\\Component\\HttpFoundation\\File\\File->getMimeType()
#3 [internal function]: App\\Http\\Controllers\\Api\\BaseApiController->uploadMedia(Object(Illuminate\\Http\\Request))
#4 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
[…]
```

```
[27/Jul/2019:14:15:59 +0000] "POST /api/v1/media HTTP/1.1" 500 44 "https://pix.benpro.fr/" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
```

.env:

```
MAX_PHOTO_SIZE=15000 (is it in kB?)
```

**Comment by dansup** [comment]
@benpro That is correct, the default limit is 15MB. The issue is likely PHP ini configuration ```POST_MAX_SIZE``` which default is 2MB iirc. Check that and your webserver configuration, make sure its at or above the ```MAX_PHOTO_SIZE``` of pixelfed.

**Comment by benpro** [comment]
@dansup 
`post_max_size` is at 8M.
But `upload_max_filesize` is at 2M, that was the cause!

I wonder why there was no error in my error.log for that. Do you override errors?

**Comment by Deuchnord** [comment]
If you use a reverse-proxy (Apache/Nginx) in front of the app run with Docker, you have to configure it to allow big bodies too. Otherwise the picture will be rejected.

**Comment by cpnfeeny** [comment]
> If you use a reverse-proxy (Apache/Nginx) in front of the app run with Docker, you have to configure it to allow big bodies too. Otherwise the picture will be rejected.

This should probably be added to the instructions. Changing php.ini doesn't help if you don't also add 
```
http {
    # […]
    client_max_body_size 100m;
    # […]
}
```
to nginx.conf.

**Comment by arjonny** [comment]
> > If you use a reverse-proxy (Apache/Nginx) in front of the app run with Docker, you have to configure it to allow big bodies too. Otherwise the picture will be rejected.
> 
> This should probably be added to the instructions. Changing php.ini doesn't help if you don't also add
> 
> ```
> http {
>     # […]
>     client_max_body_size 100m;
>     # […]
> }
> ```
> 
> to nginx.conf.

Absolutely I got hung up on this.  Some nice folks on IRC sorted me out and pointed me in the right direction.  I was also made aware that I needed to configure the correct php.ini for FPM.
