### ISSUE TITLE
Allow usernames to start with any valid character

### ISSUE THREAD

**Issue by 1000i100** [pixelfed/pixelfed#1555]
I'm trying to sign-up ton an instance of pixelfed and i read : `username is invalid. Username must be alpha-numeric and start with a letter.`

Why `and start with a letter.` ?

here is my usual username : **1000i100**

**Comment by dansup** [comment]
@1000i100 In the early days, we allowed any combination of ```a-Z 0-9 - _```. That was changed after we learned not every ActivityPub implementation supports that username format.

I will look into supporting usernames that start with a number.

**Comment by trwnh** [comment]
I think other implementations should fix their bugs if they break on certain usernames. :P [AaZz09-_] should be expected to work anywhere, as there are usernames of the form `_name`... although technically any URL-safe character could be expected.

**Comment by trwnh** [comment]
Example of a valid mastodon profile stsrting with an underscore: https://mastodon.social/@__h2__

**Comment by dansup** [comment]
Fixed in 31330e0ae
