### ISSUE TITLE
Initial Installation Instructions fail

### ISSUE THREAD

**Issue by TahomaSoft** [pixelfed/pixelfed#1556]
When following the install directions on this page (https://docs.pixelfed.org/master/installation.html), 
the instructions fail right after the git clone. 

First, there is no example env file as described here:

"By default Pixelfed comes with a .env.example file. You'll need to rename this file to just .env regardless of what environment you're working on."

Second, key generation fails (php artisan key:generate).

My session output is below.

Thanks!

[erik@localhost pixelfed]$ !php
php artisan key:generate
PHP Warning:  require(/home/erik/Gits/pixelfed/vendor/autoload.php): failed to open stream: No such file or directory in /home/erik/Gits/pixelfed/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/home/erik/Gits/pixelfed/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/erik/Gits/pixelfed/artisan on line 18
[erik@localhost pixelfed]$ emacs foo
[erik@localhost pixelfed]$ more foo
[erik@localhost pixelfed]$ !php
php artisan key:generate
PHP Warning:  require(/home/erik/Gits/pixelfed/vendor/autoload.php): failed to open stream: No such file or directory in /home/erik/Gits/pixelfed/artisa
n on line 18
PHP Fatal error:  require(): Failed opening required '/home/erik/Gits/pixelfed/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in
 /home/erik/Gits/pixelfed/artisan on line 18
[erik@localhost pixelfed]$

**Comment by dansup** [comment]
@TahomaSoft Yeah the docs really need to be updated. To fix the above error, run 

```bash
composer install
```

```bash
cp .env.example .env
```

**Edit .env file with proper values**

```bash
php artisan key:generate
```

```bash
php artisan storage:link
```

```bash
php artisan migrate
```


```bash
php artisan horizon
```

**Comment by TahomaSoft** [comment]
Thanks!
