### ISSUE TITLE
Error when publishing a collection

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#1558]
Hello,

I try to publish my first collection on my account but I have an error.

![Capture](https://user-images.githubusercontent.com/49836486/62150861-568d0d80-b2ff-11e9-95bf-4bd1ef20125c.JPG)

Is something necessary to enable collections on my instance ?

**Comment by okpierre** [comment]
I wasn't able to duplicate. Which version are you using?

Do you get the same error if you just add **one** of your post to collection and publish?

**Comment by raphgilles** [comment]
I don't know why. But if I wait a little time and retry, it's works.
But not if I directly click on the publish button.

When I add only one picture, it's working.

I'm on the last version.

**Comment by dansup** [comment]
@raphgilles How many collections have you created? They are rate limited to 10 per hour, 20 per day and 100 per month.

**Comment by raphgilles** [comment]
@dansup that was my first.

**Comment by raphgilles** [comment]
Have you changed something with the last update ? It's looks to be corrected now.

**Comment by trwnh** [comment]
ok then, closing the issue. hopefully future issues like this shouldn't be so confusing with more descriptive error messages than just "something went wrong"
