### ISSUE TITLE
[UI] .status-comments doesn't need a fixed height

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#156]
Since the image container is now using a block model (`display: block`), you no longer have to set an explicit height for the comments section. Disabling that rule actually makes the cards look better. For example:

URL | Before | After
--- | --- | ---
https://pixelfed.social/p/deadsuperhero/1041 |  ![image](https://user-images.githubusercontent.com/10606431/40883378-e3c5347a-66c0-11e8-88c3-0fa91b54e18d.png) | ![image](https://user-images.githubusercontent.com/10606431/40883383-0821bf5a-66c1-11e8-96f2-951757af7517.png)

**Comment by DeadSuperHero** [comment]
Damn, I've actually been trying to accomplish the __After__ image through alternate means; this is a way better approach.

**Comment by trwnh** [comment]
@DeadSuperHero Blame it on Bootstrap! It's pretty straightforward and not at all confusing when the UI is written from scratch :P In the block model, everything is already a block, and containers expand to fit their contents.

**Comment by trwnh** [comment]
Should be fixed as soon as #162 is deployed!
