### ISSUE TITLE
spatie/db-dumper requires php 7.3

### ISSUE THREAD

**Issue by asonix** [pixelfed/pixelfed#1561]
When trying to install pixelfed today, I encountered an issue with being able to install the proper dependencies on php 7.2. The documentation states that 7.1+ should be fine for pixelfed, but this is only true if the `composer.lock` file is deleted so composer can install the working versions of each dependency

**Comment by okpierre** [comment]
> Some upstream dependencies require php 7.3

Maybe this should be included in the notes for v0.10.0 so others will also be aware of this but I'm not sure how to do that @dansup

**Comment by dansup** [comment]
@asonix @okpierre I will update the documentation to reflect the new minimum php version ```7.3```

**Comment by trwnh** [comment]
@dansup done in https://github.com/pixelfed/docs/pull/16/commits/a7ce30b40a645deb8d12dc71cb20f03a1c436a53 (btw, that docs PR should be ready to merge sometime later today)

**Comment by asonix** [comment]
That really wasn't the solution I was hoping for... Ubuntu 18.04 ships with php 7.2, and I'm not sure there exist PPAs to upgrade an aarch64 device to 7.3...

**Comment by trwnh** [comment]
Hm. Is there a way to get it working with PHP 7.2 then?

**Comment by asonix** [comment]
Yeah, I'm currently running with 7.2 without issues that I can tell. I mentioned in the initial issue that deleting the composer.lock file and letting composer figure out the dependencies on it's own got it working in my case.

**Comment by okpierre** [comment]
@asonix have you tried php7.3 from ppa:ondrej?

**Comment by asonix** [comment]
@okpierre I have not! I could try that this evening, though. I'm not sure if all the required php libraries are packaged, though. I guess we'll find out!

**Comment by dansup** [comment]
@asonix PHP 7.2 is only supported for [3 more months](https://www.php.net/supported-versions.php).

**Comment by hinaloe** [comment]
Would you like to update composer.json?

**Comment by bms8197** [comment]
> That really wasn't the solution I was hoping for... Ubuntu 18.04 ships with php 7.2, and I'm not sure there exist PPAs to upgrade an aarch64 device to 7.3...

sudo apt install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo apt update
apt install php7.3-fpm

Same goes for php-7.4
