### ISSUE TITLE
Replying to fediverse users give unnecessary double @

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1564]
Hi,

When I answer a fediverse user who commented my post I get a superfluous `@` before the username.

See the following screen record:

![Screen Recording 2019-08-01 at 13 55 13](https://user-images.githubusercontent.com/41020854/62291554-84d82d80-b464-11e9-8c21-2dd978a4311d.gif)

Thanks in advance for fixing this.
Best,

**Comment by trwnh** [comment]
Is this still happening?

**Comment by ghost** [comment]
> Is this still happening?

I don’t know, I’m sorry.
I don’t use PixelFed anymore.

**Comment by jk-na** [comment]
This was previously happening on my instance too but was resolved with an update last week (I think)

**Comment by dansup** [comment]
This is fixed in the latest commits!
