### ISSUE TITLE
Deleting a reported account causes reports page to become inaccessible

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1567]
Hi,

Since I made a report (and I believe this one was processed), I can't access https://pixelfed.social/settings/reports anymore.

<img width="1552" alt="Screenshot 2019-08-03 at 17 06 42" src="https://user-images.githubusercontent.com/41020854/62413611-171d3480-b611-11e9-9484-a56750442fa6.png">

Thanks for your help.

**Comment by trwnh** [comment]
Cannot reproduce

edit: nvm, didn't see the part where you said you made a report first. 
edit 2: cannot reproduce even after making a report

**Comment by ghost** [comment]
@trwnh why are you closing this? It still doesn't work.

**Comment by ghost** [comment]
I emptied the cache of my web browser, tried again, and obviously, still doesn't work.

See this screen recording:
![Screen Recording 2019-08-03 at 18 09 05](https://user-images.githubusercontent.com/41020854/62414343-5a2fd580-b61a-11e9-9695-11383001ceb1.gif)

**Comment by trwnh** [comment]
@mthld it is not a bug in pixelfed. please contact your admins (https://pixelfed.social/site/contact) for help with site-specific issues.

**Comment by dansup** [comment]
@trwnh It is a bug, the admin dashboard moderation page is not loading either. I'm thinking this is due to a report referencing a deleted account.

**Comment by ghost** [comment]
I have no idea if this bug was fixed, however I have no use for PixelFed and I'd like to clean my issues backlog. Closing.
