### ISSUE TITLE
edit page does not display the filter preview

### ISSUE THREAD

**Issue by bristow** [pixelfed/pixelfed#1568]
Thank You for PixelFed !

X-Pro II filter doesn't work properly

the edit post : http://pix.toile-libre.org/?img=1564912632.png

and here the result : http://pix.toile-libre.org/?img=1564912667.png

Thanks !

**Comment by dansup** [comment]
@bristow The edit page does not display the filter preview, will be fixed in a future commit!

**Comment by dansup** [comment]
Fixed in the latest commits!
