### ISSUE TITLE
PostgreSQL case-sensitivity causes "slug already exists" for hashtags with capitals

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#1569]
Hello,

This issue is relative to this one : #1201 
Sometime when a hashtag contains a capital letter, the links and the formatting of the post are not parsed.

Here is an example : https://pixelfed.fr/p/GayPride/64332953769086976

Can you take a look ?

Thank you !

**Comment by okpierre** [comment]
Tried this and could not duplicate

![pixelfed-tagging](https://user-images.githubusercontent.com/1679025/62563410-04913e00-b851-11e9-80d9-c4fd7342ccc7.png)

Do you see any error in the log file?

**Comment by raphgilles** [comment]
I know. That's not everytime. I think it happens after using many times one of these tags. But not sure.

In my log file I have : 

> [2019-08-06 18:52:25] Production.ERROR: SQLSTATE[23505]: Unique violation: 7 ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « hashtags_slug_unique »
DETAIL:  La clé « (slug)=(paris) » existe déjà. (SQL: insert into "hashtags" ("name", "slug", "updated_at", "created_at") values (Paris, paris, 2019-08-06 18:52:25, 2019-08-06 18:52:25) returning "id") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23505): SQLSTATE[23505]: Unique violation: 7 ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « hashtags_slug_unique »
DETAIL:  La clé « (slug)=(paris) » existe déjà. (SQL: insert into \"hashtags\" (\"name\", \"slug\", \"updated_at\", \"created_at\") values (Paris, paris, 2019-08-06 18:52:25, 2019-08-06 18:52:25) returning \"id\") at /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23505): SQLSTATE[23505]: Unique violation: 7 ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « hashtags_slug_unique »
DETAIL:  La clé « (slug)=(paris) » existe déjà. at /home/pixelfed/live/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23505): SQLSTATE[23505]: Unique violation: 7 ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « hashtags_slug_unique »
DETAIL:  La clé « (slug)=(paris) » existe déjà. at /home/pixelfed/live/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)

(translation : the key « (slug)=(paris) » already exist)

It's looks like this comment : https://github.com/pixelfed/pixelfed/issues/1201#issuecomment-502436242

**Comment by dansup** [comment]
@raphgilles This is an issue with the Postgres ORM we are using, will work on a fix!

**Comment by raphgilles** [comment]
Ok.

Since tonight's update, the new publications are not parsed on my instance.

But Horizon is running good.

**Comment by idanoo** [comment]
I'm still experiencing this on PostgreSQL.

As expected looks like Eloquent isn't returning a match so is attempting to create one.

`#15 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->firstOrCreate()`

`[previous exception] [object] (PDOException(code: 23505): SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"idx_33721_hashtags_slug_unique\"
DETAIL:  Key (slug)=(testhashtag) already exists. at /var/www/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)`

**Comment by dansup** [comment]
Fixed in https://github.com/pixelfed/pixelfed/pull/4342
