### ISSUE TITLE
[UI][Enhancement] Unnecessary CSS rules

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#157]
- .status-photo is set to display as a block with an !important tag, but all objects already default to a block model. The rule can safely be removed with no changes.
- .status-comment does not need an explicit height because you are using a block model (#156)
- footer should not have both .pt-5 and .mt-5, as this leads to an unnecessarily large top gap on mobile devices.

(maybe a few more, i'll come back to this issue later...)

**Comment by hellcp** [comment]
#135 fixes footer
