### ISSUE TITLE
The message 'No posts yet' should only show for Posts

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1578]
When viewing user profile with no media posted, two messages are shown instead of one:

Collections shows
-No posts yet
-No collections yet

Bookmarks shows
-No posts yet
-No bookmarks yet

Collections and Bookmarks each should only show single message

![nocollections](https://user-images.githubusercontent.com/1679025/62731068-55d73400-b9ef-11e9-8b84-3236240d1539.png)

**Comment by trwnh** [comment]
Fixed in latest commits
