### ISSUE TITLE
[UI][Bug] Long usernames on 768px width cause the timestamp and avatar to clip

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#158]
![image](https://user-images.githubusercontent.com/10606431/40883443-a5d768b6-66c2-11e8-8d39-a2ad96829d97.png)
https://pixelfed.social/p/deadsuperhero/1041

It would be better to keep using the vertical layout, and only reflow to have the info card on the side at 992px. Either that, or have a line break between the name and timestamp. A 13-character username is not that long compared to what could be expected.

**Comment by dansup** [comment]
The timestamp should be '23h' not '23 hours ago'

**Comment by trwnh** [comment]
Ah! That makes sense.

**Comment by hellcp** [comment]
@dansup not a full fix, I would introduce ellipse to usernames just in case

**Comment by trwnh** [comment]
@hellcp Either add ellipses, or limit username length to around 20 characters. I think extremely long usernames will lead to more problems; imagine a username that's 100 characters long. For reference, Instagram uses the following:
>Limit - 30 symbols. Username must contains only letters, numbers, periods and underscores.

**Comment by dansup** [comment]
Fixed in latest commits
