### ISSUE TITLE
Unexpected 2FA codes requests

### ISSUE THREAD

**Issue by ra-mon** [pixelfed/pixelfed#1580]
Using 2FA on pix.diaspodon.fr pixelfed instance.

A 2FA code is requested after each login, as expected.

BUT after login, from time to time (many times a day), a new 2FA code is requested again, when still logged and cookies not deleted. 

Reproductible with different browser (Vivaldi , Opera) on Win7 and Android.

**Comment by dansup** [comment]
This is an issue that your instance admin needs to fix, the session lifetime is probably set too low.
