### ISSUE TITLE
[Feature request] Lightbox view

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#159]
Due to infinite complexity and disparity between screen aspect ratios and image aspect ratios, in some cases it will be unavoidable to have an image that looks bad or isn't big enough. This can be solved by using a lightbox for JS users, or allowing non-JS to view the image directly.

keywords: full picture size view expand zoom open

**Comment by trev-dev** [comment]
Shared a screenshot, it looks super tiny. I'll chime in on this suggestion. Not that pixelfed is for sharing screenshots, but because Linux.

**Comment by dansup** [comment]
Shipped 🚀in latest commits!

**Comment by trwnh** [comment]
Old lightbox was deprecated due to many issues. Reopening this issue to track progress on its replacement

**Comment by dansup** [comment]
Fixed in latest commits!
