### ISSUE TITLE
Clicking "follow" redirects to remote profile

### ISSUE THREAD

**Issue by techknowlogick** [pixelfed/pixelfed#1598]
With `AP_REMOTE_FOLLOW=true` I can search for remote profiles, and they show up in search results as expected. When clicking "Follow" I see an XHR request get sent to /i/follow, but it is cancelled as the browser is redirected to the users profile on the remote site. When I copy the follow XHR request as curl (via the browser network console) and run it that way I get a response of  `[200]`, however I check my profile (and the DB) and the follow was never added. I have tested against accounts that don't require manual approval for following.

If any other debugging information is needed please let me know.

I'm running commit 2fa01c93500998b37db916dd152d072a305d6a33, which is the latest at the time of writing.

**Comment by trwnh** [comment]
testing from pixelfed.social:
- redirected to profile, but...
- follow was successful

**Comment by trwnh** [comment]
Fixed in latest commits
