### ISSUE TITLE
[Bug] .offset-2 should not be set on follower/following list container

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#160]
Before | After
--- | ---
![image](https://user-images.githubusercontent.com/10606431/40883530-f135b766-66c4-11e8-87a6-1edc4f32457e.png) | ![image](https://user-images.githubusercontent.com/10606431/40883535-037e833a-66c5-11e8-95e3-c3196b48a1cf.png)

The proper way to center this would be to use margin auto instead of margin-left 16.6%

**Comment by hellcp** [comment]
My suggestion is to use offsets in as little places as possible, m-auto is much better at preserving from unexpected bugs than offsets
