### ISSUE TITLE
Admin moderation tools not available

### ISSUE THREAD

**Issue by jaranta** [pixelfed/pixelfed#1601]
All of the user moderation tools (from "Enforce CW" to "Delete Account") lead to a "Sorry, this page isn't available." page. Is it a new bug, or has it not been implemented yet?

I get this on pixelfed.fi, which has been updated to the latest commits by Spacebear hosting.

**Comment by dansup** [comment]
@jaranta This is a bug and will be fixed ASAP.

**Comment by techknowlogick** [comment]
@jaranta In the interim, if you need we to delete a user via CLI, or via the DB please let me know.

**Comment by jaranta** [comment]
Hey, any updates on this? I reported this several months ago and the moderation tools are still not usable. I would consider usable moderation being a high priority issue.

**Comment by dansup** [comment]
@jaranta We've shipped mod tools a while ago along with mod logs and a place for mods to discuss the user in question.
