### ISSUE TITLE
[Feature Request] Hide follows and/or followers list completely

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#1604]
Instance: pixelfed.social
Unfortunately, Instagram doesn't allow to hide followers list from your followers (so they won't see each other). And Pixelfed does the same! Even though one can hide follows and followers list from one's profile, this information is still accessible by API.

Suggestion: allow hiding follows and/or followers lists completely

**Comment by trwnh** [comment]
Closed by #1697
