### ISSUE TITLE
[Bug] Only the last 10 comments are shown

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#161]
![image](https://user-images.githubusercontent.com/10606431/40883593-9ed9d9a0-66c6-11e8-88ba-571afb2aed70.png)
https://pixelfed.social/p/trwnh/1416

**Comment by trwnh** [comment]
https://github.com/dansup/pixelfed/issues/49#issuecomment-394139033

**Comment by dansup** [comment]
Related to #189
