### ISSUE TITLE
The solution is to add ```trustedproxy="*"``` to .env, confirmed that it fixed

### ISSUE THREAD

**Issue by maxdrash** [pixelfed/pixelfed#1619]
The solution is to add ```trustedproxy="*"``` to .env, confirmed that it fixed the issue with @Shleeble's instance

_Originally posted by @dansup in https://github.com/pixelfed/pixelfed/issues/1148#issuecomment-485319303_

I have the same problem, already mentioned in issue #1148 with release v0.10.0.
I checked all the settings and tried to add this setting in.env, restarted all the services, i still have the 401 error on the preview upload:
[18/Aug/2019:16:26:14 +0200] "GET /i/media/preview/63791766192656384/41?expires=1566141973&signature=e335e36e966a8c717ab9e1c3e234f2eaa378d4e267ffb5ca28428964e1d79c38 HTTP/1.1" 401 1570 "https://myhost.local/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36"

Do you have any idea?
Thanks.

**Comment by trwnh** [comment]
Did you run `php artisan config:cache` after updating .env?

**Comment by maxdrash** [comment]
Yes i did it.
in the pixelfed working directory with the right user:
php artisan cache:clear
php artisan optimize:clear
php artisan optimize
php artisan config:cache
restart pixelfed-horizon

Same problem.

**Comment by Shleeble** [comment]
Hey friend, please make sure the horizon queue is really running...

**Comment by maxdrash** [comment]
Yes it is.

> myhost.local php[5292]: [2019-08-19 11:24:09][3] Processing: App\Jobs\ImageOptimizePipeline\ImageOptimize
> myhost.local php[5292]: [2019-08-19 11:24:10][3] Processed:  App\Jobs\ImageOptimizePipeline\ImageOptimize
> myhost.local php[5292]: [2019-08-19 11:24:10][4] Processing: App\Jobs\ImageOptimizePipeline\ImageResize
> myhost.local php[5292]: [2019-08-19 11:24:10][4] Processed:  App\Jobs\ImageOptimizePipeline\ImageResize
> myhost.local php[5292]: [2019-08-19 11:24:10][5] Processing: App\Jobs\ImageOptimizePipeline\ImageThumbnail
> myhost.local php[5292]: [2019-08-19 11:24:10][5] Processed:  App\Jobs\ImageOptimizePipeline\ImageThumbnail
> myhost.local php[5292]: [2019-08-19 11:24:10][6] Processing: App\Jobs\ImageOptimizePipeline\ImageUpdate
> myhost.local php[5292]: [2019-08-19 11:24:10][6] Processed:  App\Jobs\ImageOptimizePipeline\ImageUpdate

but:
![image](https://user-images.githubusercontent.com/17526713/63262169-905d8e00-c285-11e9-8d1b-f3316470c092.png)

**Comment by dansup** [comment]
@maxdrash Are you using docker or anything in front of the webserver? The ComposeUI uses signed urls for the preview images, I'm guessing the issue is how its configured.

**Comment by maxdrash** [comment]
> @maxdrash Are you using docker or anything in front of the webserver? The ComposeUI uses signed urls for the preview images, I'm guessing the issue is how its configured.

Theres a machine with pixelfed installation from git and an nginx for ssl offloading in front.
Here is the diagram:
[nginx ssl proxy machine] -> [pixelfed machine: nginx http + php7.3 fpm -> web directory + horizon]

nginx conf in front:

> server {
>         listen 443 ssl http2;
>         server_name myhost.local;
> 
>         ssl_certificate     /etc/ssl/fullchain.pem;
>         ssl_certificate_key     /etc/ssl/privkey.pem;
> 
>         add_header X-Frame-Options "SAMEORIGIN";
>         add_header X-XSS-Protection "1; mode=block";
>         add_header X-Content-Type-Options "nosniff";
> 
>         location / {
>                 proxy_pass_header   Server;
>                 proxy_set_header    Host $host;
>                 proxy_set_header    X-Real-IP $remote_addr;
>                 proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
>                 proxy_set_header    X-Forwarded-Proto $scheme;
>                 proxy_set_header    Upgrade $http_upgrade;
>                 proxy_set_header    Connection "upgrade";
>                 proxy_http_version  1.1;
>                 proxy_pass          http://10.0.0.100:80;
>         }
> }


And the nginx of the pixelfed machine (it comes from the pixelfed documentation without ssl mentions):

> server {
>     listen 80;
>     server_name myhost.local;                    # change this to your fqdn
>     root /var/www/pixelfed/public;                      # path to repo/public
> 
>     index index.html index.htm index.php;
> 
>     charset utf-8;
> 
>     location / {
>         try_files $uri $uri/ /index.php?$query_string;
>     }
> 
>     location = /favicon.ico { access_log off; log_not_found off; }
>     location = /robots.txt  { access_log off; log_not_found off; }
> 
>     # error_page 404 /index.php;
> 
>     location ~ \.php$ {
>         fastcgi_split_path_info ^(.+\.php)(/.+)$;
>         fastcgi_pass unix:/var/run/php/php7.3-fpm.sock; # make sure this is correct
>         fastcgi_index index.php;
>         include fastcgi_params;
>         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # or $request_filename
>     }
> 
>     location ~ /\.(?!well-known).* {
>         deny all;
>     }
> }


Do you see a misconfiguration ?
Thank you for your replies.

**Comment by jplock** [comment]
@maxdrash this is the same setup I’m using. I can get you my nginx configs in about a week. I was able to find a missing variable in a previous issue comment.

**Comment by jplock** [comment]
https://github.com/pixelfed/pixelfed/issues/1107#issuecomment-480548122 I had to add the https stuff

**Comment by maxdrash** [comment]
> [#1107 (comment)](https://github.com/pixelfed/pixelfed/issues/1107#issuecomment-480548122) I had to add the https stuff

Thank you @jplock this resolves the issue.

The new nginx conf:

> map $http_x_forwarded_proto $proxy_https {
>     default '';
>     https 'on';
> }
> 
> server {
>     listen 80;
>     server_name myhost.local;                    # change this to your fqdn
>     root /var/www/pixelfed/public;                      # path to repo/public
> 
>     index index.html index.htm index.php;
> 
>     charset utf-8;
> 
>     location / {
>         try_files $uri $uri/ /index.php?$query_string;
>     }
> 
>     location = /favicon.ico { access_log off; log_not_found off; }
>     location = /robots.txt  { access_log off; log_not_found off; }
> 
>     # error_page 404 /index.php;
> 
>     location ~ \.php$ {
>         fastcgi_split_path_info ^(.+\.php)(/.+)$;
>         fastcgi_pass unix:/var/run/php/php7.3-fpm.sock; # make sure this is correct
>         fastcgi_index index.php;
>         include fastcgi_params;
>         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # or $request_filename
>         fastcgi_param  REQUEST_SCHEME     $http_x_forwarded-proto;
>         fastcgi_param  HTTPS              $proxy_https if_not_empty;
> 
>     }
> 
>     location ~ /\.(?!well-known).* {
>         deny all;
>     }
> }

This works fine now.
