### ISSUE TITLE
Allow registering without setting display name

### ISSUE THREAD

**Issue by poperigby** [pixelfed/pixelfed#1621]
Is it intended that you have to have a name for your account? What's the distinction between a username and a name? Is the name supposed to be your IRL name? If so, that doesn't seem like a good idea to make that mandatory.

**Comment by dansup** [comment]
@PopeRigby The name field is optional but the register form does not reflect that, will fix!

**Comment by poperigby** [comment]
You should also add a placeholder of "Optional"

**Comment by dansup** [comment]
Fixed in the latest commits, we added a `required` attribute to the `name` field and also updated the backend to accept empty or null `name` values!
