### ISSUE TITLE
cloud_storage will save image locally and remotely.

### ISSUE THREAD

**Issue by shleeable** [pixelfed/pixelfed#1624]
https://github.com/pixelfed/pixelfed/blob/8cf0e4fc375158659e49e246440e99e0ee8738ba/app/Jobs/ImageOptimizePipeline/ImageUpdate.php#L72

this is an issue I've raised in chat/mastodon...

**Comment by shleeable** [comment]
dupe of this comment. https://github.com/pixelfed/pixelfed/issues/1139#issuecomment-486932249

**Comment by dansup** [comment]
@Shleeble The plan is to add a new console command that runs in the cron job that deletes local media that exists on the cloud storage driver after X time that an admin can customize.

**Comment by dansup** [comment]
Fixed in latest commits!
