### ISSUE TITLE
Indicate when there are comments on a post in the timeline

### ISSUE THREAD

**Issue by johnchidgey** [pixelfed/pixelfed#1627]
The timeline entries have no indication that any comments have been made. If you click the message icon, any messages will appear beneath, however without clicking you can't tell if you need to.

**Comment by trwnh** [comment]
I think this is currently partly intentional, due to the way comment preview on timeline works. It may be changed though

**Comment by MasterGroosha** [comment]
I don't know if this is the right issue for the problem, but "Alerts" section and "Notifications" doesn't show new comments to posts.
Pixelfed.social instance, btw. A user from mastodon.social posted a comment to my photo and I didn't see any notifications about that.

**Comment by MasterGroosha** [comment]
Just a friendly reminder that comments from remote users (let's say, from Mastodon instance) are not displayed anywhere, so you can easily miss them unless you check all your posts regularly.
This is valid as of 0.10.9

**Comment by dansup** [comment]
Fixed in the latest commits!
