### ISSUE TITLE
Fetch avatars for remote follows

### ISSUE THREAD

**Issue by johnchidgey** [pixelfed/pixelfed#1629]
Remote followers currently use the default avatar and don't appear to fetch the actual users avatar from the remote instance.

**Comment by okpierre** [comment]
Noticed default avatar is showing for both remote followers and remote following

**Comment by Casuallynoted** [comment]
Same, would love to see remote follow avatars come through. Would really make the experience more cohesive across instances imo.

**Comment by Casuallynoted** [comment]
Noticed in the latest release it is listed that remote avatars download even when S3 is not enabled (super excited to have this!). I can see this is the case for other Pixelfed instances, but not Mastodon and other such instances. Is this currently intended behaviour?

**Comment by melroy89** [comment]
@dansup It seems that Pixelfed is not returning the avatar in the webfinger call: https://pixelfed.social/.well-known/webfinger?resource=acct:dansup@pixelfed.social

Basically adding an additional link with in the JSON body: `{"rel":"http://webfinger.net/rel/avatar","href":"https://domain.com/location/to/image.jpg"}` should solves this problem.

Hence no avatar image is now getting retrieved at the moment, see: https://kbin.melroy.org/u/@dansup@pixelfed.social

**Comment by dansup** [comment]
Fixed in the latest commits!

@melroy89 I just shipped the avatar attribute in webfinger ([bca2484](https://github.com/pixelfed/pixelfed/pull/4847/commits/bca248499417963d3e859b46de88fe9ca1aba3d0))

**Comment by melroy89** [comment]
> Fixed in the latest commits!
> 
> @melroy89 I just shipped the avatar attribute in webfinger ([bca2484](https://github.com/pixelfed/pixelfed/pull/4847/commits/bca248499417963d3e859b46de88fe9ca1aba3d0))

Great, thank you so much Daniel.
