### ISSUE TITLE
Remote posts marked sensitive are not hidden in timeline

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1633]
- follow remote user (e.g. mastodon)
- receive a post marked sensitive (but no cw)

expected: post is hidden behind sensitive
actual: post is displayed directly

**Comment by dansup** [comment]
@trwnh Was the remote user from Mastodon or Pleroma?

**Comment by trwnh** [comment]
object: https://cybre.space/users/vantablack/statuses/102656283816269612.json
activity: https://cybre.space/users/vantablack/statuses/102656283816269612/activity.json

$activity is not being initialized correctly https://github.com/pixelfed/pixelfed/blob/9788c80ca937aeb0f48e868e884608d8812933b3/app/Util/ActivityPub/Helpers.php#L227-L240

it is being used in the line that checks for sensitive https://github.com/pixelfed/pixelfed/blob/9788c80ca937aeb0f48e868e884608d8812933b3/app/Util/ActivityPub/Helpers.php#L244

but not in the other lines below it, which use $res directly https://github.com/pixelfed/pixelfed/blob/9788c80ca937aeb0f48e868e884608d8812933b3/app/Util/ActivityPub/Helpers.php#L246-L262
