### ISSUE TITLE
Decode escaped HTML entities

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1638]
https://pixelfed.social/p/trwnh/69930009606885376

Notice that `&quot;` is left unparsed

**Comment by dansup** [comment]
Fixed. 

![Screen Shot 2022-01-23 at 3 15 02 AM](https://user-images.githubusercontent.com/877217/150673886-394c01ec-e241-42ed-90af-a2cd806a0d3f.png)
