### ISSUE TITLE
Why does it take 5 clicks to get to the signup of an instance?

### ISSUE THREAD

**Issue by deoxal** [pixelfed/pixelfed#1645]
pixelfed.org > join > fediverse.network/pixelfed > fediverse.network/pixelfed.social > fediverse.network/pixelfed.social > pixelfed.social

I felt like I was being bombarded by statistics and other unnecessary information while navigating fediverse.network. Now that I know what to do I can get there very quickly but it took me about 5 minutes to figure it out the first time.

I don't really know how to solve this since I'm not a UI designer, but I feel like this would push potential users away from signing up if they had a first impression like mine.

**Comment by trwnh** [comment]
This repo is for the Pixelfed software and not for the pixelfed.org website. But your point is valid, and indeed, pixelfed.org is planning to implement its own website directory/suggestion system. Development on pixelfed.org is currently at https://github.com/pixelfedLabs/delta and is in the process of being migrated/promoted to a core Pixelfed repo.

**Comment by deoxal** [comment]
Yes, I see this repo is for the software now. This was the page I found linked on fediverse.network so I posted here.

Thank you for the reply. Have a nice day.
