### ISSUE TITLE
Add Invite Code Redemption To Registration

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1651]
Suggesting an option to use invitation codes 

This will allow invites to groups, trial, testers, etc without having to disable/enable registration

Found this package:
https://packagist.org/packages/clarkeash/doorman

Requires
-php: >=7.1.3
-laravel/framework: ^5.6
-ramsey/uuid: ^3.6

**Comment by trwnh** [comment]
Possible duplicate of #805

**Comment by dansup** [comment]
Yes lets move this to #805, I'd like to add this before v0.11
