### ISSUE TITLE
«PHP Parse error» when using «php artisan»

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#1654]
Hello,

The commands «php artisan» are not working, last time i tried, i had this error: 
`PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/pixelfed/vendor/zendframework/zend-diactoros/src/functions/marshal_uri_from_sapi.php on line 83`

**Comment by dansup** [comment]
@stemy2 What version of php do you have installed?

**Comment by stemy2** [comment]
OK, i updated php, it fixed everything.
