### ISSUE TITLE
Timeline pagination continues infinitely if not enough statuses

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1657]
On a local dev instance I have only one post in my timeline, and `https://pixeldev.local/api/v1/timelines/home?max_id=72628235275472900&limit=6` is tried. This GET request is retried infinitely.

![deepin-screen-recorder_Select area_20190901175551](https://user-images.githubusercontent.com/10606431/64083234-d123c100-cce1-11e9-8fab-14cb52e6665e.gif)

I suspect this has something to do with paging and receiving nothing.

Is this the code that deals with that?

https://github.com/pixelfed/pixelfed/blob/d9638aee8f3952fd419ea9256f6d2034f6fee582/resources/assets/js/components/Timeline.vue#L597-L699

**Comment by dansup** [comment]
This has been fixed
