### ISSUE TITLE
Pictures are sorted weirdly

### ISSUE THREAD

**Issue by moshpirit** [pixelfed/pixelfed#1659]
When I scroll down I see new pictures come up but the last ones are still shown in a very weird way. This also happens with the latest photos, like you can see below: 

![](https://i.imgur.com/JoauUZr.png)
![](https://i.imgur.com/H69Ya5x.png)

**Comment by dansup** [comment]
MomentUI layout and Collections are experimental, and this is how the masonry package we use works.
