### ISSUE TITLE
Like picture on thumbnail

### ISSUE THREAD

**Issue by Tvax** [pixelfed/pixelfed#1660]
Feature to be able to like a picture by clicking on the hearth icon above the number of likes in the picture thumbnail

![Screenshot from 2019-09-04 13-25-17](https://user-images.githubusercontent.com/19556689/64250910-960ad300-cf17-11e9-8530-9e66c06f0d36.png)

**Comment by trwnh** [comment]
This might not be a good idea because the target would be incredibly small. Especially on mobile. It would be better for a click on a thumbnail to always load the post view.

**Comment by Tvax** [comment]
I mean I always try to like a photo clicking on it, and the button can use some padding to make the target bigger.
It can always be disabled on mobile.

**Comment by dansup** [comment]
This will not work, clicking on the photo will load the post.
