### ISSUE TITLE
Tapping on image in album shows preview for the first one only

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#1671]
Instance: pixelfed.social
Today @dansup uploaded a new version and lightbox (show original image when you tap in it) is back again.

Steps to reproduce the bug:
1. Go to timeline
2. Find a post with several images (f.ex. 4)
3. Keep scrolling images within album tapping on eqch one.

Result: lightbox is buggy. 
1) Tap is interpreted as both "show lightbox" and "switch to another image".
2) An image in lightbox is always the first one from album, no matter which image you tap on.

**Comment by dansup** [comment]
Closing in favour of #1774 because we now have a dedicated button and no longer use tap on image.

**Comment by MasterGroosha** [comment]
![изображение](https://user-images.githubusercontent.com/2780044/70395962-4acff700-1a15-11ea-8942-6e8fd4218d17.png)
Exactly the same bug re-appeared on Pixelfed.Social. Tapping "expand" (or "fullscreen") button shows preview only for the first image in album
