### ISSUE TITLE
Private Collections are not displayed within user timeline and Collections tab

### ISSUE THREAD

**Issue by kaisbensalah** [pixelfed/pixelfed#1675]
Hi,

I found another issue, when trying to create a collection. After successfully adding all the posts, followed by clicking on the buttons "Save" and "Publish", nothing gets loaded within the "Collections" tab on my timeline (showing "No collections yet").

In fact, the collection is successfully stored in the database, since it can be viewed using the collection link. But nothing gets shown within the user timeline UI as well as the collections tab UI.

Seems like this is a front-end issue, where the collections API is not well-integrated for loading the content.

Instance version: 0.10.2.

**Comment by dansup** [comment]
@kaisbe Did you set the collection to private or public?

**Comment by kaisbensalah** [comment]
Hi @dansup. It is set to private (followers-only).

**Comment by dansup** [comment]
Fixed in the latest commits!
