### ISSUE TITLE
[discover.places] not defined

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#1676]
Hello,

When I try to load the url of any place, I have an error page. For example : 
https://pixelfed.fr/discover/location/country/afghanistan

In the log I have that : 
`[discover.places] not defined. in /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:388`

What can I do ?

**Comment by trwnh** [comment]
php artisan route:cache

**Comment by raphgilles** [comment]
Yes, I do that in my upgrade routine. It's not that.

**Comment by trwnh** [comment]
rm -r bootstrap/cache?

**Comment by raphgilles** [comment]
Utch. My instance is down after that.

**Comment by trwnh** [comment]
composer install

**Comment by raphgilles** [comment]
I just haved to re-create the cache folder.
So, that was not that too.

**Comment by trwnh** [comment]
Try rerunning route:cache then?

**Comment by raphgilles** [comment]
Don't work.

Ok, I discovered just now that it's working fine for cities but not for countries : 
https://pixelfed.fr/discover/places/38976/limoux

Also, I checked my Nginx config that is the same of the documentation.

**Comment by trwnh** [comment]
Weird. @dansup?

**Comment by dansup** [comment]
@raphgilles I can confirm its working as intended on [pixelfed.social](https://pixelfed.social/discover/location/country/afghanistan) so the issue is related to your deployment.

Please run "composer dump-autoload" and then "php artisan route:cache"

**Comment by raphgilles** [comment]
So I tried, and it changed nothing.

**Comment by raphgilles** [comment]
Can it be a permissions issue ?
I just discovered since these last manipulations I have the same problem on the homepage : https://pixelfed.fr/

**Comment by dansup** [comment]
Closing this issue, feel free to reach out on IRC if this is still an issue.
