### ISSUE TITLE
Compose Post Beta - Crop don't work if full size selected

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#1677]
Hello,

I have some things to say about the Compose Post Beta.

The big one : 
- Crop don't work if I select a too big area. But it's ok for little area. I click on the next button and nothing is happening.

And some suggestions : 
- You should add a skip button. We don't want to crop all pictures. For example in my case : never. I do that in Lightroom.
- You should detect if the picture is vertical or horizontal. Because for now, only horizontal crop is allowed.
- You should purpose by default the same picture ratio as original.
- When we click outside the area of the compose post for resize the picture, the composte post disappears.

Of course it's still good work and I want to thank you again for that !

**Comment by dansup** [comment]
Cropping photos is now optional!
