### ISSUE TITLE
Title of single post view shows 'Untitled Post'

### ISSUE THREAD

**Issue by gvenk** [pixelfed/pixelfed#1689]
Since a few days the single post view shows 'untitled post', instead of the caption I submitted. Think this has to do something with this line: 

https://github.com/pixelfed/pixelfed/blob/ab765705a5ce1fc70b9a27c9118ac18f93336a53/resources/assets/js/components/PostComponent.vue#L303

**Comment by lapineige** [comment]
I have the same issue, it seems to happens in particular with captions including hashtags.
If you need any log, please tell me.

**Comment by lapineige** [comment]
Maybe it's a different issue. Details here: https://github.com/pixelfed/pixelfed/issues/2154

**Comment by lapineige** [comment]
Note: in my case, the length can be smaller than 100, while I see a title.

**Comment by dansup** [comment]
Fixed in latest commits
