### ISSUE TITLE
change quill to minimum requirement v1.3.7

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1691]
quill prior to 1.3.7 are vulnerable

**Comment by dansup** [comment]
@okpierre fwiw quill.js is only used in the admin dashboard, the risk is low.

**Comment by dansup** [comment]
Merged #1692, thanks @okpierre !

**Comment by okpierre** [comment]
> @okpierre fwiw quill.js is only used in the admin dashboard, the risk is low.

Good to know, thanks!
