### ISSUE TITLE
Merge Avatar settings with User settings

### ISSUE THREAD

**Issue by hellcp** [pixelfed/pixelfed#170]
It's much easier to register go into one setting and have everything to setup in one window, instead of hunting for Avatar settings separately ;)

**Comment by trwnh** [comment]
Ideally all bio elements would be editable from the profile page. For example, loading pixelfed.social/trwnh should allow me to set bio, avatar, and display name from the same page. For non-JS users, editing all these fields should still take place on the same page.

**Comment by dansup** [comment]
Fixed in latest commits
