### ISSUE TITLE
"Duplicate uri key" while performing migrations

### ISSUE THREAD

**Issue by capmisson** [pixelfed/pixelfed#1701]
I'm following the instructions to update on: https://docs.pixelfed.org/running-pixelfed/administration.html

when I do php artisan migrate --force
it's giving me the following problem:

> Migrating: 2019_08_12_074612_add_unique_to_statuses_table
> 
>    Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'https://libertalia.world/@capmisson/102606330120238894' for key 'uri' (SQL: ALTER TABLE statuses CHANGE uri uri VARCHAR(191) DEFAULT NULL UNIQUE COLLATE utf8mb4_unicode_ci)
> 
>  at /var/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
>     660|         // If an exception occurs when attempting to run a query, we'll format the error
>     661|         // message to include the bindings with SQL, which will make this exception a
>     662|         // lot more helpful to the developer instead of just the database's errors.
>     663|         catch (Exception $e) {
>    664|             throw new QueryException(
>     665|                 $query, $this->prepareBindings($bindings), $e
>     666|             );
>     667|         }
>     668| 
> 
>   Exception trace:
> 
>   1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'https://libertalia.world/@capmisson/102606330120238894' for key 'uri'")
>       /var/www/vhosts/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119
> 
>   2   PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'https://libertalia.world/@capmisson/102606330120238894' for key 'uri'")
>       /var/www/vhosts/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
> 
>   Please use the argument -v to see more details.
> 

My system is Debian Stretch with php from sury.org

The error occurs php7.2 and php7.3.

Is there any way to purge the database for duplicated entries?

**Comment by lapineige** [comment]
Same issue here, I also try to remove the status (from mastodon), it still fails.
(note that the original image, where this comment is present, was deleted a while ago, before the upgrade)

Details here: https://github.com/YunoHost-Apps/pixelfed_ynh/pull/84#issuecomment-531373801

Php 7.3

**Comment by dansup** [comment]
This is a known bug in the federation code, it will be fixed soon!

**Comment by lapineige** [comment]
Is it planned for 0.10.4 ?

**Comment by dansup** [comment]
You need to run ```php artisan status:dedup```

**Comment by lapineige** [comment]
>  There are no commands defined in the "status" namespace. 

:(

Note: this bug in preventing any upgrade. If that's a new feature, I can't use it.

**Comment by dansup** [comment]
@lapineige What version are you updating from, status:dedup was added in early August.

**Comment by lapineige** [comment]
0.10.0, with Yunohost: https://github.com/YunoHost-Apps/pixelfed_ynh

**Comment by lapineige** [comment]
Is there a way to do the "status:dedup" thing "manually" ?

**Comment by dansup** [comment]
@lapineige Yes you can do it manually, that won't prevent this from happening again until you update to v0.10.4 or higher.

**Comment by lapineige** [comment]
But how ?
If it's solved, I'll be able to upgrade.

**Comment by dansup** [comment]
@lapineige Run this code in ```php artisan tinker``` https://github.com/pixelfed/pixelfed/blob/c9f5d484553469dedaaa4756b9ed27fe8d0fa140/app/Console/Commands/StatusDedupe.php#L43-L61

**Comment by lapineige** [comment]
> PHP Parse error: Syntax error, unexpected T_OBJECT_OPERATOR on line 1

On second line.

How can I paste the code ? Do I need any indentation ?

edit: Ok I pasted the code, starting at line 42.

Now I have:
> Illuminate/Database/QueryException with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "occurences" does not exist
LINE 1: ... null and "uri" is not null group by "uri" having "occurence...
                                                             ^ (SQL: select id, uri, count(uri) as occurences from "statuses" where "deleted_at" is null and "uri" is not null group by "uri" having "occurences" > 1 order by "created_at" asc limit 50 offset 0)'

**Comment by StopTrackingUs** [comment]
@lapineige if you log into postgres and delete the row with the uri manually it will allow you to upgrade.  If you need help you can contact me admin@stoptrackingus.email.  I was able to post the fix on the ynh version thread also.

**Comment by capmisson** [comment]
I still find the same issue, runned php artisan status:dedup but when I do migrate again it find same problem...
is ther any way to manually delete on mysql?

Thanks
