### ISSUE TITLE
missing /api/v1/instance

### ISSUE THREAD

**Issue by tateisu** [pixelfed/pixelfed#1709]
Response{protocol=http/1.1, code=404, message=Not Found, url=https://pixelfed.tokyo/api/v1/instance }

Sorry, I can't detect server version from web UI.

**Comment by tateisu** [comment]
Subway Tooter check /api/v1/instance before add account (or pseudo account) for check instance type.

**Comment by dansup** [comment]
@tateisu Hello, we are still working on adding the ```/api/v1``` endpoints. They will be added in #1708

**Comment by dansup** [comment]
Added in latest commits!
