### ISSUE TITLE
Deleted federated posts still on timeline

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#1716]
Hello,

When a federated post is deleted by is owner, it still on Pixelfed without the media. Like that.

![Capture](https://user-images.githubusercontent.com/49836486/65559918-ec7a9880-df3c-11e9-96d5-099d95ee6385.JPG)

**Comment by dansup** [comment]
@raphgilles I will investigate!

**Comment by dansup** [comment]
This has been fixed
