### ISSUE TITLE
Migration fails: CreateJobsTable

### ISSUE THREAD

**Issue by es-ka** [pixelfed/pixelfed#1718]
PHP Fatal error:  Cannot declare class CreateJobsTable, because the name is already in use in /my_path/pixelfed/database/migrations/2019_09_09_154715_create_jobs_table.php on line 36

**Comment by dansup** [comment]
@es-ka This is caused by running```php artisan queue:table```, the jobs table was added early last year.

Delete the ```database/migrations/2019_09_09_154715_create_jobs_table.php``` migration and try running the migrations again!

**Comment by es-ka** [comment]
Thanks!
After deleting both
`database/migrations/2019_09_09_154709_create_jobs_table.php`
`database/migrations/2019_09_09_154715_create_jobs_table.php`
it finally works.
