### ISSUE TITLE
Main page: Oops, something went wrong. error 500

### ISSUE THREAD

**Issue by ogmkp** [pixelfed/pixelfed#1728]
Hi.

Since version 0.10.2, I have an error on the main page: Oops, something went wrong.
The page does not load the timeline of posts.
In the logs, as in the browser, I have a 500 error:
10.0.0.254 - - -[30/Sep/2019:03:03:57:20 +0200] "GET /api/pixelfed/v1/timelines/home?max_id=0&limit=4 HTTP/1.1" 500 44 

How to repair?

Thank you.

**Comment by ghost** [comment]
Are you using latest version?

**Comment by trwnh** [comment]
which site are you using? it looks like max_id is being set to 0 incorrectly, but this should not cause problems in loading...

**Comment by ogmkp** [comment]
Website: https://mypict.net
Latest version yes: 0.10.5

I don't know where the problem come from.

This issue relates same bug: #694

**Comment by lapineige** [comment]
I have a similar issue in 0.10.6, after upgrading (from the same version).
I don't know if it's related to Yunohost or not.

https://github.com/YunoHost-Apps/pixelfed_ynh/issues/86#issuecomment-551939176

**Comment by trwnh** [comment]
if you are using yunohost then issues should be filed with yunohost first, yes.

**Comment by lapineige** [comment]
That's what I did, I referenced it there just in case it might be linked to a pixelfed bug.
I've provided the log in the Yunohost's repo issue.
(and as we don't know if it was resolved or not)

**Comment by lapineige** [comment]
Problem solved by restarting php7.3 service

**Comment by lapineige** [comment]
The problem appeared again, "on its own", and restarting php7.3 service didn't change anything this time.

Does those logs https://github.com/YunoHost-Apps/pixelfed_ynh/issues/86#issuecomment-551939176 ring a bell to you Pixelfed devs ? I can't tell where to search for a issue (and if it's Yunohost related or not).

**Comment by lapineige** [comment]
I found out more information regarding my use case and that issue https://github.com/YunoHost-Apps/pixelfed_ynh/issues/86#issuecomment-601280958
It seems that this bug happens only if I add alternative text to the images.

(Also if I use any # the text is not displayed in MomentUI, but that independent I guess)
