### ISSUE TITLE
User can't receive mention from remote server.

### ISSUE THREAD

**Issue by tateisu** [pixelfed/pixelfed#1733]
(just mention, not reply to status)
- Mastodon server's user A send message with mention without media  to Pixelfed server's user B.
- User B can't see anything about that message.

**Comment by trwnh** [comment]
Currently only comments are supported. Mentions alone are not handled. When the DM feature is added to Pixelfed, then mentions may be converted to messages (but tentatively maybe not, and only messages addressed `to` or `cc` an actor will be successfully received on Pixelfed)

**Comment by dansup** [comment]
Fixed in latest commits!
