### ISSUE TITLE
Where to translate?

### ISSUE THREAD

**Issue by ahangarha** [pixelfed/pixelfed#1735]
Hi

I wanted to participate in translation of PixelFed into Persian language but I didn't find any clue where to start.

It is not hosted on https://hosted.weblate.org (the only floss translation solution). Is it anywhere else?

**Comment by trwnh** [comment]
Not yet; currently locales are stored as PHP arrays. We are working on a more convenient translation solution! 

See also #145

**Comment by kamazeuci** [comment]
I want to help translating to spanish, where is the translation project?
