### ISSUE TITLE
[Feature Request] Show Places in columns, not in rows

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#1742]
Let's take a look at https://pixelfed.social/discover/places
There are 3 columns on each page and they are visually separated one from another.

Honestly, I'd expect entries to go vertically in columns, but not in rows. So, for example, how it looks like:

```
A1          A2          A3
A4          B1          B2
C1          C2          D1
```

How it should look like:
```
A1          A4          C1
A2          B1          C2
A3          B2          D1
```

**Comment by okpierre** [comment]
@MasterGroosha are you asking for something like this?

![pixelfed-places-sort](https://user-images.githubusercontent.com/1679025/66008276-a31dd200-e483-11e9-9a82-318fa09bc0b5.png)

**Comment by MasterGroosha** [comment]
@okpierre yes

**Comment by dansup** [comment]
@MasterGroosha We don't use vertical columns for anything, we use grid rows. Instead of changing  the layout, we plan to add Places search support!
