### ISSUE TITLE
Failed profile update clears profile data

### ISSUE THREAD

**Issue by George-Payne** [pixelfed/pixelfed#1743]
Pixelfed 0.10.6
Tusky 9.0

Reproduction steps:
- Add account on Tusky
- Edit profile
- Add backdrop photograph

Outcome:
- Tusky crashes
- Clearing Tusky app data causes app to work again
- Adding account to Tusky again causes crashes 
- Visiting web UI shows `loading...` under username
- Account Settings (web UI) shows all fields empty

Filling out the `Name` field and saving (on web UI) allows account to be added to Tusky without crashes.

Expected Behaviour:
- Request is rejected without removing name field.

**Comment by dansup** [comment]
Fixed in latest commits!
