### ISSUE TITLE
Large JPEG file is converted to PNG

### ISSUE THREAD

**Issue by tateisu** [pixelfed/pixelfed#1744]
original file: JPEG 15.6MB 4912x7360 http://nextcloud.cross.lol/s/cjHCc8BCf4ewnLz 
uploaded post:  https://pixelfed.tokyo/p/tateisu/84583082539225088
image url : https://pixelfed.tokyo/storage/m/9415380b19c20b948c98d7c5f1fb65710b040a9e/3521a4b0694d36ecbb5df6f22ab3a72a2a773af7/xCX7vCoenCCaUoGdFT8dtYdQPvSMIr8qTxEqSUlH.jpeg

the file extension is jpeg, but image data is PNG, 13.1 MB 2730x4096.

What are the conditions image will be resized ? 
Other users can upload 6000x4000 image without resizing or format conversion.

**Comment by dansup** [comment]
@tateisu The image you linked is ```content-length: 99155```
```content-type: image/jpeg```.

**Comment by tateisu** [comment]
oh, sorry. It's my error about format conversion.
but how about the conditions image resize ?

**Comment by dansup** [comment]
@tateisu Images are resized based on 3 orientations like IG.

https://github.com/pixelfed/pixelfed/blob/73759fdeeb74df017d6070fcd30613340b4d8922/app/Util/Media/Image.php#L38-L49
