### ISSUE TITLE
Refactor component for unified grid-vs-list view

### ISSUE THREAD

**Issue by Grazouillis** [pixelfed/pixelfed#175]
Webdesign : it would be nice to suggest other visual presentations for the public timeline : inline and in grid. We could then see more pictures at first sight :)

**Comment by hellcp** [comment]
@dansup maybe it's worth considering moving all versions of image view into shared directory and let user switch between those two types of view (we got square one in user profile and list view in timelines) in timelines, profiles and discover.

**Comment by trwnh** [comment]
Yeah, and if we do so, then user profiles should also be viewable in list with descriptions, similar to Instagram. Kind of like a personal timeline of just one account. Also, if we use a grid display, then we can automatically reflow however many thumbnails fit on the screen.

**Comment by trwnh** [comment]
Profiles:
- [x] Grid view
- [x] List view

Timelines:
- [ ] Grid view
- [x] List view

Discover:
- [x] Grid view
- [ ] List view

Also maybe worth noting the grid view is currently 3-column and not a fully responsive "mosaic" gallery mode.

**Comment by dansup** [comment]
Pixelfed has established the appropriate list and grid views.

**Comment by trwnh** [comment]
Are we not going to unify them?
