### ISSUE TITLE
Tusky crashes when using pixelfed.social account

### ISSUE THREAD

**Issue by AlanSanchezP** [pixelfed/pixelfed#1754]
Tusky 9.0

Reproduction steps:
• Add pixelfed.social account on Tusky
• Go to local or federated timeline
• Scroll and interact with posts

Outcome:
• Tusky crashes

This only happens with my pixelfed.social account, browsing is pretty smooth on mastodon.

**Comment by wgahnagl** [comment]
if you update to the [latest version](https://github.com/tuskyapp/Tusky/releases), they've fixed those issues :ok_hand:

**Comment by AlanSanchezP** [comment]
@wgahnagl oh, I'm using the fdroid build, but it's good to know they already fixed that. You can close the issue then :blush:

**Comment by a-silvia** [comment]
This is actually happening to me with version 9.1 (unsure if it's exactly the same but sounds like the same problem)
