### ISSUE TITLE
Duplicate posts

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#1756]
Hello,

I don't really know if it is an error from the user or a glitch, but sometimes, i see many times the same photo on the public chronology.

**Comment by wgahnagl** [comment]
this might be way off base, but could this be because deletions aren't federating properly yet?

I have this error in my horizon 

```BadMethodCallException: Method Illuminate\Database\Eloquent\Collection::delete does not exist. in /home/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:104```

and I see a duplicate post from the user it references.

**Comment by dansup** [comment]
@stemy2 This bug is due to a race condition in the Timeline pagination, working on a fix.

**Comment by dansup** [comment]
@stemy2 It was actually an integer overflow issue, it is fixed in the latest commits.
