### ISSUE TITLE
Cannot upload photos with certain account

### ISSUE THREAD

**Issue by Victor-Morel** [pixelfed/pixelfed#1758]
Hello,
I set up an instance of pixelfed, which worked smoothly the first months.
But I'm now having issue uploading any (I tried with different images) photo: clicking the button ``Create a post'' does not result in anything.
I still can with other accounts, but the most used one cannot anymore.
I can't seem to find any help in my apache2 logs, and the /storage/logs/laravel.log are of no use.

I'm not sure whether it's a bug or a misconfiguration, any help would be welcomed!

Thanks for developing the software in any case

**Comment by dansup** [comment]
@Victor-Morel We need more information:

- Are you running the latest commits, what pixelfed version
- After updating, do you perform the proper post-deployment steps? (php artisan config:cache + php artisan route:cache + php artisan migrate)
- Are you having issues with ComposeUI v3 or ComposeUI v4 or both?

**Comment by Victor-Morel** [comment]
Hello Dan,
thanks for considering my issue.
I just updated to the latest commit, and performed the post-deployment steps you advised.
I had a warning:

> PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20170718/pdo_mysql (/usr/lib/php/20170718/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/pdo_mysql.so (/usr/lib/php/20170718/pdo_mysql.so: undefined symbol: pdo_parse_params)) in Unknown on line 0

But it went fine otherwise.

However, I still have the exact same issue, unlike now I do have an error message as a pop-up: 
> Oops, something went wrong!
> An unexpected error occurred.

**Comment by trwnh** [comment]
You have a problem with your PHP installation. Make sure you have support for the `pdo_mysql` plugin -- this is needed for the database driver. Your installation of Pixelfed cannot communicate with your database.

- Make sure your copy of PHP was either compiled with pdo_mysql, or that pdo_mysql is installed (for example, Arch has it prebuilt, but Debian and Ubuntu requires you to install `php-mysql`, and other distros may have other package names that need to be installed first)
- Your php.ini should have `Extension=pdo_mysql` uncommented
- When running `php -m`, the `pdo_mysql` extension should be listed as enabled
