### ISSUE TITLE
Public Discover

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1772]
Existing timeline will continue to show local posts (public timeline)

New option would allow admin to include posts from other instances within timeline

This will increase engagement for pixelfed instances

**Comment by Jookia** [comment]
Yeah this is something I miss from Mastodon. I really want to see what other art is out there, it feels a little like being punished for decentralizing.

**Comment by trwnh** [comment]
FWIW the current plan is actually to deprecate public timeline in favor of a reworked Discover (which should include local/remote content all the same). Public timelines on Mastodon have the potential to become unusable really quickly, and Pixelfed would like to encourage the usage of tags to actually allow finding specific types of posts.

**Comment by trwnh** [comment]
Closing this issue in favor of Github Projects: https://github.com/pixelfed/pixelfed/projects/14
