### ISSUE TITLE
Deleting a post decrements profile counter but not timeline sidebar counter

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1776]
An account with 4 posts deletes one of them from the timeline. The counter to the right of the timeline continues to say 4 posts, even after refreshing multiple times. Navigating to the profile shows 3 posts, and the counter there also says 3 posts. Going back to the timeline still shows 4 posts on the sidebar.

**Comment by dansup** [comment]
Fixed in latest commits
