### ISSUE TITLE
Switch Old Profile ID To New Format

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1780]
Noticed that ID format for profiles are mix

Some are in the format of xxx (ie: 145)

while others are in the format of xxxxxxxxxxxxxxxxx (ie: 65349553265399170)

Is there a tool to convert from one format to the latest?

**Comment by dansup** [comment]
@okpierre We transitioned to snowflake ids for profiles and statuses. We cannot change old ids because some profiles were created before the snowflake id epoch (February 2019)

**Comment by okpierre** [comment]
@dansup figure I report it just in case it was a bug. thanks for the explanation.
