### ISSUE TITLE
Adjust Footer Spacing In Mobile View

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1782]
The spacing allows for better "tap" on mobile web

### Current portrait view
![pixelfed-mobile-portrait-current](https://user-images.githubusercontent.com/1679025/66803166-d4b78400-eeec-11e9-97aa-fe5d2df9c8f8.png)

### Suggested portrait view
![pixelfed-mobile-portrait-suggested](https://user-images.githubusercontent.com/1679025/66803177-dd0fbf00-eeec-11e9-9802-8fe67da098d8.png)

### Current landscape view
![pixelfed-mobile-landscape-current](https://user-images.githubusercontent.com/1679025/66803064-8e622500-eeec-11e9-809f-94e6867167ef.png)

### Suggested landscape view
![pixelfed-mobile-landscape-suggested](https://user-images.githubusercontent.com/1679025/66803062-8b673480-eeec-11e9-802c-5f4a7fcf1981.png)

What do you think @dansup ?

**Comment by dansup** [comment]
@okpierre Great work, it looks much better now!

**Comment by okpierre** [comment]
@dansup good to hear! thanks!
