### ISSUE TITLE
[S3 storage] unable to get preview image when adding new post

### ISSUE THREAD

**Issue by cjeanneret** [pixelfed/pixelfed#1784]
Hello there,
I'm trying to deploy a pixelfed, **v0.10.6**. I've set up a [Minio](https://min.io/) service (s3-like), and configured pixelfed to use it for any storage:
```
  SetEnv FILESYSTEM_DRIVER "s3"
  SetEnv AWS_DEFAULT_REGION "us-east-1"
  SetEnv AWS_BUCKET "pixelfed"
  SetEnv AWS_URL "/"
  SetEnv AWS_ENDPOINT "https://objects.domain.tld"

```

Apparently, there are some issues with that use, or maybe I did it wrong, but:
- I had to add a ProxyPass for some paths in my httpd configuration:
```
  SSLProxyEngine On
  SSLProxyCheckPeerCN on
  SSLProxyCheckPeerExpire on
  ProxyPass "/public/avatars/" "https://objects.domain.tld/public/avatars/"
  ProxyPassReverse "/public/avatars/" "https://objects.domain.tld/public/avatars/"
  ProxyPass "/public/m/" "https://objects.domain.tld/public/m/"
  ProxyPassReverse "/public/m/" "https://objects.domain.tld/public/m/"
```

While it does help for the avatars, it apparently doesn't solve the issues I have while adding a new post/image:
- the image is uploaded to Minio (I can list and see it in the bucket)
- the preview doesn't work
After some more digging, the preview raises a 500 error, and I could find this in the lavarel logs:
```
[2019-10-15 18:05:46] production.ERROR: The file "/var/www/pixelfed/storage/app/public/m/9415380b19c20b948c98d7c5f1fb65710b040a9e/f61e3340f6a96129debfeb8cfd936a3a4244a6e8/ueCX2BgHmW6gF483iQp7bAK6wcb9C5RK0u1XEidR.
jpeg" does not exist {"userId":2,"exception":"[object] (Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException(code: 0): The file \"/var/www/pixelfed/storage/app/public/m/9415380b19c20b948c98d
7c5f1fb65710b040a9e/f61e3340f6a96129debfeb8cfd936a3a4244a6e8/ueCX2BgHmW6gF483iQp7bAK6wcb9C5RK0u1XEidR.jpeg\" does not exist at /var/www/pixelfed/vendor/symfony/http-foundation/File/File.php:36)
```

I'm wondering if the file shouldn't be uploaded locally first, and uploaded to the S3 backend only once the user posts the new content...
Or did I do anything wrong?

Thank you for your help!

Cheers,

C.

**Comment by dansup** [comment]
Hello, setting the ```FILESYSTEM_DRIVER``` to anything besides ```local``` is not recommended yet. Still have to tweak the S3 code which should be ready by v0.11

**Comment by cjeanneret** [comment]
Hello @dansup !
Thank you for your answer - does it mean that, for now, we shouldn't use S3 backend at all? What's the use of the other FILESYSTEM_CLOUD ? 

If S3 is a no-go, I'll wait for the 0.11 in order to continue my tests - I want to deploy pixelfed on 2 nodes, meaning a shared storage is a must (I've already have a galera cluster for other apps).

Feel free to ping me if you have things to test. My deploy isn't in prod, and I can crash it whenever I want :).

Cheers,

C.

**Comment by dansup** [comment]
@cjeanneret That is correct, S3 is not supported yet.
