### ISSUE TITLE
MAX_PHOTO_SIZE over 8MB ignored

### ISSUE THREAD

**Issue by matrix07012** [pixelfed/pixelfed#1786]
I have MAX_PHOTO_SIZE set to 20000, however when I try to upload a picture over 8MB, it fails with only Nginx giving me an error:
`FastCGI sent in stderr: "PHP message: PHP Warning:  POST Content-Length of 10468213 bytes exceeds the limit of 8388608 bytes in Unknown on line 0" while reading response header from upstream, client: IP, server: pixelfed.monster, request: "POST /api/pixelfed/v1/media HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "pixelfed.monster", referrer: "https://pixelfed.monster/i/compose"`

Setting MAX_PHOTO_SIZE under 8MB works just fine.

**Comment by dansup** [comment]
Check php.ini ```upload_max_filesize``` ```post_max_size``` and nginx ```client_max_body_size``` limits, don't forget to restart the webserver after changing them
