### ISSUE TITLE
When I like a post it should jump back to the post (non-JS)

### ISSUE THREAD

**Issue by faissaloo** [pixelfed/pixelfed#179]
If I'm like halfway down my timeline I don't want to have to scroll back.

**Comment by dansup** [comment]
Duplicate of #87

**Comment by faissaloo** [comment]
This isn't a duplicate, this can be implemented without any Javascript at all, just by having those buttons link to the current page with a # followed by the id of the element to jump to.

**Comment by trwnh** [comment]
Yeah, using section anchors (applying an #id to an element) is probably the best way to do it. You don't need JS if you do it in PHP. Assign each post a random dynamic anchor id and upon refreshing the page, load that anchor.

**Comment by trwnh** [comment]
Old non-JS frontend has been deprecated for Vue-enabled frontend; a new non-JS frontend will be implemented later
