### ISSUE TITLE
PF_OPTIMIZE_IMAGES=false not being used correctly

### ISSUE THREAD

**Issue by lapineige** [pixelfed/pixelfed#1797]
Hello,

Sometimes, the image optimizer seems to ruin the picture.
I have an use case where the picture uploaded is too compressed and looses all its fines details, which ruins the picture. (I also tried to set the maximum quality to 95, and upload a jpeg 95, still it destroys many details¹…).
The image is already optimized with personal settings, which allows me to reduce its weight without losing the fine details. I also chose an image size that is big enough to see the details, but not too big.

So I'd like to know if an (advanced) option to disable image optimizer, for a picture uploaded in PF, would be possible.

If you don't plan to add such an option, how can I manually do it when I need it ?
(which file should I edit ?)

*edit : someone told me to use `PF_OPTIMIZE_IMAGES=false`, and IMAGE_QUALITY=95, yet the final image size is ~50% smaller than the original one, and that kills all the fine details 🙁*
*edit 2 : I finally solved my issue by changing the max' values here: https://github.com/pixelfed/pixelfed/blob/dev/app/Util/Media/Image.php*

---

Bonus: disabling (on purpose) metadata removal could be a good option too, as sometimes the colour profile is needed to display it properly and (as far as I understand) is removed on upload.
But I'd prefer Pixelfed to keep all colour profile information by default.

¹ Does it use the optimizer even on an image bellow the max quality parameter ? Because on a jpeg, that mean compressing an already compressed image, which can be pretty bad :(

--- 

**Alternative proposal**: instead of just disabling all image optimisation and size reduction, could we have a kind of `high quality upload` option, with no image optimisation (or with an higher quality value ?) and a maximum size that is bigger ?

**Comment by lapineige** [comment]
> PF_OPTIMIZE_IMAGES=false not being used correctly

Could I ask for an explanation of what I was doing wrong here ? :)

**Comment by lapineige** [comment]
:up: :)

Could you please explain what was not used correctly, or at least how can I disable this optimization and/or size reduction ?
It's a real trouble that we can't upload a picture and make it look the same on Pixelfed than the file we worked on, especially when it ruins final image quality :cry:

**Comment by lapineige** [comment]
To document the workaround I found:
> edit 2 : I finally solved my issue by changing the max' values here: https://github.com/pixelfed/pixelfed/blob/dev/app/Util/Media/Image.php

To increase final image size (thus reduce loss of detail and artifacts) you can edit this file starting here https://github.com/pixelfed/pixelfed/blob/dev/app/Util/Media/Image.php#L39 (located in your pixelfed folder `/app/Util/Media/Image.php`) and increase each of the six "max size" values. Then your picture will have this maximum size.

NB: this is a dirty hack that I tried because I found no other solution (and the lack of documentation/explanation didn't help), I don't really understand what this code is supposed to do, hence apart from bigger files I don't know what could be the side effects…
Use it at your own risk.

**Comment by jimmybrancaccio** [comment]
`PF_OPTIMIZE_IMAGES` doesn't seem to be used anywhere in the code beyond the configuration file. The above hack didn't seem to work for me, but I was able to do this to prevent Pixelfed from jacking with my image quality.

In the `app/Jobs/ImageOptimizationPipeline/ImageResize.php` file. You can either remove the code, or comment it out like I did.

```php
<?php

namespace App\Jobs\ImageOptimizePipeline;

use App\Media;
use App\Util\Media\Image;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class ImageResize implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected $media;

    /**
     * Delete the job if its models no longer exist.
     *
     * @var bool
     */
    public $deleteWhenMissingModels = true;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(Media $media)
    {
        $this->media = $media;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        $media = $this->media;
        // if(!$media) {
        //     return;
        // }
        // $path = storage_path('app/'.$media->media_path);
        // if (!is_file($path) || $media->skip_optimize) {
        //     return;
        // }

        // try {
        //     $img = new Image();
        //     $img->resizeImage($media);
        // } catch (Exception $e) {
        // }

        ImageThumbnail::dispatch($media);
    }
}
```

**Edit:** Discord discussion (with myself) - https://discord.com/channels/446875483016134658/805369031876018207/902722454332526672

**Comment by jimmybrancaccio** [comment]
@dansup @trwnh This should be re-opened as the original title of the issue was changed to 'PF_OPTIMIZE_IMAGES=false not being used correctly' however the issue was closed without any information provided on how it was used incorrectly and how to correctly use it.

**Comment by dansup** [comment]
Fixed in the latest commits!

**Comment by lapineige** [comment]
Sounds great :)
In what way ?
