### ISSUE TITLE
Update README.md with installation instructions

### ISSUE THREAD

**Issue by dansup** [pixelfed/pixelfed#18]

**Comment by MrPetovan** [comment]
If it can help you refine installation instructions, I did 
```
bash> git clone ...
bash> composer install --no-dev
bash> chmod a+x artisan
mysql> CREATE NEW DATABASE pixelfed CHARACTER SET utf8mb4;
mysql> GRANT ALL ON pixelfed.* TO 'pixelfed'@'localhost' IDENTIFIED BY '...';
bash> nano config/database.php
bash> ./artisan migrate:fresh
```
and I got 
```
SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. (SQL: alter table `users` add unique `users_username_unique`(`username`))
```

Additional information:

```
bash> mysqld --version
mysqld  Ver 10.1.26-MariaDB-0+deb9u1 for debian-linux-gnu on x86_64 (Debian 9.1)
```

my.cnf:
```
innodb_large_prefix   = 1
innodb_file_format    = BARRACUDA
innodb_file_per_table = 1
```

**Comment by kpcyrd** [comment]
@MrPetovan you might want to file this as a separate issue

**Comment by MrPetovan** [comment]
There are quite a number of open issues already, I didn't want to pile on, but sure.

**Comment by MrPetovan** [comment]
Crude installation instructions for Debian 9/Apache/MariaDB:

1. `shell> apt install jpegoptim`
1. `shell> git clone https://github.com/dansup/pixelfed /path/to/pixelfed`
2. `shell> cd /path/to/pixelfed`
3. `shell> composer install --no-dev` ([Composer install](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx))
4. `mysql> CREATE NEW DATABASE pixelfed CHARACTER SET utf8mb4;`
`mysql> GRANT ALL ON pixelfed.* TO 'pixelfed'@'localhost' IDENTIFIED BY '...';`
5. `shell> cp .env.example .env`
6. `shell> php artisan key:generate`
6. `shell> php artisan storage:link` (#141)
7. `shell> nano .env` (edit database settings, hostname, etc...)
8. Enable this hack: https://github.com/dansup/pixelfed/issues/132#issuecomment-394056991
9. `shell> php artisan migrate:fresh`
10. Set the `DocumentRoot` in your Apache vhost to `/path/to/pixelfed/public`
11. Voila! 🎉

**Comment by MrPetovan** [comment]
Is there any cronjob to install I should know about?

**Comment by MrPetovan** [comment]
Alpha installation instruction: https://gist.github.com/dansup/999de4577f864d1822d226b9ddd62ca0#file-installation-md
