### ISSUE TITLE
pixelfed.social v0.10.6 mobile app support

### ISSUE THREAD

**Issue by c33s** [pixelfed/pixelfed#1801]
> pixelfed.social has disabled mobile app support
> 
> It will be available after v0.10.7 is released! #pixelfed

https://mastodon.social/@dansup/102914431144158811

aka when is v0.10.7 released? and what does "after" mean in time? also why has it been removed?

for reference the fedilab issue https://framagit.org/tom79/fedilab/issues/312

**Comment by trwnh** [comment]
this repo is for the pixelfed project, not the pixelfed.social website. questions about pixelfed.social should be directed at their admin

**Comment by c33s** [comment]
@trwnh so it should work to access pixelfed with fedilab? was not possible for me, so i read that as pixelfed disabled mobile support / mobile support is broken and will be fixed in 0.10.7. 

so this is not true and it simply should work?

**Comment by trwnh** [comment]
@c33s I'm not sure, you'll have to ask dansup. Some instances support mobile apps, some do not. It is currently an optional feature because it is not complete.

**Comment by c33s** [comment]
@trwnh this is what i am trying to do here. maybe reopen this, so other searchers also find this.

**Comment by gbraad** [comment]
dansup has messaged tht this might be fixed over the weekend when the update goes out. At the moment the pixelfed.social instance as mobile support disabled due to an issue with the oauth authentication IIRC. but as mentioned, this is not an issue with pixelfed or fedilab, but with the server instance.

Note: please modify the title to reflect this concerns the pixelfed.social instance (as the issue is invalid and does not serve much help to others experiencing this).

**Comment by gbraad** [comment]
Ref: https://mastodon.social/@pixeldev/103061105985619862

---

We have identified and fixed the 2FA auth flow bug affecting the OAuth APIs.

This will be shipping in v0.10.7, bringing mobile support back to instances like pixelfed.social!

We expect v0.10.7 to be released this weekend, so stay tuned 🚀 

#pixeldev
November 1, 2019, 1:54 PM

**Comment by neslihanturan** [comment]
Pixelfed.social still doesn't work for me with Fedilab, on Android 7.1.1. However, my friend with Android 10 is able to connect his pixelfed.social account via Fedilab. Can it be time to re-open this issue in this case?

Edit: Well, some more friends with Android 7, 10 and 10 reported they are able to use the app for pixelfed.social with no problem. And one more friend with Android 8 reported she is not able to connect her pixelfed.social. All tests are from Fedilab 2.36.2. What kind of information would help you to debug this issue?

**Comment by kabo** [comment]
Looks like there's a [fedilab ticket](https://framagit.org/tom79/fedilab/-/issues/444) for it, but it's saying it's a pixelfed bug.
