### ISSUE TITLE
Same post is displayed twice on timeline

### ISSUE THREAD

**Issue by efelon** [pixelfed/pixelfed#1803]
Pixelfed 0.10.6
Nginx/PHP7.3

![image](https://user-images.githubusercontent.com/10722552/68012187-a924ef80-fc89-11e9-9cc6-9b52a413fbf2.png)

Directly after posting this particular post, it did not show twice in the timeline when it was the latest post. I recognized the duplication only after posting other posts (I can't remember if it shows already after one new post or more). Please see the blue marking and the following line.

As well es described in issue #47, the duplication only affects the timeline but not the profile page and not the discovery page. Post count is also correct.

I didn't find any log messages and I'm also aware that this is not much information and hard to reproduce. Maybe someone has a similar issue or any hint what to do.

As a workaround I would try to delete this post and redoing it, if no one requests more information from me.

**Comment by dansup** [comment]
@efelon Are you running the latest dev branch commits? This bug was fixed in fbef897

**Comment by efelon** [comment]
> Are you running the latest dev branch commits?

@dansup No, I don't. I'm on 0.10.6 and going from tag to tag. Since I can't invest much time I feel saver doing it like that. Btw. can't wait for 0.10.7 ;)
