### ISSUE TITLE
Unable to connect via Zap

### ISSUE THREAD

**Issue by redmatrix** [pixelfed/pixelfed#1810]
Zap now supplies a signed Date header solely for pixelfed's benefit since no other fediverse software requires it. We don't supply these normally because there are a range of associated issues which will come back to haunt all of us until we can eventually convince pixelfed to do away with them. But we'll save that for another day. Anyway now Follow activities from Zap are accepted by pixelfed and then lost in space with no acknowledgement or notification. 

````
{
  "@context":[
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    "https://p3.macgirvin.com/apschema/v1.13"
  ],
  "id":"https://p3.macgirvin.com/follow/43",
  "type":"Follow",
  "actor":"https://p3.macgirvin.com/channel/otest",
  "object":"https://fedgram.com/randyr",
  "to":[
    "https://fedgram.com/users/randyr"
  ],
  "signature":{
    "@context":[
      "https://www.w3.org/ns/activitystreams",
      "https://w3id.org/security/v1",
      "https://p3.macgirvin.com/apschema/v1.13"
    ],
    "type":"RsaSignature2017",
    "nonce":"6adc64cb7df03c419b1e74fe38098dbcc480e4f489a90b93b0c277237a95130a",
    "creator":"https://p3.macgirvin.com/channel/otest",
    "created":"2019-11-03T11:12:36Z",
    "signatureValue":"I91BQD48Wuc4Nr6YCeGYOe15NyKb0dPPeV00J/uNOqrdS/d3bw2CEnBHYwqwwERwF2KYyZz2kaoZwAmt9hJ3YERk4LRXH8RZQKlhP5tkeGQMqqkRY0DSpZSw+zckwn3Yf1DXAOxVMuLzFAF7J6WlXoMwvRvQIT7xXlD73E9n3zD3WlEf3hBrcMbme7ekoHzkmwYsSfcJow8peSRKi4l+NRwj+4vAwrZFh+9Nr12civdpkWhWQlF4RH0Zvjop0R53GVxMGfZ12L5fLn2aK1ATOvph6Jz53/PSBfNRcFK4PRLII9dbYLZusKdyzrIJ88MSsxb87MClvhjVtxTlRc++AnZCXrqA7LTNSWRTZ1MEtjWa+sKBlXAKzoKL/RLDiHcVf+XmwQ8HAMCBAMx5EDVdkEgv6yREnOOlGgIbMRVvFgOkJkxXqQyo7Ek2gkgVkehgV+yW1btZIod+YAbldO7zu7aoNpxZrMI5Nod0MwMSvewFNF03LsLmz6WcbxMRgeA1OcqouHU2WvbnM0B5d2mlCvT7HdRT7dV508hZbvW58qI2zWnhUMqHD/tq7EQ50Fj6MuChZzqmyo7FDs6ppqo8031IWhI6Cq6CakQQujnLcNeimd1XMNnAfo8ka1m/2ufHU1TsqR9D0X1geZmHwumwqZgVhtYo8w16CSus7yuekMI="
  }
}
````

**Comment by dansup** [comment]
@redmatrix I was under the impression the ```Date``` header was to be signed according to the documentation. If its causing compatibility issues, we will remove that constraint.

With regards to missing Follower notifications, this is a known issue. We are not generating many notification types from federated sources and I hope to get that fixed soon!

**Comment by redmatrix** [comment]
The Follow activity is silently consumed with an HTTP 2xx return but does not appear to generate a new follower.  I'll probably need to try this with a pixelfed developer to track down what is happening on that side of the connection - but we're on opposite sides of the planet and this could be difficult to coordinate.

**Comment by redmatrix** [comment]
On the subject of signing the Date header, we typically avoid it because verifying dates in a decentralised world is fraught with issues. Networked file systems run into issues all the time with date mismatches and virtual machines lose clockticks if they are loaded down and eventually drift out of compliance. The purpose of using the date header for http signatures is to make it more difficult to perform a replay attack, but one has to provide enough "slop" (Pixelfed apparently checks for +- 1 day) that it doesn't really perform this task reliably. 

The httpsignature spec defaults to signing the date header if nothing else was specified, but most projects try to generate a good collection of header fields that make it difficult to replay (server, request-method, digest, etc.) and adding the date header doesn't really improve on this. If the date check is too tight to account for normal drift it will actually cause more problems than it solves. We can certainly add it (and I've done so to allow testing with pixelfed to proceed), but ultimately it can create intermittent or occasional networking issues which are very difficult to track down especially if another project uses a small value for "slop". I would prefer not to be forced to use it.

**Comment by dansup** [comment]
@redmatrix We have identified some issues with Friendica/Hubzilla/Zap federation and working on fixing those bugs!

**Comment by redmatrix** [comment]
Are you willing to share anything you've discovered? If it's something we don't care passionately about, we could probably change something on our side just to move forward. The Hubzilla folks identified an issue with having 'url' in the activity and made progress on that project, but the same fix didn't work for Zap. These projects are originally from the same family but the ActivityPub implementations are quite different.
