### ISSUE TITLE
Notification from remote users fails because profile_id is null

### ISSUE THREAD

**Issue by hyde-stevenson** [pixelfed/pixelfed#1811]
Hello,

It looks like when I try to follow from mastodon or maybe not directly linked, I get this message in my postgresql logs  : 

2019-11-04 12:53:56.486 CET [8126] user@pixelfed DETAIL:  Failing row contains (24, null, null, null, null, null, null, 2019-11-04 11:53:56, 2019-11-04 11:53:56, null, null, null).
2019-11-04 12:53:56.486 CET [8126] user@pixelfed STATEMENT:  insert into "notifications" ("updated_at", "created_at") values ($1, $2) returning "id"

I found in laravel.log also this :

2019-10-29 16:27:53] production.ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "profile_id" violates not-null constraint
DETAIL:  Failing row contains (13, null, null, null, null, null, null, 2019-10-29 16:27:53, 2019-10-29 16:27:53, null, null, null). (SQL: insert into "notifications" ("updated_at", "created_at") values (2019-10-29 16:27:53, 2019-10-29 16:27:53) returning "id") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"profile_id\" violates not-null constraint
DETAIL:  Failing row contains (13, null, null, null, null, null, null, 2019-10-29 16:27:53, 2019-10-29 16:27:53, null, null, null). (SQL: insert into \"notifications\" (\"updated_at\", \"created_at\") values (2019-10-29 16:27:53, 2019-10-29 16:27:53) returning \"id\") at /html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"profile_id\" violates not-null constraint
DETAIL:  Failing row contains (13, null, null, null, null, null, null, 2019-10-29 16:27:53, 2019-10-29 16:27:53, null, null, null).

**Comment by hyde-stevenson** [comment]
I dropped the not null constraint in the notifications table and I dont get any more the error when I favourite a pic from mastodon.

**Comment by trwnh** [comment]
I think the real issue is that `profile_id` is null for remote users?

**Comment by hyde-stevenson** [comment]
Actually you're right but wasn't sure what it was supposed to get and if the profile_id could be null.

**Comment by trwnh** [comment]
Just to be clear, you were following a Pixelfed user from within Mastodon, right?

**Comment by hyde-stevenson** [comment]
Yeah my Pixelfed account from my Mastodon account.

**Comment by dansup** [comment]
> I think the real issue is that `profile_id` is null for remote users?

Nope, remote and local users have ```profiles``` record, only local users have ```users``` record. This is a bug in the inbox handler.

**Comment by trwnh** [comment]
Somewhere around this line? https://github.com/pixelfed/pixelfed/blob/26c47a0d3ac2296228398f623fd734fb9b2ceb23/app/Util/ActivityPub/Inbox.php#L183

https://github.com/pixelfed/pixelfed/blob/26c47a0d3ac2296228398f623fd734fb9b2ceb23/app/Util/ActivityPub/Inbox.php#L159-L208

Tracing the actor fetch leads to this:
https://github.com/pixelfed/pixelfed/blob/f7aeb8f4333994b72a97b236f5440f382195ec3e/app/Util/ActivityPub/Helpers.php#L381-L432

**Comment by BenLubar** [comment]
https://github.com/pixelfed/pixelfed/blob/26c47a0d3ac2296228398f623fd734fb9b2ceb23/app/Util/ActivityPub/Inbox.php#L182-L190

Here's the PostgreSQL error log created by this function call:

```
ERROR:  null value in column "profile_id" violates not-null constraint
DETAIL:  Failing row contains (18, null, null, null, null, null, null, null, null, 2019-11-28 22:13:07, 2019-11-28 22:13:07, null).
STATEMENT:  insert into "notifications" ("updated_at", "created_at") values ($1, $2) returning "id"
```

**Comment by myrrhashad** [comment]
Hello.
With a fresh install on Yunohost, I have the same issue (follows from Mastodon fail because of "null value in column "profile_id""). Is there a way to fix this ?
