### ISSUE TITLE
Public/local timeline naming inconsistency

### ISSUE THREAD

**Issue by rootkea** [pixelfed/pixelfed#1822]
Hello!

On https://pixelfed.social/discover there is a link titled "[local](https://pixelfed.social/timeline/public) timelines" pointing to https://pixelfed.social/timeline/public while the dropdown profile menu has a link titled [Public Timeline](https://pixelfed.social/timeline/public) pointing to the same URL.

This is inconsistent behavior. We should either call https://pixelfed.social/timeline/public a local timeline or a public timeline.

Thanks!
![pixelfed](https://user-images.githubusercontent.com/2694559/68972069-da9dcf00-07e2-11ea-9319-836dea3f1d73.png)

**Comment by trwnh** [comment]
Best to track this in one issue instead of two. Closing in favor of #1823

**Comment by rootkea** [comment]
umm okay. Since #1823 talks about home timeline naming inconsistency and this issue is about public timeline naming inconsistency, I'm copy-pasting the issue description there.
