### ISSUE TITLE
Names of timelines are inconsistent in Discover vs. dropdown menu

### ISSUE THREAD

**Issue by rootkea** [pixelfed/pixelfed#1823]
Hello!

The navbar has a home icon with text "Home timeline" pointing to the https://pixelfed.social/ while the dropdown profile menu has a link titled "My Timeline" pointing to the same URL.

This is inconsistent behavior. We should either call it a "Home timeline" or a "My timeline".

Thanks!
![pixelfed](https://user-images.githubusercontent.com/2694559/68972833-99a6ba00-07e4-11ea-81be-8e929dc9d86a.png)

**Comment by rootkea** [comment]
Also the link title "Logo" for the same link doesn't feel right either.
![pixelfed](https://user-images.githubusercontent.com/2694559/68974224-1d15da80-07e8-11ea-812e-b4927b01f8ad.png)

**Comment by rootkea** [comment]
Also,

On https://pixelfed.social/discover there is a link titled "[local](https://pixelfed.social/timeline/public) timelines" pointing to https://pixelfed.social/timeline/public while the dropdown profile menu has a link titled [Public Timeline](https://pixelfed.social/timeline/public) pointing to the same URL.

This is inconsistent behavior. We should either call https://pixelfed.social/timeline/public a local timeline or a public timeline.

![pixelfed](https://user-images.githubusercontent.com/2694559/68972069-da9dcf00-07e2-11ea-9319-836dea3f1d73.png)

**Comment by rootkea** [comment]
> Also the link title "Logo" for the same link doesn't feel right either.
> ![pixelfed](https://user-images.githubusercontent.com/2694559/68974224-1d15da80-07e8-11ea-812e-b4927b01f8ad.png)

This is still not fixed. The link title should be "Home" or "Home Timeline" instead of "Logo".

**Comment by rootkea** [comment]
> Also,
> 
> On https://pixelfed.social/discover there is a link titled "[local](https://pixelfed.social/timeline/public) timelines" pointing to https://pixelfed.social/timeline/public while the dropdown profile menu has a link titled [Public Timeline](https://pixelfed.social/timeline/public) pointing to the same URL.
> 
> This is inconsistent behavior. We should either call https://pixelfed.social/timeline/public a local timeline or a public timeline.
> 
> ![pixelfed](https://user-images.githubusercontent.com/2694559/68972069-da9dcf00-07e2-11ea-9319-836dea3f1d73.png)

This is also not fixed yet. The url https://pixelfed.social/timeline/public is referenced as both "Local" timeline and "Public" timeline in the UI which is illogical.

Maybe I should open a new issue?

**Comment by trwnh** [comment]
"Logo" is alt text and is fine. Public timeline and local timeline currently mean the same thing, and in any case, it is going to be deprecated in favor of Discover in the near future.

**Comment by rootkea** [comment]
> Public timeline and local timeline currently mean the same thing, and in any case, it is going to be deprecated in favor of Discover in the near future.

That's good to know but till that happens should "Public" and "local" timeline should point to same url? Especially when Public x local (antonymous)

Anyways, thanks for replying! :)
