### ISSUE TITLE
Query Exception at migrating database

### ISSUE THREAD

**Issue by rototom** [pixelfed/pixelfed#1824]
This happens while do:
php artisan migrate --force

sudo -u www-data php artisan migrate --force
Migrating: 2018_04_16_005848_create_statuses_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1 (SQL: create table `statuses` (`id` bigint unsigned not null auto_increment primary key, `uri` varchar(191) null, `caption` varchar(191) null, `rendered` text null, `profile_id` bigint unsigned null, `in_reply_to_id` bigint unsigned null, `reblog_of_id` bigint unsigned null, `url` varchar(191) null, `is_nsfw` tinyint(1) not null default '0', `visibility` enum('public', 'unlisted', 'private', 'direct') not null default 'public', `reply` tinyint(1) not null default '0', `likes_count` bigint unsigned not null default '0', `reblogs_count` bigint unsigned not null default '0', `language` varchar(191) null, `conversation_id` bigint unsigned null, `local` tinyint(1) not null default '1', `application_id` bigint unsigned null, `in_reply_to_profile_id` bigint unsigned null, `entities` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:665
    661|         // If an exception occurs when attempting to run a query, we'll format the error
    662|         // message to include the bindings with SQL, which will make this exception a
    663|         // lot more helpful to the developer instead of just the database's errors.
    664|         catch (Exception $e) {
  > 665|             throw new QueryException(
    666|                 $query, $this->prepareBindings($bindings), $e
    667|             );
    668|         }
    669| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1")
      /var/www/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1")
      /var/www/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61

  Please use the argument -v to see more details.

**Comment by rototom** [comment]
I updated to mysql 10.4, which solved the issue.

**Comment by reavessm** [comment]
> I updated to mysql 10.4, which solved the issue.

Mysql or MariaDB?
