### ISSUE TITLE
Problem: "Add photo to collection" doesn't work reliably

### ISSUE THREAD

**Issue by jwildeboer** [pixelfed/pixelfed#1825]
When I want to add photos to a collection, the workflow is rather unintuitive and unfortunately IMHO buggy.

To add a photo to a collection I have to first post it as a public post and then go to My Profile, Collections, Add Photo. (It would be simpler to have a dropdown or sth in the post dialog where I can add this picture(s) to a collection straight away.)

But that popup seems to fail on me 90% of the time. It lists recent posts, but clicking on one doesn't result in its URL being added. I have been able to reproduce this with Firefox 68.2 on Linux, iOS 13.2.2 on iphone.

I click on a recent post and nothing happens.

**Comment by jwildeboer** [comment]
![Screenshot from 2019-11-18 13-23-15](https://user-images.githubusercontent.com/873028/69052234-d651fb80-0a06-11ea-974c-c5176e8610bc.png)
No matter how often I click on any of the recent posts, the URL field does not get updated. Firefox 68.2 on Linux. Same wihen trying on my iPhone (iOS 13.2.2)

**Comment by trwnh** [comment]
The compose UI is currently being redesigned to allow adding to a collection immediately before submitting a new post. It will be added to the reworked "advanced settings" flow.

**Comment by trwnh** [comment]
It seems additionally there is an issue with the "add photo" dialog which seems to have lost its events in a recent refactor, perhaps... that would be why clicking the thumbnail seems to do nothing. Because it actually does do nothing. Whoops!

**Comment by jwildeboer** [comment]
Thank you! Yes, that solves my problem. Additional thought: Auto-add to collections based on hashtags? IF a collection has a hashtag as name, THEN add posts with that hashtag to that collection.

Or even simpler - automagically create collections based on hashtags, but not as public collections. So that the user can a) find related posts and b) decide to make a hashtag public as collection should he/she/they so desire.

But that does start to feel a lot more like tags and not like collections, I guess.

**Comment by trwnh** [comment]
Fixed, I think? EDIT: Yep.
