### ISSUE TITLE
Allow following Discover categories

### ISSUE THREAD

**Issue by rootkea** [pixelfed/pixelfed#1829]
Hello!

I know that we can follow tags e.g. nature tag at https://pixelfed.social/discover/tags/nature but is it possible to follow Discover categories e.g. nature category at https://pixelfed.social/discover/c/nature ?

It seems that Discover category is a collection of related tags. e.g. Nature category has #nature #hiking #mountains etc. tags. So it would be great if I could follow the category instead of following each of those tags.

Thanks!

**Comment by dansup** [comment]
No plans to merge this feature.

**Comment by trwnh** [comment]
Why not?

**Comment by rootkea** [comment]
I think allowing user to follow the category instead of following each of the tags constituting that category would be a real help and a nice addition to PixelFed .
