### ISSUE TITLE
Embed Multiple Images Set does not work

### ISSUE THREAD

**Issue by xmgz** [pixelfed/pixelfed#1838]
## Testing Embed Feature

Copy/paste provided iframe code directly on .html page without any other script 

- single photo set works as expected
- multiple photo posts do not, returning a 404-like error

[Here a test page a build for testing my own photos](http://xmgz.eu/pixelfed.html)

with images from diferent users (pixelfed.social)

**If it's not posible ATM** embed multiple images, the iframe should load the first image of the group (i.e.) and not this 404, IMO.

there's 
#776  
also, so feel free to close this issue if related and repeated.

**Comment by trwnh** [comment]
yeah #776 isn't finalized, there's still work to be done in making the embed work for album posts
