### ISSUE TITLE
"Untitled Post" with MomentUI 

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1842]
Captation is set.

![Memo posted a photo  2 likes](https://user-images.githubusercontent.com/58190287/69721176-91b81580-1114-11ea-8d61-f7ee8f2bd177.png)

![MVO Pixel](https://user-images.githubusercontent.com/58190287/69721183-97156000-1114-11ea-9cb7-74339b02e2c3.png)

**Comment by trwnh** [comment]
Moment UI's title extraction is not perfectly reliable IIRC, and there isn't yet a way to explicitly set a `name`

**Comment by ghost** [comment]
Okay - didn't know that this is a known issue 😇

**Comment by trwnh** [comment]
Duplicate of #1689
