### ISSUE TITLE
ActivityPub GET requests are not signed

### ISSUE THREAD

**Issue by BenLubar** [pixelfed/pixelfed#1850]
ActivityPub GET requests are not signed. This means any Mastodon instance with `AUTHORIZED_FETCH` enabled (which is most of them now that more people are on 3.0.0) cannot follow a Pixelfed user due to the `outbox` property not being sent to unsigned requests.

**Comment by trwnh** [comment]
i'm not sure authorized fetch is enabled on "most of them", but also i'm not sure how that affects anything. doesn't authorized fetch only matter when trying to GET from mastodon?

**Comment by BenLubar** [comment]
Yes, and Pixelfed tries to fetch a user's profile the first time it sees them in order to verify they exist.

Mastodon replies with something like this (formatting added for readability)

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
      "toot": "http://joinmastodon.org/ns#",
      "featured": {
        "@id": "toot:featured",
        "@type": "@id"
      },
      "alsoKnownAs": {
        "@id": "as:alsoKnownAs",
        "@type": "@id"
      },
      "movedTo": {
        "@id": "as:movedTo",
        "@type": "@id"
      },
      "schema": "http://schema.org#",
      "PropertyValue": "schema:PropertyValue",
      "value": "schema:value",
      "IdentityProof": "toot:IdentityProof",
      "discoverable": "toot:discoverable",
      "Emoji": "toot:Emoji",
      "focalPoint": {
        "@container": "@list",
        "@id": "toot:focalPoint"
      }
    }
  ],
  "id": "https://mastodon.lubar.me/users/ben",
  "type": "Person",
  "inbox": "https://mastodon.local.lubar.me/users/ben/inbox",
  "preferredUsername": "ben",
  "publicKey": {
    "id": "https://mastodon.lubar.me/users/ben#main-key",
    "owner": "https://mastodon.lubar.me/users/ben",
    "publicKeyPem": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxNxJKq6YLlX/CUk6c6oB\nOtCZMvPEqrvG53OOKDFQB0Nz/u7nNIaMblLUplaDjkp6aiuE4IGWC0cbT07UY552\nHuFcppxLyhN344FKry
Mr9DqvVaR4szbEfhJyGqFLcNJacZiQda2fV2OH3C+k3e2G\n8tMn/p75Q8FpMn67zekXJqu1RozjwmrNgp52xshl23PuqLA42yCGprw66HOthbZ3\nnvLQcnUOj7c7UBX7uO3Fij/1YVazuZB1t4+4rM8DAvg9Om+z2AjsXUK6jbn+slNY\nf0anF0c6rMNEOa8hF9C
lsaiU8Adm150OFJU+75V9f25f8gD/XXEHBZcirYQ5XzKh\n3wIDAQAB\n-----END PUBLIC KEY-----\n"
  },
  "endpoints": {
    "sharedInbox": "https://mastodon.local.lubar.me/inbox"
  }
}
```

This doesn't contain an `outbox` property, so Pixelfed decides it's not a real profile and bails.

**Comment by dansup** [comment]
It's somewhat ironic that Pixelfed requires an outbox attribute considering we've supported the ability to disable them (pixelfed.social has disabled outboxes for months). Working on a fix!

**Comment by c-cesar** [comment]
Probably related to this, a user with a recent account on PixelFed can't be followed from Mastodon 3.x and Pleroma 1.1.X, and comments to their photos are not showed. 
Likes worked.
Interaction from 2.X is working OK.

Testing from a 3.X with secure fetch disabled follow and likes works, but not commenting.

**Comment by renatolond** [comment]
We're also having this issue, users in our Mastodon instance (using 3.1.3, with secure fetch enabled) cannot follow Pixelfed users or comment on their posts.

**Comment by BenLubar** [comment]
it looks like all that needs to be done is hooking up `app/Util/ActivityPub/Helpers` to `ActivityPubFetchService`

**Comment by es-ka** [comment]
Is there any news on that issue?
I have a account on http://chaos.social (Mastodon 3.1.5) and I can't follow my own pixelfed instance, but I'm not sure if it is related...

**Comment by dunn** [comment]
>  moved this from In progress to Done in Federation 

should this be fixed on staging? i'm having the same issue following from mastodon with an instance running on the latest commit from the staging branch

**Comment by dunn** [comment]
any movement on this? afaict until this is fixed pixelfed can't interact with any of the other major fedi services

**Comment by elouin** [comment]
Marked as done since a year. Is there an ETA for this in the releases?

**Comment by 0xa** [comment]
hello, just confirming that this still happen on v0.11.3:
i cannot interact with pixelfed from a mastodon instance with AUTHORIZED_FETCH enabled.
the InboxValidator job succeeds, but it doesnt pull the profile or display any notification inside pixelfed.
it seems to work fine on an instance without AUTHORIZED_FETCH

**Comment by trwnh** [comment]
i'm not sure if this is it but i've been told to please double-check that you ran `php artisan instance:actor`

the relevant code is here:

https://github.com/pixelfed/pixelfed/blob/de9573bf6e84f67c33359c0c9a68dc440cb89602/app/Services/ActivityPubFetchService.php#L18

https://github.com/pixelfed/pixelfed/blob/de9573bf6e84f67c33359c0c9a68dc440cb89602/app/Util/ActivityPub/HttpSignature.php#L36-L57

**Comment by 0xa** [comment]
thanks, the instance actor exists on the pixelfed side, but when mastodon tries to query it back with webfinger (during validation), it gets a 400 error. it seems to be the case on pixelfed.social as well:
`https://pixelfed.social/.well-known/webfinger?resource=acct:pixelfed.social@pixelfed.social`

**Comment by ntadej** [comment]
Just to add that on a new instance of Mastodon running v4.0.0rc3 I can not follow my account on pixelfed.social - it says pending approval. It may have to do with recently announced federation issues, but I see that the follow in the other direction happened already. Will report back if things change.

**Comment by AndrewNatoli** [comment]
👋  I'm seeing this as well. Follows, likes, and boosts from Mastodon don't seem to be reflecting on pixelfed.social

**Comment by kevinveenbirkenbach** [comment]
~~I have the same issue 😢 I try to follow my [pixelfed account](https://pixelfed.veen.world/i/web/profile/498496141291315201) with my [mastodon account](https://mastodon.veen.world/@kevinveenbirkenbach) but this doesn't work...
I used the following ansible role to setup pixelfed with docker-compose behind a reverse proxy: https://github.com/kevinveenbirkenbach/server-playbook/tree/master/roles/docker-pixelfed~~

Update: In my case it was just a configuration issue. I forgot to activate ActivityPub. 
Now it's solved: https://github.com/kevinveenbirkenbach/server-playbook/commit/b7440494910ac69b5965d480997fb9f1da5ed6b0

**Comment by oculos** [comment]
It stopped working for me. I don't know if it is because I moved my redis installation. All the activityPub settings are `true`, I see that all activity coming from other instances is received and processed by Horizon. Still, nothing seems to happen.
