### ISSUE TITLE
Displaying temporary media broken in php 7.4

### ISSUE THREAD

**Issue by nougad** [pixelfed/pixelfed#1852]
System: Arch linux with php 7.4.0-2 and pixelfed 0.10.6

The comparison for `Auth::user()->profile_id !== $profileId` is broken because `Auth::user()->profile_id` is a string but the parameter `$profileId` is declared as `int`. That results into:

```
[Sun Dec  1 01:04:33 2019] [::1]:45112 [404]: GET /i/media/preview/106535038996320256/8?expires=1575161981&signature=dc1e5ee86260d64ba6b3c770b1286ecf5b8c15c4b3d3c7b9bc544808e33c611f
```

If the method signature is changed to `string` it works as expected.

https://github.com/pixelfed/pixelfed/blob/77f9f7fe6792bbd5a29a166c96fe487618930207/app/Http/Controllers/Api/BaseApiController.php#L196-L204

reproduce:

* Run with php 7.4 (I did not try older PHP versions) `php -S localhost:8080`
* Upload a new image http://localhost:8080/i/compose
* result: The preview will get a 404 and will not show the image.

**Comment by dansup** [comment]
@nougad Nice find, its now fixed in dev branch!
