### ISSUE TITLE
home feed doesn't show remotely followed after 3rd image

### ISSUE THREAD

**Issue by ChameleonScales** [pixelfed/pixelfed#1854]
If I follow accounts in my instance, the home feed has unlimited scrolling for them.
However, for remotely followed accounts, their images don't appear after the 3rd one from the top.
And if I only have remotely followed accounts, the feed simply stops at 3 images and this message appears after a strangely long loading time :
> No more posts to load

I'm on pxlfd.me with version 0.10.6 of Pixelfed.

**Comment by dansup** [comment]
@ChameleonScales You will only see posts from remote accounts created after you followed them, unless your instance knows about their previous posts.

**Comment by ChameleonScales** [comment]
I know that but there's more to it.
As you say, posts that preexist my following don't show up by default but I can make them show up by pasting their url in the search bar and clicking on them. Even though this directs me to the other instance, it also links (or federates, not sure of the terminology) these posts in my feed.

However, I'm still limited to 3 remote posts.
For example, I may see 3 posts in my feed and then federate another one with the above method. If that post is more recent than one of the other 3 in my feed, this post takes place of it but I still can't get passed 3, so a post that was previously on my feed is no longer accessible there.
This is problematic if I want to comment posts that preexist my following because the only way I found to have 4th or higher posts to show up in my feed is to unfollow accounts until the post I want to see gets up to the 3rd place. I could use this hacky method for a few posts but obviously it doesn't work as soon as the post I'm looking for is 4th or higher in the same account. But more importantly, this is way impractical and not meant to happen.

**Comment by ChameleonScales** [comment]
I just tested on pixelfed.social and the exact same bug happens. I think this issue was closed a little too quickly.

**Comment by ChameleonScales** [comment]
Interestingly this bug doesn't happen on Fedilab for Android.
