### ISSUE TITLE
Discover other instances

### ISSUE THREAD

**Issue by der-On** [pixelfed/pixelfed#1857]
As a user I want to be able to discover posts and users on other instances without being registered on these instances or knowing an exact username.

## Expected behaivour

- I am on a pixelfeld isntance other then `pixelfed.social`
- I enter the following address into the search bar `https://pixelfed.social/discover`
- The results contain the discoverable posts on `pixelfed.social`

## Actual behaviour

- I am on a pixelfeld isntance other then `pixelfed.social`
- I enter the following address into the search bar `https://pixelfed.social/discover`
- I get a "No results found!"

**Comment by trwnh** [comment]
Duplicate of #1772
