### ISSUE TITLE
status.url set incorrectly for remote comments

### ISSUE THREAD

**Issue by MrPetovan** [pixelfed/pixelfed#1861]
Base Pixelfed post: https://pixelfed.mrpetovan.com/p/hypolite/104269765614374912

Remote comment URL: https://social.wake.st/@liaizon/103224830262049465

Go to post URL: https://pixelfed.mrpetovan.com/p/@liaizon@social.wake.st/106238002304520192

The page at this last URL shows "Sorry, this page isn't available".

**Comment by namelivia** [comment]
If you are okay with that I'm going to try to figure out this one, the scope seems very limited and seems easy to tackle for a newbie like me.
I've taken a look and as far as I know, the error setting the url when processing [this payload](https://social.wake.st/@liaizon/103224830262049465.json) on `Inbox.php`. I'll be writing a regression test based on that specific case.

**Comment by dansup** [comment]
Fixed in #2083!
