### ISSUE TITLE
deleted users are still follower

### ISSUE THREAD

**Issue by nyansen** [pixelfed/pixelfed#1868]
When a follower delete his account the user is still a follower.

**Comment by dansup** [comment]
We delete followers in the database, I think this is a cache invalidation bug

https://github.com/pixelfed/pixelfed/blob/7fa4d4a669dd6479c55edbfdca99d6bdce831c6e/app/Jobs/DeletePipeline/DeleteAccountPipeline.php#L89

**Comment by dansup** [comment]
@nyansen Where do you see the deleted follower, in notifications or profile Follower/Following list?

**Comment by nyansen** [comment]
I still see the user in my follower list. When I still see the user in my timeline or inbox (with old entries) it will not be an issue for me
