### ISSUE TITLE
Comments are listed in reverse-order

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#189]
Looking at the timestamps shows newest comments at the top, rather than at the bottom. Comments should flow from oldest at the top to newest at the bottom. 

Example: https://pixelfed.social/p/trwnh/1416

**Comment by dansup** [comment]
The problem with that is that pagination is not finished, so you would never see newer comments if there were 10 already. I will change the order when that is finished.

**Comment by trwnh** [comment]
"Load more comments" seems to work now, but comments are still in reverse order. If anything, the pages are loading in reverse order... the older comments fill in at the top, but the first page is still reveresed, leading to this: 0-1, 2-11, 21-12
![image](https://user-images.githubusercontent.com/10606431/48884505-635d7700-edea-11e8-97d2-e490191e85e6.png)

**Comment by dansup** [comment]
Fixed in latest commits

**Comment by trwnh** [comment]
Seems to be a regression as this is happening again.
