### ISSUE TITLE
[TOR] Premature Session Invalidation

### ISSUE THREAD

**Issue by Jookia** [pixelfed/pixelfed#1892]
Pixelfed is unusable for me since any kind of period of inactivity seems to trigger an auth check. I'm using Firefox and Tor on nfg.zone running 0.10.6

**Comment by dansup** [comment]
@Jookia It's possible that Tor is clearing cookies after you close the browser. I'll leave this open while we investigate a solution!

**Comment by Jookia** [comment]
I can confirm that Tor is not clearing cookies. My first thought would be that the sessions are linked to IPs, which rotate fairly often with Tor?

**Comment by NFGman** [comment]
Hiya Jookia.  Dansup and I are looking into it.  Thanks for the report.

**Comment by dansup** [comment]
@Jookia Sessions are not tied to IPs, and the two factor prompt is only displayed after login. If you are being logged out before the 2 day session lifetime it would be an issue with your browser. There is nothing we can do on this side.

**Comment by Jookia** [comment]
So have you reproduced this issue to confirm it's a browser issue? Or are you just closing it because that's what you think it is?

**Comment by dansup** [comment]
I know its a browser/tor issue because I can't reproduce on Chrome, Firefox or Safari. Like I mentioned before, if you are being logged out before 2 days of inactivity, your browser is not handling cookies properly.

**Comment by Jookia** [comment]
Can you try reproducing it with Firefox and Tor?

**Comment by dansup** [comment]
@Jookia Yes, I will re-open this and try to debug it this week. If you don't hear back from me by Wednesday, ping me!

**Comment by Jookia** [comment]
I'm doing some more tests to try and reproduce this. I closed the tab, closed Firefox, and got a new Tor identity (IP)- and opening the browser and page again, I'm still logged in.

**Comment by Jookia** [comment]
Ugh. I can't reproduce it. I wonder if it really was that I was inactive for 2 days? That's a really short expiration time compared to most services I use that keep me logged in forever or for 30 days

**Comment by Jookia** [comment]
Okay, reproduced! I logged in and solved my 2FA challenge on Mon, 16 Dec 2019 05:37:15 GMT according to the web server header, and just now I went to use pixelfed and and it wants me to log back in, sending the header Tue, 17 Dec 2019 05:27:39 GMT. I've been given an entirely new cookie despite sending a session cookie. It's even using the same XSRF token.

I completed the 2FA challenge at Tue, 17 Dec 2019 05:33:53 GMT. The session cookie includes "expires=Tue, 17-Dec-2019 07:33:53 GMT; Max-Age=7200;" so I might actually wait until then to connect to the server again and see if this is the maximum age I can have an inactive session.

**Comment by Jookia** [comment]
Ok, I waited until Tue, 17 Dec 2019 07:39:39 GMT to connect again and it wants me to enter another 2FA challenge. Two hours of inactivity logs you out it seems.

**Comment by Jookia** [comment]
I have a feeling the issue is because people haven't updated SESSION_LIFETIME in their env files (the .env.example and .env.testing also use 120 minutes)

**Comment by Jookia** [comment]
https://docs.pixelfed.org/installing-pixelfed/installation.html doesn't mention that you have to change SESSION_LIFETIME, so ... It sounds like sessions are just 2 hours long?

**Comment by Jookia** [comment]
https://docs.pixelfed.org/installing-pixelfed/installation.html doesn't mention that you have to change SESSION_LIFETIME, so ... It sounds like sessions are just 2 hours long and you were mistaken about them being 2 days long?

**Comment by Jookia** [comment]
Uh, okay... Is this fixed? What was the issue?

Edit: Were you able to reproduce my issue and confirm the fix?
