### ISSUE TITLE
Different values for "storage used" in settings vs dashboard

### ISSUE THREAD

**Issue by Vertux** [pixelfed/pixelfed#1899]
If I look into the dashboard it shows:
![Bildschirmfoto 2019-12-20 um 12 14 52](https://user-images.githubusercontent.com/10457918/71251499-cfc6e480-2322-11ea-9a48-954801c37b00.png)

but if I look into the user profile (it is just one on this test instance and it is an admin profile too)

![Bildschirmfoto 2019-12-20 um 12 15 12](https://user-images.githubusercontent.com/10457918/71251589-0dc40880-2323-11ea-9332-44ad3f45d1da.png)

It maybe just an issue, because of the small numbers, but nevertheless it is quite confusing.

Version: 0.10.6 beta

**Comment by Vertux** [comment]
When I checked the both values today they matched. It seems that, it has something to do with a delayed horizon job, which updates the value in the horizon GUI. Maybe someone more expirenced can check that, to be sure - otherwiese I would close this issue.

**Comment by dansup** [comment]
The dashboard values are cached and may not reflect the latest data.

**Comment by trwnh** [comment]
so maybe cached values should show the timestamp of the cache?
