### ISSUE TITLE
Rehide sensitive media after unhiding

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#1900]
You can currently click to load sensitive media, but you cannot rehide it except by refreshing the page.

**Comment by trwnh** [comment]
This is still an issue.

**Comment by spaceottercode** [comment]
The new UI now contains this feature if I'm not mistaken so this issue might be safe to close or nearly so (if one prefers to wait until the new ui is the official one)

**Comment by dansup** [comment]
Fixed in the latest commits!
