### ISSUE TITLE
Image Carousel broken on Dolphin Browser

### ISSUE THREAD

**Issue by andre-dierker** [pixelfed/pixelfed#1907]
On Android with the Dolphin Browser (Chrome based) the image carousel is broken. Swiping does not work as expected. I made a video to show the problem. All blockers are disabled & JS is enabled.
Video:
https://imgur.com/a/qHbohVb

Browser Version:
Kiwi Browser 77.0.3865.92
Android Version:
Android 9.0.0; MI 8
Pixelfed:
actual git version, pixelfed.social & own instance

**Comment by dansup** [comment]
This would be a bug in an upstream dependency ```vue-carousel```. Will investigate!

**Comment by dansup** [comment]
@andre-dierker There is nothing we can do, please use a different browser!
