### ISSUE TITLE
Convert URLs in descriptions & comments to links

### ISSUE THREAD

**Issue by der-On** [pixelfed/pixelfed#1908]
As a user I want to be able to put URLs into comments and these should become  clickable links once the comment is published.

## Acceptance criteria

- transform URLs within description & comment content starting with `http(s)://` into `<a>` tags

**Comment by der-On** [comment]
As far as I understand this has to happen before writing the text to the database as the link would not federate if it would happen on the client side/during rendering.

**Comment by dansup** [comment]
@der-On We used to allow this, then only allowed 2 links per comment/caption and eventually 0. I'll keep this issue open until we make this a configurable option since this should be up to each instance admin.

**Comment by der-On** [comment]
@dansup Thanks.

**Comment by pla1** [comment]
A third option might be to have an allowed domain list. Permitting domains like openstreetmap.org and denying domains like amazon.com. An example post with openstreammap.org. https://pixelfed.social/i/web/post/_/174395340139663360/182802750340468736 

Some folks want to share the location of their photo. ✌

**Comment by der-On** [comment]
@pla1 If so these domains need to be listed on a per instance, but I'm not sure if excluding/including certain domains would make to much sense to prevent from spam. There are better ways of doing that using (existing) moderation.

**Comment by wakest** [comment]
this still seems like a really basic feature that would make posting things that exist elsewhere work much better when also posted to pixelfed.

**Comment by moonmehta** [comment]
With [text-only posts now available](https://mastodon.social/@pixelfed/106617110297151132) on PixelFed, it would be great if links work too. There could be many reasons why people sharing photos, visuals, and their creative works may want to link to their blogs, websites, portfolios, etc. or even just share the source link of something they post. Links are fundamental to the Internet and I think PixelFed should embrace them, unlike Instagram.

**Comment by dansup** [comment]
You can edit the number of links per post here, by default the first 2 urls are auto-linked

https://github.com/pixelfed/pixelfed/blob/cd1a263f6e76476c732543f25264dbd0cada0500/app/Status.php#L53
