### ISSUE TITLE
[Bug] New comments appear on all posts in timeline

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#191]
1) Make a comment on one posts

![image](https://user-images.githubusercontent.com/10606431/40898330-352eca90-6786-11e8-8693-9f26be7a0bc0.png)

---

2) The comment now appears on all posts in the timeline

![image](https://user-images.githubusercontent.com/10606431/40898338-4359ae00-6786-11e8-8fe5-157b60bb6e46.png)

![image](https://user-images.githubusercontent.com/10606431/40898342-4aa761b6-6786-11e8-9f21-6374d3ba3487.png)

![image](https://user-images.githubusercontent.com/10606431/40898345-4f950cdc-6786-11e8-8c5a-b3e330924368.png)

---

3) Refreshing the timeline makes all the pseudocomments disappear, and the comment now only appears on the proper post.

**Comment by dansup** [comment]
@trwnh Yeah, I'm working on it.

**Comment by dansup** [comment]
Fixed in #192
