### ISSUE TITLE
Call to undefined method App\Http\Controllers\ProfileController::accountCheck()

### ISSUE THREAD

**Issue by jhaala** [pixelfed/pixelfed#1912]
The following is used in a few controllers that attempts to return a missing method:

```
if($profile->status != null) {
    return ProfileController::accountCheck($profile);
}
```

**Usage:**
ProfileController.php (line 174)
FederationController.php (lines 61 & 98)
StatusController.php (lines 29 & 116) 
App\Util\ActivityPub\Outbox.php (line 19)

**Comment by dansup** [comment]
Strange, not sure why it was removed 😅
