### ISSUE TITLE
Discover a tag fails if not logged in

### ISSUE THREAD

**Issue by efelon** [pixelfed/pixelfed#1917]
```
nginx version: nginx/1.14.0 (Ubuntu)
mariadb Ver 15.1 Distrib 10.4.11-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS
pixelfed 0.10.7 (dev)
Registration closed
2 Users only (admin and me)
```
### Expected
When I go to https://pixelfed.de/discover/tags/art for example, without being logged in (I don't have an account) I can see the public pictures of this hashtag.

### Observation
When I try to do the same on my instance (where also public pictures exist with the hashtag #art) I get a 403 error in the nginx logs when I'm not logged in. Pixelfed says "Sorry, this page isn't available." I tried it with all the other hashtags as well.

https://pixel.winklerfamilie.eu/discover/tags/art <- error
https://pixel.winklerfamilie.eu/p/efelon/77779699371216896 <- public post with #art

When I'm logged in I can see the hashtag discovery page.
I tried `php artisan fix:hashtags` which is not related if I understood it correctly.

Do I miss a setting or a config value somewhere? The nginx configuration is taken from [contrib](https://github.com/pixelfed/pixelfed/blob/dev/contrib/nginx.conf).

Thanks for your help in advance.

**Comment by dansup** [comment]
@efelon You need to add ```INSTANCE_PUBLIC_HASHTAGS=true``` in ```.env``` then run ```php artisan config:cache```

**Comment by ghost** [comment]
Because there is no documentation about this, it would be nice to have a place where all configuration options are listed.

**Comment by efelon** [comment]
As @memo-567 mentioned and not bother you here with trivial things, could I have found this information by myself (I know you are concentrating on documentation right now)?

I would propose to update the .env.example with all options (commented of course), or to create a .env.full for that purpose.

10.7 is now working great btw.
Thank you
