### ISSUE TITLE
Transparency support

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#1929]
Hello,

I uploaded a PNG with transparency, but the result is pretty disappointing.

Original image
![pizzaception](https://user-images.githubusercontent.com/22192600/72205748-7b74d780-347e-11ea-9603-cd1beb27bafc.png)

Image after upload on my pixelfed instance
![Screenshot_20200111_153122](https://user-images.githubusercontent.com/22192600/72205820-37360700-347f-11ea-8161-b04e8baee3fe.png)

**Comment by trwnh** [comment]
The image is transparent -- the viewbox just happens to be black.
