### ISSUE TITLE
Embed payload input has inconsistent line height across browsers

### ISSUE THREAD

**Issue by wakest** [pixelfed/pixelfed#1932]
this is from Piconic using the newest version of Firefox on Windows 10

![image](https://user-images.githubusercontent.com/7890201/72239988-9850fe00-3597-11ea-8de4-d4cbdb996603.png)

**Comment by dansup** [comment]
@wakest Thanks for the report, marking this as low priority since the ```Copy Embed Code``` is easier than selecting the input and copying.
