### ISSUE TITLE
MomentUI - colour selection

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1933]
No matter which MomentUI Profile Header Color is selected

![Screenshot_20200114-095815_Kiwi Browser_edited](https://user-images.githubusercontent.com/58190287/72329364-e1e33b00-36b4-11ea-87a6-43b29f5251da.jpeg)

 it is always shown blue only.

![Screenshot_20200114-095906_Kiwi Browser_edited](https://user-images.githubusercontent.com/58190287/72329391-f0315700-36b4-11ea-8ae7-ea97accbac53.jpeg)

**Comment by dansup** [comment]
@memo-567 Oops! The fix has been shipped 😅
