### ISSUE TITLE
Missing meta section on media attachments

### ISSUE THREAD

**Issue by trashhalo** [pixelfed/pixelfed#1934]
On mastodon MediaAttachment (images) have a meta section that define height and width of the image. Pixelfed servers are not setting meta and there is no way currently to know the aspect ratios of the images from the api.

See:  
https://mastodon.social/api/v1/timelines/public  
vs  
https://piconic.co/api/v1/timelines/public

**Comment by trwnh** [comment]
mastodon's meta field comes from paperclip and its contents are not standard.

**Comment by trashhalo** [comment]
@trwnh would you consider an alternative way to know image dimensions? I could always if meta else pixelfed.zeta

**Comment by trwnh** [comment]
i think we can generate our own meta, sure. in the meantime, maybe do local image processing to get the dimensions from the file itself.
