### ISSUE TITLE
TRUST_PROXIES seemingly has no effect

### ISSUE THREAD

**Issue by asonix** [pixelfed/pixelfed#1939]
EDIT:
This was caused by a configuration issue, but there is still something I want to bring to your attention. Please read the thread.

Original Post:
I'm trying to deploy pixelfed on a kubernetes cluster, and it seems to me like TRUST_PROXIES is not doing anything.

When I try to create an account, I get a `419 | Page Expired`, and searching through issues indicates this is an issue with the HTTPS configuration. I do have HTTPS enabled, but it terminates at an nginx instance (for convenience of configuring many web services on my cluster), and the unencrypted traffic is forwarded to the pixelfed apache container.

Using `TRUST_PROXIES=*` or `TRUST_PROXIES=**` has had no effect on my ability to create an account.

If there is another way to allow traffic over port 80, I would be interested in that as well

**Comment by asonix** [comment]
I'm not a PHP developer, but it looks to me like `Fideloper\Proxy\TrustedProxyServiceProvider::class` isn't in the providers in `config/app.php`. The instructions for that library indicate it should be there

**Comment by asonix** [comment]
The more I look into this, the more these seem like distinct issues. I'll report findings shortly

**Comment by asonix** [comment]
alright, well it turns out I had a configuration issue. I had set `SESSION_DOMAIN=${APP_DOMAIN}`, which was interpreted as `${APP_DOMAIN}` rather than expanding the variable. this was a holdover from my previous pixelfed install

Now that I've corrected this, both the upstream version (this repo) and my downstream with some TrustedProxy changes are working. This indicates to me that maybe TrustedProxy isn't used for anything in this project, if it being broken has no effect.

**Comment by dansup** [comment]
@asonix Remove this line from ```AppServiceProvider.php```

https://github.com/pixelfed/pixelfed/blob/0adf959a7458704ec9002390183a11756c76b3e4/app/Providers/AppServiceProvider.php#L33

**Comment by dansup** [comment]
I will leave this issue open until we make the forceScheme optional

**Comment by asonix** [comment]
@dansup sorry if I wasn't clear: I did get everything working without code changes, and this issue currently only serves to point out that TRUST_PROXIES may be unused.

**Comment by dansup** [comment]
@asonix Did you run ```php artisan config:cache``` after adding ```TRUST_PROXIES=``` in ```.env```?

The reason its not in config/app.php is because its not a provider, its a [middleware](https://github.com/pixelfed/pixelfed/blob/dev/app/Http/Middleware/TrustProxies.php)

**Comment by dansup** [comment]
@asonix For more information, please view the [Laravel Documentation](https://laravel.com/docs/6.x/requests#configuring-trusted-proxies) or the [source code](https://github.com/fideloper/TrustedProxy/blob/master/src/TrustProxies.php#L67)
