### ISSUE TITLE
TRUST_PROXIES variable with wildcard ("*") does not work anymore

### ISSUE THREAD

**Issue by efelon** [pixelfed/pixelfed#1951]
After the pull from dev today I can't reach any site of my installation (_Sorry, this page isn't available._).

### Fix:
Probably associated with cb6e8a4eaad72a824e12fb1323964dd3b369cb4d I had to actually type in the IP address of my nginx proxy to get everything working again. The wildcard syntax of the .env.example had no effect anymore.

#### Working:
```
TRUST_PROXIES="xxx.xxx.xxx.xxx"
TRUST_PROXIES=""
```

#### Not working:
```
TRUST_PROXIES="*"
TRUST_PROXIES="**"
```

**Comment by asonix** [comment]
This is interesting, because this change made my service go from not working to working. If you'll look, the commit you linked is not the final change, it is this one: https://github.com/pixelfed/pixelfed/commit/64af65e992f2f7d15ddeb91521772546b298e5b3

As we can see in this file, https://github.com/fideloper/TrustedProxy/blob/790194d5d3da89a713478875d2e2d05855a90a81/src/TrustProxies.php#L76 the strings "*" and "**" are checked before an array is made.

How many levels of proxy do you have, btw? Is it just nginx->php? Or nginx->apache->php?

**Comment by asonix** [comment]
Also just double-confirming that without the `TRUST_PROXIES="*"`, preview images do not work on my instance due to signature verification failure, but with `TRUST_PROXIES="*"`, this error does not happen.

It seems to me like maybe the whole site being unavailable without TRUST_PROXIES set could be indicative of a different configuration error.

**Comment by efelon** [comment]
There is just one proxy, nginx -> nginx. I also reversed the config back to "*" to confirm twice. I did not try "". I'm also happy to help, just tell me how. Tomorrow I can provide the proxy config.

With the IP everything is working as excepted.

**Comment by efelon** [comment]
I tried `TRUST_PROXIES=""` which also works. Everything else is still as described in the issue above.

The nginx backend is basically [this](https://github.com/pixelfed/pixelfed/blob/dev/contrib/nginx.conf) from contrib, with the following lines added in the php block to get previews working behind the proxy:

```
#fix preview problem
fastcgi_param REQUEST_SCHEME $http_x_forwarded-proto;
fastcgi_param HTTPS $proxy_https if_not_empty;
```

And here my nginx proxy location:

```
location / {
    proxy_buffering off;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $remote_addr;

     proxy_pass http://xxx.xxx.xxx.xxx/;
  }
```

**Comment by asonix** [comment]
wait, so you're saying that setting `TRUST_PROXIES` to an empty string works in your setup, but setting `TRUST_PROXIES=*` doesn't?

**Comment by asonix** [comment]
another interesting thing to note: 

I'm using nginx->apache->php and i'm not an expert on apache, but it seems to me that I don't have anything equivalent to these lines
```
fastcgi_param REQUEST_SCHEME $http_x_forwarded-proto;
fastcgi_param HTTPS $proxy_https if_not_empty;
```

Meaning that I don't explicitly tell pixelfed that I'm https, I just rely on trusting the proxy that sent the request to pixelfed.

I think it's likely that by pretending HTTPS traffic is hitting pixelfed directly, you don't actually need to trust proxies.

**Comment by efelon** [comment]
> wait, so you're saying that setting TRUST_PROXIES to an empty string works in your setup, but setting TRUST_PROXIES=* doesn't?

Yes, exactly.

> fastcgi_param REQUEST_SCHEME $http_x_forwarded-proto;
> fastcgi_param HTTPS $proxy_https if_not_empty;

If I comment these two lines:

![Auswahl_003](https://user-images.githubusercontent.com/10722552/72926145-33926200-3d54-11ea-91d0-84e2a1aef3fe.jpg)

As you can see existing pictures work, but when I try to upload a new one it fails (browser console):

![image](https://user-images.githubusercontent.com/10722552/72926210-57ee3e80-3d54-11ea-823e-e358fa185ac3.png)

Btw. this is the domain part I use:
```
APP_URL="https://pixel.winklerfamilie.eu"
APP_DOMAIN="pixel.winklerfamilie.eu"
ADMIN_DOMAIN="pixel.winklerfamilie.eu"
SESSION_DOMAIN="pixel.winklerfamilie.eu"
SESSION_SECURE_COOKIE=true
TRUST_PROXIES="xxx.xxx.xxx.xxx"
```
I need to put https in the APP_URL because otherwise no images are shown.

**Comment by asonix** [comment]
@efelon what happens if you comment out the 

> fastcgi_param REQUEST_SCHEME $http_x_forwarded-proto;
> fastcgi_param HTTPS $proxy_https if_not_empty;

but you also set `TRUST_PROXIES=*`

**Comment by asonix** [comment]
Here's my config btw
```yml
  APP_URL: https://pixel.asonix.dog
  ADMIN_DOMAIN: pixel.asonix.dog
  APP_DOMAIN: pixel.asonix.dog
  SESSION_DOMAIN: pixel.asonix.dog
  SESSION_SECURE_COOKIE: "true"
```

**Comment by efelon** [comment]
> @efelon what happens if you comment out the:
>> fastcgi_param REQUEST_SCHEME $http_x_forwarded-proto;
>> fastcgi_param HTTPS $proxy_https if_not_empty;

> but you also set TRUST_PROXIES=*

I just retested, it has no effect. With `TRUST_PROXIES=*` I can't reach any content regardless of the fastcgi... being commented or not. Not even `https://pixel.winklerfamilie.eu/site/privacy`. And if I comment the fastcgi part I don't get a preview for uploaded pictures.
