### ISSUE TITLE
Upgrading from v0.10.6 to v0.10.7 causes empty homepage

### ISSUE THREAD

**Issue by benpro** [pixelfed/pixelfed#1960]
I upgraded with:

```
git fetch -p
git checkout v0.10.7
composer install && php artisan migrate --force && php artisan config:cache && php artisan route:cache
```

Everything works except the home page and the compose menu not loading.
Successfully reversed my upgrade with:

```
git checkout v0.10.6
composer install && php artisan migrate --force && php artisan config:cache && php artisan route:cache
```

Nothing in my `error.log` nor `storage/logs/laravel.log`.

Any idea of how I can help debug this issue?
This is a manual installation on a Debian Buster.

**Comment by benoitjpnet** [comment]
Oh fixed with `php artisan cache:clear && php artisan optimize:clear`. Sorry for the noise.
