### ISSUE TITLE
Multiple images -> No enlargement button

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1961]
I posted two images and in main view there is no enlargement button:

![Screenshot_20200125-170947_Kiwi Browser-01](https://user-images.githubusercontent.com/58190287/73123979-1220b880-3f96-11ea-983b-7c167122e922.jpeg)

and in detail view the enlargement button opens the first image only:

![Screenshot_20200125-171003_Kiwi Browser-01](https://user-images.githubusercontent.com/58190287/73123993-3aa8b280-3f96-11ea-8810-d2465c6a0794.jpeg)

**Comment by trwnh** [comment]
Duplicate of #1774

**Comment by ghost** [comment]
> Duplicate of #1774

But the half only -> Missing enlargement Button.
