### ISSUE TITLE
Unfollow Link Does Not Work

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1963]
Follow works but unfollow doesn't

Unfollow appears as red link and that's all

Is it just a placeholder for now?

**Comment by dansup** [comment]
@okpierre What page are you referring to? Profiles?

**Comment by okpierre** [comment]
@dansup when I click on home, is that considered the timeline view? 

it's the three dots for each post

![pixelfed-timeline](https://user-images.githubusercontent.com/1679025/73226501-4b7e4180-41ab-11ea-9fbc-cc13e4324b63.jpg)

**Comment by dansup** [comment]
@okpierre Looks like a UI bug, will investigate!

**Comment by dansup** [comment]
@okpierre I have reproduced this issue and will ship a bug fix soon!
