### ISSUE TITLE
Supplied Key Param Cannot Be Coerced Into A Public Key

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#1972]
Here's the error message

openssl_verify(): supplied key param cannot be coerced into a public key {"exception":"[object] (ErrorException(code: 0): openssl_verify(): supplied key param cannot be coerced into a public key at /app/Util/ActivityPub/HttpSignature.php:80)

**Comment by dansup** [comment]
@okpierre This is not a bug, please make sure you follow our requirements.
