### ISSUE TITLE
Share button does nothing

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#1988]
Hello,

When i click on the share button, it becomes blue and...that's all, it does nothing else.

**Comment by dansup** [comment]
@stemy2 On what page do you see the share button?

**Comment by okpierre** [comment]
@stemy2 are you referring to the third icon?

![pixelfed-share](https://user-images.githubusercontent.com/1679025/73779269-7b54b880-475a-11ea-8363-76ee587adbd1.png)

@dansup curious how it works - just blue as stemy2 mentioned

**Comment by stemy2** [comment]
Well, this is strange, there's no more share button. The icon was a square composed of 2 little arrows, but it has disappeard.

**Comment by fifn2** [comment]
I'm having a similar problem.

**Comment by stemy2** [comment]
Well, the share button is here again (the last of the 3 icons you can see at the bottom left of the photos) and still does nothing but becoming blue.
