### ISSUE TITLE
Privacy settings - Blocked user and Muted users lack links

### ISSUE THREAD

**Issue by svalo** [pixelfed/pixelfed#1990]
When accessing the /settings/privacy page and clicking on the "muted users" or "blocked users" links the "blocked keywords" and "blocked instances" links vanishes.

When I access the links  "blocked keywords" and "blocked instances" instead I can see the "muted users" or "blocked users" links.

I think the  cause is the fact that the following lines are commented

https://github.com/pixelfed/pixelfed/blob/ee22faeb8bc2495230b23bc29b4a6d6f1fee0539/resources/views/settings/privacy/blocked.blade.php#L13

https://github.com/pixelfed/pixelfed/blob/ee22faeb8bc2495230b23bc29b4a6d6f1fee0539/resources/views/settings/privacy/muted.blade.php#L13

Is this intended?

**Comment by dansup** [comment]
Fixed in the latest commits!
