### ISSUE TITLE
use webtorrent like peertube

### ISSUE THREAD

**Issue by johnss** [pixelfed/pixelfed#1992]
to decrease server load and to allow viewing deleted content and bypass censorship, i encourage pixelfed to follow peertube that use torrent, this will decrease server load and if torrent hash is known and theres is still has a seeder viewing deleted content is possible and will bypass censorship

**Comment by ghost** [comment]
Serving pictures does not create huge server load, therefore there is no need to use peers. There is also a security concern about this. The point of Pixelfed is to not give out your personal photos to other entities such as Instagram. By peering you not only do just that, but you are encouraging that behavior. Good idea for a video sharing sites, but not for photo sharing sites, where people have their personal photos. I am not against the idea if it would be optional and only affect public photos. 

Another approach would be to encrypt photos when they are on other's servers, but let the decryption key be only obtainable from the server the user is on. That would require image encryption using JavaScript, as the whole point of this is reducing server load, and doing that might not be the best idea. This could work for private profiles as well.

**Comment by dansup** [comment]
We have no plans to support webtorrent
