### ISSUE TITLE
Disable user-select on mobile (for images)

### ISSUE THREAD

**Issue by laurens94** [pixelfed/pixelfed#1994]
When navigating the slideshow of a post with multiple images, the images sometimes get selected (e.g. while hold-touching the image on iOS).

Example:

![photo_2020-02-08_11-47-06](https://user-images.githubusercontent.com/5780704/74083865-e65b0380-4a68-11ea-8d95-fe4d90d0566f.jpg)

Adding the CSS `user-select: none;` to that element should fix this.

**Comment by dansup** [comment]
Fixed!
