### ISSUE TITLE
[Bug] Replaying a story starts from the last image

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#1997]
Instance: pixelfed.social (0.10.8)
Browser: Firefox 72.0.2
OS: Windows 10

When you first see one's multiple photo story, it starts with the first image. However when you click on it again, it always starts with the last one and then closes.
You can "swipe" with mouse till the first image, but it's still a bug.

**Comment by dansup** [comment]
@MasterGroosha This is intentional, if you've already seen the Story, it makes more sense to skip to the newest/unseen story item on subsequent requests.

**Comment by MasterGroosha** [comment]
@dansup Imagine there are 10 images in the Story. Whenever I would like to view the first image, I'll have to make 9 swipes with a mouse to reach it. That's completely user-unfriendly.
Since you don't want to restart a Story, a solution is to make those horizontal lines clickable so that you can open any image in a Story.

**Comment by MasterGroosha** [comment]
upd: oh, now I see that clicking on left side of screen goes one image backward and vice versa. Not to intuitive, honestly, but at least I can (rather) quickly get to the first image.
