### ISSUE TITLE
Rewrite frontend on Svelte

### ISSUE THREAD

**Issue by toby3d** [pixelfed/pixelfed#1998]
I want to offer my help in rewriting the frontend on Svelte. In my opinion, this will solve some existing problems and speed up responsiveness coupled with a reduction in bundle size. We need to “write less damn code” to achieve great results, and I think Svelte, with its compilation of templates into native JavaScript, can help us with this. What do you think? :thinking:

**Comment by dansup** [comment]
We have no plans to adopt a different frontend framework. Vue.js is good enough for us.
