### ISSUE TITLE
Blank Screen After Install

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2001]
Tried out the latest version and getting a blank screen
Went back to previous version and it's fine

Here's what it looks like
![pixelfed-blank](https://user-images.githubusercontent.com/1679025/74301131-0b2cd080-4d20-11ea-9c0f-5f74b2f08026.png)

**Comment by dansup** [comment]
@okpierre I can't reproduce on a fresh installation. Are you sure you ran all the commands?

**Comment by okpierre** [comment]
@dansup should've mentioned I had v0.10.8 in the folder prior the latest install overwriting so not completely fresh. switched back to v.0.10.8 and blank screen went away

**Comment by okpierre** [comment]
@dansup please see links with same issue 

`https://pixelfed.fr/p/cheyenne/43659623462473728`
`https://travelpandas.xyz/p/oufmilo/100545318235541504`
`https://piconic.co/p/sturmen/133226748115554304`

**Comment by dansup** [comment]
Fixed in #2006
