### ISSUE TITLE
Make Pixelfed GNU LibreJS compliant

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#2008]
Although Pixelfed is free software, the JavaScript loaded by Web browsers to access any instance running Pixelfed is not marked as free. So, it is impossible to access any of them while using GNU LibreJS. Please consider [setting the JavaScript code free](https://www.gnu.org/software/librejs/free-your-javascript.html).

More information on this freedom issue on the [GNU website](https://www.gnu.org/philosophy/javascript-trap.html).

**Comment by dansup** [comment]
The javascript code is already free and open source, the sources are linked in the ```packages.json``` in the project root.
