### ISSUE TITLE
Tag Lead To Page Is Not Available

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2009]
When using some characters in tag, it will lead to page is not available page when clicking on tag

![pf-sorry](https://user-images.githubusercontent.com/1679025/74494032-c92b9800-4ea1-11ea-9309-ad4a1182c134.png)

used the following tag in post:
`#hello #Здравствуйте #여보세요 #مرحبا #สวัสดี`

**Comment by dansup** [comment]
@okpierre What database are you using, or is this on a specific instance?
They work for me using MySQL with utf8mb except the last hashtag you listed.

<img width="917" alt="Screen Shot 2020-02-13 at 7 32 12 PM" src="https://user-images.githubusercontent.com/877217/74496394-caf05e00-4e97-11ea-8174-4c62c483de9b.png">
<img width="872" alt="Screen Shot 2020-02-13 at 7 32 22 PM" src="https://user-images.githubusercontent.com/877217/74496397-ce83e500-4e97-11ea-90fd-2826b39775d6.png">
<img width="935" alt="Screen Shot 2020-02-13 at 7 32 50 PM" src="https://user-images.githubusercontent.com/877217/74496403-d17ed580-4e97-11ea-9a28-357dbcd458e4.png">

**Comment by okpierre** [comment]
@dansup Yes same for the last one with mysql. Would be impossible to check for all languages. Is there anything specific to check for the last tag on the list?

**Comment by dansup** [comment]
@okpierre I figured out the bug, the hashtags are parsed and stored in the database correctly, the issue is we only checked the ```slug``` and by checking the ```name``` column in the ```hashtags``` table too, the issue is resolved.

**Comment by okpierre** [comment]
@dansup great thanks!
