### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by Tom12121212** [pixelfed/pixelfed#2010]
Hi Tim,
First I am a Brit also.

I am looking to collaborate with someone to modify the Peertube code and allow users to upload 100’s GB of data for a small hosting fee.

Also I would like to give content creators the option to sell some of their work, but also be able to give it away for free.

There would no adds. Would be similar to vimeo model.

Have you thought  about doing something similar? I am willing to give a percentage of my company to someone involved. I have a great track record.

I have some press about to come out on a hardware product that I have been developing. I can get a tonne of publicity. My hardware product would benefit greatly from some hosting. 
Thx
Tom

**Comment by dansup** [comment]
Not interested.
