### ISSUE TITLE
User deletion don't work with Postgres

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#2016]
Hello,

It's impossible to delete users with Postgres. Also in command line using artisan user:delete.
The medias still on the server, and the user can continue to connect to the instance with his password.

![Capture3](https://user-images.githubusercontent.com/49836486/74592435-ade79680-5021-11ea-8274-78d04abc38f7.JPG)

This is a problem. Because my instance is not RGPD friendly and also, still store this kind of content that I can't delete : 
![Capture2](https://user-images.githubusercontent.com/49836486/74592827-59deb100-5025-11ea-9f4f-09dd0c6806c3.JPG)

On a fresh instance on mysql it's working fine.

I understand you don't care about pgsql now. But when I created my instance it was ok. And I have the 5th biggest of the Fediverse now who use Postgres. It wouldn't be a problem if it was easy to convert a Progresql database to a Mysql database but it's not.

**Comment by dansup** [comment]
@raphgilles This is a very important feature I agree, I am investigating this bug.

**Comment by dansup** [comment]
@raphgilles I have reproduced this issue on postgres, for now you can use the ```user_id``` in the ```php artisan user:delete``` command like ```php artisan user:delete 12345``` instead of ```php artisan user:delete usernameHere``` and it works as expected.

I will ship a fix for this shortly.

**Comment by dansup** [comment]
I realized it will fail on *partially deleted* accounts, working on a fix for that too.

**Comment by raphgilles** [comment]
Thank you very much @dansup !

Last question for this issue : have I a way to manually delete a publication or re-delete an user ? My instance still think I have already deleted this user but it still partialy deleted.

**Comment by dansup** [comment]
@raphgilles run ```php artisan user:delete USERNAME_HERE --force```

**Comment by raphgilles** [comment]
It worked ! Thank you !
