### ISSUE TITLE
Stories issue display with Postgres

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#2018]
Hello,

There is a displaying of stories problem with Postgres. At the top of the timelines, the banner display multiple stories of the same person. As many as there are pictures in his story. In my example 3 pictures.

If I try with a mysql fresh installation there is not this issue.

![Capture4](https://user-images.githubusercontent.com/49836486/74592614-4c282c00-5023-11ea-9ab0-999133ab979c.JPG)

**Comment by dansup** [comment]
@raphgilles Good news, this is fixed in the latest commits! I am hunting down other postgres bugs, I appreciate reports like this!
