### ISSUE TITLE
Sorting Issue With Notification Alert

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2019]
Notification (bell icon) shows correct sort

example:
user1 liked your post 1d
user2 liked your post 2d
user3 liked your post 1w
user4 liked your post 2w
user5 liked your post 3w

Alerts sidebar shows different sort (random? it doesn't appear to be in specific order)

example:
user5 liked your post 3w
user2 liked your post 2d
user3 liked your post 1w
user4 liked your post 2w
user1 liked your post 1d

Tested in desktop view

**Comment by dansup** [comment]
@okpierre I noticed this on a newer instance, seems to be a bug in the NotificationService. Will investigate!

**Comment by dansup** [comment]
Fixed in latest version.
