### ISSUE TITLE
composer warnings

### ISSUE THREAD

**Issue by shleeable** [pixelfed/pixelfed#2031]
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.

**Comment by shleeable** [comment]
Dependabot is your friend.

**Comment by dansup** [comment]
@shleeable I can't remember why I added that dependency, we don't support 32-bit systems anymore so I will remove it and ensure nothing breaks!

**Comment by dansup** [comment]
@shleeable Oops, I forgot to address dependabot. The issue with that is some newer packages require php 7.4 and not every instance runs that yet. 

PHP 7.3 is [supported for 9 more months](https://www.php.net/supported-versions.php), we need to give admins time to update before breaking their instance.

**Comment by dansup** [comment]
Fixed in latest commits
