### ISSUE TITLE
Story Redirect

### ISSUE THREAD

**Issue by Philipinho** [pixelfed/pixelfed#2034]
Tried this on pixelfed.de

I created a story on my profile. I clicked on it, when it had finished loading, it redirected me to the homepage.
I expected it to redirect me back to my user profile.
I know the story feature is still in beta but felt I should make this known.

**Comment by dansup** [comment]
@Philipinho This is a legacy bug, at one point the StoryViewer component only loaded on the Timelines and it made the most sense at the time.

Will fix this in the next release!

**Comment by dansup** [comment]
Fixed in latest commits!
