### ISSUE TITLE
Implement basic Laravel Captcha image on new registration

### ISSUE THREAD

**Issue by iamdoubz** [pixelfed/pixelfed#2035]
## Feature Request

Add a simple captcha implementation.

[https://github.com/mewebstudio/captcha](https://github.com/mewebstudio/captcha "Laravel Captcha")

Similar to the now defunct [Google Recaptcha](https://github.com/pixelfed/pixelfed/issues/1140) but retains a certain amount of privacy this project wishes to maintain.

**Comment by dansup** [comment]
@iamdoubz Simple captchas don't work, did you see the issues of that captcha library? We need better abuse detection and mitigation.
