### ISSUE TITLE
Some strings are not translatable

### ISSUE THREAD

**Issue by svalo** [pixelfed/pixelfed#2038]
After translating some strings I noticed that  when switching language the strings were not stranslated even if the translation file existed and the term was tranlated.

I looked a bit into the code and noticed that the string in the source was hardcoded i.e. [this](https://github.com/pixelfed/pixelfed/blob/443f20eaa610a4e22589d7956bc914a4a34e328e/resources/views/layouts/partial/nav.blade.php#L57)  while the others like [this](https://github.com/pixelfed/pixelfed/blob/443f20eaa610a4e22589d7956bc914a4a34e328e/resources/views/layouts/partial/nav.blade.php#L79) were translated correctly. 

Would you accept a PR which goes trough the code and searches for such terms substituting the hardcoded strings with the placeholder? 

Do you have any rule or standard to adopt for naming the placeholders?

**Comment by dansup** [comment]
@svalo We are in the middle of a huge refactor to a SPA, many of the existing blade templates will become Vue components. After that is complete, localization will be a priority!

**Comment by svalo** [comment]
Thanks @dansup, il wati then :) As I'm not a developer translations are one of the few things I can contribute to :sweat_smile:

**Comment by RomainTT** [comment]
Any news about translations ? I am eager to contribute too.

**Comment by hikerus** [comment]
Would like to join translator team as well ;-)

**Comment by orangesunny** [comment]
I am slowly adopting Pixelfed, and I’m open to helping with some localization efforts personally.

Also, we at Weblate offer a solution that’s already boosting communities and making users happy for large numbers of projects: https://weblate.org/hosting/#libre. Let me know if I can help anyhow.

**Comment by RomainTT** [comment]
This issue is two years old. What is the status about translations @dansup? How can we help?

**Comment by dansup** [comment]
Translations can be submitted via [translate.pixelfed.org](https://translate.pixelfed.org)
