### ISSUE TITLE
Profiles with uppercases in username broken

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#2039]
Hello,

I found a bug : when I try to access to a profile with an uppercase in the username I have the "Sorry, this page isn't available." message.

For examples :
https://pixelfed.fr/Nathan
https://pixelfed.fr/Nabos
https://pixelfed.fr/Juli4nDev
https://pixelfed.fr/AnatomyPark

I have not errors in the laravel & nginx logs.

**Comment by dansup** [comment]
@raphgilles This looks like a regression, will work on a fix!

**Comment by dansup** [comment]
@raphgilles Fixed in #2040
