### ISSUE TITLE
Personal access token generation issue

### ISSUE THREAD

**Issue by glukose** [pixelfed/pixelfed#2065]
Hello,

I can't generate a new token on the /settings/applications page.
I got the form displayed with the name and the scopes to tick, but the action on the button doesn't do anything and doesn't display an error message.

The response in a 500 : "Personal access client not found. Please create one."

I guess i'm missing a step somewhere,

Cheers

**Comment by dansup** [comment]
@glukose To enable oauth support, please follow the steps listed on the v0.10.6 release [here](https://github.com/pixelfed/pixelfed/releases/tag/v0.10.6)
