### ISSUE TITLE
"Like" with double click

### ISSUE THREAD

**Issue by Bondarz** [pixelfed/pixelfed#2066]
"Like" with double click

Hello, I don't know if anyone has suggested it yet, but I'd love it if you could "Like" photos with a double click of your mouse. That way you don't have to press the heart on the bottom left.

Thanks for your work!

**Comment by trwnh** [comment]
This should already be implemented... #744

**Comment by dansup** [comment]
@trwnh It was removed a while back due to conflicts with the newer album library we are using. Re-opening this issue until we decide wether or not to re-evaluate this feature.

**Comment by fossdd** [comment]
Adding this feature back, would great!

**Comment by UncleReaton** [comment]
Any news about this feature?
