### ISSUE TITLE
Status: Id generation issue

### ISSUE THREAD

**Issue by quanghoangminh** [pixelfed/pixelfed#2067]
Hi team,

There is an issue relate to id generation of status post: The id of the latest status is smaller than the other post. There for, the timeline only show 3 latest statues.
In my test case with 5 posts, the ids in order: 1275203584, 1312952320, 1396838400, 1531056128, **562171904**.

I checked the snowflake algorithm but figure out nothing. My bad when encounter this case :walking_man: 

Thanks

**Comment by dansup** [comment]
Pixelfed uses 64 bit snowflake ids, please make sure your PHP/server supports 64 bit integers!

**Comment by quanghoangminh** [comment]
yeah, i'm sure. What else can be missed?
# php -r 'echo PHP_INT_MAX;'
9223372036854775807

**Comment by dansup** [comment]
@quanghoangminh Is your server time correct?

**Comment by quanghoangminh** [comment]
@dansup Seem it is correct.

SELECT now()
now() 
2020-02-28 08:57:57 (GMT + 7)

**Comment by dansup** [comment]
@quanghoangminh Can you run ```php artisan self-diagnosis``` and paste the results here?

**Comment by quanghoangminh** [comment]
@dansup I can not run this command because i publish the app on shared hosting.
There are some strange things:
- The profile is same as status but it's okay when save to database with 64 bit snowflake id.

- When i force change id of status with the 64 bit interger by phpmyadmin -> the query findOrFail (*OrFail function) on this model always return fail:
 `$status = Status::whereProfileId($user->id)
                ->whereNull('reblog_of_id')
                ->whereNotIn('visibility',['draft','direct'])
                ->findOrFail($id);`
**but if i change the command to:**
 `$statuses = Status::whereProfileId($user->id)
                ->whereNull('reblog_of_id')
                ->whereNotIn('visibility',['draft','direct'])
                ->get();`
`$status = $statuses->where('id', $id)->first();`
it do the job.

**Comment by dansup** [comment]
@quanghoangminh Ah, that would explain it. Shared hosting is not supported by Pixelfed.

**Comment by quanghoangminh** [comment]
Ok, thank you ^^
