### ISSUE TITLE
Delete and redraft

### ISSUE THREAD

**Issue by HolgerPeters** [pixelfed/pixelfed#2072]
I, I just uploaded a bunch of images to a pixelfed account and realized only a bit later that I forgot to tag these with some more hashtags that I discovered. From the user interface it seems I would have to delete the posts, then tediously upload everything again.

Mastodon has a cool feature somewhere between similar to an edit functionality. You can delete a post and are forwarded to the form pre-filled with the contents of said deleted post, then you can change the post as needed and post it again. I think thats kind of neat and its what I would have liked to have on pixelfed.social today.

**Comment by trwnh** [comment]
i'd rather see pixelfed support proper edits a la #823... this isn't twitter

**Comment by weex** [comment]
#823 is locked but I think this issue is valid and useful, implementation challenges aside. A narrower issue brought me here so I'll make one just about that.

**Comment by dansup** [comment]
We now support Post Edits, closing this as that feature supersedes this.
