### ISSUE TITLE
"Too Many Attempts" message.

### ISSUE THREAD

**Issue by dpmcgonigle** [pixelfed/pixelfed#2076]
Hello, I'm trying to automate posting pictures in the Pixelfed software to my local server using Pyppetteer for automation.  I'm running into an error that says, "Oops, something went wrong! Too Many Attempts."  

I have looked in the code to find the error, but can't seem to find anything of the sort (grep -ir "Too Many Attempts" * - doesn't find anything!).  Do you have more information on what causes this warning?  Is there a way to disable it?

Thank you.

**Comment by dansup** [comment]
@dpmcgonigle Hello, we use dynamic rate limiting for specific endpoints.

You can find dynamic limits defined in 
https://github.com/pixelfed/pixelfed/blob/7776cca9e9286edb075b55d027938d85099e3393/app/Util/RateLimit/User.php#L12-L20

**Comment by dpmcgonigle** [comment]
Wow, thank you for the speedy turnaround!  You're awesome!
