### ISSUE TITLE
remove predis

### ISSUE THREAD

**Issue by shleeable** [pixelfed/pixelfed#2078]
We should be able to use `phpredis` instead of `predis`.

it's a simple change, I just don't know how to remove stuff from the packages without errors.

**Comment by dansup** [comment]
@shleeable This would be a breaking change  because ```phpredis``` is a php extension and not a package meaning admins will need to install ```phpredis``` extension and add it to php.ini and restart apache/nginx.

We will eventually deprecate ```predis``` after giving admins plenty of time to install ```phpredis```.
