### ISSUE TITLE
API: notifications endpoint

### ISSUE THREAD

**Issue by Wv5twkFEKh54vo4tta9yu7dHa3** [pixelfed/pixelfed#2086]
Hi, while working with the `/api/v1/notifications` endpoint, I came upon a couple of issues:

- API returning 400 when not providing any of the arguments marked "optional" in the API

- API returning 302 when providing min_id=0 (1 works fine)

- reblogs (shares) don't show up in the web client, but do show up in the notifications endpoint. Is the omission from the web client deliberate? Should I ignore reblogs when implementing an application?

- reblogs in the notifications endpoint have their "reblog" field set to null. This doesn't strictly go against the API documentation, but it does go against the spirit of it I would think, and one would expect that field to be set

**Comment by dansup** [comment]
> API returning 400 when not providing any of the arguments marked "optional" in the API

This has been fixed in the staging branch, will be merged soon 

> API returning 302 when providing min_id=0 (1 works fine)

This has also been fixed and will be merged soon

> reblogs (shares) don't show up in the web client, but do show up in the notifications endpoint. Is the omission from the web client deliberate? Should I ignore reblogs when implementing an application?

This is a web client bug, shares/reblogs will be added to the notifications in the next release

> reblogs in the notifications endpoint have their "reblog" field set to null. This doesn't strictly go against the API documentation, but it does go against the spirit of it I would think, and one would expect that field to be set

The field is only there for legacy api purposes, the ```status``` field should be used instead
