### ISSUE TITLE
Bug: Undefined index error on friendica activity pub actions

### ISSUE THREAD

**Issue by techknowlogick** [pixelfed/pixelfed#2090]
When preferredUsername is not passed (for example from friendica), an error occurs on the following line of code: https://github.com/pixelfed/pixelfed/blob/dev/app/Util/ActivityPub/Helpers.php#L403

Possible solution: Checking if `preferredUsername` index is set before operating on it.

Error log:
```
production.ERROR: Undefined index: preferredUsername {"exception":"[object] (ErrorException(code: 0): Undefined index: preferredUsername at /var/www/app/Util/ActivityPub/Helpers.php:403)
```

**Comment by trwnh** [comment]
Duplicate of #1855
