### ISSUE TITLE
Comment not deleted until refresh

### ISSUE THREAD

**Issue by dobios** [pixelfed/pixelfed#2097]
In the home feed, the comment section of a post only shows the three latest comments (would be nice to see all of them using a `see more...` button or something of the sorts).   

Also I found the following bug when trying to delete a comment that I posted:

- After deleting a comment, a refresh (either opening or closing the comment section or reloading the page) is needed to delete the text. 
- This means that one can delete a comment twice, causing an error.

**Comment by dansup** [comment]
Fixed!
