### ISSUE TITLE
API: Child-Parents statuses are always empty

### ISSUE THREAD

**Issue by dobios** [pixelfed/pixelfed#2099]
When trying to retrieve the child statuses of a status via the /api/v1/statuses/{id}/context endpoint, I noticed that the result is always empty.

After digging through the code base I found it should be implemented in:
https://github.com/pixelfed/pixelfed/blob/dev/app/Transformer/Api/ContextTransformer.php
but instead the result is hard-coded as always empty. 

This in turn results in the status.replies_count to always be 0, even when replies have been posted.

Would it be possible to fix this ?

**Comment by dobios** [comment]
I'm trying to get the comments of a post, if there's an other way to do so, please let me know!

**Comment by dansup** [comment]
Fixed!
