### ISSUE TITLE
Notifications page shows horizontal scrolling on mobile web version

### ISSUE THREAD

**Issue by voss** [pixelfed/pixelfed#210]
When browsing the mobile version of the notifications page (https://pixelfed.social/account/activity) PixelFed on Android (8.1.0) (Chrome 67/Firefox 60.0.0.1), there's horizontal scrolling, cutting off the thumbnails of the photos on the right.

![screenshot_20180605-095643](https://user-images.githubusercontent.com/10601/40966027-45db03c8-68a7-11e8-8cfa-56a4359eae70.png)

**Comment by dansup** [comment]
Fixed in #211
