### ISSUE TITLE
Outbox collection an object instead of an array

### ISSUE THREAD

**Issue by koehn** [pixelfed/pixelfed#2100]
When I query an actor's outbox collection (e.g., https://pixelfed.koehn.com/users/bkoehn/outbox), the `orderedItems` is an object containing a `data` element, which contains the objects in the collection. 

```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "https://pixelfed.koehn.com/users/bkoehn/outbox",
  "type": "OrderedCollection",
  "totalItems": 66,
  "orderedItems": {
    "data": [
```
Instead, the `orderedItems` should be an array of the objects in the collection:
```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "https://pixelfed.koehn.com/users/bkoehn/outbox",
  "type": "OrderedCollection",
  "totalItems": 66,
  "orderedItems": [
```

**Comment by dansup** [comment]
The `fractal` PHP library we use is the culprit, will use a custom serializer to return the proper response!
