### ISSUE TITLE
Image resizing and optimization

### ISSUE THREAD

**Issue by dpmcgonigle** [pixelfed/pixelfed#2104]
Hello!  I've been working with Pixelfed across several different platforms (Mac Catalina, Linux Ubuntu 18.04, etc) and I've noticed the image optimization/resizing appears to work differently using different systems.  What I mean by this is we appear to be getting different pixel value distributions when posting the same image across different platforms when we go to inspect the result of posting the same image across different platforms.

Do you know what functionality within Pixelfed might be responsible for these differences, so that I might better understand how posting to Pixelfed will affect the resulting image?

**Comment by dansup** [comment]
@dpmcgonigle Image optimization in pixelfed is handled by ```JPEGOptim```, ```OptiPNG``` and ```PNGQuant```

**Comment by dpmcgonigle** [comment]
Thank you very much!
