### ISSUE TITLE
Media API 500s on bad Content-Type request header

### ISSUE THREAD

**Issue by snarfed** [pixelfed/pixelfed#2111]
not a big deal, but just fyi, when i upload a file to `/api/v1/media` via multipart POST and use the wrong `Content-Type`, eg `application/json` instead of `multipart/form-data`, i get an HTTP 500 response with the generic _Something went wrong_ HTML error response.

obviously it's a bad request, but i figured you'd probably want to 400 instead of crashing. just a heads up!

**Comment by connyduck** [comment]
Experienced this as well. It also happens when a part of the multipart has the wrong mime type.

**Comment by dansup** [comment]
Fixed!
