### ISSUE TITLE
API: Reblogged is always null when reblogging 

### ISSUE THREAD

**Issue by dobios** [pixelfed/pixelfed#2113]
Hi,
When testing out the `/api/v1/statuses/{id}/reblog` and `/api/v1/statuses/{id}/unreblog` API endpoints I noticed that I was capable of reblogging a post many many times without ever receiving a response that had a non null "reblogged" field.

I was thus able to reblog the same post 28 times in a row using the following request:

```
curl -i -X POST -H 'Authorization: Bearer [MyOAuthKey]' https://pixelfed.de/api/v1/statuses/[PostId]/reblog 
```
And got the following response:

```
{"id":"[id]","uri":"https://pixelfed.de/p/[user]/[id]","url":"https://pixelfed.de/p/[user]/[id]","in_reply_to_id":null,"in_reply_to_account_id":null,"reblog":null,"content":"","created_at":"2020-03-26T16:46:40.000000Z","emojis":[],"replies_count":0,"reblogs_count":28,"favourites_count":3,"reblogged":null,"favourited":null,"muted":null,"sensitive":false,"spoiler_text":"","visibility":"public","mentions":[],"tags":[],"card":null,"poll":null,"application":{"name":"web","website":null},"language":null,"pinned":null,"account":{"id":"[is]","username":"[user]","acct":"[user]","display_name":"[user]","locked":false,"created_at":"2020-03-15T18:36:38.000000Z","followers_count":7,"following_count":3,"statuses_count":5,"note":"H","url":"https://pixelfed.de/[user]","avatar":"https://pixelfed.de/storage/avatars/014/487/376/994/776/268/8/JXSErPTRWHxGuNykHrOL_avatar.jpeg?v=d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35","avatar_static":"https://pixelfed.de/storage/avatars/014/487/376/994/776/268/8/JXSErPTRWHxGuNykHrOL_avatar.jpeg?v=d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35","header":"","header_static":"","emojis":[],"moved":null,"fields":null,"bot":false,"software":"pixelfed","is_admin":false},"media_attachments":[{"id":"17465","type":"image","url":"https://pixelfed.de/storage/m/113a3e2124a33b1f5511e531953f5ee48456e0c7/228f28c9b67a9452a097a8a976581d3e7d2fe932/swyFU0XcQTF1HRJxypF7r0f0XJl4X9yw8dbZ6KBu.jpeg","remote_url":null,"preview_url":"https://pixelfed.de/storage/m/113a3e2124a33b1f5511e531953f5ee48456e0c7/228f28c9b67a9452a097a8a976581d3e7d2fe932/swyFU0XcQTF1HRJxypF7r0f0XJl4X9yw8dbZ6KBu_thumb.jpeg","text_url":null,"meta":null,"description":null}]}
```

**Comment by dobios** [comment]
I just noticed that `favorited` and `muted` are also always null...

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
So, now that a new version is out I was able to test the liking and unliking again. It doesn't error out anymore (like in #2088), but it has the weirdest behavior.

An example: I like a post with the API. I then immediately show up in the list of people who liked it (and the "x likes" counter in both the API and web UI), but neither the web UI or the API responses indicate that I have liked it (`favourited` is false, and the heart on the web UI is not red)

The response I get from the POST request to the endpoints don't reflect the value it's supposed to have, nor does it when I request the concerned status again.

Another weird effect of this: if I like a post with the API and then go to that post in the web UI, the heart is not red and when I make it red it removes me from the list of people who liked the post and decrements the "x likes" counter by one.

All of the above is exactly the same with shares (reblogs)

**Comment by dansup** [comment]
Fixed!
