### ISSUE TITLE
API 500 on creating a comment

### ISSUE THREAD

**Issue by snarfed** [pixelfed/pixelfed#2115]
hi again! i'm consistently getting a 500 from the API when attempting to create a comment with `/api/v1/statuses` with `in_reply_to_id`. full request details below.

POST https://piconic.co/api/v1/statuses
request body:
```json
{
  "status": "cute! (http://localhost/reply.html)",
  "in_reply_to_id": "156164634783649792"
}
```

response is HTTP 500 with the standard _Something went wrong_ HTML error page.

**Comment by snarfed** [comment]
Just checking in here. I haven't tried to repro recently; any chance this got fixed and the commenting API works now? Or is it still broken?

**Comment by dansup** [comment]
Fixed in latest commits!
