### ISSUE TITLE
Search API 500

### ISSUE THREAD

**Issue by snarfed** [pixelfed/pixelfed#2116]
hi again! i'm trying out the search API, and this request is 500ing for me. is it malformed? does pixelfed's search API work differently than mastodon's?

```sh
curl -v -H 'Authorization: Bearer ...' 'https://piconic.co/api/v2/search?q=localhost&resolve=True&offset=0&limit='
```

**Comment by dansup** [comment]
@snarfed I believe this is due to ```limit``` having no value. Will fix!
