### ISSUE TITLE
[Bug][Regression] Non-JS users can't load settings dropdown or post buttons

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#212]
The profile button now links to https://pixelfed.social/timeline# and as a result does not load anything -- not a dropdown, not a profile link, no way to get into settings without manually loading the URL.

**Comment by trwnh** [comment]
This is a side-effect of non-JS, as additionally the buttons disappear entirely.
![image](https://user-images.githubusercontent.com/10606431/40975795-b74707b6-6891-11e8-8eb4-334e7024aee3.png)

**Comment by hellcp** [comment]
Due to usage of SVG based font awesome, it's a matter of a simple font awesome base switch ;)

**Comment by dansup** [comment]
Fixed in latest commits, non-js users will need to use the Lite UI
