### ISSUE TITLE
Permission denied when starting docker container

### ISSUE THREAD

**Issue by noplanman** [pixelfed/pixelfed#2121]
Using v0.10.9, I get the following error when trying to start the docker apache container:

`/usr/local/bin/docker-php-entrypoint: 9: exec: /var/www/contrib/docker/start.apache.sh: Permission denied`

Not sure where the permissions are falling through, but clearly the entrypoint can't access the start script.
I've tried setting permissions to different users (including root and www-data) and even added an extra line to the Dockerfile (`RUN chown -R www-data:www-data /var/www`), to no avail...

**Comment by dansup** [comment]
cc @shleeable

**Comment by Strubbl** [comment]
start.apache.sh is missing exec rights.

`RUN chmod +x /var/www/contrib/docker/start.apache.sh`

**Comment by noplanman** [comment]
Right on @Strubbl, have added it to my PR (#2120) that fixes the Apache docker file.
Instead of adding another statement, I just made the files themselves executable to start with.
