### ISSUE TITLE
Followed accounts from external instances are not received after a domain migration

### ISSUE THREAD

**Issue by marcelcosta** [pixelfed/pixelfed#2130]
Hello!

I would like to ask something and I apologize in advance if my question is naive or not well formulated, as I don't have a solid programming foundation.

I collaborate in managing a pixelfed instance. Some months ago we migrate the domain. I have discovered that posts from accounts in pixelfed.social being followed by my instance account are not received. Interestingly, if I re-follow them they start to be. So I suspect that something related to domains in the database is not correct, but I don't know how to look at it. I've tried many of the commands suggested in pixelfed documentation without success.

In addition, I would like to ask what is the "routes" of `php artisan route:list` refering to? As this command throws me the following error:
```
Symfony\Component\HttpKernel\Exception\NotFoundHttpException  :
at /var/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1020
1016|      */
1017|     public function abort($code, $message = '', array $headers = [])
1018|     {
1019|         if ($code == 404) {
> 1020|             throw new NotFoundHttpException($message);
1021|         }
1022|
1023|         throw new HttpException($code, $message, null, $headers);
1024|     }
Exception trace:
```

Thank you very much!
If I have to explain something better or add more information, please ask!

Marcel

**Comment by trwnh** [comment]
domain migrations are not supported in the current activitypub network, since all `id` fields include the domain. this is why you must refollow -- the external instance is not aware of any objects on the new domain. there's nothing that can be done about this right now, until or unless the wider ecosystem figures out a way to refer to objects without depending on the domain's authority.
