### ISSUE TITLE
Allow non-members to view public timeline

### ISSUE THREAD

**Issue by qwazix** [pixelfed/pixelfed#214]
I think that we owe it to the web to not restrict content that should be public. If anyone can create account then they should be able to view the public tumeline imo.

**Comment by dansup** [comment]
@qwazix That is on the roadmap, thanks for making an issue so we can track it!

**Comment by dansup** [comment]
I have decided that the local timeline will not be visible to guests.

**Comment by trwnh** [comment]
Why?

**Comment by dansup** [comment]
@trwnh Would rather have the discover page public, showing a timeline to a guest would involve a lot of UI work.

**Comment by joeinnes** [comment]
Is the discover page actually public as mentioned above? Trying to access as a guest gives me 'Sorry, this page isn't available.'

**Comment by wakest** [comment]
this seems like one of the main things holding pixelfed back tbh. when I new person come to look at an instance they want to see whats on that instance. the instance picker showing some of the local posts goes a long way but that should really be on the instance page itself, maybe even the home page of the instance

**Comment by harcesz** [comment]
I can not express how much I agree with the above. I've just set up pixelfeed for a collective and I'm about to dump it for any normal gallery software as it's pretty much useless to us without a public timeline of some sort. I didnt even think to check if there is such an option it seemed so obvious and natural. We do not want people to register, we want them to be able to see images. 

And definitely, not being able to see what goes on on an instance, nor register at most might be turning away most users, it's why I ddnt even test it anywhere else before. Current splashpage just turns people away.

**Comment by KaKi87** [comment]
> Is the discover page actually public as mentioned above?

No, the sentence starts with *"[I] Would rather"*, which means it can be considered, not already done.

So, I created issue #3851 accordingly.
