### ISSUE TITLE
Problem when looking for users of my instance

### ISSUE THREAD

**Issue by MyNameIsTroll** [pixelfed/pixelfed#2140]
Hi,
When I search for users of my instance (pixelfed.social) by writing in the search bar for example: "@troll@pixelfed.social" it finds the user but when I click on "view profile" it says "Sorry, this page isn't available."
The search works well with other users who are on different instances of mine.

![64df4e6a795c4393](https://user-images.githubusercontent.com/31790025/79962652-977a1300-8488-11ea-8575-bc0115f648b1.png)
![26523e9ea6d19cf2](https://user-images.githubusercontent.com/31790025/79962658-9b0d9a00-8488-11ea-8b15-ef4a1463ace2.png)

**Comment by dansup** [comment]
@MyNameIsTroll Ah, for local users it should redirect, will fix!

**Comment by dansup** [comment]
Fixed in latest commits!
