### ISSUE TITLE
Thumbnail images are not centrered

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#2141]
When uploading multiple images, a thumbnail of them uses only the left part of the image (I think it tries to fit image to square, but does it wrong). May be somehow related to #578
![изображение](https://user-images.githubusercontent.com/2780044/79976864-fef28b80-84a5-11ea-98e0-04b0bc63ab00.png)

Can reproduce on Pixelfed.social 0.10.9

**Comment by trwnh** [comment]
i'd like to see pixelfed support focal points ideally

**Comment by dansup** [comment]
Fixed in latest commits!
