### ISSUE TITLE
[Feature request] Only ask for 2FA code for login

### ISSUE THREAD

**Issue by tux93** [pixelfed/pixelfed#2145]
After activating Two Factor Authentication for my Account I am asked for the 2FA code whenever the page was inactive or closed for some time.

I believe this should only happen if I get logged out or try to access security settings, for example changing the password, which isn't the case: It asks always when returning to the instance, e.g. the home or public timeline.

![Screenshot_2020-04-26_00-25-22](https://user-images.githubusercontent.com/1749593/80292228-5f5b2480-8755-11ea-8ae2-7bfcdba0a38e.jpg)

**Comment by dansup** [comment]
@tux93 You should only see that after logging in, is this your own instance?

**Comment by tux93** [comment]
@dansup No, I'm on pixelfed.de

**Comment by dansup** [comment]
This isn't a bug, the session timeout on your instance has likely trigged you to login again and re-enter 2FA credentials.
