### ISSUE TITLE
[tags] posts not listed on hashtag page if tag is in comment

### ISSUE THREAD

**Issue by encarsia** [pixelfed/pixelfed#215]
See [this example](https://pixelfed.social/p/bennettscience/2046) for illustration. Click on any tag in the first comment.

**Comment by dansup** [comment]
@encarsia Good find! A comment doesn't have an photo, and the hashtag page lists only posts with a photo that contain the hashtag.

Solution 1: Allow comment hashtags to appear in the hashtag page that links to the comment permalink but still uses the parent post/image in results.

Solution 2: Don't link hashtags in comments

Feedback wanted!

**Comment by hellcp** [comment]
IMO, 1, there is value in people categorizing into more labels so it's easier to find stuff

**Comment by encarsia** [comment]
I'd prefer solution 1, too.

Pros:
 - add labels that you forgot in the caption because there is no edit function (will there be one?)
 - separate photo description from hashtags
 - allow other users to tag post

Cons:
 - outwit 150 character limit of post caption so potential Instagram-like hashtag flood is possible

**Comment by trwnh** [comment]
If you only respect hashtags in the caption, then the caption should be editable and should allow more than 150 characters.

**Comment by dansup** [comment]
Fixed in latest commits
