### ISSUE TITLE
Profile directory shows NaN posts/day for all profiles

### ISSUE THREAD

**Issue by MaybeThisIsRu** [pixelfed/pixelfed#2161]
On the profile directory [here](https://pixelfed.social/discover/profiles), all the profiles show NaN posts/day. Observed on Firefox 75.0 (64 bit).

Screenshot:

![Screenshot from 2020-04-30 20-13-03](https://user-images.githubusercontent.com/3974019/80724173-2a691c00-8b1f-11ea-8837-bc992621b1a8.png)

**Comment by dansup** [comment]
We have disabled the Profile Directory for now.

**Comment by MaybeThisIsRu** [comment]
Has this been solved?

**Comment by trwnh** [comment]
not sure, but it's obsolete as long as the profile directory is disabled

**Comment by MaybeThisIsRu** [comment]
Sorry, that seems counterintuitive to me. The profile directory was disabled _because_ of this bug, as a temporary measure. It makes sense to keep it open, and when the bug is fixed, to close this issue, and re-enable the directory.

**Comment by trwnh** [comment]
i closed it because it's inactive. when the profile directory is reintroduced, if the bug is still present, then this issue will be reopened. does that make more sense?
