### ISSUE TITLE
multiple pictures: no sign

### ISSUE THREAD

**Issue by gerhardbeck** [pixelfed/pixelfed#2162]
When a post is published there is no sign, that a post has multiple pictures. Any number like 1 of 2 would be great. Or a sign as in collections
e.g.: this is a post with two pictures
![Screenshot_2020-04-30 neunburg-ev shared a post](https://user-images.githubusercontent.com/41069802/80741749-78c7ec00-8b1a-11ea-9040-171808e69e19.jpg)

**Comment by dansup** [comment]
@gerhardbeck We use a library that supports swipe and the indicators are at the bottom of the image in the middle.

**Comment by gerhardbeck** [comment]
@dansup I noticed the swipe but didn't see the indicators. Thanks.
