### ISSUE TITLE
edit posts

### ISSUE THREAD

**Issue by gerhardbeck** [pixelfed/pixelfed#2163]
I wanted to edit the text of a post with multiple pictures. After publishing it and opening "edit" I couldn't edit the text

**Comment by dansup** [comment]
@gerhardbeck You cannot edit the caption, only the image description and filter within 24 hours of posting it.

**Comment by gerhardbeck** [comment]
@dansup I suggest to change it. It would be great and I think sometimes necessary to change the caption, too

**Comment by lalejand** [comment]
I would like to add hashtags that I'm thinking of to previous posts. But since the caption is not editable, I can't.
Also I see I have made an tipo in a previous post caption, but I can't correct it.
What is the reason why captions are not editable ?
