### ISSUE TITLE
Public timeline 403 errors with V1 api

### ISSUE THREAD

**Issue by cannod** [pixelfed/pixelfed#2168]
With reference to #2149, after logging into pixelfed via API using fedilab and tusky I get 403 errors for the public timeline.

"GET /api/v1/timelines/public?limit=30&local=true HTTP/1.1" 403 32 "-" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"

After some debugging it looks like $request->user()  is not getting set. As a test I changed routes/api.php;

`Route::get('timelines/public', 'Api\ApiV1Controller@timelinePublic');`
to
`Route::get('timelines/public', 'Api\ApiV1Controller@timelinePublic')->middleware($middleware);`

Cleared the route cache and that populated $request->user() and fixed the 403 errors.

Not sure if this is a fix but thought I'd post what I did.

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Can confirm. 

`curl -H "Authorization: Bearer {TOKEN}" https://staging.pixelfed.net/api/v1/timelines/public` returns a 403, where a server running the last release works fine.
