### ISSUE TITLE
Upload video to a "Story"

### ISSUE THREAD

**Issue by jfcolom** [pixelfed/pixelfed#2169]
Hello!

Is it possible to upload a MP4 video to a "Story"? I get this message:

> Invalid FileType. The file you are trying to add is not a valid mime type. Please upload a image/jpeg,image/png only

I have configured MEDIA_TYPES as follows in `.env`, and cleaned the cache. I can post MP4 video
```
MEDIA_TYPES='image/jpeg,image/png,image/gif,video/mp4'
```
Thank you very much in advance

**Comment by dansup** [comment]
Stories only support images for now.
