### ISSUE TITLE
Private posts on Discover page

### ISSUE THREAD

**Issue by dominikstraessle** [pixelfed/pixelfed#2170]
Hi

I'm running a pixelfed instance, where all profiles and posts are private. When I open the Discover page, the users can't see anything. I understand, that this specific page is designed to only show public posts. But it would be nice, to see private posts of profiles I follow (posts I'm authorized to see) too. Then the users would have an alternative and interesting overview beside the local timeline.

I think, think a good starting point would be the following lines in the class `InternalApiController` (See [Line 90](https://github.com/pixelfed/pixelfed/blob/6c7c94f31f4819ecc050ba82e2c2314bde6cf0ff/app/Http/Controllers/InternalApiController.php#L90)):
```php
        $posts = Status::select(
                'id', 
                'caption', 
                'profile_id',
                'type'
              )
              ->whereNull('uri')
              ->whereIn('type', ['photo','photo:album', 'video'])
              ->whereIsNsfw(false)
              ->whereVisibility('public')
              ->whereNotIn('profile_id', $following)
              ->whereDate('created_at', '>', now()->subMonths(3))
              ->with('media')
              ->inRandomOrder()
              ->latest()
              ->take(37)
              ->get();
```

To achieve this, the mentioned line has to be removed and replaced with an authorization mechanism, so that only posts are listed, which the users are authorized to.

I think, the following problem could also be related:  
The Discover hashtag page (e.g. `/discover/tags/nature`) does only show public posts too. So if all the profiles and posts are private, this functionality therefore becomes useless.

**Comment by dansup** [comment]
Fixed!
