### ISSUE TITLE
Use white for the background of posts with non-square aspect ratios

### ISSUE THREAD

**Issue by MyNameIsTroll** [pixelfed/pixelfed#2173]
Hi everybody,
I find that the black bars don't really highlight the photos and it even tends to make the interface heavier.
In addition it makes too much think of the black bars on the TV when the format does not match the cinema format, we almost expect it to be a video...
I think it would make more sense to use white which is the same color as the rest of the interface. 

![1](https://user-images.githubusercontent.com/31790025/81158569-66213d00-8f88-11ea-86fd-7eb66a51f463.jpg)
![2](https://user-images.githubusercontent.com/31790025/81158574-67526a00-8f88-11ea-9fd6-f270e7127c31.jpg)
![3](https://user-images.githubusercontent.com/31790025/81158576-67526a00-8f88-11ea-8aea-4f24538231fa.jpg)

**Comment by trwnh** [comment]
the black area is the media area, the white area is the post area. on vertical layouts, there is no padding and therefore no black visible, but it is still there underneath the picture.

**Comment by jimmybrancaccio** [comment]
This should really be re-opened and fixed. There's got to be a way to make the post element more responsive. cc. @dansup 

https://discord.com/channels/446875483016134658/805369031876018207/875172969637347328

**Comment by dansup** [comment]
Fixed!
