### ISSUE TITLE
Why a specific button to enlarge the photo ?

### ISSUE THREAD

**Issue by MyNameIsTroll** [pixelfed/pixelfed#2174]
Hi everyone,
I found myself several times trying to click on the picture to try to enlarge it...
It seems to me that this is the most intuitive behaviour, when I see an image and I want to see it in a larger size I click on it. It seems more natural and intuitive to me than having to go through a dedicated button.
You can also make the magnifying glass+ icon appear on hovering if needed.

![a1](https://user-images.githubusercontent.com/31790025/81161427-d8dfe780-8f8b-11ea-9346-281fb4bcbdf0.jpg)
![a2](https://user-images.githubusercontent.com/31790025/81161430-d9787e00-8f8b-11ea-9ae1-7919e66a7ef4.jpg)

**Comment by trwnh** [comment]
- clicking is not as intuitive as having a dedicated button
- the lightbox feature is not complete

**Comment by lapineige** [comment]
> clicking is not as intuitive as having a dedicated button

I'm skeptical about that, especially for mobile users, but anyway why not a button and the click-on-image functionality ?
