### ISSUE TITLE
Story image is cropped on mobile

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#2184]
Tested on pixelfed.social instance.

Here is how the image looks on PC (same as original)
![изображение](https://user-images.githubusercontent.com/2780044/82194388-6661f680-98ff-11ea-9151-df2d9f038220.png)

Here is how it looks on mobile (cropped from the sides)
![изображение](https://user-images.githubusercontent.com/2780044/82194431-7c6fb700-98ff-11ea-81a9-142f8a1e3fc3.png)

**Comment by trwnh** [comment]
which is more desirable -- that mobile stories are fullscreen, or that they show the full image?

**Comment by MasterGroosha** [comment]
@trwnh if image can be zoomed, then showing the full image, since important things are not always in the very center, IMO

**Comment by trwnh** [comment]
i'm wondering what precedent is on e.g. snapchat or instagram with mobile devices, given the new trend of devices that aren't 16:9... how are 16:9 stories displayed on 18:9 devices, and vice-versa?

**Comment by Huy-Ngo** [comment]
> i'm wondering what precedent is on e.g. snapchat or instagram 

Iirc they're shown in full instead of cropped.

**Comment by 3xrp1** [comment]
Full image for sure. A cropped image is really annoying and looks bad.

**Comment by dansup** [comment]
Fixed!
