### ISSUE TITLE
MomentUI fails to render title properly

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#2185]
Tested on pixelfed.social. I see the following issues here:
* Title text is cut (it's longer in classic UI)
* Hashtags aren't clickable and are rendered incorectly

![изображение](https://user-images.githubusercontent.com/2780044/82195197-a7a6d600-9900-11ea-8ddf-a01313e13420.png)

**Comment by dansup** [comment]
Fixed in the latest commits.

**Comment by lapineige** [comment]
@dansup could you link to that commit ? I wonder if it's fixed in 0.10.9, because I have the same issue.

**Comment by lapineige** [comment]
Uh, seems to be somewhat related with these ones ? https://github.com/pixelfed/pixelfed/issues/2154#issuecomment-633211207
