### ISSUE TITLE
Images are oversaturated in profile preview

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#2187]
Probably it happens when filters are applied to images (as far as I remember, that photo has Gingham filter). Tested on Pixelfed.social.
![изображение](https://user-images.githubusercontent.com/2780044/82195464-010f0500-9901-11ea-8ab0-764d05eac906.png)
The image as shown on a separate page
![изображение](https://user-images.githubusercontent.com/2780044/82195616-31ef3a00-9901-11ea-8078-833ed320a30a.png)

**Comment by trwnh** [comment]
perhaps the filter is being applied only to the thumbnail?

**Comment by MasterGroosha** [comment]
This is still relevant btw

**Comment by dansup** [comment]
Fixed!
