### ISSUE TITLE
Redundant / broken "Edit" button on images

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#2188]
Tested on pixelfed.social

* Go to published post.
* Tap on 3 dots in top right corner -> Edit
![изображение](https://user-images.githubusercontent.com/2780044/82196240-205a6200-9902-11ea-944b-6e55d5ca67a7.png)

Result: 
![изображение](https://user-images.githubusercontent.com/2780044/82196276-294b3380-9902-11ea-8905-99b5e0284d73.png)

Maybe it happens because, as [you said](https://github.com/pixelfed/pixelfed/issues/2163#issuecomment-622245867) user cannot edit "old" posts. In this case there shouldn't be such option at all then.

**Comment by dansup** [comment]
Fixed in latest commits!
