### ISSUE TITLE
MAX_NAME_LENGTH setting not respected

### ISSUE THREAD

**Issue by jshholland** [pixelfed/pixelfed#2191]
`MAX_NAME_LENGTH` is [documented](https://docs.pixelfed.org/technical-documentation/env.html#pixelfed-configuration) as having a default value of 30. However, on my instance (running Pixelfed 0.10.9 from git with Postgres 10, PHP 7.2, Laravel 6.18), if I try to create a user with a username longer than 15 characters, the form at /register gives an error saying "The username may not be greater than 15 characters.". I have tried specifying MAX_NAME_LENGTH explicitly in `.env` (remembering to run `php artisan config:cache` after changes, even restarting php-fpm and nginx to be on the safe side) but it doesn't make any difference.

**Comment by dansup** [comment]
`MAX_NAME_LENGTH` is for display names, usernames are limited to 15 characters.
