### ISSUE TITLE
Rate limit requests to other ActivityPub implementations

### ISSUE THREAD

**Issue by chendo** [pixelfed/pixelfed#2202]
Our Mastodon instance is seeing occasional spikes of 500 requests in a second from "Pixelfed/0.10.9; +https://pixelfed.social" for the same URL for a user on our instance that has been deleted. The user has been deleted so it returns 410 Gone.

Pixelfed should consider rate limiting requests to other ActivityPub instances, as well as consider client-side caching of these responses. I can supply log files of this issue privately if you'd like.

**Comment by chendo** [comment]
Observed another 653 requests for the exact same user over the space of 3 seconds. We've mitigated this by caching 410 responses but our DoS mitigation has caught pixelfed.social multiple times.

**Comment by dansup** [comment]
Fixed!
