### ISSUE TITLE
"Load new posts" populates timeline with posts older than the one at the top

### ISSUE THREAD

**Issue by astrosticks** [pixelfed/pixelfed#2208]
I don't follow many accounts or hashtags so my timeline isn't changing very often. Now, when I go to my home timeline, after a few seconds, the "Load new posts" will pop up, I'll click it, and older posts from my timeline will show up. Here's some screenshots to show what I mean:

What I see as I load my timeline (my own post at the top):
![image](https://user-images.githubusercontent.com/32315760/82840559-a6dde900-9e98-11ea-80d4-39f2ed45c99b.png)

After clicking "Load more posts" (a post of mine from last year is now ontop, and a post from the official PixelFed account from a year ago as well, underneath): 
![image](https://user-images.githubusercontent.com/32315760/82840614-d987e180-9e98-11ea-9211-cdcc875aca3e.png)

**Comment by egon0** [comment]
same here

**Comment by dansup** [comment]
Fixed in the latest commits!
