### ISSUE TITLE
federation timeouts far too low

### ISSUE THREAD

**Issue by BenLubar** [pixelfed/pixelfed#2209]
The timeouts for "pull" actions are hard-coded to 5 seconds, and the default timeout for "push" actions is 2 seconds. A slow DNS lookup can easily take 10 seconds, and because these background operations are not permitted to retry, this is causing a significant amount of ActivityStreams actions to be silently discarded when they would otherwise be accepted.

**Comment by dansup** [comment]
Fixed in latest commits
