### ISSUE TITLE
Love icon get colored when unlike, while uncolored when like.

### ISSUE THREAD

**Issue by Ahmad-Amsyar** [pixelfed/pixelfed#221]
This seems happen on old post.

![love icon](https://user-images.githubusercontent.com/27284123/41022731-0b730c3e-699d-11e8-9540-b7198fb8ceb8.gif)

**Comment by trwnh** [comment]
Side effect of likes being hydrated by API but previous likes not being registered.

Workaround: clear your cache. @dansup suggests opening Dev Tools in your browser of choice, going to "Console", and typing ls.clear() followed by Enter.

**Comment by qwazix** [comment]
I don't know if I should open another issue but if due to this bug you mistakenly unlike a photo, trying to re-like it causes an error 500.

`ls.clear()` doesn't help

**Comment by ghost** [comment]
I am not sure whether I should open a new issue, but I have experienced the following issues regarding the like/love button/icon:
1 - It does not change its color when I like a post, never. Neither it makes any difference if I visit a liked post (stays the same as if it was unliked). So I have no means of knowing whether I liked a post (apart from my memory).
2 - If I like a post, the counter (x likes) increments (ok). Then if I unlike it, the counter decrements (ok). But if I like it again, the counter stays the same (maybe related to the error 500 previously mentioned).

**Comment by dansup** [comment]
Fixed in latest commits

**Comment by trwnh** [comment]
I'm having the same problem as @qwazix with this post: https://pixelfed.social/p/trwnh/276

**Comment by trwnh** [comment]
this can be closed again now that dansup fixed the ghost like issue
