### ISSUE TITLE
View Replies Lead To 404 Error

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2213]
Hi @dansup 

Click on **View Replies** within post and some will expand and some will result in 

Error: Request failed with status code 404

**Comment by dansup** [comment]
@okpierre This usually happens when a reply is deleted and the parent status reply_count is not updated. Will fix in the next release!

**Comment by okpierre** [comment]
@dansup also a problem with remote replies that are not deleted

**Comment by georgkrause** [comment]
I experienced the same issue as @okpierre with remote replies.

**Comment by dansup** [comment]
Fixed in latest commits!
