### ISSUE TITLE
[Feature request] Screenshot/image download blocking

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#2216]
Hello,

I don't even know if it's technically possible, but it would be a good idea to be able to block both of them since they are often used in malicious ways, for a better protection of our image rights.

**Comment by jeena** [comment]
If the browser can show the picture then it's already in the computers RAM and can be screenshoted, or you can even take a picture with your phone of it. I don't think it makes sense to invest time in such a feature, nobody else on the internet came up with a solution other than big fat watermarks on the pictures, and even that is possible to remove with just one click in Photoshop https://www.youtube.com/watch?v=6Zj4gLcCi2Q
