### ISSUE TITLE
Enable NSFW previews

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#2225]
Hello,

To see a nsfw picture after searching "nsfw" in the search bar, i have to open it one by one and click on the NSFW message to see how the pic looks like, and it's pretty unergonomic if i'm looking particulary for NSFW content. I'd like to be able to disable the NSFW masking for myself.

**Comment by ChameleonScales** [comment]
Any chance we could have this toggle in the Home Timeline ?
Even better would be to have it as a global setting in the account settings I think.

**Comment by mercmobily** [comment]
Where is this setting, in the old OR the new design? I am asking for a friend...

**Comment by Dark-Thoughts** [comment]
> Where is this setting, in the old OR the new design? I am asking for a friend...

In the old design there was a toggle within the search feed but no global setting. In the new design they seem to have forgotten all about it... Prime example of enshittification.
