### ISSUE TITLE
Search for a location gives no results

### ISSUE THREAD

**Issue by Strubbl** [pixelfed/pixelfed#2228]
If i use the pixelfed search field at the top on the startpage and i enter a location, it does not find any post. It would be nice if one can search for a location and see all pictures which are posted with that location

**Comment by egon0** [comment]
Have you done this post-installation step?

https://docs.pixelfed.org/installing-pixelfed/postinstall.html#import-places-data

**Comment by Strubbl** [comment]
Yes of course. I can add search locations to my posts. But if i search for that of the town, i do not see the picture.

**Comment by dansup** [comment]
@Strubbl Search does not currently support Places yet.
