### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#2229]
Hello,

After logging in my own instance i have the following message:

```
**Something went wrong**

We cannot process your request at this time, please try again later. Go back to Pixelfed.
```

According my dev console, this is an HTTP 500 error. What did i do wrong ?

**Comment by kromonos** [comment]
Did you execute "php artisan migrate"?

**Comment by stemy2** [comment]
The problem disappears suddenly.

**Comment by stemy2** [comment]
The problem reappeared and i launched the command, but it didn't worked.

**Comment by kromonos** [comment]
Looks like there is missing php-pdo dependencies. What php modules do you have enabled?

**Comment by stemy2** [comment]
Hmm, that's really strange. The app worked well until the problem appeared out of the blue. Does it means that a dependancy can vanish itself ?

**Comment by stemy2** [comment]
It solved itself. Again.

**Comment by stemy2** [comment]
The failure is back.

As you said, it seems to be a problem with pdo, cause i have another app with this problem too (framaforms) and its error message is explicitely talking about pdo. And when i remove the app, pixelfed is working again, as well as framaforms after reinstall.

**Comment by dansup** [comment]
@stemy2 This looks like the application failed to connect to your database. Also you posted your database credentials in the stacktrace you posted above. 

**Please generate new credentials and be more careful when posting stack traces!**
