### ISSUE TITLE
Non-JPG gets broken by optimization job

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#223]
https://pixelfed.social/p/trwnh/1740
https://pixelfed.social/p/trwnh/2038

Both were uploaded as GIF, and after optimization, were broken. Also, the backgrounds aren't transparent anymore.

Related issues: #45, #67, #139

Ideas: for the thumbnail, the first frame of an animation can be extracted and used as-is. An overlay would indicate that it is an animation (and animation autoplay should be toggleable off in the future). A single frame of a GIF takes up less space than a JPG.

**Comment by encarsia** [comment]
I can confirm this, the optimization job of animated GIFs results in the opposite. Comparison:

&nbsp; | Uploaded file | [File in post](https://pixelfed.social/p/encarsia/2256)
-|------------------|-------------------------
Size | 635 × 67 px | 1920 × 203 px
File size | 49,9 kB | 130,9 kB
Layers | 3 | 1 (no animation)

Maybe (animated) GIFs should be excluded from the optimization job. If this is an option a lower file size limit of that specific file type might be appropriate.

**Comment by hellcp** [comment]
Something I mentioned on IRC, but will repeat here, as it's relevant. Twitter turns non-JPG formats into JPG unless there is:
* Animation
* Transparency

Then it leaves original format.

**Comment by dansup** [comment]
Fixed in latest commits
