### ISSUE TITLE
Private user cannot see comment on another private user's post

### ISSUE THREAD

**Issue by thejonwithnoh** [pixelfed/pixelfed#2230]
## Setup
A, B, and C are private users
B and C are following A
A posts a picture (picture post has id 1, and URL is example.com/p/A/1)
B comments on the picture (comment has id 2, and URL is example.com/p/B/2)
#### B cannot see the comment on the picture's page (example.com/p/A/1), but can see the comment on the comment's page (example.com/p/B/2)
This problem seems like a definite bug to me. It should be noted that B can see the comment immediately after posting, but cannot see the comment after refreshing the page.
#### C cannot see the comment on the picture's page (example.com/p/A/1), and also cannot see the comment on the comment's page (example.com/p/B/2)
This result is somewhat more expected, and I can easily imagine situations in which this is desirable. However, I can also imagine situations where this is undesirable (as I happen to be in one  right now :slightly_smiling_face:). It might also instead be desirable to have an option for the visibility of the comment to be tied to the visibility of the original picture post (so that if a user is able to see a post, then they can see all of the comments on that post, without the comments needing to be completely public).

**Comment by Huy-Ngo** [comment]
My account is not private, and I can't see comment from a private user either. Is this the same issue as addressed  here?

**Comment by stevenroose** [comment]
Yeah I definitely agree that if someone can see a post they should be able to see the comments under it. I think it's fair to say that commenting to a post comes with the understanding that you're sharing your comment with the people that are able to see the post..

**Comment by dansup** [comment]
Fixed!
