### ISSUE TITLE
Questions about Pixelfeds api/v1/instance endpoint implementation

### ISSUE THREAD

**Issue by connyduck** [pixelfed/pixelfed#2233]
I have a few questions about the response of https://pixelfed.social/api/v1/instance, would be cool if you can answer it so I can improve the Pixelfed support of my Android Client.

`"max_toot_chars": "2000"` <- other implementations use an Integer for this attribute, why is Pixelfed returning a String here?

```
"environment": {
    "max_photo_size": "15000",
    "max_avatar_size": 5000,
    "max_caption_length": "2000",
    "max_bio_length": "250",
    "max_album_length": "10",
    "mobile_apis": true
}
```

Is `environment` a custom Pixelfed attribute? Do I assume it correctly that the unit of `max_photo_size `and `max_avatar_size` are 1000 bytes? Why is `max_photo_size` a String, but `max_avatar_size` an Integer?
What is the meaning of the `mobile_apis` flag?

(Is there a documentation of Pixelfeds Api implementation that could help answering such questions?)

**Comment by dansup** [comment]
@connyduck Hey!

> "max_toot_chars": "2000" <- other implementations use an Integer for this attribute, why is Pixelfed returning a String here?

I will fix this to return an integer.

> Is environment a custom Pixelfed attribute?

Yes

> Do I assume it correctly that the unit of max_photo_size and max_avatar_size are 1000 bytes?

Yes, these values can be customized per instance and are KB.

> Why is max_photo_size a String, but max_avatar_size an Integer?

They should be integers, will fix!

> What is the meaning of the mobile_apis flag?

This determines if the instance supports apis for Tusky and other 3rd party applications. In the future it will be removed and support will be enabled by default.

We have a basic list of [API differences](https://docs.pixelfed.org/technical-documentation/api-v1.html), I will work on updating them to be more comprehensive and cover any undocumented APIs!

**Comment by connyduck** [comment]
Thx for the help 😊
