### ISSUE TITLE
Type Announce InboxValidator Failed

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2237]
Hope this will help with the federation problem @dansup 

App\Jobs\InboxPipeline\InboxValidator
ID: 37
Queue: high

`Symfony\Component\Debug\Exception\FatalThrowableError:  syntax error, unexpected ')' in  /home/cbuzz/pixelfed/app/Util/ActivityPub/Inbox.php:303`

`payload: "{"@context":["https://www.w3.org/ns/activitystreams","https://w3id.org/security/v1"],"id":"https://misskey/notes/88eqio8ieq/activity","actor":"https://misskey/users/882ggfdae5","type":"Announce","published":"2020-06-09T00:22:15.618Z","to":["https://www.w3.org/ns/activitystreams#Public"],"cc":["https://misskey/users/882ggfdae5/followers"],"object":"https://pixelfed/p/test123/185362632369300336"}",`

**Comment by dansup** [comment]
Fixed in latest commits
