### ISSUE TITLE
PF_USER_INVITES not sending email invite

### ISSUE THREAD

**Issue by fireball74** [pixelfed/pixelfed#2238]
Pixelfed 0.10.9
MySQL 10.3.22-MariaDB-1
PHP 7.4.5
Laravel 6.18.19

Got Pixelfed set up with regular registration and email verification working fine. Trying to set up invites I added PF_USER_INVITES set to true (and with OPEN_REGISTRATION set to false). I added the different thresholds as well (PF_USER_INVITES_TOTAL_LIMIT, PF_USER_INVITES_DAILY_LIMIT, PF_USER_INVITES_MONTHLY_LIMIT) successfully. It all seems to work and "Invites" show up in the sidebar as expected. Sending an invite, Pixelfed pretends to send an invite but nothing is sent. Once an invite has been issued no new invite can be made even if the config allows it. When trying to delete the pending invite using the delete button in the UI, nothing happens.

Exactly the same behavior running on a clean install as when using the docker image.

* No invite is sent (**please advise on how to debug**)
* Configured invite threshold not respected, only one active invite is allowed
* Pending invite cannot be deleted using the UI

**Comment by cannod** [comment]
I can confirm the same behavior.

**Comment by dansup** [comment]
This feature has not been released yet.

**Comment by albjeremias** [comment]
without this issue invitation only is useless... 
I tried to join freenode #pixelfed-dev but no one is there.. on matrix a bit more people.

need to solve this issue ASAP so that pixelfed can be hosted on our project!

anyway, thank you for you awesome work...

**Comment by stevenroose** [comment]
> without this issue invitation only is useless... I tried to join freenode #pixelfed-dev but no one is there.. on matrix a bit more people.
> 
> need to solve this issue ASAP so that pixelfed can be hosted on our project!
> 
> anyway, thank you for you awesome work...

@albjeremias there is no matrix mentioned anywhere in this repo AFAIK. what is the matrix room address?

**Comment by stevenroose** [comment]
> This feature has not been released yet.

Has it already been released now?

**Comment by dansup** [comment]
This feature is still not released.
