### ISSUE TITLE
Contact form seems to count characters differently than the server

### ISSUE THREAD

**Issue by blipp** [pixelfed/pixelfed#2240]
### How to reproduce

* Go to `/site/contact` on a Pixelfed instance
* Enter the following text, which is 500 characters according to the status display just under the textarea:
```
The message must be at least 5 characters. The message must be at least 5 characters. The message must be at least 5 characters. The message must be at least 5 characters. The message must be at least 5 characters. The message must be at least 5 characters. The message must be at least 5 characters. The message must be at least 5 characters. The message must be at least 5 characters. The message must be at least 5 characters. The message must be at least 5 characters.
The message must be at leas
```
* Click “Submit”

### What happens

Error message “The message may not be greater than 500 characters.” is displayed.

### What should happen

The message should be accepted.

### How I constructed the example

* Create some text that does not contain newlines and that is 500 characters long.
* Remove one character at the end.
* Insert a newline somewhere.

### Hints

* Maybe the server counts two because the newline is "\n\r" (or the other way around, I cannot remember)?
* Does it depend on the system of the user (Linux vs Windows)? I am on Ubuntu, Firefox 77.0.1.

**Comment by dansup** [comment]
Fixed!
