### ISSUE TITLE
The icon to access the Crop-and-Rotate tool is misleading.

### ISSUE THREAD

**Issue by narFnarF** [pixelfed/pixelfed#2242]
In the Compose screen, the "magic wand" button is misleading because it opens to the Crop-and-Rotate tool. It's misleading because the "magic wand" button is commonly used in other apps to signify an "automatic improvement" of the picture's lighting and color balance, which is not what Pixelfed does when pressing that button.

![](https://i.imgur.com/n4IzMir.jpg)

To reproduce:

1.    Login to https://pixelfed.social/ and tap the Create button
1.    Select "New Post", then import a picture
1.    Observe the "magic wand" button

Current result: The button looks like a "magic wand" icon.

Expected: The icon looks like a Crop-and-Rotate icon.
Here's a reference of the Crop-and-Rotate from Photo apps on iOS:
![](https://i.imgur.com/685PsWv.png)

The same Photos app on iOS uses the "magic wand" icon to signify an automated way of improving the picture, which automatically adjust color and contrast when pressed.
![](https://i.imgur.com/ddwdIaN.png)

For reference, here's 2 Crop-and-rotate icons from Flaticon:
* https://www.flaticon.com/free-icon/crop_565803?term=crop%20rotate&page=1&position=5
* https://www.flaticon.com/free-icon/crop_1138963?term=crop%20rotate&page=1&position=11
I think Flaticon provides resources that are ok to use in a project like Pixelfed, but I'm not entirely sure about this.

Tested in the browser of an iPhone 5s.

**Comment by Anglodel** [comment]
Hey, that’s cool, I came here exactly to present the same problem. I agree with you, it’s confusing. 👍

**Comment by dansup** [comment]
Fixed in latest commits.
