### ISSUE TITLE
The textbox to enter a caption is tiny and doesn't expend

### ISSUE THREAD

**Issue by narFnarF** [pixelfed/pixelfed#2243]
When writing a caption (a post) to accompany a picture, the provided UI textbox is quite tiny (about 2.5 lines of text) which makes writing longer post quite difficult. On computer with a big screen, this is not too bad, but on mobile, this is especially problematic because it only fits about 10 words before needing to scroll.

![](https://i.imgur.com/PKR126x.png)

To reproduce:

1.    Use a mobile phone
1.    Login to https://pixelfed.social/ and tap the Create button
1.    Select "New Post", then import a picture
1.    Tap "Next"
1.    In the Caption UI textbox, type a long sentence.

Current result: After just 2 lines of text, the textbox start scrolling.

Suggestion: 
I see 2 ways to solve this issue:

The best way, in my opinion, would be to make the textbox expend as more text is entered. Maybe up to a limit of ~10 lines of text or whatever make sense for the UI. I expect this might be more difficult.

Another simpler way would be to just make the box bigger by default. At least 5 lines of height, maybe even 6 or 8 lines. If you look at the screenshot I provided above, I see some empty space below, so I think there's enough space to make that textbox bigger.

Tested in the browser of an iPhone 5s.

**Comment by idotj** [comment]
I tried to reproduce the problem on my phone (Firefox and Chrome under Android11) and all works as expected. I can see 3 lines of my caption text. Maybe during this time the caption area has evolved and a PR fixed the two and a half lines issue.

![image](https://user-images.githubusercontent.com/6554216/175099102-49003ad8-c6e9-4799-80a0-b3efc1ecc672.png)

But it's true that for mobile version 3 lines of text are not enough, and the only solution is dealing with JS to render the textarea dynamic. As @narFnarF said, something like this will improve the caption in mobile:
https://codepen.io/ipuntoj/pen/abqeEzN

**Comment by narFnarF** [comment]
I just tried again. We now see about 4.75 lines (4 lines and 3 quarters). Better, but still pretty tiny if we want to write something more substantial. I agree that the textbox should expand, like @idotj is suggesting. This would be ideal!

Here's a screenshot of what it looks like now:
![](https://i.imgur.com/UnuJTI0.jpg)

This is on my iPhone 6s, running Pixelfed in "add to Homescreen" mode.

**Comment by dansup** [comment]
Fixed!
