### ISSUE TITLE
Media upload API POST returns HTTP 200 but does not process the upload

### ISSUE THREAD

**Issue by pla1** [pixelfed/pixelfed#2244]
Attempting to get my Android app [Fedi Photo](https://fediphoto.com/) working with PixelFed. The app works with Mastodon and Pleroma. The app successfully authorizes my account https://pixelfed.social/PLA.  The post to https://pixelfed.social/api/v1/media return an HTTP 200 with HTML output for a login form. 

I would think if something is wrong with my POST it should return something other than a 200. 

Perhaps you can take a look at the logs and let me know what I need to do differently. Thanks!

**Comment by pla1** [comment]
I found several bugs in my code. Sorry for the noise. Although I could never get direct visibility to work.  public, unlisted, private all work though. Closing this issue. :peace_symbol:

**Comment by swentel** [comment]
@pla1 I'm getting the 200 as well for an app I'm writing. Cloudflare is asking for a way to bypass the captcha when trying to upload a post. Any pointers on how you got around it would be great! :)

**Comment by pla1** [comment]
@swentel I was using uppercase PUBLIC instead of lowercase public for the visibility parameter when posting a status.

**Comment by swentel** [comment]
Hmm ok. I'm not even posting that yet, still at the part of posting an image to api/v1/media.
will keeping looking, thanks for the answer already!
