### ISSUE TITLE
Can't embed from my own instance

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#2246]
Hello,

I tried to embed content from my own instance, but i only have a blank page, and it works well with the main PF instance. You can try by yourself, maybe you'll understand what's wrong, because i don't.

Link to the post
`https://pixelfed.stemy.me/p/Stemy/178062763443228672`

Embed code
`<iframe src="https://pixelfed.stemy.me/p/Stemy/178062763443228672/embed?caption=true&likes=false&layout=full" class="pixelfed__embed" style="max-width: 100%; border: 0" width="400" allowfullscreen="allowfullscreen"></iframe><script async defer src="https://pixelfed.stemy.me/embed.js"></script>`

**Comment by dansup** [comment]
@stemy2 You likely have ```add_header X-Frame-Options "SAMEORIGIN";``` in your nginx config, remove that or comment it out and restart nginx!

**Comment by stemy2** [comment]
Were is exactly located the config file containing this parameter ? I searched but didn't found it.

**Comment by stemy2** [comment]
Nope, not any config file contains this line, i think the problem is elsewhere. Could you reopen the issue ?
