### ISSUE TITLE
Remove Google tracking pixel from confirmation email

### ISSUE THREAD

**Issue by Fluf22** [pixelfed/pixelfed#2247]
Hello,

I don't know if it was on purpose, but on registering, I found a tracking pixel from Google in my confirmation email:
![Screenshot_20200616-163124_FairEmail](https://user-images.githubusercontent.com/5392083/84788664-ad6f0480-afef-11ea-8a9f-6f760fbdfff3.png)

Why is it there?
Is this actually on purpose?
How did it get there?

Thanks,
Fluf

**Comment by dansup** [comment]
@Fluf22 Pixelfed uses Laravel under the hood, we do not use any tracking pixels in our project. It's likely from a 3rd party mail provider like MailGun, SendGrid or others. In that case there is nothing we can do, its up to the instance admin to configure and manage email delivery.

**Comment by Fluf22** [comment]
Okay, I get it! Sorry for disturbing, then 😃 
After further investigation, it seems that it is from mailjet, actually (if I'm not mistaken).

The only follow-up I would suggest, if I may, is to notify people (I don't know how nor where, maybe on registration?)

Anyway, thanks for looking into this! It's cool to have a maintainer following its project closely 😄
