### ISSUE TITLE
[Accessibility] "Reduced animations" setting

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#226]
https://github.com/dansup/pixelfed/issues/73#issuecomment-395084349

>A small note on animations - A reduced motion feature where there are less animations or they're less flashy would be very very helpful. Figured we'd bring this up before it became a major issue, what with #222 already being in the works.

Also briefly referred to in #223

**Comment by cedeber** [comment]
I just discovered the project and I am currently browsing randomly the issues. I don't know if you know about it or if you already talk about it, but as info https://webkit.org/blog/7551/responsive-design-for-motion/

**Comment by maznu** [comment]
From https://stuffandnonsense.co.uk/blog/redesigning-your-product-and-website-for-dark-mode:

> prefers-color-scheme is part of a suite of preference media query options including prefers-contrast, prefers-reduced-motion, and prefers-reduced-transparency.

Hopefully the other browser vendors will follow suit and make some sort of display preference setting to activate those CSS media queries.

**Comment by trwnh** [comment]
Added in latest commits!

![image](https://user-images.githubusercontent.com/10606431/61117667-a3966600-a45c-11e9-9785-0a7e2b5372fb.png)
