### ISSUE TITLE
Inbox URLs with uppercase letters not supported

### ISSUE THREAD

**Issue by TiMESPLiNTER** [pixelfed/pixelfed#2290]
I followed a user on pixelfed.de with my user from another instance. The username is `ALLCAPS`. The inbox url: `https://example.com/users/ALLCAPS/inbox`. But Pixelfed changes the url to `https://example.com/users/allcaps/inbox`. Delivery to this inbox fails therefor with a `404 Not Found`.

According to the standard: https://www.w3.org/TR/WD-html40-970708/htmlweb.html

> URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive. /u

Also see this SO post with more quotes from different RFCs: https://stackoverflow.com/a/26196170/1652031

**Comment by enko** [comment]
I ran into this issue yesterday myself. This is most likely triggered by this commit: https://github.com/pixelfed/pixelfed/commit/14ba350ba3f1bab6364a103b38441482b0929fe2

**Comment by dansup** [comment]
Fixed!
