### ISSUE TITLE
[Grid mode] Likes are visible

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#2293]
Currently there's an inconsistency between "Feed mode" and "Grid mode". If I remember correctly, @dansup said that Pixelfed will have likes counter disabled for other people's posts (just like Instagram).
With the introduction of Grid mode, likes count is visible again. Probably it's a bug.
Reproduced on https://pixelfed.social 

![изображение](https://user-images.githubusercontent.com/2780044/85226097-6b263880-b3de-11ea-948c-3994fc2a9e21.png)

**Comment by okpierre** [comment]
@MasterGroosha don't think it's a bug since 'likes' count is still visible viewing individual post..
