### ISSUE TITLE
Add 'Repost' Feature

### ISSUE THREAD

**Issue by NFGman** [pixelfed/pixelfed#23]
Simply, an option for users to repost posts they like.  There are several good reasons to do this:

1. Discoverability is a massive problem in a decentralized network.  When something appears on your feed as a repost, you can click the OP's profile to see if they're someone you want to follow.  Popular posts get shared around, accounts get noticed.  

2. It may help reduce image theft.  Instagram users have to download and re-upload images to share them, and if someone does this, they're less likely to credit, tag or even spell correctly the name of the original poster.  

If the ability is added to comment on the repost users can be tagged, conversations started.  Comments could be added to the original post's comment thread, so the OP would know what's being said.  

En/disabling this feature per-user or per-instance may be desirable.

**Comment by dansup** [comment]
This is done, I just have to commit it when I finish federation support!

**Comment by igalic** [comment]
@dansup can you reference this back here?

**Comment by okpierre** [comment]
Noticed this is marked closed. 

Where can I find and use this feature? 

@dansup  Was this made available for 0.9.4?

**Comment by trwnh** [comment]
@okpierre Currently there is the "share" icon on posts that does this. 
![image](https://user-images.githubusercontent.com/10606431/59489538-10134a80-8e48-11e9-959e-9dd026b7d8f0.png)

But the timelines currently do not show anything aside from original posts from the local instance -- this is what is being worked on and should launch with v0.10

**Comment by xplosionmind** [comment]
> Currently there is the "share" icon on posts that does this.

I do not see it… is there something wrong in my instance? Should I enable something on my `.env` file?
