### ISSUE TITLE
I don't have the same layout as the others users

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#2304]
Hello,

As mentioned in the tickets https://github.com/pixelfed/pixelfed/issues/2302 and https://github.com/pixelfed/pixelfed/issues/2303, i have some layout problem, but for an unexplained reason, the layout i have is not the same as other user have. When i click on "go to post" on my own posts, i have this:
![Screenshot_20200628_142145](https://user-images.githubusercontent.com/22192600/85947405-f8ffa780-b939-11ea-8475-298280dd9c94.png)
But other users have that
![Screenshot_20200628_142950](https://user-images.githubusercontent.com/22192600/85947598-44668580-b93b-11ea-9b57-6dc6a8b1dc19.png)
and we are both on the main instance. Why is the interface different only for me ?

**Comment by dansup** [comment]
@stemy2 You have your profile set to MomentUI.

You have a few options
- Append ```?ui=metro``` to profiles/posts to view the default layout
- Go to Settings -> Labs and uncheck ```Use MomentUI for posts and your profile```
- Go to Settings -> Labs and check ```Force Metro Layout```
