### ISSUE TITLE
Instagram Import job failing

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#2306]
As discussed a few weeks back in the fediverse, when I try to complete an instagram import, I receive a message at the top of the page stating "Import successful! It may take a few minutes to finish.".. however, it is also accompanied by a failed job in horizon.

The rename job is failing as the destination folder does not exist.

`ErrorException: rename(/usr/share/nginx/html/pixelfed/storage/app/import/b6f8f78b-3b12-4930-9a8e-dad3a3100ad6/lIeB8z6LekhTyOsYWPbZXPTVuFSIumXwmuu8HefW.jpeg,/usr/share/nginx/html/pixelfed/storage/app/public/m/0435cc59bc9edaf1bf37a87430b321de710d4cdf/cd5b7e7613a515b0edd5b281f9fecbda52c1314f/a86ee6d571dc1c90db81b6f526d08727.jpg): No such file or directory in /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:240`

Full stack trace: https://pastebin.com/d7TQtDM0

Pixelfed: 0.10.9
Postgres: 12.3 (also happened on 11)
PHP: 7.3.11-1
Laravel: 7.16.1

**Comment by dansup** [comment]
@jk-na Are you sure the storage/ dir has the correct permissions?

**Comment by jk-na** [comment]
Well it has sufficient permissions to upload new photos.. so I gather so..

Just posted [this](https://px.nipponalba.scot/p/jk/184210470612373504) as a test.

The storage/app directory doesn't appear to have been created during the import process..

**Comment by jk-na** [comment]
The creation of the app and app/import directories seems to be where the issue was.  I deleted the relevant row from the import_jobs table, manually created the directories using the account that pixelfed runs under and then re-ran the import job and it was successful this time.

**Comment by downeymj** [comment]
Has anyone else run into this problem since then? I'm getting the exactly same failure mode. I've tried different filesystem users under `storage` (the import directory is in fact being created), clearing out the rows in `import_datas` and `import_jobs` in MariaDB, and making sure PHP & nginx settings are big enough to do the import, but still getting the failed Horizon job as described above.

**Comment by baarkerlounger** [comment]
How are you importing?

**Comment by baarkerlounger** [comment]
@downeymj  Getting the same error as well. Did you find a solution?

In my case it seems the function to move the uploaded file:

```
# pixelfed/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:240
    /**
     * Move a file to a new location.
     *
     * @param  string  $path
     * @param  string  $target
     * @return bool
     */
    public function move($path, $target)
    {
        return rename($path, $target);
    }
```

 is failing, as the dir it's trying to move the file to doesn't exist:

```
pixelfed/storage/app/public/m/...
```

**Comment by jk-na** [comment]
That was the same situation for me, I had to create the *destination* subdirectories manually then run again - all of the photos were imported into the same sub-directories in my case, but I gather that there would be a different subdirectory for each user so possibly not a plausible way forward if yours is not a single-user instance.

**Comment by downeymj** [comment]
@baarkerlounger No I didn't yet find a solution, but I also didn't do any additional troubleshooting beyond when I posted my previous comment.
