### ISSUE TITLE
Follow users from other instances

### ISSUE THREAD

**Issue by TheEvilSkeleton** [pixelfed/pixelfed#2307]
Like the title says, is there a way to follow users that use another instance?

**Comment by TheEvilSkeleton** [comment]
https://mastodon.social/@pixelfed/102641371305241243 i don't see how i can do that though

**Comment by trwnh** [comment]
you should be able to search for them, then click the follow button in their remote profile
![image](https://user-images.githubusercontent.com/10606431/86420216-765d4c00-bc9b-11ea-93f6-9aabf23a327b.png)

**Comment by TheEvilSkeleton** [comment]
Thank you so much
