### ISSUE TITLE
ios ‘add to home screen’ icon has transparent/black background (should be square with white BG)

### ISSUE THREAD

**Issue by OddHouseGames** [pixelfed/pixelfed#2311]
![image](https://user-images.githubusercontent.com/62911518/86748294-59fa4000-c00a-11ea-924f-c40f77d3ff5e.jpeg)

**Comment by trwnh** [comment]
actually it should be a square tile; iOS doesn't allow transparency by default and this is why the transparency is being converted to black

**Comment by OddHouseGames** [comment]
Good point *updated the title

**Comment by jimboolio** [comment]
Hello!
I'm installing my first Pixelfed instance and on iOS this black and transparent glitching looks so unpolished, that I created an iOS icon option from the official one. I hope you like it even though it isn't perfect: 
![ios-ss](https://user-images.githubusercontent.com/26402578/107163862-a056b980-69b4-11eb-94b0-9fff2c3a39fd.PNG)

I added 1024px square png and svg source. There's also a version with the "official" logo with white background and a bit of space around it if my doesn't fit the visual style
[pixelfed-ios.zip](https://github.com/pixelfed/pixelfed/files/5940538/pixelfed-ios.zip)

**Comment by OddHouseGames** [comment]
Any progress on this? As suggested by the user above, could be solved by providing iOS specific icon option.

It still displays like this currently:![image](https://user-images.githubusercontent.com/62911518/141965844-4aedf9a0-fa11-48e6-9b18-b0e04ea9f1db.jpeg)

**Comment by trwnh** [comment]
ping @dansup -- if you can get to this before me then that would be cool, if not i'll get to it in some weeks. here are some generated icons that meet platform guidelines:

- [ic_launcher-61939e7391fa5.zip](https://github.com/pixelfed/pixelfed/files/7546144/ic_launcher-61939e7391fa5.zip)
- [AppIcons.zip](https://github.com/pixelfed/pixelfed/files/7546257/AppIcons.zip)

to make it show up properly for safari pwas we need to use the 180px version in the manifest. for chrome, we need 192px and 512px

here's the bare minimum we need: [pixelfed-pwa-icons.zip](https://github.com/pixelfed/pixelfed/files/7546264/pixelfed-pwa-icons.zip)

notes for self if i get around to it first: edit public/manifest.json, copy icons probably to public/img/logo/<size>.png

**Comment by MrAn0nym** [comment]
@trwnh Can be closed ^^
