### ISSUE TITLE
Bookmarks API broken JSON output

### ISSUE THREAD

**Issue by swentel** [pixelfed/pixelfed#2317]
Doing a call on api/v1/bookmarks returns invalid JSON which can't be parsed.
Compare with api/v1/favourites for instance which is totally fine.

Experienced on pixelfed.social

Screenshot from a response from a rest client - first one is fine (favourites), second one is broken (bookmarks).

![favourites-response](https://user-images.githubusercontent.com/168466/87124137-760b1500-c288-11ea-825d-6ae968935d5a.png)

![bookmarks-response](https://user-images.githubusercontent.com/168466/87124142-799e9c00-c288-11ea-8a49-5a4999b36bd9.png)

**Comment by dansup** [comment]
Fixed in #2324

**Comment by swentel** [comment]
Sorry, but the fix isn't actually working.

The problem is that StatusService::get is returning a json string. And the response of the api is also json, so it's still double encoded.

Not sure what the actual best way forward is. I would opt not to store the json in the StatusService in the cache, that way, calling get on that class returns the object and the implementer can still decide what to do.

**Comment by swentel** [comment]
Ok, playing around with the coldGet and using toArray fixes the return for the bookmarks api controller, however, redis doesn't like to store an array, so that call than crashes.

Calling json_decode in the controller seems really redunant, but maybe that really is the only option, see pull request at https://github.com/pixelfed/pixelfed/pull/2377

**Comment by dansup** [comment]
Fixed!
