### ISSUE TITLE
Page expired

### ISSUE THREAD

**Issue by dadall** [pixelfed/pixelfed#232]
I'm trying to set up my own test instance. It seems to work but I can't register. I have no error in the app logs or Nginx.
I can't keep seeing this page : 

![pixelfed_pageexpired](https://user-images.githubusercontent.com/2796341/41110910-d64565be-6a7a-11e8-8a15-72de72d508a1.png)

All the cookies are there, in storage/framework/sessions.

- Debian 9
- PHP 7.2
- Redis server 3.2
- PHP Redis 4

**Comment by trwnh** [comment]
Related to #140 maybe?

**Comment by dadall** [comment]
I tried with a clean browser. Same issue.

**Comment by dadall** [comment]
Composer version 1.6.5 2018-05-04 11:44:59

PHP packages : 

- php-cli-prompt
- php-common
- php-composer-ca-bundle
- php-composer-semver
- php-composer-spdx-licenses
- php-igbinary
- php-json-schema
- php-memcached
- php-msgpack
- php-psr-log
- php-redis
- php-ssh2
- php-symfony-console
- php-symfony-filesystem
- php-symfony-finder
- php-symfony-polyfill-mbstring
- php-symfony-process
- php-zip
- php7.2
- php7.2-cli
- php7.2-common
- php7.2-gd
- php7.2-json
- php7.2-mbstring
- php7.2-mysql
- php7.2-opcache
- php7.2-readline
- php7.2-xml
- php7.2-zip

**Comment by MrPetovan** [comment]
Did you setup HTTPS? I got this issue trying to login from the HTTP version when I had set up the HTTPS version.

**Comment by dadall** [comment]
Nop, no HTTPS yet !

**Comment by dadall** [comment]
@dansup It Woks ! 

Thanks a lot for you work !

**Comment by Dragnucs** [comment]
@dadall Could you please tell us how you fixed this issue?

**Comment by dadall** [comment]
@Dragnucs I configured the HTTPS for Pixelfed, that's all !

**Comment by Dragnucs** [comment]
That would be difficult, I just want to test it locally.

On June 23, 2018 9:44:39 AM GMT+01:00, dada <notifications@github.com> wrote:
>@Dragnucs I configured the HTTPS for Pixelfed, that's all ! 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dansup/pixelfed/issues/232#issuecomment-399653674

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by noplanman** [comment]
Hmm, have added HTTPS to Apache inside the docker container, but I still get the expired page thing :confused: 

Will give it a go on a production instance, for tests of course... (which is what production *actually* means, right? Am I right?!)
