### ISSUE TITLE
Send automatically to first unread post

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#2320]
Hello,

I think it would be more practical if we were sent automatically to the first unread post instead of the top of the page.

**Comment by trwnh** [comment]
maybe as an optional feature

**Comment by dansup** [comment]
@stemy2 This is not possible because we do not track what posts users have viewed, and doing so would be a privacy violation IMO (even if used for only good purposes, it can still be abused by any instance admin)
