### ISSUE TITLE
SQLite installer crashes

### ISSUE THREAD

**Issue by pawelorzech** [pixelfed/pixelfed#2325]
I'm trying to install pixelfed with sqlite as database, but it does not work. This is what happens when I try to run artisan migrate

[pnut@s16.zenbox.pl:~/domains/yeswas.edu.pl/public_html] $php74 artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migrating: 2018_12_22_055940_add_account_status_to_profiles_table

   BadMethodCallException 

  SQLite doesn't support multiple calls to dropColumn / renameColumn in a single modification.

  at vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php:149
    145|     protected function ensureCommandsAreValid(Connection $connection)
    146|     {
    147|         if ($connection instanceof SQLiteConnection) {
    148|             if ($this->commandsNamed(['dropColumn', 'renameColumn'])->count() > 1) {
  > 149|                 throw new BadMethodCallException(
    150|                     "SQLite doesn't support multiple calls to dropColumn / renameColumn in a single modification."
    151|                 );
    152|             }
    153| 

      +5 vendor frames 
  6   database/migrations/2018_12_22_055940_add_account_status_to_profiles_table.php:23
      Illuminate\Support\Facades\Facade::__callStatic("table")

      +22 vendor frames 
  29  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by pawelorzech** [comment]
I know how bad does it look up there, so here's screenshot from terminal. Looks cleaner and better to read.
![Screenshot 2020-07-13 at 14 58 52](https://user-images.githubusercontent.com/765720/87307138-5f2f2180-c519-11ea-80d6-5425dac3c74b.png)

**Comment by dansup** [comment]
SQLite is not supported

**Comment by rnwgnr** [comment]
@dansup You should then remove `.env.testing` as this uses SQLite...so one might think it is suitable for testing environments.
