### ISSUE TITLE
pixelfed/vendor/autoload.php): failed to open stream

### ISSUE THREAD

**Issue by jncipsp** [pixelfed/pixelfed#2327]
Been trying to install Pixelfed on an Ubuntu VPS and get the below error which i can't seem to solve

PHP Warning:  require(/var/www/vhosts/xxxxx.com/pixelfed/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/xxxxx.com/pixelfed/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/var/www/vhosts/xxxxx.com/pixelfed/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/vhosts/xxxxx.com/pixelfed/artisan on line 18

**Comment by dansup** [comment]
Run ```composer install```
