### ISSUE TITLE
[Moment UI] Users cannot reply to comments on their own post

### ISSUE THREAD

**Issue by mpanhans** [pixelfed/pixelfed#2329]
Multiple users on my instance have reported that on their own posts, they see someone comment on the post, but then they themselves are not able to reply to or react to the comment, nor are they able to make additional comments on the post.

I have an admin account and have not had this issue with my own account.

I have an instance running the last pre-release v0.10.9 (not the dev branch). Perhaps this is fixed in the current dev branch, but I was unable to find either an open or closed issue relevant to this problem.

**Comment by mpanhans** [comment]
Okay it appears this issue occurs only if in Settings > Labs, MomentsUI is selected. Perhaps this is a known issue for 
MomentsUI.

**Comment by dansup** [comment]
MomentUI has been deprecated
