### ISSUE TITLE
Add iOS Home Screen support

### ISSUE THREAD

**Issue by MrPetovan** [pixelfed/pixelfed#233]
Until there is a dedicated iOS app, which is unlikely to happen any time soon, I’m planning on using Pixelfed as a Home Screen App.

The are a couple of technical requirements to enable this:
- Declaring the web app support in the meta tags
- Add a script capturing internal links in Javascript to prevent them from opening in the Safari app.

I’ll add more details when I’m on a desktop.

**Comment by MrPetovan** [comment]
Meta-tag: `<meta name="apple-mobile-web-app-capable" content="yes" />`

Link capture script: https://gist.github.com/irae/1042167

**Comment by cedeber** [comment]
Support for all browsers: https://github.com/cedeber/cedeber.github.io/blob/master/index.html
Sketch file to generate the icons: https://github.com/cedeber/cedeber.github.io/tree/master/resources

**Comment by MrPetovan** [comment]
Thanks, but both links are broken at the moment.

**Comment by cedeber** [comment]
Ah, sorry, it was private... it' just my personal website so I make it open ;-)

**Comment by Alamantus** [comment]
Here's a handy tutorial/walkthrough for setting this up for iOS:  
https://medium.com/appscope/designing-native-like-progressive-web-apps-for-ios-1b3cdda1d0e8

**Comment by alicerunsonfedora** [comment]
Have there been any updates to this? I've tried doing so with my iPhone, but the cookies don't seem to sync up with when I sign in in Safari itself. When I hit 'Login', it just boots me back to Safari instead of the web app. I'm using iOS 12.1 on an iPhone 7.

**Comment by trwnh** [comment]
Seems you can now add any web page to home screen on iOS? At least, I was just able to add Pixelfed as a regular page (though not as a webapp). So this is half-possible, it just needs the niceties like the manifest declaration so it shows up as a webapp with the icon and everything (instead of a page preview).

**Comment by alicerunsonfedora** [comment]
That and some redirection magic. I know that I had to find clever ways to prevent the 'Login' booting issue I currently have with Pixelfed in Hyperspace by storing some data locally so there would be a 'pick up where you left off' kind of thing.

**Comment by trwnh** [comment]
OK, I'm taking a look at this right now and it looks like we currently have the following:

- [x] Manifest declaration: `<meta name="apple-mobile-web-app-capable" content="yes">`
- [x] Touch icon: `<link rel="apple-touch-icon" href="">`
- [ ] Splash screen: `<link rel="apple-touch-startup-image" href="">`
- [-] Status bar: I think we can keep it default
- [-] Shortname: The title is already short enough
- [-] Disabling text selection/highlight/callout: unnecessary
- [-] Tap effects: unnecessary

I think I'll write a PR to add the icon at least. The splash screen looks kind of unnecessary and hard to maintain, so unless anyone thinks the other stuff is necessary, I'll tag that PR as fixing this issue.
