### ISSUE TITLE
Likes count doesn't update following unlike

### ISSUE THREAD

**Issue by BNolet** [pixelfed/pixelfed#2331]
Likes coming from Mastodon (as far as I can tell) don't get uncounted in the likes counter. 

Example: https://fedigram.com/p/brandon/189785975113781248

One like, but if you click on it, it will show no users.

**Comment by okpierre** [comment]
@BNolet I noticed the same and **likes** no longer sync. I think recent update broke this @dansup

**Comment by dansup** [comment]
Fixed!
