### ISSUE TITLE
2FA login issue

### ISSUE THREAD

**Issue by DuDe-75** [pixelfed/pixelfed#2332]
Hi,

after a longer absence I was trying to log in to the site. After providing míy password I was asked for the 2FA code, but that was not accepted. I tried several times, on different browsers with no success. I use Google Authenticator for 2FA and I've had no issues with it until now.

Any info yould be helpful.

Thanks,

DuDe

**Comment by dansup** [comment]
Please contact your instance admin.

**Comment by bolbishvili** [comment]
having a similar issue. I have password, but don't have the phone with 2fa app I has used. Emailed instance admin (dansup) 6 years ago and again last week, but there's no reply.   I really just want to get logged in, so i can delete the old account.
