### ISSUE TITLE
Wrong grid order after importing from Instagram

### ISSUE THREAD

**Issue by verymilan** [pixelfed/pixelfed#2333]
After importing from Instagram, the imported posts appear to have the correct (original) datetag, but the grid at `/username` sorts them as they were new, so current Pixelfed posts get thrown to the bottom.

The home-timeline looks fine.

**Comment by dansup** [comment]
@verymilan This is intentional, its not possible to backdate posts as they are ordered by snowflake id and our epoch is Feb 2019 while IG posts can be dated as early as 2010.

**Comment by nickinzon** [comment]
@dansup Could it please be reconsidered, how the pictures are being sorted on the profile page?
I had been maintaining a profile on each Instagram and pixelfed. Now I am about to transition entirely to pixelfed and just imported all pictures from Instagram. All imports are placed at the bottom of the profile page, while according to the post date they should be mixed into the already existing pixelfed posts. The inconsistent sorting on my profile really bothers me.
