### ISSUE TITLE
invalid input syntax for integer

### ISSUE THREAD

**Issue by verymilan** [pixelfed/pixelfed#2335]
As mentioned in #775, there appears to be a problem with at least postgresql:

My log gets flooded by exceptions caused by `Invalid text representation: 7 ERROR:  invalid input syntax for integer: "theusername" (SQL: select * from "users" where ("username" = theusername or "id" = theusername) and "users"."deleted_at" is null`.

This also blocks cli operations like making a user admin.
Users in notifications do not have avatars, not sure if this could be related... .

**Comment by lapineige** [comment]
This apparently prevents Pixeldroid from connecting to Pixelfed : https://github.com/YunoHost-Apps/pixelfed_ynh/issues/167#issuecomment-1079769477

**Comment by dansup** [comment]
Fixed!
