### ISSUE TITLE
[UI] Misleading interface on post comment likes

### ISSUE THREAD

**Issue by diogogithub** [pixelfed/pixelfed#234]
The positioning of comment's likes suggests that it is referring to the post.
Example given:
-> https://pixelfed.social/p/dansup/2073
-> https://pixelfed.social/p/damien/2073/c/2124

**Comment by trwnh** [comment]
Gotta admit I thought the same

**Comment by hellcp** [comment]
![screenshot from 2018-06-08 03-13-31](https://user-images.githubusercontent.com/30577011/41133916-f3516dfc-6ac9-11e8-806e-863330731975.png)

Just a trial of how that could look like ;)

**Comment by dansup** [comment]
Fixed in latest commits!
