### ISSUE TITLE
Don't compress again jpeg images when it's not necessary

### ISSUE THREAD

**Issue by pezcurrel** [pixelfed/pixelfed#2342]
I have an account on pixelfed.social, I mainly post jpegs without applying any "pixelfed modification" (crop, filters...).
Pixelfed.social scales down to 1080px vertical resolution those images which have it greater, and even if one posts a jpeg with vertical resolution <= 1080px and without applying any "pixelfed modification", pixelfed.social saves it again with a quality of 75%, which is way too low in many cases.
I think users should be allowed to manage the space they have like they want to, so I think any jpeg file should be published as-is (not even scaled), when there's no need to save it again (ie no "pixelfed modification").
If a resolution limit is necessary, I think at least those jpegs which have a resolution <= that limit shouldn't be recompressed.
I also think that when it is unavoidable to re-save jpeg image data (ie when "pixelfed modifications" are applied), it should be saved with a quality > 75% (like 92% or so).

**Comment by kr-cr** [comment]
Hi, 

is there any update on this side? I am trying to figure out how the compression on pixelfed works in attempt to have the less degradation. Should I favour png or jpg, at which resolution, and is it possible to avoid any re-compression by saving under a specific file weight?

Thank you.

**Comment by eobet** [comment]
Mastodon recently [increased its media limits](https://github.com/mastodon/mastodon/pull/23726), but Pixelfed hasn't followed through?

**Comment by dansup** [comment]
Fixed!
