### ISSUE TITLE
Request: PWA support

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#2344]
Loving Pixelfed so far. I would like to request PWA support (Alternatively if you're open to a PR on it I can add it), but I do know you are working on an official app. I think it would be beneficial for those who want to use this like an app but don't want to download something from the app store. The interface is already quite mobile friendly, and adding PWA support makes it a little bit easier to use as you can just add it to your homepage on android (unsure about iOS).

Thoughts?

**Comment by trwnh** [comment]
should already be supported

**Comment by forenta** [comment]
Well,... not yet?
As far as I visit instances (pixelfed.social, pixelfed.de), my browser (Microsoft Edge 90, stable) doesn't recognize a PWA, neither the PWA-stores I use (Appscope, pwastore.com) have listed Pixelfed yet.
