### ISSUE TITLE
The menu option "Copy Link" doesn't work in the "..." menu of a post

### ISSUE THREAD

**Issue by narFnarF** [pixelfed/pixelfed#2350]
The menu option "Copy Link" doesn't work in the "..." menu of a post.

Device: iPhone 5s
iOS version 12.4.6
Browser: "Pin to Home" Safari browser

## Steps to reproduce:

1. Go to the main timeline
2. On any post, tap the "..." button (top right corner of a post)
3. In the menu that appears, tap the "Copy Link" option.

## Current result:
Nothing happens.

## Expected result:
The appropriate link is copied to the clipboard and Pixelfed display's a confirmation text (ex: "Copied!")

![](https://i.imgur.com/tHLK0Jm.png)

**Comment by dansup** [comment]
@narFnarF What browser are you using?

**Comment by narFnarF** [comment]
I use the "Pin to Home Screen" feature on iOS to access Pixelfed, so it launches in the Safari Browser, but without the Safari UI (aka: no buttons to change tabs, change the URL, etc)

I just tried in Firefox for iOS and it doesn't copy the URL either.

I tried in Firefox on my desktop computer (Windows 10) and it worked fine: the Menu closes the and URL was copied.

**Comment by dansup** [comment]
Fixed!
