### ISSUE TITLE
No confirmation screen when Unfollowing from the "..." menu

### ISSUE THREAD

**Issue by narFnarF** [pixelfed/pixelfed#2353]
On iOS, it's easy to accidentally unfollow someone because there is no confirmation screen.

Device: iPhone 5s
iOS version 12.4.6
Browser: Safari (pinned to Home screen)

## Steps to reproduce:

1. Go to the main timeline
2. On any post, tap the "..." button of that post
3. Tap the "Unfollow" option

## Current result:
The user is immediately unfollowed.

## Expected result:
Pixelfed ask the user "Are you sure you want unfollow _username_?" "Unfollow/Cancel"

![](https://i.imgur.com/kh1TZPg.png)

**Comment by dansup** [comment]
Fixed!
