### ISSUE TITLE
Error php artisan install via ssh

### ISSUE THREAD

**Issue by EddieCicero** [pixelfed/pixelfed#2360]
Error php artisan install via ssh
![erro_php_artisan](https://user-images.githubusercontent.com/33223554/88943885-703e9900-d262-11ea-8c3a-c291b27c062b.png)

**Comment by dx7** [comment]
@EddieCicero that is a Redis connection error. do you have Redis running?

**Comment by EddieCicero** [comment]
Yes, that is Redis is running. I disable the firewall but don't is function

**Comment by dx7** [comment]
redis server is refusing connections. can you connect using `redis-cli`?

**Comment by EddieCicero** [comment]
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor pre
   Active: active (running) since Fri 2020-07-31 12:17:19 -03; 21min ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 10120 ExecStop=/bin/kill -s TERM $MAINPID (**code=exited, status=1/FAIL**
  Process: 10123 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exi
 Main PID: 10124 (redis-server)
    Tasks: 4 (limit: 4546)
   CGroup: /system.slice/redis-server.service
           └─10124 /usr/bin/redis-server 127.0.0.1:6379

jul 31 12:17:19 baggios-G31M-ES2C systemd[1]: redis-server.service: Scheduled re
jul 31 12:17:19 baggios-G31M-ES2C systemd[1]: Stopped Advanced key-value store.
jul 31 12:17:19 baggios-G31M-ES2C systemd[1]: Starting Advanced key-value store.
jul 31 12:17:19 baggios-G31M-ES2C systemd[1]: redis-server.service: Can't open P
jul 31 12:17:19 baggios-G31M-ES2C systemd[1]: Started Advanced key-value store.
lines 1-17/17 (END)

**Comment by EddieCicero** [comment]
baggios@baggios-G31M-ES2C:~$ redis-cli
127.0.0.1:6379> ping
PONG
127.0.0.1:6379>

**Comment by dansup** [comment]
@EddieCicero Do you have the ```php-redis``` php extension installed? You need to set ```REDIS_CLIENT=phpredis``` in .env and then run ```php artisan config:cache``` and restart the webserver.
