### ISSUE TITLE
MicroUI and other experimental frontends?

### ISSUE THREAD

**Issue by lullis** [pixelfed/pixelfed#2369]
Sorry for making a question in certainly the wrong place, but I haven't found any other place for project-related discussion.

I've been following PixelFed's development for some time and one of the things that caught my interest was the different "experimental" front-ends. What happened to those? I found a post explaining that these were only on "labs", but I didn't find any repo for them. Are they closed source? Abandoned?

**Comment by trwnh** [comment]
unreleased/uncommitted until the backing features are ready. currently Moment and Metro are the only included UIs. one other thing that should probably be figured out first is if we want to have even more frontends or 3rd-party frontends, etc.
