### ISSUE TITLE
Mobile navigation buttons covered by Home Bar in PWA on iPhone

### ISSUE THREAD

**Issue by Spaceface16518** [pixelfed/pixelfed#2370]
Although the icons are visible, the Home Bar on newer iPhones is activated when the user taps near it (so as to "activate" it). This interferes with PixelFed's navigation menu, making it visually and physically difficult to use it (if only slightly). The phone's curved corners also make this menu look slightly "off"; the user would expect the space on the top and bottom of the icons to be symmetrical, but this is not the case because the Home Bar and curved corners take up some of the space on the bottom of the icons.

This could be easily fixed by adding a little margin/padding to the bottom of the UI elements, but the real problem is making sure this only happens when it needs to (i.e. only on new iPhone models, or other phones with intrusive UI elements). Or just making the nav bar a little bigger would work too.

Relevant code:

https://github.com/pixelfed/pixelfed/blob/390592f755650eecc5b4f283ea21cce3ac463199/resources/views/layouts/app.blade.php#L58-L78

Example screenshot on **iPhone XR; IOS 13.5.1**  using the PWA.

![IMG_5908576C36FA-1](https://user-images.githubusercontent.com/33424649/89434085-be431900-d708-11ea-883a-f3b8e4605f56.jpeg)

**Comment by dansup** [comment]
Fixed!
