### ISSUE TITLE
Privacy Policy page not updating

### ISSUE THREAD

**Issue by russelljohn** [pixelfed/pixelfed#2371]
I've edited the privacy policy page from /admin/settings/pages, but the default one shows up instead of it. Cleared cache, but that didn't help.

Edited About and Terms page the same way and they worked fine. Any clue what might be happening with privacy policy page?

**Comment by sir-octopus** [comment]
After implementing my workaround in #3616 to get the page editor to load, I am also experiencing this issue too, except it is affecting all pages not just privacy.

**Comment by dansup** [comment]
Fixed!
