### ISSUE TITLE
hashtag search doesn't work if hastag contains ZWNJ

### ISSUE THREAD

**Issue by ahangarha** [pixelfed/pixelfed#2378]
If there be ZWNJ (Zero Width None-Join) character in the hashtag, hashtag page doesn't show anything. for example you can check page for [دارک‌تیبل](https://pixelfed.social/discover/tags/%D8%AF%D8%A7%D8%B1%DA%A9%E2%80%8C%D8%AA%DB%8C%D8%A8%D9%84?src=hash) hashtag which remains in loading status.

This character is commonly used in at least Persian language if no other languages.

**Comment by dansup** [comment]
@ahangarha  This is fixed in the latest commits!
