### ISSUE TITLE
Password fields present in a form with an insecure (http://) form action

### ISSUE THREAD

**Issue by dadall** [pixelfed/pixelfed#238]
Hi,

I'm trying to fix this issue that prevent users to login in a secure way. The issue title is a copy/past of my Firefox warning.
The actual configuration seems to be ok, no errors in logs.

APP_URL is set to https://pix.servername.tld

I did these actions : 
 
- php artisan cache:clear
- php artisan config:cache

At first, I was using a non HTTPS APP_URL.

Any idea ?

**Edit** : I use Nginx as a reverse proxy.

**Comment by ArthurHoaro** [comment]
Sorry to comment on a closed issue, but I have the exact same problem. The `APP_URL` is set with `https://`, and `APP_ENV` is set to `production`. 

Were you able to fix the issue?

**Comment by koehn** [comment]
I ended up putting a `\URL::forceScheme('https');` at the top of `routes/web.php` and the issue resolved. Crude, but effective.

**Comment by ogmkp** [comment]
Hi.

I've installed a copy of pixelfed today and this issue stills present.
Do you have information about this ?

Thanks.

**Comment by ogmkp** [comment]
> I ended up putting a `\URL::forceScheme('https');` at the top of `routes/web.php` and the issue resolved. Crude, but effective.

It's doing the job, thank you.

**Comment by benoitjpnet** [comment]
Could this trick be added on the production code?
I'm behind an HAProxy (which do the TLS offload) and I need `\URL::forceScheme('https');`.
