### ISSUE TITLE
Infinite redirect loop when verifying updated email address with 2FA enabled

### ISSUE THREAD

**Issue by vszakats** [pixelfed/pixelfed#2385]
This report is against the running instance over <https://pixelfed.social/> at the time I'm opening this Issue.

I've updated my email address on a Pixelfed account and when clicked on the verification link received to the new email address, the website went into an infinite redirect loop. A logged-in instance in another tab wasn't allowed to change any setting (such as disabling 2FA) saying the email isn't verified yet. After clearing cookies and logging back again, an infinite loop happened again. Closing the tab and reopening <https://pixelfed.social/> went to a similar infinite loop, stopping at one of these URLs: <https://pixelfed.social/i/auth/checkpoint>, <https://pixelfed.social/i/verify-email>. Also tried to password reset: It works for the new (not-yet-verified) address, allowing to change the password using the emailed link, then goes into the same infinite redirect loop. It means that I lost access to said account.

The issue likely has to do something with 2FA being enabled, as I've done the same email update on a different account on the same server, and that one worked fine. That account didn't have 2FA enabled though.

**Comment by dansup** [comment]
@vszakats This has been fixed!

**Comment by vszakats** [comment]
@dansup: I can confirm that your update fixed the issue. Thanks a lot!
