### ISSUE TITLE
Unique violation of profiles_domain_username_unique in InboxValidator during remote follow

### ISSUE THREAD

**Issue by scientress** [pixelfed/pixelfed#2393]
I've set up a new instance and enabled activity pub. 

When I tried to follow or unfollow an account on that instance from a remote mastodon instance the InboxValidator job fails. The follow also doesn't work and the follower count is not incremented or decremented.

Exception Details:
```
PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "profiles_domain_username_unique"
DETAIL: Key (domain, username)=(chaos.social, @hackyscientress@chaos.social) already exists. in /var/www/rubber.zone/pics/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127
```
I can see in the admin dashboard that a profile has been created for the mastodon account I'm trying to follow from, but apparently inbound activitypub event's can't be correctly mapped to to it.

I'm using Posgresql for the database.
Version: git/dev head (0c5c7fd6e019b2ad482ea614ccea652b6b27e034)
In hindsight it might have been a better idea to use the latest tag, but I didn't think about that during installation. Might be a good think to add to the installation documentation if that's recommend. currently it tells you to checkout the current head of the default branch.

**Comment by lapineige** [comment]
Same issue here, is it something important or could we kind of ignore it until it's fixed ?

**Comment by dansup** [comment]
Fixed in #2665

**Comment by jk-na** [comment]
I'm on the latest commits and have had 26 instances of this error (spread over both InboxValidator and InboxWorker) out of 68 failed jobs (~38% of failures).. I'm not sure therefore that this is resolved and the issue should be re-opened.

**Comment by inga-lovinde** [comment]
Might be also related to #2520 .

I have the same issue for remote accounts containing uppercase letters; and it is not just follow/unfollow - any interactions produces such an error in horizon.
