### ISSUE TITLE
FPM dockerfile non-necessary ?!

### ISSUE THREAD

**Issue by carstencodes** [pixelfed/pixelfed#2395]
Good morning,

in PullRequest #2137 @Strubbl has reduced the layers of the apache docker image. Before that, the images fpm and apache just differed from the words `fpm` and `apache`.

I'm proposing to create a single dockerfile with a build argument for that:

In [line 1](https://github.com/pixelfed/pixelfed/blob/248dd78ddfb4f7a4af299985c5edc1b9e9b1d70b/contrib/docker/Dockerfile.apache#L1) we would write:

```
ARG ENGINE=apache
FROM php:7.4-$ENGINE-buster
```

This would include the necessity to extend [line 92](https://github.com/pixelfed/pixelfed/blob/248dd78ddfb4f7a4af299985c5edc1b9e9b1d70b/contrib/docker/Dockerfile.apache#L92) with an additional run command:

```
COPY . /var/www/
# for detail why storage is copied this way, pls refer to https://github.com/pixelfed/pixelfed/pull/2137#discussion_r434468862
RUN ln -s /var/www/contrib/docker/start.$ENGINE.sh /var/www/contrib/docker/start.sh \
     && cp -r storage storage.skel \
```  

This way the command in [line 102](https://github.com/pixelfed/pixelfed/blob/248dd78ddfb4f7a4af299985c5edc1b9e9b1d70b/contrib/docker/Dockerfile.apache#L102) would be the following:

```
CMD ["/var/www/contrib/docker/start.sh"]
```

This way, both engines would be supported using a single file.

This way we can extend [line 20](https://github.com/pixelfed/pixelfed/blob/248dd78ddfb4f7a4af299985c5edc1b9e9b1d70b/docker-compose.yml#L20) of the compose file to

```
      dockerfile: contrib/docker/Dockerfile
      args:
          - ENGINE=apache # set to fpm if you need fpm
``` 

This would help creating official docker images with both backends,

@dansup @shleeable @dm What do you think?

**Comment by dansup** [comment]
Superseded by #4844
