### ISSUE TITLE
Webfinger endpoint does not respect best practice regarding CORS

### ISSUE THREAD

**Issue by TiMESPLiNTER** [pixelfed/pixelfed#2397]
According to the webfinger RFC the `Access-Control-Allow-Origin` should be set to the least secure option:

```
Access-Control-Allow-Origin: *
```

See: https://tools.ietf.org/html/rfc7033#section-5

Currently there's no `Access-Control-Allow-Origin` header set which prevents any CORS requests.

**Comment by MrAn0nym** [comment]
Could be wrong but I believe this is fixed by now

**Comment by NyaomiDEV** [comment]
it's not, not yet at least

**Comment by dansup** [comment]
Fixed!
