### ISSUE TITLE
Make "alt text" field limit configurable

### ISSUE THREAD

**Issue by hnrd** [pixelfed/pixelfed#2407]
Currently alt text is hard limited to 140 chars:

`'media.*.alt' => 'nullable|string|max:140',`

It would be great to be able to configure the length limit at instance level, like it already is with the caption text.

**Comment by der-On** [comment]
Yep. A 140 character limit for alt-texts is not very usefull, when you want to describe the image for blind people. Either make it configurable or simply set it to something like 512 or even 1024. The more the better.
ping @dansup

**Comment by lapineige** [comment]
I would say both are needed, the default value is way too low in most cases, and being able to extend it would be useful (a default value will probably always be too short in some cases if it's not as long as maybe 3000 characters - a book page can contain 2000 characters).
I see a particular use case: post a picture of some text (book, quote, …), that you could copy, then use it in the alternative text.

**Comment by dansup** [comment]
Fixed! This is now configurable by the admin.

**Comment by lapineige** [comment]
Great ! Thank you :)
