### ISSUE TITLE
use favicon.png for og:image by default

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#2409]
right now linking to root url and other non-photo pages will have no picture in media-embeds

![Screenshot_2020-09-18 pixelfed 🚀 ( pixelfed mastodon social)](https://user-images.githubusercontent.com/59403389/93590555-02376800-f9af-11ea-9044-dab938e9de20.png)
https://mastodon.social/@pixelfed/102205893884525639

![Screenshot_2020-09-18 Pixelfed ( PixelFed) Twitter](https://user-images.githubusercontent.com/59403389/93590557-03689500-f9af-11ea-8865-f75f5cf4c856.png)
https://twitter.com/PixelFed/status/1211591544148545537

![Screenshot_2020-09-18 link to pixelfed org on dym sh](https://user-images.githubusercontent.com/59403389/93590743-5cd0c400-f9af-11ea-82fe-a6087a0649fc.png)
https://dym.sh/notice/9zHSnGNdT1j8Sy83IO

**Comment by dansup** [comment]
Fixed!
