### ISSUE TITLE
[Bug] <title> of an user's follower/following lists are wrong

### ISSUE THREAD

**Issue by joachimesque** [pixelfed/pixelfed#241]
If I go look at my followers, https://pixelfed.social/joachim/followers , the <title> says "voss's followers" instead of "joachim's followers". 

voss is the oldest follow in my list. If I look at a multi-page list (e.g. https://pixelfed.social/chr/followers?page=2), it's the oldest in the displayed list, not the first follower ever.

This bug also happens on Following lists.

**Comment by hellcp** [comment]
Fixed with #239
