### ISSUE TITLE
Add post to collection during post creation

### ISSUE THREAD

**Issue by RomainTT** [pixelfed/pixelfed#2416]
If one uses collections to group his/her posts by theme for instance, process to add new posts to a collection should be simpler.

I suggest a new item in the new post panel:

![image](https://user-images.githubusercontent.com/12847715/94686823-aadcb480-032b-11eb-9d14-9008ed3b98e4.png)

User could select one of his/her collections in this item, or even several collections.

This is just a suggestion.

**Comment by dansup** [comment]
This has been supported for a while, closing this.
