### ISSUE TITLE
Embed shows wrong number of posts

### ISSUE THREAD

**Issue by johegl** [pixelfed/pixelfed#2417]
I have noticed that the embed does not show the correct number of posts, which is very strange for visitors. Maybe this can be looked at?

For example, https://pix.diaspodon.fr/dada/embed shows a number of "1K". But there are actually only 134 posts on https://pix.diaspodon.fr/dada at the time of submitting this issue.

I have had a look at that on pixelfed.de and pixelfed.social too and the numbers don't seem to match there either :-(

**Comment by dansup** [comment]
Fixed!
