### ISSUE TITLE
Registerring Apps still leads to 404 error

### ISSUE THREAD

**Issue by maxheadroom** [pixelfed/pixelfed#2419]
I'm running Pixelfed Version 0.10.9 which should have resolved https://github.com/pixelfed/pixelfed/issues/714 already. But I still get a 404 when I'm trying to register with a mobile app (like an Android client). The calls to:

 "POST /api/v1/apps HTTP/1.1" result in a 404 error. 

Anything I miss?

Thanks and best regards

Falko

**Comment by xundeenergie** [comment]
Is it possible, that experimental code worked a few weeks ago? 
I think i remember, that i added one testaccount with an android app successfully... don't know the instance and version of pixelfed...
(deleted the account later)

**Comment by xundeenergie** [comment]
OAUTH_ENABLED=true in .env file enables the authentication from app.

**Comment by dansup** [comment]
Fixed!
