### ISSUE TITLE
[UI] Follower/Following list : trailing space inside a link

### ISSUE THREAD

**Issue by joachimesque** [pixelfed/pixelfed#242]
The trailing space is visible on hover, as it gets underlined with the link.

<img width="580" alt="capture d ecran 2018-06-09 a 16 25 34" src="https://user-images.githubusercontent.com/1781070/41192700-17703bd0-6c02-11e8-923e-4d38c151d642.png">

```
<a class="following-username font-weight-bold text-dark" href="https://pixelfed.social/xxxx">
xxxx
</a>
<span class="following-name text-muted">
xxxx
</span>
```

should be :

```
<a class="following-username font-weight-bold text-dark" href="https://pixelfed.social/xxxx">xxxx</a>
<span class="following-name text-muted">xxxx</span>
```

**Comment by trwnh** [comment]
Fixed with the redesigned components
