### ISSUE TITLE
Text Within Post Breaks On Different Screen Sizes

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2423]
Here's what it looks like:

![pixelfedcomment-before](https://user-images.githubusercontent.com/1679025/96786780-bcf7c300-13be-11eb-8ffb-4bae31e8fd2e.png)

example:
show word **long** instead of just the letter **l**
show word **thisisvery** instead of just the letter **thi**

**Comment by tripu** [comment]
(cf #1108)
