### ISSUE TITLE
Uploads >1M failing

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#2429]
I have the same issue as https://github.com/pixelfed/pixelfed/issues/1522

I set `MAX_PHOTO_SIZE=102400` in .env and ran `php artisan config:cache` afterwards. In php.ini `upload_max_filesize = 1G` is set, which I confirmed by checking phpinfo() on the Pixelfed subdomain. But when I try to upload an image with 2MB I get "Oops, something went wrong!" on Pixelfed and this in my nginx error.log:
`[error] 1703#1703: *835204 client intended to send too large body: 2448150 bytes, client: x:x:x:x:x:x:x:x, server: x.x.x, request: "POST /api/pixelfed/v1/media HTTP/2.0", host: "x.x.x", referrer: "https://x.x.x/"`

Uploads with smaller files work just fine. I have a Nextcloud running on the same host, big uploads are no issue there.

**Comment by dansup** [comment]
You also need to update the ```client_max_body_size``` directive in the [nginx configuration](https://www.cyberciti.biz/faq/fix-client-intended-to-send-too-large-body-xyz-bytes-in-nginx/).
