### ISSUE TITLE
[Suggestion] Instance-wide setting to display/hide social counts (followers, following, likes…)

### ISSUE THREAD

**Issue by joachimesque** [pixelfed/pixelfed#243]
One of the things that is often criticized in social networks, is the omnipresence of likes and followers counts.

It might be interesting for some instances to choose to not register and not display likes (and not to display the like button), and to not display followers and followings. A user profile might show "0 followers" or "∞ followers" instead of the true count, even when displayed from another instance (like from Mastodon).

**Comment by yhancik** [comment]
To illustrate this metrics criticism, have a look at Ben Grosser's paper ["What do metrics want? How quantification prescribes social interaction on Facebook"](
http://computationalculture.net/what-do-metrics-want/) on the effect these numbers can have on ourselves and our social interactions

He put it in practice with his "demetricators" browser extensions that remove metrics from Facebook and Twitter
- https://bengrosser.com/projects/facebook-demetricator/
- https://bengrosser.com/projects/twitter-demetricator/

~

**See also:** 
- this short article by Basecamp's Jason Fried: https://m.signalvnoise.com/the-intimidating-zero-4d90fcdcc3b2
- Photo sharing app/site VSCO doesn't display any metrics, and that's a conscious choice too: https://twitter.com/vsco/status/534059586206957570

**Comment by dansup** [comment]
@joachimesque I like this idea, it would require some work to pull it off but I don't see a problem with this!

**Comment by Julianoe** [comment]
I come here to give a big **+1** to that idea @joachimesque!

Notifications driven use, "likes" powered algorithms are things used to hook users and tools to create an alienation and dependence in the relation between users and the social media. The engineers that created those tools backed their design with neuroscience and psychology to be as precise as they could in the manipulation. The end result and purpose was selling ads. We don't have ads on the Fediverse, we don't really need those tools to have the same place and priority. At least we should allow users and admins to question them.

Another hint we can use to feed this discussion is the interview of the former employee from Facebook Chamath Palihapitiya,
https://www.youtube.com/watch?v=PMotykw0SIk

Another example is that you won't perceive the quality of a photograph in the same way if you just look at it and if you check the number of likes beforehand. Our brains are trained to look at the number of likes before analyzing the real content.

It's like looking at the price tag of a bottle of wine before drinking it. It really does not taste the same.



edit : as i'm thinking about it furthermore i think that it should be both to the choice of the admin and the user. You could want as an admin to propose a different experience on your instance for all your users. But it would be really cool if as a user you could opt-out of those metrics for your own use of the app.

**Comment by stevelord** [comment]
This sounds like an excellent idea, although new users may struggle if it's a default.

Ultimately people expect likes to be a feature in social networks. I think it's worth having them, but giving people the option to disable them.

**Comment by joachimesque** [comment]
Despite the fact that the title of my issue is somewhat limiting, I believe it would be great for the setting to be available to single users, along with the instance admins.

I think it's a feature that could pull people to specific instances, by default, these instances wouldn't show numbers to logged-out users : everyone would be able to see the accounts without them, and these instances could advertise that fact to potential users.

Of course there should also be an opt-in for users on instances that have opted out, but in my opinion that would kind of defeat the purpose of that instance.

**Comment by stevelord** [comment]
I think having an instance-wide and individual user setting is a great move and will be something that sets this apart.

**Comment by dansup** [comment]
You can now disable following/follower counts on your profile.

**Comment by joachimesque** [comment]
Thanks! Will it be possible for admins to set it instance-wide by default?

**Comment by dansup** [comment]
@joachimesque In a future commit, yes!
