### ISSUE TITLE
[UI] Desktop : always contain vertical images inside the window

### ISSUE THREAD

**Issue by joachimesque** [pixelfed/pixelfed#244]
When images are too high (vertical images mostly), you have to scroll to see the whole image. I would prefer having the whole image contained in a box that's sized after the height of the screen.

```
.status-photo img {
    object-fit: contain;
    max-height: calc(100vh - (6rem));
}
```

The use of `object-fit` should be mature enough : https://caniuse.com/#search=object-fit (it's applied on an image, so Edge should render it correctly), and `vh` units have been ok for some time : https://caniuse.com/#search=vh

**Comment by hellcp** [comment]
I would suggest making those containers scrollable ;) It's nice to be able to see whole image and not have to go through trouble of right clicking and viewing image directly :D

**Comment by hellcp** [comment]
![peek 2018-06-09 21-36](https://user-images.githubusercontent.com/30577011/41195404-36e901ce-6c2d-11e8-96ab-0a1c6a4cdb3b.gif)

**Comment by joachimesque** [comment]
Mmh, I don't know if replacing a logical scroll (logical because we know that we should scroll the window) by an illogical scroll (illogical because we might not expect the box to not display the whole photo) will be better for the user.

Let's say we have a 2:3 portrait photo, that's too high for my browser window.

The current behaviour is: I have to scroll in order to see the whole photo, and I have no way to see the whole photo in one go. As a photographer, I prefer seeing the whole photo before checking the details. The option to see the whole photo doesn't exist.

My proposal would solve that problem by allowing the user to see the whole photo, constrained in a box that's guaranteed not to be too high for their window. The details would be available following a click. This way, the user can see the whole photo, and the details, even if the latter option is behind a click, it's an option that exists.
