### ISSUE TITLE
Directs not working with PostgreSQL

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#2440]
I've updated to the latest commits but the directs page is not loaded when I try to access it - just blank under the nav bar.

browser console returns a 500 error) for GET on https://instance-URL/api/direct/browse?a=inbox

Error in laravel.log:

`[previous exception] [object] (PDOException(code: 42803): SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"direct_messages.id\" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select *, max(created_at) as createdAt from \"direct_messages...
               ^ at /usr/share/nginx/html/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129)`

Full stack trace: https://pastebin.com/y1uvNMyP

**Comment by dansup** [comment]
Fixed in latest commits
