### ISSUE TITLE
Where is the save button in Settings?

### ISSUE THREAD

**Issue by dosch** [pixelfed/pixelfed#2441]
Heya, I want to change some settings in the admin.

But how do I save my changes?

<img width="1000" alt="Screenshot 2020-11-20 at 15 29 30" src="https://user-images.githubusercontent.com/5372610/99811331-542e7280-2b45-11eb-8b80-a268789ab39d.png">

**Comment by mryoaz** [comment]
Is this still an issue, now with the new UI?

**Comment by dansup** [comment]
Fixed.
