### ISSUE TITLE
Images marked NSFW show up revealed in Discover

### ISSUE THREAD

**Issue by Alamantus** [pixelfed/pixelfed#2446]
One of the trending images for pixelfed.social is an image marked as sensitive (for nudity), but in the Discover screen, it is displayed without the content warning. Images marked with content warnings should be hidden everywhere they appear until manually revealed.

Screenshots of Trending section (**NSFW**) and the actual page:
https://imgur.com/a/Dh7BDQX

**Comment by dansup** [comment]
Fixed in latest commits
