### ISSUE TITLE
Lots of inboxValidator failed horizon jobs - Directs (postgres)

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#2447]
Most of the errors seem to be about request running too long or being requested too many times but I also found some relating to a value being too long for the datat type.

e.g.
`Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(191) in /usr/share/nginx/html/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:131`

full stack trace: 
https://pastebin.com/8zR6r7qK

**Comment by dansup** [comment]
Fixed in latest commits
