### ISSUE TITLE
Accept header not parsed properly

### ISSUE THREAD

**Issue by puckipedia** [pixelfed/pixelfed#2448]
Using the header `Accept: foo/bar, application/activity+json, application/ld+json; profile="https://www.w3.org/ns/activitystreams"` or `Accept: application/*`, or equivalent headers, when requesting any Pixelfed AS2 object results in HTML incorrectly being returned, meaning that it's impossible to request any other formats with priority above AS2 JSON. This is (presumably) caused by Laravel's lacking `Accept` header parsing support.

**Comment by dansup** [comment]
Fixed!
