### ISSUE TITLE
Missing Follow button on iOS in browser

### ISSUE THREAD

**Issue by narFnarF** [pixelfed/pixelfed#2451]
On iOS, in the browser, the Follow button is missing from user profiles. Some other buttons seems to be missing too.

Device: iPhone 5s, iOS 12.4.8
App: Safari browser and Firefox

Steps to reproduce:
1. Using the phone browser, go to pixelfed.social and log in.
2. Open any profile (ex: https://pixelfed.social/i/web/profile/_/236964345593073664 for `@avocatier@banana.dog`)
3. Observe the missing Follow button

Expected result:
The follow button is present so I can follow accounts.

Screenshot: https://i.imgur.com/cLnvAWR.png
For reference, I'm talking about these buttons, as seen on desktop: https://i.imgur.com/ZIe1ljO.png

Note: 
This issue started recently. I would say somewhere in the last month or 2. Before that, I was able to follow accounts easily.

**Comment by dansup** [comment]
Fixed!
