### ISSUE TITLE
Profiles issue: Direct messages not saved, notifications not displaying.

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#2455]
I just sent a direct message from my pixelfed instance to my pleroma account:

Text only - works
Image - never received
Response from pleroma - never received (this did work prior to today's updates)
Image from pleroma - never received

When I come out of the message on pixelfed and back to the inbox, the message is gone.

There are no failed horizon jobs.

Not sure if this is related to the issue I had yesterday with the profile_id or if this is an issue as a result of the latest commits.  It could be related, I also don't see any notifications (I had several before the profile_id issue).

**Comment by jk-na** [comment]
I can see the messages in the database, so I think this is related to the issue from yesterday.. the ID used for the messages is the old one (1) rather than the new one but I notice that the new one is back in the users table.

I can also see new notifications in the notifications table which aren't being displayed on pixelfed either.

Favourites & boosts icons not representing activity after a page refresh too.

**Comment by dansup** [comment]
Closing this since you got it fixed on IRC
