### ISSUE TITLE
Inaccurate storage used numbers

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#2458]
I am using 53MB of 1GB and this is being returned as 6% rather than 0.06%

![Screenshot_2020-11-27_13-10-28](https://user-images.githubusercontent.com/51400674/100453089-467f6c80-30b2-11eb-8464-542e8b4df786.png)

**Comment by snarfed** [comment]
um, 53MB is 5.3% (~= 6%) of 1GB, right? seems right.

**Comment by jk-na** [comment]
> um, 53MB is 5.3% (~= 6%) of 1GB, right? seems right.

Been running on a prolongued period of lack of sleep here.. not sure what I was thinking.. as you were, nothing to see here ;)
