### ISSUE TITLE
Location setting could be clearer.

### ISSUE THREAD

**Issue by murphnj** [pixelfed/pixelfed#2466]
When making a post, and adding a location, the selector is unclear as to what location will be active, and where it is.

![Screenshot from 2020-11-30 19-04-03](https://user-images.githubusercontent.com/26210067/100680216-100a5180-333f-11eb-81a7-7e52ba5b5408.png)

I have put in what I thought was correct, and turns out to be incorrect.  Is there a way to specify which state, or to preview where the location will be set to when selecting one of the (in this example) 3 locations?

I have in the past, specified High Point, intending New Jersey, and ending up with a location in the Carolinas.

**Comment by mlncn** [comment]
This happens with "Minneapolis" also (yes turns out there's a second, very small, one!)  County, state, or even only geo coordinates should be enough to fix this.  Especially important to help people get this right the first time without having edit capability— #823

**Comment by HaraldWalker** [comment]
![pixelfed-2466-minden-search](https://user-images.githubusercontent.com/2520109/203832472-cd197ec4-9819-4300-bbd7-d73f14824bd6.png)

Preferably would show additional information like state, district etc. if available. I know the geolocation is available, so at least for the selected one it could show it on a map.
