### ISSUE TITLE
InboxValidator & InboxWorker still pending in Horizon

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#2476]
Hello,

Since march 2020, everytime I try to follow a Pixelfed account with an account from an other instance (Mastodon or Pixelfed), the InboxValidator & InboxWorker jobs are created in Horizon but still pending. So the following is not validated.

I tried several times to create multiple fresh instances on fresh servers, with fresh domains, following the official doc step by step. Like this one I created yesterday :
https://beta.bokeh.social/test

Horizon is runing fine, the queue:work is runing fine, all the other jobs are working fine, the self-diagnosis is ok, and I have nothing in the Laravel log or Nginx log.

It's a very recursive issue on a lot of active instances. You can try to follow all these accounts and it will not work :
https://cliq.buzz/team 
https://anar.chi.st/bugs
https://pixel.nogafam.es/admin
https://instamatic.mountaintown.video/ajroach
https://pixelfett.de/thomas
https://instafed.cattube.org/spla
https://pixel.misterbanal.net/stacyharper
https://imas.photo/barippi
https://pixels.helpchangethe.world/SpunkyAlpaca
https://pixelfed.earth/tscho
ect ect

My configuration : 
Ubuntu 20.04
Nginx 1.18.0
MariadDB 10.3.25
Php 7.4.3
Supervisor for the processes

**Comment by johndevs** [comment]
I can confirm this, I have my own instances of Mastodon and Pixelfed and my Mastodon messages all get stuck in pixelfeds Pending Jobs queue for Inbox Worker. 

I think this started happening end of last year.

Everything is looking green on the Dashboard and Horizon looks okay.

If I ssh into the Horizon container and manually process the queues with

`php artisan queue:work --queue=shared`

It does process the queue successfully and the status appears in my feed.

Using:
Mastodon 4.1.0
Pixelfed 2023-04-12

**Comment by johndevs** [comment]
> I can confirm this, I have my own instances of Mastodon and Pixelfed and my Mastodon messages all get stuck in pixelfeds Pending Jobs queue for Inbox Worker.
> 
> I think this started happening end of last year.
> 
> Everything is looking green on the Dashboard and Horizon looks okay.
> 
> If I ssh into the Horizon container and manually process the queues with
> 
> `php artisan queue:work --queue=shared`
> 
> It does process the queue successfully and the status appears in my feed.
> 
> Using: Mastodon 4.1.0 Pixelfed 2023-04-12

Managed to somehow fix it by ssh:ing into the worker container and doing 
```
php artisan instance:actor
php artisan horizon:install
php artisan horizon:publish
```

And then restarting the container. 

Seems a bit flaky this, shouldn't the worker script initialize it properly from the start?

**Comment by dansup** [comment]
Fixed!
