### ISSUE TITLE
Docker build error pixelfed_worker_1 start.apache.sh not found

### ISSUE THREAD

**Issue by mikeecuffe** [pixelfed/pixelfed#2478]
Hi,
The container pixelfed_worker_1 perists in a restart loop with the following error
/var/www/contrib/docker/start.apache.sh: not found

changing the contrib/docker/start.apache.sh script line terminators from CRLF to LF resolved this for me.

---
Windows 10
Docker 2.5.0.1
branch dev -latest commit SHA 9211bbd6d124e060788d4a2af72229daf6bb8a09 by daniel - "Merge pull request #2469 from pixelfed/staging"

**Comment by mikeecuffe** [comment]
this just needs a .gitattribute pushed. I will make a PR

**Comment by kraihn** [comment]
I'm still experiencing this issue as of yesterday.
