### ISSUE TITLE
Images load in new tab instead of lightbox

### ISSUE THREAD

**Issue by AnonymousWebHacker** [pixelfed/pixelfed#2481]
When I open a photo, full screen in my instance, I open it with the full address, instead of a player.

It's annoying, because you have to turn back to go back to pixelfed
![full](https://user-images.githubusercontent.com/43164089/101846252-e93cdf80-3ae3-11eb-801f-6e628c0830d3.png)
![error](https://user-images.githubusercontent.com/43164089/101846235-e0e4a480-3ae3-11eb-87f6-81c2fe3cc17c.png)

**Comment by AnonymousWebHacker** [comment]
Now go to pixel.org and I realize that it is not implemented.
It would be very cool if they did, it is something that is missing in pixel to make users like it more.
![full2](https://user-images.githubusercontent.com/43164089/101851367-bf3cea80-3aee-11eb-8b00-bdb169448045.png)
![image full](https://user-images.githubusercontent.com/43164089/101851402-d085f700-3aee-11eb-9c9d-7adcb73b40b7.png)

**Comment by AnonymousWebHacker** [comment]
tnks @trwnh I hope you can add those things

**Comment by dansup** [comment]
We've supported the lightbox on click in the webUI for a while now, closing!
