### ISSUE TITLE
Support custom CW text

### ISSUE THREAD

**Issue by lapineige** [pixelfed/pixelfed#2489]
Version : 0.10.9

Hello,
I found two issues:
- When using MomentUI, there is no CW on comments (posted from Mastodon).
- When using MetroUI, CW text is not showed, only "This content may contains sensitive information" which is already something but way less useful that a "real" CW text that indicates what can be the kind of content (that needs that CW)

**Comment by spaceottercode** [comment]
To my best knowledge, the current version of PixelFed under the new UI now fulfills both of @lapineige original point. It may now be safe to close this issue.

I will create a separate one, if it does not already exist, for extending the Create New Post dialog to include the option to add a CW description whenever the Contains NSFW Media option is toggled.
