### ISSUE TITLE
/register Not Found The requested URL was not found on this server.

### ISSUE THREAD

**Issue by BubbletopTag** [pixelfed/pixelfed#2492]
I finally got this whole thing to work, problem is if I try to login or register it will say

Not Found
The requested URL was not found on this server.

Apache/2.4.41 (Ubuntu) Server at clicksnip-beta.bubblesites.ga Port 80

anyone know how to help

I did ls on /usr/share/webapps/pixelfed/public and this the output:
![output](https://user-images.githubusercontent.com/56369099/102025487-392ad900-3d66-11eb-9655-a7a132509ef5.PNG)

Info:
OS: Ubuntu Server 20.04 LTS
Host: Amazon EC2 t2.micro
PHP Version: PHP 7.4.3
Apache Version: 2.4.41
MariaDB version: mariadb  Ver 15.1 Distrib 10.3.25

Apache host config
![host](https://user-images.githubusercontent.com/56369099/102025509-6f685880-3d66-11eb-8b9b-57605d15b50b.PNG)

**Comment by dansup** [comment]
@BubbletopTag Your Apache host config is incorrect, ```AllowOverride None``` should be ```AllowOverride All```.

**Comment by BubbletopTag** [comment]
That didn't seem to fix it.
![eeeeeeeeeeee](https://user-images.githubusercontent.com/56369099/102026750-abeb8280-3d6d-11eb-88be-97ae67bed915.PNG)
![icant](https://user-images.githubusercontent.com/56369099/102026757-b3129080-3d6d-11eb-80b1-e5e7985e60ba.PNG)

I tried to do systemctl reload apache2 even tried to reboot but it still gives me this error

More info 
.htaccess file

![jfoidsjogkdfigiodfgidfigjdfgjdfuiguidfgdfhgdhgudfuighdfui](https://user-images.githubusercontent.com/56369099/102027180-75633700-3d70-11eb-9d50-e917ceda4596.PNG)

**Comment by BubbletopTag** [comment]
helppppppppppppppppppp

**Comment by BubbletopTag** [comment]
Turn out. YOU WONT BELEAVE THIS! I DIDNT ENABLE MOD REWRITE
