### ISSUE TITLE
timeout for App\Jobs\InboxPipeline\InboxValidator

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2497]
Pixelfed: latest
Misskey: 12.63.0 

`{
username: "pixelfed",
headers: {
content-length: [
"1149"
],
connection: [
"keep-alive"
],
signature: [
"keyId="https://misskey/users/882hg3kjcw#main-key",algorithm="rsa-sha256",headers="(request-target) date host digest",signature="wQarVswXceDiEmtTsqY43U6P8BiDF6qjccW6ymcrB6r9fU5oAEP+9EVHEz1Tcbn+NI6Xr/MWMr7N8qlcNu3Q6VyW9jlDOe41vZq3kmST7jbZ0rXsJxFKq1YP6Dgvyoaqh35PjwhMIccwlBTSoaskq42Fz3S4NpTI1tWB0zbRCb6tBHRKPVo9r7s1EXSqK1A5nBPRaMTXOc/aZ6/bToksllcIm4wMKUVTcRwGlmS5VKC5PoUTaKgB1qNw5u5byMQJcJLAuyBohT9jJpwktnvna0udaStpBRvZteSrGyL2Y25iCVzZFkB5/t3xsFQvUrBCYbZG82YwBtAQexopppcZGlIcvhsdaBDrc/IXV/9OFOKmjNiLHJgD3zAUjLnzQ8SivvqCvEtZty6FL/pKRUMI33n5/NBOZ62R5JJ95iTyFkpwAHbmrb9uem1bMIip/+6Am3iGvoco5ij1W9u6pocUBby5q4wVGvS+XMISoMoi9dNdCQGGkNqOAvQDXVCsKczM3me9E4+l1pz+gqkElSwWd2nVI4mW8r8k82FF4Lt77yvXaHHMn2JAaG4aFH5dRuAWxFTgiswxOfAG4kMVsJKPvck/hKSU9E4L+59wzfg1jueBPMNgP4o6x4gCfz0RlrQ1SGbEf7Mo2VPy+o1DB4nrh/o6eVOzUb8qymTHLivNVuE=""
],
date: [
"Mon, 14 Dec 2020 00:50:33 GMT"
],
host: [
"pixelfed"
],
digest: [
"SHA-256=u4oG2vDftlY4WUlaxKYBxBrjLk2aO7IRaqAL0TBtrhM="
],
content-type: [
"application/activity+json"
],
user-agent: [
"Misskey/12.63.0 (https://misskey)"
]
},
payload: "{"@context":["https://www.w3.org/ns/activitystreams","https://w3id.org/security/v1"],"id":"https://misskey/notes/8fren8dlad/activity","actor":"https://misskey/users/882hg3kjcw","type":"Create","published":"2020-12-14T00:50:33.129Z","object":{"id":"https://misskey/notes/8fren8dlad","type":"Note","attributedTo":"https://missmey/users/882hg3kjcw","summary":null,"content":"<p><a href=\"https://pixelfed/pixelfed\" class=\"u-url mention\">@pixelfed@pixelfed</a><span> this is a test</span></p>","_misskey_content":"@pixelfed@pixelfed this is a test","published":"2020-12-14T00:50:33.129Z","to":["https://www.w3.org/ns/activitystreams#Public"],"cc":["https://misskey/users/882hg3kjcw/followers","https://pixelfed/users/pixelfed"],"inReplyTo":"https://pixelfed/p/pixelfed/243899568503263232","attachment":[],"sensitive":false,"tag":[{"type":"Mention","href":"https://pixelfed/users/pixelfed","name":"@pixelfed@pixelfed"}]},"to":["https://www.w3.org/ns/activitystreams#Public"],"cc":["https://misskey/users/882hg3kjcw/followers","https://pixelfed/users/pixelfed"]}",
timeout: 5,
tries: 1,
job: null,
connection: null,
queue: "high",
chainConnection: null,
chainQueue: null,
chainCatchCallbacks: null,
delay: null,
middleware: [
],
chained: [
]
}`

**Comment by dansup** [comment]
@okpierre Can you share the exception too?

**Comment by dallasgroot** [comment]
@dansup this was my expectation error:


Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\InboxPipeline\InboxValidator has been attempted too many times or run too long. The job may have previously timed out. in /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:713
--
Stack trace:
#0 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(195): Illuminate\Queue\Worker->maxAttemptsExceededException(Object(Illuminate\Queue\Jobs\RedisJob))
#1 /home/pi/www/pixelfed/app/Util/ActivityPub/Helpers.php(164): Illuminate\Queue\Worker->Illuminate\Queue\{closure}(14, Array)
#2 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(385): App\Util\ActivityPub\Helpers::App\Util\ActivityPub\{closure}()

**Comment by dansup** [comment]
Fixed in latest commits!
