### ISSUE TITLE
Verify a user

### ISSUE THREAD

**Issue by BubbletopTag** [pixelfed/pixelfed#2498]
I would like to know how to give users a verification badge as it isnt listed in the documentation and I can't find it anywhere in the settings

**Comment by BubbletopTag** [comment]
I know this a dumb question but I actually need help with this

**Comment by cyberkeiler** [comment]
According [this comment of @dansup](https://pixelfed.social/p/dansup/76159055223197696) from a year ago, there is no other badge than the admin badge.

And in my users model there isn't a verified attribute, too.
So the answer is I guess: There is no verified badge (yet?)
