### ISSUE TITLE
Direct Messages: Missing detail page

### ISSUE THREAD

**Issue by gerdemann** [pixelfed/pixelfed#2500]
Hi,

I have updated my instance to the current version. Now I have the problem that I get the following error in the direct messages when I click on a message:
"Sorry, this page isn't available."

I don't see any errors in the logs.

**Comment by trwnh** [comment]
Cannot reproduce

**Comment by gerdemann** [comment]
Can you maybe give me some tips where to look for the error?

**Comment by trwnh** [comment]
Are you running the lastest commits? For me, clicking on a DM just loads the context menu.

**Comment by gerdemann** [comment]
Yes, I use the latest commits. As soon as I click on a DM, I get a 404 (Sorry, this page isn't available).
Unfortunately, I don't get an error in any log either. Can you give me tips on how I can debug this?
