### ISSUE TITLE
Postgresql - Artisan backup not available

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#2508]
Unable to run the artisan backup:run command as the following response is returned:

`Backup failed because: Cannot create a dumper for db driver 'postgres'.  Use 'mysql', 'pgsql', 'mongodb' or 'sqlite'..`

There is no mention of 'postgres' in my .env file so I gather this is incorrectly defined in some application file.

My relevant .env entries are:
`DB_CONNECTION=pgsql`
`DB_DRIVER=pgsql`

**Comment by trwnh** [comment]
DB_DRIVER is not an env var anywhere in the config. But do you maybe have cached config? Try running the `config:cache` or `config:clear` Artisan tasks.

**Comment by jk-na** [comment]
I removed DB_DRIVER from my .env file and ran `config:cache` as per normal with any env update.. still exactly the same error

**Comment by jk-na** [comment]
I presume that the artisan job itself or associated file(s) contains a reference to 'postgres' rather than 'pgsql'

**Comment by dansup** [comment]
@jk-na Replace `mysql` with `pgsql` here https://github.com/pixelfed/pixelfed/blob/4ad3de3b885b8d21a53ca9cc8a4a83e2a1d4a459/config/backup.php#L52

Then run `php artisan config:cache`

**Comment by jk-na** [comment]
this worked, thanks.
