### ISSUE TITLE
Fresh install on postgresql database throws error on duplicate column 2provider"

### ISSUE THREAD

**Issue by xundeenergie** [pixelfed/pixelfed#2510]
Installed pixelfed fresh according to this instructions https://docs.pixelfed.org/running-pixelfed/installation.html#setting-up-services 
On `php artisan migrate --force` i get the following error

`Migrating: 2020_12_13_203646_add_providers_column_to_oauth_clients_table

   Illuminate\Database\QueryException 

  SQLSTATE[42701]: Duplicate column: 7 ERROR:  column "provider" of relation "oauth_clients" already exists (SQL: alter table "oauth_clients" add column "provider" varchar(191) null)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕ 

      +12 vendor frames 
  13  database/migrations/2020_12_13_203646_add_providers_column_to_oauth_clients_table.php:18
      Illuminate\Support\Facades\Facade::__callStatic("table")

      +22 vendor frames 
  36  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
`

Workaround (not sure if i break something with it):
comment out the whole function "up" in file 
`database/migrations/2020_12_13_203646_add_providers_column_to_oauth_clients_table.php`
run `php artisan migrate --force` again, no error. 
Remove comments for function up, run command again, no error.

**Comment by cyberkeiler** [comment]
Can verify the same issue for mysql migration in a fresh DB

**Comment by cydactyl** [comment]
Just came here to report this same thing.

I just commented out line 17
`$table->string('provider')->after('secret')->nullable();`
in pixelfed/database/migrations/2020_12_13_203646_add_providers_column_to_oauth_clients_table.php

**Comment by dansup** [comment]
Fixed in #2530
