### ISSUE TITLE
Link to federated profile on comments lead to wrong subpath

### ISSUE THREAD

**Issue by xundeenergie** [pixelfed/pixelfed#2512]
When i add a comment with a mentioned user (for example from my own mastodon-instance), the username gets blue and is linked to https://japix.schuerz.at/@jakob@mastodon.schuerz.at?src=rph
![grafik](https://user-images.githubusercontent.com/5894829/102331381-10cff400-3f8b-11eb-8f00-64a39f050f35.png)
![grafik](https://user-images.githubusercontent.com/5894829/102331866-ac616480-3f8b-11eb-9856-bc856d21fc1d.png)

That's correct.
Reloading the page changes the link. Now it points to https://japix.schuerz.at/discover/tags/@jakob@mastodon.schuerz.at?src=rph which is wrong and leads to 
![grafik](https://user-images.githubusercontent.com/5894829/102331769-889e1e80-3f8b-11eb-9208-ffa59eb43dfd.png)

**Comment by dansup** [comment]
Fixed!
