### ISSUE TITLE
Using Fork Awesome instead of Font Awesome

### ISSUE THREAD

**Issue by lanodan** [pixelfed/pixelfed#252]
Font awesome basically went partly closed source and stopped accepting new icons, fork awesome is a continuation of it but still under a free license and with new icons accepted.

Their website is on: https://forkawesome.github.io/

**Comment by xuv** [comment]
I have to add also that Fork Awesome has integrated the icons for the most popular fediverse apps: Mastodon, Diaspora, Peertube, GnuSocial and even has an icon for ActivityPub. We'll be happy to add PixelFed to the list once you settle down for a logo ;)

**Comment by dansup** [comment]
The Font Awesome 5 free icons better suit the UI of pixelfed.

**Comment by lanodan** [comment]
:-1: Because you can probably report that issue of yours or easily change the style as it’s SVG, unless it’s the drawings that you don’t like.
And I’m pretty sure Font Awesome (Free) Icons will not stay there anyway.
