### ISSUE TITLE
Doesn't seem possible to expand photos to full window if not signed in

### ISSUE THREAD

**Issue by debbiegoldsmith** [pixelfed/pixelfed#2526]
It is possible for users to view (public) photo posts even if they don't have a pixelfed or Mastodon account. However, the button to expand photos to take up the whole browser window is in a bar with the comment/like/bookmark tools, so if you're not signed in you don't see it, and there's no way to expand the image.
Could that button be moved (or duplicated) elsewhere, so it can appear even if you're not logged in? Perhaps next to the image itself?

**Comment by trwnh** [comment]
You can right click and view image, but yeah, the UI logic should probably be refactored so that only specific buttons are hidden instead of all buttons. Or the expand button should be in a separate container.

**Comment by dansup** [comment]
Fixed!
