### ISSUE TITLE
Issue in setup/db migration

### ISSUE THREAD

**Issue by JHenzi** [pixelfed/pixelfed#2527]
I'm looking to setup pixelfed and when I execute the following;

php artisan migrate --force

This runs fine for a while and then errors out on a fresh database:

Migrating: 2020_12_13_203646_add_providers_column_to_oauth_clients_table

   Illuminate\Database\QueryException

  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'provider' (SQL: alter table `oauth_clients` add `provider` varchar(191) null after `secret`)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕

      +12 vendor frames
  13  database/migrations/2020_12_13_203646_add_providers_column_to_oauth_clients_table.php:18
      Illuminate\Support\Facades\Facade::__callStatic("table")

      +21 vendor frames
  35  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by dansup** [comment]
Fixed in #2530
