### ISSUE TITLE
Why limiting to 150 letters ?

### ISSUE THREAD

**Issue by PhieF** [pixelfed/pixelfed#253]
Hi ! I was wondering : why such a low limit ?
something like 1000 - 5000 letters would allow us to join small poems with images for example, would be nice ! :)

thanks for your work

**Comment by hellcp** [comment]
If anything limit would be to 500, for Mastodon federation purposes

**Comment by faissaloo** [comment]
I like the limit, 'show more' looks ugly under an image people should keep their captions brief

**Comment by dansup** [comment]
@PhieF The goal is to support up to 2200 like IG but truncate to the first 150 with a read more link. Each instance admin can set their own limit in the config!

**Comment by dansup** [comment]
Fixed in latest commits

**Comment by ghost** [comment]
Tried to set this to 500 ends up with the standard 150 letters

Steps to reproduce:

Set `MAX_CAPTION_LENGTH=500` in .env and ran the command `php artisan config:cache`

Still 150 letters.

**Comment by ghost** [comment]
An additional `php artisan cache:clear;` is the solution.
