### ISSUE TITLE
Federation between Pixelfed instances is inconsistent

### ISSUE THREAD

**Issue by Casuallynoted** [pixelfed/pixelfed#2540]
I'm noticing that federation between Pixelfed instances is really lacking and inconsistent. At the moment, you can manually search up someone and find them but they have no profile photo and no content. Oftentimes, the content itself doesn't load in at all- even new stuff. For example, on my instance I've followed @dansup@pixelfed.social, but I've never seen that content because his profile on my instance is still totally empty after nearly a year of having followed it.

Here's a link to Dansup's profile page on my instance: https://fatpig.club/i/web/profile/_/212048754507911168

Versus the same profile page on its origin instance: https://pixelfed.social/dansup

And I'm seeing the same issues when trying to follow my own profile from a profile I made on pixelfed.social: https://pixelfed.social/i/web/profile/_/212048775647203328

I've also noticed that folks on the same instance are not seeing reshared content from other instances on their home timelines.

While I know not every federated instance will federate the same way (of course there have gotta be considerations with other open source software like Masto, Pleroma, Misskey, etc.), it's gotta be more consistent between two or more Pixelfed instances. It's part of what creates the neat network that is Pixelfed! :) 

With that said, awesome job on the latest updates. I'm really enjoying DMs and it's neat seeing Pixelfed evolve so nicely over time.

EDIT: Just realized the link to my instance requires registration. Here's a screencap of what the profile looks like-

![image](https://user-images.githubusercontent.com/6272557/103395543-96f84880-4afc-11eb-938b-adb6ffbf6259.png)

**Comment by okpierre** [comment]
@Casuallynoted from my small test, it does seem actions (likes, comments, shares, messages) between Mastodon, Misskey and Pleroma work well together but Pixelfed doesn't. Dansup did mentioned on irc last week that features are being refactored so something to look forward to.

**Comment by dansup** [comment]
Fixed in #2545
