### ISSUE TITLE
Owner cannot view Followers Only post [bug]

### ISSUE THREAD

**Issue by spaceottercode** [pixelfed/pixelfed#2542]
Hi PixelFed Team,

First and foremost, thank you for all the great work you've done. I just wanted to report a possible bug. Not sure, if this is a new bug or not, but as of version 0.10.9 I cannot visit any posts I have posted with a visibility of Followers Only. Instead when I click on said post from the Profile/Gallery Page I get a Sorry this page isn't available screen. I also noticed that Followers-Only post don't appear in my Home timeline...though this issue sounds familiar (sorry if its a duplicate or regression)...anyhow here are the steps I took to encounter this issue:

Post a video and mark it as Followers Only
navigate to the My Profile page
Click on thumbnail of said post
Page with error displays

Once again, thank you for your time.

**Comment by dansup** [comment]
This has been fixed, thanks for the bug report!

**Comment by spaceottercode** [comment]
Wow you're fast! Thank you @dansup
