### ISSUE TITLE
Hashtag discovery and search missing posts

### ISSUE THREAD

**Issue by dpmcgonigle** [pixelfed/pixelfed#2560]
Hello,

I'm getting an incorrect number of posts showing on both the hashtag discovery page as well as using a search for a given hashtag.  All of the posts are public, and none of them have any sensitive content or anything like that.  I am attaching a couple of pictures that indicate the issue:

<img width="547" alt="hashtag" src="https://user-images.githubusercontent.com/26857163/104201905-daea2800-53ef-11eb-8a9f-dc34d4c98312.png">
<img width="550" alt="search" src="https://user-images.githubusercontent.com/26857163/104201915-dde51880-53ef-11eb-8ba5-ba04c0cf6891.png">

In both cases, there should be 11 posts that show, but only 9 are displayed.  I have tried to run the "php artisan fix:hashtags" command, but it says there are none to fix.  I'm also not sure if I'm running that command correctly.

My question is whether it is correct behavior not to show all posts with a given hashtag when viewing the hashtag discovery page, or when searching for a particular hashtag with the search bar.  If that is not the correct behavior, I'm wondering if there is anything I should be doing that can fix the current behavior.  I'm currently using Pixelfed 0.10.7.

**Comment by jk-na** [comment]
I too have this issue and have done for a looooong time.  It seems that photos that are part of an album are included in the count individually but the album or individual photos are not displayed, though this might not be a variable in your particular issue, I get these similar results with categories also.

**Comment by dpmcgonigle** [comment]
To piggyback on this issue, I am also getting the wrong amount of posts in /timeline/public.  For instance, if I look at account 1, which has 8 posts, and account 2, which has 4 posts, I am getting 11 posts total in /timeline/public.  Is there some mechanism that is truncating the total posts to view in Pixelfed?

**Comment by dansup** [comment]
Hashtags used in comments count towards the total and are not displayed on Hashtag page. Profile status count includes comments/replies as well.

**Comment by dpmcgonigle** [comment]
Thanks for the response, but all of the hashtags were in the post caption.  None of them were in comments/replies.
