### ISSUE TITLE
Multi-hashtag categories post count includes duplicates

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#2561]
I have a category on my instance that reports 24 posts, the category has 3 hashtags with a post count of 18, 1 and 5.. which equals 24 and so is sort of correct.. but there are posts which contain 2 of the 3 hashtags and each hashtag is being counted once to arrive at the total, rather than the total containing only unique posts.

If this doesn't make sense, I'm happy to provide a more detailed example later.

**Comment by dansup** [comment]
Fixed in https://github.com/pixelfed/pixelfed/pull/4342
