### ISSUE TITLE
Too few arguments to function .. InboxValidator::verifySignature()

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#2568]
After today's commits I'm seeing numerous failed jobs in horizon with the follow error:

`ArgumentCountError: Too few arguments to function App\Jobs\InboxPipeline\InboxValidator::verifySignature(), 2 passed in /usr/share/nginx/html/pixelfed/app/Jobs/InboxPipeline/InboxValidator.php on line 92 and exactly 3 expected in /usr/share/nginx/html/pixelfed/app/Jobs/InboxPipeline/InboxValidator.php:131`

Full stack trace: https://pastebin.com/XtGJSzLK

Pixelfed: 10.9.0 (latest commit acf04b6b63f845498545b2d3828aba94a414c87f)
PostGresSQL: 12.5
PHP: 7.3
Laravel: 8.22.1

**Comment by dansup** [comment]
Fixed in #2569
