### ISSUE TITLE
Please don't use a CDN

### ISSUE THREAD

**Issue by 0-st** [pixelfed/pixelfed#258]
Since a script moved to cloudflare the website doesn't work properly anymore in all cases.

**Comment by dansup** [comment]
@Sarkasper In 0b85810 I removed CDN assets.

**Comment by ghtux** [comment]
there's still cloudflare used. Without script profile isn't working

**Comment by kpcyrd** [comment]
@mglinux I'm having trouble finding any reference to "cloudflare" in the repo using git grep, could you provide more information what you found and where? Thanks!

**Comment by ghtux** [comment]
OK this was misleading sorry. Pixelfed.social is using cl Ajax, so this not related to pixelfed itself. My fault, not a fan of cloudflare 😋

**Comment by Perflyst** [comment]
As far as I can see there is still cdnjs.cloudflare.com used in the admin section.

```
pixelfed/resources/views/admin/settings/system.blade.php:<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.0/marked.min.js" integrity="sha256-Z0oIr+NZFYgsP19IS8I9OHioGTr34whIUMpSNMaKj8o=" crossorigin="anonymous"></script>
pixelfed/resources/views/admin/home.blade.php:<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js" integrity="sha256-oSgtFCCmHWRPQ/JmR4OoZ3Xke1Pw4v50uh6pLcu+fIc=" crossorigin="anonymous"></script>
```

also here

```
pixelfed/resources/views/admin/pages/edit.blade.php:<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
pixelfed/resources/views/admin/pages/edit.blade.php:<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
```
