### ISSUE TITLE
Key path "file:///var/www/storage/oauth-private.key" does not exist or is not readable

### ISSUE THREAD

**Issue by dunn** [pixelfed/pixelfed#2586]
I'm running into this error with a local Docker dev installation.  I made sure OAuth is enabled, spun up the instance, then created an account and tried to generate a personal access token (with all permissions).  Here's the full trace: https://gist.github.com/dunn/7c2807853ec4f4cca655f7c4d44cb770

Do the `PASSPORT_*` environment variables need to be set?  The comments around them made it seem optional.

**Comment by dansup** [comment]
@dunn Run the following commands listed [here](https://github.com/pixelfed/pixelfed/releases/tag/v0.10.6), will update the documentation!

**Comment by trwnh** [comment]
Docs have already been updated since some time ago: https://docs.pixelfed.org/technical-documentation/api-v1.html
