### ISSUE TITLE
Embeding user profile always show following count

### ISSUE THREAD

**Issue by zefr0x** [pixelfed/pixelfed#2590]
When i embed my profile to a website the Following bar appears even though I have disabled Show Following Count from my Privacy settings.

I am using **https://pixelfed.social** and it's on **version 0.10.9**

**_Also it would be a good idea to set an option to configure Dark Mode in Embeding._**
![Screenshot_20210128_143446](https://user-images.githubusercontent.com/65136727/106134342-73660380-6177-11eb-967c-0cb3a0c7a9b2.png)
![Screenshot_20210128_144017](https://user-images.githubusercontent.com/65136727/106134345-74973080-6177-11eb-8b1e-23d29c4764c4.png)

**Comment by zefr0x** [comment]
I tried it again today and the data has become vulnerable to leakage (so now it's a security issue). I don't know if it shows zero value yestrday because  of the server's slow database _--I followed a new person 5 minutes before the test--_ or it's due to the new update 0.10.10

_**I'm sorry about the wrong info yestrday.**_ ☹☹

![Screenshot_20210129_185556](https://user-images.githubusercontent.com/65136727/106297352-a980b180-6263-11eb-8be0-e120ce46197b.png)

**Comment by dansup** [comment]
Fixed in #2641!
