### ISSUE TITLE
Server Error When Creating A Personal Access Token

### ISSUE THREAD

**Issue by ryan-ricard** [pixelfed/pixelfed#2598]
I have an account on pixelfed.social - https://pixelfed.social/firewally - and I would like to create a Pesonal Access Token to develop a script that cross-posts between Pixelfed and Instagram. I'm currently unable to create a Personal Access Token

## Steps to Reproduce

1. Navigate to https://pixelfed.social/settings/applications
2. Click "Create new token"
3. Give the token a name, check "read" and "write"
4. Click "Create"

**Expected Result:** I am shown a new Personal Access Token

**Actual Result:** Nothing happens in the UI. When I open up developer tools and view the Network tab, I see a 500 response with "Server Error" as the content

**Comment by dansup** [comment]
Fixed!
