### ISSUE TITLE
Can't delete posts

### ISSUE THREAD

**Issue by DrageFem** [pixelfed/pixelfed#2608]
On pixfed.com, I'm trying to delete some of my posts, but after I confirm that I want it deleted, it still stays up.

**Comment by okpierre** [comment]
Not sure if it is related but notice something similar from my test.

Added several posts and then went to the time line view to delete. 

After posts are deleted, refresh timeline page and some posts reappears.

Pixelfed v0.10.10

**Comment by DrageFem** [comment]
I don't see which version pixfed.com is right now. Unlike other pixelfed instances, the version isn't displayed at the bottom of the page.

**Comment by okpierre** [comment]
That instance is using v0.10.9

**Comment by dansup** [comment]
This is not a bug in Pixelfed, likely pixfed.com has problems with horizon/redis installation. Please contact the admins of that instance for assistance.
