### ISSUE TITLE
Like count does not match

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2610]
Like count for individual post does not match profile view

example:
post = 6 likes
![pflikecount](https://user-images.githubusercontent.com/1679025/106700614-318fef80-65b3-11eb-9f62-ebc8eb8d9cde.png)

profile view = 2 likes
![pflikecountprofile](https://user-images.githubusercontent.com/1679025/106700616-3359b300-65b3-11eb-99a1-7d4b92c98b7f.png)

Pixelfed v0.10.10

**Comment by dansup** [comment]
Fixed in latest commits!
