### ISSUE TITLE
v0.10.10, ErrorException when importing from Instagram

### ISSUE THREAD

**Issue by splacat** [pixelfed/pixelfed#2612]
Running 0.10.10 version.

When importing photos from Instagram, downloaded to local directory and selected from there, Horizon throws this error:

ErrorException: rename(/var/www/pix/pixcat/storage/app/import/9c046093-3b1c-4671-856f-eb9f13c3bbe7/murfcouOtLKQdiM3Typh6wdbB4MkwJwizGYls9Bb.jpg,/var/www/pix/pixcat/storage/app/public/m/01425e939359e081ec015715d0dd00fc7d06754e/1d580e6fb305dc377450e8f0146c6d7dbcfa5dc9/5c2e9b165caa32e7cce3260906d0026e.jpg): No such file or directory in /var/www/pix/pixcat/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:290

Target directory does not exists so seems a create dir permissions problem. I followed exactly the instructions [to set them right](https://docs.pixelfed.org/running-pixelfed/installation.html#set-correct-permissions) but ErrorException keeps throwing above error.

Even tried a new fresh install in a new directory but nothing changed.

**Comment by dallasgroot** [comment]
I too am getting this as well

**Comment by t3rr0rz0n3** [comment]
Same error.

I have checked that after creating this directory storage/app/public/m/01425e939359e081ec015715d0dd00fc7d06754e/1d580e6fb305dc377450e8f0146c6d7dbcfa5dc9/ manually, then it is imported correctly.

**Comment by stelzch** [comment]
Hello, I opened a PR with a patch that worked for me. It is best to try it with a fresh install.

Feedback very welcome.

**Comment by t3rr0rz0n3** [comment]
It seems to be working @stelzch. But it only lets me upload 100 posts from Instagram (454 post in total), is there a limit @dansup?

**Comment by splacat** [comment]
> Hello, I opened a PR with a patch that worked for me. It is best to try it with a fresh install.
> 
> Feedback very welcome.

@stelzch it works, thank you.

**Comment by stelzch** [comment]
> But it only lets me upload 100 posts from Instagram (454 post in total)

@Zagur Yes, there is a configuration variable for that: https://docs.pixelfed.org/technical-documentation/env.html#import-instagram-post-limit

**Comment by t3rr0rz0n3** [comment]
> > But it only lets me upload 100 posts from Instagram (454 post in total)
> 
> @Zagur Yes, there is a configuration variable for that: https://docs.pixelfed.org/technical-documentation/env.html#import-instagram-post-limit

Okaay! It works, thank you @stelzch!

**Comment by dansup** [comment]
Fixed!
