### ISSUE TITLE
Argument 2 passed to App\Http\Controllers\CollectionController::show() must be of the type int

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2615]
Pixelfed v0.10.10

`ERROR: Argument 2 passed to App\Http\Controllers\CollectionController::show() must be of the type int, string given, called in /pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Controller.php on line 54 {"exception":"[object] (TypeError(code: 0): Argument 2 passed to App\\Http\\Controllers\\CollectionController::show() must be of the type int, string given, called in /pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Controller.php on line 54 at /pixelfed/app/Http/Controllers/CollectionController.php:35)`

stacktrace https://pastebin.com/YchAXwFW

**Comment by dansup** [comment]
~@okpierre Stack traces without the line before #0 are useless, need to see the exception that triggered it.~

**Comment by dansup** [comment]
What version of PHP are you running?

**Comment by okpierre** [comment]
PHP 7.4.15
