### ISSUE TITLE
Trying to access array offset on value of type null at FederationController.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2617]
Pixelfed v0.10.10

`ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /pixelfed/app/Http/Controllers/FederationController.php:56)`

stacktrace https://pastebin.com/PsuHDwEt

**Comment by dansup** [comment]
~@okpierre Stack traces without the line before #0 are useless, need to see the exception that triggered it.~

**Comment by dansup** [comment]
This should be fixed in the latest commits, can you confirm? Feel free to re-open the issue.
