### ISSUE TITLE
Last admin is set as "Instance Admin"

### ISSUE THREAD

**Issue by mnowiasz** [pixelfed/pixelfed#2618]
I want to have more than one admin on my new site - unfortunately at my test site I've noticed that the last admin (i.e. the newest one) is shown as "Instance Admin" in the about-page.  It would be great to configure this behaviour, because I'm supposed to be the "main" admin (i.e. "Instance Admin") and other admins are secondary one - helping out if I'm not available and so on. However, they are not the main admins..

**Comment by dansup** [comment]
Fixed! You can delegate the public admin in the Settings dashboard
