### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by mkljczk** [pixelfed/pixelfed#262]
Just a meta-issue to count, what do we have to change in PixelFed in order to be GDPR-compliant:
- [x] service can only be available for users who are at least 16 years old #259
- [x] privacy policy should be more visible #261
- [ ] contact form should be included as temporary solution to everything that user can download or request to remove from server

These are the most important ones ~(the last one is the most important)~, but there’s probably much more to do…

**Comment by nikhiljha** [comment]
> service can only be available for users who are at least 16 years old

Can we just make a checkbox that says "I am 16 or older." during signup? Seems easy to comply with that.

**Comment by mkljczk** [comment]
@nikhiljha but it's just for servers running in EU, there's already info about COPPA in privacy policy

**Comment by vilbi** [comment]
The GDPR is targeting not for servers located in EU but for EU users. So the age of EU users has to be restricted to 16+.  And hiding that somewhere in documents is not complient, so a prominent checkbox at the registration page "as EU user I state that I am over 16 years old" is from my understanding compliant...

**Comment by vilbi** [comment]
The GDPR is targeting not for servers located in EU but for EU users. So the age of EU users has to be restricted to 16+.  And hiding that somewhere in documents is not complient, so a prominent checkbox at the registration page "as EU user I state that I am over 16 years old" is from my understanding compliant...

**Comment by vilbi** [comment]
Next topic is that a user account must be deleted inc. all posts, comments etc. on user request. (For federating services, this request should be forwarded for each topic to the federation as delete request)

**Comment by vilbi** [comment]
Source https://www.eugdpr.org/gdpr-faqs.html
For the two topics:
What about Data Subjects under the age of 16? 
"Parental consent will be required to process the personal data of children under the age of 16 for online services; member states may legislate for a lower age of consent but this will not be below the age of 13."
And
Who does the GDPR affect?
" It applies to all companies processing and holding the personal data of data subjects residing in the European Union, regardless of the company’s location."
and
What constitutes personal data?
"…This definition provides for a wide range of personal identifiers to constitute personal data, including name, identification number, location data or online identifier,…"

**Comment by todoneunl** [comment]
@dansup Especially the option to delete an account as @vilbi mentioned, has a very high priority.

**Comment by dansup** [comment]
You can delete your account on a supported instance. Here is the link for pixelfed.social: https://pixelfed.social/settings/remove/request/permanent
