### ISSUE TITLE
App\Jobs\InboxPipeline\InboxValidator: ErrorException: Trying to get property 'private_key' of non-object

### ISSUE THREAD

**Issue by mnowiasz** [pixelfed/pixelfed#2625]
I've noticed a problem with activity pub - there are failed jobs in Horizion containing:

```
ErrorException:  Trying to get property 'private_key' of non-object in  /var/www/pixelfed.netzgemeinde.eu/htdocs/pixelfed/app/Util/ActivityPub/HttpSignature.php:40
--
Stack trace:
#0   /var/www/pixelfed.netzgemeinde.eu/htdocs/pixelfed/app/Util/ActivityPub/HttpSignature.php(40):  Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8,  'Trying to get p...', '/var/www/pixelf...', 40, Array)
#1   /var/www/pixelfed.netzgemeinde.eu/htdocs/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(420):  App\Util\ActivityPub\HttpSignature::App\Util\ActivityPub\{closure}()
#2   /var/www/pixelfed.netzgemeinde.eu/htdocs/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(406):  Illuminate\Cache\Repository->rememberForever('federation:_v1:...',  Object(Closure))
```

I've set:
```
ACTIVITY_PUB=true
AP_REMOTE_FOLLOW=true
AP_INBOX=true
```
Any idea what's wrong here?

**Comment by dallasgroot** [comment]
Same issue here, fresh install of 0.10.10. 
```
ACTIVITY_PUB=true

AP_REMOTE_FOLLOW=true

AP_OUTBOX=true

AP_INBOX=true

AP_LOGGER_ENABLED=true

INSTANCE_DISCOVER_PUBLIC=true
```

**Comment by mnowiasz** [comment]
Due to this bug Activity Pub is not working at all - when trying to add the channel from another instance (in this case, hubzilla) via activitiy pub there's no feed at all.

Oh, and FediLab - the Android App - doesn't work too, something about a API and long response.

PHP is 7.3.26, DB is postgres (13.1)

**Comment by t3rr0rz0n3** [comment]
I too am getting this as well. Fresh install of 0.10.1 (Debian 10 with PHP 7.3 with MariaDB)

**Comment by okpierre** [comment]
@mnowiasz 

> Due to this bug Activity Pub is not working at all

Could activity pub not work because of this FederationController.php https://github.com/pixelfed/pixelfed/issues/2617

**Comment by der-On** [comment]
Same here with staging branch.

**Comment by nuciluc** [comment]
have you tried to execute the command `php artisan instance:actor` ?

reference: [https://github.com/pixelfed/pixelfed/releases/tag/v0.10.10](https://github.com/pixelfed/pixelfed/releases/tag/v0.10.10)

**Comment by dallasgroot** [comment]
I have done this already

**Comment by mnowiasz** [comment]
> 
> 
> have you tried to execute the command `php artisan instance:actor` ?
> 
> reference: https://github.com/pixelfed/pixelfed/releases/tag/v0.10.10

That seems to do the trick. Well, I haven't upgraded I've installed a new instance by using the documentation: https://docs.pixelfed.org/running-pixelfed/installation.html - and there was nothing about running `php artisan instance:actor`. To be honest, I'm a little bit puzzled: Am I really supposted to read all release notes when installing a new instance?

**Comment by mnowiasz** [comment]
Additional information: After running this command on my freshly installed instance activity pub is now working.
