### ISSUE TITLE
Feature Request: Followers-Only option for Pixelfed Stories

### ISSUE THREAD

**Issue by spaceottercode** [pixelfed/pixelfed#2627]
At the moment (I believe) stories default to Public visibility. I could be wrong, but i cant tell. If this is the case, then it would be nice to have the option to also post Followers Only stories.

That's pretty much it. thank you.

Aside: When Pixelfed circles/lists are added, this will also be a potential use case for them. ( one could argue that followers only designation, and even public, are special case circles/lists to begin with). But this is outside the scope of this request.

**Comment by dansup** [comment]
Stories are follower only atm, we're adding support for public stories soon!
