### ISSUE TITLE
Trying to get property 'id' of non-object at Helpers.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2639]
Pixelfed v0.10.10

`ERROR: Trying to get property 'id' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'id' of non-object at /pixelfed/app/Util/ActivityPub/Helpers.php:351)`

stacktrace https://pastebin.com/HDdBFFVb

**Comment by dansup** [comment]
~@okpierre Stack traces without the line before #0 are useless, need to see the exception that triggered it.~

**Comment by dansup** [comment]
@okpierre Are you running the latest commits? What version of PHP?

**Comment by okpierre** [comment]
@dansup PHP 7.4.15 - will keep an eye on this with the latest commits

**Comment by dansup** [comment]
Fixed in #2665
