### ISSUE TITLE
Bug - Pixelfed generates invalid URIs for User Profile pictures/ avatars that are stored on S3

### ISSUE THREAD

**Issue by cyberczar** [pixelfed/pixelfed#2646]
I have S3 storage configured for my instance as follows:

```
APP_URL="https://foo.com"
...
FILESYSTEM_DRIVER=s3
FILESYSTEM_CLOUD=s3
AWS_ACCESS_KEY_ID=[redacted]
AWS_SECRET_ACCESS_KEY=[redacted]
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=cdn.foo.com
AWS_URL="https://cdn.foo.com/"
AWS_ENDPOINT="https://s3.us-east-1.wasabisys.com"
AWS_USE_PATH_STYLE_ENDPOINT=true
```

Media uploaded is stored just fine, and appears just fine in local timelines. The URI generated for any media uploaded is correct.

However, if a user goes to upload a new profile picture, the URI that is generated to load the uploaded avatar is invalid and generates a 404 error because the URI does not exist.

This is the invalid URI that is generated for an profile picture recently uploaded:

`https://foo.comhttps//cdn.foo.com/public/avatars/026/418/038/774/235/545/6/6qjLfqiiMAtMY45Vo5l9_avatar.jpg?v=1`

As you can see above, the first 15 characters of the above string are being erroneously prepended to the avatar image URI generated.

I have tried setting `AWS_USE_PATH_STYLE_ENDPOINT` to both `true` and `false` with the same results.

**Comment by dansup** [comment]
@cyberczar Do not set `FILESYSTEM_DRIVER=s3`, it needs to be `FILESYSTEM_DRIVER=local`.

Pixelfed needs to temporarily store media locally to optimize and process before uploading to S3. If you want to support S3 for media files, set `FILESYSTEM_CLOUD=s3` like you have.
