### ISSUE TITLE
Bug - Unable to upload an MP4 video

### ISSUE THREAD

**Issue by cyberczar** [pixelfed/pixelfed#2649]
With `MEDIA_TYPES=image/jpeg,image/png,image/gif,video/mp4` set in the `.env` file, followed by a `php artisan config:cache` command being executed as the pixelfed user, users are still unable to upload any MP4 videos. The following error message is displayed:

![image](https://user-images.githubusercontent.com/9130320/107814023-3c7b1a80-6d3f-11eb-91da-4254f3c17624.png)

As you can see, it's like the `MEDIA_TYPES` variable is not being overwritten or at least recognized by the system.

**Comment by dansup** [comment]
You need to also run `php artisan cache:clear` to clear a cached api endpoint when changing `MEDIA_TYPES`
