### ISSUE TITLE
Undefined index: id at InboxWorker.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2650]
Pixelfed v0.10.10 / PHP 7.4.15

`ERROR: Undefined index: id {"exception":"[object] (ErrorException(code: 0): Undefined index: id at /pixelfed/app/Jobs/InboxPipeline/InboxWorker.php:141)`

stacktrace https://pastebin.com/tY2fWKiw

**Comment by dansup** [comment]
@okpierre Do you have the ActivityPub object payload for this exception?

**Comment by dansup** [comment]
Fixed in #2665
