### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry for key 'uri' at PDOStatement.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2655]
Pixelfed v0.10.10 / PHP 7.4.15 / mysql  Ver 14.14 Distrib 5.7.33

`(PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'https://misskey' for key 'uri' at /pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115)`

stacktrace https://pastebin.com/YQykPbrS

**Comment by dansup** [comment]
Fixed in #2665
