### ISSUE TITLE
Refactor post presenter

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#267]
- The buttons and indicators are not readily visible.
- Different aspect ratios cause a jarring reflow of the container.
- Galleries auto-advance in a slideshow, which does not allow viewing one photo for an extended period of time.
- Galleries only show the first photo in timelines.

Possible approaches:
- Use a square container for album posts of differing aspect ratio, and apply `object-fit: contain` (similar to #244)
- Filmstrip view instead of a slideshow

For controls:
- Either add a background or shadow to the overlay controls, or possibly move them outside the image container?

**Comment by nailyk-fr** [comment]
* Different aspect ratios cause a jarring reflow of the container: 

On my timeline (default page) someone made a post with multiples images (https://pix.hostux.social/p/fennec/3247) Those pictures does not have the same height. 
This cause 'jumps' on every below posts: 
![mov_0006](https://user-images.githubusercontent.com/16372405/48959239-62505500-ef64-11e8-8f22-a14a93da156a.gif)
![mov_0005](https://user-images.githubusercontent.com/16372405/48959246-6a0ff980-ef64-11e8-92e5-daf530457ce0.gif)
(sorry for poor quality gifs...)

**Comment by trwnh** [comment]
For inspiration / recap:

1) https://www.instagram.com/p/BxJEhzGBEfd/ is a good example of how we can handle the album view, and allow creative panorama illusion.

2) Worth noting that the flexibility of the IG/FB image viewers is that they've caused a dark pattern of advertisers making their media taller to take up more screen space. Enforcing a square container and letting media fit itself is a way to avoid this. The lightbox can be used to view the image closer to fullscreen; e.g. the container can be 640px * 640px, but the lightbox can be near-fullscreen.
  - We may want to allow users to set a background color to their post, to avoid cases where people use other image editors to hardcode a solid background and force images to be square that way. This would allow the original aspect ratio to be preserved in the lightbox instead of having black bars around it, etc. It also saves on storage space.

3) Animation / slideshow should be opt-in, not automatic. Most other viewers have a dedicated slideshow button. Auto-navigating not only causes ugly reflows (as per point 2), but it also prevents viewing one image for an extended period of time.

4) I think we should remove overlays from the image and instead put that info in the cards. Here's a mockup:

Before | After
--- | ---
![20190506-210729](https://user-images.githubusercontent.com/10606431/57267862-3a066f80-7047-11e9-80ce-66fc808694c9.png) | ![20190506-213931](https://user-images.githubusercontent.com/10606431/57267914-73d77600-7047-11e9-9ea8-311afb8fba8a.png)

**Comment by trwnh** [comment]
Looks like it was finally fixed in latest commits! https://staging.pixelfed.net/p/admin/89932225663078400
