### ISSUE TITLE
Impossible to change one picture on a post.

### ISSUE THREAD

**Issue by MBalensi** [pixelfed/pixelfed#2672]
I tried to create a post with several pictures. One of them was not uploaded correctly, so I tried to delete or replace it. I did not find any way to do this, the only things I could edit on this picture were the description and the filter. To delete it, I had to delete the whole post, with all the other pictures in it.
It would be nice to be able to change, delete or add a picture to an existing post.

**Comment by trwnh** [comment]
Duplicate of #823
