### ISSUE TITLE
TypeError: Cannot read property blurhash of undefined

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2674]
Pixelfed v0.10.10 https://github.com/pixelfed/pixelfed/commit/2ff863fa0064161e772fc7bc73a729d319b9f5d6 / PHP 7.4.15

![pixelfedblurhash](https://user-images.githubusercontent.com/1679025/108606276-2e547c00-7387-11eb-8460-3a71bf19fd6c.png)

**Comment by trwnh** [comment]
i don't think this is a significant issue, it just looks like a post was missing from the discover view and therefore didn't have a blurhash
