### ISSUE TITLE
Operation timed out after 30001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2675]
Pixelfed v0.10.10 2ff863f / PHP 7.4.15

```
ERROR: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) {"exception":"[object] (
Zttp\\ConnectionException(code: 0): cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at /pixelfed/ve
ndor/pixelfed/zttp/src/Zttp.php:169)
```

stacktrace https://pastebin.com/0pMKHTMv

**Comment by jk-na** [comment]
I am also seeing this error, it makes up around 5% of failed jobs since I updated to the last commit 3 or so days ago.

**Comment by trwnh** [comment]
seems to be a standard timeout while fetching a remote resource. the issue would be on the other server which is not responding for at least 30 seconds, at which point pixelfed gives up on fetching.
