### ISSUE TITLE
Firefox can't open this page

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#2678]
Hello,

I can't see the embedded contents from my own instance, they are replaced by the message mentioned on the title. Did i misconfigured something on my server ?

**Comment by dansup** [comment]
@stemy2 Can you view [this](https://dansup.github.io/pixelfed-embed/) fine? We set the `X-FRAME-OPTIONS` header here https://github.com/pixelfed/pixelfed/blob/2ff863fa0064161e772fc7bc73a729d319b9f5d6/app/Http/Controllers/StatusController.php#L127

Can you confirm if that header is being sent with the request?

**Comment by stemy2** [comment]
Yes, the said line is the same as the one defined in my own StatusController.php file, but strangely, the response header is `x-frame-options: SAMEORIGIN`

**Comment by dansup** [comment]
@stemy2 Check your nginx config, make sure you have no `X-Frame-Options` header set!

**Comment by stemy2** [comment]
> @stemy2 Check your nginx config, make sure you have no `X-Frame-Options` header set!

Where is the said config file ? I didn't found it in the nginx config folder.
