### ISSUE TITLE
The refresh token is invalid at HandlesOAuthErrors.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2679]
Pixelfed v0.10.10 https://github.com/pixelfed/pixelfed/commit/2ff863fa0064161e772fc7bc73a729d319b9f5d6 / PHP 7.4.15

```
ERROR: The refresh token is invalid. 
{"exception":"[object] (Laravel\\Passport\\Exceptions\\OAuthServerException(code: 8): 
The refresh token is invalid. at 
/pixelfed/vendor/laravel/passport/src/Http/Controllers/HandlesOAuthErrors.php:26)
```

stacktrace https://pastebin.com/xWXbe8UR

**Comment by trwnh** [comment]
i'm going to close this under the assumption that it's no longer occurring; if it does reoccur, please let me know so i can reopen the issue
