### ISSUE TITLE
[UI][Enhancement] Fixed positioning of CW toggle

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#268]
Toggle jumps around when open or closed, making it hard to easily toggle visibility.

Open | Closed
--- | ---
![image](https://user-images.githubusercontent.com/10606431/41404322-85775a68-6f8c-11e8-9967-32dc0b3ed99a.png) | ![image](https://user-images.githubusercontent.com/10606431/41404327-8c92e1f0-6f8c-11e8-9536-4fca05be6b04.png)

**Comment by dansup** [comment]
Fixed in latest commits
