### ISSUE TITLE
Audience Defaults to Public in a Private Account

### ISSUE THREAD

**Issue by geoidwalker** [pixelfed/pixelfed#2683]
I'm curious if there is any plan to be able to set the default Audience. I changed my account to private and posted a few pictures which to my surprise were public. I can change it manually each time I post - but am I missing a way to make it default to followers only? It always defaults to Public. A quick search on the web seems to indicate this has already been done - maybe only certain instances have that updated code? I am using pixelfed.social. I tried making my account not private and private again but same behavior each time - the audience always defaults to public. 

Pretty new to pixelfed but enjoying so far.

**Comment by dansup** [comment]
Fixed in #2685

**Comment by geoidwalker** [comment]
That was fast! Thanks guys.
