### ISSUE TITLE
Like count does not match

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2687]
Problem still exist and confirmed on main instance

![like22](https://user-images.githubusercontent.com/1679025/109427882-6af52880-79c2-11eb-84b9-711f4b8d886a.png)
![like34](https://user-images.githubusercontent.com/1679025/109427884-6b8dbf00-79c2-11eb-8876-816446ecfc73.png)

Reference to previous issue that was closed. Was going to try and figure it out but didn't see link to commit. 
https://github.com/pixelfed/pixelfed/issues/2610

**Comment by inga-lovinde** [comment]
What's even more interesting, it seems that it depends on the currently logged in user.

In my case:

* User A posted a photo, it got 6 likes;
* When user A looks at the photo page, there is "6 likes" text;
* When user B looks at the photo page, there is "6 likes" text;
* When user A looks at A's profile, there is 6 next to a heart icon;
* When user B looks at A's profile, there is 4 next to a heart icon.

**Comment by akwala** [comment]
The likes count no longer appears when hovering over a pic on the My Profile page.
