### ISSUE TITLE
[UI][Bug] Buttons are not vertically aligned

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#269]
![image](https://user-images.githubusercontent.com/10606431/41404425-cfd83992-6f8c-11e8-8134-1fee2083d376.png)

![image](https://user-images.githubusercontent.com/10606431/41404837-d64ac1e0-6f8d-11e8-95b7-82c87c26935d.png)

In particular:
- The comment button is a little too high compared to the other buttons
- The save button is not visually balanced due to the little coattails on the ribbon.

**Comment by hellcp** [comment]
That's due to comment being "h3" and icons being in "btn-lg" class
