### ISSUE TITLE
Suggestion: Change default license for users

### ISSUE THREAD

**Issue by svoe** [pixelfed/pixelfed#2692]
Hello, 
a user should be able to change the default license for all their pictures or all pictures of a post. At the moment the default license is "All rights reserved" and has to be changed via the advanced settings for every single picture.
This makes it very frustrating to use a different or no license and therefore promotes unnecessary restrictive licensing.

A list of licenses to choose from with a link to explanations additional to the text input would also be nice.

Please excuse mistakes I made. This is my first issue report ever.

**Comment by realpixelcode** [comment]
I think most regular users of social media wouldn't expect that they automatically waive their copyrights by default when uploading photos. Instead, in my opinion, there should be an option to select a profile-wide default licence, but “all rights reserved” should remain the standard.

**Comment by darrinlrogers** [comment]
I have been wanting this feature, as well. It would be useful.
