### ISSUE TITLE
No image preview in profile neither in discover

### ISSUE THREAD

**Issue by samuelortion** [pixelfed/pixelfed#2697]
See [my PixelFed Instance for Instance](https://pix.ortion.xyz/UncleSamulus)
or [discover](https://pix.ortion.xyz/discover)

**Comment by clesauln** [comment]
Few things :
1) check symbolic link to **public/storage** : it should point to **/pixelfed/storage/app/public** with the server rights: **www-data** or **pixelfed** user group
2) check your **app_url** in **.env**, the same of your deployed app
3) Finally run **cache:clear**, **view:clear**, **route:clear** and restart horizon

**Comment by erinarbleizez** [comment]
I have the same problem on a new instance. I have checked the 3 things and it did nothing :/

**Comment by erinarbleizez** [comment]
doing a `composer update` did the trick for me

edit: I was partly right: `composer update` fixed the old image but new image still doesn't have preview :/

**Comment by AnonymousWebHacker** [comment]
> haciendo un `composer update`me hizo el truco
> 
> editar: estaba parcialmente en lo cierto: `composer update`arregló la imagen anterior, pero la nueva imagen aún no tiene vista previa: /

In my case I give Discover, and it stays loading, and it does not show walks
https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/deCXDDqsioCNvHVnCJpEwKxf

https://matrix.to/#/!dSVFUbUBfXIgduyxBO:matrix.org/$1633313198135582TWZJt:matrix.org?via=matrix.org&via=matrix.tdstoragebay.com&via=schuerz.at
