### ISSUE TITLE
Idea: Dynamic albums / Collections

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#270]
While it may be possible to delete images selectively out of a multipost, it would probably be better to instead implement an album system where posts can be removed and added to separate collections or categories. For example, an album of all posts containing concert photography, or for a specific event, etc.

Potential considerations:
- Backend would treat these richer albums as an `OrderedCollection` of `Image` objects, perhaps `Note` attached
- At minimum, one level of nesting should be supported; otherwise, a separate category feature should be implemented as well. (More nesting is entirely arbitrary and would add complexity)
- The "Collections" / "Categories" feature(s) might live as extra tabs on the profile, next to "Posts" and "Saved".

**Comment by dansup** [comment]
@trwnh Deleting a single image in an album/multipost is not possible, it would not federate well since each album is a single Note with multiple attachments. You could use hashtags and 'pin' 6 or 9 posts to a new collections tab 🤔

**Comment by trwnh** [comment]
@dansup I don't think it would require deleting images from a multipost, but rather, changing the structure of it just a bit. For example, right now it is a `Note` with multiple `attachment`. Instead of attaching `Image`, you could attach a `Collection` or an `OrderedCollection` of `Image`, either with an attachment `Note` or attached to a `Note`.

Conceptually, it seems cleaner to attach a `Note` to `Collection`; although it might be possible that e.g. Mastodon expects primarily `Note` objects. But it would be far more preferable to do it the "correct" way and have Mastodon adapt to handle it, as was done with PeerTube. It's also entirely possible that a microblogging application like Mastodon doesn't even *need* to be aware of rich albums, as you could still federate out individual statuses as `Note` with `Image` attached. The JSON to be generated and consumed would be dereferenced eventually.

So, to clarify, the proposed behavior would be as follows:
- Federate statuses as {`Note` with `Image` as `attachment`} (currently consumable by Mastodon)
- Federate arbitrary collections of statuses as {`OrderedCollection` of {`Note` with `Image` attached}}
- Alternatively, federate arbitrary collections of images as {{`OrderedCollection` of `Image`}, with optional `Note` attached.)

Sample dynamic album might look like this:
```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "summary": "Pictures of my cat",
  "type": "Collection",
  "totalItems": 2,
  "items": [
    {
      "type": "Image",
      "name": "A picture of my cat",
      "url": "https://pixelfed.social/storage/m/kjh/cat1.jpg"
      "attachment": [
      {
        "type": "Note",
        "name": "Image Description (optional)".
        "content": "His name is Spot. Spot says hi!",
        "url": "http://pixelfed.social/p/trwnh/276"
      }
    },
    {
      "type": "Image",
      "name": "Another picture of my cat",
      "url": "https://pixelfed.social/storage/m/kjh/cat2.jpg"
    }
  ]
  "attachment": [
    {
      "type": "Note",
      "content": "This is an album containing pictures of my cat. My cat is very cute!
                  <br/>
                  I love cats. If you like cats as well then you will probably
                  appreciate these pictures.",
      "url": "http://pixelfed.social/@trwnh/albums/cat"
    }
  ]
}
```

**Comment by trwnh** [comment]
Upon revisiting, I think this is what the upcoming Collections feature might be handling? Tagging this with the keyword so that it shows up higher in search.

**Comment by ghost** [comment]
It seems that albums can't be deleted? I mean, the UI is there, but they don't actually go anywhere. 😄
