### ISSUE TITLE
Unable to migrate

### ISSUE THREAD

**Issue by zefr0x** [pixelfed/pixelfed#2701]
I get that after [migrating the database](https://docs.pixelfed.org/running-pixelfed/installation.html#setting-up-services):
$ sudo php artisan migrate --force
![Screenshot_20210305_022327](https://user-images.githubusercontent.com/65136727/110044439-2ec31e80-7d5a-11eb-8f4f-93ee4ef6de78.png)

I used the dev brach on Linux lubuntu with MariaDB.

**Comment by dansup** [comment]
You need to set `DB_CONNECTION=mysql` in .env, the error screenshot lists sqlite as the DB_CONNECTION
