### ISSUE TITLE
Federation doesn't work

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#2702]
Hello,

According my config file, federation is active, but i only see local posts. what have i to do to see posts from instances i federate ?

```
ACTIVITY_PUB=true
AP_REMOTE_FOLLOW=true
AP_INBOX=true
AP_SHAREDINBOX=true
AP_OUTBOX=true
ATOM_FEEDS=true
NODEINFO=true
WEBFINGER=true
```

**Comment by samuelortion** [comment]
I have the same problem.

**Comment by trwnh** [comment]
did you run `php artisan instance:actor`

**Comment by samuelortion** [comment]
Yes I did.

**Comment by stemy2** [comment]
It says "instance actor already exists".

**Comment by chee** [comment]
have you followed someone, and then waited for them to post a photograph? https://blog.soykaf.com/post/how-federation-works/

**Comment by okpierre** [comment]
@stemy2 not all federation features works but it does do some. There are many bugs with Pixelfed federation that needs to be worked out.
