### ISSUE TITLE
Update to config/services.php

### ISSUE THREAD

**Issue by wisemonkey** [pixelfed/pixelfed#2704]
While using MAILGUN through API.
config/services.php need to be manually updated with EU endpoint.

Suggested solution:
update config/services.php to:
```
    'mailgun' => [
        'domain' => env('MAILGUN_DOMAIN'),
        'secret' => env('MAILGUN_SECRET'),
        'endpoint' => env('MAILGUN_ENDPOINT'),
    ],

```

And then .env can be added with:
**`MAILGUN_ENDPOINT=api.eu.mailgun.net`**

This way further git pull doesn't cause file mismatches.

**Comment by dansup** [comment]
Send a PR please!
