### ISSUE TITLE
Clicking on "Collections" breaks buttons

### ISSUE THREAD

**Issue by Nesaijn** [pixelfed/pixelfed#2728]
When looking at a profile with the default view on "POSTS" and then clicking on "COLLECTIONS" it changes to the collections but then I can't switch back to posts. The button does not work anymore. Same goes for the follow button, three dots button on the profile, "Followers" count and "Following" count.

On pixelfed.social

**Comment by dansup** [comment]
@Nesaijn Which profile and browser are you using?

**Comment by Nesaijn** [comment]
@dansup I am using the Brave Browser. I also just tried the Microsoft Edge Browser and got the same result.
What exactly do you mean with "which profile"? In case you want to know the pixelfed profile where that happend, it happens on every profile I tried to recreate the bug. The profile where I noticed the bug is [manga.art](https://pixelfed.social/manga.art)

Edit:
Also just tried it with Firefox. Same result.

**Comment by tjiho** [comment]
I confirm the issue. In fact it not happens every time. In the Firefox console I have the following error when it happens:
```
TypeError: t is undefined
    destroy https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    b https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    b https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    b https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    b https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    b https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    b https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    w https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    C https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    C https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    C https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    C https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    C https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    C https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    C https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    C https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    C https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    C https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    Fi https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    _update https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    r https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    get https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    run https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    cn https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    tt https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
    Je https://pixelfed.social/js/vendor.js?id=a818775c694ed2a103e9:1
vendor.js:1:125823
```

**Comment by tjiho** [comment]
To force the bug to appear: 
- refresh the profile
- click on "follow" or "unfollow" button
- click on collections
- then "post" button either tree dots button either "follow" button stop working

**Comment by xundeenergie** [comment]
I recognized this on firefox mobile on my Huawai P30.

Clicking on  Collections, i get "No collections yet" and than i stuck in collections. No way back to Posts. Have to reload the whole site.

At the same time on Firefox on my laptop, it shows my collections.

**Comment by xundeenergie** [comment]
Making the Browserwindow on my laptop that small, that responsive design for smartphonse is set, it works how designed.
Choosing "Always get desktop-version" on my smartphone keeps the UI broken as described above.

**Comment by xundeenergie** [comment]
I can't find collections any more.
Only creat-button for collections still exist. And it opend an existing collection, not a nee one.

Are collections dropped?

**Comment by trwnh** [comment]
Collections aren't dropped, but this issue as filed cannot be reproduced. All buttons work fine in Firefox Mobile with "Desktop mode" enabled even if I follow/unfollow the profile first.
