### ISSUE TITLE
Compress photos mozjpg to improve loading/performance and increase space available for users

### ISSUE THREAD

**Issue by xunil89** [pixelfed/pixelfed#2750]
Good morning wouldn't it make sense to introduce mozjpg compression by default? It would benefit the servers having less data load both in transmission and in storege, and taking into account that all instances live with donations optimizing space and consumption would be great, right?

**Comment by xunil89** [comment]
https://github.com/mozilla/mozjpeg

**Comment by dansup** [comment]
@xunil89 jpegOptim and other image optimization tools are already implemented.

**Comment by xunil89** [comment]
What about the avif format? I tried uploading an image but it's not supported yet. Will it be implemented?
