### ISSUE TITLE
Unify the settings look

### ISSUE THREAD

**Issue by hellcp** [pixelfed/pixelfed#276]
Make settings so they have elements in constant place, have constant width, so they are easier to navigate and understand between particular views.

Some mock-ups :D 
![zrzut ekranu z 2018-06-15 14-09-51](https://user-images.githubusercontent.com/30577011/41467213-df32d694-70a5-11e8-8104-21068fe2be91.png)
![zrzut ekranu z 2018-06-15 14-07-37](https://user-images.githubusercontent.com/30577011/41467212-df111e82-70a5-11e8-8f3c-f78d80e49522.png)
![zrzut ekranu z 2018-06-15 14-15-35](https://user-images.githubusercontent.com/30577011/41467384-9f12076e-70a6-11e8-903c-a1d4eda99386.png)

**Comment by mkljczk** [comment]
‘Submit’ button definitely needs to be placed like on your mockups

**Comment by trwnh** [comment]
While we're on this subject: there needs to be a better placement of the sidebar on mobile layouts. It takes up way too much space, almost an entire page: [image](https://user-images.githubusercontent.com/10606431/41477228-45da1c58-7089-11e8-9524-92b4a100cab6.png)

For that matter, it might also be a good idea to collapse some settings pages together:
- "Avatar" should be included with "Profile"
- "Password" and "Email" should be collapsed into a generic "Account" settings page.

**Comment by hellcp** [comment]
For mobile we could go with default settings page with all those links and inside links those views without sidebar menu with "go back" button (imo the best way to implement this is without JS too).

**Comment by dansup** [comment]
@hellcp I like it! What about the /site/ pages like https://pixelfed.social/site/about ? They use the same layouts.

**Comment by hellcp** [comment]
Actually, maybe we can drop titles altogether, selected tab already functions as a title, and considering the layout every pixel is valuable.

At the same time, that title makes sense on mobile, idk.

Either way, all the pages created with that layout require some work :D
