### ISSUE TITLE
Docker Installation problem

### ISSUE THREAD

**Issue by gensisco** [pixelfed/pixelfed#2764]
Hi , 
I have installed pixelfed with docker  but i have some  problems 
I can't login or register i'm testing it locally using 0.0.0.0:8080 it redirects me to real.domain:8080/register ,
and the main page in 0.0.0.0:8080 shows " 
```
Sorry, this page isn't available.
The link you followed may be broken, or the page may have been removed. Go back to Pixelfed.
"
```
how can i fix these problems i hope you help to run my instance

**Comment by dansup** [comment]
@igensis Please make sure `APP_URL` and `APP_DOMAIN` environment variables are set.

**Comment by gensisco** [comment]
@dansup id o the same everytime the same result and same error 
and the installing process without docker is too hard
i failed many times can you help me
