### ISSUE TITLE
Moderation tools broken (again)

### ISSUE THREAD

**Issue by jaranta** [pixelfed/pixelfed#2765]
I was trying to delete a user on my instance after I noticed them spamming. I noticed that the "Delete User" has no effect. The other moderation tools (e.g. trying to unlist their posts) also have no effect.

This is on an instance running v0.10.10, hosted by Spacebear.

**Comment by dansup** [comment]
@jaranta Please confirm that Horizon is running, as most of the user deletion process happens in a background job. Once you initiate the Delete User action, a message is displayed on the profile until its fully deleted. Unlisting posts only affects future posts created by that user.
