### ISSUE TITLE
Many lines aren't localized and are not available for translation

### ISSUE THREAD

**Issue by WerySkok** [pixelfed/pixelfed#2766]
I found that very few lines are translated into Russian, then I checked the repo and found that only few lines are available for translations according to english localization files.
I'd like to see that all of the lines could be translated.

**Comment by forenta** [comment]
+1
Given the prevalence of Pixelfed, I was surprised that the translation was so limited and wanted to get to work on the German language translation as well.

In its current form, with maybe 2/3 translated parts, it really makes a bad impression, unfortunately.

**Comment by dansup** [comment]
Fixed in latest commits! Visit [translate.pixelfed.org](https://translate.pixelfed.org) to contribute translations!

**Comment by forenta** [comment]
Thank you oh-so-much for your work once more!
