### ISSUE TITLE
Error when trying to edit a post

### ISSUE THREAD

**Issue by dnno** [pixelfed/pixelfed#2777]
Currently I cannot edit a post, when I use the respective link in the pixelfed ui:

![Bildschirmfoto 2021-06-02 um 09 40 28](https://user-images.githubusercontent.com/2003552/120443099-9a7f4c80-c386-11eb-9ea3-72630e30bd86.png)

**Comment by inthedarkwelive** [comment]
I have the same problem. Edit function works on some posts, while on other posts this error message appears, regardless of the chosen browser (Safari on iOS, Opera & Firefox on Windows 10).

**Comment by dansup** [comment]
@dnno @inthedarkwelive This has been fixed on pixelfed.social.

**Comment by ghost** [comment]
How could this be fixed? I have the same issue on our self-hosted instance (latest dev branch).
