### ISSUE TITLE
Error message at the bottom of the timeline

### ISSUE THREAD

**Issue by jerrykan** [pixelfed/pixelfed#278]
I've just registered a new account on pixelfed.social and at the bottom of my timeline feed there is an error message

URL: https://pixelfed.social/timeline (logged in)
![Timeline](https://user-images.githubusercontent.com/377632/41495999-05a29cf6-7178-11e8-8a27-d418f0544969.png)
(Ignore the Search bar halfway down the image, it is a result of using the Firefox Screenshot Node feature) 

I haven't uploaded any images yet, so I'm not sure if this is the cause of the error.

**Comment by hellcp** [comment]
Yeah, I already fixed that with #273

**Comment by jerrykan** [comment]
Ok, sorry for wasting your time ;)
