### ISSUE TITLE
Cannot access admin

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#2780]
When trying to access admin panel I get the error something went wrong on the new version 0.11.0

**Comment by yodahome** [comment]
Same issue here, since the update I get the same message whenever I try to access the admin dashboard.

**Comment by dansup** [comment]
Did you run the [post deployment commands](https://github.com/pixelfed/pixelfed/releases/tag/v0.11.0)?

**Comment by ghost** [comment]
@dansup  that worked thanks for pointing out! However messages aren’t working yet.
