### ISSUE TITLE
PHP Deprecated:  Unparenthesized

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2781]
Error message for v0.11.0

`PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /pixelfed/app/Util/Lexer/PrettyNumber.php on line 17" while reading response header from upstream`

**Comment by dansup** [comment]
Fixed in #2787
