### ISSUE TITLE
 Unparenthesized a ? b : c ? d : e is deprecated error

### ISSUE THREAD

**Issue by Casuallynoted** [pixelfed/pixelfed#2784]
I'm getting this error when trying to access media via Pixelfed:

2021/06/05 19:42:54 [error] 1324#0: *1309 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Unparenthesized a ? b : c ? d : e is deprecated. Use either (a ? b : c) ? d : e or a ? b : (c ? d : e) in  /var/www/app/Util/Lexer/PrettyNumber.php on line 17" while reading response header from upstream, client: 192.168.1.254, server: pixelfed.instance, request: "GET /i/admin/dashboard HTTP/2.0", upstream: "fastcgi://127.0.0.1:9281", host: "pixelfed.instance", referrer: "https://pixelfed.instance/"

It seems to be a change in more recent versions of PHP. I'm using PHP 7.4.19.

**Comment by dansup** [comment]
Fixed in #2787
