### ISSUE TITLE
DM error - I got a 404 error on the chat page

### ISSUE THREAD

**Issue by tjiho** [pixelfed/pixelfed#2792]
Hi ! 
I use pixelfed.social.
A friend sent me a message yesterday. I am unable to see it. When I go to the conversation page I have a 404 error "Sorry, this page isn't available."

![image](https://user-images.githubusercontent.com/12885430/121166286-3b6f7b00-c851-11eb-98ed-113422ffaf8f.png)

and then when clicking on 'dm':

![image](https://user-images.githubusercontent.com/12885430/121166405-52ae6880-c851-11eb-8ee0-9504ae1109a6.png)

But for another conversation (without message since a long time) the conversation is correctly displayed.

**Comment by dansup** [comment]
@tjiho This has been fixed on pixelfed.social.

**Comment by ghost** [comment]
when can we send dm public distribution? I’m using cloudron and as the cloudron app packager informed not able to send direc messages I’m not using pixelfed.social I’m using my own website will this be fixed in future version or not ?
