### ISSUE TITLE
DOMException: Failed to execute 'querySelector' on 'Document': The provided selector is empty

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2793]
Pixelfed v0.11.0 / PHP 7.4.20

Unable to view content
Above error occurs when clicking on **see post**

![pixelfed-sensitive-content](https://user-images.githubusercontent.com/1679025/121215480-0dd50280-c84e-11eb-9ffa-901eb598c568.png)

**Comment by dansup** [comment]
Do you have a link to the post in question? Without more information, I cannot reproduce this.

**Comment by okpierre** [comment]
@dansup the issue does not show up in timeline feed only when viewing the individual post.

Try this link: `https://mstdn.beer/@reima/106401268145114336`
