### ISSUE TITLE
Recommended recovery path for an instance w/ DB loss or corruption

### ISSUE THREAD

**Issue by SMJ** [pixelfed/pixelfed#2794]
When you have all image and avatar assets still on disk and your database becomes corrupt or lost what is the recommended recovery path? Would it be possible to associate these images with their original creators on an instance from the command line?

**Comment by dansup** [comment]
It really depends on how much data is intact. If you have profile_ids, you can determine the ownership of media uploads, though unless you have the `media` table it would be hard to determine the `status_id` of media still on disk.

How did it get corrupted and what exactly is corrupt?
