### ISSUE TITLE
Filter notifications by type

### ISSUE THREAD

**Issue by ahangarha** [pixelfed/pixelfed#2796]
It would be nice if PixelFed supports notification filtering based on their type, very much like what Mastodon does. So, one can check only comments instead of exploring whole of notifications to find them.

**Comment by zefr0x** [comment]
I sugges using formats like this:
1) %s, %s, %s and 13 others liked you.
2) %s, %s and %s shared you.
2) %s and %s commented on you post.

We should just show some of the images on top of each other (like in mastodon when you replay or reblog a post)
![Screenshot_20211223_083932](https://user-images.githubusercontent.com/65136727/147193656-b9fc570d-5074-4c73-ba16-ff4775735d67.jpg)

when you  hover on a username it will show you the image and some simple informations about the user.

If you wanted to show all the usernames you are able to  click on the notification to expand it to a list of usernames.

**Comment by dansup** [comment]
This is now supported in the Metro 2.0 UI!

**Comment by ahangarha** [comment]
I wanted to say thanks to the person suggested this feature and realized it was me :laughing:

So a big thanks to all the contributors and Danial in particular. Well done :+1:
