### ISSUE TITLE
Federate all instance to Mastodon

### ISSUE THREAD

**Issue by AnonymousWebHacker** [pixelfed/pixelfed#2814]
### PeerTube
In the case of peertube, all instances have a default user to follow an instance completely, example
`peertube@peertube.domain.com`
With this, when following it from a Mastodon instance, all the videos uploaded to the PeerTube instance are automatically published in Mastodon. 
Regardless, that some other user follows one of the accounts of that instance of peertube

### Pixelfed
- I can follow pixelfed users from Mastodon ,example `user@pixelfed.domain.com`
but , is there any way i can follow the instance in its entirety?That everything that is published in Pixelfed, be federated to Mastodon?

**Comment by plant7403** [comment]
If ActivityPub(pretty sure this is the name) is turned on you should be able to reach that instance from any other ActivityPub enabled instance
If I go and search my pixelfed nick through mastodon I can find it, and vice versa
But it seems it was not completely implemented, I can find my account for example, but I can't see my posts 😥
(But get subscribed and get the notification of a new subscriber)

**Comment by AnonymousWebHacker** [comment]
@xxxcrow In order to view your posts on Pixelfed from Mastodon, you have to follow your Pixelfed account. The previous publications, the time do not come out, but the new ones in the future if they would.

- If you want to start an old publication, you can go to search and put the full URL of the post, and if it would come out.

- As for following an instance completely, I asked to @dansup , and he says that this has not been implemented yet, but that he plans to add

**Comment by plant7403** [comment]
@AnonymousWebHacker interesting, and anyway cool 😄
