### ISSUE TITLE
Can't authorize third party app

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#2816]
Hello,

I tried to authorize my own instance for some third party apps (tried with pixeldroid and fedilab), but i can't because of this error:

		

**Something went wrong**

_We cannot process your request at this time, please try again later. Go back to Pixelfed._

It works on flagship instance though.

**Comment by tophers** [comment]
is oauth enabled on your instance? fairly certain it needs to be enabled for the apps to use the api. 
https://docs.pixelfed.org/technical-documentation/api-v1.html#authorization

**Comment by stemy2** [comment]
I don't have any file called ".env", where must i add "OAUTH_ENABLED=true" ?

**Comment by dansup** [comment]
@stemy2 Did you run `php artisan passport:client --personal`?

**Comment by stemy2** [comment]
It works now !
