### ISSUE TITLE
How to enable config cache ?

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#2818]
Hello,

To modify server settings with the web interface, i have to "Add ENABLE_CONFIG_CACHE=true in my .env file". But there are many env files, to wich one am i supposed to add a such parameter ?

**Comment by ghost** [comment]
it’s on env.production you need to add it newly there’s nothing to change on parameters you need to simply open env.production and go to the bottom of it add ENABLE_CONFIG_CACHE=true

Don’t forget these 

Post Deployment

After updating your instance to v0.11.0, please run the following commands:

composer install

php artisan migrate --force

php artisan config:cache

php artisan route:cache

php artisan cache:clear

**Comment by stemy2** [comment]
Where is this file ? I looked in some folders without finding it.

**Comment by ghost** [comment]
https://docs.pixelfed.org/technical-documentation/env.html#app

**Comment by stemy2** [comment]
It doesn't answer to my question, what's the name of the file i must modify and where is it located ?

**Comment by ghost** [comment]
File name is env.production

Where you can find i actually have no idea try to search env.production or env docker I i used cloudron to install it and it has access to those folders 

note : cloudron doesn’t give access to every folders and files as if you installed pixelfed by raw cloudron only allows you to access few files and folders that includes env production

**Comment by stemy2** [comment]
I tried these commands but non of them gave me any results.

find env.production
find -name *env*.production                 
find -name env.production
find env.production*

**Comment by ghost** [comment]
How did you install pixelfed ? Raw installation or any other way ? 

If docker try to search 
env.docker inside config folder

**Comment by stemy2** [comment]
With Yunohost.

**Comment by ghost** [comment]
Please contact Yunohost  support / help on how to find the env file or go through the forums of Yunohost related to pixelfed app

as per search on GitHub Yunohost 

/var/www/pixelfed/.env
or 
pixelfed_ynh/conf/.env

production.env = .env
Both are same

**Comment by stemy2** [comment]
Hello, i found the said file, but there's no parameter named "ENABLE_CONFIG_CACHE", and adding it manually does nothing.

**Comment by ghost** [comment]
For yunohost once after cd to the path

var/www/pixelfed

and then run 

nano .env

After go to the bottom of the file and add the following 

ENABLE_CONFIG_CACHE=true

save the .env exit 

and then run

php artisan config:cache
pho artisan cache:clear

**Comment by stemy2** [comment]
It works !
