### ISSUE TITLE
You're All Caught Up! ???

### ISSUE THREAD

**Issue by prolibre** [pixelfed/pixelfed#2819]
On v0.11.0 (pixelfed.social)

For me, I've noticed that when I see the message "You're All Caught Up!" ... that's not the case at all. I have lots of photos that I hadn't seen that show up when I click on : "view older posts".

Thanks to the developers

**Comment by azuredusk10** [comment]
I get the impression it only shows you images from the last 24 hours by default. Maybe the message could be a bit more explicit if that’s the case, because I was confused for the same reason as you the first few times I saw it.

**Comment by moellus** [comment]
Option to disable this feature please

**Comment by dansup** [comment]
Fixed in latest commits! We have removed this feature!
