### ISSUE TITLE
Trying to get property 'id' of non-object at /pixelfed/app/Util/ActivityPub/Inbox.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2821]
Pixelfed v0.11.0 / PHP 7.4.20

ERROR: Trying to get property 'remote_url' of non-object {"userId":55,"exception":"[object] (ErrorException(code: 0): Trying to get property 'remote_url' of non-object at /pixelfed/app/Http/Controllers/SearchController.php:330)

stacktrace https://pastebin.com/SRz5rbRE

**Comment by dansup** [comment]
Fixed in latest commits!
