### ISSUE TITLE
Undefined index: id at /pixelfed/app/Jobs/InboxPipeline/InboxWorker.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2822]
Pixelfed v0.11.0 / PHP 7.4.20

ERROR: Undefined index: id {"exception":"[object] (ErrorException(code: 0): Undefined index: id at /pixelfed/app/Jobs/InboxPipeline/InboxWorker.php:150)

stacktrace https://pastebin.com/tbjyWtBw

**Comment by dansup** [comment]
Fixed in latest commits!
