### ISSUE TITLE
Trying to access array offset on value of type null at /pixelfed/app/Jobs/InboxPipeline/InboxValidator.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2823]
Pixelfed v0.11.0 / PHP 7.4.20

ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /pixelfed/app/Jobs/InboxPipeline/InboxValidator.php:226)

stacktrace https://pastebin.com/wF9DFpZU

**Comment by dansup** [comment]
Fixed in latest commits!
