### ISSUE TITLE
Trying to get property 'id' of non-object at /pixelfed/app/ Util/ActivityPub/Helpers.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2824]
Pixelfed v0.11.0 / PHP 7.4.20

ERROR: Trying to get property 'id' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'id' of non-object at /pixelfed/app/
Util/ActivityPub/Helpers.php:384)

stacktrace https://pastebin.com/RMNiQzD6

**Comment by dansup** [comment]
Fixed in latest commits!
