### ISSUE TITLE
Incorrect image orientation in Photo Preview

### ISSUE THREAD

**Issue by jerrykan** [pixelfed/pixelfed#283]
I've noticed that when I upload a file via the web interface that the orientation of the photo in the Photo Preview does not match how the image is presented when it is posted. The Photo Preview feature should show the orientation that the photo will have once posted.

Semi-related issue... sometimes the orientation of photo stored in the image metadata is incorrect. It would be useful if the image could be rotated manually during the upload process to override the incorrect information stored in the metadata.

**Comment by dansup** [comment]
@jerrykan Once uploaded, the image is optimized and gets properly re-orientated based on the metadata/exif before the exif data is removed.
