### ISSUE TITLE
Can't save my settings

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#2834]
Hello,

I tried to change some settings in my admin page, but after clicking on "save", i get this error message. An it happens even if i don't change anything. According my web inspector, this is an internal server error.

**Something went wrong

We cannot process your request at this time, please try again later. Go back to Pixelfed.**

**Comment by ghost** [comment]
Please be specific on what are the settings and what you tried to save

**Comment by stemy2** [comment]
Added more precision in the original message.

**Comment by ghost** [comment]
Something went wrong are not server error pixelfed is yet on development and has lots more miles to go through with fixing bugs hence keep @dansup informed on this however fixes can take up to 6 months or year

**Comment by dansup** [comment]
@stemy2 Are you running the latest commits? The latest version has a new `COPY DIAGNOSTIC DETAILS` link on the *Something went wrong* error page that you can use & decrypt on the Diagnostics page in the admin dashboard. That should provide more insight into what is going wrong.

**Comment by dansup** [comment]
@stemy2 Did you by chance check `Enable Mobile APIs` ? If so, run `php artisan passport:keys` and try again. Will fix this in the next release!

**Comment by dansup** [comment]
Fixed in latest commits!
