### ISSUE TITLE
Feature request: Enlarge on click

### ISSUE THREAD

**Issue by proailurus** [pixelfed/pixelfed#2839]
Pictures are already loaded in full resolution and you can view this by right clicking and opening in new tab.

It would be neat if a simple click on the image would either enlarge it or open it in a new tab.

There is talk about a button to enlarge here
https://github.com/pixelfed/pixelfed/issues/2174
but I don't see any, browsing as not logged in user.

Example:
https://pixelfed.social/p/nafnlj/316255327760814080

**Comment by dansup** [comment]
Fixed in latest commits!
