### ISSUE TITLE
Pixelfed 0.11.0 - Force the MediaStoragePipeline to be re-run

### ISSUE THREAD

**Issue by cyberczar** [pixelfed/pixelfed#2841]
Is there any way to force the `App\Jobs\MediaPipeline\MediaStoragePipeline` to be re-run to store any locally stored media back into AWS/ S3?

I had migrated my cloud storage provider from Wasabi to Linode and there was an issue with my S3 compatible access tokens causing me to have to issue new tokens.

Now I've got a bunch of media stored locally on `/usr/share/webapps/pixelfed/storage/app/public` that I'd like to be moved/ uploaded to S3.

**Comment by dansup** [comment]
Fixed in latest commits!

**Comment by TheEnbyperor** [comment]
How does one actually do this? "Fixed in latest commits!" with no details on *how* it was fixed isn't particularly helpful.
