### ISSUE TITLE
Broken thumbnail for reply view

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2851]
Pixelfed v0.11.0 / PHP 7.4.20

This happens when clicking on view for a notification
ie: @testing liked your post [view]

Thumbnail is broken for both desktop and mobile view

![pixelfedthumbnailreplyblade](https://user-images.githubusercontent.com/1679025/125204407-279da700-e24b-11eb-9a29-fef4854adb5f.png)

**Comment by dansup** [comment]
@okpierre This is fixed in the latest commits!
