### ISSUE TITLE
Can't upload a video [unexpected error occurred]

### ISSUE THREAD

**Issue by plant7403** [pixelfed/pixelfed#2852]
Hi, I couldn't find any support page on pixelfed.social 😅
Uploading is already too hard in pixelfed
But now I can't upload a low-res video with length of 1:40
Decreasing bitrate let the video upload, but it shows only the first frame and plays the sound 😄
Shorter videos are ok, loading without a problem

**Comment by weex** [comment]
A help page is linked from the pixelfed.social if you're not logged in, but I'm waiting for a confirmation email to check when logged in. If that doesn't fix the help link part, please make a separate issue or reply here and I will.

What is the format of your video?

**Comment by weex** [comment]
Funny that the software doesn't send an email confirmation automatically, guess that might be an anti-bot tactic. Anyway, I saw from the help pages which is linked at the bottom of the page: https://pixelfed.social/site/kb/sharing-media that it must be mp4. Is that your format?

**Comment by plant7403** [comment]
@weex yeah, mp4 is my format, but strange thing that pixelfed(all instances documentation) doesn't provide any information more than "mp4"
By now I checked different videos with different file size, resolution, aspect ratio
I only can't upload videos that are >200mb

**Comment by weex** [comment]
Pixelfed uses laravel-ffmpeg and there don't seem to be any filters on specific types so it probably supports many formats under the mp4. The docker config has a max_file_size of 64 mb but that can be changed easily. I guess it'd be good to add the limit to the help site.

**Comment by plant7403** [comment]
@weex oh! That's why!
Yeah, add limit to the documentation, AND probably add some error message instead of "unexpected error occurred"
🤝

**Comment by plant7403** [comment]
@weex whoah, it seems to be the case, 60mb video is uploading, 65mb not
