### ISSUE TITLE
 Feature request: Increase the Media Description text limit

### ISSUE THREAD

**Issue by sajeshcherian** [pixelfed/pixelfed#2854]
Currently, the text for media descriptions is limited to 140 characters. It would be nice to have it the same as on Mastodon, i.e. 1500 characters. I keep hitting the limit, and sometimes it's hard to describe a photo in 140 characters.

I know the caption provides 2000 characters, but Media Description is an accessibility feature, and it will be weird to describe the photo in captions.

(I tried finding any similar issues, but didn't find anything, so filing it as a new issue)

**Comment by dansup** [comment]
Fixed in latest commits!
