### ISSUE TITLE
A "Material Design" look [PROTOTYPE]

### ISSUE THREAD

**Issue by Aurnytoraink** [pixelfed/pixelfed#287]
Hi **everyone**,
I like the UI of PixelFed but I asked myself how the website can be with *"material design"*.
So I've done this UI during my free time.

I need to finish some details and I will add a *"Night mode"* later. But you can still see it.

Here is a **preview**:
![export](https://user-images.githubusercontent.com/28545669/41512413-41a0d342-7288-11e8-8fe1-fff63a035415.png)

What do you think ? If you want you wan **download** the project and modify it.

To-do:

- [x] Do a prototype
- [ ] Do a prototype with all pages (working progress)
- [ ] Finish the last details
- [ ] Add *"Night mode"*
- [ ] Be validated by the moderate team
- [ ] Try to code it in **CSS**
- [ ] *Maybe do an Android application* (not sure)

<br>
<br>
<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />Ce(tte) œuvre est mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Licence Creative Commons Attribution -  Partage dans les Mêmes Conditions 4.0 International</a>.

PS: I'm not a real designer, I just try to create some things.

You can download stuff here:
[MaterialFed.zip](https://github.com/dansup/pixelfed/files/2109445/MaterialFed.zip)

**Comment by dansup** [comment]
@RavengamerSpace Great work, the only thing I would recommend is to remove the rounded corners!

**Comment by dansup** [comment]
This would be an alternate theme, users could pick between the current design (default) or this for example. It could set the standard for custom themes which is a great feature.

**Comment by Aurnytoraink** [comment]
Ah, because I loved that. Maybe I will do 2 another version:

- One with soft round corner
-  Another with no round corner

**Comment by dansup** [comment]
@RavengamerSpace A slight rounded corner would match the existing theme, I think thats a good idea!

**Comment by Aurnytoraink** [comment]
Okay, I've quickly modify him and now he looks like this:
![soft round corner](https://user-images.githubusercontent.com/28545669/41512593-74bba4e8-728b-11e8-9e1a-3401599a8369.png)

**Comment by hellcp** [comment]
Considering that we would love to have easy capability to update and continue using that kind of theme, it would be nice to make it as variable file for bootstrap:

Documentation (honestly scarce):

https://getbootstrap.com/docs/4.0/getting-started/theming/

List of variables available:

https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss

It will make out lifes easier while updating to newer version of bootstrap in the future :D

**Comment by Aurnytoraink** [comment]
@hellcp Thanks, but actually I'm not coding. First I do the prototype and then I will code.

Actually I just ask to people what they thinks, adjust my prototype and after I will start his development.

If you want to know more about my prototype, you can download the zip file which countains the Gravit design project

Here is a look of what I do:

![2018 06 18-00 16](https://user-images.githubusercontent.com/28545669/41512649-fb02591a-728c-11e8-8971-dbf55dcb4ea7.png)

**Comment by hellcp** [comment]
Well, what I suggested is not really coding, it's writing multiple numbers and variables in list :D 
But sure, I get it, it's better to have a clear idea what to do in the future

**Comment by faissaloo** [comment]
This would be great for the Android app, would be more consistent with other apps on the platform

**Comment by Aurnytoraink** [comment]
@faissaloo Why not ? 😃 
I will add this to my To-Do list

**Comment by Aurnytoraink** [comment]
Okay, so I re-modify the prototype and I do new render.
What do you think ?

Timeline:

![timeline](https://user-images.githubusercontent.com/28545669/41536598-66ca0930-7306-11e8-9350-015ef750511d.png)
<br>
<br>
Discover (I know that I've make a mistake):

![discover](https://user-images.githubusercontent.com/28545669/41536625-768173ae-7306-11e8-946d-5aa9aade2432.png)
<br>
<br>
Activity:

![activity](https://user-images.githubusercontent.com/28545669/41536645-83c6d590-7306-11e8-9d97-14fb732f68bd.png)

**Comment by moshpirit** [comment]
I love the design! Until this is completed, @dansup could you reduce the height of the top bar? It feels too big. Instagram's is similar but the icon logo is smaller and the bar gets minimized when people scroll down.

[![](https://i.imgur.com/DlsKGN9.png)](https://i.imgur.com/DlsKGN9.png)
