### ISSUE TITLE
Extra spacing before URL

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2873]
Pixelfed v0.11.0 / PHP 7.4.20

Extra spacing before the URL in timeline view

![pixelfed-post](https://user-images.githubusercontent.com/1679025/128767347-32d40961-c849-48f4-84d9-73bf9d58c8af.png)

**Comment by wakest** [comment]
this one has been around for a ling while and I always wondered what was up with it.

**Comment by okpierre** [comment]
> this one has been around for a ling while and I always wondered what was up with it.

I guess I haven't noticed until now, thanks for confirming.

**Comment by dansup** [comment]
Fixed in latest commits!
