### ISSUE TITLE
[feature request] Steps to make Pixelfed safer, especially for children and young people.

### ISSUE THREAD

**Issue by linux-lukas** [pixelfed/pixelfed#2874]
The possibility to deactivate that anyone can write to a user, to deactivate the number of followers and the number of Following are good possibilities to prevent cyber-grooming, for example, and to weaken the "social media pressure", but perhaps one or the other possibility to strengthen Pixelfed in terms of steps for the protection of children and young people in the media could still be considered.

I could imagine, for example, that a content warning (CW), as already implemented on Mastodon, could be incorporated into Pixelfed, so that, for example, young creators from YouTube, Twitch or TikTok, who switch to the Fediverse on Pixelfed, could identify advertising contributions as such in order to sensitize young people.

In the Federal Republic of Germany, there is a " German Interstate Agreement on the Protection of Minors in the Media", which could perhaps serve as a good guideline for mechanisms in Pixelfed: https://www.kjm-online.de/fileadmin/user_upload/Rechtsgrundlagen/Gesetze_Staatsvertraege/JMStV_geaend._durch_19._RAEStV.pdf

**Comment by Lukas2112** [comment]
I could imagine, for example, that a content warning (CW), as already implemented on Mastodon, could be incorporated into Pixelfed, so that, for example, young creators from YouTube, Twitch or TikTok, who switch to the Fediverse on Pixelfed, could identify advertising contributions as such in order to sensitise young people.

**Comment by Lukas2112** [comment]
In the Federal Republic of Germany, there is a " German Interstate Agreement on the Protection of Minors in the Media", which could perhaps serve as a good guideline for mechanisms in Pixelfed: https://www.kjm-online.de/fileadmin/user_upload/Rechtsgrundlagen/Gesetze_Staatsvertraege/JMStV_geaend._durch_19._RAEStV.pdf

**Comment by spaceottercode** [comment]
Show Follower Count, Show Following Count have been added to PixeFed. PixelFed has added Contains NSFW Media option and users can block other users. This may satisfy most but not all of the points discussed in the original posts when it was first created.
