### ISSUE TITLE
Suspicious activity screen immediately after innocuous comment

### ISSUE THREAD

**Issue by weex** [pixelfed/pixelfed#2876]
I commented on [this post](https://pixelfed.social/p/dansup/330761128516915200) and it happened quick but I think went to a 404 page, then tried to see that my comment went through and was shown this.

Didn't get a chance to check out until now, an hour later, but I couldn't see what might have triggered the moderation.

![pixelfed-suspicious-activity](https://user-images.githubusercontent.com/38776/129107614-c227aca3-c91c-4fd3-8bd2-e1350fd95137.png)

**Comment by dansup** [comment]
Fixed in latest commits!
