### ISSUE TITLE
Like showing in one view but not in another

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2883]
Pixelfed v0.11.0 / PHP 7.4.20

In this view the photo shows LIKE
https://www.example.com/i/web/profile/_/112233445566778899

In this view same photos do not show LIKE
https://www.example.com/i/web/post/_/123456789012345678/123456789012345678

This causes confusion when someone visits the profile looking for other photos and then can accidentally unlike by clicking on them again

**Comment by hansw-nlo** [comment]
That can be merged with my bug entry. I still do not see likes in the profile view.

**Comment by hansw-nlo** [comment]
#2795 to be sure.

**Comment by dansup** [comment]
Fixed in latest commits!
