### ISSUE TITLE
Remote avater can't show

### ISSUE THREAD

**Issue by YoheiZuho** [pixelfed/pixelfed#2884]
S3 is enabled, but Remote Avatar is not enabled.
Do I need to configure something?
Please let me know.

**Comment by okpierre** [comment]
I believe it relies on everything filled out for **filesystem**

https://docs.pixelfed.org/technical-documentation/env.html#filesystem

Can anyone confirm what is required?

**Comment by YoheiZuho** [comment]
I think the "Filesystem" settings on my server are correct.
```
PF_ENABLE_CLOUD=true
FILESYSTEM_CLOUD=s3
AWS_ACCESS_KEY_ID=key
AWS_SECRET_ACCESS_KEY=key
AWS_ENDPOINT=https://region.example.com
AWS_URL=https://aws.example.com
AWS_DEFAULT_REGION=region
AWS_BUCKET=bucket_name
AWS_USE_PATH_STYLE_ENDPOINT=false
```

**Comment by dansup** [comment]
Fixed in latest commits!
