### ISSUE TITLE
Privacy declaration missing

### ISSUE THREAD

**Issue by drdsgvo** [pixelfed/pixelfed#2886]
On the website pixelfed.org there is no privacy declaration.
For platforms which target the European Union or  which are in the responsibility of a person or company located in the EU, the GDPR applies.

Any websites falls under the GDPR as IP addresses are personally identifiable information (PII), as the CJEU judged in the year 2017 (C-582/14).
You website obviously is an "offer", so that a responsibility arises for you.
According to articles 12 and 13 GDPR, you must inform your users about data processing on the website.

Please add a page with a privacy declaration and link to it on every page of the website.

Without that your platform is not a privacy platform nor it is GDPR compliant.

**Comment by dansup** [comment]
pixelfed.org is a static website, it does not host any user data.
