### ISSUE TITLE
/discover/tags/<tag> shows only few images

### ISSUE THREAD

**Issue by xundeenergie** [pixelfed/pixelfed#2888]
Hashtag-discovery should show maximum about 260 images or so, someone told me in matrix-chat. 
But my instance only shows 9. The hashtag has more than 9 images. I know and checked it.

Other hashtags have 30 and 34 "status count"
![grafik](https://user-images.githubusercontent.com/5894829/130993994-28cd9d7f-797e-49c0-918b-84fb2dcc735d.png)
but klicking on the number, it shows only 24 images.

Another thing... klicking on the id in the blue box opens an url
https://japix.schuerz.at/i/admin/apps/show/19
which is not found... and i think its totally wrong...

**Comment by xundeenergie** [comment]
could this problem be related to postgresql-issues? case sensitive vs. insensitive? @dansup

**Comment by dansup** [comment]
Fixed in latest commits!

**Comment by xundeenergie** [comment]
Sorry.... it's not gone.. or do i have to "recreate" the hashtag-list?

I get - after update - no suggestions for upper-case hashtags, which i want to use.

**Comment by xundeenergie** [comment]
thank you for resolving this issue!!
