### ISSUE TITLE
Add support for healthchecks

### ISSUE THREAD

**Issue by SathyaBhat** [pixelfed/pixelfed#2893]
I'm hosting pixelfed on AWS behind a load balancer. The load balancer expects a health check URL and a positive response, else it does not consider the target, ie, pixelfed hosted on the VM behind the load balancer as valid and does not route traffic to it.

The load balancer also expects a relative URL, without the domain in the URL. Pixelfed, as far as I could determine, does not seem to return a 200 response to routes like `/site/about`, `/site/term` returns a 404 without the domain. I was able to change the expected response code as 404 so that the load balancer could send traffic to it, but I'd be happy to know if there's a better way around this

**Comment by dansup** [comment]
Added in #4549!
