### ISSUE TITLE
Cannot load stories, try again later.

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#2904]
After updating my instance to the latest post-stories 2.0 commits (including fixes) - I see the following dialogue box when I refresh the home or network pages:

![Screenshot_2021-09-04_15-04-32](https://user-images.githubusercontent.com/51400674/132097262-cfabca90-b6b0-4f3a-9e88-4baacd2be68d.png)

When I go to the new Stories link from the admin page, I receive the following error:

![Screenshot_2021-09-04_15-05-48](https://user-images.githubusercontent.com/51400674/132097291-f9e2026d-e46d-45bc-a405-7b13f87f5c32.png)

=======================
 Instance Diagnostic 
=======================
APP_URL: https://px.nipponalba.scot
APP_DOMAIN: px.nipponalba.scot
Version: 0.11.0
PHP: 7.3.29-1~deb10u1
PHP-bcmath: Installed
PHP-ctype: Installed
PHP-curl: Installed
PHP-intl: Installed
PHP-json: Installed
PHP-mbstring: Installed
PHP-openssl: Installed
PHP-redis: Installed
Database: pgsql (12.8)
Bootstrap: Writable
Storage: Writable
========= END =========

I have run the migrations, cached both config and routes and tried clearing the cache as well.

I appear to be able to post a story and a red ring appears around my profile picture but I don't get a story div at the top of the page and get the error above.

**Comment by jk-na** [comment]
It seems like the div or section initially renders the border but only momentarily, avatars appear (though they wouldn't anyway as I'm still awaiting documentation on how to move from local to S3 bucket to enable them :wink: )  then the error appears and the story bar vanishes.

**Comment by jk-na** [comment]
I see the following via  firefox browser console:
```
error	"SQLSTATE[42803]: Grouping error: 7 ERROR: column \"stories.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: select \"stories\".*, \"followers\".\"following_id\" from \"stories...\n ^ (SQL: select \"stories\".*, \"followers\".\"following_id\" from \"stories\" left join \"followers\" on \"followers\".\"following_id\" = \"stories\".\"profile_id\" where \"followers\".\"profile_id\" = 1 and \"stories\".\"active\" = 1 group by \"followers\".\"following_id\" order by \"id\" desc)"
```

.. another postgresql issue on a new feature?

**Comment by xundeenergie** [comment]
it still exists on a postgresql-based instance

**Comment by dansup** [comment]
@jk-na @xundeenergie It's been fixed in 00c3236, let me know if you encounter any more issues!

**Comment by jk-na** [comment]
can confirm, it seems to be working now, thanks.

**Comment by xundeenergie** [comment]
Seems it's gone.

Thank you!
