### ISSUE TITLE
Story Error "Division by zero"

### ISSUE THREAD

**Issue by xundeenergie** [pixelfed/pixelfed#2905]
I have problems with stories. They won't work.

Going to admin-paneld and klick on "Stories" I get an "Divison by zero" Error and this stacktrace

![grafik](https://user-images.githubusercontent.com/5894829/132105111-72fd250f-7245-469a-b8f1-645e1de159cf.png)

The url is: https://pixelfed.mydomain.tld/i/admin/stories/list

I'm on devel-Branch commit 0de2df96

**Comment by dansup** [comment]
Fixed in #2907
