### ISSUE TITLE
Missing icons for menu and post view

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2908]
Pixelfed v0.11.0 / PHP 7.4.20

Looks like the latest upgrade https://github.com/pixelfed/pixelfed/commit/82c5e74feba6bd6b08690bb9b7a298807fdb94c9 breaks the icons

![pixelfed-missing-icons](https://user-images.githubusercontent.com/1679025/132111465-b397cff6-5c05-4f3e-8598-5bc590f5380a.png)

**Comment by dansup** [comment]
Use the compiled assets.
