### ISSUE TITLE
Following count showing 0 - show count if profile belongs to user

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2911]
Pixelfed v0.11.0 / PHP 7.4.20

Following count is hidden for user in public view which works as it should

When user view their own profile, it is showing Following 0

If the **profile belongs to user**, would it be better to show the following count instead?

![pixelfed-following](https://user-images.githubusercontent.com/1679025/132114785-d00b34cb-cc10-4dc4-bd0d-480330d17d5c.png)

**Comment by dansup** [comment]
Fixed in v0.11.1
