### ISSUE TITLE
Photos and videos in stories aren’t displayed correctly on Firefox for iOS

### ISSUE THREAD

**Issue by azuredusk10** [pixelfed/pixelfed#2912]
On Firefox for iOS (v 36.0), when I tap to open a story, most of the image is covered by a black rectangle:
![05EEB695-E022-4FFA-B6B6-FEC8DA1BCBE0](https://user-images.githubusercontent.com/18142893/132117873-baea4ad1-976d-476e-8381-d8b3974d849b.png)

(for comparison, here is the same story in Safari for iOS:)
![1FC8B3AE-7104-4558-B9F8-F65A63894B7B](https://user-images.githubusercontent.com/18142893/132117934-83141342-4850-4e8e-a0ce-4258cc0927a6.png)

Furthermore, if the story contains a video, the video can only be viewed by pressing the “pause” button in the top-right of the screen and then pressing the “play” button in the top-right. Otherwise, all that is displayed is a black rectangle.

**Comment by dansup** [comment]
@azuredusk10  This should be fixed in the latest version (v0.11.1), let me know if you are still experiencing this issue on the latest version!

**Comment by spaceottercode** [comment]
I could be wrong, but i think it should now be safe to close this ticket

**Comment by spaceottercode** [comment]
Thank you @azuredusk10
