### ISSUE TITLE
Allow for sorting and categorizing activities

### ISSUE THREAD

**Issue by hellcp** [pixelfed/pixelfed#292]
@RavengamerSpace had a very good idea of seperating activities into categories. While 3 column system might not be a good idea, I think we need to have a way to see only likes, mentions or follows

**Comment by Aurnytoraink** [comment]
Here is a example:
![activity](https://user-images.githubusercontent.com/28545669/41550737-0d26054a-732a-11e8-8ace-061bbef37af2.png)

**Comment by dansup** [comment]
@RavengamerSpace I think thats an interesting idea, I think a js filter would be more appropriate so you keep the chronological aspect in a single column

**Comment by dansup** [comment]
<img width="741" alt="screen shot 2018-09-15 at 10 59 39 am" src="https://user-images.githubusercontent.com/877217/45588723-804f6880-b8d6-11e8-80a6-01c633c0c03f.png">

You can now filter notifications by activity type!
