### ISSUE TITLE
Notifications blank and comments showing the same thing on other posts 

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#2921]
=======================
 Instance Diagnostic 
=======================
Version: 0.11.1
PHP: 7.3.29-1~deb10u1
PHP-bcmath: Installed
PHP-ctype: Installed
PHP-curl: Installed
PHP-intl: Installed
PHP-json: Installed
PHP-mbstring: Installed
PHP-openssl: Installed
PHP-redis: Installed
Database: pgsql (11.12)
Bootstrap: Writable
Storage: Writable

========= END =========

@dansup 

I went through this bug where notifications page is blank .

and also comments after viewing shows the same comment when you click on another comment button on posts that no one has commented yet 

For example

say the post A has comments and am viewing it (looking at it ) when i view post B it shows the same comment of post A on post B comments section

**Comment by ghost** [comment]
Running 

php artisan route:cache
php artisan cache:clear 

fixed the notification issue but the comments issue is still there

**Comment by koalie** [comment]
I have been experiencing the latter part of the issue for a couple days now. I see  blank [notifications/activity](https://pixelfed.social/account/activity) in one of the two pixelfed accounts I have. 
This happens cross browsers and cross platforms.
Thank you!

**Comment by ghost** [comment]
Did you try running 

1.php artisan config:cache 
2.php artisan route:cache 

3.php artisan cache:clear 

for better observation please try refreshing the app and see it works while running each commands

**Comment by koalie** [comment]
I have not. And I would not even know how to! I use the web page and therefore click or touch vs. run commands.
