### ISSUE TITLE
Error after upgrade

### ISSUE THREAD

**Issue by AnonymousWebHacker** [pixelfed/pixelfed#2922]
![Captura de pantalla de 2021-09-09 02-28-51](https://user-images.githubusercontent.com/43164089/132634492-3c2b287c-3c41-4171-b40c-abe6691c0cbe.png)
![Captura de pantalla de 2021-09-09 02-25-13](https://user-images.githubusercontent.com/43164089/132634063-1e857b81-e923-474d-a8e2-313cb4c6e103.png)

the photos of the last post, can not be seen

**Comment by ghost** [comment]
Did you try running the following command 

php artisan cache:clear?

**Comment by AnonymousWebHacker** [comment]
![Captura de pantalla de 2021-09-09 02-35-55](https://user-images.githubusercontent.com/43164089/132635285-03c27b1a-0f17-416f-9fe4-b3333200f817.png)
![Captura de pantalla de 2021-09-09 02-35-46](https://user-images.githubusercontent.com/43164089/132635287-b47a6245-1a79-4ae2-8885-9a07c5a01f2a.png)


If I go to the instance profile, it only "supposedly" has a single post.

If I'm going to DISCOVER, the other posts from that account come out, but don't put more posts in the section below as recommendations, only one post comes out

**Comment by AnonymousWebHacker** [comment]
> Did you try running the following command
> 
> php artisan cache:clear?

I read it here https://github.com/pixelfed/pixelfed/releases

but I was looking at this https://docs.pixelfed.org/running-pixelfed/administration.html#updating-pixelfed and here it did not say.

My mistake for not looking at it, thank you very much

**Comment by AnonymousWebHacker** [comment]
After a few days, it happens to me that the notification box was shitting infinitely.
![](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/qxAYTGLTiXMkowndGhkYFFhe)
![](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/fuNNBBRGHDTVugoBLnZCltis)

If the same thing happens to someone, you can solve it with :  
`php artisan config:cache`
`php artisan cache:clear`

I hope this helps someone :)
