### ISSUE TITLE
artisan backup:run mit postgres not working

### ISSUE THREAD

**Issue by xundeenergie** [pixelfed/pixelfed#2925]
Running backup with artisan failes on postgresql-installation, because it wants to do a mysqldump... 

```
# sudo -u pixelfed php artisan backup:run
Starting backup...
Dumping database pixelfed...
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2013: "Lost connection to MySQL server at 'handshake: reading initial communication packet', system error: 11" when trying to connect
.

```

**Comment by dansup** [comment]
You can edit the backup config if you are not using mysql

https://github.com/pixelfed/pixelfed/blob/cdfb6ac25f0090c5e033b2bc813c076aefac9ba4/config/backup.php#L48-L53

**Comment by xundeenergie** [comment]
this is not straight forward and where can i find this in the docs?
