### ISSUE TITLE
Unable to find other instances / federation not working

### ISSUE THREAD

**Issue by xplosionmind** [pixelfed/pixelfed#2933]
I have Pixelfed 0.11.0 installed [via Yunohost](https://github.com/YunoHost-Apps/pixelfed_ynh 'Pixelfed Yunohost package repository on GitHub') on my VPS. Currently, I am the only user and I have no published post. When performing a search I cannot find any external user (so no users, since I am the only one on my instance, [tmi.pics](https://tmi.pics 'TMI Pics').

Furthermore, when attempt to scan external instances from the admin interface, I get this:

<img width="1440" alt="Screenshot 2021-09-13 at 12 47 06 PM" src="https://user-images.githubusercontent.com/42862428/133071069-4f296551-f3d8-4c7d-aca8-718f1b5d822a.png">

What should I do?

Thanks a lot.

**Comment by splacat** [comment]
Try start following other instance user. Go to search and write in https://pixelfed.social/@dansup

**Comment by xplosionmind** [comment]
> Try start following other instance user. Go to search and write in https://pixelfed.social/@dansup

I see the account and the bio, but nothing else; even after following:

<img width="1072" alt="Screenshot 2021-09-14 at 12 41 27 PM" src="https://user-images.githubusercontent.com/42862428/133243662-ca3eafcc-6bbc-44a3-9899-5e24f682a081.png">
<img width="1064" alt="Screenshot 2021-09-14 at 12 41 10 PM" src="https://user-images.githubusercontent.com/42862428/133243666-4554b6f6-95cd-4008-9d0f-6b8beb7b476c.png">

**Comment by splacat** [comment]
now go to admin / instances. Do you see pixelfed.social there?

**Comment by xplosionmind** [comment]
I do, but I only see pixelfed.social, with one user. is the only way to discover new instances specifically follow targeted users? In any case, there is still the problem that I cannot see any pictures!

<img width="1440" alt="Screenshot 2021-09-14 at 6 11 04 PM" src="https://user-images.githubusercontent.com/42862428/133294425-c9e67ca8-9ae6-4a7b-b23d-fdb1f89b9b81.png">

<img width="1440" alt="Screenshot 2021-09-14 at 6 11 10 PM" src="https://user-images.githubusercontent.com/42862428/133294419-9fdb8504-fdae-4daf-952d-b96802012082.png">

**Comment by splacat** [comment]
as far as I know yeah, this is how Pixelfed's federation works. As soon as @dansup or any other user you follow post a new image you will see it in your home timeline

**Comment by xplosionmind** [comment]
> this is how Pixelfed's federation works

I do not think so… when I search for somebody from my account on [pixelfed.uno](https://pixelfed.uno), for example, I see all of their pictures retro-actively.

Furthermore, If I look for `exampleuser@pixelfed.somedomain`, which I am sure it exists, it does not work, I have to insert the domain. It should not be so.

**Comment by inthreedee** [comment]
@xplosionmind Did you ever figure out what was going on with this?

**Comment by xplosionmind** [comment]
I figured out that the only way to search for users on remote instances is to paste in the search bar the full url of the profile, rather than `@username@instance.tld`

**Comment by inthreedee** [comment]
How did you get it to show their posts?  I'm at the same point you were at, where if I paste `https://pixelfed.social/dansup` into my instance's search bar and click on "view profile", all I see is an empty profile.  If I do the same on my pixefed.social account, I see all the profile's posts.

**Comment by dadall** [comment]
Federation starts when your account is connected to another account. That's the trigger. Whatever happened before is not federated, or just a tiny part.

**Comment by inthreedee** [comment]
@dadall pixelfed.social does show up under instances in my admin panel.  This happened after I followed my accounts in both places.  But I still don't see any profile information.  Is there more I need to do?

**Comment by inthreedee** [comment]
It seems to be starting to sort itself out.  I guess the previous suggestions here are correct in that it only shows new posts after the connection is made.  Thanks everyone!
