### ISSUE TITLE
HTTP Signature failing against GoToSocial and Mastodon with secure mode set to ON 

### ISSUE THREAD

**Issue by tsmethurst** [pixelfed/pixelfed#2935]
I did a bit of investigation yesterday and today about the following issue:

https://github.com/superseriousbusiness/gotosocial/issues/131

The tl;dr is that HTTP Signatures don't seem to be working for Pixelfed => secure instances, at least for the instance actor fetching.

I logged a bunch of my findings in the linked issue, so I hope that helps to debug :)

**Comment by tsmethurst** [comment]
For reference: https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures#section-2.3

See particular 4.1 under that heading, to do with concatenating values from same-key headers.

I *think* Pixelfed is not comma-separating values of headers with the same key, but i'm not entirely sure

**Comment by tsmethurst** [comment]
As far as I can tell this is still not fixed unfortunately, see my comment here: https://github.com/pixelfed/pixelfed/commit/a900de2121762cab296c9a6a160492edf71156c4#r56770957

**Comment by egon0** [comment]
Sadly, it's not fixed and prevents a larger adoption of pixelfed in my family and Peergroup 😐

**Comment by mrvdb** [comment]
Is someone still looking at this?  I think not being able to subscribe from gotosocial account to a pixelfed account is a manifestation of this issue?

**Comment by tsmethurst** [comment]
If pixelfed doesn't sign outgoing GET requests, it could be related to that.

I did a bit of a fix for this for gnu social here: https://codeberg.org/GNUsocial/gnu-social/commit/2df30e298727a5097b6712bf053e9402d4fea328

@dansup you might be interested in porting that code into pixelfed, since iirc you used the same gist for your http signature implementation right? :)

**Comment by anantshri** [comment]
@dansup is there something that can be done to help with prioritisation of this issue.

**Comment by dansup** [comment]
@tsmethurst Fixed in #4504 and tested on my staging instance, I can now successfully search and view GtS posts!

**Comment by tsmethurst** [comment]
Nice work :)
