### ISSUE TITLE
Filters Apply to First Image Only in Multi-Image Posts

### ISSUE THREAD

**Issue by jimmybrancaccio** [pixelfed/pixelfed#2939]
### Environment

Pixelfed via Docker - v0.11.1

### Steps to reproduce

1. Create an account on your/a Pixelfed instance.
2. Login and create a new post.
3. Include at least 2 images in your new post.
4. Apply a filter to each of the images in the post and save.
5. Observe that the first image in the post has had the filter previously selected applied to it.
6. Observe any images after the first image does not have the previously selected filter applied to it.

### Expected Result

I expect that when creating a post with multiple images that each have a filter applied to them that when the post is published each of the images is rendered with the previously applied filter.

### Actual Result

Only the first image of a multi-image post is created with the previously selected filter. Any other images beyond the first are not created with the filter that was selected for them.

Of note, I noticed this on my Pixelfed instance first, but I did a test on pixelfed.social to see if was related to only my instance. It is not. I replicated the issue on pixelfed.social as well. The following screenshots are from the test post I made on pixelfed.social.

My test - https://pixelfed.social/p/jimmyb/344174247984783152

### Visual Proof (screenshots, videos, text)

First image:

<img width="527" alt="Screen Shot 2021-09-16 at 12 45 06 PM" src="https://user-images.githubusercontent.com/405585/133660876-e4623c81-8d9d-464e-8ddd-a81d42578fd1.png">

Second Image:

<img width="512" alt="Screen Shot 2021-09-16 at 12 45 22 PM" src="https://user-images.githubusercontent.com/405585/133661325-57394507-478c-4ae3-bd1f-6f0f6208c9d2.png">

Final Results:

<img width="1170" alt="Screen Shot 2021-09-16 at 12 53 21 PM" src="https://user-images.githubusercontent.com/405585/133661093-d3aa5720-81ab-4cba-8926-db3f18f1df8d.png">

<img width="1140" alt="Screen Shot 2021-09-16 at 12 53 28 PM" src="https://user-images.githubusercontent.com/405585/133661106-39235816-1113-450a-a278-2c50670be0b1.png">

**Comment by kojid0** [comment]
Facing this bug as well. Could you please take a look, @dansup?

**Comment by trwnh** [comment]
Not strictly the "first" photo, it seems to happen for me as the "last selected photo". Furthermore, editing the post (e.g. to reorder the photos) causes the filter to be lost on any/all photos.
