### ISSUE TITLE
Inconsistent user name rule

### ISSUE THREAD

**Issue by rfonseca** [pixelfed/pixelfed#2940]
Hi, 

I tried to create a user name starting with a number, such as 123name, but the form complained with the message: "Username is invalid. Must start with a letter or number." As this one starts with a number, either the error checking is wrong, or the error message is wrong. (I would rather that it be the error checking)

Thank you

**Comment by rm-yakovenko** [comment]
Looks like this issue has been already fixed in https://github.com/pixelfed/pixelfed/commit/31330e0aed2a6bf2547bce3378e3830bd0f98e82.
