### ISSUE TITLE
Stories not viewable unless signed in

### ISSUE THREAD

**Issue by 3xrp1** [pixelfed/pixelfed#2944]
Hi, I noticed stories are not viewable unless signed in.

While this is consistent with fb, fb did this to force people to create accounts on their platform, not as an actual privacy feature. I would love to encourage people to create accounts on pixelfed, but duplicating this as a no-option setting is really not good.  It should be a public/platform/friends checkbox option like there is for posts. This could be set to login-only by default so people accustomed to fb don't get surprised.

ST

**Comment by dansup** [comment]
@STemR Stories are follower only for now, if we support public stories they will be viewable without logging in.
