### ISSUE TITLE
Incorrect federation after upgrading

### ISSUE THREAD

**Issue by marcelcosta** [pixelfed/pixelfed#2945]
Hello,

I have recently upgraded our instance to last version and federation is not working properly. After publishing a photo, it is not seen by other activity pub running services: pleroma, mastodon or even pixelfed. Curiously, after boosting the photo with my own account I start to see the boost and the original post from outside.

The Diagnosis shows no clues:

```
=======================
 Instance Diagnostic 
=======================
APP_URL: https://test.pixelfed.anartist.org
APP_DOMAIN: test.pixelfed.anartist.org
Version: 0.11.1
PHP: 7.3.30-1+0~20210826.87+debian9~1.gbpe56a7b
PHP-bcmath: Installed
PHP-ctype: Installed
PHP-curl: Installed
PHP-intl: Installed
PHP-json: Installed
PHP-mbstring: Installed
PHP-openssl: Installed
PHP-redis: Installed
Database: mysql (8.0.25)
Bootstrap: Writable
Storage: Writable
========= END =========
```

**Comment by marcelcosta** [comment]
Hi,

I have noticed that the "StatusActivityPubDeliver" is not executed when posting a photo. What may that be? Could this be the reason?

My .env federation part looks like this:

```bash
ACTIVITY_PUB=true
#REMOTE_FOLLOW=true
#ACTIVITYPUB_INBOX=true
#ACTIVITYPUB_SHAREDINBOX=true
#AP_OUTBOX=true
AP_INBOX=true
#AP_SHAREDINBOX=true
AP_REMOTE_FOLLOW=true
PF_COSTAR_ENABLED=false
INSTANCE_DISCOVER_PUBLIC=true
```

**Comment by poltrian** [comment]
Same here, no sharing with other Fediverse platforms

**Comment by dansup** [comment]
Fixed in latest commits!
