### ISSUE TITLE
Similarity between multi-colour Pixelfed and Apple Photos logo

### ISSUE THREAD

**Issue by jumoru** [pixelfed/pixelfed#295]
I don't know whether this is a big problem, but at least the multi-colour version of the new Pixelfed logo looks very much like the logo of Apple's Photos app

It's probably important to think about whether this can be problematic

![ohne titel](https://user-images.githubusercontent.com/27491477/41541299-66ffc46a-7312-11e8-8d61-ff340b854654.png)
![apple-photos-app-logo](https://user-images.githubusercontent.com/27491477/41540933-8216b49e-7311-11e8-91d3-f76d48ac97ed.jpg)

**Comment by StefOfficiel** [comment]
I think it's a problem. They are exactly the same.

**Comment by faissaloo** [comment]
Can I just mention that this logo is horrible and busy anyway? It looks like the Picasa logo too

**Comment by NicolasConstant** [comment]
I think it's an issue too. 
As most of logo contributions where inspired by other existing apps/service (Apple Photo app, Picasa, Instagram, etc), maybe the contributions should have been filtered first for not being a "re-branded existing logo".

**Comment by hellcp** [comment]
https://medium.com/@fvo/your-logo-is-copied-710ac4604258

There is only so much you can do to make app look like photos app. There always are and always will be similarities. While Instagram went with a camera (and you can't tell how many camera apps there are with a camera for a logo/icon), there is also idea of paint colour sampler used here. It's a common element across many different apps, and you can't avoid it. It's not even close to Picasa too, the only similarity is a lot of colours (and that is no similarity in my book), it's a shutter and not a sampler.

Imo issue should be closed, there is no point to discuss here.

**Comment by dansup** [comment]
I agree with @hellcp.

**Comment by NicolasConstant** [comment]
@hellcp 
Yes logos can have similarities, but it's only ok if it's **not in the same field** (like your article illustrate too).

And since - obviously - photo app will rely on photographic material, it's doesn't mean it have to be inspired by a front projection of a Polaroid camera like Instagram do, like we saw in many contributions. 
Of course this is ok since most of the contributors aren't designers (and did a great job), but it could bring some issues in the long term: like when someone will do an iOS PixelFed App, and then will have a logo inspired from PixelFed, will people think this app is a PixelFed client or a more well-known service client? This is the main issue for me.

**Comment by hellcp** [comment]
It's not gonna be confusing, style, colours and shape are different. Idea is the same, but that's about it :D

**Comment by StefOfficiel** [comment]
Imagine Mastodon with a little blue bird looking to the left! Yes, it's inspired, it's similar but with differences. But it's copied! Here, the logo is copied, exactly the same rounded, exactly the same colors, in the same proportions!

**Comment by StefOfficiel** [comment]
"style, colours and shape are different." I've problem with my eyed ? 😅

**Comment by hellcp** [comment]
Style: Overlapping transparent colours vs solid overlap
Colours: Uh, using much darker shades (and dark green)
Shape: I can see that being confusing, there is giant P cut out in the middle?

**Comment by dansup** [comment]
I wasn't able to respond to this issue sooner, so I locked it until I could respond appropriately. The logo has 4 variants and the coloured version was only to be used temporarily for pride month. I have updated it to the black variant which I think differentiates it enough from Apple Photos. 

Let me know what you think!

**Comment by jumoru** [comment]
If this colored version is only used temporarily to celebrate pride month I‘m totally fine with it.

Without this background information I was just worried that this is the new permanent logo. And in this case Pixelfed probably wouldn’t have done itself a favor in terms of being an optically easy to recognize app (especially on the Apple OSs), which would have been sad because we want Pixelfed to be successful.

**Comment by jumoru** [comment]
@hellcp  Of course there always will be similarities in the sense that multiple logos can be based on the same basic idea (camera, color wheel, …). 

But as already mentioned by @NicolasConstant and @StefOfficiel  I also think that the colored version of the Pixelfed logo risks running into two issues. 

First, on one of the two major mobile platforms it looks like the systems photo app, especially at the relative small size of the logos on the home screen, which makes spotting the few minor differences (white „P“ and more solid colors) much harder.

Second, compared to projects like Chrome or Darktable which also play with the idea of a color wheel, the colored Pixelfed logo is much less distinct from the Apple logo because it has the same proportions, shapes, arrangement, colors, number of colors, … 

For me this is the real issue. There’s nothing wrong with using an established idea like a camera or a color wheel, but if one chooses to use such a basic idea, one has to make sure that the logo is still distinct. Instagram, for example, achieved distinctiveness by using round edges in their camera and by choosing a unique color scheme (orange colors, gradients). And, btw, this is also why I think that the black, grey and white versions of the logo are less problematic.

**Comment by StefOfficiel** [comment]
"And, btw, this is also why I think that the black, grey and white versions of the logo are less problematic."

I agree, but we do not use or few monochrome logo. For having worked in the Branding team of a big American company in France, Branding is something complicated and complex. Monochrome is badly perceived in the collective spirit and does not offer a great success.
(It can be seen with diaspora*)
The key to success is to have something visually professional, it reassures non-nerd users!

**Comment by Grazouillis** [comment]
I think this choice is very good - it's better in black, I was worried about the similarity with picasa's/apple logos too.

**Comment by mrk-us** [comment]
I'm the designer of the winning the logo. I can assure you any similarities are purely coincidental or subconscious here. I basically script rotated 7 copies of a rectangle in sketch and rounded them. They are very similar seeing them side by side, however, and I probably would have caught this and opted not to use it, had I used iOS. The colors are especially a problem, unfortunately it's a universal wheel so short of rotating the starting point or changing the laws of electromagnetic radiation, not much can be done. The initial proposal was this - [https://github.com/dansup/pixelfed/issues/182#issuecomment-396067684](https://github.com/dansup/pixelfed/issues/182#issuecomment-396067684) - with a multicolored version as an alternative (I prefer the single color version for both branding reasons and personal preference), so I'd suggest we just change the colors or the shapes used @dansup to avoid any confusion going forth.

Are there any from the work in progresses that catch your eye @dansup? I'm happy to work up alternatives and black and white variations for print/over images if you decide to change it to any of the following.

<img width="1325" alt="pixelfed-wip" src="https://user-images.githubusercontent.com/15676251/41624059-167d7684-7404-11e8-8c1b-77c8141a7ce8.png">

**Comment by dansup** [comment]
@rnarrkus 😍So hard to pick one of those, is it possible you can join #pixelfed channel on freenode IRC?

**Comment by StefOfficiel** [comment]
@rnarrkus Very nice job !
My favorites are: The third line, 5 and 6!

**Comment by jumoru** [comment]
@rnarrkus I have to say that I really like the red / orange single color ones. They're clean, simple, elegant, unique and look a lot more friendly than black or white one. From the set of the multicolored ones my favorite would be the last one in line 3, also because those visible pixels would go very well with the name Pixelfed.

**Comment by kaffeeringe** [comment]
3rd line. no. 6
