### ISSUE TITLE
same DeleteWorker multiple attempts

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2951]
I looked at them and it's from same host. 

-Is there a way to group the same error together?
-Also if it's the same error, decrease the attempts for later so it's not constantly trying?

![pixelfeddeleteworker](https://user-images.githubusercontent.com/1679025/134445438-193d9909-043a-4254-9937-de1241d9f458.jpg)

**Comment by dansup** [comment]
@okpierre By default (https://github.com/pixelfed/pixelfed/blob/dev/config/horizon.php#L174) it will retry 3 times, it appears to be retrying once per minute and more than 3 tries, can you confirm it is the same activitypub object?

**Comment by okpierre** [comment]
@dansup is there a way to completely remove the domain causing this error? no idea what it is

each entry looks similar. not sure if this helps but here's the payload

```
"user-agent": [
"Pleroma 2.3.0-1-gb221d77a; https://pl.thj.no <example@example.com>"
]
},
"payload": "{"@context":["https://www.w3.org/ns/activitystreams","https://pl.thj.no/schemas/litepub-0.1.jsonld",{"@language":"und"}],"actor":"https://pl.thj.no/users/thor","cc":[],"id":"https://pl.thj.no/activities/c95c7cb1-da0a-4669-8c1b-c04a39b6aa05","object":"https://pl.thj.no/objects/7e149297-24e0-4831-bc0a-39599ba90fb3","to":["https://pl.thj.no/users/thor/followers","https://frees***.com/users/thedonnerd","https://www.w3.org/ns/activitystreams#Public","https://pl.thj.no/users/thor"],"type":"Delete"}",
"timeout": 60,
"tries": 1,
"job": null,
"connection": null,
"queue": "delete",
"chainConnection": null,
"chainQueue": null,
"chainCatchCallbacks": null,
"delay": null,
"afterCommit": null,
"middleware": [
],
"chained": [
]
```

**Comment by dansup** [comment]
Fixed in latest commits!
