### ISSUE TITLE
Instagram import asks for media.json and photos directory, which do not exist

### ISSUE THREAD

**Issue by cloo** [pixelfed/pixelfed#2955]
Instagram import cannot be completed, because .zip files provided by instagram in both JSON and HTML formats do not contain required media.json file neither "Photos directory".

![210925-174402](https://user-images.githubusercontent.com/651760/134775492-592e18ee-902e-479a-bc21-a3ea749784a2.png)
 
![210925-174223](https://user-images.githubusercontent.com/651760/134775497-c1bb5a74-e1e6-4dbe-bb2f-da32385728fb.png)
 
![210925-174232](https://user-images.githubusercontent.com/651760/134775502-f0ba732c-5683-450b-a141-9c287b820593.png)

Server version 0.11.1

**Comment by SathyaBhat** [comment]
#2877 it's an instagram change

**Comment by davetapley** [comment]
@cloo please close this as dupe

**Comment by cloo** [comment]
Closing as dupe. 
Yet it is still an issue. Pixelfed should not offer its users a button to attempt doing what is not possible to do, regardless of why it is not possible.
