### ISSUE TITLE
1205 Lock wait timeout exceeded try restarting transaction

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2958]
First time seeing this error message and only after upgrading to latest version

Pixelfed v0.11.1 / PHP 7.4.20 / mysql 8.0.26

`General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: update `statuses` set `deleted_at` = 2021-09-27 22:01:25, `statuses`.`updated_at` = 2021-09-27 22:01:25 where `statuses`.`reblog_of_id` = 345672812412697740 and `statuses`.`reblog_of_id` is not null and `statuses`.`deleted_at` is null) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: update `statuses` set `deleted_at` = 2021-09-27 22:01:25, `statuses`.`updated_at` = 2021-09-27 22:01:25 where `statuses`.`reblog_of_id` = 345672812412697740 and `statuses`.`reblog_of_id` is not null and `statuses`.`deleted_at` is null) at /pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:692)`

stacktrace
https://pastebin.com/ecHZRd22

**Comment by dansup** [comment]
Fixed in latest commits!
