### ISSUE TITLE
Mastodon Integrity constraint violation 1062 Duplicate entry

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2959]
Error for mastodon profile

Pixelfed v0.11.1 / PHP 7.4.20 / mysql 8.0.26

`Integrity constraint violation: 1062 Duplicate entry 'https://mastodon.social/@zorinlynx/107006169477770500' for key 'uri' (SQL: insert into `statuses` (`profile_id`, `url`, `uri`, `object_url`, `caption`, `rendered`, `created_at`, `in_reply_to_id`, `local`, `is_nsfw`, `scope`, `visibility`, `cw_summary`, `id`, `updated_at`) values (324347321921966080, https://mastodon.social/@zorinlynx/107006169477770500, https://mastodon.social/@zorinlynx/107006169477770500, https://mastodon.social/users/zorinlynx/statuses/107006169477770500, [**long content removed**], 2021-09-27 23:16:08, ?, 0, 0, public, public, ?, 348243728082518956, 2021-09-27 23:16:14)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'https://mastodon.social/@zorinlynx/107006169477770500' for key 'uri' (SQL: insert into `statuses` (`profile_id`, `url`, `uri`, `object_url`, `caption`, `rendered`, `created_at`, `in_reply_to_id`, `local`, `is_nsfw`, `scope`, `visibility`, `cw_summary`, `id`, `updated_at`) values (324347321921966080, https://mastodon.social/@zorinlynx/107006169477770500, https://mastodon.social/@zorinlynx/107006169477770500, https://mastodon.social/users/zorinlynx/statuses/107006169477770500, [**long content removed**], 2021-09-27 23:16:08, ?, 0, 0, public, public, ?, 348243728082518956, 2021-09-27 23:16:14)) at /pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:692)`

stacktrace
https://pastebin.com/sdQFjVTJ

**Comment by dansup** [comment]
Fixed in latest commits!
