### ISSUE TITLE
Unfortunately I never understand how to change the storage path

### ISSUE THREAD

**Issue by poltrian** [pixelfed/pixelfed#2963]
I want to save the storage folder on a network drive. How can I do that. Sorry, I'm brand new to Pixelfed 
can someone please help me?

**Comment by ghost** [comment]
You can join the discord and request 

https://discord.com/invite/sxhADKFSWF

as of yet this feature is not implemented 
You can try the S3 storage on env I’m not sure if it works 


## S3
FILESYSTEM_DRIVER=local
FILESYSTEM_CLOUD=s3
PF_ENABLE_CLOUD=false
#AWS_ACCESS_KEY_ID=
#AWS_SECRET_ACCESS_KEY=
#AWS_DEFAULT_REGION=
#AWS_BUCKET=
#AWS_URL=
#AWS_ENDPOINT=
#AWS_USE_PATH_STYLE_ENDPOINT=false
