### ISSUE TITLE
email settings Driver SMPT 

### ISSUE THREAD

**Issue by poltrian** [pixelfed/pixelfed#2964]
I have entered my settings in the .env, but no email is sent. I chose SMTP as the driver and specified the username and password. Encryption I chose starttls with port 587 but also tls with 465. Unfortunately no email is sent. Can someone help me please?

**Comment by poltrian** [comment]
works without tls.

**Comment by Happyfeet01** [comment]
Oh thanks. Without the tls encryption Settings?
