### ISSUE TITLE
Black box appearing on Stories

### ISSUE THREAD

**Issue by vachan-maker** [pixelfed/pixelfed#2982]
There is a black box appearing on the stories. I cannot view the image completely.  
Instance: https://pixelfed.social
Desktop: Windows 10
Browser: Firefox 93
Dark theme active.
Screenshot attached below
![image](https://user-images.githubusercontent.com/65799568/138100629-759eb678-b428-4c87-801f-b38bd98c2495.png)

**Comment by ghost** [comment]
Hi,

stories don’t support dark theme at the moment
