### ISSUE TITLE
Docker: Issues sending mail with SMTP from selfhosted pixelfed instance hosted in Docker

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#3000]
## Issue
I'm trying to install a Self-hosted Pixelfed instance in Docker with using SMTP as a mail driver. I use Migadu (https://www.migadu.com) as my email provider to send mails via SMTP. When I try registering a new user, the Instance asks me to send a confirmation mail, and it fails with the prompt "Something went wrong, please contact the administrator" error screen.

Their (Migadu) usage instructions are as follows.
**Outgoing Mail**
Protocol: SMTP
Server: smtp.migadu.com
Port: 465
Security: TLS
Authentication: Password
Username: test@domain.com
Password: somestrongpassword

And, my Configuration in the .env file is written as follows
MAIL_DRIVER=smtp
MAIL_HOST=smtp.migadu.com
MAIL_PORT=465
MAIL_USERNAME=test@domain.com
MAIL_PASSWORD=somestrongpassword
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS="test@domain.com"
MAIL_FROM_NAME="Pixelfed"

## Logs
This is the log that I can see in `storage/logs/laravel.log` related to mail delivery.
```
[previous exception] [object] (Swift_IoException(code: 0): Connection to tcp://smtp.migadu.com:465 Timed Out at /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:166)
```

## Things I have tried
- I have tried changing `MAIL_ENCRYPTION=tls` to `MAIL_ENCRYPTION=ssl` which did not work.
- I have tried changing the port to 587 which did not work.

I'm not sure if this is an issue with Docker or mail delivery. It would be great if somebody could shed light on this.

**Comment by ghost** [comment]
MAIL_FROM_ADDRESS="noreply@yourselfhosteddomain.com"

**Comment by ghost** [comment]
Do you mean to say that I should have tried with the "noreply" kind of email? Does it matter much? Because I have tried with all possible kinds of email addresses for `MAIL_FROM_ADDRESS`, all of them have failed with similar error.

**Comment by ghost** [comment]
change your mail from address to 
no-reply@yourdomain.com

**Comment by ghost** [comment]
Didn't work. Here are the logs that were logged in `storage/logs/laravel.log` for more context.
```
[2021-11-10 04:02:28] production.ERROR: Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients
" {"userId":1,"exception":"[object] (Swift_TransportException(code: 554): Expected response code 354 but got code \"554\", with message \"554 5.5.1 Error: no valid recipients
\" at /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:459)
[stacktrace]
#0 /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(344): Swift_Transport_AbstractSmtpTransport->assertResponseCode()
#1 /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand()
#2 /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(392): Swift_Transport_EsmtpTransport->executeCommand()
#3 /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(499): Swift_Transport_AbstractSmtpTransport->doDataCommand()
#4 /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(518): Swift_Transport_AbstractSmtpTransport->doMailTransaction()
#5 /var/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo()
```

**Comment by dansup** [comment]
@0xv31an5a1i5 Add
 ```
MAIL_FROM_ADDRESS="you@example.com"
MAIL_FROM_NAME="your name"
```
to .env then run
```
php artisan config:cache
```

**Comment by ghost** [comment]
Tried it. Didn't work. 

The logs indicate that the issue is regarding the recipient. However, when I try sending the mail in regular means, via an Email client, it works! Could this be an issue with the Docker setup?

**Comment by mgrzeca** [comment]
On my instance (also Docker) this problem also appeared, probably between August and now. Previously it worked, the configuration was not changed at that time. The SMTP server returns "535 Username and Password not accepted". The login and password are correct.

**Comment by ghost** [comment]
The mails are being sent now. Strange! Not sure what fixed it. I haven't changed the config, haven't made any changes to the source code. I just removed and rebuilt the stack with the same image. Now the emails are being sent. So, I think I can close this issue now.
