### ISSUE TITLE
No Index File in PixelFed Folder

### ISSUE THREAD

**Issue by minoush82** [pixelfed/pixelfed#3003]
Hello,

I followed the installation instructions from here [1], and when I input the URL of my pixelfed in the browser I get the folder listing [2] instead of a web page. Inspecting the folder listing does not show any index file inside.

What could have gone wrong? Where is the index file?

Thanks.

[1] [Documentation](https://docs.pixelfed.org/)
[2] [Folder Listing](https://www.dropbox.com/s/j168eqvx17lxwva/pixelfed_folder_listing.png?dl=0)

**Comment by ghost** [comment]
Hi

The installation is sort of complicated and yet under development 

instead install Yunohost to run pixelfed

**Comment by ghost** [comment]
Hi

The installation is sort of complicated and yet under development 

instead install Yunohost to run pixelfed

**Comment by trwnh** [comment]
The index.php file is in /public. Make sure to configure your web server to link to the /public folder, not to the root of the Git repository.

Wrong: `/path/to/pixelfed`
Right: `/path/to/pixelfed/public`

https://docs.pixelfed.org/running-pixelfed/installation.html#handling-web-requests
