### ISSUE TITLE
Remote avatars not displayed

### ISSUE THREAD

**Issue by hikerus** [pixelfed/pixelfed#3014]
I see in version 0.11.1 dev that remote avatars are not displayed and I found that this is reported serveral times.
eg. https://github.com/pixelfed/pixelfed/issues/1629

Any ideas to fix this?

**Comment by Casuallynoted** [comment]
Also curious if there are any updates on this.

**Comment by dansup** [comment]
Fixed in latest commits! Remote avatars are cached/updated every 24 hours. You can also run the `php artisan avatar:sync` command to fix existing avatars!
