### ISSUE TITLE
http/https protocol in links is invisible

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#3016]
![image](https://user-images.githubusercontent.com/10606431/142954971-f6c993eb-1c7a-4523-8046-67442d3dcc93.png)

this is happening because the protocol is wrapped in a span.invisible, and `.invisible` applies `visibility: hidden !important`

presumably the intention was to hide the protocol for "cleaner" links, but this should have been done with `display: none` instead of `visibility: hidden`

i would even argue it shouldn't be done at all -- hiding the protocol is a bit of an anti-feature even if it does look nicer

**Comment by dansup** [comment]
Fixed in latest commits!

![Screen Shot 2022-01-25 at 1 09 45 AM](https://user-images.githubusercontent.com/877217/150937077-00619911-6032-4876-9d2b-fa978c00c39a.png)
