### ISSUE TITLE
Feature: Optional full-size timeline-like display of photos on profile

### ISSUE THREAD

**Issue by realpixelcode** [pixelfed/pixelfed#3019]
I find the square photo preview on Pixelfed profiles very practical because it is so uncluttered.

But sometimes I want to see all the photos of a profile in full size. Then it is a bit inconvenient to have to click on each individual picture separately. It would be better if you could also view the photos of a Pixelfed profile in the form of a "timeline" (a continuous list of the expanded photos, just like on the personal home timeline).

**Comment by dansup** [comment]
Fixed in latest commits!
