### ISSUE TITLE
Issue with incorrections in programming on registration/login process

### ISSUE THREAD

**Issue by imaginae** [pixelfed/pixelfed#3021]
Found errors on code as using $user->user->is_admin, while it should be $user->is_admin

![Captura de pantalla 2021-11-26 a las 13 50 12](https://user-images.githubusercontent.com/39167320/143585815-ebbd98b7-5c86-4a76-bc4a-7f3eac87c486.png)

**Comment by dansup** [comment]
Fixed in latest commits!
