### ISSUE TITLE
Default avatar files are not in github

### ISSUE THREAD

**Issue by imaginae** [pixelfed/pixelfed#3022]
Hi there,

have found that avatar files are not uploaded to github and we are missing them once logged in. See screenshot:

![Captura de pantalla 2021-11-26 a las 14 11 23](https://user-images.githubusercontent.com/39167320/143586339-235632b6-daf0-4d3c-95c2-15e8c07d9737.png)

Regards

**Comment by imaginae** [comment]
It seems is something related to the images routes, that are inside storage/public, also happens with already pushed images on posts:
![Captura de pantalla 2021-11-26 a las 14 19 11](https://user-images.githubusercontent.com/39167320/143587171-ff36b046-be93-4724-9408-6810cf66d90a.png)

**Comment by dansup** [comment]
@imaginae Run the `php artisan storage:link` command
