### ISSUE TITLE
Public post switches to unlisted if it contains a URL

### ISSUE THREAD

**Issue by tuxor1337** [pixelfed/pixelfed#3028]
When creating a "public" post, it only remains public for a short while, then it switches to "unlisted" (maybe after reload or so).

Edit: See my post below for an explanation.

**Comment by tuxor1337** [comment]
This effect seems to be due to the URLs contained in the post's text. I removed the URLs and re-posted and the status seems to remain "public": https://pixelfed.social/p/freeboardgames/371321543995041884

Is this a general Pixelfed feature or is this a local policy implemented by my instance pixelfed.social? In any case, it would be good to be informed about this kind of effect. For example, when writing the post, or when clicking the submit-button, a visual indication would be very helpful.

**Comment by dansup** [comment]
@tuxor1337 Your post was flagged by the automated spam detection service, it shouldn't happen again!

**Comment by tuxor1337** [comment]
I created a new post that contains URLs and it again switched from public to unlisted: https://pixelfed.social/p/freeboardgames/372661926040819747 (link might not work for you due to #2936)

**Comment by tuxor1337** [comment]
@dansup Even if this is due to the automated spam detection service it would be good to be informed about that flagging in order to be able to react to it in some way.
