### ISSUE TITLE
Faker still outdated

### ISSUE THREAD

**Issue by Valinwolf** [pixelfed/pixelfed#3043]
I was about to cherry-pick PR #3041 into my local copy when I noticed you were actively working on pulling it into the main branch, so I waited and after you merged it I removed my local copy and downloaded a fresh copy from the dev branch and noticed that I still get an error for faker:

```
$ composer install --no-ansi --no-interaction --optimize-autoloader

Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.0.13) does not satisfy that requirement.
```

I was looking at the faker package and noticed that it is an abandoned project. [Faker had a commit](https://github.com/fzaninotto/Faker/commit/80218ec41b9ba6e93a8b010e077a3878503b8ad5) that added PHP 8 support, however it seems it never made it into the composer package. So is faker a hard requirement of pixelfed or can it be removed safely? If it cannot be removed safely, is there an alternate library that can be used?

**Comment by dansup** [comment]
@Valinwolf Try running `composer install --no-dev`. It's safe to remove faker, I'll remove it from composer in the next release!
