### ISSUE TITLE
Add locaton - too inflexible

### ISSUE THREAD

**Issue by hikerus** [pixelfed/pixelfed#3044]
With a picture you can add a location - that's a good idea. But the module is very inflexible - you can only add a village or a city. Would be nice to be able to add also a country or a region.

**Comment by LukeWheeldon** [comment]
Same issue here, ideally it would be possible to input standard coordinates.

**Comment by stephen304** [comment]
It would be cool if it also had a pop up map (osm maybe?) to drop a pin and set a name for the location.
