### ISSUE TITLE
Specifies "application/x-www-form-urlencoded" in the Content-Type Header

### ISSUE THREAD

**Issue by toddsundsted** [pixelfed/pixelfed#3049]
It looks like Pixelfed is sending ActivityPub activities with a content type of "application/x-www-form-urlencoded" instead of 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"' or even "application/activity+json". Unless explicitly specified, PHP cURL uses either "multipart/form-data" or "application/x-www-form-urlencoded", depending on the data.

The correct header could be added in:
https://github.com/pixelfed/pixelfed/blob/dev/app/Services/ActivityPubDeliveryService.php#L44

or in the signature generation code:
https://github.com/pixelfed/pixelfed/blob/dev/app/Util/ActivityPub/HttpSignature.php#L17

I could wrong, but I think the relevant documentation is here: https://www.php.net/manual/en/function.curl-setopt.php#refsect1-function.curl-setopt-notes.

**Comment by spctrlth** [comment]
Bump. This seems to affect federation with Pleroma, see https://git.pleroma.social/pleroma/pleroma/-/issues/2790#note_90849

**Comment by dansup** [comment]
Fixed in #3411
