### ISSUE TITLE
Klick on Image shows only line

### ISSUE THREAD

**Issue by xundeenergie** [pixelfed/pixelfed#3073]
When i klick on an image, there should be shown an overlay with the image... but i get only a black line.

you can see this line best in the "Comments-section" on the right.
![grafik](https://user-images.githubusercontent.com/5894829/147159547-76a183fc-2262-41d9-b719-0a829ab8012b.png)

I updatedt to dev-branch from git to commit 4f2c8b39

**Comment by dansup** [comment]
Fixed in latest commits!
