### ISSUE TITLE
Like Bug - Error code 500 (server response)

### ISSUE THREAD

**Issue by trev-dev** [pixelfed/pixelfed#309]
Hey Dan,

Hopefully not a double post. Looks like we're throwing error code 500 when sending data via ajax to the /like REST endpoint(?). This is also causing strange/inconsistent UI behavior (like the heart filling in pink sometimes, or not), and the number of likes going *down* instead of *up*. That and for compatibility, you may want to polyfill promises (maybe, up to you :) ).

Possibly related, it happens pretty consistently when you like, unlike, then relike a post.

![Bug Screenshot](https://user-images.githubusercontent.com/28788713/41662244-8887bdd8-7455-11e8-8871-b75b6ea6b328.png)
![Another Screen](https://user-images.githubusercontent.com/28788713/41662377-d7259668-7455-11e8-8d48-fceaeb4502f5.png)
![One More](https://user-images.githubusercontent.com/28788713/41662448-0c40cbc4-7456-11e8-8451-f5db5452dfef.png)

**Comment by dansup** [comment]
@trev-dev This has been fixed in the latest commits!
