### ISSUE TITLE
Issues viewing photos in “preview function” 

### ISSUE THREAD

**Issue by UnixPhonez** [pixelfed/pixelfed#3103]
Photo isn't being displayed in the preview function

Reproduce:
Go to a user's profile 
then click a photo (left click)
then click the photo again to expand (left click) 

System: 
Chromium (Brave) 

Instance:
Pixelfed.social 

Pixelfed Version: 
 v0.11.1

**Comment by dansup** [comment]
Fixed in latest commits!
