### ISSUE TITLE
My profile won't load after the first page

### ISSUE THREAD

**Issue by kaffeeringe** [pixelfed/pixelfed#3105]
My profile only shows the first 17 pics: https://pixelfed.de/kaffeeringe - Or is that just for me?

**Comment by dansup** [comment]
@kaffeeringe It's being caused by [this post](https://pixelfed.de/p/kaffeeringe/361877084087619566), try deleting it and it will resolve the issues. I'll work on a bug fix so this doesn't happen again!

**Comment by kaffeeringe** [comment]
Thank you!
