### ISSUE TITLE
Invalid redirection

### ISSUE THREAD

**Issue by sanpii** [pixelfed/pixelfed#311]
Hello,

I tried to install pixelfed, the installation itself work fine but when I open the index I get an invalid redirection error because `/` redirect to `/dashboard` (301) and `/dashboard` redirect to `/` (302).

Do you have an idea what’s broken?

**Comment by dansup** [comment]
@sanpii Did you set the proper .env variables like APP_URL ?

**Comment by sanpii** [comment]
@dansup I copied the `.env.example` file and modify it corresponding to my environment. Here the begin of my `.env`:

```sh
APP_NAME="PixelFed Test"
APP_ENV=local
APP_KEY=base64:8gNp8EhaDO/JyFJXAdcijjqkc/a/zeOWoX+zgnXEXPo=
APP_DEBUG=true
APP_URL=https://photos.homecomputing.fr

ADMIN_DOMAIN="photos.homecomputing.fr"
APP_DOMAIN="${APP_DOMAIN}"
```

**Comment by dansup** [comment]
@sanpii ```APP_DOMAIN="${APP_DOMAIN}"``` is invalid, that is self-referencing. Try ```APP_DOMAIN="photos.homecomputing.fr"```.

**Comment by sanpii** [comment]
@dansup Thank you.
