### ISSUE TITLE
Remove black background from PWA icon on iOS

### ISSUE THREAD

**Issue by bcye** [pixelfed/pixelfed#3111]
On iOS the App Icon is displayed with a black background, I'm guessing the icon is transparent and iOS gives it a black background because icons must have a specific shape.

If it's possible it might be good to use two icons, one for iOS and one for desktop/android in that case.

![image](https://user-images.githubusercontent.com/29666239/147809031-8b3849f5-30c0-4b07-8c10-a8e9ab771128.jpeg)

**Comment by trwnh** [comment]
this should have been solved by #3009

**Comment by bcye** [comment]
Do you know if the fix is deployed already to pixelfed.social?
