### ISSUE TITLE
Clicking on notifications in the Metro UI (the new UI) fails to navigate after the first time

### ISSUE THREAD

**Issue by zladuric** [pixelfed/pixelfed#3118]
I tried the new UI and if I click on the links in "Notifications" widget, it works the first time, but not in any subsequent time.

Steps to reproduce:
1. Open the pixelfed.social and log in. (Timeline opens)
2. Click on the "Try new UI" button. (New UI is loaded)
3. Click on one of the links in the "Notifications" widget. (you navigate to that post)
4. Click again on one of the links in the "Notifications" - **app fails to navigate**.

Bellow is the screenshot of the example. I did not test extensively, but could reproduce this on Firefox and Chrome on Fedora 34, tried scrolling deeper into notifications and clicking other links, it did not work.
FWIW right-clicking and opening in new tab does work.

I see this error in Chrome DevTools console:

     NavigationDuplicated: Avoided redundant navigation to current location: "/i/web/post/382591348991325356".

![image](https://user-images.githubusercontent.com/1014367/147955290-c08e316a-37af-4db8-8434-62c5306fcaa4.png)

Side question: contributing guidelines say that beside just a bug report, you'd welcome a pull request fixing it as well :) I may yet try it out (if I find the time), but is the bug report welcome even without the PR attached? Especially since I could not find a similar issue.

**Comment by dansup** [comment]
Fixed in latest commits!
