### ISSUE TITLE
[Bug] Regression: Wrong comment gets loaded on permalink

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#312]
Post by trwnh
- "time for a tall test."
- https://pixelfed.social/p/trwnh/1416

Comment by dansup on trwnh's post
- should say "test"
- instead shows "time for a tall test."
- https://pixelfed.social/p/dansup/1416/c/1457

Comment by trwnh on trwnh's post
- should say "test 20"
- instead shows "time for a tall test."
- https://pixelfed.social/p/trwnh/1416/c/1455

Aside from the wrong username being used in the URL (https://github.com/dansup/pixelfed/issues/51#issuecomment-394677430), the actual comment is not being displayed properly, and instead, is a copy of the original caption.

**Comment by dansup** [comment]
Fixed in latest commits
