### ISSUE TITLE
Small images get upscaled

### ISSUE THREAD

**Issue by inthreedee** [pixelfed/pixelfed#3120]
**Current behavior**
If an image is smaller than the sizes defined here, it gets upscaled:
https://github.com/pixelfed/pixelfed/blob/7a234ccd4c2a4390d61f32487fd6307ca903d6ce/app/Util/Media/Image.php#L36-L52

**Desired behavior**
Images smaller than that size should not be resized.

**Use-case**
An artist or photographer who wants to share their work, but have the images be on the smaller side to make them more useless to anyone who might want to steal and use the images without permission.

**Comment by dansup** [comment]
Fixed in latest commits!
