### ISSUE TITLE
[Bug] Only the first hashtag is counted in a post

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#313]
https://pixelfed.social/p/trwnh/4273
Clicking #waluigi will load the post in a search, but clicking #wa, #wah, #waa, and #nonbinary will not show the post in search results.

Post | Search
--- | ---
![image](https://user-images.githubusercontent.com/10606431/42072002-f2aebd5e-7b23-11e8-8649-29adb3b827ff.png) | ![image](https://user-images.githubusercontent.com/10606431/42072009-fe8e3c76-7b23-11e8-833b-b1591c956786.png)

**Comment by dansup** [comment]
@trwnh Fixed in latest commits!
