### ISSUE TITLE
New UI: Option to hide comments by default

### ISSUE THREAD

**Issue by jerrykan** [pixelfed/pixelfed#3130]
I like scrolling through feeds just looking at the pictures and generally don't care about the comments. If there is a comment on a post then it adds a lot of unnecessary scrolling/padding to get to the next picture. It would be nice if there was a option to make comments be hidden/collapsed by default.

**Comment by dansup** [comment]
Added in latest commits! Make sure you go to **UI Settings** and uncheck **Autoload Comments**
