### ISSUE TITLE
New UI: Glitches trying to load old pictures in personal(?) profile view

### ISSUE THREAD

**Issue by jerrykan** [pixelfed/pixelfed#3131]
When using the new UI to look at my personal profile it seems to glitch trying to load older pictures. When scrolling down it will load two sets of pictures, but on the third it glitches. The video should hopefully demonstrate what I mean

https://user-images.githubusercontent.com/377632/148484251-d80dcfb5-5ea6-4770-8303-1190b41f30f8.mp4

Tested with:
  - Firefox v95.0.1 (Linux/Debian Testing)
  - Chromium v93.0.4577.82 (Developer Build) (Linux/Debian Testing)

**Comment by dansup** [comment]
Fixed in latest commits!

**Comment by jerrykan** [comment]
FYI: I'm not sure if the committed fixes have been deployed or not, but I'm still experiencing this problem on pixelfed.social
