### ISSUE TITLE
"No Preview Available"

### ISSUE THREAD

**Issue by kaffeeringe** [pixelfed/pixelfed#3151]
![Screenshot 2022-01-12 at 16-21-26 kaffeeringe on pixelfed de](https://user-images.githubusercontent.com/367592/149169443-101fa481-0f21-474b-a8ef-62ab6ff6813f.png)
The Pixelfed-Instance I use had a problem some months ago. No preview-pictures were created. Now they are still missing in my profile:
https://pixelfed.de/kaffeeringe

It would be great if Pixelfed generates the missing previews instead of displaying "No Preview Available".

**Comment by ghost** [comment]
It also happens on our instance, can't debug why: https://pixelfed.graz.social/noxi

**Comment by dansup** [comment]
Fixed in latest commits! @hfte Seems like your instance isn't configured properly, wasn't able to locate media thumbnails which is a good indication that the horizon job queue is not running!
