### ISSUE TITLE
Can't see Followers-only Mastodon posts even if following the account

### ISSUE THREAD

**Issue by TyMick** [pixelfed/pixelfed#3152]
I'm testing [a Pixelfed account](https://pixelfed.social/TyMick) and [a Mastodon account](https://mastodon.social/@TyMick) together to see how interoperable they are, and it appears I can't see Followers-only photo posts from my Mastodon account on my Pixelfed account. Here are the steps I took:

1. Made my Pixelfed account public.
2. Turned off "Require follow requests" on my Mastodon account.
3. Followed my Mastodon account from my Pixelfed account.
4. Posted a photo with "Public" privacy from my Mastodon account.
5. Refreshed my feed on Pixelfed and verified that my Pixelfed account sees that public photo in its feed.
6. Posted a photo with "Followers-only" privacy from my Mastodon account.
7. Refreshed my feed on Pixelfed many times but never saw the Followers-only photo post show up.

**Comment by TyMick** [comment]
For what it's worth, I have learned that it works the other way around; that is, my Mastodon account can see "Followers only" posts from my Pixelfed account.

**Comment by spaceottercode** [comment]
same. follower-only posts, from people on Mastodon whom  you follow from PixelFed, not showing up on my PixelFed feed.
