### ISSUE TITLE
Can't see text-only posts in Home timeline

### ISSUE THREAD

**Issue by TyMick** [pixelfed/pixelfed#3153]
I'm testing [a Pixelfed account](https://pixelfed.social/TyMick) and [a Mastodon account](https://mastodon.social/@TyMick) together to see how interoperable they are, and it appears I can't see text-only posts from my Mastodon account in my Pixelfed timeline even though I've enabled the "Show text-only posts" setting. Here are the steps I took:

1. Made my Pixelfed account public.
2. In my [Timeline Settings](https://pixelfed.social/settings/timeline), enabled "Show text-only posts" and clicked "Submit".
2. Turned off "Require follow requests" on my Mastodon account.
3. Followed my Mastodon account from my Pixelfed account.
4. Posted a photo with "Public" privacy from my Mastodon account.
5. Refreshed my feed on Pixelfed and verified that my Pixelfed account sees that photo in its feed.
6. Posted a text-only post with "Public" privacy from my Mastodon account.
7. Refreshed my feed on Pixelfed many times but never saw the text post show up.

**Comment by jorgesat** [comment]
Maybe a good idea to include a kind of text renderer (with color backgrounds, nice typography) for this kind of posts - large texts with a "Read more" button below.

Also it would be great [feature request] to be able to publish text-only posts on pixelfed with such rendered text add-on...

**Comment by Coo-ops** [comment]
Hey folks, same issue here. Expected to see text posts on my Mastodon account but didn't see anything.

Was kinda hoping to not require a Mastodon and a Pixelfed instance, but to just use Pixelfed for both.

**Comment by jhenshaw** [comment]
Curious to know if @dansup's vision is to support text-only feeds, and what the scope is. Limited to local timeline only? If so, why?

**Comment by ploum** [comment]
Is the "not planned" an official position that text-only posts will not be displayed in pixelfed timelines ?

On some instance, those text-only appears only if they have been boosted (which is weird). Is that expected ?
