### ISSUE TITLE
Approving follow requests from Mastodon is very spotty

### ISSUE THREAD

**Issue by TyMick** [pixelfed/pixelfed#3154]
I'm testing [a Pixelfed account](https://pixelfed.social/TyMick) and [a Mastodon account](https://mastodon.social/@TyMick) together to see how interoperable they are, and I've learned that after making my Pixelfed account private, its handling of follow requests from my Mastodon account is very spotty. The first time I sent a follow request from Mastodon, my Pixelfed account was able to approve it just fine. After unfollowing and trying a second time, though, my Pixelfed account auto-approved the follow request without asking me. The same thing happened a third time. Now, trying a fourth time, I received the follow request in my Pixelfed notifications again and approved it, but this time my Mastodon account won't register that the follow request was approved, and it can't see posts from my Pixelfed account sent after that.

Here are the steps I took:

### Round 1

1. Made my Pixelfed account private.
2. Left the "Require follow requests" setting off on my Mastodon account.
3. Ensured that neither account was yet following the other.
4. In Mastodon, found my Pixelfed account, which showed a 🔒 next to the username. I then clicked the "Follow" button, after which the button text changed to "Cancel follow request".
5. In Pixelfed, refreshed the page and saw that I'd received a follow request from my Mastodon account, which I approved. I then navigated to my followers list and confirmed that my Mastodon account was in that list.
6. In Mastodon, refreshed the page and saw the text on the Follow button change from "Cancel follow request" (before refresh) to "Unfollow" (after refresh). Then, I clicked the "Unfollow" button.
7. In Pixelfed, refreshed the page and saw that my Mastodon account was no longer in the followers list.

### Rounds 2 and 3

1. In Mastodon, found my Pixelfed account, which showed a 🔒 next to the username. I then clicked the "Follow" button, after which the button text changed to "Cancel follow request".
2. In Pixelfed, refreshed the page and saw no follow request notification. Instead, though, I had a notification that my Mastodon account had simply started following me. I then went to my [privacy settings](https://pixelfed.social/settings/privacy) to make sure that my account was still set to private. It was. I then went to my followers list and saw my Mastodon account in the list.
3. In Mastodon, refreshed the page and saw the text on the Follow button change from "Cancel follow request" (before refresh) to "Unfollow" (after refresh). Then, I clicked the "Unfollow" button.
4. In Pixelfed, refreshed the page and saw that my Mastodon account was no longer in the followers list.

### Round 4

1. In Mastodon, found my Pixelfed account, which showed a 🔒 next to the username. I then clicked the "Follow" button, after which the button text changed to "Cancel follow request".
2. In Pixelfed, refreshed the page and saw that I'd received a follow request from my Mastodon account, which I approved. I then navigated to my followers list and confirmed that my Mastodon account was in that list.
3. In Mastodon, refreshed the page and saw the "Cancel follow request" button remain the same. I then refreshed the page a few more times, and the button still read "Cancel follow request" after each time.
4. In Pixelfed, posted a photo just in case a new post had to come through for Mastodon to see that the follow request had been approved.
5. In Mastodon, refreshed the page a few more times, but nothing changed. I then went to my "Home" feed but did not see the new Pixelfed post there.

**Comment by stephen304** [comment]
I think I'm having #3 going on between my layer8.space mastodon account and my selfhosted pixelfed. Just stuck on cancel follow request on the mastodon side.

**Comment by MrAn0nym** [comment]
Can you try if this is still an issue, there have been changes recently iirc

**Comment by stephen304** [comment]
@MrAn0nym I'm running 11.3 and it seems I still can't follow my private pixelfed account from mastodon. When trying to accept on the pixelfed side, I believe it used to show that it succeeded but never propagated to the mastodon side, but now when I try to accept the follow request in pixelfed, I get a 500 error:

```
{"message":"The given data was invalid.","errors":{"id":["The id field is required."]}}
```

It seems no ID is passed in the request

**Comment by MrAn0nym** [comment]
Are you running a private instance or a public one? 
If it's a private one try pulling the latest changes from the dev branch, if it's the latter which instance is it

**Comment by MrAn0nym** [comment]
```
{"message":"The given data was invalid.","errors":{"id":["The id field is required."]}
```
This error is probably related to #3530

**Comment by stephen304** [comment]
@MrAn0nym That seems to work! I accidentally forgot to apply migrations the first time I tried. The only thing I noticed is that you have to go into the notifications view to see the request - not sure if it's supposed to show up in the notification side-box or somewhere else in the main UI.
