### ISSUE TITLE
Please make Pixelfed use much more screen space for photos

### ISSUE THREAD

**Issue by pezcurrel** [pixelfed/pixelfed#3157]
Hi and first of all thanks for the great job. I think it would be good if Pixelfed used much more screen space for photos than it currently does (particularly with Metro 2.0), both on desktops and on mobiles. On desktop I think it would be better to have only one "tools" column, and to use all the left space for displaying the photos. On mobile, I think the previous UI version was better at displaying photos: it didn't enclose them into borders, so the little screen space was optimally used. I made a little and very basic html+css template sketch to visually explain how I think the template could be arranged: https://mastodon.help/cesto/pixelfed_ui_template_sketch/ (it uses all the disposable horizontal and vertical screen space). I think that using much more screen space for photos would benefit Pixelfed and would set it apart from other photo sharing platforms, giving it a more defined identity, and a better one (like in "Pixelfed gives you more on-screen space for your photos than instagram").

**Comment by pezcurrel** [comment]
I changed a bit the css to make the "photobox" enlarge to a maximum of 1440px, the current pixelfed maximum width for photos (images larger than 1440px get scaled to 1440px width when one uploads them).

**Comment by justinharkey** [comment]
I agree, the Metro 2.0 version seems okay but the pictures all get letterboxed and feel less important than before. I like pretty much everything else about Metro 2.0.

**Comment by dansup** [comment]
@justinharkey @pezcurrel Fixed in c55eeac8! Make sure you go to **UI Settings** and uncheck **Compact Media Previews**
