### ISSUE TITLE
Add Backblaze support to config/backup.php

### ISSUE THREAD

**Issue by virtadpt** [pixelfed/pixelfed#316]
How difficult would it be to add support for Backblaze B2 to config/backup.php as a service backup solution?

**Comment by dansup** [comment]
@virtadpt We might be able to support this via https://github.com/gliterd/flysystem-backblaze

**Comment by virtadpt** [comment]
Excellent!

**Comment by dansup** [comment]
You can use backblaze with the driver listed above!
