### ISSUE TITLE
Filter notifications

### ISSUE THREAD

**Issue by kaffeeringe** [pixelfed/pixelfed#3160]
I sometimes miss comments because there are so many more likes. It would be cool, if there were at least two tabs in notifications: "All" and "Comments"

**Comment by mgrzeca** [comment]
A good solution to this inconvenience would be an aggregated notification feed. A sequence of multiple consecutive likes for the same post could be aggregated into a notification like "@someuser, @someotheruser and 13 others liked your post". A sequence of multiple consecutive likes of many of your posts by one user could be aggregated into a notification like "@someone liked 13 of your posts". This way, it would be possible to keep a single notification feed, and at the same time it would be much easier than now to find the comment notification.

**Comment by kaffeeringe** [comment]
I like the solution in the current UI. Thank you!
