### ISSUE TITLE
File upload size unknown

### ISSUE THREAD

**Issue by cloo** [pixelfed/pixelfed#3162]
Pixelfed often fails to upload videos due to low default upload sizes. 
Failure results in a generic "unexpected error": 
![220117-185333](https://user-images.githubusercontent.com/651760/149810037-a5c138eb-adfb-4938-bfc4-d213062a2de2.png)

Also by default, allowed file sizes are not stated in server description. 
I propose to state max file size near upload button, e.g. with or instead text ("share up to 50 photos or videos"). 

 
![220117-185950](https://user-images.githubusercontent.com/651760/149811259-d57c4ace-5cff-474d-82f6-666288c93029.png)

In case of choosing too big files, a dialog could show a meaningful warning about too large file selection even before brutally trying to upload them. You know how this normally feels, no need to describe I guess.

**Comment by Strubbl** [comment]
There are two file upload limits. There is a file upload limit by your webserver and by pixelfed itself.

**Comment by cloo** [comment]
It makes no sense to tell the user how many limits there are. User must only know how big files he can actually upload, so he would not have bad experience. Also user must be able understand why the error is shown. 
At first I thought it was a defective system: firstly because it said so, and secondly because it is so common to warn about too big files.

**Comment by Strubbl** [comment]
Was a hint for the developers to check both values not only one.

**Comment by dansup** [comment]
@cloo Fixed in the latest commits!
![Screen Shot 2022-01-22 at 9 20 00 PM](https://user-images.githubusercontent.com/877217/150664669-8c9c8d87-5b5c-41e8-b7f2-07e1221e41a5.png)

@Strubbl Good point, will add a warning to the admin dashboard!
