### ISSUE TITLE
Wrong followers count in user profilepage

### ISSUE THREAD

**Issue by verymilan** [pixelfed/pixelfed#3163]
Hi there, i was just notified by a user that they've got 9 followers displayed (as count) while they actually have 11. The modal shows all 11 users and the count in the adminpage is correct as well. Couldn't see any logs so far.

After deleting some follow...ings, where instance was down or something, the "follwing" count should have changed to 16 as it is in the admin page, but the public facing profile counter still stated 19.

**Comment by verymilan** [comment]
Update: they report that it mostly corrected itself but the "Following" number still is one too many. I cannot open that list on their public profile (animation spins forever) and also don't see any logs. 
The browser report a 404 on `/api/pixelfed/v1/accounts/199794474296152064/following?page=1`.

In the admin interface, that number is not incorrect tho.

**Comment by dansup** [comment]
Fixed in 4b6effb9. After updating to the latest commits, please run `php artisan cache:clear` and re-open this issue if you still experience this issue!

**Comment by ShinIce** [comment]
good morning :)

unfortunately I can't see any change on my profile :-/ in fact the "following" count, on the public facing site, is still wrong by one and if I try to open that list from `?md=following` I still see the 404 errors posted by @verymilan

**Comment by ShinIce** [comment]
hey @verymilan , could you please reopen the issue as I can't? thx :)

**Comment by verymilan** [comment]
sorry @ShinIce i can't. @dansup?

**Comment by ShinIce** [comment]
hey @dansup , did you had the possibility to have a second look at this issue?

**Comment by joho1968** [comment]
Not sure if this is related, but looking at the "Home feed" for a user, it says "0 following  0 followers" in the upper left hand corner. That account is following one account. If the user, however, hovers over the profile it's actually following on that timeline, the "popup card" says that that account has one follower, which is correct.

The same problem exists in both the new and the "previous" UI.

![image](https://user-images.githubusercontent.com/3135227/209953430-8100d129-708e-4d9a-8cfd-0dc647dabb2d.png)

**Comment by mitexleo** [comment]
It's happening again

**Comment by ghost** [comment]
I am facing the same issue with my personal instance even now. At the latest in the dev branch, I have nobody following me, and I follow three. However, my profile page shows 2 followers and 0 following. If I click on the followers, it takes me to a page where it is loading followers with a spinning widget, but nothing happens. If I click on the following, I get only one account. It's wrong in both the old and new UI.

That said, if I go into my profile screen and look at Relationships, it's correct.

I've tried php artisan cache:clear, and it doesn't seem to have made a lick of difference. Frustrating!

**Comment by ShinIce** [comment]
> Frustrating!

indeed, but tbh I doubt we will see any changes here...
