### ISSUE TITLE
Compliance with AGPL

### ISSUE THREAD

**Issue by hellcp** [pixelfed/pixelfed#317]
AGPL has a few quirks that require some work:

* Notifications (headers) with a date of modifications (might as well be changelog) https://github.com/dansup/pixelfed/blob/dev/LICENSE#L202-L203 , https://github.com/dansup/pixelfed/blob/dev/LICENSE#L205-L208 and https://github.com/dansup/pixelfed/blob/dev/LICENSE#L627-L648
* License of software has to be visible in UI https://github.com/dansup/pixelfed/blob/dev/LICENSE#L218-L221 and https://github.com/dansup/pixelfed/blob/dev/LICENSE#L627-L648

**Comment by kpcyrd** [comment]
The license you are quoting is the AGPL of pixelfed, you need to comply with that if you fork pixelfed. Also note that those conditions are in the "Conveying Modified Source Versions" section, which pixelfed doesn't do for its dependencies.

You can find a copy of the LGPL here: https://www.gnu.org/licenses/lgpl-3.0.en.html

If you have any questions regarding the license of the pixelfed dependencies just let me know and I'm going to reopen this issue. :)

**Comment by hellcp** [comment]
Yeah, blame my mind for being dumb.
The issue here is that modifications of the code are introduced into the codebase by every contributor.

https://github.com/dansup/pixelfed/blob/dev/LICENSE#L91-L98 and https://github.com/dansup/pixelfed/blob/dev/LICENSE#L620-L657 explain that my points are still valid, with showing license in UI and in headers of files licensed under AGPL.

**Comment by kpcyrd** [comment]
The first one is in the "Definitions" section and defines the term "Appropriate Legal Notices" that is used in section 5.

The second one is a short description how you can apply the AGPL to your project, but is not part of the terms and conditions as indicated by `END OF TERMS AND CONDITIONS` right above that. :)
