### ISSUE TITLE
Metro 2.0: Image area ratio is too wide for most images

### ISSUE THREAD

**Issue by justinharkey** [pixelfed/pixelfed#3170]
In Metro 2.0 the image ratio for image posts appears to be 16:10 but most images and videos being posted are 16:9. These leads to letterboxing on nearly every post on the timeline. The image areas are responsive so this is less of an issue at smaller resolutions but anything wider than 1327 or so results in letterboxing. It also happens when the view switches to single column in lower resolutions.

This was not an issue in the older version. 

Potential options: Remove max-height restriction, change max-height restriction to better fit most images. Open to further discussions or justifications as to why it is set this way. Also open to contributing code once discussion happens.

Screen resolution: 1920x1080
Browser: Firefox 96.0.1
OS: Windows 10

**Comment by dansup** [comment]
Fixed in the latest commits, in addition you can now click on a photo to load the full version.
