### ISSUE TITLE
Fix i18n

### ISSUE THREAD

**Issue by gunchleoc** [pixelfed/pixelfed#3174]
Hi,

there are multiple comments on Crowdin regarding the strings to translate, e.g. this one:

https://translate.pixelfed.org/translate/pixelfed/9/en-gd#87

The problems are mostly of 2 categories:

1. Translators need full sentences, e.g. "%1$s liked your %1$2" (or even better: ""%s liked your post" instead of just "liked", "your", "post".
2. Plural forms (c.f. https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html). We don't have many of these, so the full sentence fixes should be prioritized.

I tried to have a look, but I don't do JavaScript often and the minified script is not something I can work with easily.

**Comment by comradekingu** [comment]
I don't understand why this project doesn't use Weblate instead of the very non-ethical Crowdin.
