### ISSUE TITLE
admin panel : Something went wrong after updating to the latest commits 

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#3188]
After updating today to the latest commits and trying to access the admin panel “something went wrong” appears 

hash code cannot be diagnosed after copying since the admin panel is not accessible

**Comment by dansup** [comment]
Check the logs in `storage/logs/laravel.log` or run `php artisan tinker` then `decrypt('PAYLOAD HERE')` to decrypt the payload.

**Comment by ghost** [comment]
@dansup 

it’s me spacemag from discord 🧐👻

I’m sorry I’m not able to log i have reset my phone and don’t have access to terminal or CLI I’m requesting if you could self diagnose this if possible I did not have this issue before updating to latest commits recently before 2 days 

thanks
