### ISSUE TITLE
Atom feed doesn't update when posting multiple images at once

### ISSUE THREAD

**Issue by tebjan** [pixelfed/pixelfed#3193]
Hello, my Atom feed doesn't update... My profile has two posts, but the Atom feed has only one entry. What could be the cause of this?

https://pixelfed.social/tebjan

https://pixelfed.social/users/tebjan.atom

EDIT: The issue seems to be a post with multiple images. I've just made a new one with just one image and that one is now visible in the feed.

**Comment by raphraph** [comment]
Same on my feed.
It encourages in posting multiple (less valuable imho) posts for a set of pics instead of a single (more valuable) post in order to "feed" the feed...

**Comment by aubguillemette** [comment]
Same here, would be nice if the Atom feed would include posts with multiple images.

**Comment by niccokunzmann** [comment]
Searching...
Code:
https://github.com/pixelfed/pixelfed/blob/5d9b6863b66f092100380f88d00df65086e4a1d1/resources/views/atom/user.blade.php#L31

Generated code:

```
		<summary type="html">
		<![CDATA[
			<img id="rss_item_1" src="https://pix.toot.wales/storage/m/_v2/454898839954469424/3c6c7d1ab-ede048/odnDv854NNZE/G42QMeKxnWB0tJaDSRA8NNusyTGChcwSXnGk4ofv.jpg" alt="">
			<p style="padding:10px;">A little update: several outdoor signs for the &lt;a href=&quot;https://pix.toot.wales/discover/tags/INCC?src=hash&quot; title=&quot;#INCC&quot; class=&quot;u-url hashtag&quot; rel=&quot;external nofollow noopener&quot;&gt;#INCC&lt;/a&gt; are ready to be hung up. Made in the &lt;a href=&quot;https://pix.toot.wales/discover/tags/makerspace?src=hash&quot; title=&quot;#makerspace&quot; class=&quot;u-url hashtag&quot; rel=&quot;external nofollow noopener&quot;&gt;#makerspace&lt;/a&gt;!</p>
		  ]]>
		</summary>
```

What would the optimal feed look like ... one entry with several pictures? One entry per picture?

This claims that they should be embedded differently: https://perishablepress.com/feed-your-image-via-atom-or-rss/
```
<channel>
	<image>
		<url>http://domain.tld/path/site_logo.jpg</url> // *required! - the URL of the image
		<title>The alt attribute of the image</title>   // *required! - the image alt attribute
		<link>http://domain.tld/my_blog/</link>         // *required! - the URL of the website
		<width>111</width>                              // the image width
		<height>33</height>                             // the image height
		<description>An amazing website</description>   // the link title attribute
	</image>
</channel>
```

This is a nice commit as it also modifies the way the database is accessed: https://github.com/pixelfed/pixelfed/commit/5d9b6863

I am wondering: There are different filters:

https://github.com/pixelfed/pixelfed/commit/5d9b6863#diff-400ac01eb77aef336811aa65304b7cd528c2b436a580f54e18147a401069ca01R203-R216

```
	                ->whereType('photo')
			->latest()
			->take(10)
			->get()
			->map(function($status) {
				return StatusService::get($status->id);
			})
			->filter(function($status) {
				return $status &&
					isset($status['account']) &&
					isset($status['media_attachments']) &&
					count($status['media_attachments']);
			})
			->values();
```
-----

## Looking though [the filters of statuses and type](https://github.com/pixelfed/pixelfed/search?p=7&q=statuses+type)

Learning:
- So, this will only generate 10 entries - that might not be what we want
- `count($status['media_attachments']);` and these should be ok - just means that there are some
- `->whereType('photo')` - seems like this one can mean something different - maybe there is a special one for several photos?

Other filters:

[$profile->statuses()->whereHas('media')](https://github.com/pixelfed/pixelfed/blob/f5260902293b35c830c865f5bc88162ae6e60f57/app/Transformer/ActivityPub/ProfileOutbox.php#L15)
related: [->whereType('photo') ->whereScope('public')](https://github.com/pixelfed/pixelfed/blob/f5260902293b35c830c865f5bc88162ae6e60f57/app/Transformer/Api/AccountWithStatusesTransformer.php#L46)
and [same](https://github.com/pixelfed/pixelfed/blob/ff1a12cdd795786944701016b6d855ee88035b93/app/Services/DiscoverService.php#L16)
AND **WHOHOO**

[->whereIn('type', ['photo', 'photo:album', 'video', 'video:album', 'photo:video:album'])](https://github.com/pixelfed/pixelfed/blob/f5260902293b35c830c865f5bc88162ae6e60f57/app/Console/Commands/FixStatusCount.php#L46)
If that is the case, there are other places where introducing a new type creates errors.

Here, we have another filter:
[->whereIn('type', ['photo','photo:album','video'])](https://github.com/pixelfed/pixelfed/blob/eaddb2147a1b3b0b3d6701b76378a8329d6490d3/app/Http/Controllers/DiscoverController.php#L155) missing other albums...

[->whereIn('type', ['photo', 'video','photo:album'])](https://github.com/pixelfed/pixelfed/blob/e25248b2300271be175743d82641f34307e9c231/app/Http/Controllers/StatusController.php#L126)

----

https://github.com/pixelfed/pixelfed/blob/639c7117f41ee98256fe9745dfe2162d6d79e586/resources/views/admin/settings/home.blade.php#L227 suggests that the album actually is a collection of several photos




## Summary

1. there is inconsistency in the code about when to use photo (old) and photo:album and the rest
2. there are only 10 posts retrieved (latest)
3. adding photo albums (my guess) will exclude videos and thus also create a new issue
4. only the first picture is embedded in the atom feed
5. there is no documentation about the types in the database (and thus divergent usage, see (1))

I guess, I would like some feedback on this...

**Comment by raphraph** [comment]
Thanks for taking a look at this issue. I'm not a dev so I won't be able to help you so much for code decisions.

Maybe one way of going forward with post with multiple images (is this a `photo:album` ?) is to only show one image in the atom feed and treat the post as if it was a classic post with only one image. I suppose that by following the link in the atom feed to the original post one would realize that it is actually a post with multiple images.

To me this would be an acceptable (temporary ?) user experience.

**Comment by niccokunzmann** [comment]
I think, when I get feedback on the two pull requests - they should do 
that: one image (photo or album) and not restricting to 10 but all.

**Comment by raphraph** [comment]
I just wanted to add that I realized that when using the embed snippet proposed by pixelfed (in the old UI only apparently until now), the snippet also previews only posts without multiple images. I didn't check so I don't know if fixing the atom feed also fixes the embedded posts.

```
<iframe src="https://pix.diaspodon.fr/username/embed" class="pixelfed__embed" style="max-width: 100%; border: 0" width="400" allowfullscreen="allowfullscreen"></iframe>
<script async defer src="https://pix.diaspodon.fr/embed.js"></script>
```

**Comment by dansup** [comment]
Fixed in https://github.com/pixelfed/pixelfed/commit/1c105a6ce3ae7866678a124054da15dc0d21e47b

**Comment by aubguillemette** [comment]
Thank you very much, this is really appreciated! Happy 2024!

**Comment by niccokunzmann** [comment]
For me, this hints at copy&paste mistakes. I think, the queries might be worth consolidating somehow.
