### ISSUE TITLE
Image preview size regression introduced in the latest commit

### ISSUE THREAD

**Issue by mgrzeca** [pixelfed/pixelfed#3198]
The last commit breaks portrait photos even more than the previous ones. Additionally, it also breaks photos in landscape orientation. The option to disable letterboxing has disappeared from the UI settings. The problem affects both the desktop and mobile, but is more of a pain on mobile browsers. The media area of the post has a fixed aspect ratio and does not adapt to the dimensions / aspect ratio of the content.

**Comment by mgrzeca** [comment]
The comparison of the old and new UI in the case of a desktop browser for a typical 4/5 portrait photo looks like this:

![old UI](https://user-images.githubusercontent.com/2249297/151788942-01bfb229-3912-45b2-a599-b66982833f76.png)
![MetroUI 2.0 with the latest commit](https://user-images.githubusercontent.com/2249297/151788956-4ec9add7-499f-48e6-806e-89915497c170.png)

The image preview in MetroUI 2.0 with the latest commit is so tiny that it is barely visible. Additionally, this blurry background image distracts attention from the actual image and causes rapid eye fatigue.

**Comment by mgrzeca** [comment]
The same for the 2/3 portrait photo and the mobile browser. The picture from MetroUI 2.0 is too small to even fill the media area of the post. A glitch is visible in the background. My eyes hurt from looking at such a small photo against a large blurred background.

<img src="https://user-images.githubusercontent.com/2249297/151790947-d0cc17a4-abe6-423f-b6a0-3608aaef6263.PNG" width="200px"> <img src="https://user-images.githubusercontent.com/2249297/151790917-f9764ad5-8a72-4955-8055-fb9521cb4657.PNG" width="200px">

**Comment by mgrzeca** [comment]
Next example, a 4/3 landscape photo in a desktop browser:

![Zrzut ekranu 2022-01-31 o 13 43 31](https://user-images.githubusercontent.com/2249297/151796028-871cc8e7-dbf2-45fd-a086-ce0764d984e9.png)
![Zrzut ekranu 2022-01-31 o 13 43 34](https://user-images.githubusercontent.com/2249297/151796038-b2e95c7c-8d22-45af-9f40-dd3543f6a136.png)

**Comment by mgrzeca** [comment]
Another example, a square photo in a desktop browser:

![Zrzut ekranu 2022-01-31 o 13 47 32](https://user-images.githubusercontent.com/2249297/151796500-baad483c-fa0d-4a10-bb8f-67e93c8cde55.png)
![Zrzut ekranu 2022-01-31 o 13 47 36](https://user-images.githubusercontent.com/2249297/151796521-289d1eec-9d05-410e-804e-8bd8c21bab3d.png)

**Comment by mgrzeca** [comment]
A photo with embedded frames looks interesting, like some sort of a visual glitch:

![Zrzut ekranu 2022-01-31 o 13 51 39](https://user-images.githubusercontent.com/2249297/151796857-6c66645a-c22f-481a-a633-4e949efd8cab.png)
![Zrzut ekranu 2022-01-31 o 13 51 36](https://user-images.githubusercontent.com/2249297/151796873-810a9840-291f-4cab-8801-61f590ed2dfd.png)

**Comment by mgrzeca** [comment]
So far, I have not been able to find even one case in which the preview of the photo in MetroUI 2.0 would look better than in the old UI. Maybe i'm missing something obvious, but what are the actual benefits of the new UI when it comes to viewing photos?

**Comment by mgrzeca** [comment]
The latest commit almost fixes the regression. Unchecking "Short Media" in UI options restores the previous way of fitting images to the surrounding container, but the photos are still letterboxed in a fixed area of 690x400px.

**Comment by dansup** [comment]
@mgrzeca Fixed in c55eeac8! Make sure you go to **UI Settings** and uncheck **Compact Media Previews**
