### ISSUE TITLE
Feature request: Add to collection in New Post

### ISSUE THREAD

**Issue by SathyaBhat** [pixelfed/pixelfed#3199]
I think being able to add a new post and to a collection would reduce a lot of friction in categorizing. I envision an option similar to "Add  Location", where we could type in a collection and Pixelfed could provide an autocomplete text box.

![image](https://user-images.githubusercontent.com/25424/151843431-5780a954-892d-4365-8c04-443bbb34648c.png)

**Comment by dansup** [comment]
Added in #3251!
