### ISSUE TITLE
Feature request: justified gallery layout view in profiles, similar to Flickr / 500px

### ISSUE THREAD

**Issue by mgrzeca** [pixelfed/pixelfed#3205]
There is a JS library available under the MIT license that generates such kind of view: https://github.com/miromannino/Justified-Gallery/

Grid view only works well for square photos or photos with aspect ratios close to 1.0. A Masonry layout is great for portrait photos, but not necessarily good for landscape photos. A justified gallery layout is good for landscape photos, but not necessarily good for portrait photos. These 3 layouts complement each other pretty well.

**Comment by trwnh** [comment]
superseded by #3598
