### ISSUE TITLE
Feature request: add block / mute user to the "..." menu of the post.

### ISSUE THREAD

**Issue by mgrzeca** [pixelfed/pixelfed#3207]
This will allow you to block unwanted content faster and more conveniently directly from the timeline.

**Comment by AramLoosman** [comment]
Came here to ask for this feature. I do not want to visit a profile to be able to mute/block them. I'd rather do it directly from the timeline.

**Comment by piebob** [comment]
yes, same! too many clicks and then you lose your place in the TL.

**Comment by okpierre** [comment]
Mute/block from menu was submitted and waiting for approval/merge 

If you want to give it a try see this
https://github.com/pixelfed/pixelfed/pull/4677/commits/455bd1bbce1d32c136b582b71d0740efb479529c 

@mgrzeca @AramLoosman @piebob
