### ISSUE TITLE
Views do not keep state when navigating to other views

### ISSUE THREAD

**Issue by mgrzeca** [pixelfed/pixelfed#3208]
Metro 2.0 was supposed to be a SPA, but it does not exactly behave like a SPA. For example, opening a user profile from a post on a timeline and going back will reload the entire timeline and scroll back to the top. Returning from an open profile should go back to where you opened the profile, without reloading the whole thing.

**Comment by dansup** [comment]
@mgrzeca Metro 2.0 is still a work in progress. We are not caching timelines like we do profiles or posts yet, and there is a good reason!

The websocket/realtime streaming endpoints are not ready, and we don't want to poll for updates, so that is why timelines are reloaded.
