### ISSUE TITLE
"Error: The requested image could not be loaded" on posts marked NSFW

### ISSUE THREAD

**Issue by mgrzeca** [pixelfed/pixelfed#3209]
The following error shows up every time trying to display hidden NSFW media:

<img width="711" alt="Zrzut ekranu 2022-02-4 o 11 34 35" src="https://user-images.githubusercontent.com/2249297/152514761-a14f67f6-7168-4724-9b7e-091779c48fdc.png">

Nevertheless, the image appears as soon as I close the error popup:

<img width="711" alt="Zrzut ekranu 2022-02-4 o 11 34 45" src="https://user-images.githubusercontent.com/2249297/152514890-e89e09ce-6cb5-4881-b2cc-7a26a2a9b4c4.png">

**Comment by dansup** [comment]
Which browser are you using?

**Comment by mgrzeca** [comment]
Safari 15.2 / macOS 12.1

**Comment by mgrzeca** [comment]
It looks like this issue no longer occurs in 0f385b45b988e22c59b9aa740c87b75ccfa18a19 🤷‍♂️

**Comment by mozillamonks** [comment]
Seeing this again on v0.11.4
