### ISSUE TITLE
Metro 2.0: Delete comments out of order

### ISSUE THREAD

**Issue by forenta** [pixelfed/pixelfed#3217]
Pixelfed v0.11.2 Metro 2.0 Beta on pixelfed.photos

Since I mistyped a comment, I had rewritten it and wanted to remove the previous comment.
Although the function is available in the Metro design and no error is reported, the comment is still there even when checking via Ctrl+F5 as well as on another device. Switching to the old interface made it possible to remove the comment.

**Comment by dansup** [comment]
This has been fixed in the latest commits, your instance admin should update!
