### ISSUE TITLE
Media tab

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#3219]
When I click on the Media tab, this error comes out.

![image](https://user-images.githubusercontent.com/16371257/152940723-f8451ee5-b58b-43cc-a9d8-4f78dd601653.png)

And this is the diagnostic details.

eyJpdiI6IjhoUWptOXhGbUtoRzZhNzIvVzRGaWc9PSIsInZhbHVlIjoiQjBsYkZLWnFBcEZPbWZ5ckZyazFLcVg2dXpjKzdxNCtrNmYxNEMxT3h2cTJKZHF0Nys4Mk5FS0NHTEZkYjFleExKOEZYdG02VEkzRVBYUENPbEs5T0FGZk1xZjdPZ1BFbEpMQzYrVmI2YlU4V1ZUNFcvV0xhQlQzYlh2RWZFUXkiLCJtYWMiOiI0YjY4ZGE3NDU5YmNkNTAyYjc5YmQ1YzQwZDY2ZDMyNDk2ZDMwMTlhZGU2ZjI3NWZkN2JjMTk0OTMzYjE2OWZkIiwidGFnIjoiIn0=

**Comment by dansup** [comment]
You need to decode that yourself using the Admin Dashboard -> Diagnostics page or by running `php artisan tinker` and then `decrypt('eyJpdiI6IjhoUWptOXhGbUtoRzZhNzIvVzRGaWc9PSIsInZhbHVlIjoiQjBsYkZLWnFBcEZPbWZ5ckZyazFLcVg2dXpjKzdxNCtrNmYxNEMxT3h2cTJKZHF0Nys4Mk5FS0NHTEZkYjFleExKOEZYdG02VEkzRVBYUENPbEs5T0FGZk1xZjdPZ1BFbEpMQzYrVmI2YlU4V1ZUNFcvV0xhQlQzYlh2RWZFUXkiLCJtYWMiOiI0YjY4ZGE3NDU5YmNkNTAyYjc5YmQ1YzQwZDY2ZDMyNDk2ZDMwMTlhZGU2ZjI3NWZkN2JjMTk0OTMzYjE2OWZkIiwidGFnIjoiIn0=')`

**Comment by dansup** [comment]
@alaris1983 Oops, accidentally closed this. After you decrypt it, please paste the decoded message here!

**Comment by ghost** [comment]
@dansup I think I don't have access to Admin Dashboard...

Edit: It worked now
