### ISSUE TITLE
[Issue] Adding posts to collections results in "Invalid URL" error

### ISSUE THREAD

**Issue by smlpt** [pixelfed/pixelfed#3230]
When trying to add a post to an existing collection via the "add photo" button, I get an error message, saying the entered URL is invalid. The website then immediately reloads without any user interaction on the error message. I made sure that:
- the post I'm trying to add is public and belongs to my instance
- the collection contains less than the maximum number of allowed posts (in fact it only contains two posts yet)
- the collection is set to public as well
- the URL looks like the example URL (https:[instance]/p/[user]/[post ID]
- this happens with the old and the new UI
- this happens with all posts

Selecting one of the recent images in the "add photo" dialogue however works flawlessly. Am I missing something obvious here or is this a bug? My instance is pixelfed.de. I'll gladly provide more information if needed.

**Comment by realpixelcode** [comment]
I can confirm this issue. It also occurs when creating a brand new collection. Currently, the Collection feature is completely useless for me due to this.
