### ISSUE TITLE
Empty comment list

### ISSUE THREAD

**Issue by kakuy** [pixelfed/pixelfed#3241]
When I open a post through the normal web ui ( https://{host}/i/web/post/{id} I can see there are comments but I can't see the comments below. These comments are relayed event to remote instances.

On the contrary, when I open the same post through the public ui ( https://{host}/p/{user}/{id} ), comments show normally on the right side.

When I publish a comment with the https://{host}/i/web/post/{id} ui, it shows immediately but it disappears as soon as I reload the page.

I use pixelfed [cc9fcae69cb6323f8adbababaddc757a17033864] and PosrgreSQL.

**Comment by trwnh** [comment]
fixed at some point, i think?
