### ISSUE TITLE
Selecting a post ends in an error message since introducing Metro UI 2

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#3252]
Selecting a single posting on https://pixel.gruene.social/norbert ends in an error message: Sorry, this page isn't available.

This started after the Metro UI 2 was introduced.

**Comment by dansup** [comment]
Can you navigate to the admin dashboard -> Diagnostics and copy + paste the data here?

**Comment by ghost** [comment]
APP_URL: https://pixel.gruene.social
APP_DOMAIN: pixel.gruene.social
Version: 0.11.2
PHP: 7.4.27
PHP-bcmath: Installed
PHP-ctype: Installed
PHP-curl: Installed
PHP-intl: Installed
PHP-json: Installed
PHP-mbstring: Installed
PHP-openssl: Installed
PHP-redis: Installed
Database: mysql (8.0.27)
Bootstrap: Writable
Storage: Writable
