### ISSUE TITLE
ID of statuses get a random id in database, sometimes negative values

### ISSUE THREAD

**Issue by Schdefoon** [pixelfed/pixelfed#3255]
Hi,

I started a new instance of Pixelfed (v0.11.2) on a local server. Now I noticed that posting get random numbers (id in statuses table of the database) that are sometimes negative.
This is no problem when looking at "My Feed" - the statuses seem to be sorted by date descending. But when I go to "Public Feed" some statuses are missing (the ones with negative id) and they seem to be sorted by id descending.
In other public Pixelfeed instances the id seems to increase by date, so the sorting in Public Feed is well. But in my instance with random id everything seems to be unsorted.

Any idea why this could happen?

Best regards

**Comment by dansup** [comment]
@Schdefoon Pixelfed uses snowflake ids which are 64 bit integers, thus you need to run the 64 bit version of PHP!
