### ISSUE TITLE
Can't post images

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#3270]
Hello,

I tried to post some images on my own instance (https://pixelfed.stemy.me/), but all i get after upload is "Oops something went wrong, an unexpected error occured" and "An error occured, please refresh the page". I can upload the said images on the flagship instance without problem.

**Comment by dansup** [comment]
@stemy2 Can you provide more information? Go to the admin dashboard and copy the Diagnostic details

**Comment by stemy2** [comment]
```
    APP_URL: https://pixelfed.stemy.me
    APP_DOMAIN: pixelfed.stemy.me
    Version: 0.11.2
    PHP: 7.4.28
    PHP-bcmath: Installed
    PHP-ctype: Installed
    PHP-curl: Installed
    PHP-intl: Installed
    PHP-json: Installed
    PHP-mbstring: Installed
    PHP-openssl: Installed
    PHP-redis: Installed
    Database: pgsql (11.14)
    Bootstrap: Writable
    Storage: Writable
```
I don't understand the feature "decrypt the payload". What's exactly a "payload" ?

**Comment by dansup** [comment]
@stemy2 I recently added more diagnostic fields that should help identify the issue, can you pull in the latest commits and repost the diagnostic details here?

**Comment by feloxxx** [comment]
> Hello,
> 
> I tried to post some images on my own instance (https://pixelfed.stemy.me/), but all i get after upload is "Oops something went wrong, an unexpected error occured" and "An error occured, please refresh the page". I can upload the said images on the flagship instance without problem.

Hello all, me the same :(

**Comment by MrAn0nym** [comment]
@stemy2 @feloxxx is this still a problem?
