### ISSUE TITLE
The file does not exist or is not readable

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#3286]
Pixelfed v0.11.2

`The "" file does not exist or is not readable. {"userId":833,"exception":"[object] (Symfony\\Component\\Mime\\Exception\\InvalidArgumentException(code: 0): The \"\" file does not exist or is not readable. at /pixelfed/vendor/symfony/mime/FileinfoMimeTypeGuesser.php:50)`

stacktrace https://pastebin.com/RNxTSSXR

**Comment by dansup** [comment]
Without the file I can't really reproduce this

**Comment by kakuy** [comment]
I have the same error when I upload any image while creating a post. The ui shows "Oops, something went wrong!" and when I acceps the message: "An error occured, please refresh the page"

I'm using Pixelfed 0.11.3, MariaDB 10.5.15; Php 8.0.8, Laravel 8.73.2, Nginx 1.18

**Comment by ForestJohnson** [comment]
im willing to bet this happens when the instance admin runs pixelfed behind an HTTP server that limits request body sizes. I can reproduce it too.  My 1MB video file uploads fine, the 3.3MB one causes this error every time.
