### ISSUE TITLE
Add "Content Warnings | Sensitive content" features

### ISSUE THREAD

**Issue by skiant** [pixelfed/pixelfed#33]
Like Mastodon, CW should indicate some content might be problematic for some people.
CW should hide the picture/description, sensitive content only hide the picture.

Users could potentially opt-in to always see content hidden in CW/Sensitive posts.

**Comment by NFGman** [comment]
Until we manage to make people more tolerant, I support this feature request.

**Comment by Grayswandir** [comment]
Hello, depends of how do you implement the fediverse. Ie: like Mastodon: an account will follow another account? Or like Peertube: an instance will follow another Peertube instance? If it's the second choice, I think that the admin of the instance should have the same options as Peertube: do not list/blur thumbnail/display.

**Comment by dansup** [comment]
CW/NSFW support has been added.
