### ISSUE TITLE
.env values for production

### ISSUE THREAD

**Issue by angristan** [pixelfed/pixelfed#330]
Hello,

I want to use pixelfed _in production_.

What should I set these values to ?

```
APP_ENV=local
APP_KEY=
APP_DEBUG=true
```

**Comment by dadall** [comment]
Try this : 

`php artisan key:generate`

**Comment by dansup** [comment]
@Angristan See the following env variables, to set the APP_KEY you need to run the command that @dadall listed.

```bash
APP_ENV=production
APP_DEBUG=false
```

**Comment by angristan** [comment]
Thanks
