### ISSUE TITLE
Trying to access array offset on value of type null /pixelfed/app/Jobs/InboxPipeline/InboxValidator.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#3306]
Pixelfed v0.11.2

`Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /pixelfed/app/Jobs/InboxPipeline/InboxValidator.php:226)`

stacktrace https://pastebin.com/E1jeA6cu

**Comment by jk-na** [comment]
I get the same, have for quite a while now.
