### ISSUE TITLE
Duplicate entry for key 'uri' /pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#3316]
Pixelfed v0.11.2

`[object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'https://mastodoninstance/@todokuro2/107958023049558899' for key 'uri' at /pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)`

stacktrace https://pastebin.com/19nL8rFA

**Comment by dansup** [comment]
Fixed in #3366!
