### ISSUE TITLE
ACTIVITYPUB instance actor cached: ❌

### ISSUE THREAD

**Issue by OccultWarlock** [pixelfed/pixelfed#3318]
When looking at the diagnostics page, I noticed

ACTIVITYPUB instance actor created: ✅
ACTIVITYPUB instance actor cached: ❌

How do I enable the actor cache?

**Comment by dansup** [comment]
It will happen automatically the first time it's fetched, you can pre-cache it by visiting https://pixelfed.social/i/actor and replace `pixelfed.social` with your instance domain.
