### ISSUE TITLE
Only allowed to like a certain number of posts a day?

### ISSUE THREAD

**Issue by pherwaniharsh** [pixelfed/pixelfed#3322]
I may have liked like 15-25 posts so far in a day and pixlefed has blocked me from liking any more of them 🤔 I understand spam protection as this is something that exists in Instagram too, but I was wondering that it would wear off atleast in 30-60mins but it still won't let me like any posts at all due to the interaction limit.

**Comment by dansup** [comment]
You can like up to 100 posts per 24 hours.

**Comment by pherwaniharsh** [comment]
> You can like up to 100 posts per 24 hours.

Thanks a lot, love the project!
