### ISSUE TITLE
Mastodon integrity constraint violation for key 'uri' at at /pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#3325]
Pixelfed [v0.11.2](https://github.com/pixelfed/pixelfed/commit/4f6864667bb928fec59ef780a4d5cd82d79016d5)

`Integrity constraint violation: 1062 Duplicate entry 'https://mastodoninstance/@user/107989114444364949' for key 'uri' at /pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)`

stacktrace https://pastebin.com/nAHXUnxs

**Comment by dansup** [comment]
Fixed in #3366
