### ISSUE TITLE
Trying to access array offset on value of type null at /pixelfed/app/Jobs/InboxPipeline/DeleteWorker.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#3326]
Pixelfed [v0.11.2](https://github.com/pixelfed/pixelfed/commit/4f6864667bb928fec59ef780a4d5cd82d79016d5)

`Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /pixelfed/app/Jobs/InboxPipeline/DeleteWorker.php:216)`

stacktrace https://pastebin.com/m3Dxdw5L

**Comment by dansup** [comment]
Fixed in #3360
