### ISSUE TITLE
Deleting account does not work

### ISSUE THREAD

**Issue by glomeg132** [pixelfed/pixelfed#3327]
https://pixelfed.social/settings/remove/request/permanent

-> after delete I can login again.

**Comment by BinaryWoIf** [comment]
Similar problem. I deleted my account on metapixl.com but it still show up. When I try to login, it tells "These credentials do not match our records".

It's been months and I didn't had this issue with other instances.

**Comment by dansup** [comment]
Fixed in the latest commits!
