### ISSUE TITLE
No Public Docker Image?

### ISSUE THREAD

**Issue by gsugambit** [pixelfed/pixelfed#3337]
This app appears to have no public docker image? I don't see `pixelfed` inside docker hub? Do we have to build our own images?

**Comment by keunes** [comment]
Dear creator(s) of Pixelfed,

I have been following the development of Pixelfed and it looks great, both visually and in terms of functionality. I recently got Docker Compose set up, and now I understand how it works it's a breeze to install & maintain my home server apps (compared to bare metal installations).

I came to GitHub to create an issue for this, as I didn't find any reference in the docs (Yunohost reference is there, so I figured Docker would've been mentioned also if it were available). And I found this issue, so hereby I would like to turn the above question into a request :)

Thanks for your work on Pixelfed!

**Comment by bplein** [comment]
Adding my comments: It appears that the repo issues releases of pixelfed without actually testing that the docker-compose.yml (which builds a pixelfed image) actually works. I have tried the most recent release as well as the latest dev.  Even fixing the first issue (image built on php 7.4, you can edit it to use 8.1), it won't build. 

So it will require fixes to their own Dockerfile(s) before they can start building images. 

--- edited later ---

Hmmm, looks like apache version might build. If so, I might set up my own build of this based on releases....  previously I was testing fpm dockerfiles.

**Comment by bplein** [comment]
I've "fixed" the two Dockerfiles and submitted PR #3850 to address this. I haven't tested it end to end (brought up a site with each) but at least they build now. And both dockerfiles (Apache and fpm) are reconciled to be identical wherever possible.  Now it's up to the devs :)

**Comment by M-D-M** [comment]
I'm adding my vote for an official image, as well.  Once I started using docker, I can't go back to running things directly on an instance anymore.

**Comment by fivestones** [comment]
Just adding my vote too. Docker makes things so much easier and keeps my server clean.

**Comment by gsugambit** [comment]
I'm hoping this will happen soon. I want to give PixelFed to my network

**Comment by trwnh** [comment]
> Now it's up to the devs :)

i regret to inform y'all that we don't actually know anything about maintaining docker images 😅 the docker image was contributed by someone else and all changes to it have been made by outside contributors. we're open to docker deployments, but indeed, the entire deployment story is still not very friendly -- there's still a lot of work to do to make it better, and unfortunately a lot of that work is currently not slated until we get closer to preparing a proper 1.0 release. we're still about 3 release cycles^ away from that point, sadly. the priority right now is to develop pixelfed features like the api and apps (especially the mobile apps), as well as improve federation and the backend.

^arguably we don't have a proper release cycle strategy yet, our releases are kind of ad-hoc still and as-needed. the recommended deployment continues to be using git and pulling the `dev` branch, so that you are always up-to-date with the latest changes. this should also improve eventually!

**Comment by gsugambit** [comment]
> > Now it's up to the devs :)
> 
> i regret to inform y'all that we don't actually know anything about maintaining docker images 😅 the docker image was contributed by someone else and all changes to it have been made by outside contributors. we're open to docker deployments, but indeed, the entire deployment story is still not very friendly -- there's still a lot of work to do to make it better, and unfortunately a lot of that work is currently not slated until we get closer to preparing a proper 1.0 release. we're still about 3 release cycles^ away from that point, sadly. the priority right now is to develop pixelfed features like the api and apps (especially the mobile apps), as well as improve federation and the backend.
> 
> ^arguably we don't have a proper release cycle strategy yet, our releases are kind of ad-hoc still and as-needed. the recommended deployment continues to be using git and pulling the `dev` branch, so that you are always up-to-date with the latest changes. this should also improve eventually!

understood. no pressure!

**Comment by M-D-M** [comment]
> 

Totally understandable.  Docker, however, is the way most professional server deployments happen today -- having this feature would be _immensely_ useful to Pixelfed's adoption.

The good thing about Docker is that the development on the Docker image/services can be done completely independently, and there a lot of very knowledgeable people that could assist with it. I'm currently working on it now, and I know others are too.

Any PRs related to files like "Dockerfile", "docker-compose.yaml", etc, are completely safe to merge without affecting the rest of Pixelfed functionality.

**Comment by bplein** [comment]
It is possible to add Actions that build the Dockerfile and if successful, publish it.  With this, each release would trigger a build. 

As noted by @M-D-M , PRs related solely to the Docker code wouldn't affect pixelfed. They may break on changes in Pixelfed, and then someone will hop on and fix them. Maybe include them but documented as "Unsupported, best effort community support" and leave them in the Contrib area just for that reason.

**Comment by woj-tek** [comment]
Another +1 for docker. It just makes deploying any service _so-much-easier_ and it virtually JustWorks.

I searched the issues and there were a bunch of them and some PRs with improvements to build and automate (GH actions) images.

**Comment by keunes** [comment]
> Another +1 for docker

Please give a thumbs-up to the first post. That a) avoids all supporters of this issue receiving a bunch of notifications and b) better visualise the actual support for this. Many thanks!

**Comment by b2cc** [comment]
I submitted a PR with a new `Dockerfile`:
* https://github.com/pixelfed/pixelfed/pull/4634
