### ISSUE TITLE
Video thumbnails/previews on Profile Page always blur

### ISSUE THREAD

**Issue by alandrees** [pixelfed/pixelfed#3347]
I'm not sure if it's expected functionality or not, but when I upload videos to my pixelfed instance, it will generate a preview, but it is a blurred image (like what you would expect for NSFW content).

I would otherwise expect a still frame from the video to be the preview image, or something which indicates the content.

Edit: This seems to be only an issue in columns and grid layouts, as it seems everything else (old UI and 'list' layout) embed video players, which obviously don't run into those issues.

(I can provide more details if needed)

**Comment by Casuallynoted** [comment]
Also having this problem. Hoping this can be fixed because it makes users not want to mark their content as sensitive.
