### ISSUE TITLE
All my standard uploads on an account have an unwanted "This post may contain sensitive content." label.

### ISSUE THREAD

**Issue by biolithic** [pixelfed/pixelfed#3363]
Hi, 
I am new to Pixelfed. I would like to use https://pixelfed.social to store a photo gallery.

I uploaded 64 photos of a gaming event (day 1) to account:
https://pixelfed.social/i/web/profile/311163851691397120 https://pixelfed.social/paxsoth_inlife
and received 0 "This post may contain sensitive content." labels (ie...possible NSFW).

Then I uploaded 96 photos of same gaming event (day 2) to account:
https://pixelfed.social/i/web/profile/416223366397323891 https://pixelfed.social/paxsth2_inlife
and ALL received "This post may contain sensitive content." labels (ie...possible NSFW).

The photos are not NSFW. Do some contain images of people?  Yes.  Are they nude or political or something?  No, I had these photos up on Facebook, Instagram, Photobucket, etc previously with no warnings and I wish to move off those platforms.

How can I remove the "This post may contain sensitive content." labels (ie...possible NSFW) from all the photos on the second account?

Is "sensitive content" a user viewing setting?
Is "sensitive content" a per image setting?
Is "sensitive content" a per account setting?
Is "sensitive content" a label applied to all photos with people in them on pixelfed.social and thus I should self-host/find a different instance?
Do I need to do something like "verify my account" to hide the "sensitive content" warnings on all the photos?
Is this a bug with Pixelfed?

Here is an example of an auto-label of "Sensitive content" I did not put on nor do I want on this image of the old video game Pong https://pixelfed.social/i/web/post/417196545326749491 . How can I remove the "Sensitive content" warning for an image on my account such as this?

Thanks!

**Comment by dansup** [comment]
@biolithic Hi, so it appears you trigged our automated anti-spam system. I have manually reverted this, so it shouldn't happen again!

**Comment by biolithic** [comment]
Thank you for the fix, much appreciated!
