### ISSUE TITLE
[Bug][UI] Padding can cause mobile layout to overflow

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#338]
### Screenshots

![image](https://user-images.githubusercontent.com/10606431/43121478-7e80082e-8ee3-11e8-9655-1e6095f216cb.png)

https://pixelfed.social/trwnh

### Testing

The elements inside `.lead` are the ones affected, due to erroneous padding. Removing `pr-5` from the Following `div` seems to fix it.

**Comment by ghost** [comment]
I am not a web expert, but I will put my two cents. I got this issue, and checked with an element inspector on my mobile device.

It's a short investigation that might be false or find better replies (with media queries).
I fixed it by adding an "overflow-x: hidden;" for html element. 

![capture d ecran 2018-10-26 a 18 51 14](https://user-images.githubusercontent.com/30171182/47580926-70548b00-d950-11e8-9893-00e539a8b1c5.png)

![capture d ecran 2018-10-26 a 18 51 27](https://user-images.githubusercontent.com/30171182/47580930-72b6e500-d950-11e8-8276-9e0894782252.png)

**Comment by dansup** [comment]
Fixed in latest commits
