### ISSUE TITLE
Mastodon API: unable to log in with web client due to CORS

### ISSUE THREAD

**Issue by alexgleason** [pixelfed/pixelfed#3381]
In theory it's now possible to log into pixelfed.social with https://fe.soapbox.pub/ or another web client like Pinafore.

However Pixelfed does not respond with a `access-control-allow-origin` header, so the browser blocks the requests.

Pleroma solves it by sending `access-control-allow-origin: *`. The problem does not occur with Mastodon either, though I'm not sure why.

**Comment by max-vogler** [comment]
Hey @dansup! Just checking in if there's a reason for the CORS restriction or if you'd be open for a PR?

In case you have concerns about opening the whole API for CORS, it'd still be great to open public feeds like `/account/portfolio/{account}.json`.
