### ISSUE TITLE
Video thumbnails show as "No Preview Available"

### ISSUE THREAD

**Issue by stpnwf** [pixelfed/pixelfed#3384]
Video thumbnails don't work as expected. Both when posting and after video is posted, No Preview Available is shown instead of the actual thumbnail. Issue is present both on the Android app and the web browser.

![Screenshot from 2022-04-12 13-45-08](https://user-images.githubusercontent.com/81482539/163013806-72e5297e-e0a9-4f35-a00d-9e54e5d98c39.png)
![Screenshot_20220412-135144_PixelDroid-cropped](https://user-images.githubusercontent.com/81482539/163014504-b759d9fe-b103-4de6-911d-ffedb672f2b5.jpg)

**Comment by spectateur** [comment]
does it happen with picture also ? Does it happen for all video ? 

Have the same issue happening randomly with pic here 

![image](https://user-images.githubusercontent.com/102883284/163059886-dd94e8e3-53e2-4251-a31d-db04efeb8499.png)

**Comment by stpnwf** [comment]
It happened with both videos I wanted to post, and then the other two I posted just to test it. Initially I thought the issues was bc I compressed them with handbrake, but still happened to the other two, so I don't know what may be the cause. So far it has _only_ happened to videos, _never_ pictures. Nice pic btw.
