### ISSUE TITLE
Blacklist certain email domains from signup

### ISSUE THREAD

**Issue by Whaxion** [pixelfed/pixelfed#339]
Okay, my issue name is a bit strange, I'll explain that.

So, I was looking the analytics of pxlfd.me (I've added Fathom) and I've seen an strange referring site. I clicked on it, and it redirect me to 10minutesmail. Okay, I understand that for some people it's important to have the ability of using totally anonymous email. But me, I really don't love that.

My suggestion is to add a system to ban some email domain, that will not totally resolve this problem, because there is thousand of alternatives to 10minutesmail, but I think it can't be a bad idea. (Of course, instance owner can disable this email ban in the configuration)

**Comment by Codercise** [comment]
I think if this system is going to be built it needs to be optional and perhaps something the site administrator can manage themselves. Pixelfed and it's community are pretty privacy focused and banning these sites straight up might push people away when they could have become advocates for the platform. The other issue will be managing a monstrous list of domains. Something like https://www.mailinator.com has a lot of domains that can be used and tracking/banning them all will be very difficult.

**Comment by veb** [comment]
Sounds like a great option to have for instance owners @Haydos585 and @Whaxion

**Comment by dansup** [comment]
Domain blacklisting has been available for a while. You can add or remove domains from this function https://github.com/pixelfed/pixelfed/blob/73759fdeeb74df017d6070fcd30613340b4d8922/app/Services/EmailService.php#L18-L21
