### ISSUE TITLE
Allow smaller donations

### ISSUE THREAD

**Issue by MaybeThisIsRu** [pixelfed/pixelfed#3396]
Over on Patreon, you have the option of donating $1/month. I'd love it if we could have an option of maybe $2/month and $3/month here on GitHub. I like to donate to projects on GitHub because there is simply more visibility and it's more social (people visiting your profile know which projects you support and that increases project awareness)

**Comment by trwnh** [comment]
i think this is an issue with github sponsors, not pixelfed

**Comment by MaybeThisIsRu** [comment]
I'm donating over at Liberapay for now, but this is not a "GitHub issue."

From a couple of other projects:

<img width="405" alt="Screenshot 2022-08-02 at 7 21 17 PM" src="https://user-images.githubusercontent.com/3974019/182391666-09e2dc72-0df4-4f63-a34f-2b052a27d10b.png">

<img width="356" alt="Screenshot 2022-08-02 at 7 21 23 PM" src="https://user-images.githubusercontent.com/3974019/182391684-3b7a5446-f5b3-4cb5-993f-f69bf585dd04.png">

**Comment by trwnh** [comment]
sorry, i meant you'd have to ask @dansup about that directly -- it has nothing to do with pixelfed the software
