### ISSUE TITLE
Once you select "Try new Metro UI," use cookies to redirect users whenever possible to the new UI

### ISSUE THREAD

**Issue by MaybeThisIsRu** [pixelfed/pixelfed#3397]
It seems many links are still pointing to the old UI. Even if you select "Try new Metro UI", you routinely end up on the old UI and then have to hunt for the button again.

Would be cool if the opt-in was saved using a cookie and then when a relevant page is available in the new UI, you are redirected automatically.

**Comment by todoneunl** [comment]
It is also the other way around, so probably related. When I'm on the legacy UI, and view the complete post, I'm on the Metro UI. When I click 'Go back to previous design', I'm back in the legacy UI again and I can repeat the cycle again.

**Comment by TVHstudio** [comment]
how to disable "back to previous design"? i want to set metro UI as default
