### ISSUE TITLE
Unable to follow accounts on my instance from other instances or services like mastodon

### ISSUE THREAD

**Issue by cytrinox** [pixelfed/pixelfed#3400]
I've setup my own instance of pixelfed and enabled everything the install manual mentioned for federation. I can see the local users on other services like pixelfed.social or mastodon.socal, but when I try to follow them, it's always transformed into a follow request.

I don't get any notification about this on my instance/account and the followers count won't increase.

I see logs in nginx like this, straight after I click **follow** on mastodon:

````
[27/Apr/2022:18:37:04 +0000] "POST /users/daniel/inbox HTTP/1.1" 200 31 "-" "http.rb/5.0.4 (Mastodon/3.5.1; +https://mastodon.social/)"
````

But thats all. No errors, no notifications. At first I assumed this is a federation problem between mastodon and pixelfed, but it also happens when I try to follow me from an account at pixelfed.social.

Are there any logs I can consult to find the root cause for this problem? What can I do next? The troubleshooing section don't even mention something about logging :disappointed: 

Here are some relevant config params from my .env:

````
ACTIVITY_PUB=true
AP_REMOTE_FOLLOW=true
AP_INBOX=true
AP_SHARED_INBOX=true
AP_REMOTE_FOLLOW=true
PF_COSTAR_ENABLED=false

OAUTH_ENABLED=true

ENABLE_CONFIG_CACHE=true

````

````
=======================
 Pixelfed Instance Diagnostic v0.2 
=======================
APP_URL: https://photocave.net
APP_DOMAIN: photocave.net
Version: 0.11.2-86afc5af
PHP: 7.4.28
Database: pgsql (13.5)
Bootstrap: Writable
Storage: Writable
Image Driver: imagick
REDIS Ping: ✅
PHP memory_limit: 256M
PHP post_max_size: 50M
PHP upload_max_filesize: 50M
APP Cache Driver: redis
APP Mail Driver: smtp
APP Mail Host: 10.10******
APP Queue Driver: redis
APP Session Driver: redis
APP Session Lifetime: 86400
APP Session Domain: photocave.net
CONFIG pixelfed:
{"domain":{"admin":"photocave.net","app":"photocave.net"},"version":"0.11.2","nodeinfo":{"url":"https://photocave.net/api/nodeinfo/2.0.json"},"memory_limit":"1024M","open_registration":false,"max_account_size":1000000,"max_photo_size":"45000","max_avatar_size":2000,"max_caption_length":"150","max_bio_length":125,"max_name_length":30,"min_password_length":8,"max_album_length":"4","enforce_email_verification":true,"image_quality":80,"account_deletion":true,"account_delete_after":false,"cloud_storage":false,"max_users":"1000","optimize_image":true,"optimize_video":true,"user_invites":{"enabled":false,"limit":{"total":0,"daily":0,"monthly":0}},"max_collection_length":18,"media_types":"image/jpeg,image/png,image/gif","enforce_account_limit":true,"import":{"instagram":{"enabled":false,"limits":{"posts":100,"size":5000}}},"oauth_enabled":true,"bouncer":{"enabled":false},"media_fast_process":true,"max_altext_length":1000}
CONFIG federation:
{"activitypub":{"enabled":true,"outbox":true,"inbox":true,"sharedInbox":true,"remoteFollow":true,"delivery":{"timeout":30,"concurrency":10,"logger":{"enabled":false,"driver":"log"}}},"atom":{"enabled":true},"avatars":{"store_local":true},"nodeinfo":{"enabled":true},"webfinger":{"enabled":true},"network_timeline":true,"custom_emoji":{"enabled":false,"max_size":2000000}}
ACTIVITYPUB instance actor created: ✅
ACTIVITYPUB instance actor cached: ✅
OAUTH enabled: ✅
OAUTH token_expiration 365 days
OAUTH public key exists: ✅
OAUTH private key exists: ✅
========= END =========
````

**Comment by cytrinox** [comment]
I've switched to MariaDB but the problem persists.

**Comment by spctrlth** [comment]
Possibly because of this issue https://github.com/pixelfed/pixelfed/issues/3049

**Comment by cytrinox** [comment]
@spctrlth Maybe, but I can't federate between pixelfed.social and my own pixelfed instance, so the problem is not directly related to only other fediverse services. And I assume federation between pixelfed instances should work..?

**Comment by Happyfeet01** [comment]
I can't add my pixelfed Instance to apps like Mastodon for iOS. But federation works fine. Maybe an nginx Problem?

**Comment by 5uie** [comment]
> I can't add my pixelfed Instance to apps like Mastodon for iOS. But federation works fine. Maybe an nginx Problem?

@Happyfeet01 Can you add pixelfed.social to Mastodon for iOS? I am unable to add only pixelfed.social on any iOS apps I try, all other pixelfed instances seem to work. Maybe it is some configuration with pixelfed.social? I have posted the issue [#3416](https://github.com/pixelfed/pixelfed/issues/3416), apologies if this is the wrong thread.

**Comment by cytrinox** [comment]
Okay, I found a solution. I've used the artisan queue. My systemd unit has listed the queue as active and the log output seems to be okay, but the queue never received any jobs. I switched to horizon and the unit log output starts with many jobs like InboxPipeline etc. Federation and follow requests works now as expected.

Not sure why the artisan queue failed silently...

**Comment by Pipazoul** [comment]
@cytrinox  Can you please give more details on how you made it work ?
