### ISSUE TITLE
Video thumbnails not generated in profile view

### ISSUE THREAD

**Issue by spaceottercode** [pixelfed/pixelfed#3402]
I know the new UI is currently under development but i just wanted to make a note of the following minor discrepancy:

Under the new UI, thumbnails for videos are not being generated in the profile view.

Other than that, loving the new ui. thanks!

PS this issue differs from issue #3384 which includes thumbnails/previews used elsewhere.

**Comment by spaceottercode** [comment]
It appears that we now have thumbnails for posted videos when viewing the profile page under the new UI.

**Comment by dos1** [comment]
I have never seen a video thumbnail rendered correctly on profile view so far - see for example https://pixelfed.social/i/web/profile/439465108689482043

**Comment by ghost** [comment]
Video previews mostly do not render correctly at this time. I'm unsure why, they play fine but the visual look is detracting from folks I try to get to join. Even just taking a thumbnail 5 frames into the video would suffice. Attached is an example:
<img width="610" alt="Screenshot 2023-12-04 at 8 45 55 AM" src="https://github.com/pixelfed/pixelfed/assets/152904423/b5ba32cb-3ccb-425b-b9c9-152018f757d2">
