### ISSUE TITLE
support POST /api/v2/media 

### ISSUE THREAD

**Issue by connyduck** [pixelfed/pixelfed#3405]
Please support `POST /api/v2/media` enpoint of the Mastodon api. Some client apps, like Tusky, use it and can no longer upload images to Pixelfed which returns 404. It should not be much effort to implement since it is very similar to `/api/v1/media`

From https://docs.joinmastodon.org/methods/statuses/media/ 
> deprecated in favor of POST /api/v2/media, which is equal to v1 in all aspects, except it returns HTTP 202, and the returned JSON object has a url of null, because while the thumbnail is prepared synchronously, the full version of the media attachment will be processed in the background

**Comment by dansup** [comment]
@connyduck Will add right away!

**Comment by dansup** [comment]
@connyduck Deployed to pixelfed.social, can you test it for me?

**Comment by connyduck** [comment]
@dansup you are the best!
https://pixelfed.social/p/connyduck/426086866746658313
