### ISSUE TITLE
When writing a comment, tagging someone by pressing "Enter" in the autocomplete dropdown posts the comment prematurely.

### ISSUE THREAD

**Issue by azuredusk10** [pixelfed/pixelfed#3408]
1. In a comment box, type the character @
2. Start typing in the name of the user you'd like to tag
3. Scroll to the user you'd like to tag using the arrow keys on your keyboard
4. Press enter to autocomplete their username

Expected result: The autocomplete entry is added to your comment.

Actual result: The autocomplete entry is added to your comment, and then your comment is immediately posted.

E.g. in the screenshot below, if I press "Enter", my comment is posted prematurely.
![image](https://user-images.githubusercontent.com/18142893/166123079-72bed568-4318-4ed1-a86a-140608e346b2.png)

**Comment by dansup** [comment]
Fixed in the latest commits!
