### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#3417]
I am trying to add a photo to a collection but I get this message:

![148B1D54-2D83-4C6F-809F-D92D5AB55E5C](https://user-images.githubusercontent.com/16371257/166501666-8af81555-a458-47bd-97b5-35e733e8bcbe.png)

However, the photo is published.

**Comment by ghost** [comment]
Hi,

I don't know if anything has been done but it has been fixed.

Best regards.

**Comment by dansup** [comment]
Closing as it was reported as fixed!
