### ISSUE TITLE
Sharing via the share button in Firefox gives an ugly caption

### ISSUE THREAD

**Issue by faissaloo** [pixelfed/pixelfed#342]
If I go to [this photo](https://pixelfed.social/p/KazukyAkayashi/6740) for example and hit 'share to Telegram' in Firefox the resulting message is:  
  
>KazukyAkayashi posted a photo: 3 likes, 0 comments
>https://pixelfed.social/p/KazukyAkayashi/6740  
  
This is a really ugly message, firstly it shows stats that will inevitably change, it doesn't feature the caption at all.

**Comment by trwnh** [comment]
This has nothing to do with Firefox or Telegram specifically, I think -- the preview is being pulled from OpenGraph tags being added to each page. I agree that the OG description should include the caption.

**Comment by trwnh** [comment]
OpenGraph now uses the caption as og:description and "A post by username" for og:title.
