### ISSUE TITLE
Unable to bulk change the licence of my pictures

### ISSUE THREAD

**Issue by andre-dierker** [pixelfed/pixelfed#3421]
Hello

I tried to bulk change or sync the licence of my pictures in the settings/media menu but it is not possible due to an missing colum in the database.

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'compose_settings' in 'field list' (SQL: update `user_settings` set `compose_settings` = "{\"default_license\":12,\"media_descriptions\":false}", `user_settings`.`updated_at` = 2022-05-06 23:29:03 where `id` = 1)
```

## Pixelfed Instance Diagnostic v0.2 

APP_URL: https://metapixl.com
APP_DOMAIN: metapixl.com
Version: 0.11.2-7a0acebf
PHP: 7.4.29
Database: mysql (10.4.24-MariaDB-1:10.4.24+maria~buster-log)
Bootstrap: Writable
Storage: Writable
Image Driver: imagick
REDIS Ping: ✅
PHP memory_limit: 512M
PHP post_max_size: 100M
PHP upload_max_filesize: 100M
APP Cache Driver: redis
APP Mail Driver: smtp
APP Mail Host: mail.******
APP Queue Driver: redis
APP Session Driver: redis
APP Session Lifetime: 86400
APP Session Domain: metapixl.com
CONFIG pixelfed:
{"domain":{"admin":"metapixl.com","app":"metapixl.com"},"version":"0.11.2","nodeinfo":{"url":"https://metapixl.com/api/nodeinfo/2.0.json"},"memory_limit":"4G","open_registration":true,"max_account_size":"4194304","max_photo_size":"25000","max_avatar_size":2000,"max_caption_length":"500","max_bio_length":"550","max_name_length":"30","min_password_length":8,"max_album_length":"50","enforce_email_verification":true,"image_quality":80,"account_deletion":true,"account_delete_after":false,"cloud_storage":false,"max_users":"10000","optimize_image":true,"optimize_video":true,"user_invites":{"enabled":false,"limit":{"total":0,"daily":0,"monthly":0}},"max_collection_length":18,"media_types":"image/jpeg,image/png,image/gif,video/mp4,video/mpeg,video/mov","enforce_account_limit":true,"import":{"instagram":{"enabled":true,"limits":{"posts":500,"size":5000}}},"oauth_enabled":true,"bouncer":{"enabled":false},"media_fast_process":true,"max_altext_length":1000}
CONFIG federation:
{"activitypub":{"enabled":true,"outbox":true,"inbox":true,"sharedInbox":true,"remoteFollow":true,"delivery":{"timeout":"2.0","concurrency":"10","logger":{"enabled":false,"driver":"log"}}},"atom":{"enabled":true},"avatars":{"store_local":true},"nodeinfo":{"enabled":true},"webfinger":{"enabled":true},"network_timeline":true,"custom_emoji":{"enabled":true,"max_size":2000000}}
ACTIVITYPUB instance actor created: ✅
ACTIVITYPUB instance actor cached: ✅
OAUTH enabled: ✅
OAUTH token_expiration 365 days
OAUTH public key exists: ✅
OAUTH private key exists: ✅
========= END =========

Thanks for your awesome work :)

**Comment by dansup** [comment]
@andre-dierker Hi, it looks like you haven't run migrations [as that column was added last year](https://github.com/pixelfed/pixelfed/blob/dev/database/migrations/2021_07_23_062326_add_compose_settings_to_user_settings_table.php#L17)

You should run `php artisan migrate` after every update! 

If the issue persists, feel free to re-open this issue.

**Comment by andre-dierker** [comment]
Hey @dansup,

artisan migrate is part of my pixelfed updater script. So it's done every update.
I do not know how to re-open the issue

**Comment by andre-dierker** [comment]
Hot fixed in Discord. No idea what caused the issue.
