### ISSUE TITLE
Unable to edit or create new pages, entirely broken?

### ISSUE THREAD

**Issue by andre-dierker** [pixelfed/pixelfed#3422]
Hello,

- currently it's not possible to create or edit pages in the admin menu https://your-instance.com/i/admin/settings/pages.
- If pages exist they somehow there but it's not possible to enable them.
- For existing(?) pages it's not possible to edit the body, only the title has an text field.
- Delete button does not delete a page

![image](https://user-images.githubusercontent.com/6938843/167228550-ff1507ae-cc22-48a9-a930-10509d75fc2e.png)
![image](https://user-images.githubusercontent.com/6938843/167228809-60f35c92-1c3d-49e3-bf70-f967cfea7c83.png)

Regards

**Comment by ghost** [comment]
Same here with v0.11.3, browser-independent effect.

**Comment by sir-octopus** [comment]
The issue I just created, #3616 may be the same, although I got a 500 error not missing UI elements. I've given a workaround in that issue that may work here.

**Comment by dansup** [comment]
Fixed in #3623!
