### ISSUE TITLE
JSON-LD Context is broken?

### ISSUE THREAD

**Issue by MitarashiDango** [pixelfed/pixelfed#3423]
For Note objects created by Pixelfed, it seems that the Context is incorrect and cannot be treated correctly as JSON-LD.

Below is an error when trying to load a sample Note object(*1) from the Pixelfed documentation with JSON-LD Playground(*2).
(It has been confirmed that the same result is obtained with the data generated by the server that is actually operating.)

![image](https://user-images.githubusercontent.com/19360569/167270741-df587710-6bc1-4ded-8b18-34e532a90334.png)

*1: https://docs.pixelfed.org/technical-documentation/activitypub.html#note
*2: https://json-ld.org/playground/

**Comment by trwnh** [comment]
#3451 does not fix all issues with json-ld context, so reopening this issue

**Comment by zealov** [comment]
> ### 

- [ ] @1. > [`****`](url)

**Comment by trwnh** [comment]
should be fixed by #3464 and #3475
