### ISSUE TITLE
How to make newly translated UI string work?

### ISSUE THREAD

**Issue by fweng322** [pixelfed/pixelfed#3425]
It should be a improvement request in the document.

I translated some strings in the resource/lang/zh-tw/web.php but couldn't find out how to compile it or to make it show on the web home page.  I couldn't find any related instructions in https://docs.pixelfed.org/ .

Could any one please tell me how to make translations work?  Also, if I have done translating the UI strings, should I send it via pull requests or send anywhere?

**Comment by dansup** [comment]
We're not using translation on the home page [yet](https://github.com/pixelfed/pixelfed/blob/dev/resources/views/site/index.blade.php#L64) but it is planned, we're working on a new design so I'd hold off on translating that for now.

You can contribute translations here https://translate.pixelfed.org/
