### ISSUE TITLE
Problem when adding instance via mobile App

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#3428]
Hey everyone,

thanks to the one or other hint here I have managed to get the ActivityPub in my Pixelfed-instance v0.11.2 working with remote follows, messages etc. !

The only problem I still have that the instance cannot be connected with an official mobile client (here Mastodon or Toot on iOS), instead the instance still seems to be searched somehow but there is no result shown.

Parameters in the .env-file are:

```
ACTIVITY_PUB=true
AP_REMOTE_FOLLOW=true
AP_SHAREDINBOX=true
AP_INBOX=true
AP_OUTBOX=true
ATOM_FEEDS=true
NODEINFO=true
WEBFINGER=true
```

Does anyone know what may cause this error and what I still am missing somehow?

![IMG_2092](https://user-images.githubusercontent.com/42076599/167302591-538a753c-1bf3-4dc1-b17f-fa194a26b69c.jpeg)

Thanks and best regards,

Oliver

**Comment by dansup** [comment]
Did you run `php artisan passport:install`?

**Comment by ghost** [comment]
Yeah, straight from the beginning.

Encryption keys generated successfully.
Personal access client created successfully.
Password grant client created successfully.

What else may I be missing here?

**Comment by dansup** [comment]
Hard to say without more info, please paste your diagnostics from the admin dashboard!

**Comment by ghost** [comment]
Sure - updated to 0.11.3 in the meantime:

=======================
 Pixelfed Instance Diagnostic v0.2 
=======================
APP_URL: https://pixelfed.instance.xyz
APP_DOMAIN: pixelfed.instance.xyz
Version: 0.11.3-8c219348
PHP: 7.4.29
Database: mysql (10.3.28-MariaDB)
Bootstrap: Writable
Storage: Writable
Image Driver: gd
REDIS Ping: ✅
PHP memory_limit: 256M
PHP post_max_size: 2048M
PHP upload_max_filesize: 2048M
APP Cache Driver: redis
APP Mail Driver: smtp
APP Mail Host: smtp.**************
APP Queue Driver: redis
APP Session Driver: redis
APP Session Lifetime: 86400
APP Session Domain: pixelfed.instance.xyz
CONFIG pixelfed:
{"domain":{"admin":"pixelfed.instance.xyz","app":"pixelfed.instance.xyz"},"version":"0.11.3","nodeinfo":{"url":"https://pixelfed.instance.xyz/api/nodeinfo/2.0.json"},"memory_limit":"1024M","open_registration":false,"max_account_size":"5192000","max_photo_size":"15000","max_avatar_size":2000,"max_caption_length":"1000","max_bio_length":"250","max_name_length":30,"min_password_length":8,"max_album_length":"10","enforce_email_verification":true,"image_quality":80,"account_deletion":true,"account_delete_after":false,"cloud_storage":false,"max_users":"5","optimize_image":true,"optimize_video":true,"user_invites":{"enabled":false,"limit":{"total":0,"daily":0,"monthly":0}},"max_collection_length":18,"media_types":"image/jpeg,image/png,image/gif","enforce_account_limit":true,"import":{"instagram":{"enabled":false,"limits":{"posts":100,"size":5000}}},"oauth_enabled":false,"bouncer":{"enabled":false},"media_fast_process":true,"max_altext_length":1000}
CONFIG federation:
{"activitypub":{"enabled":true,"outbox":true,"inbox":true,"sharedInbox":true,"remoteFollow":true,"delivery":{"timeout":30,"concurrency":10,"logger":{"enabled":false,"driver":"log"}}},"atom":{"enabled":true},"avatars":{"store_local":true},"nodeinfo":{"enabled":true},"webfinger":{"enabled":true},"network_timeline":true,"custom_emoji":{"enabled":false,"max_size":2000000}}
ACTIVITYPUB instance actor created: ✅
ACTIVITYPUB instance actor cached: ❌
OAUTH enabled: ✅
OAUTH token_expiration 365 days
OAUTH public key exists: ✅
OAUTH private key exists: ✅

========= END =========

**Comment by ghost** [comment]
Just a short note - neither Toot nor the official Mastodon-app is able to connect to the server.

Metatext at least connects to the instance, requests the permission but cannot load any timeline nor the startpage afterwards.

**Comment by ghost** [comment]
Tried it with Toot in the meantime and the only instance I can add here without any flaw is pixelfed.social, even pixelfed.de cannot be connected and this reflects with my own instance, too.

Where's the difference? 🤔

![image](https://user-images.githubusercontent.com/42076599/168474782-16c26fe7-5980-4591-9f52-6cd12a24ac0e.jpeg)

![image](https://user-images.githubusercontent.com/42076599/168474786-855017a7-5272-4224-a989-1276e22fea4b.jpeg)

**Comment by dansup** [comment]
@OliverPifferi Hey, so this was recently fixed! You can set `EXP_EMC=true` in .env and re-deploy or update to the latest commits where that variable is set by default.

Sorry for the inconvenience, feel free to re-open this issue if it persists.

**Comment by ghost** [comment]
> Sorry for the inconvenience, feel free to re-open this issue if it persists.

No problem, that's why we are here ;-) !

Updated and it got better (by far not perfect):

- Mastodon iOS-app: Still searches without finding anything
- Toot: Server can be found, OAUTH works - then an empty timeline appears
- Metatext: Everything works (timeline etc.) but messages cannot be opened, stating that sent data has an improper format

Seems as if every app handles the instance different - the original problem is gone but there is still some way to go :-) !

Screenshots from Toot:

![IMG_2120](https://user-images.githubusercontent.com/42076599/168609604-490e3fd0-b68e-4680-923f-71aa99a1b57c.jpeg)

![IMG_2121](https://user-images.githubusercontent.com/42076599/168609668-da801073-0db7-4a1a-a203-8bae232c5625.jpeg)

![IMG_2124](https://user-images.githubusercontent.com/42076599/168609712-cad21987-e365-47d2-a5eb-a567bd306bfa.jpeg)

Thanks for your efforts and best regards,

Oliver
