### ISSUE TITLE
Can't compile assets

### ISSUE THREAD

**Issue by nicolafan** [pixelfed/pixelfed#3434]
Hi! After setting up a new installation using Homestead 13.2 everything looks good, but it results impossible to me to compile assets (I would like to make changes to Vue code of my testing installation).
The following is the walkthrough of all the issues (in case you could help me understand the real problem) I encounter after running `npm install && npm run production` (same for `npm run development`):

1.   I get:
      ```
      ERROR in ./resources/assets/js/components/presenter/VideoPresenter.vue 1:0
      Module parse failed: Unexpected token (1:0)
      You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See        https://webpack.js.org/concepts#loaders
      > <template>
      |       <div v-if="status.sensitive == true" class="content-label-wrapper">
      |               <div class="text-light content-label">
      ```
      This error is repeated for many Vue files. I solve this by adding `.vue()` to `webpack.mix.js`.
2.  `npm run production` now works. I navigate to `https://pixelfed.test/i/web` and get the same error as in #3247. Mix can't load `spa.js` and  `spa.css` because they are not in `webpack.mix.js`. I solve this (probably erroneously) by using `asset('js/spa.js')` and `asset('css/spa.css')` in `layouts/spa.blade.php`. After that, the problem is solved but **the entire screen of `https://pixelfed.test/i/web` is black**.
3. If I use the classic UI (`https://pixelfed.test/`) this is what I get:
    
    ![Screenshot from 2022-05-10 22-36-34](https://user-images.githubusercontent.com/48762613/167717615-f698dc41-e19e-40c1-ac3a-c8a75e489329.png)

    The console prints out:
    ![Screenshot from 2022-05-10 22-38-57](https://user-images.githubusercontent.com/48762613/167717871-11ec2567-9509-42f5-a1ea-28a67d870763.png)
    
    After changing the first line of `resources/assets/js/components.js` from `window.Vue = require('vue');` to `window.Vue = require('vue').default;` and re-running `npm run production`, I get:
    
    ![Screenshot from 2022-05-10 22-47-44](https://user-images.githubusercontent.com/48762613/167719214-df496bc6-914d-489f-b061-433ce1e2af5b.png)

    
   (No console error but still no icons). Tried Chrome and Firefox. I got this problem with v. 0.11.3 and v. 0.11.2. I can compile in v. 0.11.1.

These are all the things I tried but I wasn't able to understand the problem. I'm sorry if I'm missing something obvious. I can provide additional information if required. Thank you so much!

**Comment by dansup** [comment]
Hello, sorry about that! We're in the middle of a huge refactor, and hope to resolve our asset pipeline issues soon.

**Comment by zealov** [comment]
> 您好，对此感到抱歉！我们正在进行大规模的重构，并希望尽快解决我们的资产管道问题。
大概需要多久这个问题可以解决呀

**Comment by zhangzhongwu666** [comment]
大概需要多久这个问题可以解决呀

**Comment by ballerburg9005** [comment]
Dang! I was about to make a small PR out of nowhere but had a hard time testing my changes. Thanks for the issue.

**Comment by motzmose** [comment]
Hey there!
Love the project.
Are there any news on this issue or any tips on how to proceed when trying to edit the Vue code?
Thanks in advance!

**Comment by nicolafan** [comment]
Hi! Just an update concerning the icons... If you recompile assets and lose them change the fontawesome classes of the icons in the corresponding files from `fal` (I don't remember very well but I think it was `fal`), to `fas`.

I think that fontawesome light icons are only available for Pro users.

**Comment by motzmose** [comment]
Hey!
Thanks for the quick response!
I think my only option is to somehow rollback to a state (as you stated 0.11.1 doesn't have that problem) where I can still make changes.
I can confirm however that changing `fal` to `fas` brings back the icons.
Have good start into the week y'all!

**Comment by M-Miller-42** [comment]
I would be very thankful for a hint on how the `public/spa.js` is generated. It is updated regularly for newer versions, but it seems some code for that is not yet checked in. Could it be described/posted here in the meantime as a workaround?

**Comment by stigger** [comment]
I've been looking for the sources of the processed javascript code as well.

**Comment by DoM1niC** [comment]
I got 
```ERROR in ./resources/assets/components/remote-auth/GettingStartedComponent.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib/index.js??clonedRuleSet-5.use[0]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./resources/assets/components/remote-auth/GettingStartedComponent.vue?vue&type=script&lang=js&) 2:0-55
Module not found: Error: Can't resolve './partials/RegisterForm.vue' in '/home/www/projects/other/pixelfed/resources/assets/components/remote-auth'
Did you miss the leading dot in 'resolve.extensions'? Did you mean '[".*",".wasm",".mjs",".js",".jsx",".json",".vue"]' instead of '["*",".wasm",".mjs",".js",".jsx",".json",".vue"]'?

webpack compiled with 1 error
```

**Comment by mitexleo** [comment]
> I got
> 
> ```
> Module not found: Error: Can't resolve './partials/RegisterForm.vue' in '/home/www/projects/other/pixelfed/resources/assets/components/remote-auth'
> Did you miss the leading dot in 'resolve.extensions'? Did you mean '[".*",".wasm",".mjs",".js",".jsx",".json",".vue"]' instead of '["*",".wasm",".mjs",".js",".jsx",".json",".vue"]'?
> 
> webpack compiled with 1 error
> ```

Known issue. @dansup will fix it soon.

**Comment by mbliznikova** [comment]
@mitexleo Hi! Is it fixed yet? Can you recommend a way to fix it on my local machine? I want to try to learn developing for pixelfed, and hopefully contribute some bug fixes, but this prevents me from moving forward.

**Comment by motzmose** [comment]
Yup, has been fixed. See #4464 and #4465 for details.
