### ISSUE TITLE
Swipe to navigate album on timelines

### ISSUE THREAD

**Issue by Whaxion** [pixelfed/pixelfed#344]
When we are on mobile, swiping on an album is impossible.
So, I think it's really a good idea to add this.

Also, on timeline we don't see if it's an image or an album, so it can't be a bad idea to make this apparent or if we can see an album without clicking on it. :stuck_out_tongue:

**Comment by maznu** [comment]
I played with https://flickity.metafizzy.co recently which, being GPL, should be license-compatible with pixelfed. It seems pretty solid, might save a bunch of UI dev time, if suitable?

**Comment by ahstro** [comment]
Correct me if I'm wrong, but swiping works right now, so this should be closable? Or am I missing something?

**Comment by trwnh** [comment]
@ahstro: Not on timelines, no.

**Comment by dansup** [comment]
@trwnh The [carousel supports](https://bootstrap-vue.js.org/docs/components/carousel/#touch-swipe-support) mobile swipe support.
