### ISSUE TITLE
Small issues detected by phpstorm

### ISSUE THREAD

**Issue by shleeable** [pixelfed/pixelfed#3440]
* There are 2 refreshNotifications() in resources/assets/js/components/NotificationCard.vue

* There are 2 returns in store() in app/Http/Controllers/InstallController.php
![image](https://user-images.githubusercontent.com/17537000/168262123-343f8130-681e-4138-8b2c-bb34138a20c9.png)

* argon-dashboard outdated

**Comment by shleeable** [comment]
![image](https://user-images.githubusercontent.com/17537000/168262227-09a55033-c7d6-400d-a2de-4c0964cbbe9c.png)
getStories missing the pid? on line 31

**Comment by shleeable** [comment]
StatusHashtagService
![image](https://user-images.githubusercontent.com/17537000/168276270-c4cced7e-eb51-4a6a-823b-08736b7fc0dd.png)

Del has 1 arg 
![image](https://user-images.githubusercontent.com/17537000/168276330-5d1ef41c-87dd-4cf4-b312-7b0c12dd4365.png)

**Comment by shleeable** [comment]
## Dupe tags?

![image](https://user-images.githubusercontent.com/17537000/168279138-48ce3c4b-d2f0-413f-8bb6-0a03d601c005.png)
app/Transformer/Api/Mastodon/v1/StatusTransformer.php

![image](https://user-images.githubusercontent.com/17537000/168279225-a53638f9-9d59-4deb-8947-96e55a9c044c.png)
app/Transformer/Api/StatusTransformer.php

![image](https://user-images.githubusercontent.com/17537000/168279302-3a79045f-2b76-4b7c-8f27-8d0248225cea.png)
app/Transformer/Api/StatusStatelessTransformer.php

**Comment by dansup** [comment]
> StatusHashtagService ![image](https://user-images.githubusercontent.com/17537000/168276270-c4cced7e-eb51-4a6a-823b-08736b7fc0dd.png)
> 
> Del has 1 arg ![image](https://user-images.githubusercontent.com/17537000/168276330-5d1ef41c-87dd-4cf4-b312-7b0c12dd4365.png)

This is intentional, the `StatusHashtagService::get()` method does not use the cache at the moment.

The other issues will be fixed shortly.
