### ISSUE TITLE
Cannot get the tick on "instance actor cached" in diagnostics

### ISSUE THREAD

**Issue by shleeable** [pixelfed/pixelfed#3443]
![image](https://user-images.githubusercontent.com/17537000/168406987-98839ea0-319e-4296-8bbc-15487edc9460.png)

![image](https://user-images.githubusercontent.com/17537000/168407020-8b024eda-4a76-4565-8dbc-354e578aef88.png)

no way to trigger InstanceActorController::profile and cache that value?
![image](https://user-images.githubusercontent.com/17537000/168407004-71889472-fec7-4acf-93d3-750145382175.png)

**Comment by dansup** [comment]
That's okay, it will be cached by the first request to `your-instance.example/i/actor`. You can replace `your-instance.example` with your instance domain and visit that in your browser to warm the cache but it's not a very expensive operation and is cached forever.
