### ISSUE TITLE
Provide a counter for the caption field

### ISSUE THREAD

**Issue by ingorichter** [pixelfed/pixelfed#346]
A couple of times I ran into the situation that my caption was longer than the maximum allowed chars.

It would be helpful to have either a char counter or turn the border of the input field into a different color once the caption is over the max.

**Comment by dansup** [comment]
@ingorichter It will be added soon!

<img width="960" alt="screen shot 2018-08-09 at 6 28 37 pm" src="https://user-images.githubusercontent.com/877217/43932584-2515c57c-9c02-11e8-9dfb-909f65fb0858.png">

**Comment by dansup** [comment]
It's been added in the latest commits!

**Comment by ingorichter** [comment]
A-m-a-z-i-n-g! 👏 Thank you!
