### ISSUE TITLE
Video does not show, only audio plays

### ISSUE THREAD

**Issue by Magess** [pixelfed/pixelfed#3520]
I uploaded videos directly from my phone, and the visuals do not show. When the video plays, there's a black box and only audio. I have tried Firefox and Chrome on both Windows 10 and MacOS, as well as opening pixelfed in Ecosia and Chrome on my phone.

https://pixelfed.social/i/web/post/419851738638626864

Sample video that does not show visuals.

**Comment by cloo** [comment]
Same here. Tried on FF and chrome. 

![220527-231159](https://user-images.githubusercontent.com/651760/170783330-83588cae-09ed-4450-8d41-59cfe3526a0a.gif)

Strangely from Mastodon feed it plays perfectly. 
![220527-231616](https://user-images.githubusercontent.com/651760/170783767-c4531655-5fc9-4bf6-a86f-34299e20b33a.gif)


I'm pretty sure I looked at it right after uploading and it worked.
Original post: https://metapixl.com/i/web/post/426433591457298074
