### ISSUE TITLE
Metro 2: Stories don't seem to disappear

### ISSUE THREAD

**Issue by carbeck** [pixelfed/pixelfed#3531]
According to the description of the stories feature, they should disappear after 24 hours. However, I keep seeing one story that's been hanging there for 3 weeks now and I start to believe it's a bug, not a feature. The server (pixelfed.de) uses Pixelfed v0.11.3.

![Screenshot of the hanging story item](https://user-images.githubusercontent.com/2134500/171501723-c1532548-a996-401c-9383-17e57e460539.png)

**Comment by dansup** [comment]
@carbeck It looks like the instance you are on is not running the [task scheduler](https://docs.pixelfed.org/running-pixelfed/installation.html#scheduling-periodic-tasks), as they are supposed to be checked every 5 minutes and expired if applicable.

https://github.com/pixelfed/pixelfed/blob/8059cf39ac9c9ce9723cd21b6cb73ff84fc67ea3/app/Console/Kernel.php#L31

cc @hnrd

**Comment by LM1LC3N7** [comment]
For the records: I am using the docker image from @jippi and stories does not disappear. With docker overrides I was able to automatically install cron + configure the cron task.
Wait & see, but it should be okay now.

**Comment by guillaumedc** [comment]
Can you give us more details, please?
I'm using a Docker image too, and the cron is probably not running.

**Comment by jippi** [comment]
> @carbeck It looks like the instance you are on is not running the [task scheduler](https://docs.pixelfed.org/running-pixelfed/installation.html#scheduling-periodic-tasks), as they are supposed to be checked every 5 minutes and expired if applicable.
> 
> https://github.com/pixelfed/pixelfed/blob/8059cf39ac9c9ce9723cd21b6cb73ff84fc67ea3/app/Console/Kernel.php#L31
> 
> cc @hnrd

@dansup  Are the task scheduler not running via Horizon tasks? Are there any additional services/crons that need to be running?
