### ISSUE TITLE
Can’t accept follower request 

### ISSUE THREAD

**Issue by genebean** [pixelfed/pixelfed#3534]
I have setup a private account on pixelfed.social. I sent a follower request to it from my public Fosstodon account but am unable to accept it. I’m happy to provide any information needed to help debug this.

**Comment by mediaformat** [comment]
Same. 

Additionally the user making the follow request appears with a double at-sign `@@user@instance.tld`.

**Comment by genebean** [comment]
I’m seeing the same double `@@` as @mediaformat 

![96F5CFE9-9063-4BE1-8E7A-05BEB3F082F2](https://user-images.githubusercontent.com/966789/173249920-95b94007-1ff1-4d8e-8d3c-62bd424dc945.jpeg)

**Comment by dansup** [comment]
Fixed in #3532!

**Comment by genebean** [comment]
Thanks @dansup! Is it expected that a new follower can’t see old posts?
