### ISSUE TITLE
Old posts aren't visible / accessible?

### ISSUE THREAD

**Issue by kr428** [pixelfed/pixelfed#3541]
On pixelfed / pixelfed.social, the last post visible both in my web profile (when directly using pixelfed) or via some app (when browsing that profile from, say, a Mastodon or Friendica account following me there), I can't see any posts older than Sept 2019. They still seem around (i.e. I can find some of them by using the hashtags I had set there, and direct links still work too). Known problem? pixelfed issue? pixelfed.social issue? Or intentional limitation?

**Comment by dansup** [comment]
Fixed in #3532!

**Comment by dansup** [comment]
I tested this on pixelfed.social btw, I can now load your oldest posts on Metro 2 and the old UI

**Comment by kr428** [comment]
Yes. Looks good now. Thanks bunches for the quick fix. :)
