### ISSUE TITLE
Unfollow remote profiles not working

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#3558]
Pixelfed https://github.com/pixelfed/pixelfed/commit/76dbddfae9cf26ba1937810f1ecd791e41f5b7c6

The profile card shows 'following' 
click on it to 'unfollow'

The profile card shows 'follow'

The profile is still listed after refreshing page and returns to previous 'following' status

**Comment by MrAn0nym** [comment]
Is this still a problem, and if yes does it happen on the old or on the new UI?

**Comment by trwnh** [comment]
cannot reproduce
