### ISSUE TITLE
Docker: Can't save settings changed in the app.

### ISSUE THREAD

**Issue by gitwittidbit** [pixelfed/pixelfed#3566]
So I have Pixelfed up und running in docker (via docker-compose).

I also managed to enable the Settings page inside the app.

But whenever I change a setting and click "Save", I get an error message "Something went wrong. We cannot process your request at this time, please try again later."

Any ideas what this is about?

Many thanks in advance.

**Comment by ghost** [comment]
Perhaps if you are the admin you could copy the error payload to decrypt as following on admin area >diagnostics> scroll to bottom 

![2CD5AB89-964E-4BC6-A6AA-D507C4D2E747](https://user-images.githubusercontent.com/75223599/176814999-0be7c6d4-a0a7-4bfc-95b1-b7c4a3f3e828.jpeg)

**Comment by mixeme** [comment]
I've the similar issue, but no error messages. Is there a solution?
