### ISSUE TITLE
Adding post to collection during post creation

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#3573]

**Comment by mattsches** [comment]
Could this be an issue with the Redis cache?

@ozmanorchis  Could you please wait 24h, check the collection again and report here if the post has been added?

**Comment by ozmanorchis** [comment]
> Could this be an issue with the Redis cache?
> 
> @ozmanorchis Could you please wait 24h, check the collection again and report here if the post has been added?

Post has already been added to collection via the "add photo" function in the separate collections screen. I'll need to replicate issue when next posting and will report back after 24h.

**Comment by ozmanorchis** [comment]
> Could this be an issue with the Redis cache?
> 
> @ozmanorchis Could you please wait 24h, check the collection again and report here if the post has been added?

The scenario was replicated and 24 hours was allowed to elapse. Outcome: post still failed to populate to the collection that was selected at the time post creation

**Comment by SathyaBhat** [comment]
I see the same behavior on my hosted Pixelfed instance.
