### ISSUE TITLE
dockerized installation missing php error logs

### ISSUE THREAD

**Issue by ctr49** [pixelfed/pixelfed#3602]
Am I missing something or does the dockerized installation (from contrib) lack php error logging?
https://github.com/pixelfed/pixelfed/blob/dev/contrib/docker/php.production.ini#L570 has default configuration which is empty.
For a dockerized installation this should usually be something like
`error_log = /proc/self/fd/2`
or is error handling done differently?

**Comment by ctr49** [comment]
I can see nginx error_log being configured in the refactored container, but still no error_log in php(-fpm).ini

**Comment by Murazaki** [comment]
What would you want to get in logs? 
It seems to me that we do have fpm logs showing up with Pixelfed Glitch images (integrating #4844) ?

You can test them here https://github.com/pixelfed-glitch/pixelfed
