### ISSUE TITLE
Thumbnails on profile not displayed

### ISSUE THREAD

**Issue by gegeweb** [pixelfed/pixelfed#361]
On a fresh testing installation, I don't show thumbnails on user profile.

Don't know if it is a bug or a misconfiguration on my side.
php-gd is installed, and i think all depandancies.

I've this on the horizon log : 
```
[2018-08-11 11:06:52][13] Processing: App\Jobs\ImageOptimizePipeline\ImageResize
[2018-08-11 11:06:53][13] Processing: App\Jobs\ImageOptimizePipeline\ImageResize
[2018-08-11 11:06:55][13] Failed:     App\Jobs\ImageOptimizePipeline\ImageResize
```

<img width="836" alt="capture d ecran 2018-08-11 a 11 25 49" src="https://user-images.githubusercontent.com/9108457/43990238-63046098-9d59-11e8-990a-45d5ff8f855c.png">

**Comment by gegeweb** [comment]
Same issue on hashtag view.

This seems to be a problem with thumbnail_path that does not exist in `storage/app/public/`.
When i look at the media tables, thumbnail_path is NULL.

Don't know how to fix it.

**Comment by gegeweb** [comment]
On FreeBSD, need to install the port php72-exif (or php**-exif, where ** is the version of php port installed).

**Comment by jeroenpraat** [comment]
On Debian 9 this PHP (7.2) exif module is already there, but still this is a problem. No thumbnails are generated with the same symptoms described here.

Can this issue be reopened @dansup ?

**Comment by edwardlow** [comment]
Same problem than @jeroenpraat , once I serve the server thru apache and not artisan, no thumbnails generated correctly. I have installed Exif module thru php7.2
@dansup can be the issue reopened?

**Comment by jeroenpraat** [comment]
Problem found. It was a Nginx vhost setting.

```
location / {
                try_files $uri $uri/ /index.php?$query_string;
        }
```

Should be:
```

location / {
                try_files $uri /index.php?$query_string;
        }
```

So you have to remove `$uri/`.

According [this answer](https://stackoverflow.com/a/38046124) on Stack Exchange, it is needed when you disabled directory indexing off (what is default in Nginx AFAIK).

**Comment by andre-dierker** [comment]
My working nginx.conf. 
```bash
  location / {
    try_files $uri $uri/ /$is_args$args;
  }
```
$uri is needed for redirect the index file. In your config index.php is 'hardcoded'. If needed I can provide the full config.

**Comment by jeroenpraat** [comment]
@andre-dierker Thanks, that works too.

@dansup You can close this issue.
