### ISSUE TITLE
Unable to search and display profiles

### ISSUE THREAD

**Issue by stephenjmaher** [pixelfed/pixelfed#3617]
When trying to search for profiles, then search hangs. Also, when trying to display profiles by clicking on a username, nothing appears.

An example of the search is
![image](https://user-images.githubusercontent.com/23047367/184157217-9adc41e1-5dfa-480f-9732-db76f503042e.png)

The githash is a2082367.

**Comment by dansup** [comment]
@stephenjmaher Did you run `php artisan passport:install` after installing?

**Comment by stephenjmaher** [comment]
I have run `php artisan passport:install`, but still get the same result.

**Comment by keunes** [comment]
I am a user on pixelfed.eu and I'm experiencing the same. I'm trying to follow this user: https://pixelfilm.nz/jennifilm but when searching for jennifilm@pixelfilm.nz in the search bar (pressing enter does nothing, it seems it should automatically show results), nothing is returned:
![Imagepipe_2.jpg](https://user-images.githubusercontent.com/11229646/189450391-2b1f03d9-223e-4350-80d8-2a78fb9c634e.jpg)

Should I reach out to the server admin?

**Comment by SathyaBhat** [comment]
> I am a user on pixelfed.eu and I'm experiencing the same. I'm trying to follow this user: https://pixelfilm.nz/jennifilm but when searching for jennifilm@pixelfilm.nz in the search bar (pressing enter does nothing, it seems it should automatically show results), nothing is returned:
> ![Imagepipe_2.jpg](https://user-images.githubusercontent.com/11229646/189450391-2b1f03d9-223e-4350-80d8-2a78fb9c634e.jpg)
> 
> Should I reach out to the server admin?

Try pasting the URL in the search box ie `https://pixelfilm.nz/jennifilm`, that fetches the user.

**Comment by koreus** [comment]
> @stephenjmaher Did you run `php artisan passport:install` after installing?

I had the same problem, search didn't work and this command solved it . But it is not in the Install doc.  It should be add, no ?

**Comment by stephenjmaher** [comment]
I ended up doing a complete reinstall. It appears to be working on the new install. Not sure what made the difference.

@koreus I agree, putting `php artisan passport:intall` in the documentation would be helpful.
