### ISSUE TITLE
GIF preview not showing on trending pages.

### ISSUE THREAD

**Issue by filippodb** [pixelfed/pixelfed#3619]
My GIF animation is here:

https://pixelfed.uno/i/web/post/463349801741693003

on trending page it show a: "No preview available":

https://pixelfed.uno/i/web/discover

![immagine](https://user-images.githubusercontent.com/7091176/184374495-8a96d547-8658-4f34-8195-9a5a7e2d1e69.png)

**Comment by trwnh** [comment]
Duplicate of #567
