### ISSUE TITLE
Cannot hide my likes in pixelfed. In the web version.

### ISSUE THREAD

**Issue by milkywaymetropolis** [pixelfed/pixelfed#3621]
Well the title says it all. I tried to find its setting. Unable. Pls help. However app doesn't show likes count. Pls add a feature to hide likes count or help me with this issue. Add more privacy features related to this.

**Comment by MrAn0nym** [comment]
Hidden likes would only be visible to you and the person whose post you liked, right?

> However app doesn't show likes count

which app are you referring to?

**Comment by milkywaymetropolis** [comment]
When i like others post, who aren't my followers or maybe followers too. It shows on my liked panel. I want to make it private.
