### ISSUE TITLE
image non showing on mastodon

### ISSUE THREAD

**Issue by filippodb** [pixelfed/pixelfed#3622]
HI, I have created this post on pixelfed:

https://pixelfed.uno/i/web/post/464112652979177326

but that image is not showing on mastodon:

https://mastodon.uno/tags/daitarn3

this is the image: https://jirafeau.devol.it/f.php?h=14pSbE6W&p=1

It's a  5MB jpg image, is it too big?

![daitarnJapan](https://user-images.githubusercontent.com/7091176/184532915-5efed8ec-75ea-4972-b3ad-5a134041aeaa.jpg)

**Comment by MrAn0nym** [comment]
Seems to be an issue on mastodon's side, the file size could be the cause though

**Comment by trwnh** [comment]
pixelfed.uno is not loading, that's probably it
