### ISSUE TITLE
Federation issues

### ISSUE THREAD

**Issue by mgrzeca** [pixelfed/pixelfed#3630]
Using a personal instance makes you feel really lonely. I follow over 200 people from various instances, not only from Pixelfed. I can see their posts on my home timeline, however, activities related to these posts come only from people I already follow. I can't see comments or likes from people outside my "following" collection. In a situation where the content of the discovery page only contains posts from my own instance, it becomes impossible to find new people without having an account on a different, larger instance. This seems incorrect or at least undesirable.

**Comment by piratenpanda** [comment]
I already mentioned this on mastodon and @dansup said likes and reshares will also be federated in the future as well as better discovery possibilities. But I agree, running your own instance feels very lonely and the community aspect can certainly be improved upon.
