### ISSUE TITLE
production.ERROR: Command 'ZPOPMIN' is not a registered Redis command

### ISSUE THREAD

**Issue by xundeenergie** [pixelfed/pixelfed#3633]
When i Like a shared pixeldfed-posting (friendica user shared a posting from pixelfed, a pleroma-user, following the friendica-user likes the shared posting) i get this error in pixelfed

`Aug 29 12:21:26 srvimages ja-pix[1360928]: [2022-08-29 10:21:26] production.ERROR: Command 'ZPOPMIN' is not a registered Redis command. {"exception":"[object] (Predis\\ClientException(code: 0): Command 'ZPOPMIN' is not a registered Redis command. at /usr/share/webapps/pixelfed/vendor/predis/predis/src/Profile/RedisProfile.php:88)
`
The like on pleroma is not shared to friendica and pixelfed.

Searching for the pixelfed-url of a posting in pleroma and like this posting from pleroma works as expected. 

OS: Debian Bullseye
Redis: 
```
# dpkg -l|grep redis
ii  php-redis                            5.3.2+4.3.0-2+deb11u1                 amd64        PHP extension for interfacing with Redis
ii  redis                                5:6.0.16-1+deb11u2                    all          Persistent key-value database with network interface (metapackage)
ii  redis-server                         5:6.0.16-1+deb11u2                    amd64        Persistent key-value database with network interface
ii  redis-tools                          5:6.0.16-1+deb11u2                    amd64        Persistent key-value database with network interface (client)
```
But Redis writes on https://redis.io/commands/zpopmin/  that zpopmin is part of redis 5.0.0

**Comment by xundeenergie** [comment]
Is it possible, that php-redis is too old (the newest and only available version in debian!)

because when i run redis-cli i can execute ZPOPMIN

**Comment by xundeenergie** [comment]
I searched in https://github.com/phpredis/phpredis/blob/develop/redis_commands.h for zpopmin command... and i could not find it even there...

**Comment by dadall** [comment]
Hey,

Same issue here. Notification are impacted. 

OS : Debian 11
PHP : 8.0
Redis : 6.0

**Comment by dadall** [comment]
Fixed adding `REDIS_CLIENT=phpredis` in the .env with php-redis installed.

Thanks @dansup for the tips :+1:

**Comment by urtzai** [comment]
Since the last update (https://github.com/pixelfed/pixelfed/releases/tag/v0.11.4) i got this error. But even if I add `REDIS_CLIENT=phpredis` problem is not solve due to this error when I execute composer install:

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   RedisException 

  No such file or directory

  at vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:153
    149▕                 $parameters[] = $context;
    150▕             }
    151▕         }
    152▕ 
  ➜ 153▕         $client->{($persistent ? 'pconnect' : 'connect')}(...$parameters);
    154▕     }
    155▕ 
    156▕     /**
    157▕      * Create a new redis cluster instance.

      +14 vendor frames 
  15  app/Services/ConfigCacheService.php:86
      Illuminate\Support\Facades\Facade::__callStatic()

  16  app/helpers.php:7
      App\Services\ConfigCacheService::get()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

OS: Debian Buster
Redis:
```
# dpkg -l|grep redis
ii  php-redis                         5.3.7+4.3.0-1+0~20220330.42+debian10~1.gbp6fe8b7 amd64        PHP extension for interfacing with Redis
ii  php8.1-redis                      5.3.7+4.3.0-1+0~20220330.42+debian10~1.gbp6fe8b7 amd64        PHP extension for interfacing with Redis
ii  redis                             6:7.0.5-1rl1~buster1                             all          Persistent key-value database with network interface (metapackage)
ii  redis-server                      6:7.0.5-1rl1~buster1                             amd64        Persistent key-value database with network interface
ii  redis-tools                       6:7.0.5-1rl1~buster1                             amd64        Persistent key-value database with network interface (client)
```
I think the PHP version is not a problem, because I also tried with 7.4 and the result was the same.

Can someone give me any clue? Thanks

**Comment by ewagoner** [comment]
This issue suddenly appeared for me after weeks of use, and changing `REDIS_CLIENT=phpredis` fixed it for me.

**Comment by xundeenergie** [comment]
> This issue suddenly appeared for me after weeks of use, and changing `REDIS_CLIENT=phpredis` fixed it for me.

This fixed it for me too!!

**Comment by cytrinox** [comment]
Hit the same problem, additionally to switching to php-redis, I've to change the `.env` file to use redis TCP/IP connection instead of unix socket file.
