### ISSUE TITLE
Wrong profile avatar for notifications page

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#3634]
Pixelfed https://github.com/pixelfed/pixelfed/commit/99fe46ead408b7bd3c2dd06017839248f90df5d1

Even if **local** profile has image, it shows default (blank) avatar

note: _remote_ profile shows correct avatar

![notificationsavatardefault](https://user-images.githubusercontent.com/1679025/187224924-87cde19d-e2c8-4875-8894-6a40fecae624.jpg)

Not sure if it related to https://github.com/pixelfed/pixelfed/issues/3559

**Comment by dansup** [comment]
Fixed in 989e424
