### ISSUE TITLE
Wrong comments count displayed

### ISSUE THREAD

**Issue by strk** [pixelfed/pixelfed#3651]
The count of comments under a post is lower than the actual number of comments in it.

See this:
![image](https://user-images.githubusercontent.com/289678/189079272-ecd41849-b926-43e5-9f0a-eff3d64b3aaf.png)

It's happening here: https://pixelfed.de/i/web/post/473298527647553820

Problem propagates to PixelDroid too:
https://gitlab.shinice.net/pixeldroid/PixelDroid/-/issues/340

**Comment by okpierre** [comment]
@strk view `i/web` view shows (2) comments and other view shows number as (4) comments - how many does pixeldroid show (2) or (4)?

**Comment by strk** [comment]
Now four (maybe some cache expired) but you can see it showed 2 in my screenshot
