### ISSUE TITLE
Download original Image

### ISSUE THREAD

**Issue by davidak** [pixelfed/pixelfed#3654]
When i share content with a free license, i want others to be able to **use** it. For that, they need the original file. Other platforms like Flickr or Wikimedia Commons let users download the image in original size and smaller.

Currently it seem to copy Instagram where users should only consume and not remix and participate.

I uploaded a 2048x2048px JPEG (2.3MB) which was downscaled and compressed to 1080x1080px (432kB). The original PNG is 9.4MB, so a lot of information is lost.

**Comment by eobet** [comment]
Yeah, I agree. I must admit, I thought this was the entire point of Pixelfed, seeing as Mastodon haven't budged in this area in several years (however, they also unfortunately seem to block any image above 2MP in size, which is beyond terrible).

**Comment by mitexleo** [comment]
You need to turn off Image Optimization.
