### ISSUE TITLE
Help set up the S3 backblaze

### ISSUE THREAD

**Issue by Shizanit** [pixelfed/pixelfed#3664]
with this configuration I get an error

**Comment by Shizanit** [comment]
fixed 
![image](https://user-images.githubusercontent.com/65107731/192102629-aa2c8f4d-ba5a-4519-8cc5-175ebd0e2219.png)

**Comment by Shizanit** [comment]
not fixed
the links come out like this 
http://pixel.securetown.tophttps://f003.backblazeb2.com/file/Pixel-SecureTown/public/avatars/047/928/285/336/148/787/3/R3jZakFEveJVW34xXRh0_avatar.png?v=5

![image](https://user-images.githubusercontent.com/65107731/192102957-6fb9c843-8132-490d-a911-463679a20431.png)

**Comment by jbfriedrich** [comment]
I am trying to use Backblaze B2 as S3 compatible storage, too. But I am similarly unsuccessful. This is my S3 config:

```
## S3
FILESYSTEM_DRIVER=s3
FILESYSTEM_CLOUD=s3
PF_ENABLE_CLOUD=true
AWS_ACCESS_KEY_ID=<redacted>
AWS_SECRET_ACCESS_KEY=<redacted>
AWS_DEFAULT_REGION=us-west-000
AWS_BUCKET=mybucketname
AWS_URL=mybucketname.s3.us-west-000.backblazeb2.com
AWS_ENDPOINT=https://s3.us-west-000.backblazeb2.com/file/mybucketname
AWS_USE_PATH_STYLE_ENDPOINT=false
```

And this is the error message that I got:

```
pixelfed-worker-1  | 2023-07-24T03:38:43.792777494Z [2023-07-24 03:38:42] production.ERROR: Unable to write file at location: public/m/_v2/588893769629233153/bf0f52ff2-92677b/r0VgWn4p7h8x/dUCLsIccAnqO027bzX0sA9rMRCUbUhgtRCkKwThG.jpg. Custom endpoint `s3.us-west-000.backblazeb2.com` was not a valid URI {"exception":"[object] (League\\Flysystem\\UnableToWriteFile(code: 0): Unable to write file at location: public/m/_v2/588893769629233153/bf0f52ff2-92677b/r0VgWn4p7h8x/dUCLsIccAnqO027bzX0sA9rMRCUbUhgtRCkKwThG.jpg. Custom endpoint `s3.us-west-000.backblazeb2.com` was not a valid URI at /var/www/vendor/league/flysystem/src/UnableToWriteFile.php:24)
pixelfed-worker-1  | 2023-07-24T03:38:43.792796549Z [stacktrace]
pixelfed-worker-1  | 2023-07-24T03:38:43.793120535Z [previous exception] [object] (Aws\\Exception\\UnresolvedEndpointException(code: 0): Custom endpoint `s3.us-west-000.backblazeb2.com` was not a valid URI at /var/www/vendor/aws/aws-sdk-php/src/EndpointV2/Rule/ErrorRule.php:41)
pixelfed-worker-1  | 2023-07-24T03:38:43.793127357Z [stacktrace]
```

I also tried it with `AWS_ENDPOINT=https://s3.us-west-000.backblazeb2.com:443`, but to no avail. Any help or advise would be greatly appreciated, as I am out of ideas.

**Comment by mitexleo** [comment]
> I am trying to use Backblaze B2 as S3 compatible storage, too. But I am similarly unsuccessful. This is my S3 config:
> 
> ```
> ## S3
> FILESYSTEM_DRIVER=s3
> FILESYSTEM_CLOUD=s3
> PF_ENABLE_CLOUD=true
> AWS_ACCESS_KEY_ID=<redacted>
> AWS_SECRET_ACCESS_KEY=<redacted>
> AWS_DEFAULT_REGION=us-west-000
> AWS_BUCKET=mybucketname
> AWS_URL=mybucketname.s3.us-west-000.backblazeb2.com
> AWS_ENDPOINT=https://s3.us-west-000.backblazeb2.com/file/mybucketname
> AWS_USE_PATH_STYLE_ENDPOINT=false
> ```
> 
> And this is the error message that I got:
> 
> ```
> pixelfed-worker-1  | 2023-07-24T03:38:43.792777494Z [2023-07-24 03:38:42] production.ERROR: Unable to write file at location: public/m/_v2/588893769629233153/bf0f52ff2-92677b/r0VgWn4p7h8x/dUCLsIccAnqO027bzX0sA9rMRCUbUhgtRCkKwThG.jpg. Custom endpoint `s3.us-west-000.backblazeb2.com` was not a valid URI {"exception":"[object] (League\\Flysystem\\UnableToWriteFile(code: 0): Unable to write file at location: public/m/_v2/588893769629233153/bf0f52ff2-92677b/r0VgWn4p7h8x/dUCLsIccAnqO027bzX0sA9rMRCUbUhgtRCkKwThG.jpg. Custom endpoint `s3.us-west-000.backblazeb2.com` was not a valid URI at /var/www/vendor/league/flysystem/src/UnableToWriteFile.php:24)
> pixelfed-worker-1  | 2023-07-24T03:38:43.792796549Z [stacktrace]
> pixelfed-worker-1  | 2023-07-24T03:38:43.793120535Z [previous exception] [object] (Aws\\Exception\\UnresolvedEndpointException(code: 0): Custom endpoint `s3.us-west-000.backblazeb2.com` was not a valid URI at /var/www/vendor/aws/aws-sdk-php/src/EndpointV2/Rule/ErrorRule.php:41)
> pixelfed-worker-1  | 2023-07-24T03:38:43.793127357Z [stacktrace]
> ```
> 
> I also tried it with `AWS_ENDPOINT=https://s3.us-west-000.backblazeb2.com:443`, but to no avail. Any help or advise would be greatly appreciated, as I am out of ideas.

Don't include ports.

**Comment by jbfriedrich** [comment]
As I wrote above, I tried both. Does not work for me. Neither with or without ports 😞

**Comment by jbfriedrich** [comment]
I resolved my problem thanks to @dansup help. This is my working configuration:

```
## S3
FILESYSTEM_DRIVER=s3
FILESYSTEM_CLOUD=s3
PF_ENABLE_CLOUD=true
AWS_ACCESS_KEY_ID=<key ID>
AWS_SECRET_ACCESS_KEY=<application key>
AWS_DEFAULT_REGION=us-west-000
AWS_BUCKET=mybucket
AWS_ENDPOINT=https://s3.us-west-000.backblazeb2.com
AWS_USE_PATH_STYLE_ENDPOINT=false
```

I had to completely nuke my containers though. It seems that the wrong path from all the testing was stuck in the database somehow.

**Comment by Shizanit** [comment]
> 



> I resolved my problem thanks to @dansup help. This is my working configuration:
> 
> ```
> ## S3
> FILESYSTEM_DRIVER=s3
> FILESYSTEM_CLOUD=s3
> PF_ENABLE_CLOUD=true
> AWS_ACCESS_KEY_ID=<key ID>
> AWS_SECRET_ACCESS_KEY=<application key>
> AWS_DEFAULT_REGION=us-west-000
> AWS_BUCKET=mybucket
> AWS_ENDPOINT=https://s3.us-west-000.backblazeb2.com
> AWS_USE_PATH_STYLE_ENDPOINT=false
> ```
> 
> I had to completely nuke my containers though. It seems that the wrong path from all the testing was stuck in the database somehow.

how did you build the docker image?

**Comment by jbfriedrich** [comment]
> how did you build the docker image?

Checked out the git repo and used the apache Dockerfile in contrib: `docker build --force-rm --rm --no-cache -t jbfriedrich/pixelfed-apache:latest -f contrib/docker/Dockerfile.apache .` I am running it behind a Træfik proxy

**Comment by Shizanit** [comment]
> > how did you build the docker image?
> 
> Checked out the git repo and used the apache Dockerfile in contrib: `docker build --force-rm --rm --no-cache -t jbfriedrich/pixelfed-apache:latest -f contrib/docker/Dockerfile.apache .` I am running it behind a Træfik proxy

and you've done this? ( https://docs.pixelfed.org/running-pixelfed/installation/#one-time-setup-tasks )

**Comment by MrRoyce** [comment]
> 



> > 
> 
> > I resolved my problem thanks to @dansup help. This is my working configuration:
> > ```
> > ## S3
> > FILESYSTEM_DRIVER=s3
> > FILESYSTEM_CLOUD=s3
> > PF_ENABLE_CLOUD=true
> > AWS_ACCESS_KEY_ID=<key ID>
> > AWS_SECRET_ACCESS_KEY=<application key>
> > AWS_DEFAULT_REGION=us-west-000
> > AWS_BUCKET=mybucket
> > AWS_ENDPOINT=https://s3.us-west-000.backblazeb2.com
> > AWS_USE_PATH_STYLE_ENDPOINT=false
> > ```


@jbfriedrich Did you restart everything from scratch?  I'm building using ansible, and if I use similar parameters, I get the following error during the `php artisan migrate --force` command:

```
 2023_02_04_053028_fix_cloud_media_paths FAIL", "", "In ErrorRule.php line 41:" Custom endpoint `https//s3.us-west-004.backblazeb2.com` was not a valid URI
```

**Comment by MrRoyce** [comment]
> 



> > 
> 
> > I resolved my problem thanks to @dansup help. This is my working configuration:
> > ```
> > ## S3
> > FILESYSTEM_DRIVER=s3
> > FILESYSTEM_CLOUD=s3
> > PF_ENABLE_CLOUD=true
> > AWS_ACCESS_KEY_ID=<key ID>
> > AWS_SECRET_ACCESS_KEY=<application key>
> > AWS_DEFAULT_REGION=us-west-000
> > AWS_BUCKET=mybucket
> > AWS_ENDPOINT=https://s3.us-west-000.backblazeb2.com
> > AWS_USE_PATH_STYLE_ENDPOINT=false
> > ```


@jbfriedrich Did you restart everything from scratch?  I'm building using ansible, and if I use similar parameters, I get the following error during the `php artisan migrate --force` command:

```
 2023_02_04_053028_fix_cloud_media_paths FAIL", "", "In ErrorRule.php line 41:" Custom endpoint `https//s3.us-west-004.backblazeb2.com` was not a valid URI
```

**Comment by jbfriedrich** [comment]
> I had to completely nuke my containers though. It seems that the wrong path from all the testing was stuck in the database somehow.

Yes, as mentioned I had to start from scratch with the right configuration. I am sure with the right commands, and knowledge of the database structure, this would be quick to fix. But I just tore everything down and redeployed.

**Comment by MrRoyce** [comment]
> > I had to completely nuke my containers though. It seems that the wrong path from all the testing was stuck in the database somehow.
> 
> Yes, as mentioned I had to start from scratch with the right configuration. I am sure with the right commands, and knowledge of the database structure, this would be quick to fix. But I just tore everything down and redeployed.

Thanks.. of course my error here was a silly typo.. the type that you can stare at for days before you see it... Now I'm past that error but on to the next one!  Now Redis is acting up... maybe I'll try disabling it??

**Comment by jbfriedrich** [comment]
No idea, sorry. I have different issues with federation. I think it's not yet ready if you are not a developer who can dive into the code.
