### ISSUE TITLE
Cloud Storage breaks Avatar url

### ISSUE THREAD

**Issue by mackiexx** [pixelfed/pixelfed#3677]
i recently started my website which was yesterday but this problem still occurs on my website. i cloned directly from here and i thought the change was committed already. this hasn't been solved?

it shows up like this

https://my-redacted-domain.comhttps://my-redacted-cloud-storage.com/pixelfed-bucket-20220728-1330/public/avatars/046/211/443/849/321/677/2/uu1zCsXDguuGj5I2nAUE_avatar.jpg?v=2

**Comment by mackiexx** [comment]
Fixed it

**Comment by emilweth** [comment]
How ?

**Comment by okpierre** [comment]
> How ?

@emilweth a fix was submitted and waiting for @dansup to review for next release
