### ISSUE TITLE
Posting Story doesn't work due to crop issue

### ISSUE THREAD

**Issue by maxheadroom** [pixelfed/pixelfed#3682]
When I'm uploading an image to a story on my 0.11.4 instance I'm getting an error after the crop step. The server returns a HTTP 500 error for 
`"POST /api/web/stories/v1/crop HTTP/1.1" 500 1282 "https://pxl.mxhdr.net/i/stories/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"`

```
{
  "error": "No query results for model [App\\Story] 483167154362736641"
}

```
I've recently upgrade from 0.11.3 to 0.11.4 and also executed withe post-upgrade.sh script without any erros.

**Comment by mackiexx** [comment]
> When I'm uploading an image to a story on my 0.11.4 instance I'm getting an error after the crop step. The server returns a HTTP 500 error for `"POST /api/web/stories/v1/crop HTTP/1.1" 500 1282 "https://pxl.mxhdr.net/i/stories/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"`
> 
> ```
> {
>   "error": "No query results for model [App\\Story] 483167154362736641"
> }
> ```
> 
> I've recently upgrade from 0.11.3 to 0.11.4 and also executed withe post-upgrade.sh script without any erros.

I am using AWS s3 storage so it doesn't work for me cause i think the path is wrong. it works when i use local disk

**Comment by maxheadroom** [comment]
Looks like this issue is related to issues with MYSQL DB. I was using mysql 8.0 docker image. I found this other thread with similar errors: https://github.com/pixelfed/pixelfed/issues/2989 

I've switched to MARIADB now and everything seems to work fine....

**Comment by maxheadroom** [comment]
Looks like MariaDB solved the problem. Although I did a fresh installation using the provided docker-compose.yml file which references the MySQL 8.0 docker image. That reliably produced the error. Using the MariaDB:latest docker image as a drop-in replacement solved the problem.
