### ISSUE TITLE
 The emoji must be a file of type: jpg, png.

### ISSUE THREAD

**Issue by mackiexx** [pixelfed/pixelfed#3690]
Unable to add custom emoji in admin. I have added .jpg and .png format and yet i still get this error. i am using s3 storage

**Comment by Jfmblinux** [comment]
I have the same concern
`emoji must be a file type: jpg, png.`

**Comment by syntafin** [comment]
![image](https://user-images.githubusercontent.com/695535/202856416-226a7766-c6f1-4152-b9d5-f24932ea742d.png)

I provided a PR to fix the issue
