### ISSUE TITLE
Notifications in sidebar are not updating

### ISSUE THREAD

**Issue by 23n** [pixelfed/pixelfed#3695]
Hi there, since weeks the notifications in the right sidebar are not updating. 
Neither automatically nor manually.
Is it only me? How to troubleshoot?
Pixelfed Version v0.11.4 on a shared host.

![2022-10-10PFnotifications](https://user-images.githubusercontent.com/1303101/194858592-5cd1dea9-c13f-4ff8-a1c5-8101eb578d01.png)

**Comment by 23n** [comment]
Nothing? :-(

**Comment by 23n** [comment]
SOLVED
Solution: restart redis

**Comment by betodealmeida** [comment]
I had the same problem: no notifications. I was trying to connect to an external Redis server via TLS, using `REDIS_SCHEME="tls"`, but looking at the logs I don't think that works. I installed `stunnel` to proxy the Redis traffic, and then it worked.
