### ISSUE TITLE
Adding mp4 to Story: "Oops! Unable to load FFMpeg"

### ISSUE THREAD

**Issue by teemofej** [pixelfed/pixelfed#3702]
I just set up a new production pod following the official documentation on https://docs.pixelfed.org/running-pixelfed/ and tested the new Stories feature. While photos are being processed flawlessly for Stories, mp4 videos fail with the error "Oops! Unable to load FFMpeg". Despite that, I am able to post the same mp4 videos as regular posts.

My instance is running on Ubuntu Server 22.04.1 LTS with ffmpeg version 4.4.2-0ubuntu0.22.04.1 and PHP 8.1.11.

**Comment by jcrabapple** [comment]
I am experiencing the same issue on Pixelfed 11.5.

**Comment by Thomas-Schmall** [comment]
Still going on v0.11.8 at (https://pixelfed.org/)
I tried a couple different compression/container settings. But it doesn't want AVI or such, just FFMpeg, it says. Other combis and smaller file sizes (under 4 MB) didn't work either. But I dunno much about video compression to try more than the standard options my editor gives me.
