### ISSUE TITLE
Enable ActivityPub by default?

### ISSUE THREAD

**Issue by osresearch** [pixelfed/pixelfed#3727]
The example configuration sets `ACTIVITY_PUB=false`: https://github.com/pixelfed/pixelfed/blob/2bb27229f3f8c315d193010106fc328b6f3ac578/.env.docker#L94

Is there a reason to not enable it (and the other federated features) by default?

**Comment by harmtemolder** [comment]
I imagine a lot of people cloning/forking and trying out Pixelfed without actually setting it up all the way, on a public domain, with frontend proxies and everything. Those instances do not need to be part of the greater ActivityPub ecosystem yet, or do you disagree?

Having `ACTIVITY_PUB=false` as default means it is a conscious decision to enable it, I would say.
