### ISSUE TITLE
Ability to add link back to Mastodon

### ISSUE THREAD

**Issue by stevolucidity** [pixelfed/pixelfed#3728]
I can't find an obvious way to include a <link rel="me"....> to the headers.

Can we have an option to do this in preferences? Or maybe let us know which file to add the link to?

**Comment by ghost** [comment]
I was looking to do this as well, would be handy

**Comment by nourkagha** [comment]
As per #459, you just need to add a link to your Mastodon profile in the Website field.

**Comment by stevolucidity** [comment]
Obviously done that, but the link back doesn't get rendered in the headers on the pixelfed side.

**Comment by nourkagha** [comment]
Hmm I'm not sure what this means, can you give an example?

From what I understood from the initial post, you're attempting to add HTML (with rel=me) to your Pixelfed profile, but this is not needed as all you need to do is enter the Mastodon link itself in the Website field (it automatically does rel=me).

**Comment by stevolucidity** [comment]
Sure! 🙂 
Following your example...

![721309AD-2BFA-4F6D-9B34-1AE3602B3161_4_5005_c](https://user-images.githubusercontent.com/44602820/202850849-6a68aa7a-4da4-4a3f-9cfa-e534f1e2968e.jpeg)

...I don't see any verification on the Mastodon side:

![70689B18-1686-48A6-B667-DA06C52FF939_4_5005_c](https://user-images.githubusercontent.com/44602820/202850862-c0ee294e-8a7e-4d8b-badb-151ba7f6dcf4.jpeg)

**Comment by SathyaBhat** [comment]
Did you try to save the profile on Mastodon after adding it in Pixelfed? As I gather Mastodon's verification checks run when you save it, not on a scheduled basis.

Also the new Metro UI doesn't have the rel=me tag, so you will have to force point to the old UI for verification to be successful.

**Comment by stevolucidity** [comment]
Thanks, @SathyaBhat.

The last point probably indicates my real issue. Not much point trying to chase it, then! 🙂
Thanks for clearing that up for me.

**Comment by ghost** [comment]
Folks,

thanks for the discussion here which helped me to link back my Pixelfed-profile to my Mastodon-profile and vice versa!
