### ISSUE TITLE
Add register page links (terms, data policy, cookie policy)

### ISSUE THREAD

**Issue by jish** [pixelfed/pixelfed#373]
### Steps to reproduce:

1. Disable cookies in your browser
2. Visit https://pixelfed.social/register
3. Click on any of "Terms", "Data Policy" or "Cookies Policy".
4. Browser emits a security warning when attempting to set cookies or use local storage
5. No policies are displayed to the user

### Expected result:

To be able to read "Terms", "Data Policy" and "Cookies Policy".

<img width="817" alt="screen shot 2018-08-13 at 10 20 30 pm" src="https://user-images.githubusercontent.com/1817/44073159-5606b75c-9f47-11e8-8198-f5fd81be3779.png">

### Browser

Firefox `61.0.2`

**Comment by dansup** [comment]
@jish This has nothing to do with cookies, the Terms, Data Policy and Cookies Policy links dont actually link anywhere yet.

**Comment by jish** [comment]
Oh, ok. Sorry about that 😉
