### ISSUE TITLE
Uploaded caption text is initially displayed without linefeeds

### ISSUE THREAD

**Issue by lightaffaire** [pixelfed/pixelfed#3731]
When I upload an image with caption text via the webpage dialog the caption text is initially displayed without linefeeds that are present in the upload caption text.

A browser reload (F5) will then display the caption text correctly.

UPDATE: latest post to my profile is still unformatted after numerous refreshes:

![pixelfed-now-broken](https://user-images.githubusercontent.com/59885511/200493747-b7340bb6-f5c1-45ea-bb8e-d8ac42c8e7b9.png)

UPDATE #2: I checked back 4 hours later and did a browser refresh. Now the caption text is correctly formatted.

Attached screenshots showing the problem:

![pixelfed-just-posted](https://user-images.githubusercontent.com/59885511/200488348-a6ce8eda-0476-4b2c-957b-87cb9fd53606.png)
![pixelfed-after-f5-or browser-refresh](https://user-images.githubusercontent.com/59885511/200488429-3cec1a77-45c9-4f57-aad2-95d27f78e924.png)

**Comment by ArcEdge** [comment]
I am running into the same issue, or a very similar issue. It seems like one out of every five or six attempts to upload an image with formatting and linebreaks actually goes through successfully, and that Pixelfed just eats my line breaks on the other attempts. I haven't noticed any of the formatting re-appearing upon refresh attempts.

**Comment by lightaffaire** [comment]
For me it is every upload. Manual refresh after upload no longer has any effect works BUT 1-4 hours later the formatting seems to be corrected. Is there some kind of lazy update process running across new uploads is my currect thought?

**Comment by twatzl** [comment]
This is probably connected: If I use shift+enter in the caption text dialog the linefeeds are not displayed, but if I write the text first in VSCode and then copy it to the caption box then the linefeeds are working.

![image](https://user-images.githubusercontent.com/18753370/205360222-126ec0e2-9849-4751-bad2-8ea1f5aa747b.png)

![image](https://user-images.githubusercontent.com/18753370/205360297-eb5838cc-afa3-48db-b0b2-0b14658bc1bb.png)

After 15 minutes there was no change. Will try again in a couple of hours.

Edit: Now after ~ 30 minutes the post which was formatted in the web ui is now also correctly displayed:
![image](https://user-images.githubusercontent.com/18753370/205364984-ff56675a-15d6-4582-baaa-3c0002ef0847.png)

**Comment by jim-easterbrook** [comment]
I've just run into this (or a problem like it) when posting via the Mastodon.py Python package. It hadn't occurred to me to wait after posting to see if it reformats itself correctly. Time for more testing...

1 hour later: Still no line breaks on pixelfed, but the same post showed correctly immediately when viewed from Mastodon.

**Comment by jim-easterbrook** [comment]
I've just discovered that if I have a post that is missing line breaks I just have to "like" it, and then "unlike" it, to make it display properly.

**Comment by lightaffaire** [comment]
@jim-easterbrook i just tried your like plus unlike 'hack' and yes it does correctly format with linefeeds.

Would be great to get this fixed @dansup

**Comment by jim-easterbrook** [comment]
It appears that v0.11.6 breaks this 'hack'. I now can't get posts to display the line feeds.

[Edit: I've found this was a problem with my uploader software. The 'hack' is still there.]

**Comment by trwnh** [comment]
Duplicate of #3909
