### ISSUE TITLE
Update from Laravel 8 to Laravel 9 breaks picture uploads

### ISSUE THREAD

**Issue by jemayer** [pixelfed/pixelfed#3739]
Besides raising the minimum PHP requirements to PHP8 (which would have to be adjusted in the setup documentation), the Laravel update in 18f3fcc663ea152b592aa2ddc189531e06e3b346 breaks picture uploads due to wrong storage/cache permissions on directory level, as discussed here: https://laracasts.com/discuss/channels/laravel/laravel-9-storage-permission.

I'm sorry my PHP days are long ago, so all I can do is highlight the issue. Please don't take this as a complaint, I'm thankful for all the incredible work you are doing on Pixelfed!

**Comment by goxonline** [comment]
The file where the permissions should be set is: 

config/filesystems.php

I have set the permissions, but it does absolutely nothing....

**Comment by goxonline** [comment]
Ferget to run:

php artisan config:cache

And its fix!

Check the pull:

[https://github.com/pixelfed/pixelfed/pull/3825](https://github.com/pixelfed/pixelfed/pull/3825)

Regards,

**Comment by escuco** [comment]
The fix #3825 worked for me.
After applying the patch I had to delete `/storage/app/public/m` because of the wrong, old permissions.
