### ISSUE TITLE
Call to undefined method Illuminate\Validation\Factory::includeUnvalidatedArrayKeys()

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#3741]
`  Call to undefined method Illuminate\Validation\Factory::includeUnvalidatedArrayKeys()

  at vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
    257▕         if (! $instance) {
    258▕             throw new RuntimeException('A facade root has not been set.');
    259▕         }
    260▕ 
  ➜ 261▕         return $instance->$method(...$args);
    262▕     }
    263▕ }
    264▕ 

  1   app/Providers/AppServiceProvider.php:58
      Illuminate\Support\Facades\Facade::__callStatic()

      +7 vendor frames 
  9   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()`

**Comment by dansup** [comment]
Run `composer update`
