### ISSUE TITLE
Error when deleting photos League\Flysystem\Filesystem must be of type string

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#3751]
PHP: 8.1.12 / Laravel: 9.38.0 / Pixelfed: 0.11.4 https://github.com/pixelfed/pixelfed/commit/92dd5b9abf5693e9c838211e40f54551f3fc96cc

After upgrading to the latest unable to delete photos

`League\Flysystem\Filesystem::has(): Argument #1 ($location) must be of type string, null given, called in /pixelfed/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php on line 181 {"userId":1,"exception":"[object] (TypeError(code: 0): League\\Flysystem\\Filesystem::has(): Argument #1 ($location) must be of type string, null given, called in /pixelfed/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php on line 181 at /pixelfed/vendor/league/flysystem/src/Filesystem.php:51)`

Stacktrace: https://pastebin.com/kSrKJnvV

![pixelfeddelete](https://user-images.githubusercontent.com/1679025/201495702-89f0ec24-1518-41d9-bfcd-b98750c9503d.jpg)

**Comment by dansup** [comment]
Please run `composer update` after updating, you are missing the latest aws sdk

**Comment by okpierre** [comment]
@dansup Still not working after updating. Again this is a new installation. Even restarted the server. Unable to reopen issue.
