### ISSUE TITLE
Liking is too slow

### ISSUE THREAD

**Issue by faissaloo** [pixelfed/pixelfed#376]
The like button should change immediately when clicked, in order to indicate that the click/tap has actually been recieved. The fact that it doesn't currently do this will lead to users tapping it multiple times in order to change it. I understand however that there must also be a way of indicating that the like has been accepted hence I propose the outline change color when clicked but become filled in when the like is accepted.

**Comment by dansup** [comment]
@faissaloo I will fix this, like I did with the comment form!

**Comment by Ichabod** [comment]
Also liking produces a new browser history item what it should not...

**Comment by trwnh** [comment]
Fixed at some point
