### ISSUE TITLE
Does it support Ios images and is s3 storage fixed?

### ISSUE THREAD

**Issue by mackiexx** [pixelfed/pixelfed#3763]
Unfortunately, iphone users cannot post photos because of pixelfed inability to convert other photo formats, also s3 storage url is broken when you use it. Has this been fixed? Couldn't use pixelfed cause of this

**Comment by okpierre** [comment]
@mackiexx setup a brand new install using https://github.com/pixelfed/pixelfed/commit/92dd5b9abf5693e9c838211e40f54551f3fc96cc and problem exists. It might be related to flysystem but not certain
