### ISSUE TITLE
can't follow my account from mastadon

### ISSUE THREAD

**Issue by ahmed12345678910111213141516** [pixelfed/pixelfed#3773]
can't follow my account nor any account on pixelfed from mastadon
tried other mastadon instance but didn't work
it shows that follow request sent
i have disabled tgat from setting but nothing change

**Comment by ivanvector** [comment]
I also have this issue, on Mastodon v4.0.2 and PixelFed v0.11.4. I can send a follow request from Mastodon and it is now marked as "awaiting approval", but I have no request to approve on the PixelFed side.

**Comment by ahmed12345678910111213141516** [comment]
look like it have a delay time 
its works now

**Comment by ivanvector** [comment]
Confirmed, the follow request did come through eventually and I did not have to approve it. Same with a reply I made to a boosted post on Mastodon, it took a while but it did come through.
