### ISSUE TITLE
"Edit Profile" and "My Portfolio" buttons clash on mobile portrait

### ISSUE THREAD

**Issue by stephenpearce** [pixelfed/pixelfed#3799]
See attached. This frontend bug occurs when logged in and viewing your own profile.

The instance I am experiencing this on is [pixey.org](https://pixey.org), which as of writing is running v0.11.4.

Tested with mobile Brave in PWA mode<sup>[1]</sup> and also Brave for Windows desktop<sup>[2]</sup> under DevTools at various mobile portrait breakpoints.

Best regards.

![pixey org_i_web_profile_494263863804434022(Pixel 5)](https://user-images.githubusercontent.com/1271004/202708683-e7036d45-730d-4ef0-add0-3886ef90f78b.png)

[1] Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)
[2] Version 1.45.123 Chromium: 107.0.5304.110

**Comment by mitexleo** [comment]
I also noticed the same

**Comment by jphastings** [comment]
Confirmed also occurring on pixelfed.social on Chrome v107.0.5304.105 on Android 13.

**Comment by raphgilles** [comment]
Same here

**Comment by raphgilles** [comment]
```
@media only screen and (max-width:768px) {
.btn.btn-light.font-weight-bold.btn-block.follow-btn.mt-n4 {
margin-top:8px !important;
}
}
```

In the administration panel:
Settings > Advanced > Custom CSS

This solves the problem waiting for a fix.

**Comment by mitexleo** [comment]
> 

Thanks 😊

**Comment by okpierre** [comment]
Fixed in latest commit https://github.com/pixelfed/pixelfed/commit/dedc81c00fdf2e32b7c07cac98200c7daa638ace or maybe only applied to `pxlmo` instance?

![pixelfedportfolio](https://user-images.githubusercontent.com/1679025/206963731-50d5b69f-69ce-4a9e-93a2-1d28b0e96bfa.png)
