### ISSUE TITLE
The lite link when opening pixelfed with no javascript requires javascript to work

### ISSUE THREAD

**Issue by valholl** [pixelfed/pixelfed#382]
When logging in to pixelfed with javascript disabled one is shown a page with the phrase

> Javascript is required for an optimized experience, please enable it or use the lite version.

where “lite” is a link to https://pixelfed.social/# (and thus I suspect requires javascript to work).

Of course, enabling javascript for this website shows the regular UI, so I couldn't find a way to discover the actual link to the lite version.

I've tested this on the https://pixelfed.social instance

**Comment by dansup** [comment]
The Lite UI is not yet ready, so javascript is required until it is released.
