### ISSUE TITLE
Portfolio Nginx config for subdomain

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#3827]
Hello,

I'm trying to configure the urls of the portfolio from pixelfed.fr
I want to configure the subdomain portfolio.pixelfed.fr

In the .env I added :
PORTFOLIO_DOMAIN="portfolio.pixelfed.fr"
PORTFOLIO_PATH=""

But I don't know what I have to do with Nginx. Someone can help me please ? Thanks !

**Comment by dansup** [comment]
@raphgilles Try updating your nginx `server_name` to `server_name .pixelfed.fr;` and reload, keep the `PORTFOLIO_PATH=""` and if you still have issues feel free to re-open this!
