### ISSUE TITLE
php artisan test fail

### ISSUE THREAD

**Issue by dallasgroot** [pixelfed/pixelfed#3828]
I’m running my pixelfed inside docker, when doing artisan test after a fresh install, the test passed. I pulled the latest changes and docker built the image again, though now it fails on`FAIL  Tests\Unit\Lexer\StatusLexerTest ` on autolink and `FAIL  Tests\Unit\Lexer\UsernameTest `  

` • Tests\Unit\Lexer\StatusLexerTest > autolink
  Failed asserting that two strings are equal.

  at tests/Unit/Lexer/StatusLexerTest.php:64
     60▕ 
     61▕     public function testAutolink()
     62▕     {
     63▕         $expected = '<a class="u-url mention" href="https://pixelfed.dev/pixelfed" rel="external nofollow noopener" target="_blank">@pixelfed</a> hi, really like the website! <a href="https://pixelfed.dev/discover/tags/píxelfed?src=hash" title="#píxelfed" class="u-url hashtag" rel="external nofollow noopener">#píxelfed</a>';
  ➜  64▕         $this->assertEquals($this->autolink, $expected);
     65▕     }
     66▕ 
     67▕     /** @test **/
     68▕     public function remoteMention()
  --- Expected
  +++ Actual
  @@ @@
  -'<a class="u-url mention" href="https://social.dallasgroot.ca/pixelfed" rel="external nofollow noopener" target="_blank">@pixelfed</a> hi, really like the website! <a href="https://social.dallasgroot.ca/discover/tags/píxelfed?src=hash" title="#píxelfed" class="u-url hashtag" rel="external nofollow noopener">#píxelfed</a>'
  +'<a class="u-url mention" href="https://pixelfed.dev/pixelfed" rel="external nofollow noopener" target="_blank">@pixelfed</a> hi, really like the website! <a href="https://pixelfed.dev/discover/tags/píxelfed?src=hash" title="#píxelfed" class="u-url hashtag" rel="external nofollow noopener">#píxelfed</a>'
  • Tests\Unit\Lexer\UsernameTest > generic username
  Failed asserting that two strings are equal.

  at tests/Unit/Lexer/UsernameTest.php:38
     34▕                                        ],
     35▕                                ],
     36▕                        ],
     37▕                ];
  ➜  38▕                $this->assertEquals($expectedAutolink, $autolink);
     39▕                $this->assertEquals($expectedEntity, $entities);
     40▕        }
     41▕ 
     42▕        /** @test **/
  --- Expected 
  +++ Actual
  @@ @@
  -'<a class="u-url mention" href="https://pixelfed.dev/dansup" rel="external nofollow noopener" target="_blank">@dansup</a>'
  +'<a class="u-url mention" href="https://social.dallasgroot.ca/dansup" rel="external nofollow noopener" target="_blank">@dansup</a>'
  • Tests\Unit\Lexer\UsernameTest > username with period
  Failed asserting that two strings are equal.

  at tests/Unit/Lexer/UsernameTest.php:68
     64▕                                        ],
     65▕                                ],
     66▕                        ],
     67▕                ];
  ➜  68▕                $this->assertEquals($expectedAutolink, $autolink);
     69▕                $this->assertEquals($expectedEntity, $entities);
     70▕        }
     71▕ 
     72▕        /** @test **/
  --- Expected
  +++ Actual
  @@ @@
  -'<a class="u-url mention" href="https://pixelfed.dev/dansup.two" rel="external nofollow noopener" target="_blank">@dansup.two</a>'
  +'<a class="u-url mention" href="https://social.dallasgroot.ca/dansup.two" rel="external nofollow noopener" target="_blank">@dansup.two</a>'
  • Tests\Unit\Lexer\UsernameTest > username with dash
  Failed asserting that two strings are equal.

  at tests/Unit/Lexer/UsernameTest.php:98
     94▕                                        ],
     95▕                                ],
     96▕                        ],
     97▕                ];
  ➜  98▕                $this->assertEquals($expectedAutolink, $autolink);
     99▕                $this->assertEquals($expectedEntity, $entities);
    100▕        }
    101▕ 
    102▕        /** @test **/
  --- Expected 
    +++ Actual
  @@ @@
  -'<a class="u-url mention" href="https://pixelfed.dev/dansup-too" rel="external nofollow noopener" target="_blank">@dansup-too</a>'
  +'<a class="u-url mention" href="https://social.dallasgroot.ca/dansup-too" rel="external nofollow noopener" target="_blank">@dansup-too</a>'
  • Tests\Unit\Lexer\UsernameTest > username with underscore
  Failed asserting that two strings are equal.

  at tests/Unit/Lexer/UsernameTest.php:128
    124▕                                        ],
    125▕                                ],
    126▕                        ],
    127▕                ];
  ➜ 128▕                $this->assertEquals($expectedAutolink, $autolink);
    129▕                $this->assertEquals($expectedEntity, $entities);
    130▕        }
    131▕ 
    132▕        /** @test **/
  --- Expected
  +++ Actual
  @@ @@
  -'<a class="u-url mention" href="https://pixelfed.dev/dansup_too" rel="external nofollow noopener" target="_blank">@dansup_too</a>'
  +'<a class="u-url mention" href="https://social.dallasgroot.ca/dansup_too" rel="external nofollow noopener" target="_blank">@dansup_too</a>'
  • Tests\Unit\Lexer\UsernameTest > multiple mentions
  Failed asserting that two strings are equal.

  at tests/Unit/Lexer/UsernameTest.php:175
    171▕                                ],
    172▕                        ],
    173▕                ];
    174▕ 
  ➜ 175▕                $this->assertEquals($expectedAutolink, $autolink);
    176▕                $this->assertEquals($expectedEntity, $entities);
    177▕        }
    178▕ 
    179▕ }
  --- Expected
  +++ Actual
  @@ @@
  -'hello <a class="u-url mention" href="https://pixelfed.dev/dansup" rel="external nofollow noopener" target="_blank">@dansup</a> and <a class="u-url mention" href="https://pixelfed.dev/pixelfed.team" rel="external nofollow noopener" target="_blank">@pixelfed.team</a> from <a class="u-url mention" href="https://pixelfed.dev/username_underscore" rel="external nofollow noopener" target="_blank">@username_underscore</a>'
  +'hello <a class="u-url mention" href="https://social.dallasgroot.ca/dansup" rel="external nofollow noopener" target="_blank">@dansup</a> and <a class="u-url mention" href="https://social.dallasgroot.ca/pixelfed.team" rel="external nofollow noopener" target="_blank">@pixelfed.team</a> from <a class="u-url mention" href="https://social.dallasgroot.ca/username_underscore" rel="external nofollow noopener" target="_blank">@username_underscore</a>' 
  
  
  Tests:  6 failed, 62 passed
  Time:   3.93s `

**Comment by ghost** [comment]
Same here without Docker, running 0.11.4.
<img width="437" alt="Bildschirm­foto 2022-11-27 um 01 03 10" src="https://user-images.githubusercontent.com/42076599/204113444-5694b793-46ca-45ae-bf58-c44b9d23bac1.png">

**Comment by dansup** [comment]
Are you running these from `./vendor/bin/phpunit` because they are all passing for me and our CI.

**Comment by dallasgroot** [comment]
Why close this? I’m running this from within the root of the pixelfed folder, same way you do config:cache
I’m using Docker

**Comment by todoneunl** [comment]
I have the same issue @dansup. Actually I have multiple issues with a newly installed Pixelfed and I'm trying to find the reasons. So this command was the first I tried. What you mean with "Are you running these from ./vendor/bin/phpunit"? I do `sudo -u www-data php artisan test` and the result is: 

```
Tests:    8 failed, 78 passed (97 assertions)
Duration: 6.56s
```

All related to Tests\Unit\Lexer\StatusLexerTest and Tests\Unit\Lexer\UsernameTest. 

PHP version is 8.4
