### ISSUE TITLE
Set up S3 or DO or Wassabi

### ISSUE THREAD

**Issue by ehsan0921** [pixelfed/pixelfed#3832]
Hi guys 
I'm having an issue with bucket set up.
can you please send me some sample of .Env
I tried alot but didnt work.

PF_ENABLE_CLOUD=true
FILESYSTEM_DRIVER=local
FILESYSTEM_CLOUD=s3

####Ditigal O spaces
DO_SPACES_KEY=********************
DO_SPACES_SECRET=**********************
DO_SPACES_ENDPOINT=syd1.digitaloceanspaces.com
DO_SPACES_REGION=syd1
DO_SPACES_BUCKET=aust-social
DO_SPACES_ROOT=/

**Comment by dansup** [comment]
If you are using DO Spaces, use `FILESYSTEM_CLOUD="spaces"` and run `php artisan config:cache && php artisan cache:clear`

**Comment by ehsan0921** [comment]
as long as FILESYSTEM_DRIVER=local then it upload all the files on server not S3 or DO.
