### ISSUE TITLE
Profile images dosnt load on S3

### ISSUE THREAD

**Issue by ehsan0921** [pixelfed/pixelfed#3843]
Hi guys

I linked S3 as below.

PF_ENABLE_CLOUD=true
FILESYSTEM_DRIVER=s3
FILESYSTEM_CLOUD=s3
AWS_ACCESS_KEY_ID=******
AWS_SECRET_ACCESS_KEY=*******
AWS_DEFAULT_REGION=ap-southeast-2
AWS_BUCKET=********

everything is fine with post. all uploading on S3 with no issue.
but when it comes to profile photo change. it doesn't work.
seems the address have some issue.

the address is like below:
https://aust.socialhttps//austsocial.s3.ap-southeast-2.amazonaws.com/public/*************

but it should be line 
https//austsocial.s3.ap-southeast-2.amazonaws.com/public/*************

can anyone help me with that?

Best

**Comment by ehsan0921** [comment]
in addition to that.
if I change my bucket name same as the domain name.
then for URL I put the 
AWS_URL=.s3.ap-southeast-2.amazonaws.com/

then it is fine for profile images but not for posts

**Comment by dansup** [comment]
Remove `AWS_URL` from .env, then run `php artisan config:cache && php artisan cache:clear`

**Comment by ehsan0921** [comment]
I did both of them but still same issue with the profile images.
https://aust.socialhttps//austsocial.s3.ap-southeast-2.amazonaws.com/public/avatars/502125722834407425/v8sjvm.png%3Fv%3D25
