### ISSUE TITLE
Add Rel="me" to Profile URL For Mastodon Verification

### ISSUE THREAD

**Issue by alpha1** [pixelfed/pixelfed#3844]
Potentially the smallest feature suggestion that will ever be added - please consider adding `rel="me"` to a user's profile website URL so that users can verify their pixelfed accounts on Mastodon.

**Comment by dansup** [comment]
We already support this, add your Mastodon url to the Website field in Pixelfed settings.

https://github.com/pixelfed/pixelfed/blob/4393780a4d3ff2ff30d26ec126fc2afc668fa420/resources/views/profile/show.blade.php#L11-L13

**Comment by alpha1** [comment]
That only seems to apply to the old UI, not the Metro2

**Comment by ghost** [comment]
Works here with Metro2 and Mastodon 4.0.2 on the other side - may take some time to flag the Pixelfed-instance as being "green" on Mastodon, but it definitely works.

**Comment by dallasgroot** [comment]
Is this in the admin settings under custom css?

**Comment by ghost** [comment]
> Is this in the admin settings under custom css?

No. Just enter your Mastodon-profile URL into the "Website"-field of your Pixelfed-profile and your Pixelfed-profile's URL in one of the four links-sections ok your Mastodon-profile. After a short while, the link should appear with a green color on Mastodon, being verified 😀 !

**Comment by artburnGM** [comment]
Despite seeing a few other profiles with verified links on their Mastodon profiles, this doesn't appear to work anymore. 
I get that it's in the profile/show.blade.php code, but can't seem to get it work for me.

Meanwhile, this pixelfed profile's page code has no 're="me" but it works...  
https://pixelfed.social/daw50n > https://tecnfy.com/@andy
