### ISSUE TITLE
Delete avatar cache for more space

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#3848]
Low on disk space? Want to reclaim it? 

```
/pixelfed/storage/app/public/cache
avatars/ 1.2G
```
Is there a way for admin to delete the avatars cache?
Even better a button inside the admin panel?

**Comment by escuco** [comment]
I have the same problem.

Is there a safe way to clean up the avatar cache?
My instance has more than 8 GB cache in /storage/app/public/cache/avatars.

**Comment by escuco** [comment]
Maybe @dansup can answer this question?

Is it safe, to delete the content in /storage/app/public/cache/avatars manually or does a commend exists, to purge the cached avatars content?

@okpierre

**Comment by escuco** [comment]
@okpierre With the newest commit you can purge the avatar cache:
`php artisan avatar:storage-deep-clean`

More information: https://github.com/pixelfed/pixelfed/pull/4694

Works nice, my avatar cache shrinked from 10 gb to 2,4 gb.

@dansup I think, this issue can also be closed.

**Comment by okpierre** [comment]
@escuco Good to know it is now available, thanks!

**Comment by lapineige** [comment]
This is not documented https://docs.pixelfed.org/technical-documentation/artisan/

Same for the base command
```
avatar:storage             Manage avatar storage
avatar:storage-deep-clean  Cleanup avatar storage
```

Also the help message does not explicitly say it will empty the avatar cache (it only says `storage`).

**Comment by lapineige** [comment]
In addition, in my case it didn't purge avatars cache.


The command description is :
`Purge/delete old and outdated avatars from remote accounts`

It checked 3906 avatars - which is huge for a single person instance, and obviously I don't need to store that much people avatar in cache.
No space gained.

The command doesn't seem to be about purging avatars cache, but rather removing old files ? :thinking:

**Comment by lapineige** [comment]
And if I remove the `storage/app/public/cache/avatars` cache folder, no avatar are shown any longer.
So I guess that mean Pixelfed doesn't work with avatar in any other way than copying them locally and then using that file.

**Comment by lapineige** [comment]
In addition, `avatar:storage` output seems to be vastly underestimating the space used by the avatar cache:

```
Pixelfed Avatar Storage Manager
 
+--------------+------------+------------+
| Segment      | Count      | Space Used |
+--------------+------------+------------+
| Local        | 1          | 0B         |
| Remote       | 4625       | 351M       |
| Cached (CDN) | 4398       | 351M       |
| Uncached     | 1288       | 0B         |
| ------------ | ---------- | -----      |
| Total        | 5686       | 351M       |
+--------------+------------+------------+
```

It's actually around 1.4GB in my case, according to the `storage/app/public/cache/avatars` folder.
