### ISSUE TITLE
Unable to upload JPG image as story - getting "invalid media type" error

### ISSUE THREAD

**Issue by zcraber** [pixelfed/pixelfed#3857]
I'm unable to upload [this ](https://user-images.githubusercontent.com/61133303/205126991-16532a62-f760-463b-85f0-7a8793572e50.jpg)JPG image as a story. Getting `Invalid media type` error.
![image](https://user-images.githubusercontent.com/61133303/205127568-e27f1229-3b56-44fd-94ad-67f53630d9d7.png)

[pixey.org](https://pixey.org/) server. Pixelfed v0.11.4.

**Comment by vanlueckn** [comment]
Can confirm it, i tried to upload your jpg on my instance and get the same error.

**Comment by vanlueckn** [comment]
Your Image is a webp image. MIME Type is `image/webp`.

I have webp images activated in my instance but the story upload does not accept webp images anyway.

**Comment by zcraber** [comment]
> Your Image is a webp image. MIME Type is `image/webp`.
> 
> I have webp images activated in my instance but the story upload does not accept webp images anyway.

Oh, ok. I'll close it then. WebP is not supported for stories, right? I could upload it as a post without issues. #2791

**Comment by vanlueckn** [comment]
I created a pull request with code changes allowing webp stories: #3888
