### ISSUE TITLE
comments getting dropped?

### ISSUE THREAD

**Issue by pwoolcoc** [pixelfed/pixelfed#387]
It looks like comments that I make on posts are not being shown? Here is me commenting on one of my own posts:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/620392/44212061-5a4c7200-a138-11e8-9d59-add7d23a3e8e.png">

After I reload the page, I see this:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/620392/44212105-7819d700-a138-11e8-8b20-213cfb0a87ad.png">

The same thing happens if I comment on another user's posts

Username is @balrogboogie (obviously, from the screenshots), and this is on pixelfed.social

EDIT: If I click into the post, I can see the comments, but on the timeline they don't show up after a page reload

**Comment by dansup** [comment]
@pwoolcoc Yes, this is the intended behaviour for now. It will soon show the latest 3 comments in the timelines.

**Comment by pwoolcoc** [comment]
thanks!
