### ISSUE TITLE
Spam detection too strict

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#3872]
Hey everyone,

I've got an effect with my own 0.11.4-instance which is quite odd and I don't know how to solve this issue:

At the moment, I have 24 photos (many single photos, some multiple posts) uploaded on this instance. Only the first three appear in my atom feed, can be configured in my Portfolio page or appear on the local timeline.

I can post more but each of the three stay with the first three posts I have made after creating the instance from the scratch.

What's this all about, can anyone help? Horizon and Queue Worker are running in the background as services within systemd and the instance looks good despite this effect.

Thanks in advance,

Oliver

**Comment by ghost** [comment]
Just found out that, albeit posting all pictures as public, they seem to be so (pictured with the globe).

After going back to my profile and looking at my timeline, the open lock on the same picture previously shown the globe now tells me that the post is "hidden from public feeds".

<img width="296" alt="Bildschirm­foto 2022-12-02 um 18 09 49" src="https://user-images.githubusercontent.com/42076599/205347343-3386b57d-3e9e-46a1-83e9-69ba32b83a1c.png">

This seems to be the reason for my problem but how may this be solved?
<img width="607" alt="Bildschirm­foto 2022-12-02 um 18 12 35" src="https://user-images.githubusercontent.com/42076599/205348239-01206008-9dc8-49ed-85bf-95a0cb71d8c2.png">
<img width="696" alt="Bildschirm­foto 2022-12-02 um 18 13 30" src="https://user-images.githubusercontent.com/42076599/205348247-f32cfe13-212c-4b7e-822f-77cceceeec41.png">
<img width="679" alt="Bildschirm­foto 2022-12-02 um 18 13 51" src="https://user-images.githubusercontent.com/42076599/205348250-296dd097-207a-4588-91d3-394538ce7e20.png">

If this is the expected "user error", how may I set all pictures on "public" again to solve the initial thread opener above?

Thanks for any clue!

Best regards,

Oliver

**Comment by ghost** [comment]
Same issue as [https://github.com/pixelfed/pixelfed/issues/3772](https://github.com/pixelfed/pixelfed/issues/3772) but it's apparently no Admin-thing as I AM the admin of this single-user instance ;-) !

**Comment by ghost** [comment]
Got it - it was the spam-detection. I flagged all remarked posts as "no spam" in the Admin-backend and they went public again, fixing my initial issue including the Atom-feed!

<img width="1167" alt="Bildschirm­foto 2022-12-02 um 18 21 17" src="https://user-images.githubusercontent.com/42076599/205349607-0673b51e-67c7-420c-b564-ab26a4605e03.png">

**Comment by HaraldWalker** [comment]
I see this as an UX issue. As user user you don't understand why this is happening, you think you did something wrong or that something is broken. User should get notified when this happens.

**Comment by trwnh** [comment]
If bad-faith actors were notified then there is a big chance they will just sign up for a new account, possibly somewhere else, instead of continuing wasting their time. On the other hand, if they were good-faith actors then they would be able to reach out to their admins and be informed of this, possibly amending their ways, or if it was a false positive then the problem can be resolved.

I think a better solution might be to make this clearer to admins when an account has been flagged as spam, so that admins aren't completely confused when a user asks about it. Either that or reworking/removing the automatic spam detection and relying on human intervention.

**Comment by ghost** [comment]
> I think a better solution might be to make this clearer to admins when an account has been flagged as spam, so that admins aren't completely confused when a user asks about it. Either that or reworking/removing the automatic spam detection and relying on human intervention.

That's the point - on bigger instances, this feature of spam defense is of elementary importance. If there would have been any notification in the Admin-account - fine. As this didn't happen and I stumbled upon those post in the Admin-backend ("Moderation") hovering as "Flagged Posts", I first didn't know what to do as they weren't classified by spam either - just being "Under review".

Maybe I triggered the spam detection as I manually migrated posts from my old instance to my new one manually, post by post and after the first three went well, the system discovered the rest as some kind of unusual activity. I could fix this for myself having my own instance but everyone being dependent from a (hopefully) active Admin of a bigger instance is in need for external help so, finally, at least any kind of notification when the detection is being triggered should be implemented.
