### ISSUE TITLE
Images are not being uploaded to S3

### ISSUE THREAD

**Issue by vanlueckn** [pixelfed/pixelfed#3883]
Hi,

i activated S3 Config in my .env file. The images still get uploaded to local files instead of s3. I cleared the cache.

My .env file:

```
FILESYSTEM_DRIVER=local
FILESYSTEM_CLOUD=s3
REMOVE_AVATARS=true
PF_ENABLE_CLOUD=true
AWS_ACCESS_KEY_ID=SECRET
AWS_SECRET_ACCESS_KEY=SECRET
AWS_DEFAULT_REGION=eu-west-1
AWS_BUCKET=pixelfed
AWS_URL=https://eu2.contabostorage.com
AWS_ENDPOINT=eu2.contabostorage.com
AWS_USE_PATH_STYLE_ENDPOINT=true
```

**Comment by okpierre** [comment]
visit the diagnostics page and report back the value for `PF_ENABLE_CLOUD`

**Comment by vanlueckn** [comment]
`PF_ENABLE_CLOUD` is enabled

**Comment by okpierre** [comment]
Ok if your .env matches diagnostics page, then it's something else

Thought you might have this issue: https://github.com/pixelfed/pixelfed/issues/3874

**Comment by vanlueckn** [comment]
I don't know why but i fixed it with `php artisan passport:install`
