### ISSUE TITLE
Sudden "Oops, something went wrong"-error when posting new pictures

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#3893]
Hey everyone,

after doing 136 posts on my own instance with 0.11.4 (latest commits) without any hassle, I am suddenly not able to post new pictures for whatever reason, the "Oops, something went wrong"-error occurs then.

<img width="646" alt="Bildschirm­foto 2022-12-04 um 12 26 45" src="https://user-images.githubusercontent.com/42076599/205488153-cf7b739a-9dc0-4c37-abcb-2fb5cbafa972.png">

The error appeared straight out of the nowhere and while I have checked and even rebooted the system, everything looks fine. When I look into the Admin under "Media", I do also see the pictures uploaded without a fitting status as the post couldn't be completed so, basically, it doesn't seem to be an upload issue.

<img width="1149" alt="Bildschirm­foto 2022-12-04 um 12 38 12" src="https://user-images.githubusercontent.com/42076599/205488276-3732b9a1-3a13-4f17-8b7d-eb5a32803f8e.png">

Does anybody has a clue as there is no error message available I could possibly decrypt as payload in the "Diagnostics"-section? It is not Browser-specific (tested with Safari and Brave) and while there's the error-message on the Desktop, the Pixelfed-app on iOS simply displays nothing but gives the ability of posting anything to... well, where? The post isn't prevented here but doesn't show in the timeline.

Thanks in advance!

Best regards,

Oliver

**Comment by ghost** [comment]
Diagnostics information:

=======================
 Pixelfed Instance Diagnostic v0.2 
=======================
Troubleshooting

Bootstrap: Writable ✅
Storage: Writable ✅
DATABASE Ping: Pong! Connected to DB "pixelfed" ✅
REDIS Ping: Pong! Connected to Redis ✅
ACTIVITYPUB instance actor created: ✅ true
ACTIVITYPUB instance actor cached: ❌ false
OAUTH enabled: ✅ true
OAUTH token_expiration 365 days
OAUTH public key exists: ✅ true
OAUTH private key exists: ✅ true
Important Information

Version: 0.11.4-1b211edc
Database: mysql (10.5.15-MariaDB-0+deb11u1)
APP_URL: https://mypixelfed.net
APP_DOMAIN: mypixelfed.net
ADMIN_DOMAIN: mypixelfed.net
SESSION_DOMAIN: mypixelfed.net
PHP Variables

PHP: 8.1.13
PHP INI memory_limit: 512M
PHP INI post_max_size: 256M
PHP INI upload_max_filesize: 10240M
PHP INI max_file_uploads: 200
PHP INI max_execution_time: 300
PHP INI max_input_time: 600
PHP INI file_uploads (On): 1
PHP INI - SECURITY allow_url_fopen (true): 1
PHP INI - SECURITY allow_url_include (false):
PHP INI - SECURITY expose_php (false):
PHP INI - SECURITY display_errors (false): Off
PHP INI - SECURITY display_startup_errors (false):
PHP INI - SECURITY log_errors (true): 1
PHP INI - SECURITY ignore_repeated_errors (false):
PHP INI - SECURITY disable_functions:
Pixelfed Variables (No Secrets)

CONFIG	VARIABLE NAME	DETAILS
APP	APP_NAME	"Pixelfed"
APP	APP_ENV	"production"
APP	APP_DEBUG	❌ false
APP	APP_URL	"https://mypixelfed.net"
APP	APP_LOCALE	"en"
APP	APP_FALLBACK_LOCALE	"en"
BROADCASTING	BROADCAST_DRIVER	"log"
CACHE	CACHE_DRIVER	"redis"
CAPTCHA	CAPTCHA_ENABLED	❌ false
DATABASE	DB_CONNECTION	"mysql"
DATABASE	REDIS_CLIENT	"phpredis"
EXP	EXP_LC	❌ false
EXP	EXP_TOP	❌ false
EXP	EXP_POLLS	❌ false
EXP	EXP_CPT	❌ false
EXP	EXP_GPS	❌ false
EXP	EXP_EMC	✅ true
FEDERATION	ACTIVITY_PUB	✅ true
FEDERATION	AP_OUTBOX	✅ true
FEDERATION	AP_INBOX	✅ true
FEDERATION	AP_SHAREDINBOX	✅ true
FEDERATION	AP_REMOTE_FOLLOW	✅ true
FEDERATION	ACTIVITYPUB_DELIVERY_TIMEOUT	"30"
FEDERATION	ACTIVITYPUB_DELIVERY_CONCURRENCY	"10"
FEDERATION	AP_LOGGER_ENABLED	❌ false
FEDERATION	ATOM_FEEDS	✅ true
FEDERATION	REMOTE_AVATARS	✅ true
FEDERATION	NODEINFO	✅ true
FEDERATION	WEBFINGER	✅ true
FEDERATION	PF_NETWORK_TIMELINE	✅ true
FEDERATION	PF_NETWORK_TIMELINE_DAYS_FALLOFF	2
FEDERATION	CUSTOM_EMOJI	✅ true
FEDERATION	CUSTOM_EMOJI_MAX_SIZE	"2000000"
FILESYSTEMS	FILESYSTEM_DRIVER	"local"
FILESYSTEMS	FILESYSTEM_CLOUD	"s3"
HASHING	BCRYPT_COST	"10"
HORIZON	HORIZON_PREFIX	"horizon-"
HORIZON	HORIZON_MEMORY_LIMIT	"64"
HORIZON	HORIZON_BALANCE_STRATEGY	"auto"
HORIZON	HORIZON_MIN_PROCESSES	"1"
HORIZON	HORIZON_MAX_PROCESSES	"20"
HORIZON	HORIZON_SUPERVISOR_MEMORY	"64"
HORIZON	HORIZON_SUPERVISOR_TRIES	"3"
HORIZON	HORIZON_SUPERVISOR_NICE	"0"
HORIZON	HORIZON_SUPERVISOR_TIMEOUT	"300"
HORIZON	HORIZON_DARKMODE	❌ false
IMAGE	IMAGE_DRIVER	"gd"
INSTANCE	INSTANCE_DESCRIPTION	"Pixelfed - Photo sharing for everyone"
INSTANCE	INSTANCE_CONTACT_FORM	❌ false
INSTANCE	INSTANCE_CONTACT_MAX_PER_DAY	"1"
INSTANCE	INSTANCE_DISCOVER_PUBLIC	✅ true
INSTANCE	EXP_LOOPS	❌ false
INSTANCE	INSTANCE_PUBLIC_HASHTAGS	✅ true
INSTANCE	INSTANCE_CONTACT_EMAIL	"contact@mypixelfed.net"
INSTANCE	INSTANCE_PUBLIC_LOCAL_TIMELINE	✅ true
INSTANCE	INSTANCE_NETWORK_TIMELINE_CACHED	
INSTANCE	INSTANCE_NETWORK_TIMELINE_CACHE_DROPOFF	100
INSTANCE	INSTANCE_NETWORK_TIMELINE_CACHE_MAX_HOUR_INGEST	6
INSTANCE	PAGE_404_HEADER	"Sorry, this page isn't available."
INSTANCE	PAGE_404_BODY	"The link you followed may be broken, or the page may have been removed. <a href="/">Go back to Pixelfed.</a>"
INSTANCE	PAGE_503_HEADER	"Service Unavailable"
INSTANCE	PAGE_503_BODY	"Our service is in maintenance mode, please try again later."
INSTANCE	BANNED_USERNAMES	""
INSTANCE	USERNAME_REMOTE_FORMAT	"@"
INSTANCE	USERNAME_REMOTE_CUSTOM_TEXT	""
INSTANCE	STORIES_ENABLED	✅ true
INSTANCE	RESTRICTED_INSTANCE	❌ false
INSTANCE	OAUTH_TOKEN_DAYS	"365"
INSTANCE	OAUTH_REFRESH_DAYS	"400"
INSTANCE	OAUTH_PAT_ENABLED	❌ false
INSTANCE	OAUTH_PAT_ID	""
INSTANCE	ENABLE_COVID_LABEL	✅ true
INSTANCE	COVID_LABEL_URL	"https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public"
INSTANCE	COVID_LABEL_ORG	"visit the WHO website"
INSTANCE	ENABLE_CONFIG_CACHE	✅ true
LDAP	LDAP_CONNECTION	"default"
LDAP	LDAP_LOGGING	✅ true
LDAP	LDAP_CACHE	❌ false
LOGGING	LOG_CHANNEL	"stack"
LOGGING	LOG_LEVEL (stack)	"debug"
MAIL	MAIL_DRIVER	"smtp"
MAIL	MAIL_HOST	"smtp.eu.mailgun.org"
MAIL	MAIL_PORT	"587"
MAIL	MAIL_FROM_ADDRESS	"pixelfed@mypixelfed.net"
MAIL	MAIL_FROM_NAME	"Pixelfed"
MAIL	MAIL_ENCRYPTION	"tls"
MEDIA	MEDIA_EXIF_DATABASE	❌ false
PIXELFED	ADMIN_DOMAIN	"mypixelfed.net"
PIXELFED	APP_DOMAIN	"mypixelfed.net"
PIXELFED	MEMORY_LIMIT	"1024M"
PIXELFED	OPEN_REGISTRATION	❌ false
PIXELFED	MAX_ACCOUNT_SIZE (KB)	"10000000"
PIXELFED	MAX_PHOTO_SIZE (KB)	"15000"
PIXELFED	MAX_AVATAR_SIZE (KB)	"4096"
PIXELFED	MAX_CAPTION_LENGTH	"1000"
PIXELFED	MAX_BIO_LENGTH	"250"
PIXELFED	MAX_NAME_LENGTH	"30"
PIXELFED	MIN_PASSWORD_LENGTH	"8"
PIXELFED	MAX_ALBUM_LENGTH	"20"
PIXELFED	ENFORCE_EMAIL_VERIFICATION	✅ true
PIXELFED	IMAGE_QUALITY (1-100)	"80"
PIXELFED	ACCOUNT_DELETION	✅ true
PIXELFED	ACCOUNT_DELETE_AFTER	❌ false
PIXELFED	PF_ENABLE_CLOUD	✅ true
PIXELFED	PF_MAX_USERS	50
PIXELFED	PF_OPTIMIZE_IMAGES	✅ true
PIXELFED	PF_OPTIMIZE_VIDEOS	✅ true
PIXELFED	PF_USER_INVITES	❌ false
PIXELFED	PF_USER_INVITES_TOTAL_LIMIT	"0"
PIXELFED	PF_USER_INVITES_DAILY_LIMIT	"0"
PIXELFED	PF_USER_INVITES_MONTHLY_LIMIT	"0"
PIXELFED	PF_MAX_COLLECTION_LENGTH	"100"
PIXELFED	MEDIA_TYPES	"image/jpeg,image/png,image/gif,video/mp4"
PIXELFED	LIMIT_ACCOUNT_SIZE	✅ true
PIXELFED	IMPORT_INSTAGRAM	❌ false
PIXELFED	IMPORT_INSTAGRAM_POST_LIMIT	"100"
PIXELFED	IMPORT_INSTAGRAM_SIZE_LIMIT	"5000"
PIXELFED	OAUTH_ENABLED	✅ true
PIXELFED	PF_BOUNCER_ENABLED	✅ true
PIXELFED	PF_MEDIA_FAST_PROCESS	✅ true
PIXELFED	PF_MEDIA_MAX_ALTTEXT_LENGTH	"1000"
PURIFY	RESTRICT_HTML_TYPES	BROKEN
QUEUE	QUEUE_DRIVER	"redis"
SESSION	SESSION_DRIVER	"database"
SESSION	SESSION_LIFETIME	"86400"
SESSION	SESSION_DOMAIN	"mypixelfed.net"
TRUSTEDPROXY	TRUST_PROXIES	"*"

========= END =========

**Comment by dansup** [comment]
> after doing 136 posts on my own instance with 0.11.4

Were these 136 posts created recently? We do have rate limiting, running `php artisan cache:clear` will clear the rate limiter

**Comment by ghost** [comment]
> > after doing 136 posts on my own instance with 0.11.4
> 
> Were these 136 posts created recently? We do have rate limiting, running `php artisan cache:clear` will clear the rate limiter

Yeah, it was kinda bulk-adding, one by one! Also tried `php artisan cache:clear` without any effect but after some hours of sleep (and patience!) I was able to finish the job. Thanks for the info, @dansup - closing this then. Maybe giving any kind of notification for user or admin would be a great addition in the future?

Greetings,

Oliver
