### ISSUE TITLE
Update the documentation: Mentioned PHP version no longer works.

### ISSUE THREAD

**Issue by murtezayesil** [pixelfed/pixelfed#3907]
Documentation mentions that PHP7.3 or above is needed [here](https://docs.pixelfed.org/running-pixelfed/prerequisites/#php-fpm). Composer fails to install because many packages require PHP 8.1.
I tested with 8.1 and 7.4. Only PHP 8.1 worked.

**Comment by HaraldWalker** [comment]
Documentation has its own repository and issues:
https://github.com/pixelfed/docs/issues
The last official 0.11.4 release supports 7.4 but the current `dev` branch does not any longer and installation guide uses the `dev` branch.

**Comment by murtezayesil** [comment]
Understood. I will check the changes there and maybe repeat this issue there accordingly.
