### ISSUE TITLE
[Feature] [UI] [Mobile] Android mobile icon

### ISSUE THREAD

**Issue by Nikoos** [pixelfed/pixelfed#393]
Hello,

An icon should be displayed when a bookmark is created on a Android desktop.

Actually there is no pixelfed icon displayed.

Regards,

Nikos

**Comment by Nikoos** [comment]
Hello @dansup 

I am actually away from my main computer. But back in some days, I will try to propose a modification through a pr (my first one).

Regards Nikoos (nikos on mastodon)

**Comment by dansup** [comment]
Duplicate of #233
