### ISSUE TITLE
Refactor profile="http://www.w3.org/ns/activitystreams" to be all https:// across all code

### ISSUE THREAD

**Issue by dannekrose** [pixelfed/pixelfed#3930]
The reference in profile="http://www.w3.org/ns/activitystreams"  throughout the code uses both http:// and https:// schemas.  I'm pretty sure this should all be https://  This is a request to refactor and change all references to http://www.w3.org/ns/activitystreams to use https (http -> https)

This does seem to break some federation with instances that are expecting https consistency.  Either way, being consistent and enforcing https:// everywhere is a good idea and will keep the code more consistent and predictable.

**Comment by dannekrose** [comment]
Seems to be 8 hits when searching on http://

https://github.com/pixelfed/pixelfed/search?q=http%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams

I don't think this would be too hard to do.

**Comment by trwnh** [comment]
should be fixed by #3932
