### ISSUE TITLE
Location of log file

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#3942]
Hey everyone,

does anyone of you know where Pixelfed logs, for example, failed login attempts?

I've found the "laravel.log" in the "storage/logs"-directory but there are no specific entries on wrong user-/password-combinations or anything similar, neither is shown in NGINX's access and error-log.

Is there a specific .env-parameter or a file that logs these attempts?

Thanks in advance,

Oliver

**Comment by svenluijten** [comment]
I've taken a quick look through the codebase and it looks like [it's using the default Laravel authentication](https://github.com/pixelfed/pixelfed/blob/dev/app/Http/Controllers/Auth/LoginController.php), which (unfortunately) does not write anything to the logs as you can see [here](https://github.com/laravel/ui/blob/4.x/auth-backend/AuthenticatesUsers.php#L46).

**Comment by ghost** [comment]
@svenluijten Thanks for the insight. I am currently looking for this log to extract failed login attempts to deal with via CrowdStrike. Sad that there isn't logged similar but your input is very welcome. Closing this then!
