### ISSUE TITLE
Posts are no longer using cloud storage - old posts are broken

### ISSUE THREAD

**Issue by foozmeat** [pixelfed/pixelfed#3943]
I have a small instance at https://pixelfed.pdx.social and older posts no longer display images. I have been set up with DO spaces and that was working until this problem occured. Here's an .env snippet

```
## S3
FILESYSTEM_DRIVER=local
FILESYSTEM_CLOUD=spaces
PF_ENABLE_CLOUD=true

# Digital Ocean
DO_SPACES_KEY=x
DO_SPACES_SECRET=x
DO_SPACES_ENDPOINT=https://sfo3.digitaloceanspaces.com
DO_SPACES_REGION=sfo3
DO_SPACES_BUCKET=pixelfed-pdx-social
```

New posts correctly display images but the media is landing in the storage folder local to the container and not cloud storage. Here's an example of a new post

https://pixelfed.pdx.social/i/web/post/509171075027341313

and an old post

https://pixelfed.pdx.social/i/web/post/497820014318493697

My understanding is that the media URLs should be pointing to my bucket but they're pointing to the server's `/storage` endpoint.

Editing to add that permissions on the bucket are world-read and owner-write. Here's one image

https://pixelfed-pdx-social.sfo3.digitaloceanspaces.com/public/m/_v2/497575513864949761/a48ad3dc0-89cf68/TGUMbx7tWYRk/nSU7uzMPXF9M4sW8To2HIrwEzMWxX65xbAB1xehW.jpg

**Comment by okpierre** [comment]
@foozmeat what is the value for PF_ENABLE_CLOUD when you visit diagnostics page?

**Comment by foozmeat** [comment]
That is set to `true`.

**Comment by foozmeat** [comment]
I think I have a problem with my install. It appears that my web and worker containers are no longer sharing storage. I'm going to correct that problem and then check back in.

**Comment by foozmeat** [comment]
My shared storage was indeed disconnected so now the old posts are fixed. New posts are not uploading to DO spaces but that's a separate issue.
