### ISSUE TITLE
Adding a collection to a new post does not add it to the collection

### ISSUE THREAD

**Issue by oct2pus** [pixelfed/pixelfed#3945]
this was done on pixelfed social

Process:

![image](https://user-images.githubusercontent.com/30452393/208063010-ec7d097a-11fd-4dcf-b2a9-1ab6aebb3757.png)
Create a new post

![image](https://user-images.githubusercontent.com/30452393/208063089-67dc968e-5639-4743-9add-ca08f2259b3a.png)
Select the collection you wish to add the post to

![image](https://user-images.githubusercontent.com/30452393/208063152-db3c2e82-6a63-4f33-87cc-642011495441.png)
save, see that it has a collection added

![image](https://user-images.githubusercontent.com/30452393/208063225-1784df62-65b7-4989-9e70-dd53efbc4ff7.png)
post

![image](https://user-images.githubusercontent.com/30452393/208063365-7b6f12c7-cd86-4c38-80df-d6b89feac7ff.png)
upon checking the collection, it does not appear to be added to the collection

**Comment by dansup** [comment]
Fixed in 9f8957b9
