### ISSUE TITLE
Enhancement: Automatically convert uploaded images to .webp

### ISSUE THREAD

**Issue by hnrd** [pixelfed/pixelfed#3948]
Got a feature request from a user of my instance:

It'd be neat if the server would offer to automatically convert uploaded images to webp before posting.

IMHO, this should be configurable by the instance admins (if the instance even offers the feature) and by the instance user (if they want their images converted)

This would solve the problem of not being able to post webp from most mobiles.

**Comment by scottalanmiller** [comment]
This is a fantastic idea and exactly what I want to see on ours. This would make running the server so much more efficient and lower hosting costs so much.
