### ISSUE TITLE
[Bug] 403 on loading private account, even when following that user

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#396]
`trwnh` follows `abdullah`
`abdullah` is set to private
`trwnh` attempts to load `pixelfed.social/abdullah`

expected result: profile loads, because i am logged in
actual result: 403 - forbidden

**Comment by nailyk-fr** [comment]
Thanks for opening the issue :wink: 
 * Another point, you cannot send follow request to locked account. 
 * Like you said, following people who locked the account result in 403 while attempting to load the profile page. *However* you can access a post if you know the direct link: https://pix.hostux.social/p/spurcamen/1436 , even if not logged in and/or not following. 
 * Request sent from mastodon result in 'pending for approval' icon on mastodon side, the follow request never arrived on the pixelfed account. 

Feels free to contact me for more informations/testing. 

Many thanks for the project :heart: 

P.S.: Am not able to find what is the running version on the tested instance.

**Comment by trwnh** [comment]
@nailyk-fr The "pending" from Mastodon is probably because ActivityPub support isn't 100% complete yet. Most of the outbox is done, but inbox is not.

**Comment by nailyk-fr** [comment]
I guess it is fixed now.
