### ISSUE TITLE
Meta: move to GitHub Actions

### ISSUE THREAD

**Issue by svenluijten** [pixelfed/pixelfed#3983]
Might I suggest moving running the (unit) tests to GitHub Actions? This has several benefits as I see it:

- It's free for open source projects (just like CircleCI).
- It makes contributing to the project easier by having everything in one place.
- The status of the CI job is automatically "linked" to the PR/commit that triggered the job, and can be viewed inline.
- It's more "in your face" when contributing, which lowers the amount of low-quality contributions.

If okay'd, I'd be more than happy to help set this up (and subsequently work on #1466), but the Actions feature needs to be enabled for this repository which only the owner can do I believe.

1. Go to [this repository's settings](https://github.com/pixelfed/pixelfed/settings).
2. Click "Actions" -> "General" in the left sidebar.
3. Check "Allow all actions and reusable workflows" at the top of the screen.
4. Hit save.

I realise it's probably been disabled for a reason, but I could not find a discussion about it anywhere in this organization's repositories. If it was indeed a conscious decision, would you mind explaining to me why CircleCI was chosen over GitHub Actions?

**Comment by Murazaki** [comment]
I actually pushed for github actions to build docker images, but here we are a year after, and it is still not used by the project. I'm building my own images on my fork here, I had to add another pull and build mechanic, to make it work locally :
https://github.com/Murazaki/pixelfed
https://hub.docker.com/r/murazaki/pixelfed/tags
