### ISSUE TITLE
No possibility to write Direct Message

### ISSUE THREAD

**Issue by bovergaauw** [pixelfed/pixelfed#3990]
I'm on pixelfed.social, and am unable to send any direct message: I have no way to enter any text. I use Firefox for Android on a Samsung Galaxy S9.

**Comment by mitexleo** [comment]
Could you please share a screenshot with us ?

**Comment by bovergaauw** [comment]
![image10](https://user-images.githubusercontent.com/16757851/209297182-ddeba40d-9274-4305-9ab2-4cbcaceab9a7.png)

**Comment by mitexleo** [comment]
Kindly scroll down a bit  😀

**Comment by mitexleo** [comment]
![Screenshot_20221224-120320_Vivaldi Browser](https://user-images.githubusercontent.com/114842102/209423702-4eeaec52-a5d8-4aa0-81a0-eb0e4bc60946.jpg)

**Comment by bovergaauw** [comment]
Oops, sorry...
