### ISSUE TITLE
Security Features

### ISSUE THREAD

**Issue by dansup** [pixelfed/pixelfed#4]
- [x] ~bcrypt password hashing~
- [x] OAuth / Authorized Applications
- [x] ~Option to verify email before account can do anything~
- [x] Option to require TLS by default (including remote apis)
- [x] ~Two Factor Auth~
- [x] ~Account Audit Log~
- [x] ~Show Active Sessions in Security Settings~
- [x] Usernames are retired after user deletes account
- [x] ~Close new registrations~
- [x] Restrict new registrations to invite-only
- [x] Restrict new registrations to domain specific email addresses

**Comment by nailyk-fr** [comment]
Also looks like I am not able to delete my account.

**Comment by dansup** [comment]
@nailyk-fr It is a WIP!

**Comment by andyrtr** [comment]
Please also support WebAuthn/U2F login using hardware security tokens. While it works great with GitHub and GitLab the Fediverse is lacking that support. See also https://github.com/tootsuite/mastodon/issues/562
