### ISSUE TITLE
Add licence information in scripts provided to the user

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#4013]
Pixelfed is licenced under AGPL. And can be proud of it!
Scripts should contain information about their licence and availability of source code.

Can by done by adding comments like below (also works in external files):

```
<script>
// @license magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109&dn=agpl-3.0.txt AGPL-3.0
//  Source code: https://github.com/pixelfed/pixelfed
    [script is here]
// @license-end
</script>
```

This can also be done to the promotion page on https://pixelfed.org .
More information and more ways to specify JavaScript licences can be found here: https://www.gnu.org/software/librejs/free-your-javascript.html

**Comment by willtop43** [comment]
Thank you for filing this issue. I noticed in pixelfed-0.11.9/public/js that some scripts have a reference to source and license, but others do not. Maybe they are working on it?

**Comment by LorenzoAncora** [comment]
I too had trouble checking the licensing (and source code freeness) of this project. LibreJS is excessive, but adding the [SPDX license identifier](https://spdx.org/licenses/) on top of each minified script is a good practice.

Example:

```
[start of the file]
// SPDX-License-Identifier: MIT
[rest of the code]
```
