### ISSUE TITLE
Improved User Suggestions

### ISSUE THREAD

**Issue by kaffeeringe** [pixelfed/pixelfed#402]
When I call https://pixelfed.social/discover Pixelfed suggests three user accounts. IMHO it would be more interesting if suggestions didn't just show random profiles but at least profiles with a profile picture and one post.

It's okay, that it's not a selection of the most popular accounts - that's what takes Pixelfed apart from Instagram, where you only get more popular because you are popular. But there are a lot test accounts on pixelfed.social it seems.

**Comment by trwnh** [comment]
The discover page no longer suggests user accounts; it now suggests posts instead.

**Comment by AnonymousWebHacker** [comment]
@trwnh  I was looking at this photo, currently pixelfed, 
https://pixelfed.nyc3.cdn.digitaloceanspaces.com/media/Screen%20Shot%202019-02-05%20at%206.34.59%20PM.png 
don't you have that user suggestion menu?
