### ISSUE TITLE
FatalError : continue' not in the 'loop' or 'switch' context

### ISSUE THREAD

**Issue by dadall** [pixelfed/pixelfed#4023]
Hi,

Here is an error raised since the lasts commits : 

`[2022-12-27 13:46:57] production.ERROR: 'continue' not in the 'loop' or 'switch' context {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): 'continue' not in the 'loop' or 'switch' context at /home/pixelfed/app/Jobs/StatusPipeline/StatusTagsPipeline.php:69)`

Seems to happen when a PF user share a post. 

Pixelfed version : commit 989f7f8386cc060bf5d77b41f4b7b32f05722d99
OS : debian 11
PHP : 8.1

Regards,

**Comment by dansup** [comment]
Fixed in #4024
