### ISSUE TITLE
Permissions, in general, seems to be somewhat confusing

### ISSUE THREAD

**Issue by joho1968** [pixelfed/pixelfed#4027]
Having read through most of the treads here and elsewhere about troubles with permissions, in particular relating to picture uploads, avatars, previews, and so on, I'm somewhat confused as to what's going on.

My setup is Ubuntu 22.04.LTS, where the dist version of nginx, by default, runs as www-data/www-data. I furthermore use the dist version of PHP 8.1 (FPM), it is setup to run as "pixelfed/pixelfed". All umasks, in all places it can be changed, is set to 0007 or 007, in other words, I want the files and directories to be owner:rw, group:rw, world:nothing.

I have written a simple php script and execute it as the pixelfed user, which the same that happens when PHP-FPM is invoked by nginx. The files and directories created (using fopen) have the correct 0660/660 and 0770/770 permissions. So something is actively changing the masks and not using the defaults as implied by process permissions.

I have included nginx (www-data user) in the pixelfed group.

Looking at what's created when I begin adding a new post, I see a newly created directory, with the permissions 0700/700, owned by the pixelfed user and the pixelfed group. The owner/group is fine, the permissions are not. 

I have tried adding specific permissions to config/filesystems.php, but that seems to have no effect. Unless there's pixelfed code that changes this, I'd guess it has something to do with Laravel 9, but I don't know enough about L9. "Web Site Isolation" active, maybe?

This can, of course, be rather easily fixed by changing everything to use one setup of user/group, in all places, but I believe that's a rather bad idea for a number of reasons (security, multi-site hosting, and so on). There are already ways to set default umasks, group membership of processes like php and nginx, so why add an extra layer for everything?

It could be that I got all of this wrong, of course, and maybe the problem is hidden in plain sight.

**Comment by joho1968** [comment]
OK, so after digging some more into Laravel 9, I can tweak how files and directories are created by modifying config/filesystems.php. I did this, just to make sure I could spot the change:

    'disks' => [  
        'local' => [ 
            'driver' => 'local',  
            'root'   => storage_path('app'), 
            'permissions' => [ 
              'file' => [ 
                'public' => 0111, 
                'private' => 0222, 
              ], 
               'dir' => [ 
                 'public' => 0333, 
                 'private' => 0444, 
              ], 
            ], 
        ], 
    ], 

(note that I did not do this under 'public', I tried that first, but it had no effect)

So now, the directory that was created had 0440, which of course is wrong, but it's a step in the right direction :blush: 

Changing it to this:

    'disks' => [  
        'local' => [ 
            'driver' => 'local',  
            'root'   => storage_path('app'), 
            'permissions' => [ 
              'file' => [ 
                'public' => 0664, 
                'private' => 0660, 
              ], 
               'dir' => [ 
                 'public' => 0775, 
                 'private' => 0770, 
              ], 
            ], 
        ], 
    ], 

works.

(You'll need to run `php artisan config:cache` for this to take effect.)

I don't know what the solution is, but something has obviously changed.

**Comment by HaraldWalker** [comment]
there is already a pull request for this since end of November
https://github.com/pixelfed/pixelfed/pull/3825

**Comment by joho1968** [comment]
> there is already a pull request for this since end of November #3825

Great! Then let's hope for a speedy resolution.

**Comment by MrRoyce** [comment]
This issue was supposed to be fixed with https://github.com/pixelfed/pixelfed/commit/22da2647c7f28f7e1d6a588f4549c3326aee9356 but its still not working for me with the latest release.  I had to manually `config/filesystems.php` as shown above to get the permissions correctly set.

Maybe there is some combination of parameters for nginx, php, php-fpm, ubuntu groups/users, composer, artisan, etc that the fix works for, but I'm stumped.

**Comment by jenselofsson** [comment]
I'm seeing the same issue as @MrRoyce

**Comment by nabbi** [comment]
I too am seeing a permission problem when nginx and php-fpm are ran as separate users.
php-fpm uploads files in directories which nginx does not have access to read.

The discussion in #3825  hints at additional changes were needed but not incorporated into 22da2647c7f28f7e1d6a588f4549c3326aee9356 ?

Adding the global read+execute flag on the parent paths corrected this for me as well.
Running php-fmp and nginx as the same user is another workaround, but as mentioned elsewhere, that is not always desirable.


```
$ git diff config/filesystems.php 
diff --git a/config/filesystems.php b/config/filesystems.php
index 80e63ed9..e3b5c6e1 100644
--- a/config/filesystems.php
+++ b/config/filesystems.php
@@ -53,7 +53,7 @@ return [
                 ],
                 'dir' => [
                     'public' => 0755,
-                    'private' => 0700,
+                    'private' => 0755,
                 ],
             ],
         ],
```
