### ISSUE TITLE
Strange avatar paths when using S3 storage

### ISSUE THREAD

**Issue by joho1968** [pixelfed/pixelfed#4031]
Site URL: https://pixels.domain.com
Site Media URL: https://pixelmedia.domain.com (reverse proxy caching nginx)

My S3 configuration for PF:

```
## S3 Configuration (Post-Installer)
PF_ENABLE_CLOUD=true 
#FILESYSTEM_DRIVER=local 
FILESYSTEM_DRIVER=s3 
FILESYSTEM_CLOUD=s3 
AWS_ACCESS_KEY_ID=[redacted]
AWS_SECRET_ACCESS_KEY=[redacted]
AWS_DEFAULT_REGION="eu-central-1"
AWS_BUCKET=pixels
AWS_URL=https://pixelmedia.domain.com
AWS_ENDPOINT=[redacted]
AWS_USE_PATH_STYLE_ENDPOINT=false 
```

When uploading an avatar, the preview image is "broken", and the URL points to:

https://pixels.domain.comhttps//pixelmedia.domain.com/public/avatars/051/366/502/472/685/158/5/EgkJLLmjzlRaoYQawWRy_avatar.jpg?v=1

The file has been correctly uploaded to S3 storage, in the right path, but as you can see, there's something mangling the filename. It should not contain the initial "https://pixels.domain.com".

Regular posts work fine, including posts with images, etc.

**Comment by mitexleo** [comment]
Set filesystem driver to local

**Comment by mitexleo** [comment]
If you're using Aws s3 .. then comment out AWS_URL

**Comment by joho1968** [comment]
Not sure I follow. I *want* to use S3; the AWS_URL is only used to fetch media (for S3), no? The AWS_ENDPOINT is used for writing media to S3, no? At least that seems to be the current behavior, since it *is* working for posts (everything works there).

The above AWS_URL is just to force PF to replace the URL when fetching media, it points to a reverse proxy nginx that in turn is setup to cache fetch requests from S3 storage.

Why is the URL, as mentioned above, malformed?

**Comment by joho1968** [comment]
PF seems to take the APP_URL and simply concatenate AWS_URL to it, after cleaning out ":". I'm not sure why this is specific to the avatar handling. The above mentioned configuration works beautifully for posts and comments (including comments containing media). Is there some specific handling for avatar uploads going on?

**Comment by joho1968** [comment]
So, in app/Profile.php, in function avatarUrl(), the second to last return statement seems to be making assumptions that may not necessarily be true. Adding some "debug output" to the log, it's quite obvious that `return config('app.url') . Storage::url($path);` is where the concatenation problem occurs. Not sure what a reasonable comparison should be here though, but wouldn't using simply `Storage::url($path);` be more correct, which would then follow the storage configuration, whatever that might be?

```
    public function avatarUrl()
    {
        $url = Cache::remember('avatar:'.$this->id, 1209600, function () {
            $avatar = $this->avatar;

            if($avatar->cdn_url) {
                if(substr($avatar->cdn_url, 0, 8) === 'https://') {
                    return $avatar->cdn_url;
                } else {
                    return url('/storage/avatars/default.jpg');
                }
            }

            $path = $avatar->media_path;

            if(substr($path, 0, 6) !== 'public') {
                return url('/storage/avatars/default.jpg');
            }

            $path = "{$path}?v={$avatar->change_count}";

            return config('app.url') . Storage::url($path);
        });

        return $url;
    }
```

**Comment by okpierre** [comment]
Similar to https://github.com/pixelfed/pixelfed/issues/3559

Also there is a patch awaiting review
https://github.com/pixelfed/pixelfed/pull/3846

edit: keep in mind that dansup said this is a configuration issue so patch may not be needed

![dansupprofilebroken](https://user-images.githubusercontent.com/1679025/210057544-a06d6202-092c-4a07-a3e9-35eb33372505.jpg)
