### ISSUE TITLE
Awaiting Submission (Your directory listing isn't completed yet)

### ISSUE THREAD

**Issue by joho1968** [pixelfed/pixelfed#4039]
The only thing standing out is "Missing favourite posts".

But adding "favourite posts" doesn't seem possible.

Clicking on "Favourite Posts" in the Admin UI gives me three options; none of which seem to do anything.

"Add by post id" doesn't find any posts (there are two public posts), "Add by popularity" shows only my admin account ..

So how is this supposed to be used?

**Comment by trankten** [comment]
Hello @joho1968... any luck?

I'm having the same issue at pixelfed.es and I'm not able to find a way to reach Pixelfed team. :(

In my case everything is completed but yet, unable to submit.

![imagen](https://user-images.githubusercontent.com/86560527/210099369-ae50d84a-b77d-4885-aeff-c7ba8d244a8b.png)

**Comment by joho1968** [comment]
No luck I'm afraid. And I haven't even been able to get the "Configured favourite posts" to "green". Not sure what I need to do.

**Comment by mitexleo** [comment]
> Hello @joho1968... any luck?
> 
> I'm having the same issue at pixelfed.es and I'm not able to find a way to reach Pixelfed team. :(
> 
> In my case everything is completed but yet, unable to submit.
> 
> ![imagen](https://user-images.githubusercontent.com/86560527/210099369-ae50d84a-b77d-4885-aeff-c7ba8d244a8b.png)

You don't have to do anything... Pixelfed Devs will approve your site ... @dansup is busy with the Mobile App.

**Comment by joho1968** [comment]
> Hello @joho1968... any luck?
> I'm having the same issue at pixelfed.es and I'm not able to find a way to reach Pixelfed team. :(

I removed my instance a few days ago; I must have missed the fact that Pixelfed Devs had to approve the site. Oh well, at some time in the future, I'll have a look at the project again.
