### ISSUE TITLE
[Feature] [UX] Keyboard navigation

### ISSUE THREAD

**Issue by joachimesque** [pixelfed/pixelfed#405]
I'd like to be able to navigate with `j` and `k` in timelines. `j` for next post, and `k` for prev. Ideally, `l` would be used to like the active picture, `o` to open it, `r` and `s` to reply and save it.

To see such a feature in action, check out the Mastodon UI or Reddit (old and new versions).

**Comment by trwnh** [comment]
duplicate of #304

**Comment by joachimesque** [comment]
ooh thanks, I hadn't seen that issue (I looked for "keyboard" and it didn't show up)
