### ISSUE TITLE
Can't follow pixelfed.social profile on mastodon.cloud

### ISSUE THREAD

**Issue by nafergo** [pixelfed/pixelfed#4055]
Can't follow my pixelfed.social profile on mastodon.cloud
I can find the pixelfed.social profile and click on Follow,  mastodon page shows Follow Requested but there's no notification on pixelfed.social
any ideas? Thx

**Comment by mitexleo** [comment]
It's a known issue .. I dunno if anyone is working to fix it .. 
It might be a issue on the Mastodon Server ... Wait few hours
