### ISSUE TITLE
Hastags with accented chars are not distinct from the same tag with non accented chars

### ISSUE THREAD

**Issue by dgmid** [pixelfed/pixelfed#406]
for example:

#Ísland (Iceland in icelandic)
https://pixelfed.social/discover/tags/ísland?src=hash

gives the same result as

#island (island in English)
https://pixelfed.social/discover/tags/island?src=hash

**Comment by nailyk-fr** [comment]
This looks like a feature to me :thinking: 
(BTW this redirects me to a login page)

**Comment by dgmid** [comment]
In many languages the addition of an accent can completely change the word / meaning. In the example I gave, Ísland is the name of a country whereas island is just and island.
The links redirect to a login page most likely because you aren't logged in to pixelfed.
