### ISSUE TITLE
Portfolio not working any more.

### ISSUE THREAD

**Issue by uk3** [pixelfed/pixelfed#4060]
Hi,

Portfolio somehow stopped working or to be more precise: it froze in the state of about 2 weeks ago.

New posts after that do not show up in the portfolio. Even if the portfolio is manually curated and the posts are correctly marked to be shown, the new ones are not shown in the portfolio.

Older Posts are correctly shown either way. So I assume that something with the postings changed that they are not found by the portfolio any more.

Greetings, Ulrich

**Comment by uk3** [comment]
Ok, what I did not realise: Posts are only added to the portfolio, if they contain a single photo. If a Post contains more than one photo it is not added to the portfolio, no matter what I do.

Greetings, Ulrich.

**Comment by marc-neumann** [comment]
+1 please also allow multi image posts
