### ISSUE TITLE
[bug] Tags are not parsed correctly

### ISSUE THREAD

**Issue by nailyk-fr** [pixelfed/pixelfed#407]
Right after uploading pictures, the post is displayed. Tags are shown as not parsed. Refreshing the page make tags parsed. 
after posting: 
![capture d ecran_2018-08-25_17-20-26](https://user-images.githubusercontent.com/16372405/44619870-e7f03600-a88b-11e8-945d-80990729916a.png)
after reloading the page: 
![capture d ecran_2018-08-25_17-20-36](https://user-images.githubusercontent.com/16372405/44619871-e7f03600-a88b-11e8-8f69-fc0091370ea1.png)

Tag parsing looks really random. Cannot get steps to reproduce, sorry. 
![capture d ecran_2018-08-25_17-19-49](https://user-images.githubusercontent.com/16372405/44619869-e7f03600-a88b-11e8-9b63-d9ea8a114337.png)

![capture d ecran_2018-08-25_17-25-34](https://user-images.githubusercontent.com/16372405/44619872-e7f03600-a88b-11e8-9cef-7d4fc3df033f.png)

(the best result I had to get tags parsed, seems to be: add the tag *after* writing the text, without space in front of it, only one tag)

Feels free to ask for any information/tests.

**Comment by dansup** [comment]
@nailyk-fr Which commit of pixelfed are you running?

**Comment by nailyk-fr** [comment]
@dansup am really sorry because am not able to find it... Where can I check? (am not the instance admin and he his not answering me)
