### ISSUE TITLE
Formatting descriptions

### ISSUE THREAD

**Issue by stemy2** [pixelfed/pixelfed#4078]
Hello,

I'm pretty annoyed by the unability to format image descriptions. I wanted to make a description on multiple lines, but they are published on only one line. I think a formatting with html or markdown could help solving this.

**Comment by jim-easterbrook** [comment]
Have you tried including `\n` characters in your text? I've found this works when posting media to pixelfed using the Mastodon.py package.

**Comment by trwnh** [comment]
Duplicate of #3821
