### ISSUE TITLE
Atom feed unavailable on Profile (error message "Sorry, this page isn't available.")

### ISSUE THREAD

**Issue by x572b** [pixelfed/pixelfed#4079]
Click profile

Click three dots next to profile name

Select "Atom Feed"

Receive error message "Sorry, this page isn't available."

**Comment by okpierre** [comment]
@x572b which version are you seeing this?

I'm getting a popup to download file pixelfed.atom

**Comment by x572b** [comment]
I am seeing the error on: pixelfed.social - v0.11.4

It is working correctly on pxlmo.com - I can't find the version they are running on their site, but https://the-federation.info/platform/26 reports the version is also v0.11.4

**Comment by dansup** [comment]
@x572b Can you confirm if this is still happening on pixelfed.social?

**Comment by x572b** [comment]
I am still getting an error page instead of an atom feed on pixelfed.social.

**Comment by x572b** [comment]
Now it is broken on http://pxlmo.com/ also.

**Comment by x572b** [comment]
This seems like it is fixed in 11.6 - hurray! Not sure what changed but working now on pixelfed.social. 

Anyone else want to confirm?

**Comment by mitexleo** [comment]
It has been fixed. Working fine for me 😊

**Comment by edm00se** [comment]
I started seeing this issue on pixelfed.social starting in the last 24 hours.

**Comment by x572b** [comment]
> I started seeing this issue on pixelfed.social starting in the last 24 hours.

Hi - does this mean you started experiencing the problem as well, even on 11.6?

My php code that reads the RSS feed isn’t working any longer - something in the Pixelfed code must have changed. 

But, I am at least being presented with the atom file on 11.6 when I click the link in my profile.

**Comment by edm00se** [comment]
@x572b correct, but this appears to have resolved itself now; maybe a configuration/routing issue 🤔. I was using the link from the profile, server’s on 0.11.6.

**Comment by x572b** [comment]
Seems to be working as expected now so I will close this issue.
