### ISSUE TITLE
Site does not work in Pale Moon or Seamonkey

### ISSUE THREAD

**Issue by Rising-Soul** [pixelfed/pixelfed#4080]
This seems to be because Pixelfed depends upon WebComponents support in the browser. This is problematic for the reasons outlined here, especially for a project that prides itself on being decentralized: https://forum.palemoon.org/viewtopic.php?f=1&t=24004

Please consider supporting more browser choice. Thanks. :)

**Comment by mitexleo** [comment]
+1
