### ISSUE TITLE
Restricted Mode code is commented 

### ISSUE THREAD

**Issue by gdelfresno** [pixelfed/pixelfed#4083]
Hello, 

I was testing the project and wanted to use the Restricted Mode as documented. As it wasn't working I looked at the code and noticed that the code is commented here https://github.com/pixelfed/pixelfed/blob/15fa79fa7e6e7f2b2670c343b66474ec2d2ea74e/app/Http/Kernel.php#L71

I wanted to know if there is a reason for this to be disabled, since I have uncommented the code and everything seems to work fine. 

I have an instance for a small group of people, so I could help debugging/fixing any problems with the restrict mode if you need help with it.

Thanks for the project!

**Comment by carlyman** [comment]
Did you uncomment line 40 as well? 

https://github.com/pixelfed/pixelfed/blob/15fa79fa7e6e7f2b2670c343b66474ec2d2ea74e/app/Http/Kernel.php#L40

**Comment by gdelfresno** [comment]
Yes, I had to uncomment that one too.
