### ISSUE TITLE
delete image dosnt work in new upadte.

### ISSUE THREAD

**Issue by ehsan0921** [pixelfed/pixelfed#4119]
I jsut updated my Pixelfed and noticed that post can not be delete.

why is that??? is it a bug?
@dansup

**Comment by ehsan0921** [comment]
no worries. 
it was my S3 issue.

**Comment by ChronosXYZ** [comment]
I use `FILESYSTEM_DRIVER=local`, but cannot delete my post as well. Request `POST /i/delete` returns 200 OK, but post appears after reloading page. Latest `zknt/pixelfed` image. No permission issues appears in logs.

**Comment by wwjimenez** [comment]
> 

Did you manage to resolve this issue? I'm experiencing the same problem - it doesn't return any errors. It returns a 200 status code and disappears from the page, but reappears upon refreshing.
