### ISSUE TITLE
@username incorrect to federated user

### ISSUE THREAD

**Issue by eitch** [pixelfed/pixelfed#4130]
If you look at this image, then you will see that a user posted an image with a text, mentioning other people. The links are incorrect.

![image](https://user-images.githubusercontent.com/245382/215584772-355c99ea-d8af-426f-b337-f1bc8f614bd5.png)

![image](https://user-images.githubusercontent.com/245382/215585044-73ce56bf-b842-4e09-b5f6-8030f7a10e2b.png)

![image](https://user-images.githubusercontent.com/245382/215585074-f447bc64-a63b-4424-985e-afc07084862a.png)

and if i then click those links, i get a 404:
![image](https://user-images.githubusercontent.com/245382/215585160-ddbe7e20-b362-407a-b426-b1cd5983c470.png)

**Comment by trwnh** [comment]
it seems the proper route currently is `/i/web/profile/` instead of `/i/web/username/`

**Comment by dansup** [comment]
Fixed in #4133

**Comment by eitch** [comment]
@dansup awesome, thanks for the quick fix!

**Comment by eitch** [comment]
I can confirm, that this is now fixed on the dev branch, just deployed it. Thanks a lot @dansup
