### ISSUE TITLE
Add more redis connection parameters in configuration file

### ISSUE THREAD

**Issue by blankoworld** [pixelfed/pixelfed#414]
It would be nice to use a socket instead of tcp use of Redis.

As explained here: https://github.com/nrk/predis/wiki/Connection-Parameters#list-of-connection-parameters

"scheme" and "path" should be enough to activate redis socket use.

It may give a performance increase, compared to TCP/IP.

**Comment by dansup** [comment]
@blankoworld You should use [phpredis](https://github.com/phpredis/phpredis/) instead of predis for better performance.

**Comment by blankoworld** [comment]
@dansup: Ok, but as I'm only a user, how can I change this in PixelFed? Does it mean that I have to change something in php.ini and then configure something in PixelFed?
