### ISSUE TITLE
Unable to use DigitalOcean Spaces

### ISSUE THREAD

**Issue by kristophrk** [pixelfed/pixelfed#4148]
In trying to set this up - I've been using various guides I've found online to navigate through this.

However, I see that PixelFed supports the use of Digital Ocean Spaces.  I've tried setting it up in various ways and cannot get it to work for the life of me.  I was hoping to get to the point where I could document it and share it online for others to use but after trying various ways - I just can't get it to work.

So - does DO Spaces work with Pixelfed?  Is there an official way to set it up?

It also seems weird that no matter what I put in the .env file (and updating the cache) that the settings aren't being reflected in the actual configurations.  Is that intentional?

**Comment by okpierre** [comment]
If you haven't done so already, have a look at these posts https://github.com/pixelfed/pixelfed/issues/2866 https://github.com/pixelfed/support/issues/199
