### ISSUE TITLE
php: Could not open input file for artisan file

### ISSUE THREAD

**Issue by stevenroose** [pixelfed/pixelfed#4169]
Following the installation manual, I get the following error while running the systemd service that is provided in the installation manual.

```
Feb 11 04:48:01 pix systemd[1]: Started Pixelfed task queueing via Laravel Horizon.
Feb 11 04:48:01 pix php8.1[30039]: Could not open input file: /root/pixelfed/artisan
Feb 11 04:48:01 pix systemd[1]: pixelfed.service: Main process exited, code=exited, status=1/FAILURE
Feb 11 04:48:01 pix systemd[1]: pixelfed.service: Failed with result 'exit-code'.
```

I have gone over the manual another two times to make sure I didn't forget any permissioning detail. I have a user `pixelfed` that is in the group `redis` and `www-data`. The `/root/pixelfed` directory is owned by the `pixelfed` user and has the permissions as instructed in the manual. The file mentioned in the error has the following status:

```
-rw-r--r--  1 pixelfed pixelfed   1686 Feb 10 15:43 artisan
```

I have created a php-fpm pool named `pixelfed` as follows:
```
[pixelfed]
user = pixelfed
group = pixelfed
listen = /run/php/pixelfed.sock
listen.owner = pixelfed
listen.group = www-data
listen.mode = 0660
```
(I initially had `listen.owner` set to `www-data` but that didn't work either.)

Meanwhile, when trying to access the website, I get a 404 and the following error in nginx:
```
2023/02/11 04:43:40 [crit] 3786#3786: *114 stat() "/root/pixelfed/public/index.php" failed (13: Permission denied), client: REDACTED, server: MYDOMAIN, request: "GET /index.php HTTP/2.0", host: "MYDOMAIN"
```

**Comment by orangemelo11** [comment]
change listen.group to pixelfed and restart fpm

**Comment by stevenroose** [comment]
> change listen.group to pixelfed and restart fpm

In the example the listen.* vars are kept at http or www-data, but I tried what you said and without success.

**Comment by stevenroose** [comment]
Is it normal and expected that the `artisan` file doesn't have `+x` permission? While it seems like it is being executed by the pixelfed service:
```
ExecStart=/usr/bin/php8.1 /root/pixelfed/artisan horizon
```

**Comment by stevenroose** [comment]
Also maybe, I ran `composer install` as root. When I try to rerun `sudo -u pixelfed composer install` I get permission denied. Maybe I need to reboot to flush permissions or so, let me try that.

**Comment by stevenroose** [comment]
No avail.

The phpfpm pool is working:
```
             ├─837 "php-fpm: master process (/etc/php/8.1/fpm/php-fpm.conf)" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─966 "php-fpm: pool pixelfed" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─967 "php-fpm: pool pixelfed" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─968 "php-fpm: pool www" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             └─969 "php-fpm: pool www" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
```

I'm doubting it's a nginx issue because the systemd service also doesn't work.

**Comment by orangemelo11** [comment]
All artisan commands should be ran inside the domain folder

**Comment by stevenroose** [comment]
![image](https://user-images.githubusercontent.com/853468/218291446-e4d8ebfb-cf66-4582-a4ed-1331047e9d6d.png)
The guide suggests that it could be any folder. Ok, so I will try move it to Ubuntu's webapp folder?

**Comment by stevenroose** [comment]
> All artisan commands should be ran inside the domain folder

I don't think this is correct. I tried to run the systemd command manually as follows:

```
$ cd /
$ /usr/bin/php8.1 /root/pixelfed/artisan horizon
Horizon started successfully.
^CShutting down...
$ sudo -u pixelfed /usr/bin/php8.1 /root/pixelfed/artisan horizon
Could not open input file: /root/pixelfed/artisan
```

So even in the directory `/` I can run the php command when using root, but I can't when using the pixelfed user. Somehow the php8.1 binary isn't allowing the pixelfed user to run the artisan scripts.

**Comment by orangemelo11** [comment]
I have no idea how did you install but if you need help with fresh install I can help you

**Comment by stevenroose** [comment]
I followed the tutorial almost exactly: https://docs.pixelfed.org/running-pixelfed/prerequisites/

So I guess this could function as a bug report of the tutorial for Ubuntu (latest LTS, fresh VPS).

**Comment by stevenroose** [comment]
I did the entire install as `root` and composer doesn't seem to be happy about that. Could it be that because I ran composer install as root, the pixelfed user can't access some of the deps for the artisan executable? Even though I did several `chmown`s and `chmod`s afterwards. I guess I'll have to restart and update the tutorial as I go. It never mentions things shouldn't be run as root, f.e.

**Comment by orangemelo11** [comment]
just follow these 

create an account at ploi.io for free
connect your host to ploi 
create a server fresh ubuntu server using ploi 
create a laravel site project using ploi
create a database using ploi
deploy github pixelfed/pixelfed
branch dev
Amend the env as needed like database/ domain credentials etc

under server or site management go to options horizon create horizon 

Rest is setting the env as you want

**Comment by orangemelo11** [comment]
p.s - don’t forget the ssl part on ploi

**Comment by stevenroose** [comment]
Wouldn't that mean my pixelfed was hosted on ploi?

EDIT: also, I followed the official installation manual carefully, so consider this an issue report of the manual. It should be possible for a professional to install pixelfed by following the manual right?

**Comment by orangemelo11** [comment]
Hi

I don’t know I wanted to help you with a stable installation up to you

**Comment by stevenroose** [comment]
I got this resolved by starting over. I filed a few MRs in the docs repo. For the record, this is the exact course I took..

------------------------

preparation
===========


# installation

```
$ apt install git vim php-fpm composer mariadb-server nginx redis php-gd jpegoptim optipng pngquant ffmpeg
```

# php

```
$ php-fpm8.1 -m
[PHP Modules]
calendar
cgi-fcgi
Core
ctype
date
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
openssl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

$ apt install php-bcmath php-curl php-gd php-intl php-mbstring php-redis php-xml php-zip php-mysql

$ php-fpm8.1 -m
[PHP Modules]
bcmath
calendar
cgi-fcgi
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

```
$ vim /etc/php/8.1/fpm/php.ini
```

edit the fields
- `post_max_size`
- `upload_max_filesize`
- `max_file_uploads`
- `max_execution_time`


# mariadb

```
$ mysql -u root -p
> create database pixelfed;
> grant all privileges on pixelfed.* to 'pixelfed'@'localhost' identified by 'strong_password';
> flush privileges;
```

# user

```
$ cp /etc/php/8.1/fpm/pool.d/www.conf /etc/php/8.1/fpm/pool.d/pixelfed.conf
$ vim /etc/php/8.1/fpm/pool.d/pixelfed.conf
```

set these vars:
```
[pixelfed]
user = pixelfed
group = pixelfed
listen = /run/php/php8.1-fpm-pixelfed.sock
listen.owner = pixelfed
listen.group = pixelfed
listen.mode = 0660
```

```
$ systemctl restart php8.1-fpm
```

# redis

```
$ vim /etc/redis/redis.conf
```

set
```
port 0
unixsocket /var/run/redis/redis-server.sock
unixsocketperm 770
```

(not sure this is needed, but I do it)
```
$ usermod -aG redis pixelfed
```


installation
============

```
$ mkdir /usr/share/webapps
$ cd /usr/share/webapps/
$ git clone -b dev https://github.com/pixelfed/pixelfed.git pixelfed
$ cd pixelfed/
$ chown -R pixelfed:pixelfed .
$ find . -type d -exec chmod 755 {} \;
$ find . -type f -exec chmod 644 {} \;

$ composer install --no-ansi --no-interaction --optimize-autoloader

$ cp .env.example .env
```

Changed the values of

- `APP_NAME`
- `APP_URL` (also to be https)
- `APP_DOMAIN`
- `ADMIN_DOMAIN`
- `SESSION_DOMAIN`
- `DB_SOCKET` (and remove `DB_HOST` and `DB_PORT`)
- `DB_PASSWORD`
- `REDIS_SCHEME`
- `REDIS_HOST`
- `REDIS_PORT`
- `ACTIVITY_PUB`
- `AP_REMOTE_FOLLOW`
- `MAIL_DRIVER`
- `MAIL_HOST`
- `MAIL_PORT`
- `MAIL_USERNAME`
- `MAIL_PASSWORD`
- `MAIL_ENCRYPTION`
- `MAIL_FROM_ADDRESS`
- `MAIL_FROM_NAME`

```
$ php artisan key:generate
$ php artisan storage:link
$ php artisan migrate --force
$ php artisan import:cities
$ php artisan instance:actor
$ php artisan passport:keys
$ php artisan route:cache
$ php artisan view:cache
$ php artisan config:cache

$ php artisan horizon:install
$ php artisan horizon:publish
```

# systemd

```
$ vim /etc/systemd/system/pixelfed.servier
```

```
[Unit]
Description=Pixelfed task queueing via Laravel Horizon
After=network.target
Requires=mariadb
Requires=php8.1-fpm
Requires=redis
Requires=nginx

[Service]
Type=simple
ExecStart=/usr/bin/php /usr/share/webapps/pixelfed/artisan horizon
User=pixelfed
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

```
$ systemctl enable --now pixelfed
```


# let's encrypt

Instructions taken from https://certbot.eff.org/instructions?ws=nginx&os=ubuntufocal .

```
$ ufw allow 80/tcp
$ ufw allow 443/tcp
```

```
$ sudo snap install core; sudo snap refresh core
$ snap install --classic certbot
$ ln -s /snap/bin/certbot /usr/bin/certbot
$ certbot --nginx
```

Change `/etc/nginx/sites-available/default` to this:

```
server {
        listen 443 ssl http2; # managed by Certbot
        listen [::]:443 ssl http2; # managed by Certbot
        server_name [DOMAIN]; # managed by Certbot

        root /usr/share/webapps/pixelfed/public;         # path to repo/public

        ssl_certificate /etc/letsencrypt/live/[DOMAIN]/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/[DOMAIN]/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";

        index index.html index.htm index.php;

        charset utf-8;

        location / {
                try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        error_page 404 /index.php;

        location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/run/php/php8.1-fpm-pixelfed.sock; # make sure this is correct
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # or $request_filename
        }

        location ~ /\.(?!well-known).* {
                deny all;
        }
}
server {
        listen 80 ;
        listen [::]:80 ;
        server_name [DOMAIN];

        if ($host = [DOMAIN]) {
                return 301 https://$host$request_uri;
        } # managed by Certbot

        return 404; # managed by Certbot
}
```

In `/etc/nginx/nginx.conf`, set

- `user` to `pixelfed`
- `client_max_body_size` to the value according to my php ini

```
$ systemctl restart nginx  # probably nginx -s reload would be sufficient
```


Starting
=======


```
$ systemctl start pixelfed
```
