### ISSUE TITLE
Portfolio not loading

### ISSUE THREAD

**Issue by Danie10** [pixelfed/pixelfed#4192]
When clicking on My Portfolio button in my profile, all I see briefly is a portfolio icon then the screen goes black and shows a spinning circle.

It used to work as I set it all up after Portfolios went live. I have tried two different desktop brows and a mobile browser. Have tried disabling dark mode, and also tried when logged out (using portfolio URL). My link is https://portfolio.pixelfed.social/danie10. I notice though a logged out person does not see any portfolio link on my profile, only posts and collections.

I can see @Dansup portfolio though. So maybe it is only my own portfolio, but how can I reset it, or get access to it now?

**Comment by koreus** [comment]
I have the same issue using the "most recent posts". 
It works with the source "Curated posts".

Using Version: 0.11.4-4a1cbb80

**Comment by dansup** [comment]
Fixed in latest commits!

**Comment by tigransimonyan** [comment]
version: v0.11.13

`GET /api/portfolio/680041427420344321/feed`

`SQLSTATE[42803]: Grouping error: 7 ERROR:  column "media.id" must appear in the GROUP BY clause or be used in an aggregate functionLINE 1: ...tus_id" is not null group by "status_id" order by "id" desc ...                                                             ^ (Connection: pgsql, SQL: select "status_id" from "media" where "profile_id" = 680041427420344321 and "status_id" is not null group by "status_id" order by "id" desc limit 50)`
