### ISSUE TITLE
Apply filter on multiimage-posting will only be set on first image

### ISSUE THREAD

**Issue by xundeenergie** [pixelfed/pixelfed#4194]
When i upload more than one image to a posting in Webapp (Desktop and Smartphone), i can set for each image a filter. 

But the filter is only applied to the first one, when i post it finally.

Example:
https://japix.schuerz.at/i/web/post/532133134731522448
On both images i set the "poplar"-Filter.

That's all, what browser-console says. (the PassFF-Entries are not from pixelfed. It's my passwordmanager)
![image](https://user-images.githubusercontent.com/5894829/219611268-8bf265f0-74d9-4ba1-851b-97baacfe3781.png)

I use dev branch with commit ac6683e9. But the problem exists since more than a year.

**Comment by BuZZ-dEE** [comment]
I can confirm this issue. I think this should have a high priority.
