### ISSUE TITLE
Cant post mp4s

### ISSUE THREAD

**Issue by TheArticToxic9** [pixelfed/pixelfed#4199]
When I try to post a mp4 i get this message

![image](https://user-images.githubusercontent.com/38593949/219905601-420fb128-5595-4daf-8338-7f2ca20f827b.png)

anyway to fix it? When i upload photos it was fine

**Comment by TheArticToxic9** [comment]
I tried doing it on both pc and android i get the same message

**Comment by koreus** [comment]
On which server ? The server must allow mp4 , which is not set by default.
