### ISSUE TITLE
Optional dark theme (and maybe additional themes)

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#42]
I'm thinking something like a easily accessible button where one can easily toggle different themes by clicking, either drop down or just a button that switches between them while you click like a toggle thing. It is pretty much up to Dan or anyone else as I am not a coding dude or anything but thought it would be good to do some initial input. I am very sure that a lot of people will appreciate this feature.

**Comment by dansup** [comment]
A dark theme is not on our roadmap at this time.

**Comment by ZeroDot1** [comment]
Hi @dansup, 

I would appreciate a Dark Theme very much as it would improve the accessibility of the site for visually impaired people.
Is it possible to add this in the future?

**Comment by dansup** [comment]
I will try to include this into the v1.0 release!

**Comment by ZeroDot1** [comment]
Thank you very much. I appreciate this very much.

**Comment by trwnh** [comment]
Dark theme toggle has been added recently!

**Comment by CurrentBias** [comment]
> Dark theme toggle has been added recently!

Is there a way to toggle this for the whole instance instead of on a per-user basis while logged in?

Thank you!

**Comment by mitexleo** [comment]
> > Dark theme toggle has been added recently!
> 
> Is there a way to toggle this for the whole instance instead of on a per-user basis while logged in?
> 
> Thank you!

At this moment,  no ..

**Comment by Blackieray** [comment]
White is glaring. No way to change to dark theme, Doesn't seem to exist infact.
