### ISSUE TITLE
Post thumbnails and deletion

### ISSUE THREAD

**Issue by alex-phillips** [pixelfed/pixelfed#420]
Running a local dev instance per your docker container. When I post an image, it uploads successfully and I can see the image as a post. However, if I go to my timeline, it does not display a thumbnail of the image (looks like the background-image url is simply set to `domain.com/storage`.

Also, when I attempt to delete a post, the delete API call returns a 302 and simply takes me back to my timeline, but the post still exists and is viewable.

**Comment by dansup** [comment]
@alex-phillips Hi, I haven't had a chance to look at the dockerfile yet, will try to get it working this weekend!

**Comment by dansup** [comment]
Duplicate of #43
