### ISSUE TITLE
Dockerhub missing all images for pixelfed/pixelfed

### ISSUE THREAD

**Issue by intentionally-left-nil** [pixelfed/pixelfed#4214]
The docker-compose.yml file references pikelfed/pixelfed:latest. However there don't appear to be any images that exist:
https://hub.docker.com/r/pixelfed/pixelfed/tags

**Comment by intentionally-left-nil** [comment]
I figured out that you have to pull a specific tag for it to build locally, but it would still be nice to publish an official version, rather than needing to re-create it (Especially since it appears at first glance that the same docker container should work for everyone with just different .env files

**Comment by lordkitsuna** [comment]
how exactly did you do this? i tried git checkout on a tag but it still does not build locally it gets mad that it cant find a manafest for the docker image
