### ISSUE TITLE
can not select Riga as location

### ISSUE THREAD

**Issue by BuZZ-dEE** [pixelfed/pixelfed#4231]
It is not possible to select Riga (Latvia) as location.

![Screenshot_2023-03-12-12-52-51-04_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/125954/224545874-99a79a2c-5d60-4968-8edb-d5d62268eef5.jpg)

**Comment by alexgranford** [comment]
Please add your issue to #3277, there are lots of similar issues added and developers do not pay any attention. Let’s at least collate our frustration into one tracker.
