### ISSUE TITLE
Login with Instagram (Facebook)

### ISSUE THREAD

**Issue by erlend-sh** [pixelfed/pixelfed#4234]
In light of [Facebook’s ActivityPub experiment “P92”](https://www.platformer.news/p/meta-is-building-a-decentralized?publication_id=7976&post_id=107445508), might it make sense for Pixelfed to support an optional login with Instagram/Facebook?

Seeing as it’s Facebook, it’s hard to imagine P92 being anything other than a [EEE](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish) play. However, by supporting easy onboarding for Instagram users, Pixelfed would basically be already offering what P92 is vaguely promising.

If Fb genuinely intends to be a good citizen of the Fediverse, they should accommodate interoperability between the likes of Instagram and Pixelfed. By supporting Ig login, you get to say “we’ve done our part; your turn”.

Related: #2089 & #2877

**Comment by mitexleo** [comment]
FB is here for destroying the fediverse ! This is what they do to new projects !

**Comment by x64x2** [comment]
> In light of [Facebook’s ActivityPub experiment “P92”](https://www.platformer.news/p/meta-is-building-a-decentralized?publication_id=7976&post_id=107445508), might it make sense for Pixelfed to support an optional login with Instagram/Facebook?
> 
> Seeing as it’s Facebook, it’s hard to imagine P92 being anything other than a [EEE](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish) play. However, by supporting easy onboarding for Instagram users, Pixelfed would basically be already offering what P92 is vaguely promising.
> 
> If Fb genuinely intends to be a good citizen of the Fediverse, they should accommodate interoperability between the likes of Instagram and Pixelfed. By supporting Ig login, you get to say “we’ve done our part; your turn”.
> 
> Related: #2089 & #2877

No Facebook

Facebook is not free nor open source 

Facebook just want to shit on open source federation
