### ISSUE TITLE
Location no longer working 

### ISSUE THREAD

**Issue by orangemelo11** [pixelfed/pixelfed#4239]
Cannot add a location while posting a photo using postgral database latest version of pf tried php artisan imprort:cities doesn’t work either

**Comment by x64x2** [comment]
It's a feature not a bug

**Comment by orangemelo11** [comment]
when i type it doesn’t drop down any location as before anymore it doesn’t work that’s what I meant

**Comment by dansup** [comment]
@orangemelo11 @s0mt0chukwu fixed in [64a4a00](https://github.com/pixelfed/pixelfed/commit/64a4a0060aeafa5b204ab6e3151d5c146d0fd69f)
