### ISSUE TITLE
follower count doesn't add up despite having two followers already 

### ISSUE THREAD

**Issue by Nekothegamer** [pixelfed/pixelfed#4241]
my follower count still says 0 despite having two people following me already 

![Screenshot_20230322-104629](https://user-images.githubusercontent.com/112352776/226865343-9316f073-19bb-4262-820f-e61517ebd84e.png)
![Screenshot_20230322-104633](https://user-images.githubusercontent.com/112352776/226865357-af4a4128-829c-4054-9261-20a17ff42af8.png)

**Comment by ghost** [comment]
Do you have the same effect after using

`php artisan cache:clear` ?

**Comment by Nekothegamer** [comment]
> Do you have the same effect after using
> 
> `php artisan cache:clear` ?

this is an issue i had with pixey.org, i don't really have this problem anymore
