### ISSUE TITLE
Problems in worker

### ISSUE THREAD

**Issue by CyberPingU** [pixelfed/pixelfed#4244]
With a docker-compose fresh install, I get this error on worker:
`worker_1  | [2023-03-23 10:15:10] production.ERROR: Class "BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BeyondCode\\LaravelWebSockets\\WebSocketsServiceProvider\" not found at /var/www/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208)
worker_1  | [stacktrace]
worker_1  | #0 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\\Foundation\\ProviderRepository->createProvider()
worker_1  | #1 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest()
worker_1  | #2 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(649): Illuminate\\Foundation\\ProviderRepository->load()
worker_1  | #3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
worker_1  | #4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
worker_1  | #5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
worker_1  | #6 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
worker_1  | #7 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
worker_1  | #8 {main}
worker_1  | "} 
worker_1  | 
worker_1  | In ProviderRepository.php line 208:
worker_1  |                                                                             
worker_1  |   Class "BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" not found  
worker_1  |                                                                             
worker_1  | 
pixelfed_worker_1 exited with code 1
`

Any clue on how to solve this?

**Comment by mattlqx** [comment]
Remove the contents of `/var/www/bootstrap/cache/`.
