### ISSUE TITLE
Error 1146: pixelfed.config_cache doesn't exist

### ISSUE THREAD

**Issue by CyberPingU** [pixelfed/pixelfed#4245]
When I launch artisan generate, I always get this error and actually the db is empty.
How do you get is populated?

`pixelfed@memoria:~/pixelfed$ php artisan key:generate
Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pixelfed.config_cache' doesn't exist (SQL: select * from `config_cache` where `k` = pixelfed.oauth_enabled limit 1)
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
756▕ // If an exception occurs when attempting to run a query, we'll format the error
757▕ // message to include the bindings with SQL, which will make this exception a
758▕ // lot more helpful to the developer instead of just the database's errors.
759▕ catch (Exception $e) {
➜ 760▕ throw new QueryException(
761▕ $query, $this->prepareBindings($bindings), $e
762▕ );
763▕ }
764▕ }
1 [internal]:0
Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()
+2 vendor frames
4 [internal]:0
Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()
`

**Comment by mitexleo** [comment]
Did you run `php artisan migrate --force` ?

**Comment by gangrif** [comment]
If it matters, this fixed a very similar problem for me.  A different table that didn't exist after i did a pixelfed update.

**Comment by blacklight** [comment]
I can confirm the issue.

In my case it can be reproduced even with a fresh docker-compose installation:

```
app-1     | Fresh installation, initializing database...
app-1     |
app-1     | In Connection.php line 829:
app-1     |
app-1     |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pixelfed.config_
app-1     |   cache' doesn't exist (Connection: mysql, SQL: select * from `config_cache`
app-1     |   where `k` = pixelfed.oauth_enabled limit 1)
```

It just seems that `config_cache` is being read before being initialized.

If I run a manual `CREATE TABLE config_cache` statement (with a very vague idea of what the columns are supposed to be btw) then the db initialization can proceed.

**Comment by blacklight** [comment]
@trwnh why has this issue been closed? In my case it can be reproduced also on a vanilla installation by following the docs. Manually creating tables perhaps should be a workaround, not a solution, unless it's documented somewhere.
