### ISSUE TITLE
Bio text limit could be more obvious

### ISSUE THREAD

**Issue by alexlehm** [pixelfed/pixelfed#4248]
I tried to add a link to my bio and ran over the 125 char limit which I didn't notice immediately and when clicking Submit the error messages says stay below 125 chars and resets the field.

It would be better if the indicator that you are over the limit would be more obvious, maybe make the text read and it would be nice if the message didn't clear the fields.

![image](https://user-images.githubusercontent.com/156144/227708557-06ef1c05-d1d0-40fb-86eb-9bf845202461.png)

**Comment by dansup** [comment]
Fixed in latest commits!
