### ISSUE TITLE
Endpoint "/api/v1/accounts/update_credentials" is not working correctly

### ISSUE THREAD

**Issue by mczachurski** [pixelfed/pixelfed#4250]
Hi,

I would like to use `update_credentials` endpoint to update user profile information like `display_name`, `note`, `website` and `avatar`. But it seems that it's not working the same like endpoint in Mastodon. I'm sending request like below.

**URL**
```
PATCH https://pixelfed.social/api/v1/accounts/update_credentials
```

**Headers**
```
Authorization: Bearer eyJ0......
Content-Type: multipart/form-data; boundary=d76a15ab-d0d4-499a-a3c6-62a86d0d2a74
```

**Body**
```
--d76a15ab-d0d4-499a-a3c6-62a86d0d2a74
Content-Disposition: form-data; name="display_name"
Content-Type: text/plain; charset=UTF-8

John Doe
--d76a15ab-d0d4-499a-a3c6-62a86d0d2a74
Content-Disposition: form-data; name="note"
Content-Type: text/plain; charset=UTF-8

Biography....
--d76a15ab-d0d4-499a-a3c6-62a86d0d2a74
Content-Disposition: form-data; name="website"
Content-Type: text/plain; charset=UTF-8

https://test.com
--d76a15ab-d0d4-499a-a3c6-62a86d0d2a74
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpeg

0x3..............(image binary data)
--d76a15ab-d0d4-499a-a3c6-62a86d0d2a74
```

Also I tried the same in Postman.

<img width="1191" alt="Screenshot 2023-03-25 at 11 12 48" src="https://user-images.githubusercontent.com/6191974/227711137-5de5ad85-b635-4251-af23-b451572ca267.png">

In both cases Pixelfed API returns `200 OK` but data has not been changed (text fields and avatar). When I'm sending exactly same requests to Mastodon API everything is working as expected.

However, when I'm sending request like below, then new values are changed in Pixelfed, but I cannot send avatar binary data in the URL (?).

**URL**
```
PATCH https://pixelfed.social/api/v1/accounts/update_credentials?display_name=John Doe&website=jdoe.com
```

Is this a bug in Pixelfed API or I'm doing something wrong?

**Comment by dansup** [comment]
@mczachurski Sorry about that, I'm working on a fix!

**Comment by dansup** [comment]
@mczachurski So the fix is pretty simple, instead of `PATCH` you should do a `POST` request when uploading an avatar. The `POST` method will work with or without an `avatar` param so you can use this instead of `PATCH`.

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
If I understand things correctly, this should start working properly from PHP 8.4 (released at the end of this year), when https://wiki.php.net/rfc/rfc1867-non-post is implemented
