### ISSUE TITLE
Link profiles to other instances don't always work 

### ISSUE THREAD

**Issue by alvarokrn** [pixelfed/pixelfed#4254]
I'm doing a little project  where I need to create a Pixelfed profile link to a user which is not the  same instance.

For example, I'm kr0n@pixelfed.social and I want to build a profile link to @deniman@pixelfed.eus. My first approach was to try something like https://pixelfed.social/@deniman@pixelfed.eus but this does not work. I've tryed with other account like https://pixelfed.social/@kr0n@pixelfed.de and it works right, but not for https://pixelfed.social/@kr0n@pixel.tchncs.de

So, I guess this is a bug or maybe something is wrong with these accounts or the instances.

**Comment by pitbuster** [comment]
Probably the instance know about the user that works, but not about the other one (you can search for the user to trigger the instance knowing about a new user). On the other hand: why does https://pixelfed.eus/deniman not work for you?

**Comment by alvarokrn** [comment]
That makes sense. 

https://pixelfed.eus/deniman does not work for me because I want to link to the "deniman@pixelfed.eus" in the proper instance of other user, in that way the user click on the link and see the profile in the logged instance and can follow to deniman

**Comment by dansup** [comment]
@alvarokrn I can fix this.

Do you need `https://pixelfed.social/@username@example.org` to redirect (and resolve*) to `https://example.org/username` (the origin profile) when not logged in to `pixelfed.social`?

If logged in to `pixelfed.social` it would redirect (and resolve* if necessary) the webfinger profile to the local profile page (ie: `https://pixelfed.social/i/web/profile/123`)

\* - resolving remote profiles to local or origin urls from unauthenticated users could be abused, and requires some careful consideration in it's implementation

**Comment by alvarokrn** [comment]
> If logged in to pixelfed.social it would redirect (and resolve* if necessary) the webfinger profile to the local profile page (ie: https://pixelfed.social/i/web/profile/123)

That's what it was not working properly at least for the two links provided:

- https://pixelfed.social/@deniman@pixelfed.eus 
- https://pixelfed.social/@kr0n@pixel.tchncs.de

I was logged in to pixelfed.social, but those links failed. Today it worked. So I guess it might be something related to the trigger commented by @pitbuster
