### ISSUE TITLE
API endpoint (api/v1/accounts/*/block) for blocking account is not working

### ISSUE THREAD

**Issue by mczachurski** [pixelfed/pixelfed#4256]
Hi,

The API endpoint for blocking account is not working (tested with 0.11.5 Pixelfed).

**Headers**
```
Authorization: Bearer eyJ.......
```

**Url**
```
POST https://pixelfed.social/api/v1/accounts/[ACCOUNT_ID]/block
```

In the response we have:
```html
<div class="container">
  <div class="error-page py-5 my-5">
    <div class="text-center">
      <h3 class="font-weight-bold">Something went wrong</h3>
      <p class="lead py-3">We cannot process your request at this time, please try again later. </p>
      <p class="mb-0">
        <a href="/" class="btn btn-primary font-weight-bold">Go back to timeline</a>
      </p>
    </div>
    <hr>
    <p class="text-center small payload text-uppercase font-weight-bold text-primary cursor-pointer" data-payload="eyJpdiI6Im1VR1VuSExoT210V3JWR25qQm1vakE9PSIsInZhbHVlIjoieWsyMnFoOFZZSUtMbEhHc2I3a3B1d2NlQmZnMG5ha09SQ3N5cGpCSzMyaHh4U3UzYWJhUFowVGRhaUcrNkZVQ1NhRXFPMFB6Nk8xSUdqZHA3S0drdHZGaEVHa1hKSEllSTltRGpBNVV3OVU9IiwibWFjIjoiYWU5MWY3YWJmMWJlZmFmZmM4OWYyYTY4ZmZhMjA5ZTJmMGNkMTgxYzBmMjFhZjdiM2Q1Y2JlODFhNjA5NDFjOCIsInRhZyI6IiJ9">
      Copy diagnostic details
    </p>
  </div>
</div>
```

Similar endpoint for unblocking account is working correctly.

**Comment by mitexleo** [comment]
Can you open the url on a browser and copy the  payload ? Then go to Diagnostics and Decrypt that. It will display the error msg.

**Comment by mczachurski** [comment]
I attached payload in the bug description above. I cannot find "Diagnostics" page (probably it's only for administrators).

**Comment by mitexleo** [comment]
> I attached payload in the bug description above. I cannot find "Diagnostics" page (probably it's only for administrators).

Yeah , diagnostics is available in the Admin Dashboard.

**Comment by mczachurski** [comment]
I don’t have access to pixelfed.social admin dashboard 😉.

**Comment by mitexleo** [comment]
> I don’t have access to pixelfed.social admin dashboard 😉.

🦊
