### ISSUE TITLE
Discover showing same post with different hashtags

### ISSUE THREAD

**Issue by orangemelo11** [pixelfed/pixelfed#4271]
Testfight showinf same post on discover with different hashtags I understand this is because the post contains too many hashtags 

It would be better if the discover could show a certain post just once without repeating it with different hashtags ?

**Comment by dansup** [comment]
@orangemelo11 This is usually caused by someone posting from Mastodon and Pixelfed, so technically they are two unique posts from two unique accounts.

**Comment by orangemelo11** [comment]
Single post on mastodon 


![IMG_0021](https://user-images.githubusercontent.com/119735594/229807597-970dfd77-5b20-42e4-86f7-ca5b4851331f.jpeg)

showing multiple times on discover  on different hashtags 

#fotografie  and #dog

![IMG_0022](https://user-images.githubusercontent.com/119735594/229807873-c322bdd8-2c28-40af-8490-f8b50955e2ed.jpeg)

![IMG_0023](https://user-images.githubusercontent.com/119735594/229808035-a0d0f384-97c4-4984-8210-3b5830e3fae3.jpeg)

**Comment by orangemelo11** [comment]
@dansup


attached images please take a look
