### ISSUE TITLE
embed latest post

### ISSUE THREAD

**Issue by niccokunzmann** [pixelfed/pixelfed#4272]
I would like to know if it is already possible to embed the latest post of a pixelfed account.

I can see that there is the embed option like this: #776
Post -> share -> embed

What I would like to have for our website is that the posts update to the latest post automatically so that  people see what is going on.

Is this already implemented? Is this something that would be implemented here? Is this something for a 3rd-party service?

**Comment by x64x2** [comment]
It's already implemented already.

**Comment by niccokunzmann** [comment]
Where can I read more about how to do it?

**Comment by dansup** [comment]
@niccokunzmann This is how you get the embed code for your profile

1) Navigate to profile and tap on the gear button and then 'View in old UI` ![Screenshot 2023-04-04 at 2 39 57 AM](https://user-images.githubusercontent.com/877217/229737537-b39c04ba-8080-4038-917d-38a3736b3b4a.png)

2) Tap on 3 dot menu ![Screenshot 2023-04-04 at 2 40 15 AM](https://user-images.githubusercontent.com/877217/229737925-c525780e-62e8-4c2e-a533-0e8f30351e11.png)

3) Tap on 'embed'
![Screenshot 2023-04-04 at 2 40 23 AM](https://user-images.githubusercontent.com/877217/229738080-252960d2-9349-4954-bf7c-d0a1d6a413f5.png)

4) Tap 'Copy embed code'
![Screenshot 2023-04-04 at 2 40 33 AM](https://user-images.githubusercontent.com/877217/229738220-638064a5-c6df-4e3f-abea-c028ae46fe9b.png)

Then you can paste that HTML on your own website or other platforms where supported!

**Comment by andypiper** [comment]
> 1. Navigate to profile and tap on the gear button and then 'View in old UI`

Is this going to be added to the new UI, or will we always have to chose the old UI option to get to the embed code?
