### ISSUE TITLE
can’t upload photos from files app on Testfight ios

### ISSUE THREAD

**Issue by orangemelo11** [pixelfed/pixelfed#4298]
![IMG_0066](https://user-images.githubusercontent.com/119735594/231573193-ffb0b669-3c33-4adc-8e12-5c537375f696.jpeg)
Hello updated to the latest version of TestFlight app iOS and not able to upload photos using files app yet

**Comment by drallgood** [comment]
Is this still valid? @orangemelo11

**Comment by orangemelo11** [comment]
> Is this still valid? @orangemelo11

Yes sir Testfight iOS app is the same yet
