### ISSUE TITLE
Cannot change profile picture

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#4303]
Hey everyone,

after some months I thought it was time for a new profile picture but discovered that I cannot change the current photo at all. Uploading a new shows the new photo, but the change isn't going live after saving / submitting. This doesn't work either from the web nor from mobile apps like Pixelfed or Vernissage (iOS).

Uploading of other photos and material works without problems (storing on S3, too), this issue seems to be profile-related only.

Version: 0.11.5-d47f2f96
Database: mysql (10.5.18-MariaDB-0+deb11u1)
PHP: 8.2.5
FILESYSTEM_DRIVER | "local"
FILESYSTEMS | FILESYSTEM_CLOUD | "s3"

How can I fix this?

Thanks and best regards,

OIiver

**Comment by ghost** [comment]
Working with

`php artisan avatar:storage`

has helped to refetch the latest avatar. Is this something that happens automatically or does it always need to be triggered manually somehow?

**Comment by orangemelo11** [comment]
> Working with
> 
> `php artisan avatar:storage`
> 
> has helped to refetch the latest avatar. Is this something that happens automatically or does it always need to be triggered manually somehow?

if your instance is new you have to run it for the first time

**Comment by ghost** [comment]
> if your instance is new you have to run it for the first time

It is already four months old, that's why I was wondering after the first change of my profile picture after this time.

**Comment by ghost** [comment]
Closing this for good.
