### ISSUE TITLE
[REQUEST] allow larger video size to be uploaded & webm support

### ISSUE THREAD

**Issue by miseenbutt** [pixelfed/pixelfed#4315]
it would be great to have a larger file size for videos. 15mb is just too small. not sure what the large amount would be, but even around 50/60mb would be at least a doable thing

also webm support would be great to have. since that **should** drop the file size quite a bit. obviously. though I understand problems with support or implementing it in the first

**Comment by mitexleo** [comment]
Upload size can be increased or decreased by the instance admin. For example: on my instance nixorigin.one you can upload to 98 MB file

**Comment by miseenbutt** [comment]
@neonota aye, I am on the main pixelfed.org instance. thanks for letting me know though 😊
