### ISSUE TITLE
error 500 when editing profile

### ISSUE THREAD

**Issue by NellyOfc** [pixelfed/pixelfed#4318]
i am having this problem when editing pixelfed profile, i turned on debug mode and it says these errors, does anyone know how i can solve this?

![image](https://user-images.githubusercontent.com/87354471/233821397-4fe295c1-f8bb-4c9a-82f5-820ab682cb21.png)

**Comment by dansup** [comment]
@NellyOfc You need to install the `intl` php extension as described in the [documentation](https://docs.pixelfed.org/running-pixelfed/prerequisites/#php-fpm)
