### ISSUE TITLE
Incorrect 302 redirect when using API

### ISSUE THREAD

**Issue by entr0p1** [pixelfed/pixelfed#4329]
I'm trying to use [FediFetcher](https://github.com/nanos/FediFetcher) with Pixelfed to retrieve historical posts. When it is querying the API, it is able to query the timeline but when it tries to query an individual post/status, a 302 redirect to the login page is returned.

These are the HTTP logs from NGINX for Pixelfed when this occurs:
`172.18.0.1 - - [24/Apr/2023:23:54:39 +1000] "GET /api/v1/timelines/home HTTP/1.1" 200 63844 "-" "FediFetcher (https://go.thms.uk/mgr)"
172.18.0.1 - - [24/Apr/2023:23:54:40 +1000] "GET /api/v1/timelines/home?limit=20&max_id=525908647988187815 HTTP/1.1" 200 63417 "-" "FediFetcher (https://go.thms.uk/mgr)"
172.18.0.1 - - [24/Apr/2023:23:54:40 +1000] "GET /api/v1/timelines/home?limit=20&max_id=520461028899521013 HTTP/1.1" 200 79736 "-" "FediFetcher (https://go.thms.uk/mgr)"
172.18.0.1 - - [24/Apr/2023:23:54:41 +1000] "GET /api/v1/timelines/home?limit=20&max_id=516690116162388304 HTTP/1.1" 200 94295 "-" "FediFetcher (https://go.thms.uk/mgr)"
172.18.0.1 - - [24/Apr/2023:23:54:41 +1000] "GET /api/v1/timelines/home?limit=20&max_id=514155715055894721 HTTP/1.1" 200 53538 "-" "FediFetcher (https://go.thms.uk/mgr)"
172.18.0.1 - - [24/Apr/2023:23:54:42 +1000] "GET /api/v1/timelines/home?limit=20&max_id=513192509945450636 HTTP/1.1" 200 47988 "-" "FediFetcher (https://go.thms.uk/mgr)"
172.18.0.1 - - [24/Apr/2023:23:54:42 +1000] "GET /api/v1/timelines/home?limit=20&max_id=513192059235713144 HTTP/1.1" 200 64629 "-" "FediFetcher (https://go.thms.uk/mgr)"
172.18.0.1 - - [24/Apr/2023:23:54:43 +1000] "GET /api/v1/timelines/home?limit=20&max_id=512918054445858903 HTTP/1.1" 200 38347 "-" "FediFetcher (https://go.thms.uk/mgr)"
172.18.0.1 - - [24/Apr/2023:23:54:43 +1000] "GET /api/v1/timelines/home?limit=20&max_id=512802183261823041 HTTP/1.1" 200 70620 "-" "FediFetcher (https://go.thms.uk/mgr)"
172.18.0.1 - - [24/Apr/2023:23:54:44 +1000] "GET /api/v1/timelines/home?limit=20&max_id=512785870576369700 HTTP/1.1" 200 41358 "-" "FediFetcher (https://go.thms.uk/mgr)"
172.18.0.1 - - [24/Apr/2023:23:55:01 +1000] "GET /api/v1/statuses/555749281617895425/context HTTP/1.1" 302 378 "-" "FediFetcher (https://go.thms.uk/mgr)"
172.18.0.1 - - [24/Apr/2023:23:55:01 +1000] "GET /login HTTP/1.1" 200 2407 "-" "FediFetcher (https://go.thms.uk/mgr)"`

This was originally logged as a FediFetcher bug [here](https://github.com/nanos/FediFetcher/issues/30) however Dan confirmed on a [Mastodon post](https://mastodon.social/@dansup/110113759189806437) that this was indeed a Pixelfed bug.

Is this issue still pending a fix? Happy to provide any details you need about the environment to reproduce the issue as well.

**Comment by dansup** [comment]
@entr0p1 We recently implemented a spam mitigation that involves blocking requests from cloud ips and it was enabled by default, however I just shipped an update that disables it by default so this could explain the errors your experiencing.

I'm going to close this as it isn't really a bug.
