### ISSUE TITLE
[Bug?] I can't delete my post

### ISSUE THREAD

**Issue by naskya** [pixelfed/pixelfed#4330]
I have just opened a new v0.11.5 instance and faced an issue: I can't delete my post.

I'm not sure if this is a pixelfed bug or a problem with my server settings, so I'm sorry if this is my fault.

https://user-images.githubusercontent.com/48414671/234390298-391f0fa3-c669-4373-81ad-5cfb0be9e2b9.mp4

browser console error log:
```
TypeError: t.status is undefined
    o https://myinstance.example/js/profile.chunk.45a990056083f92b.js:1
    _render https://myinstance.example/js/vendor.js?id=985cea6d09ed0f4c43ee3646a991ac84:2
    r https://myinstance.example/js/vendor.js?id=985cea6d09ed0f4c43ee3646a991ac84:2
    get https://myinstance.example/js/vendor.js?id=985cea6d09ed0f4c43ee3646a991ac84:2
    run https://myinstance.example/js/vendor.js?id=985cea6d09ed0f4c43ee3646a991ac84:2
......
```

the error occurred here:
![2023-04-26_05:19:06](https://user-images.githubusercontent.com/48414671/234393801-4dedaa03-0dae-4313-bb35-f21e1653c86c.png)

server `journalctl -xeu pixelfed.service` log:
```
Apr 25 19:29:10 pixelfed php[25087]: Horizon started successfully.
Apr 25 19:30:37 pixelfed php[25087]:   2023-04-25 19:30:37 App\Jobs\StatusPipeline\StatusDelete ........... RUNNING
Apr 25 19:30:38 pixelfed php[25087]:   2023-04-25 19:30:37 App\Jobs\StatusPipeline\StatusDelete ..... 423.50ms FAIL
```

instance diagnostics:
```
Bootstrap: Writable ✅
Storage: Writable ✅
DATABASE Ping: Pong! Connected to DB "pixelfed" ✅
REDIS Ping: Pong! Connected to Redis ✅
ACTIVITYPUB instance actor created: ✅ true
ACTIVITYPUB instance actor cached: ✅ true
OAUTH enabled: ✅ true
OAUTH token_expiration 365 days
OAUTH public key exists: ✅ true
OAUTH private key exists: ✅ true 
```

**Comment by mitexleo** [comment]
Could you please share laravel logs? 

Can be found in ``pixelfed/storage/logs/``

**Comment by naskya** [comment]
Thank you for your comment, and I apologize that this was my bad.
I didn't know that the laravel log is present at `pixelfed/storage/logs/`, so I checked it for the first time and realized that my S3 setting was wrong. It started working properly after I disabled object storage functionality.
