### ISSUE TITLE
Tags on new posts created via Mastodon compatible api are removed

### ISSUE THREAD

**Issue by aneillans** [pixelfed/pixelfed#4336]
When you submit a post via the Mastodon compatible API, on POST /api/v1/statuses, tags (#example) are removed from the post content.

Given the expectation of Mastodon style compatibility, tags should be maintained and then used to enhance discoverability.

**Comment by aneillans** [comment]
Traced this to a missing route to resolve Mastodon api compatibility with some apps - expectation of some apps is /api/v2/instance endpoint to exist now, as well as /api/v1/instance - so the app wasn't getting some instance config.  Adding this missing route resolved it.

**Comment by dansup** [comment]
Fixed in the latest commits!
