### ISSUE TITLE
Add pusher alternatives

### ISSUE THREAD

**Issue by c33s** [pixelfed/pixelfed#4338]
it feels wrong to free from one proprietary service (insta) just to get held hostage by two others. to be specifc it is only one other service (pusher) but trying to register an account on https://pixelfed.social/ i wasn't able to pass the cloudflare wall, which of course isn't the fault of pixelfed but the team which is hosting pixefled.social.

getting locked out from using pixelfed with waterfox classic which lead to switching to a privacy enhanced chromium only to get blocked by cloudflare was a quite non-inclusive experience. then i had a look into self-hosting pixelfed only to read about requireing pusher.

would [unified push](https://unifiedpush.org/) help here even if it is targed for mobile?

**Comment by mitexleo** [comment]
> it feels wrong to free from one proprietary service (insta) just to get held hostage by two others. to be specifc it is only one other service (pusher) but trying to register an account on https://pixelfed.social/ i wasn't able to pass the cloudflare wall, which of course isn't the fault of pixelfed but the team which is hosting pixefled.social.
> 
> getting locked out from using pixelfed with waterfox classic which lead to switching to a privacy enhanced chromium only to get blocked by cloudflare was a quite non-inclusive experience. then i had a look into self-hosting pixelfed only to read about requireing pusher.
> 
> would [unified push](https://unifiedpush.org/) help here even if it is targed for mobile?

Where did you read about pusher ? Push Notifications is yet to be implemented on Pixelfed.

Pixelfed.social is hosted by @dansup ... 

You can try other instances.

**Comment by mitexleo** [comment]
Pixelfed might use websockets for push Notifications. I'm not sure ! But you won't have to use Pusher !

**Comment by c33s** [comment]
i just wanted to share my experience with it. 

as i wrote i don't blame the prixelfed team for instance admins to use cloudflare. it feels wrong to me to have a federated software that is behind a non-federated gatekeeper. (thanks for pinkging dansup (but of course i also understand that the protection of webapplications and the fight agains ddos and spam is a challenging battle))

> Where did you read about pusher ? Push Notifications is yet to be implemented on Pixelfed.

https://docs.pixelfed.org/running-pixelfed/optional-features/websockets/

> Pixelfed might use websockets for push Notifications. I'm not sure ! But you won't have to use Pusher !

but if i would like to use the push feature it looks like i would have to use pusher.

**Comment by mitexleo** [comment]
Maybe I misunderstood the docs. Sorry !

**Comment by dansup** [comment]
@c33s You do not have to use Pusher to use push notifications, we are using a [php websocket library](https://docs.pixelfed.org/running-pixelfed/optional-features/websockets/#starting-the-websocket-server)
