### ISSUE TITLE
Getting a 500 error when trying to create a personal access token

### ISSUE THREAD

**Issue by SteveDinn** [pixelfed/pixelfed#4340]
```
POST /oauth/personal-access-tokens HTTP/2.0 500 64 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"
```

I don't get any kind of indication that anything has gone wrong from the web app itself, but I found the above entry in my web logs.

Pixelfed v0.11.5

**Comment by dansup** [comment]
@SteveDinn Is this your own instance or a public one?

**Comment by SteveDinn** [comment]
My personal instance. Everything else seems to be fine.

**Comment by dansup** [comment]
@SteveDinn Did you run `php artisan passport:install`?

**Comment by SteveDinn** [comment]
I thought I had, but I guess I had not. That did the trick. Thanks!
