### ISSUE TITLE
Feature request: proxying object storage through nginx

### ISSUE THREAD

**Issue by oculos** [pixelfed/pixelfed#4348]
Hi,

It would be awesome if we could proxy object storage through NGINX, like Mastodon allows.
I am very afraid if I have to move my S3 bucket somewhere, so this would be a nice feature for me and for others.

https://docs.joinmastodon.org/admin/optional/object-storage-proxy/

**Comment by ghost** [comment]
Getting in line here - I once tried this according to the way Mastodon does (where it works flawlessly) and failed. Gave up in the meantime but would be interested in this feature as well!

**Comment by dansup** [comment]
I am doing this on pixelfed.social, simply set `AWS_URL=https://example.org` and replace example.org with your proxy domain. Then run `php artisan config:cache && php artisan cache:clear`

I'll share my Digital Ocean Spaces `.env` config:

```env
PF_ENABLE_CLOUD=true
FILESYSTEM_CLOUD="spaces"
AWS_URL="https://pxscdn.com"
DO_SPACES_KEY="***"
DO_SPACES_SECRET="***"
DO_SPACES_ENDPOINT="https://nyc3.digitaloceanspaces.com"
DO_SPACES_REGION="nyc3"
DO_SPACES_BUCKET="pixelfed-prod"
DO_SPACES_ROOT=""
```

Media uploaded prior to changing this will still use the old URL, I'm working on a command to easily update these.

Note the `DO_SPACES_ROOT=""`, previously the default was `"/"` which lead to unexpected double `//` during a subsequent laravel filesystem update so leave it blank.

**Comment by oculos** [comment]
Amazing! Thanks!

Will this break existing links?

Best,

Francis

**Comment by dansup** [comment]
@oculos It won't break existing links because they will still use the previous `AWS_URL` as cloud media urls are stored in the database. 

I'm working on a command that you can run to update existing media urls to the new `AWS_URL`!

**Comment by ghost** [comment]
> @oculos It won't break existing links because they will still use the previous `AWS_URL` as cloud media urls are stored in the database. 
> 
> 
> 
> I'm working on a command that you can run to update existing media urls to the new `AWS_URL`!

Sounds great! Do you have a sample nginx.conf for the proxying host to share?

**Comment by antondomratchev** [comment]
@OliverPifferi came across this, maybe it could be helpful for you: https://stackoverflow.com/a/44749584/3210172

Trying to make this work with Linode's (Now Akamai) object storage.

**Comment by ghost** [comment]
> @OliverPifferi came across this, maybe it could be helpful for you: https://stackoverflow.com/a/44749584/3210172
> 
> Trying to make this work with Linode's (Now Akamai) object storage.

Thanks for the hint, will check this out. 👌

**Comment by DrMxrcy** [comment]
> @oculos It won't break existing links because they will still use the previous `AWS_URL` as cloud media urls are stored in the database.
> 
> I'm working on a command that you can run to update existing media urls to the new `AWS_URL`!

Was a command ever made to update the URLs?

**Comment by dansup** [comment]
> > @oculos It won't break existing links because they will still use the previous `AWS_URL` as cloud media urls are stored in the database.
> > I'm working on a command that you can run to update existing media urls to the new `AWS_URL`!
> 
> Was a command ever made to update the URLs?

Yes, in #4739

**Comment by lapineige** [comment]
> I am doing this on pixelfed.social, simply set AWS_URL=https://example.org and replace example.org with your proxy domain.

So that mean that `AWS_URL` is meant to point not to the S3 storage, but to another URL where the request is proxied to the S3 storage public endpoint ?

**Comment by SathyaBhat** [comment]
> So that mean that `AWS_URL` is meant to point not to the S3 storage, but to another URL where the request is proxied to the S3 storage public endpoint ?

Yes, I have it pointed to my CDN

**Comment by lapineige** [comment]
Thank you, it seems to be the right setting.
