### ISSUE TITLE
Having some trouble with Instagram import

### ISSUE THREAD

**Issue by SteveDinn** [pixelfed/pixelfed#4350]
I have my Instagram backup all done.
I have 98 photos to import.
I choose the photos and in the `import_datas` table, ~25 or so rows appear.
I then choose the JSON file and I get an unspecified error.

Has anybody else done this?

**Comment by mitexleo** [comment]
Instagram isn't working properly yet. It's WIP

**Comment by hayo** [comment]
I was wondering about the status of this. Similar problem, except only 4 images were imported in the end. @neonota could you point us to the issue where work is being done?

**Comment by paulexyz** [comment]
Most of the issues come from decoding issues because Facebook does weird things to their JSON(s) - here's a PR with a fix for that #4726
