### ISSUE TITLE
.env settings not reflected in admin dashboard or UI

### ISSUE THREAD

**Issue by ltning** [pixelfed/pixelfed#4357]
Tried setting max_caption_length to 1000 in .env, ran artisan config:cache, but the diagnostics page still showed 500. After a bit of fiddling it turns out that when creating a new post, the new limit is used.

Looking through the sources it seems like there should be a way to configure this through the admin dashboard - but I can't find that anywhere.

Running on 0.11.6 (b3e1c7f96acd508e1de890cc76dd64bad4fe998e); upgraded today.

**Comment by mitexleo** [comment]
All you need to do is clear application cache! 

Run `php artisan cache:clear`

**Comment by ltning** [comment]
Yeah, this was done several times, but nothing changed. I cleared all(?) the caches, no change.

**Comment by mitexleo** [comment]
> Yeah, this was done several times, but nothing changed. I cleared all(?) the caches, no change.

Could you please share you diagnostics and .env file contents ?

**Comment by dansup** [comment]
@ltning I can confirm that adding `MAX_CAPTION_LENGTH=1000` in .env and then running `php artisan config:cache && php artisan cache:clear` will increase the limit from 500 to 1000. I think you may have been using the wrong .env variable for this, it's uppercase.

If this still isn't working, please re-open this issue!

**Comment by ltning** [comment]
The .env file has MAX_CAPTION_LENGTH=1000; I did run config:cache afterwards. When that did not work, I did cache:clear (along with the other :clear commands, for good measure). The only immediate effect I saw was that when writing a caption, the max counter now said 1000 rather than 500, so the setting *did* take effect.
Note the title of this issue: The problem was that it was not reflected in the *admin* UI; neither as an editable option nor in the Diagnostics screen. When I load that page now, it does indeed say


PIXELFED | MAX_CAPTION_LENGTH | "1000"
-- | -- | --

so apparently it needed time..?

However, the Settings page does not seem to show me this:
https://github.com/pixelfed/pixelfed/blob/4a97e8003fcb354f1d9a2b734a3a1b37aec6423b/resources/views/admin/settings/config/general.blade.php#L59
nor, in fact, most of the other options there. I'm wondering where these should be exposed, and how I can reach them in the UI?

**Comment by mitexleo** [comment]
> The .env file has MAX_CAPTION_LENGTH=1000; I did run config:cache afterwards. When that did not work, I did cache:clear (along with the other :clear commands, for good measure). The only immediate effect I saw was that when writing a caption, the max counter now said 1000 rather than 500, so the setting _did_ take effect. Note the title of this issue: The problem was that it was not reflected in the _admin_ UI; neither as an editable option nor in the Diagnostics screen. When I load that page now, it does indeed say
> 
> PIXELFED	MAX_CAPTION_LENGTH	"1000"
> so apparently it needed time..?
> 
> However, the Settings page does not seem to show me this:
> 
> https://github.com/pixelfed/pixelfed/blob/4a97e8003fcb354f1d9a2b734a3a1b37aec6423b/resources/views/admin/settings/config/general.blade.php#L59
> 
> 
> nor, in fact, most of the other options there. I'm wondering where these should be exposed, and how I can reach them in the UI?

It was a caching issue !
