### ISSUE TITLE
Feature Request: Support Mastodon Blocked Instance Import Format

### ISSUE THREAD

**Issue by aneillans** [pixelfed/pixelfed#4362]
In order to make it easier to import block lists between installations of fediverse components, please support the same format as currently used in Mastodon, or provide a flat entry ability for an admin to drop a list of domains to block instead of needing to individually search and toggle.

**Comment by dansup** [comment]
We added blocklist import/exports in ecfc076 which was prior to Mastodon implementing it.

The format of the exports are: 
```json
{
    "version": 1,
    "auto_cw": [
        "example.org"
    ],
    "unlisted": [
        "example.org"
    ],
    "banned": [
        "example.org"
    ],
    "created_at": "2023-05-09T03:05:03+00:00",
    "_sha256": "441f560d45871d0cb76ea0450d4d70b0e613ce817e51908d8af8d457e89f10dd"
}
```

I'm not familiar with Mastodons format, we have 3 separate categories and I'm not sure they would be compatible with Mastodon.

**Comment by aneillans** [comment]
Ok - but you miss the use case I pitch; a simpler approach.

At the minute, if you look across the platforms there are too many different models it gets problematic to manage an estate of deployments. 

Calckey / misskey with a flat list (not ideal, no reasons logged)
Mastodon with a csv file structure (better given it actually takes a reason too)
Pixelfed which has a json format (can't see a reason in the definition above?)

There's no commonality - I'm not saying that any one is better than the other, but having the ability to load other formats is going to be essential to try and ease the burden on maintainers :/
