### ISSUE TITLE
Performance of web-ui

### ISSUE THREAD

**Issue by h-2** [pixelfed/pixelfed#4367]
I am new to Pixelfed and am experiencing some serious performance problems.

I am not sure whether these are related to how my instance is set up or if they are problems of the software per se. If you think I should contact my instance about it, please let me know. I am on pixelfed.de which is the second largest instance, I think.

Examples:
* Local feed: it takes 65s to load the first post on the local timeline. I actually thought it was completely broken, but it just took that long to load. This is much faster on Fedilab, so I suspect it's a problem of the WebUI.
* Home feed: it immediately loads six posts, and then it 105s (!) to load the next 5 posts; then it freezes again for a long time before loading the next... This is also no problem on mobile (Fedilab), however the client there might also cache previous posts, so I am not 100% sure about.
* Global feed: curiously, this one loads up immediately 🤷🏻 

To be honest, this makes using the web-interface quite annoying.

Thank you for any help!

**Comment by mitexleo** [comment]
I think it's a instance specific issue 🤔

**Comment by h-2** [comment]
Polite ping at @hnrd, assuming that you are the owner of pixelfed.de?

**Comment by h-2** [comment]
Are there any news on this? I have not been able to reach the admin of pixelfed.de via Github or e-mail. Seeing as pixelfed.de is the second-largest instance, this is a bit worrisome... is no-one else experiencing these problems?
