### ISSUE TITLE
See post from hashtag shows the description only

### ISSUE THREAD

**Issue by mamarguerat** [pixelfed/pixelfed#4386]
When clicking on a post from the hashtag list view, it goes to the description of that post, but the media is not shown. I have 2 instances, one with 11.6 installed (the release commit), and the other one with the latest commit in the dev branch. The problem is only on the second instance. That means that this bug is from one of the latest commits.

The original post
<img width="728" alt="image" src="https://github.com/pixelfed/pixelfed/assets/49449909/930f41d5-91da-46e2-9725-2c0a852045f2">
The post seen from the hashtag list link
<img width="687" alt="image" src="https://github.com/pixelfed/pixelfed/assets/49449909/177b5f96-15d3-4c9a-9843-dfacd3c6ef19">

**Comment by xundeenergie** [comment]
Did you try reloading the page?
Then the image(s) should load...

**Comment by mamarguerat** [comment]
@xundeenergie Yes, the image is there after a reload. But that's not the expected behavior...

**Comment by xundeenergie** [comment]
It's part of the bug :)
Would only know, it we are talking about the same thing.

**Comment by mamarguerat** [comment]
Seems to be fixed, but cannot find the change related to the fix in the code
