### ISSUE TITLE
Pixelfed.social login button broken on Firefox Android

### ISSUE THREAD

**Issue by Cragsand** [pixelfed/pixelfed#4392]
The login button is currently broken for me 
https://pixelfed.social/login 

Firefox Android version:
112.2.0 (Build #2015946691), 7d1493c332+
GV: 112.0.2-20230424110519
AS: 97.2.0

Best regards

https://github.com/pixelfed/pixelfed/assets/49168045/9db8d14c-80cd-4acd-9c00-1b049aa918ce

**Comment by mitexleo** [comment]
Make sure you're not blocking hCaptcha  😉

**Comment by dece** [comment]
Don't you have to use your email instead of your username?

**Comment by tristanjahier** [comment]
The actual problem is that you must use your email address instead of your username, but the email field validation error does not appear properly on Firefox. This should still be considered as a bug though.
