### ISSUE TITLE
Activity - Mod view - broken dev branch

### ISSUE THREAD

**Issue by aneillans** [pixelfed/pixelfed#4397]
The activity mod view page appears to be broken on the current dev branch.

**Comment by dansup** [comment]
@aneillans How so? Can you share a screenshot or decrypted error payload?

**Comment by aneillans** [comment]
> @aneillans How so? Can you share a screenshot or decrypted error payload?

For new users no information is being logged at all its just blank entirely.

**Comment by aneillans** [comment]
Think I've identified what is missing from activity - maybe ... when a user first registers, the initial registration (and login) isn't captured to the activity log - perhaps  ?
