### ISSUE TITLE
Image dimensions should accommodate portrait 2:3

### ISSUE THREAD

**Issue by NFGman** [pixelfed/pixelfed#44]
Most DSLRs (almost all, except the micro 4:3 class I think) use a 2:3 sensor ratio, so an image that's 1500 pixels long would be 1000 wide.  It would be great to accommodate this with Pixelfed.

Instagram allows arbitrarily long landscape images, but portrait images max out at ~4:5, so a 2:3 image is too long.  The user can either crop the image, or use other apps to pad the sides somehow.

Obviously a maximum ratio needs to be applied, or pencil-thin endless images would be a problem, but since most 'photographer' cameras are 2:3, it seems sensible to me that this ratio be considered as a maximum.

**Comment by 0-st** [comment]
6:7 is also a common used portrait format in studio work

**Comment by hellcp** [comment]
I disagree as designer, images that are very long (for example website mockups, scrollable elements) are things I actually create from time to time. I don't see how that kind of restriction is required. I fixed issue that caused images like this to be annoying (and I put everything into a square for convenience, apart from actual image view). I also share this kind of stuff online ;)

**Comment by vilbi** [comment]
Also disagree to the suggestion of limiting image dimentinons format:
- suggestion for the image preview display to be 1:1 in timelines as this format enables also mosaic display wich may be a future feature
- in the detail view there should be a reasonable maximum pixel boundary for width and height, but no ratio restriction.

**Comment by hellcp** [comment]
@vilbi that would actually stop us from making mozaic view, considering that if somebody uploaded 1:100 image, you would just have one image for a very long time ;) Let's keep squares for convenience sake :D

**Comment by vilbi** [comment]
So you can not differ the image from the preview image? 
My suggestion to make it more clear was do limit the original picture size, ratio reasonable AND
use for preview & timeline & mosaic & whatever... a 1:1 crop / resized preview image with small resolution as common
