### ISSUE TITLE
Black margins in multi-photo posts

### ISSUE THREAD

**Issue by savvdm** [pixelfed/pixelfed#4402]
Here's an example: https://pixelfed.social/i/web/post/566267670621564551
This post has several images, with one image in portrait orientation, others in landscape.
The result - the landscape images are displayed with large black margins above and below, presumably reserving space for one single vertical image in the set.
What's wanted - these margins are not displayed. Ideally, each image in a set has its own dimensions for display. At least the first image in a set should not display these black margins, because many people will probably never scroll to other images at all.
The problem appears in a desktop browser (Firefox on Ubuntu, if that matters).

**Comment by SteveDinn** [comment]
It seems to only happen when you scroll so far as to have the *next* image be a dimension that would cause the black margins. i.e., if you have 4 photos, but the 3rd photo is in portrait orientation, you wouldn't see the black margins appear until you scrolled over to the 2nd photo and the aberrant 3rd photo is waiting in the wings.

**Comment by savvdm** [comment]
When I open the example link above, I immediately see black margins above and below the image, without any scrolling whatsoever.

**Comment by SteveDinn** [comment]
You are correct. I didn't even realize that I was using the Android app instead of the website. The Android app behaves slightly differently.
