### ISSUE TITLE
API calls need CORS header

### ISSUE THREAD

**Issue by cheeaun** [pixelfed/pixelfed#4411]
Logging in from [Phanpy](https://phanpy.social/), a 3rd-party web client (using Mastodon's API), the flow works until the `/oauth/token` part as the response returned doesn't include CORS headers.

Devtools console output:

> Access to fetch at 'https://pixelfed.social/oauth/token' from origin 'https://phanpy.social' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> 
> POST https://pixelfed.social/oauth/token net::ERR_FAILED 200

I did a little digging and found that https://pixelfed.social/api/v1/instance also doesn't return CORS headers, so I suspect most of the API calls don't have them.

Instead of a response with no CORS headers, it should have CORS headers.

Tested on Chrome Version 113.0.5672.126 (Official Build) (arm64), macOS Ventura 13.4 (22F66).

Disclaimer: I'm the developer of Phanpy.

**Comment by precz** [comment]
This issue is limiting many PWA applications and was mentioned before https://github.com/pixelfed/pixelfed/issues/3381

**Comment by jeffsikes** [comment]
[trunks.social](https://trunks.social) is also attempting to allow connections to Pixelfed and running into this CORS issue as well.

Tested the web app on MacOS, Firefox and Chrome

```
OPTIONS pixelfed.social/apps CORS Missing Allow Origin
POST pixelfed.social/apps NS_ERROR_DOM_BAD_URI
```

**Comment by ThisIsMissEm** [comment]
I think I can do up a PR today to fix it.. maybe.

**Comment by ThisIsMissEm** [comment]
PR is now ready; have tested locally via curl, but I'm unable to test with phanpy directly because it assumes SSL and my local homelab setup isn't with SSL.
