### ISSUE TITLE
email notification fails when password reset

### ISSUE THREAD

**Issue by aarontrom** [pixelfed/pixelfed#4438]
I am running Pixelfed version 0.11.8 via [yunohost](https://github.com/YunoHost-Apps/pixelfed_ynh) and a user tried to reset the password of an account via the Reset Password page.

When submitting the email via "Send Password Reset Link" they get the following error message: 

![Pixelfed forgot password - error](https://github.com/pixelfed/pixelfed/assets/69819346/1d4dcd37-c38e-4412-97fa-bc9dd5d329f4)

with the following Diagnostic Details:
`eyJpdiI6ImpWcmFSVHNHMnlOaEE1dEY0NFE5bFE9PSIsInZhbHVlIjoiY25DMml5M0hsajE3Z0lMRDBYWlpNUVhka2IwQnBteTRURXFyOTZRWGZsYjZSSndwVzhnbHFBNDlKYldwY054LzNkWS9ST20rQ0NKQWVkQStRb3hRRkJWRVBVWnNEMGF4dFV3dlVWQitpQldJNTlTNG1JVWJxVW5iekY0MU1jNUNOU3JsU2s4RTA5ZGlhQ2hTRExzT1lwMFVOM1kvblU5VGowNlZSL0s3dkNKU01hY0huUUgzREZVYk5IZUxLK0UvQ24zeERBRkJmMk03RndXOWkyQkNrNVk0Unp6ZXNpcGtucVBvNHJrYjhidz0iLCJtYWMiOiJlMWFmNmUyNTAyNWMzNDk2NjJiMmUxOWQ5ZDJjYjEyNTU2N2MzMTRiZWI1ODVkNTczNzRkMTEzMjUwOGJiNGU0IiwidGFnIjoiIn0=`

Did anyone ever came across that error and has an idea what to do?

**Comment by webmink** [comment]
Can you go to <your-domain>/i/admin/diagnostics/home and scroll to the bottom and paste that payload into the box to decrypt it?
![image](https://github.com/pixelfed/pixelfed/assets/1368723/b9c17475-a2c8-470f-aba5-f7e7ccd622e5)

**Comment by aarontrom** [comment]
Ohh okay, I didn't know that it works like that :D 

It says: 
Unable to connect with STARTTLS: 
stream_socket_enable_crypto(): Peer certificate 
CN=`tromdienste.de' did not match expected CN=`localhost'

![pixelfed issue](https://github.com/pixelfed/pixelfed/assets/69819346/1c2e001f-1de3-4875-84bc-1f3a1023ae1e)

**Comment by mitexleo** [comment]
Something is wrong with your config. Could you  please share diagnostics and the email config on .env ?

**Comment by aarontrom** [comment]
Thanks for looking into it! 

email config from .env: 

## Mail
MAIL_DRIVER=smtp
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_FROM_ADDRESS="pixelfed@pixel.tromdienste.de"
MAIL_FROM_NAME="Pixelfed"
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

=======================
 Pixelfed Instance Diagnostic v0.2 
=======================
Troubleshooting

Bootstrap: Writable ✅
Storage: Writable ✅
DATABASE Ping: Pong! Connected to DB "pixelfed" ✅
REDIS Ping: Pong! Connected to Redis ✅
ACTIVITYPUB instance actor created: ✅ true
ACTIVITYPUB instance actor cached: ✅ true
OAUTH enabled: ✅ true
OAUTH token_expiration 365 days
OAUTH public key exists: ✅ true
OAUTH private key exists: ✅ true

Important Information

Version: 0.11.8-unknown git commit
Database: pgsql (13.11)
APP_URL: https://pixel.tromdienste.de
APP_DOMAIN: pixel.tromdienste.de
ADMIN_DOMAIN: pixel.tromdienste.de
SESSION_DOMAIN: pixel.tromdienste.de

PHP Variables

PHP: 8.2.6
PHP INI memory_limit: 256M
PHP INI post_max_size: 512M
PHP INI upload_max_filesize: 512M
PHP INI max_file_uploads: 20
PHP INI max_execution_time: 30
PHP INI max_input_time: 60
PHP INI file_uploads (On): 1
PHP INI - SECURITY allow_url_fopen (true): 1
PHP INI - SECURITY allow_url_include (false):
PHP INI - SECURITY expose_php (false):
PHP INI - SECURITY display_errors (false): Off
PHP INI - SECURITY display_startup_errors (false):
PHP INI - SECURITY log_errors (true): 1
PHP INI - SECURITY ignore_repeated_errors (false):
PHP INI - SECURITY disable_functions:

Pixelfed Variables (No Secrets)

CONFIG	VARIABLE NAME	DETAILS
APP	APP_NAME	"TROMDienste - Pixelfed"
APP	APP_ENV	"production"
APP	APP_DEBUG	❌ false
APP	APP_URL	"https://pixel.tromdienste.de"
APP	APP_LOCALE	"de"
APP	APP_FALLBACK_LOCALE	"en"
BROADCASTING	BROADCAST_DRIVER	"log"
CACHE	CACHE_DRIVER	"redis"
CAPTCHA	CAPTCHA_ENABLED	❌ false
DATABASE	DB_CONNECTION	"pgsql"
DATABASE	REDIS_CLIENT	"predis"
EXP	EXP_LC	❌ false
EXP	EXP_TOP	❌ false
EXP	EXP_POLLS	❌ false
EXP	EXP_CPT	❌ false
EXP	EXP_GPS	❌ false
EXP	EXP_EMC	✅ true
FEDERATION	ACTIVITY_PUB	✅ true
FEDERATION	AP_OUTBOX	✅ true
FEDERATION	AP_INBOX	✅ true
FEDERATION	AP_SHAREDINBOX	✅ true
FEDERATION	AP_REMOTE_FOLLOW	✅ true
FEDERATION	ACTIVITYPUB_DELIVERY_TIMEOUT	"30"
FEDERATION	ACTIVITYPUB_DELIVERY_CONCURRENCY	"10"
FEDERATION	AP_LOGGER_ENABLED	❌ false
FEDERATION	ATOM_FEEDS	✅ true
FEDERATION	REMOTE_AVATARS	✅ true
FEDERATION	NODEINFO	✅ true
FEDERATION	WEBFINGER	✅ true
FEDERATION	PF_NETWORK_TIMELINE	✅ true
FEDERATION	PF_NETWORK_TIMELINE_DAYS_FALLOFF	2
FEDERATION	CUSTOM_EMOJI	❌ false
FEDERATION	CUSTOM_EMOJI_MAX_SIZE	"2000000"
FILESYSTEMS	FILESYSTEM_DRIVER	"local"
FILESYSTEMS	FILESYSTEM_CLOUD	"s3"
HASHING	BCRYPT_COST	"10"
HORIZON	HORIZON_PREFIX	"horizon-"
HORIZON	HORIZON_MEMORY_LIMIT	"64"
HORIZON	HORIZON_BALANCE_STRATEGY	"auto"
HORIZON	HORIZON_MIN_PROCESSES	"1"
HORIZON	HORIZON_MAX_PROCESSES	"20"
HORIZON	HORIZON_SUPERVISOR_MEMORY	"64"
HORIZON	HORIZON_SUPERVISOR_TRIES	"3"
HORIZON	HORIZON_SUPERVISOR_NICE	"0"
HORIZON	HORIZON_SUPERVISOR_TIMEOUT	"300"
HORIZON	HORIZON_DARKMODE	✅ true
IMAGE	IMAGE_DRIVER	"imagick"
INSTANCE	INSTANCE_DESCRIPTION	"Pixelfed - Photo sharing for everyone"
INSTANCE	INSTANCE_CONTACT_FORM	❌ false
INSTANCE	INSTANCE_CONTACT_MAX_PER_DAY	"1"
INSTANCE	INSTANCE_DISCOVER_PUBLIC	❌ false
INSTANCE	EXP_LOOPS	❌ false
INSTANCE	INSTANCE_PUBLIC_HASHTAGS	❌ false
INSTANCE	INSTANCE_CONTACT_EMAIL	""
INSTANCE	INSTANCE_PUBLIC_LOCAL_TIMELINE	❌ false
INSTANCE	INSTANCE_NETWORK_TIMELINE_CACHED	
INSTANCE	INSTANCE_NETWORK_TIMELINE_CACHE_DROPOFF	100
INSTANCE	INSTANCE_NETWORK_TIMELINE_CACHE_MAX_HOUR_INGEST	6
INSTANCE	PAGE_404_HEADER	"Sorry, this page isn't available."
INSTANCE	PAGE_404_BODY	"The link you followed may be broken, or the page may have been removed. <a href="/">Go back to Pixelfed.</a>"
INSTANCE	PAGE_503_HEADER	"Service Unavailable"
INSTANCE	PAGE_503_BODY	"Our service is in maintenance mode, please try again later."
INSTANCE	BANNED_USERNAMES	""
INSTANCE	USERNAME_REMOTE_FORMAT	"@"
INSTANCE	USERNAME_REMOTE_CUSTOM_TEXT	""
INSTANCE	STORIES_ENABLED	✅ true
INSTANCE	RESTRICTED_INSTANCE	❌ false
INSTANCE	OAUTH_TOKEN_DAYS	"365"
INSTANCE	OAUTH_REFRESH_DAYS	"400"
INSTANCE	OAUTH_PAT_ENABLED	❌ false
INSTANCE	OAUTH_PAT_ID	""
INSTANCE	ENABLE_COVID_LABEL	✅ true
INSTANCE	COVID_LABEL_URL	"https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public"
INSTANCE	COVID_LABEL_ORG	"visit the WHO website"
INSTANCE	ENABLE_CONFIG_CACHE	✅ true
LDAP	LDAP_CONNECTION	"default"
LDAP	LDAP_LOGGING	✅ true
LDAP	LDAP_CACHE	❌ false
LOGGING	LOG_CHANNEL	"stack"
LOGGING	LOG_LEVEL (stack)	"debug"
MAIL	MAIL_DRIVER	"smtp"
MAIL	MAIL_HOST	"localhost"
MAIL	MAIL_PORT	"25"
MAIL	MAIL_FROM_ADDRESS	"pixelfed@pixel.tromdienste.de"
MAIL	MAIL_FROM_NAME	"Pixelfed"
MAIL	MAIL_ENCRYPTION	""
MEDIA	MEDIA_EXIF_DATABASE	❌ false
PIXELFED	ADMIN_DOMAIN	"pixel.tromdienste.de"
PIXELFED	APP_DOMAIN	"pixel.tromdienste.de"
PIXELFED	MEMORY_LIMIT	"1024M"
PIXELFED	OPEN_REGISTRATION	✅ true
PIXELFED	MAX_ACCOUNT_SIZE (KB)	"1000000"
PIXELFED	MAX_PHOTO_SIZE (KB)	"15000"
PIXELFED	MAX_AVATAR_SIZE (KB)	"2000"
PIXELFED	MAX_CAPTION_LENGTH	"500"
PIXELFED	MAX_BIO_LENGTH	"125"
PIXELFED	MAX_NAME_LENGTH	"30"
PIXELFED	MIN_PASSWORD_LENGTH	"8"
PIXELFED	MAX_ALBUM_LENGTH	"5"
PIXELFED	ENFORCE_EMAIL_VERIFICATION	✅ true
PIXELFED	IMAGE_QUALITY (1-100)	"80"
PIXELFED	ACCOUNT_DELETION	✅ true
PIXELFED	ACCOUNT_DELETE_AFTER	❌ false
PIXELFED	PF_ENABLE_CLOUD	❌ false
PIXELFED	PF_MAX_USERS	1000
PIXELFED	PF_OPTIMIZE_IMAGES	✅ true
PIXELFED	PF_OPTIMIZE_VIDEOS	✅ true
PIXELFED	PF_USER_INVITES	❌ false
PIXELFED	PF_USER_INVITES_TOTAL_LIMIT	"0"
PIXELFED	PF_USER_INVITES_DAILY_LIMIT	"0"
PIXELFED	PF_USER_INVITES_MONTHLY_LIMIT	"0"
PIXELFED	PF_MAX_COLLECTION_LENGTH	"100"
PIXELFED	MEDIA_TYPES	"image/jpeg,image/png,image/gif,video/mp4"
PIXELFED	LIMIT_ACCOUNT_SIZE	✅ true
PIXELFED	IMPORT_INSTAGRAM	✅ true
PIXELFED	IMPORT_INSTAGRAM_POST_LIMIT	"100"
PIXELFED	IMPORT_INSTAGRAM_SIZE_LIMIT	"5000"
PIXELFED	OAUTH_ENABLED	✅ true
PIXELFED	PF_BOUNCER_ENABLED	❌ false
PIXELFED	PF_MEDIA_FAST_PROCESS	✅ true
PIXELFED	PF_MEDIA_MAX_ALTTEXT_LENGTH	"1000"
PURIFY	RESTRICT_HTML_TYPES	BROKEN
QUEUE	QUEUE_DRIVER	"redis"
SESSION	SESSION_DRIVER	"redis"
SESSION	SESSION_LIFETIME	"86400"
SESSION	SESSION_DOMAIN	"pixel.tromdienste.de"
TRUSTEDPROXY	TRUST_PROXIES	"*"
========= END =========

**Comment by mitexleo** [comment]
> Thanks for looking into it!
> 
> email config from .env:
> 
> ## Mail
> MAIL_DRIVER=smtp MAIL_HOST=localhost MAIL_PORT=25 MAIL_FROM_ADDRESS="[pixelfed@pixel.tromdienste.de](mailto:pixelfed@pixel.tromdienste.de)" MAIL_FROM_NAME="Pixelfed" MAIL_USERNAME=null MAIL_PASSWORD=null MAIL_ENCRYPTION=null
> 
> # =======================
> Pixelfed Instance Diagnostic v0.2
> Troubleshooting
> 
> Bootstrap: Writable ✅ Storage: Writable ✅ DATABASE Ping: Pong! Connected to DB "pixelfed" ✅ REDIS Ping: Pong! Connected to Redis ✅ ACTIVITYPUB instance actor created: ✅ true ACTIVITYPUB instance actor cached: ✅ true OAUTH enabled: ✅ true OAUTH token_expiration 365 days OAUTH public key exists: ✅ true OAUTH private key exists: ✅ true
> 
> Important Information
> 
> Version: 0.11.8-unknown git commit Database: pgsql (13.11) APP_URL: https://pixel.tromdienste.de APP_DOMAIN: pixel.tromdienste.de ADMIN_DOMAIN: pixel.tromdienste.de SESSION_DOMAIN: pixel.tromdienste.de
> 
> PHP Variables
> 
> PHP: 8.2.6 PHP INI memory_limit: 256M PHP INI post_max_size: 512M PHP INI upload_max_filesize: 512M PHP INI max_file_uploads: 20 PHP INI max_execution_time: 30 PHP INI max_input_time: 60 PHP INI file_uploads (On): 1 PHP INI - SECURITY allow_url_fopen (true): 1 PHP INI - SECURITY allow_url_include (false): PHP INI - SECURITY expose_php (false): PHP INI - SECURITY display_errors (false): Off PHP INI - SECURITY display_startup_errors (false): PHP INI - SECURITY log_errors (true): 1 PHP INI - SECURITY ignore_repeated_errors (false): PHP INI - SECURITY disable_functions:
> 
> Pixelfed Variables (No Secrets)
> 
> CONFIG VARIABLE NAME DETAILS APP APP_NAME "TROMDienste - Pixelfed" APP APP_ENV "production" APP APP_DEBUG ❌ false APP APP_URL "https://pixel.tromdienste.de" APP APP_LOCALE "de" APP APP_FALLBACK_LOCALE "en" BROADCASTING BROADCAST_DRIVER "log" CACHE CACHE_DRIVER "redis" CAPTCHA CAPTCHA_ENABLED ❌ false DATABASE DB_CONNECTION "pgsql" DATABASE REDIS_CLIENT "predis" EXP EXP_LC ❌ false EXP EXP_TOP ❌ false EXP EXP_POLLS ❌ false EXP EXP_CPT ❌ false EXP EXP_GPS ❌ false EXP EXP_EMC ✅ true FEDERATION ACTIVITY_PUB ✅ true FEDERATION AP_OUTBOX ✅ true FEDERATION AP_INBOX ✅ true FEDERATION AP_SHAREDINBOX ✅ true FEDERATION AP_REMOTE_FOLLOW ✅ true FEDERATION ACTIVITYPUB_DELIVERY_TIMEOUT "30" FEDERATION ACTIVITYPUB_DELIVERY_CONCURRENCY "10" FEDERATION AP_LOGGER_ENABLED ❌ false FEDERATION ATOM_FEEDS ✅ true FEDERATION REMOTE_AVATARS ✅ true FEDERATION NODEINFO ✅ true FEDERATION WEBFINGER ✅ true FEDERATION PF_NETWORK_TIMELINE ✅ true FEDERATION PF_NETWORK_TIMELINE_DAYS_FALLOFF 2 FEDERATION CUSTOM_EMOJI ❌ false FEDERATION CUSTOM_EMOJI_MAX_SIZE "2000000" FILESYSTEMS FILESYSTEM_DRIVER "local" FILESYSTEMS FILESYSTEM_CLOUD "s3" HASHING BCRYPT_COST "10" HORIZON HORIZON_PREFIX "horizon-" HORIZON HORIZON_MEMORY_LIMIT "64" HORIZON HORIZON_BALANCE_STRATEGY "auto" HORIZON HORIZON_MIN_PROCESSES "1" HORIZON HORIZON_MAX_PROCESSES "20" HORIZON HORIZON_SUPERVISOR_MEMORY "64" HORIZON HORIZON_SUPERVISOR_TRIES "3" HORIZON HORIZON_SUPERVISOR_NICE "0" HORIZON HORIZON_SUPERVISOR_TIMEOUT "300" HORIZON HORIZON_DARKMODE ✅ true IMAGE IMAGE_DRIVER "imagick" INSTANCE INSTANCE_DESCRIPTION "Pixelfed - Photo sharing for everyone" INSTANCE INSTANCE_CONTACT_FORM ❌ false INSTANCE INSTANCE_CONTACT_MAX_PER_DAY "1" INSTANCE INSTANCE_DISCOVER_PUBLIC ❌ false INSTANCE EXP_LOOPS ❌ false INSTANCE INSTANCE_PUBLIC_HASHTAGS ❌ false INSTANCE INSTANCE_CONTACT_EMAIL "" INSTANCE INSTANCE_PUBLIC_LOCAL_TIMELINE ❌ false INSTANCE INSTANCE_NETWORK_TIMELINE_CACHED INSTANCE INSTANCE_NETWORK_TIMELINE_CACHE_DROPOFF 100 INSTANCE INSTANCE_NETWORK_TIMELINE_CACHE_MAX_HOUR_INGEST 6 INSTANCE PAGE_404_HEADER "Sorry, this page isn't available." INSTANCE PAGE_404_BODY "The link you followed may be broken, or the page may have been removed. [Go back to Pixelfed.](/)" INSTANCE PAGE_503_HEADER "Service Unavailable" INSTANCE PAGE_503_BODY "Our service is in maintenance mode, please try again later." INSTANCE BANNED_USERNAMES "" INSTANCE USERNAME_REMOTE_FORMAT "@" INSTANCE USERNAME_REMOTE_CUSTOM_TEXT "" INSTANCE STORIES_ENABLED ✅ true INSTANCE RESTRICTED_INSTANCE ❌ false INSTANCE OAUTH_TOKEN_DAYS "365" INSTANCE OAUTH_REFRESH_DAYS "400" INSTANCE OAUTH_PAT_ENABLED ❌ false INSTANCE OAUTH_PAT_ID "" INSTANCE ENABLE_COVID_LABEL ✅ true INSTANCE COVID_LABEL_URL "https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public" INSTANCE COVID_LABEL_ORG "visit the WHO website" INSTANCE ENABLE_CONFIG_CACHE ✅ true LDAP LDAP_CONNECTION "default" LDAP LDAP_LOGGING ✅ true LDAP LDAP_CACHE ❌ false LOGGING LOG_CHANNEL "stack" LOGGING LOG_LEVEL (stack) "debug" MAIL MAIL_DRIVER "smtp" MAIL MAIL_HOST "localhost" MAIL MAIL_PORT "25" MAIL MAIL_FROM_ADDRESS "[pixelfed@pixel.tromdienste.de](mailto:pixelfed@pixel.tromdienste.de)" MAIL MAIL_FROM_NAME "Pixelfed" MAIL MAIL_ENCRYPTION "" MEDIA MEDIA_EXIF_DATABASE ❌ false PIXELFED ADMIN_DOMAIN "pixel.tromdienste.de" PIXELFED APP_DOMAIN "pixel.tromdienste.de" PIXELFED MEMORY_LIMIT "1024M" PIXELFED OPEN_REGISTRATION ✅ true PIXELFED MAX_ACCOUNT_SIZE (KB) "1000000" PIXELFED MAX_PHOTO_SIZE (KB) "15000" PIXELFED MAX_AVATAR_SIZE (KB) "2000" PIXELFED MAX_CAPTION_LENGTH "500" PIXELFED MAX_BIO_LENGTH "125" PIXELFED MAX_NAME_LENGTH "30" PIXELFED MIN_PASSWORD_LENGTH "8" PIXELFED MAX_ALBUM_LENGTH "5" PIXELFED ENFORCE_EMAIL_VERIFICATION ✅ true PIXELFED IMAGE_QUALITY (1-100) "80" PIXELFED ACCOUNT_DELETION ✅ true PIXELFED ACCOUNT_DELETE_AFTER ❌ false PIXELFED PF_ENABLE_CLOUD ❌ false PIXELFED PF_MAX_USERS 1000 PIXELFED PF_OPTIMIZE_IMAGES ✅ true PIXELFED PF_OPTIMIZE_VIDEOS ✅ true PIXELFED PF_USER_INVITES ❌ false PIXELFED PF_USER_INVITES_TOTAL_LIMIT "0" PIXELFED PF_USER_INVITES_DAILY_LIMIT "0" PIXELFED PF_USER_INVITES_MONTHLY_LIMIT "0" PIXELFED PF_MAX_COLLECTION_LENGTH "100" PIXELFED MEDIA_TYPES "image/jpeg,image/png,image/gif,video/mp4" PIXELFED LIMIT_ACCOUNT_SIZE ✅ true PIXELFED IMPORT_INSTAGRAM ✅ true PIXELFED IMPORT_INSTAGRAM_POST_LIMIT "100" PIXELFED IMPORT_INSTAGRAM_SIZE_LIMIT "5000" PIXELFED OAUTH_ENABLED ✅ true PIXELFED PF_BOUNCER_ENABLED ❌ false PIXELFED PF_MEDIA_FAST_PROCESS ✅ true PIXELFED PF_MEDIA_MAX_ALTTEXT_LENGTH "1000" PURIFY RESTRICT_HTML_TYPES BROKEN QUEUE QUEUE_DRIVER "redis" SESSION SESSION_DRIVER "redis" SESSION SESSION_LIFETIME "86400" SESSION SESSION_DOMAIN "pixel.tromdienste.de" TRUSTEDPROXY TRUST_PROXIES "*" ========= END =========

Set MAIL_ENCRYPTION to "tls"

**Comment by aarontrom** [comment]
Okay thx for the suggestion! 

I set that variable in the .env file: 

## Mail
MAIL_DRIVER=smtp
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_FROM_ADDRESS="pixelfed@pixel.tromdienste.de"
MAIL_FROM_NAME="Pixelfed"
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=tls

and then I run 
```
php artisan config:cache
php artisan route:cache
```

when I did that, I got the following error:
```
php artisan config:cache
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 8.2.0". You are running 7.4.33.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 7.4.33. in /var/www/pixelfed/vendor/composer/platform_check.php on line 24
```

then I switched to php 8.2 via:
```
update-alternatives --set php /usr/bin/php8.2 
update-alternatives: using /usr/bin/php8.2 to provide /usr/bin/php (php) in manual mode
```
and then it worked: 
```
php artisan config:cache

   INFO  Configuration cached successfully.  

php artisan route:cache

   INFO  Routes cached successfully.  

```

However, the issue still persists. The same error message in a different form though:

![pixelfed error](https://github.com/pixelfed/pixelfed/assets/69819346/43232777-349f-4cc8-9235-76158abb1ec2)

**Comment by mitexleo** [comment]
> Okay thx for the suggestion!
> 
> I set that variable in the .env file:
> 
> ## Mail
> MAIL_DRIVER=smtp MAIL_HOST=localhost MAIL_PORT=25 MAIL_FROM_ADDRESS="[pixelfed@pixel.tromdienste.de](mailto:pixelfed@pixel.tromdienste.de)" MAIL_FROM_NAME="Pixelfed" MAIL_USERNAME=null MAIL_PASSWORD=null MAIL_ENCRYPTION=tls
> 
> and then I run
> 
> ```
> php artisan config:cache
> php artisan route:cache
> ```
> 
> when I did that, I got the following error:
> 
> ```
> php artisan config:cache
> Composer detected issues in your platform:
> 
> Your Composer dependencies require a PHP version ">= 8.2.0". You are running 7.4.33.
> 
> PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 7.4.33. in /var/www/pixelfed/vendor/composer/platform_check.php on line 24
> ```
> 
> then I switched to php 8.2 via:
> 
> ```
> update-alternatives --set php /usr/bin/php8.2 
> update-alternatives: using /usr/bin/php8.2 to provide /usr/bin/php (php) in manual mode
> ```
> 
> and then it worked:
> 
> ```
> php artisan config:cache
> 
>    INFO  Configuration cached successfully.  
> 
> php artisan route:cache
> 
>    INFO  Routes cached successfully.  
> ```
> 
> However, the issue still persists. The same error message in a different form though:
> 
> ![pixelfed error](https://user-images.githubusercontent.com/69819346/243350493-43232777-349f-4cc8-9235-76158abb1ec2.jpg)

Well ! If you want to send email without smtp you have to set `MAIL_DRIVER` to `sendmail` ... This is the problem

**Comment by mitexleo** [comment]
Although I would recommend you to use a smtp service like Sendinblue. They have free plan.

**Comment by aarontrom** [comment]
> Well ! If you want to send email without smtp you have to set `MAIL_DRIVER` to `sendmail` ... This is the problem

That worked! Thanks a lot for that :) 

Why would you recommend to use a smtp service like Sendinblue?

**Comment by mitexleo** [comment]
> > Well ! If you want to send email without smtp you have to set `MAIL_DRIVER` to `sendmail` ... This is the problem
> 
> That worked! Thanks a lot for that :)
> 
> Why would you recommend to use a smtp service like Sendinblue?

Because of email deliverability. In many cases if you use `sendmail` the email will go to spam folder. That's something you won't like.
