### ISSUE TITLE
Line breaks are being ignored

### ISSUE THREAD

**Issue by SteveDinn** [pixelfed/pixelfed#4458]
I wrote a description of three paragraphs, separated by blank lines. The photo is irrelevant. It looks as though multi-paragraph posts used to have `<br>` tags between the paragraphs. Recent builds do not do this.

In my web client, it displays as one block of text.
![image](https://github.com/pixelfed/pixelfed/assets/3911507/b662c021-085d-4af8-aff2-20a29135ac74)

In the mastodon web client where I follow my pixelfed account, it shows normally.
![image](https://github.com/pixelfed/pixelfed/assets/3911507/4a181e5a-2d91-49d0-b16b-85dff621fb3f)

**Comment by SteveDinn** [comment]
Upon editing, it seems to fix itself. I'm very confused.
![image](https://github.com/pixelfed/pixelfed/assets/3911507/9f65c11d-f747-4cf6-bb6b-3255f9ba4fd7)

**Comment by jim-easterbrook** [comment]
This sounds similar to the bug #3731. Try clicking "like", then "unlike" on your post and then reload the page.

**Comment by trwnh** [comment]
Duplicate of #3909
