### ISSUE TITLE
[tusky] Notifications in 22 broken with current pixelfed(.social)

### ISSUE THREAD

**Issue by kr428** [pixelfed/pixelfed#4461]
Related to https://github.com/tuskyapp/Tusky/issues/3580 ; now Tusky v22 is deemed "stable" and this issue is still a problem in there, essentially rendering Tusky not really usable with pixelfed anymore. Problem apparently is that pixelfeds way of delivering notifications doesn't (completely/correctly/whatever) implement the Mastodon API so these things aren't compatible at the moment. Results: Having tusky connected to pixelfed,

- recent notifications often appear multiple times when refreshing;
- at some point, refreshing notifications doesn't work anymore at all, ending just with "an error has occured".

Any idea to fix this?

**Comment by sandervankasteel** [comment]
@dansup do you want to get this fixed at Pixelsfed end? Because I am more than happy to pick this up.
