### ISSUE TITLE
[Frontend] Fix webpack config, and ship missing vue components

### ISSUE THREAD

**Issue by lol768** [pixelfed/pixelfed#4464]
`spa.js` is an opaque minified blob; the code required to build it has not been in the repository [for over a year](#3434)

Is this an open source project or not?

**Comment by dansup** [comment]
Nope, I just merged some code a few hours ago.

**Comment by lol768** [comment]
With respect, you've not answered my question @dansup.

**Comment by dansup** [comment]
@lol768 When I replied, there was no comment body, you just edited that.

The webpack config is broken, and I've been meaning to fix it for some time. I'll try to get to it this weekend.

**Comment by lol768** [comment]
> @lol768 When I replied, there was no comment body, you just edited that.

I had the Ctrl key held down when I was trying to insert a line-break; GitHub was kind enough to create an empty issue for me! I didn't expect a response in under 30s.

> The webpack config is broken, and I've been meaning to fix it for some time. I'll try to get to it this weekend.

If the webpack config was merely broken, I'd expect to be able to find the sources that get compiled into e.g. the view that powers `https://pixelfed.social/i/web/hashtag/XYZ` - but I am having real trouble finding the file that's responsible for this when I search for [strings I'd expect to find](https://github.com/search?q=repo%3Apixelfed%2Fpixelfed+hashtag-feed&type=code&l=Vue). It seems to me that the actual sources are entirely missing.

Perhaps I'm missing something.

**Comment by dansup** [comment]
@lol768 There are a few missing vue components, and a few files like `resources/assets/js/spa.js` besides the broken config. Like I mentioned, I will clean them up and release them when I have a moment.

**Comment by dansup** [comment]
Fixed in #4465

**Comment by lol768** [comment]
Many thanks for sorting

**Comment by dansup** [comment]
Now merged!
