### ISSUE TITLE
What to need for moving between servers (full backup)

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#4469]
Hey everyone,

I was wondering what I really do need when moving, for example, from one VPS to the other. How does the process look like?

Dump the database? ZIP the "pixelfed"-folder and move everything to the new (prepared) VPS, re-importing the whole stuff then?

Is there any equivalent to the "php artisan backup:run"-command that re-imports the backup which, in my eyes, consists of the whole "pixelfed"-folder and the DB-dump or is there any alternative to re-importing the backup in this use case?

Thanks for your input!

Cheers,

Oliver

**Comment by mitexleo** [comment]
I first setup pixelfed on the new server. Then just dump the db and import it into the new server.. That's it ! 
If you're not using s3 storage (You should! You can migrate local media to s3 easily with builtin command.) you'll have to use the backup tool. 

There is no equivalent to "php artisan backup:run" for restoring pixelfed as far as I know. 

You'll have to do it manually.

**Comment by ghost** [comment]
Yeah, I am with S3 (we got to know each other due to a thread here) but the .env-file should be copied over before going all in again I think?

Thanks for your input!

**Comment by mitexleo** [comment]
> Yeah, I am with S3 (we got to know each other due to a thread here) but the .env-file should be copied over before going all in again I think?
> 
> Thanks for your input!

It's upto you ! If you don't copy it you'll have to read the docs and set everything again :)

**Comment by ghost** [comment]
> > Yeah, I am with S3 (we got to know each other due to a thread here) but the .env-file should be copied over before going all in again I think?
> 
> > 
> 
> > Thanks for your input!
> 
> 
> 
> It's upto you ! If you don't copy it you'll have to read the docs and set everything again :)

Just mentioned this as you have missed to enumerate it - and as this file holds many (if not all) basic infos to the instance I thought I'd better ask to clarify 😄

**Comment by ghost** [comment]
Okay, I just went to the new machine, installed all dependencies and imported the TARed pixelfed-directory and the SQL-dump - recreated the services and NGINX-configuration afterwards and made my first move of a Pixelfed-instance with S3-storage attached. Worked, therefore closing this!

**Comment by mitexleo** [comment]
Wow 🥰 ... Glad to hear that.
