### ISSUE TITLE
Pixelfed request / suggestion

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#4474]
1-  the story flow seems to be fast

2 - Will the Android app me be on google play by the time?

3 - pixelfed.social and app where is the translation address?

4 - " .svg " I want to add my works. I hope this feature will come to Pixelfed in the future.
PSD, AI, SVG , MPEG, MOV, AVI ,MP3 , WAV, AAC,FLAC, AIF and M4A  will he support it ?

**Comment by lipupini** [comment]
What other image gallery web app allows uploading PSD and AI files for web display?
