### ISSUE TITLE
[Instagram Import] Cyrilic support

### ISSUE THREAD

**Issue by rpavelu** [pixelfed/pixelfed#4476]
I was talking about it in Mastodon but gonna mention here too just for visibility
There is a problem with cyrilic description on photos

![Picture](https://github.com/pixelfed/pixelfed/assets/5406013/b715c2ee-36b0-4a13-922e-27015bfa9849)

**Comment by unsolaci** [comment]
Could you provide the `title` value for this post as it stands in the `posts.json` file from the Instagram export?

I think I may facing a similar issue, but with different Unicode characters (non-cyrillic) in #4479.

**Comment by paulexyz** [comment]
should be fixed by https://github.com/pixelfed/pixelfed/pull/4726
