### ISSUE TITLE
Pronouns selection is confusing

### ISSUE THREAD

**Issue by orowith2os** [pixelfed/pixelfed#4489]
I'm fairly new to Pixelfed (coming from Mastodon, a user for 6 months) and overall I'd say the whole UX is inconsistent and confusing to use.

I hope to get to all of my complaints in separate issues, but my first one that I'd like to put a priority on is pronouns selection.

I'd argue this falls under "accessibility" too.

## Selecting pronouns

I have to click and drag in order to select pronouns, which is *not* very easy to use and understand, and some sets of pronouns are completely spread out from each other. 

I'd much prefer it if the pronouns selection was just a text box. Attempting to accommodate all of the potential sets of pronouns can be annoying, and not everyone is the same. 

Additionally, what if someone wants to put "any/all", "throw a dart", or something along those lines? That's impossible with the current setup.

## Federation

The pronouns also aren't shown on non-Pixelfed servers; IMO, this should be fixed. There's probably no official standard for this in ActivityPub, so it's a bit iffy in the first place. 

I'd prefer it to be put into a Pronouns field (table, or "profile metadata" as Mastodon calls it) and Pixelfed automatically adapts that. It's not a perfect solution, but it would work.

## Alternative solution

Just put it into the bio. This is what many do on other fediverse servers. They also might put pronouns in their tables on their profile, which Pixelfed *does not* show; that's a major issue.

**Comment by orowith2os** [comment]
It appears some features of Mastodon aren't in the official ActivityPub protocol, so I guess this issue makes sense? I wonder if there's some way to upstream these changes, or if it's already been attempted.

**Comment by x64x2** [comment]
I don't think pronoun selection is necessary
