### ISSUE TITLE
PNG: Transparent Background = Corrupted Pictures

### ISSUE THREAD

**Issue by nikhiljha** [pixelfed/pixelfed#45]
This is what I uploaded:

![gccthonk](https://user-images.githubusercontent.com/2773700/40822923-34175966-6523-11e8-9b12-9bc6f917af41.png)

This is what I got:

https://pixelfed.social/p/njha/3

**Comment by kpcyrd** [comment]
The file is stored as jpg, which doesn't support transparency. We would need to fill the background with a color.

**Comment by nikhiljha** [comment]
Mabye too late, but it might be better to store pictures as png. Most image hosting websites I've used do this, and in general I think pngs have a better file size/quality ratio.

**Comment by dansup** [comment]
Fixed in b437b62
