### ISSUE TITLE
Change post status from unlisted to listed

### ISSUE THREAD

**Issue by Morse6690** [pixelfed/pixelfed#4506]
I have imported some posts from IG, I guess 11% is better than none at all. These all show as unlisted, with the unlocked padlock icon above each one. 

Is there a way to edit a post and make it listed or unlisted at a later time?

**Comment by ghost** [comment]
I've got the same issue here and don't find any option to list them in the timeline - is that intentional?

**Comment by paulexyz** [comment]
Same issue as in #4610 - unlisted is an admin/moderation feature which does not seem to be intended to be set by the user. Underlying issue explained here: https://github.com/pixelfed/pixelfed/issues/4610#issuecomment-1789823108
