### ISSUE TITLE
Multiple 500 Errors

### ISSUE THREAD

**Issue by YourSandwich** [pixelfed/pixelfed#4511]
Hello, this is probably not an issue related to Pixelfed itself, but PHP.
I have just updated the ArchLinux AUR package of Pixelfed -> [https://aur.archlinux.org/packages/pixelfed](https://aur.archlinux.org/packages/pixelfed)

I have successfully deployed the Webpage -> [pixel.archworks.co](pixel.archworks.co), the federation works I am able to see the posts from mastodon.

Now they are multiple issues that I think are related to following PHP extensions missing, and I just want to confirm this.

The following PHP extensions are missing on my ArchLinux system:

- mbstring
- tokenizer
- ctype
- xml

1. Profile
     when opening my profile over here:
     
![image](https://github.com/pixelfed/pixelfed/assets/20018243/454169b2-70e7-43ca-8e0c-7639a19d451f)
I'll get the following error:
```
Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (vendor.js?id=84983046cff65e2066e3ab11c5a3db14:2:83455)
    at e.exports (vendor.js?id=84983046cff65e2066e3ab11c5a3db14:2:85878)
    at XMLHttpRequest.y (vendor.js?id=84983046cff65e2066e3ab11c5a3db14:2:78775)
```
Opening the Profile with the Profile Icon just works.

2. Searching for People in the Fediverse does not work
3. Enabling the Mobile API, does not work, and I am unable to get the debug log from this issue.
4. Opening My Portfolio also gives me an Error:
```
Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (vendor.js?id=84983046cff65e2066e3ab11c5a3db14:2:83455)
    at e.exports (vendor.js?id=84983046cff65e2066e3ab11c5a3db14:2:85878)
    at XMLHttpRequest.y (vendor.js?id=84983046cff65e2066e3ab11c5a3db14:2:78775)
```

## Setup
System: ArchLinux (latest 28.06.2023)
Pixelfed: 0.11.8
Composer: 2.5.8
PHP: 8.2.7
PHP-FPM: 8.2.7
Nginx: 1.24.0
Postgres: 15.3

Enabled PHP Extension:
extension=bcmath
extension=curl
extension=exif
extension=gd
extension=iconv
extension=intl
extension=pdo_pgsql
extension=sodium

### Internal
```
server {
    listen 80;
    server_name pixel.archworks.co;                    
    root /usr/share/webapps/pixelfed/public;

    error_log /var/log/nginx/pixel.archworks.co-error.log;
    access_log /var/log/nginx/pixel.archworks.co-access.log combined;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass    unix:/run/php-fpm/php-fpm.sock;
        fastcgi_param   SCRIPT_FILENAME     $realpath_root$fastcgi_script_name;
        fastcgi_param   QUERY_STRING        $query_string;
        fastcgi_param   REQUEST_METHOD      $request_method;
        fastcgi_param   CONTENT_TYPE        $content_type;
        fastcgi_param   CONTENT_LENGTH      $content_length;
        fastcgi_param   SCRIPT_NAME         $fastcgi_script_name;
        fastcgi_param   REQUEST_URI         $request_uri;
        fastcgi_param   DOCUMENT_URI        $document_uri;
        fastcgi_param   DOCUMENT_ROOT       $document_root;
        fastcgi_param   SERVER_PROTOCOL     $server_protocol;
        fastcgi_param   GATEWAY_INTERFACE   CGI/1.1;
        fastcgi_param   SERVER_SOFTWARE     nginx/$nginx_version;
        fastcgi_param   REMOTE_ADDR         $remote_addr;
        fastcgi_param   REMOTE_PORT         $remote_port;
        fastcgi_param   SERVER_ADDR         $server_addr;
        fastcgi_param   SERVER_PORT         $server_port;
        fastcgi_param   SERVER_NAME         $server_name;
        fastcgi_param   HTTPS               $https if_not_empty;
        fastcgi_param   REDIRECT_STATUS     200;
        fastcgi_param   HTTP_PROXY          "";
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
```
### External 
```
server {
    listen 443 ssl;
    server_name pixel.archworks.co;

    ssl_certificate /super/secret/path;
    ssl_certificate_key /super/secret/path;

    error_log /var/log/nginx/pixel.archworks.co-error.log;
    access_log /var/log/nginx/pixel.archworks.co-access.log combined;

    location / {
        proxy_pass http://pixel;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto "https";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_redirect off;
    }
}

```

**Comment by YourSandwich** [comment]
Please let me know if any information is missing, I really would like to provide the People from the Arch community with a simple installation method of Pixelfed for people that do not want to use your docker image.

**Comment by mitexleo** [comment]
Why you're not installing those extensions? They're required.

**Comment by YourSandwich** [comment]
They are not available in the ArchLinux repository, unfortunately :(
I was wondering that the WebUI works at all without them.

So if these issues are clearly because of these extensions, then I can close the Issue. Just wanted to make sure because some of the errors were suspicious.

I am aware that ArchLinux is officially not supported, of course.

**Comment by YourSandwich** [comment]
Not a Pixelfed Issue
