### ISSUE TITLE
Can't build with docker compose

### ISSUE THREAD

**Issue by tassoman** [pixelfed/pixelfed#4517]
> Error response from daemon: manifest for pixelfed/pixelfed:latest not found: manifest unknown: manifest unknown

Just hangs, before pulling, should I pull an explicit version?

**Comment by daemionfox** [comment]
Having the same issue, looking for a workaround.

**Comment by JuanjoSalvador** [comment]
Does this happen when you're trying to pull the image?

**Comment by maxime1992** [comment]
@JuanjoSalvador just try it yourself

```
docker pull pixelfed/pixelfed
```

```
docker pull pixelfed/pixelfed                                           ✔
Using default tag: latest
Error response from daemon: manifest for pixelfed/pixelfed:latest not found: manifest unknown: manifest unknown
```

**Comment by JuanjoSalvador** [comment]
Also there is no tags on Dockerhub. So I guess the workaround for this could be mapping the source into a volume and starting it using any Nginx and PHP docker image.

**Comment by schlenger** [comment]
Any news here? This error still occurs with the current version

**Comment by tassoman** [comment]
In my opinion, the project shouldn't rely to an image but have a **Dockerfile** itself. Then the _docker-compose.yml_ should bring up a locally built image by git sources.  
The difficult part comes on detection of "first smoke test" boot, or "upgrade" boot, and finally regular boot. Then apply needed commands sequences.

**Comment by deimjons** [comment]
docker hub just heven't image, who own dockerhub account? pls just build and load there image. 
https://hub.docker.com/r/pixelfed/pixelfed
