### ISSUE TITLE
Github discussions

### ISSUE THREAD

**Issue by tassoman** [pixelfed/pixelfed#4529]
Maybe it's useful to enable Github Discussions to avoid bloating issues with support requests?  
I guess community of users can mutually help each other.

**Comment by x64x2** [comment]
Interested

**Comment by trwnh** [comment]
we have https://github.com/pixelfed/support which is maybe not advertised very well and could possibly be replaced by discussions, yes

**Comment by drallgood** [comment]
I think this is done, right?

**Comment by tassoman** [comment]
it's an answer but not a solution
