### ISSUE TITLE
Feature Request - Select our on #'s on Discovery tab

### ISSUE THREAD

**Issue by RiversideBryan** [pixelfed/pixelfed#4534]
I'm not certain what determines which hashtags automatically populate the tab for "Discovery." The do change from day tp day, so perhaps trending hashtags?
At any rate, please allow us to pick which hashtags appear here.
It is often full of memes,  image-not-available, and sometimes even NSFW that has not been flagged. 
Numerous times I have visited this tab to find nudity not hidden under the #gay category. 

![Screenshot_20230711_042350_Pixelfed](https://github.com/pixelfed/pixelfed/assets/137232062/3cbaf5a6-e173-4fe5-97fe-b95a4d9b373f)

Preferably we chose which hashtags appear on this tab, OR give us ability to hide mute the ones we do not wish to see.

**Comment by binarydigit404** [comment]
Yes this! I would like the ability to block hashtags. The Discover/trending section has tons of super NSFW that I don't want to see on my feed.
