### ISSUE TITLE
Verification badge / icon / whatever

### ISSUE THREAD

**Issue by RustoMCSpit** [pixelfed/pixelfed#4536]
Pitch
A central body ran by the Pixelfed non-profit that verifies users. Due to the de-centralised nature of Pixelfed the recognition of this authority would be opt-in per user / per server and if opt'd-out a user would not see verification badges given by the non-profit. As well as that, all verifications should be shown on the website in a downloadable a dynamic CSV file showing what body / person is being verified under what account (usernames change, maybe a different ID). Also, there should be a feature that would allow other people to make their own verification bodies in which people can opt-in to with their own badges, you could hypothetically opt-in to different multiple authorities at once.

Motivation
Safety of users, prevention of misinformation, makes famous people more comfortable to join the platform

**Comment by RustoMCSpit** [comment]
Pretty much copy pasted from my Mastodon issue

**Comment by FrittenLoverMarvin** [comment]
> Pretty much copy pasted from my Mastodon issue

Do you mean something like the [verification on Mastodon](https://joinmastodon.org/verification)?

**Comment by hayo** [comment]
yeah. let's not.
