### ISSUE TITLE
Support for stories

### ISSUE THREAD

**Issue by HatakeKakashri** [pixelfed/pixelfed#4543]
Any plans to add a feature like stories.

**Comment by mitexleo** [comment]
Stories are already supported.

**Comment by shbhmnk** [comment]
@neonota Thanks, I was not aware of stories support in Pixelfed. I had searched the docs and issues list but did not find anything related. Could you point out to the issue/PR/doc which describe how to use stories in Pixelfed.

**Comment by HatakeKakashri** [comment]
@neonota I had searched the docs, issues and PR list before creating this issue but did not find anything related. Could you point out the issue/PR/doc which describes how to use stories in Pixelfed.

CC: @dansup

**Comment by blacklightpy** [comment]
> Stories are already supported.

Not yet in the app
