### ISSUE TITLE
419 Page Expired

### ISSUE THREAD

**Issue by grahhnt** [pixelfed/pixelfed#4556]
If you get this error message when logging in on a fresh installation, clear all cookies stored for the domain Pixelfed is installed on

I ran into this when reinstalling Pixelfed on the same domain and was fixed by clearing the cookies for the domain

**Comment by grahhnt** [comment]
This issue is intended to help with search results relating to "419 page expired Pixelfed"

**Comment by gautam1ghosh** [comment]
I get this error as well, but cannot fix it by clearing the cookies. 

Login doesn't work for me. After submitting the login info on the login page and pressing submit, it just returns back to the login page without any error message (and clearly not logged in). So I am unable to get logged in and using Pixelfed.
See #4588

**Comment by x64x2** [comment]
Hehe this error message is quite funny you know considering the racist meaning it has in some countries.
