### ISSUE TITLE
(Feature request) Import photos from any existing Mastodon instance post, OR set a new Pixelfed post specific date/time

### ISSUE THREAD

**Issue by edel79** [pixelfed/pixelfed#4559]
Hello, 

I would like to transfert some posts from a general purpose Mastodon instance and account to a photo-specific Pixelfed instance and account. 

Doing this manually as new posts will loose the original post's date and time, but I would like it to be preserved. Unless it is possible to edit the date of the post, but I don't think it is.

Thanks !

**Comment by mgrzeca** [comment]
Being able to manually set the date of a post is a highly useful feature for photographers running photo journals or 365 projects. In my case, it often happened that I took pictures every day for several days, but I only had time to transfer the photos from the camera, edit them, and upload them to Pixelfeed on Saturdays or Sundays. In such situations, having the option to set the date for each post would be extremely helpful.

**Comment by Murazaki** [comment]
> Being able to manually set the date of a post is a highly useful feature for photographers running photo journals or 365 projects. In my case, it often happened that I took pictures every day for several days, but I only had time to transfer the photos from the camera, edit them, and upload them to Pixelfeed on Saturdays or Sundays. In such situations, having the option to set the date for each post would be extremely helpful.

I would prefer that Pixelfed gives the possibility to read EXIF to extract the usable date and give the choice between the two (or maybe the day of import in case you don't want to import those dates) rather than give the possibility to write a new one. It would push people to avoid lying on that, even though you can modify your EXIF with proper tools.
