### ISSUE TITLE
Remove old remote Media

### ISSUE THREAD

**Issue by samuel-p** [pixelfed/pixelfed#4571]
I just wondered if there are some media cleanup jobs for Pixelfed to save storage. Like Mastodon has `tootctl media remove --days 3` to remove remote media older than 3 days for example. If anyone requests an old post, the media is fetched again (see https://docs.joinmastodon.org/admin/tootctl/#media-remove). Is there anything similar to Pixelfed?

As I saw Pixelfed has `media:gc`, which seems kind of similar to Mastodons `tootctl media remove-orphans`.

**Comment by daSmirnov** [comment]
AFAIK Pixelfed doesn't cache any remote media?

**Comment by daSmirnov** [comment]
AFAIK Pixelfed doesn't cache any remote media (aside from avatars)?

**Comment by justdaj** [comment]
> AFAIK Pixelfed doesn't cache any remote media (aside from avatars)?

My understanding too

**Comment by escuco** [comment]
Is there a safe way to clean up the avatar cache?
My instance has more than 8 GB cache in /storage/app/public/cache/avatars.

**Comment by escuco** [comment]
Maybe @dansup can answer this. 

Is it safe, to delete /storage/app/public/cache/avatars or does another way exists to purge the cached avatar content?

@justdaj @daSmirnov @samuel-p

**Comment by dansup** [comment]
Fixed in #4694
