### ISSUE TITLE
Ngrok Connection in Pixelfed

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#4577]
I am trying to connect to my local pixelfed by using ngrok. I set up my Pixelfed and it works perfectly on local, but when i connect it to my ngrok instance, https://0c7a-39-117-170-126.ngrok-free.app, it gives a 404 error. What is the cause and how do i fix it?

**Comment by dansup** [comment]
Set `APP_DOMAIN="0c7a-39-117-170-126.ngrok-free.app"` in `.env` and run `php artisan config:cache && php artisan cache:clear`
