### ISSUE TITLE
Following count failing to be updated

### ISSUE THREAD

**Issue by Anselmo21** [pixelfed/pixelfed#4581]
Steps to reproduce:
1. Go to any one's profile that's not yours.
2. Press follow button.
3. Then immediately press back button on your browser.
4. Notice that your following count does not move

Note: I tested these same actions in Facebook and Instagram. In both cases, the following count has increased.

**Comment by HermanRonk** [comment]
![1](https://github.com/pixelfed/pixelfed/assets/2781343/2fcd319a-ff40-4f22-8cee-33a8bb481189)
![2](https://github.com/pixelfed/pixelfed/assets/2781343/239e50d5-464a-451f-8e8e-68fdc72ace46)
![3](https://github.com/pixelfed/pixelfed/assets/2781343/83abd2d3-5580-440a-9e82-d941848658ad)


I can confirm that this happens, The following list is updated as it should, only the counter stays at 0 in all places it shows.

running the 0.11.8 pixelfed version

**Comment by eobet** [comment]
I can’t even see the following count updated when I press refresh on my profile.

however, when I got to that same user’s page, it still says “unfollow”.

(Tangent issue, I don’t see any of their posts after logging in either. They have 11 posts on their server, but when viewed from pixelfed.social it appears as 0.)

**Comment by MikeHuntington** [comment]
The latest version of PixelFed 0.11.9, The following number stays at zero.. no matter how many people I'm following. The same issue that @HermanRonk has.

**Comment by krees000** [comment]
Reporting the exact same issue.
I managed to decrease the count to -1 on a newly spinned instance by following, unfollowing and refreshing. It eventually goes back to 0. It does not get to 1.

Tried on 0.11.9 and also on the dev branch, same situation in both.

I noted that querying the database through php artisan tinker returns also incorrect number of following on the user.

**Comment by gerardkieffer** [comment]
Same issue here, running Pixelfed with Cloudron. 
My profile shows "0 following" but when I click on it, I see all the people aI'm actually following.
Just updated to 0.12.0 yesterday, issue persists.
