### ISSUE TITLE
pixelfed.social: No login via tor (browser)?

### ISSUE THREAD

**Issue by kr428** [pixelfed/pixelfed#4589]
In some environments I'm trying to connect to pixelfed.social using Tor Browser. In there, I can't log in with this message, and there seems no way around it:

![image](https://github.com/pixelfed/pixelfed/assets/685879/e48dabc9-2ec6-46fa-a4ca-b82f912f856a)

Is this a known problem? Could this be caused by pixelfed.social hiding behind Cloudflare? Is there any way to fix this?

**Comment by x64x2** [comment]
Just use a normal browser like everyone else does

**Comment by kr428** [comment]
> Just use a normal browser like everyone else does

Hmmm... interesting response. There are valid reasons to use Tor, and pixelfed.social is one of the few services that doesn't work with it (and the only one I know in the Fediverse).

**Comment by mitexleo** [comment]
> In some environments I'm trying to connect to pixelfed.social using Tor Browser. In there, I can't log in with this message, and there seems no way around it:
> 
> ![image](https://user-images.githubusercontent.com/685879/260648752-e48dabc9-2ec6-46fa-a4ca-b82f912f856a.png)
> 
> Is this a known problem? Could this be caused by pixelfed.social hiding behind Cloudflare? Is there any way to fix this?

It's probably because of Cloudflare. Pixelfed software itself doesn't have this kind of restrictions AFAIK. You should join another server !

**Comment by kr428** [comment]
Anything changed here? Because apparently this isn't a problem anymore as of today...
