### ISSUE TITLE
incomplete federation, can't be followed

### ISSUE THREAD

**Issue by tassoman** [pixelfed/pixelfed#4592]
When a remote account tries to follow my local pixelfed account, nothing happens.  
Remote account still's into "limbo" (Waiting) but can't get answer.  
I can see the request inside Horizon, but no reply goes to remote server.

If I follow remote accounts, their posts appear into global timeline. This is working.  
Just outside-in actions are missing.

Local follow requests are ok.

**Comment by tassoman** [comment]
I've updated at 0.11.9 but still can't get activities from remote servers.  
Any hint on how to troubleshoot?

**Comment by thanius** [comment]
+1 here. Can't be followed from outside of Pixelfed, as well as search for tags that haven't been included on people I follow making discovery hard outside the main instance.

**Comment by wac-** [comment]
+1. Also seeing that follows from another server look to just disappear. Outside server shows "follow requested" state, but user doesn't require approval on follows. No failed tasks in horizon, no 500s in the request log, no errors that I've been able to find.
