### ISSUE TITLE
Feature Request: Double-click to like

### ISSUE THREAD

**Issue by magicmarcy** [pixelfed/pixelfed#4604]
The most feature I use on IG is the "double-click to like" feature and it would be great if we can get that on Pixelfed. 

EDIT:
It's worth noting that this feature only works on IG when you double-click images, not videos. It would be nice if it worked on videos as well, but I don't think it's a must.

**Comment by JuanjoSalvador** [comment]
This feature is on the way for v0.12.0 since 2020, I guess there should be some kind of WIP version or PR at this point.
