### ISSUE TITLE
Bug: No image in single view of post after search

### ISSUE THREAD

**Issue by magicmarcy** [pixelfed/pixelfed#4605]
I am using pixelfed.social and the error occurs when e.g. entering a hashtag via the search function. As a result, I get a grid view of images tagged with this hashtag. If I now click on an image, only the post appears without an image - i.e. only the text portion in a single view.
If I now reload the page via F5, the image appears. This happens on both Firefox and Chrome

OS: Windows
Browser: Firefox 116.0.3 / Chrome 116.0.5845.97

Hashtag search:
![hashtag_search](https://github.com/pixelfed/pixelfed/assets/93079125/c05fb006-424e-4a3b-a068-412993ccebaf)

Single view:
![single_view](https://github.com/pixelfed/pixelfed/assets/93079125/7d57fd02-bf72-4700-bc33-fbfcba3a5699)

Single view after pressing F5:
![single_view_after_f5](https://github.com/pixelfed/pixelfed/assets/93079125/6587959d-f99e-4e7a-b19d-d286cbca8a35)

**Comment by escuco** [comment]
Same here, Pixelfed v0.11.8 and now also with v0.11.9.

**Comment by mitexleo** [comment]
Same here on my instance.

**Comment by d1gg** [comment]
Same on my instance and pixelfed.social.

**Comment by mamarguerat** [comment]
Same on my instance and pixelfed.social, reported in #4386

**Comment by xundeenergie** [comment]
Same here on japix.schuerz.at

**Comment by escuco** [comment]
The bug exists still on Pixelfed v0.11.13.

**Comment by xundeenergie** [comment]
It seems, this problem is solved after the update (devel) today...

**Comment by escuco** [comment]
Yes, it works now after the latest update 🚀

**Comment by magicmarcy** [comment]
Yeah, seems the issue is fixed but can't find a related issue to tag here. Anyway I'm happy with that ;-)
