### ISSUE TITLE
support muting or blocking based on hashtags

### ISSUE THREAD

**Issue by piebob** [pixelfed/pixelfed#4607]
i'd like to be able to mute or block specific hashtags, such as those designating AI-generated content.

**Comment by CarlFink** [comment]
Second the motion. There are topics I just don't want to see. For me personally, say #Bookbinding photos are uninteresting. I'd like to not have to skip past them.

**Comment by CarlFink** [comment]
Second the motion. There are topics I just don't want to see. For me personally, say #Bookbinding photos are uninteresting. I'd like to not have to skip past them. While I'm at it, you could get part of the effect by just revealing the hashtags of a "sensitive content" image, so if it's #StuffYouDontLike image I could just not reveal it. 99% of Pixelfed "sensitive" images don't tell you **why** it is so sensitive (unlike Mastodon, where they usually have actual explanations).
