### ISSUE TITLE
Explore on the landing page is not working

### ISSUE THREAD

**Issue by MFYDev** [pixelfed/pixelfed#4626]
Hello there,

I am using php-8.2 with MySQL 8

I did everything correctly according to the general installation instructions.

I found everytime I cannot delete any post after the fresh install

<img width="614" alt="image" src="https://github.com/pixelfed/pixelfed/assets/53750381/8706a25f-cc38-4c42-8e86-1851ada71043">

And also for landing page /api/pixelfed/v2/discover/posts/trending?range=daily will always be 403 error

I have done multiple reinstallations and everytime they are the same.

**Comment by eruraindil** [comment]
To fix the explore page, set INSTANCE_DISCOVER_PUBLIC true in your env file
