### ISSUE TITLE
Allow adding metadata to profile

### ISSUE THREAD

**Issue by schneekluth** [pixelfed/pixelfed#463]
I'd love to see the ability to add some metadata to pixelfeds profile like Mastodon does e.g. adding a link to your Mastodon account or Twitter etc. Right now you have to type it into your bio.

**Comment by 0verk1ll** [comment]
Mastodon has a feature like this. https://docs.joinmastodon.org/usage/basics/#profile-metadata
Since the fields are user-defined, it is very flexible and can be used to share any information the user deems pertinent.

**Comment by maznu** [comment]
Given the prevalence of image theft from social media — it happens time and time again, deliberately, by news organisations which should know better — I can see a "licensing information" or "copyright" type field being used by a lot of pros as they consider moving to the fediverse.

**Comment by DamienSirkis** [comment]
One type of metadata that I would love to see added too is an easy way to embed a a mastodon verification link into your homepage, as in like `<a rel="me" href="https://djs.social/@damien">Mastodon</a>`.

You could have a field in your profile enabling you to input the mastodons site (maybe even make sure the user is authorized to log into the site) and this would generate the embedded code when the profile page loads up.

Of course this would be invisible to someone browsing the page but it would allow mastodon profiles to get the verification checkmark on the pixel fed link in their profiles.

**Comment by trwnh** [comment]
The way this is handled in Mastodon's ActivityPub representation is to use an `attachment` array of type `PropertyValue` from the schema.org vocabulary instead of the Activity Vocab spec: https://mastodon.social/@trwnh.json

**Comment by dansup** [comment]
We do not plan on adding meta fields to pixelfed. You can add that information to your bio or website field.

**Comment by trwnh** [comment]
Website is currently not included in actor JSON but for some reason it does include the schema.org PropertyValue in its json-ld context.
