### ISSUE TITLE
Security issue when login in android app with 2FA

### ISSUE THREAD

**Issue by mokazemi** [pixelfed/pixelfed#4633]
When you have 2-factor authentication enabled and then try to login in the app, it doesn't ask for the code.

**Steps to reproduce:**

1. Open the android apl and tap login
2. The browser window opens. Enter username and password
3. It log in in the app but doesn't ask for security code
4. When you open browser window, it asks for code but even without it, the app login is successful

**Comment by ashkaijin** [comment]
I've previously submitted an issue regarding this too
And this applies to any third party Pixelfed app as well
https://github.com/pixelfed/pixelfed/issues/4551

**Comment by drallgood** [comment]
@dansup We should probably have a look at this. might have security implications

**Comment by trwnh** [comment]
Duplicate of #3328

**Comment by eonlineok** [comment]
Hi all =).
I tested with `https://play.google.com/store/apps/details?id=com.pixelfed&hl=en-US` and have the same issue.

All the best.
