### ISSUE TITLE
Upload Photo > Should not have access to the videos in camera roll 

### ISSUE THREAD

**Issue by Sepideh-farsi** [pixelfed/pixelfed#4647]
Kindly notice this:

**Test Data**

Device: iPhone XR
Server: [OnePicADay!](https://onepicaday.com/)

**Action Taken**

- Navigate to Create post
- Click on Upload button
- Assert the access to the camera roll

**Result**

For better UX when user wants to upload photo and he is only allowed to upload photo not videos, he should not have access to the videos in camera roll in first place to avoid getting an error on next step.
Please find the attachments

Thank you
Cheers

![image](https://github.com/pixelfed/pixelfed/assets/111892438/45ddd17b-b15f-42be-a783-d66c4e38700d)
![image](https://github.com/pixelfed/pixelfed/assets/111892438/8026741a-367d-4c06-8798-f78621066cad)

**Comment by groovenectar** [comment]
Here is reference on this:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers

`<input type="file" accept="image/jpeg,image/png,image/gif" />`

But it's going to have to use something like `explode()` to generate the list of enabled types
