### ISSUE TITLE
New post: German umlaut ü is malformed when emoji is present

### ISSUE THREAD

**Issue by realpixelcode** [pixelfed/pixelfed#4651]
Original input in the draft window:

> Dieses Foto war übrigens mit ein Anlass, warum ich Pixelfed installiert habe. Danke noch einmal für den Tipp. ☺️

Output after posting:

> Dieses Foto war ü@übrigensmit ein Anlass, warum ich Pixelfed installiert habe. Danke noch einmal fü@ürden Tipp. ☺️

The issue only occurs when there is an emoji in the text. Then, `ü ` is wrongly displayed as `ü@ü` (trailing space removed).

When there is **_no_** emoji in the text, `ü` is displayed correctly.

Also, the line breaks disappear immediately after publishing a post (they re-appear after some time, like when there are newer posts in the home timeline).

---

This issue is a duplicate of #1847, which was wrongly closed. It should be re-opened, c.f. https://github.com/pixelfed/pixelfed/issues/1847#issuecomment-1584915863

Original author: @memo-567

**Comment by groovenectar** [comment]
I'd like to look into this with you

I tried editing a description, and also a comment with the same text: https://pix.dup.bz/p/dup/610422942198181889

This is v0.11.9. Does it only happen when creating a new post (in the description), and not when editing for you? Any idea what release version it is?

**Comment by realpixelcode** [comment]
The server I use currently runs v0.11.9, but the issue had already occurred before that. The malforming doesn't appear to occur reliably every time, but if it appears, it already appears directly after posting. Editing the post doesn't change anything.

**Comment by gahbla** [comment]
This issue occured with my Profile as well, e.g. with the following postings:

- https://pixelfed.de/p/pixelstreet/568164220217333675

- https://pixelfed.de/p/pixelstreet/568566825746599726

- https://pixelfed.de/p/pixelstreet/570721468840005740

- https://pixelfed.de/p/pixelstreet/571455147313738548

- https://pixelfed.de/p/pixelstreet/571779577506611795

- https://pixelfed.de/p/pixelstreet/572458591873076621

- https://pixelfed.de/p/pixelstreet/572826924908161640

For some reason, the following posts are not effected:

- https://pixelfed.de/p/pixelstreet/572530744117900567

- https://pixelfed.de/p/pixelstreet/567828569849076128

- https://pixelfed.de/p/pixelstreet/565705958710726629

- https://pixelfed.de/p/pixelstreet/565598481390749508

**Comment by groovenectar** [comment]
This issue seems to clearly be something intentional from the Instagram export, which can also potentially change again at any time. It gives more reason to be excited about migrating away from Instagram, though they are making sure the process could be some hassle

**Comment by groovenectar** [comment]
Would be neat if we come up with a sort of standardized import format

Then have a separate process to convert the Instagram export to that first

**Comment by verymilan** [comment]
I'd like to add that at least after removing the emoji in the post (not in the same line), the issue is still there. It is not happening in hashtags. It is also not an Instagram import in my case. It is also still present after trying to change and save again.

**Comment by gahbla** [comment]
> This issue seems to clearly be something intentional from the Instagram export

So just to be clear: I didn't import anything from Insta, the issue occured well before there was a Insta import feature.
