### ISSUE TITLE
Muted accounts still showing in home feed.

### ISSUE THREAD

**Issue by ArnonClark** [pixelfed/pixelfed#4652]
I've tried muting an account but it continues to show up in my home feed. Confirmed via apps and web-portal. Thanks for a terrific piece of software!

**Comment by okpierre** [comment]
Was submitted and waiting for approval/merge

If you want to give it a try see this
https://github.com/pixelfed/pixelfed/commit/99b8e418d7d3889374b9c25f743cee8457b9b7a5

@ArnonClark

**Comment by dansup** [comment]
Fixed in #4740

**Comment by ArnonClark** [comment]
Cool, thanks!
