### ISSUE TITLE
Feature Request ( Invite Code )

### ISSUE THREAD

**Issue by ThesiiNCey** [pixelfed/pixelfed#4653]
Invite code function

An invitation code that an administrator can set for the user

If a user wants to register, he needs a field (invitation code).

for a Server Without Federation

**Comment by dansup** [comment]
This already exists, you need to run `php artisan admin:invite` and follow the instructions!

![Screenshot 2023-09-17 at 6 26 32 PM](https://github.com/pixelfed/pixelfed/assets/877217/2a10d11e-3ebc-4745-97b5-c55c953adc5c)
