### ISSUE TITLE
Custom domain not "compatible" for Mastodon Login

### ISSUE THREAD

**Issue by dylanvaughn** [pixelfed/pixelfed#4658]
Hello - I'm trying to use the new "Login with Mastodon" feature:

https://github.com/pixelfed/pixelfed/pull/4545/files

I have dev mastodon and pixelfed sites setup to test this, and I can get my custom mastodon site to appear on the list:

![pixelfed-custom-mastodon-domain](https://github.com/pixelfed/pixelfed/assets/14910/ab54f99b-e6ff-4862-82ca-8bc0f6f2afa0)

but when I click on it I get an error:

![custom-mastodon-domain-error](https://github.com/pixelfed/pixelfed/assets/14910/d9a2b117-dfc9-40ec-a9b6-920683f75d8d)

Looking through the code it looks like it is getting marked as "not compatible" here:

https://github.com/pixelfed/pixelfed/blob/v0.11.9/app/Services/Account/RemoteAuthService.php#L124

which calls this:

https://beagle.pixelfed.net/api/v1/raa/domain?domain=mastodon.dev.coloradorewild.org

which returns:

```
{
"compatible": false
}
```

What is this beagle api call and how can I get this domain marked as compatible?

Thanks, Dylan

**Comment by dansup** [comment]
Looks like its showing as compatible now, we use https://fedidb.org for the beagle service.

For future reference, you can self-submit your instances to fedidb.org.
