### ISSUE TITLE
want delete my account & not know how

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [pixelfed/pixelfed#467]
want delete my account & not know how

**Comment by dansup** [comment]
Please contact your instance admin, the issue tracker is not the right place for this.

**Comment by poshaughnessy** [comment]
There should be an option in the settings to delete your account.

Also, for all of us on pixelfed.social, aren't you our instance admin? So you mean we should contact you in a different way to ask for our accounts to be deleted? How? Mastodon? I'll try sending you a message there...

**Comment by EsmailELBoBDev2** [comment]
@poshaughnessy what you exactly mean from your words because i didn't understand it (my main lang not EN :P) + i didn't find "delete" option in settings

**Comment by todoneunl** [comment]
There is not a delete option yet.

**Comment by trwnh** [comment]
The new issue for this is #655
