### ISSUE TITLE
Can't upload images from mobile firefox

### ISSUE THREAD

**Issue by leahoswald** [pixelfed/pixelfed#4680]
Hey, I just tried to upload a new image from the New->New Post mobile web view. This doesn't work in mobile firefox 118.1.0 on android 13. Nothing happens,no upload file chooser. Trying to upload something to a story works. In mobile Chrome it works directly.

**Comment by leahoswald** [comment]
Looks like the firefox app needs camera access which is totally unintuitive, but now it works. Not sure if this isn't still a bug, there should be at least an information about missing permissions.

**Comment by dansup** [comment]
Thanks for reporting this!
