### ISSUE TITLE
Some posts showing duplicates in feed

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#47]
![image](https://user-images.githubusercontent.com/10606431/40823482-fdfa3f2a-6535-11e8-84d5-431075229677.png)

https://pixelfed.social/p/ansuz/16

Only shows once on profile, but twice in public timeline.

**Comment by dansup** [comment]
@trwnh Most likely it was double posted by the user when submitting the form. I think handling this in JS would be ideal (with the current non-js form as a fallback)
