### ISSUE TITLE
Two-factor authentication field is not recognized as a text field

### ISSUE THREAD

**Issue by jaranta** [pixelfed/pixelfed#470]
I enabled two-factor authentication on my account today and noticed that the two-factor authentication field is not recognized as a text field in my browser (qutebrowser using webkit), making it more difficult to input the correct authentication code.

The numpad was not recognized at all and clicking on the field did not allow my to input anything on the field. I moved the cursor to the text field and then manually changed my browser into text-input mode and was then able to fill the numbers by using the numbers on the top row.

**Comment by mraitisoja** [comment]
I don't know if this is the same issue, but I noticed that text field doesn't have focus automatically.
I ended up typing the code, but nothing was typed in the box.
I added in my installation "autofocus" parameter for the text box and now the cursor is automatically in the text field. I haven't tested the numpad
