### ISSUE TITLE
QR code Two-factor authentication

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#471]
Hi,
On my mobile browser Firefox Nightly, it seems that the QR Code is oversized and out of CSS.

Second, I use AndOTP for 2FA, we need a text field to copy the base64 code to put into AndOTP.

Link to a screenshot : https://mstdn.fr/@BoF/100741658833095084

Regards :)

**Comment by dansup** [comment]
Fixed in b113d67

**Comment by ghost** [comment]
Thank you :)
