### ISSUE TITLE
Videos recorded by my iPhone can't be uploaded to pixelfed

### ISSUE THREAD

**Issue by Genfood** [pixelfed/pixelfed#4710]
Videos recorded with my iPhone can't be uploaded due to an unsupported file type. Any chance to support videos recorded by Apple devices, or add the option to automatically convert them to a supported file type?

**Comment by ghost** [comment]
Hello,

As far as I understand, an application (iOS, Android or even desktop) can handle the transcoding of the video format from the Apple `.mov` format into the Pixelfed supported `.mp4`.

Another possibility would be to add `.mov`, as a supported `video/quicktime` MIME Type in Pixelfed itself. That could surely be handled by FFMPEG which is [a Pixelfed prerequisite](https://docs.pixelfed.org/running-pixelfed/prerequisites/) upon installation.

**Comment by Genfood** [comment]
@mthld I tried to convert the videos but it didn't worked out well. Nevertheless I don't see myself using a social network where I have to convert videos. 😅  
I guess the more convenient solution is to support a wider variety of MIME Types.

**Comment by azuredusk10** [comment]
Related issues: 
https://github.com/pixelfed/pixelfed/issues/2745
https://github.com/pixelfed/pixelfed/issues/4760
https://github.com/pixelfed/pixelfed/issues/3614
