### ISSUE TITLE
Full screen for slide shows no longer opens

### ISSUE THREAD

**Issue by steinarb** [pixelfed/pixelfed#4716]
This is the web interface to https://pixelfed.social and I have seen this bug on chrome on windows and vivaldi on debian.

Clicking on the "Full screen" button for slide shows (black square upper left in the image) currently does nothing.

I get the following stack trace in the console of the chrome (actually vivaldi) webtools when clicking on the "Full screen" button:
```
TypeError: Cannot read properties of undefined (reading 'src')
    at vendor.js?id=aa78e65108a1408200df9d23217f0aca:2:152574
    at V (vendor.js?id=aa78e65108a1408200df9d23217f0aca:2:152692)
    at o.toggleLightbox (spa.js?id=3d4942f9a9920995110f87454f9a5979:2:11323)
    at click (spa.js?id=3d4942f9a9920995110f87454f9a5979:2:48250)
    at qn (vendor.js?id=aa78e65108a1408200df9d23217f0aca:2:2926733)
    at HTMLParagraphElement.n (vendor.js?id=aa78e65108a1408200df9d23217f0aca:2:2914489)
    at Yi.i._wrapper (vendor.js?id=aa78e65108a1408200df9d23217f0aca:2:2961934)
```

Clicking on the image of a non-slideshow image, shows that image in full screen.

Clicking on the image (instead of the button) in a slide-show gives the following output to the webtools console:
```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Z (https://pixelfed.social/js/vendor.js?id=aa78e65108a1408200df9d23217f0aca:2:156033)
```

**Comment by steinarb** [comment]
A little ping on this one today: still not able to open slideshow posts in full screen on the web interface of pixelfed.social.

**Comment by Leatherface75** [comment]
Same problem on my instance it works when there is 1 picture but not a few pictures in a post.
Edit: And yes i am using latest commits with the supposed fullscreen fix.
But the problem still exists.

ping @dansup

**Comment by Leatherface75** [comment]
Anyone workong on this?

**Comment by Leatherface75** [comment]
Anyone workong on this?
Running with all latest changes.
Only works in Pixelfed app and posts with only 1 picture and not a collection.

![image](https://github.com/pixelfed/pixelfed/assets/2489019/2cfe3737-2b50-4c34-ba1a-654f88801a2e)

**Comment by steinarb** [comment]
The stack trace today is the same as in my original issue.

There are two more warnings in the devtools console, that may, or may not be related:
```
vendor.js?id=aa78e65108a1408200df9d23217f0aca:2 [VueIntersect] You may only wrap one element in a <intersect> component.
(anonymous) @ spa.js?id=3d4942f9a9920995110f87454f9a5979:2
vendor.js?id=aa78e65108a1408200df9d23217f0aca:2 Allow attribute will take precedence over 'allowfullscreen'.
```

**Comment by Leatherface75** [comment]
This issue seems to be ignored.

**Comment by ellotheth** [comment]
Same behavior and stack trace when I click the "expand" icon in a post with multiple images on my instance running 84b63f8aa9bba5bdf00c7446930fca4b4b73c93b:

```
TypeError: can't access property "src", O[L] is undefined
    V https://gram.ello.tech/js/vendor.js?id=aa78e65108a1408200df9d23217f0aca:2
    V https://gram.ello.tech/js/vendor.js?id=aa78e65108a1408200df9d23217f0aca:2
    toggleLightbox https://gram.ello.tech/js/spa.js?id=3d4942f9a9920995110f87454f9a5979:2
    click https://gram.ello.tech/js/spa.js?id=3d4942f9a9920995110f87454f9a5979:2
    qn https://gram.ello.tech/js/vendor.js?id=aa78e65108a1408200df9d23217f0aca:2
    n https://gram.ello.tech/js/vendor.js?id=aa78e65108a1408200df9d23217f0aca:2
    _wrapper https://gram.ello.tech/js/vendor.js?id=aa78e65108a1408200df9d23217f0aca:2
    Yi https://gram.ello.tech/js/vendor.js?id=aa78e65108a1408200df9d23217f0aca:2
    mt https://gram.ello.tech/js/vendor.js?id=aa78e65108a1408200df9d23217f0aca:2
    Ui https://gram.ello.tech/js/vendor.js?id=aa78e65108a1408200df9d23217f0aca:2
    v https://gram.ello.tech/js/vendor.js?id=aa78e65108a1408200df9d23217f0aca:2
vendor.js:2:2927099
```

(Firefox 122b9)

**Comment by steinarb** [comment]
Suddenly discovered today that opening full screen on slide shows now  works on https://pixelfed.social/ again.

So this bug is probably fixed.

Since I am the one opening the issue and since the issue now is gone for me, I'm closing this as fixed

**Comment by Leatherface75** [comment]
> Suddenly discovered today that opening full screen on slide shows now works on https://pixelfed.social/ again.
> 
> So this bug is probably fixed.
> 
> Since I am the one opening the issue and since the issue now is gone for me, I'm closing this as fixed

Yeah it works again since a while ago.
