### ISSUE TITLE
Muted Accounts & Mobile App

### ISSUE THREAD

**Issue by RiversideBryan** [pixelfed/pixelfed#4722]
Muted accounts appear on the timelines when using the Pixelfed App for Android.

Mutes and blocks should be removed from view.

**Comment by okpierre** [comment]
Maybe similar to this https://github.com/pixelfed/pixelfed/issues/4652

Edit: was submitted and waiting for approval/merge

If you want to give it a try see this
https://github.com/pixelfed/pixelfed/commit/99b8e418d7d3889374b9c25f743cee8457b9b7a5
