### ISSUE TITLE
The "help" link leads to a 404 error

### ISSUE THREAD

**Issue by nhoizey** [pixelfed/pixelfed#4728]
The "help" link in the bottom of the left panel leads to [an inexistant page](https://pixelfed.social/i/web/help), hence a 404 error.

![CleanShot 2023-11-01 at 20 24 31@2x](https://github.com/pixelfed/pixelfed/assets/78213/a2e29631-7e1e-4d9e-86fc-bfb59bff8750)

**Comment by drallgood** [comment]
I cannot confirm this. Seems to work on my instance and also on the link provided above

**Comment by nhoizey** [comment]
@drallgood this is still true with the “help” link on my profile page: https://pixelfed.social/i/web/profile/406

![CleanShot 2024-01-03 at 22 52 11@2x](https://github.com/pixelfed/pixelfed/assets/78213/a47031b7-c24c-400a-abd4-462cc0817c6d)
