### ISSUE TITLE
Server domain failure at login with pixelfed.de

### ISSUE THREAD

**Issue by flwjdfkdi** [pixelfed/pixelfed#4731]
Hello :) If I enter the server domain pixelfed.de in order to login into my account it always says: "This server is not compatible or is offline. Please try again later" - "invalid instance domain". But it should be valid. I can login using this website. I tried it several days, always failed in the app. What can I do? Thanks in advance!

**Comment by drallgood** [comment]
Is this issue still happening?

**Comment by flwjdfkdi** [comment]
No, it has been solved, thank you!
