### ISSUE TITLE
Allowing users to add videos on iOS

### ISSUE THREAD

**Issue by sallyFoster** [pixelfed/pixelfed#4760]
Can you guys allow users to add videos on the iOS app on test flight? It currently only allows users to add images, but on web users can add videos. This puts me on the uncomfortable position of having to constantly having to change between web and mobile to add videos.

**Comment by drallgood** [comment]
Note that this is the repo for the main Pixelfed web app and not the mobile apps.
I recommend submitting this issue on the mobile app repo:
https://github.com/pixelfed/mobile-app

@sallyFoster

**Comment by nicksherman** [comment]
@drallgood While this does indeed apply to the mobile app as well, it’s also an issue that affects the mobile web-based functionality.

@trwnh I see you’ve closed several issues about this problem as “won’t fix”, but could you give some insight about why that is? It seems like a recurring (and understandable) frustration for people who are trying to post videos.

**Comment by trwnh** [comment]
@nicksherman this is an issue with the Pixelfed iOS app, not the Pixelfed server software. the issue has since been refiled (correctly) at https://github.com/pixelfed/mobile-app/issues/144
