### ISSUE TITLE
Redis database parameter is ignored

### ISSUE THREAD

**Issue by sunchaserinfo** [pixelfed/pixelfed#477]
With REDIS_DATABASE=2 it still writes to 0

**Comment by dansup** [comment]
@sunchaserinfo This is an upstream issue of predis or phpredis.

**Comment by sunchaserinfo** [comment]
@dansup O RLY
https://github.com/pixelfed/pixelfed/blob/dev/config/database.php#L115
so this
https://github.com/pixelfed/pixelfed/blob/dev/config/cache.php#L79
is ignored

**Comment by sunchaserinfo** [comment]
@dansup even if the bug was upstream it's still a bug in your software so the fixing (in terms of creating an upstream issue and integrating a fix) falls to you technically
