### ISSUE TITLE
Horizon queue name

### ISSUE THREAD

**Issue by sunchaserinfo** [pixelfed/pixelfed#478]
Is it wise to use random name for horizon queue? It changes after every restart and may lose queued tasks

Not an actual but a possible problem

**Comment by sunchaserinfo** [comment]
Also, redis gets polluted with old queue keys

**Comment by dansup** [comment]
@sunchaserinfo That is the default behaviour of the laravel framework we are using

**Comment by sunchaserinfo** [comment]
@dansup seems like a very bad default not suitable for (possible future) large instances
