### ISSUE TITLE
The app closes after starting or doesn't load anything. 

### ISSUE THREAD

**Issue by Peloria** [pixelfed/pixelfed#4788]
The app is most of the time not working. 
Frequently it closes instantly and when it opens nothing loads. 
As you can see in the screenshots, nothing loads besides the discovery tab. If I click on a picture in that tab, the image won't load either. 
I see this issue on Samsung Galaxy S22 and not on my older Google Pixel 4. The Galaxy was affected with OneUI 5.1 (Android 13) and now on OneUI (Android 14)

![Screenshot_20231128_132659_Pixelfed](https://github.com/pixelfed/pixelfed/assets/93275144/714d60a5-6cbf-4db6-b3b7-c49998dbceab)
![Screenshot_20231128_132644_Pixelfed](https://github.com/pixelfed/pixelfed/assets/93275144/78d8cc7f-53d0-462c-a531-c9b8980bd679)
![Screenshot_20231128_132628_Pixelfed](https://github.com/pixelfed/pixelfed/assets/93275144/5d931037-4e98-46c1-bcc3-62af4f1d415e)
![Screenshot_20231128_132608_Pixelfed](https://github.com/pixelfed/pixelfed/assets/93275144/728edef4-47c7-4a24-bf08-3e03182fd8b2)

**Comment by drallgood** [comment]
Note that this is the repo for the main Pixelfed web app and not the mobile apps.
I recommend submitting this issue on the mobile app repo:
https://github.com/pixelfed/mobile-app

@Peloria
