### ISSUE TITLE
Unable to make my account publically browsable

### ISSUE THREAD

**Issue by steinarb** [pixelfed/pixelfed#4793]
Originally reported as https://github.com/pixelfed/support/issues/188

I am unable to make https://pixelfed.social/steinarb publically browsable.

No matter what I do I'm sent to a login page, when opening in a private window I'm sent to a login page, and the same goes for people without a pixelfed account.

**Comment by dansup** [comment]
Fixed!

**Comment by steinarb** [comment]
Verified fixed! Lovely! Thanks! :smiley:
