### ISSUE TITLE
Dark mode small CSS fix: timestamp badge text is unreadable because of text color

### ISSUE THREAD

**Issue by Julianoe** [pixelfed/pixelfed#4800]
I suppose resources/assets/components/partials/profile/ProfileFeed.vue#L1126 should have `color: var(--dark);` like `.video-overlay-badge` does but I've never contributed code to PixelFed yet.

**Comment by Julianoe** [comment]
Just bumping this issue. Timestamp badge is still impossible to read on dark mode!

**Comment by trwnh** [comment]
![image](https://github.com/pixelfed/pixelfed/assets/10606431/95bf7c1e-fcc3-4f47-bf84-6e22d6870fba)
