### ISSUE TITLE
Andorid App: Clicking Moderation Reports in Admin fails

### ISSUE THREAD

**Issue by justdaj** [pixelfed/pixelfed#4808]
Clicking the 'Moderation Reports' tile in the Admin section of the Android app produces a black screen.  The app has crashed and you need to close it down.  

V1.0.0.43

![Screenshot_2023-12-08-15-39-22-08](https://github.com/pixelfed/pixelfed/assets/5741412/9bde1fad-acbd-4b58-b613-071dc791b892)

**Comment by drallgood** [comment]
Note that this is the repo for the main Pixelfed web app and not the mobile apps.
I recommend submitting this issue on the mobile app repo:
https://github.com/pixelfed/mobile-app

@justdaj
