### ISSUE TITLE
Andorid App: Stats tile gives an error

### ISSUE THREAD

**Issue by justdaj** [pixelfed/pixelfed#4809]
Clicking the Stats tile in the Admin section of the Android App gives "An error occured, please try again later"

"Occured" also incorrect spelling 🤔  That may be a framework thing though

![Screenshot_2023-12-08-15-39-31-82](https://github.com/pixelfed/pixelfed/assets/5741412/30a05873-d487-42ed-aa47-6f82ab043276)

V1.0.0.43

**Comment by drallgood** [comment]
Note that this is the repo for the main Pixelfed web app and not the mobile apps.
I recommend submitting this issue on the mobile app repo:
https://github.com/pixelfed/mobile-app

@justdaj
