### ISSUE TITLE
User list in Android Admin tool has limited list

### ISSUE THREAD

**Issue by justdaj** [pixelfed/pixelfed#4812]
When clicking the 'Users' tile in the Android Admin section, it only lists 30 users.  There is no option to continue scrolling, or paginating options

**Comment by drallgood** [comment]
Note that this is the repo for the main Pixelfed web app and not the mobile apps.
I recommend submitting this issue on the mobile app repo:
https://github.com/pixelfed/mobile-app

@justdaj
