### ISSUE TITLE
Issues with importing from Instagram

### ISSUE THREAD

**Issue by oculos** [pixelfed/pixelfed#4818]
I noticed that:

- When I import from instagram, the image isn't really imported before `php artisan:transform-imports` is run
- after php artisan:transport-imports is run, the image is uploaded to the local storage (and not to the cloud, which is what is configured for me). 
- The folder of the image gets owned by root, which is why the I get the blank images ("no preview available"):
- `drwx------   2 root     www-data`   
- chmod www-data fixes the directory, but the image is still local
- `php artisan media:migrate2cloud` doesn't seem to work:

```
php artisan media:migrate2cloud -vvv
 200/200 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% < 1 sec/< 1 sec 30.0 Mi
```

But the image is still local, ie, it doesn't get uploaded to the S3 backend.

My question is:
- How can I get these files uploaded to my cloud storage?
- Can we fix encoding text that is displaying like this "n stÃ¸rste fa" when imported from instagram?

**Comment by tretkowski** [comment]
We also had to run `php artisan app:transform-imports` after importing from Instagram and fix the owner of the folders containing the imported images.

**Comment by tretkowski** [comment]
Looks like `app:transform-images` is automatically run every ten minutes:
https://github.com/pixelfed/pixelfed/blob/dev/app/Console/Kernel.php#L41

Not sure if this would also fix the permission issues...
