### ISSUE TITLE
MySQL issue when register

### ISSUE THREAD

**Issue by Whaxion** [pixelfed/pixelfed#482]
I'm trying to implement a new version of my Pixelfed Docker environment but I'm getting some issues.
When registering, I got this QueryException:
```SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'user_settings_user_id_unique' (SQL: insert into `user_settings` (`user_id`, `updated_at`, `created_at`) values (1, 2018-09-23 15:47:45, 2018-09-23 15:47:45))```

If I reload, I can connect to my account and everything looks normal

![Screenshot of the error](http://i.imgur.com/ae71H2B.png)

**Comment by dansup** [comment]
@Whaxion What version of laravel are you running?

**Comment by Whaxion** [comment]
To make some update here and not only on IRC, Laravel Framework 5.6.38

**Comment by hnrd** [comment]
Same for my instance, although I am not sure which commit introduced that bug. Worked fine a while ago, did not test registering for quite some time.

**Comment by carbontwelve** [comment]
I have this running on dedicated hardware with the following environment set up this morning:

* PHP 7.2.11
* Debian 9
* Nginx 1.10.3
* PostgreSQL 9.6.10

When running a fresh install against a Postgres database I get an identical error for any attempt to register a new account.

Seems to be the `AuthLogin` event listener that is triggering the error but I don't yet know why unless it's being triggered twice.

**Comment by carbontwelve** [comment]
@dansup  I just spent a little bit of time investigating and it looks as though the on-saved event listener in `UserObserver` (https://github.com/pixelfed/pixelfed/blob/dev/app/Observer/UserObserver.php#L43) is doing the same as the handle method of the `AuthLogin` event (https://github.com/pixelfed/pixelfed/blob/dev/app/Listeners/AuthLogin.php#L31).

I am assuming that when a new user is created the `saved` method of `UserObserver` is triggered and creates a new `user_settings` record. Once the user is registered they are automatically logged in and it would appear that the `User` object that is passed to `AuthLogin` isn't up to date therefore resulting in `empty($user->settings)` evaluating true and the event trying to create a new `user_settings` record therefore triggering a unique violation error.

This can be "fixed" by modifying `AuthLogin` to look up _settings_ via `$user->settings()->count()` although if the record is being created by the `saved` observer _why_ should it be duplicated in the `AuthLogin` event?

**Comment by Whaxion** [comment]
Seems to be solved in the last commits
Is it also solved for you @carbontwelve ?

**Comment by dansup** [comment]
This bug was fixed in  33265f9
