### ISSUE TITLE
Feature Request: Pinch to Zoom

### ISSUE THREAD

**Issue by justdaj** [pixelfed/pixelfed#4823]
Can we please have pinch to zoom on the Android app?

No idea if it is available on iOS.  Can anyone confirm?

**Comment by OutOfPhase87** [comment]
> Can we please have pinch to zoom on the Android app?
> 
> No idea if it is available on iOS. Can anyone confirm?

iOS does not have this feature either.

**Comment by drallgood** [comment]
Note that this is the repo for the main Pixelfed web app and not the mobile apps.
I recommend submitting this issue on the mobile app repo:
https://github.com/pixelfed/mobile-app

@justdaj @OutOfPhase87

**Comment by justdaj** [comment]
You must have got fed up typing that today. LOL.  First anyone has responded to many of these issues.

Maybe Dan can move the various issues that need transferred.  I am not sure if that is a feature on Github
