### ISSUE TITLE
Admin dashboard issue when no pics

### ISSUE THREAD

**Issue by Whaxion** [pixelfed/pixelfed#483]
I'm still creating my Docker environment, and I've found a new issue.
If there is no pics posted, when visiting admin dashboard, we got an ErrorException:
```filesize(): stat failed for /pixelfed/storage/app/public/m/ (View: /pixelfed/resources/views/admin/home.blade.php)```
It's not a big issue, but it's still one, so.
![Picture of the exception](http://i.imgur.com/tJDFYtT.png)

**Comment by dansup** [comment]
@Whaxion That is an older laravel version exception page, are you sure you are running the latest commits?

**Comment by Whaxion** [comment]
It's a new setup from scratch, so, yes
