### ISSUE TITLE
"Something went wrong" when accessing privacy page

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#4839]
Hey everyone,

since the last commits (running v0.11.9-25a4289d), I cannot access the "Privacy"-option in my account settings anymore. Yes, I am keen on using the code helping to block specific domains but at least the option should open 😉 !

Decrypted payload shows "Route [settings.privacy.domain-blocks] not defined. (View: /var/www/pixelfed/resources/views/settings/privacy.blade.php)"

What does this mean and how can this be fixed?

Thanks in advance,

Oliver
<img width="974" alt="Bildschirmfoto 2023-12-23 um 09 38 35" src="https://github.com/pixelfed/pixelfed/assets/42076599/ba818e1e-c076-4520-a493-6769547ae3ea">
<img width="471" alt="Bildschirmfoto 2023-12-23 um 09 41 02" src="https://github.com/pixelfed/pixelfed/assets/42076599/6c854993-9b5e-4124-b2f4-7f3081e8b35d">

**Comment by dansup** [comment]
@OliverPifferi Looks like you need to run `php artisan route:cache`

You should be running the post deployment commands listed [here](https://docs.pixelfed.org/running-pixelfed/administration/#updating-pixelfed)

**Comment by dansup** [comment]
Feel free to re-open this if you are still experiencing issues

**Comment by ghost** [comment]
@dansup Thanks, that did it - ran all the commands but this one was missing. Can confirm that it works now - thanks for the blazing fast reponse and merry X-Mas!

**Comment by dansup** [comment]
Merry Christmas to you too!
