### ISSUE TITLE
Missing Open Graph thumbnail for video posts

### ISSUE THREAD

**Issue by azuredusk10** [pixelfed/pixelfed#4841]
When sending a link to a public video post via a messaging app, the link preview that’s generated is missing the video thumbnail. In its place is a “No preview available” placeholder image. 

![IMG_8155](https://github.com/pixelfed/pixelfed/assets/18142893/d6cc2e6a-fad6-45f3-b7a5-53b352c78954)

Steps to reproduce:
1. Open a messaging app, e.g Signal
2. Add a link to a video post in a new message, e.g. https://pixelfed.social/p/AzureDusk10/624747701908685463

Expected result: 
The link preview shows the video thumbnail (like the one that’s shown on the grid of posts on a profile page)

Actual result:
The link preview shows a placeholder “No preview available” thumbnail

**Comment by dansup** [comment]
Fixed in fd44c80ce9
