### ISSUE TITLE
Permit login with account number.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [pixelfed/pixelfed#4848]
The e-mail address on my account may change, so I'd like to be able to login with my user number rather than the e-mail address so that my credential manager need not reflect the current e-mail address in use.

**Comment by mitexleo** [comment]
You meant "username" ?

+1

**Comment by roke-julian-lockhart** [comment]
https://github.com/pixelfed/pixelfed/issues/4848#issuecomment-1879638751

No, @mitexleo, the account number.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/pixelfed/pixelfed/issues/4848#issuecomment-1879638751

Does no issue exist also for the username? ~~If not, I'll make one and link it here for you, because that should be possible too.~~

https://github.com/pixelfed/pixelfed/issues/4852

**Comment by dansup** [comment]
Duplicate of #494

**Comment by roke-julian-lockhart** [comment]
> https://github.com/pixelfed/pixelfed/issues/4848#issuecomment-1879776453

@dansup, this isn't a duplicate of that issue. They're about entirely different attributes. Regardless, https://github.com/pixelfed/pixelfed/issues/4852#issuecomment-1879794277.

**Comment by s0mt0x64** [comment]
> > https://github.com/pixelfed/pixelfed/issues/4848#issuecomment-1879776453
> 
> @dansup, this isn't a duplicate of that issue. They're about entirely different attributes. Regardless, https://github.com/pixelfed/pixelfed/issues/4852#issuecomment-1879794277.

Take meds
