### ISSUE TITLE
API ignores license parameter

### ISSUE THREAD

**Issue by MSicc** [pixelfed/pixelfed#4850]
The API ignores the license parameter on media uploads and edits.

I tried to use the paramater with name "license", using any of the ids from https://github.com/pixelfed/pixelfed/blob/dev/app/Util/Media/License.php#L5 as value.

My best guess is that is not yet implemented in the API.

**Comment by dansup** [comment]
Correct, this is not implemented in our Mastodon-compatible APIs since it's a pixelfed specific feature!

**Comment by MSicc** [comment]
So users that want to use the license for their images are forced to use your website?
