### ISSUE TITLE
favourites limit is 20 instead of 40

### ISSUE THREAD

**Issue by technicat** [pixelfed/pixelfed#4854]
I'm using the Mastodon API to retrieve favourites with the max limit of 40 as in the spec

https://docs.joinmastodon.org/methods/favourites/

but this error message from pixelfed.social indicates the max is 20. I'm using 40 for everything else (bookmarks, timelines...) and I think this is the only case where the limit doesn't match the spec.

```json
{
  "message" : "The limit may not be greater than 20.",
  "errors" : {
    "limit" : [
      "The limit may not be greater than 20."
    ]
  }
}
```

**Comment by dansup** [comment]
@technicat Can confirm, will push a fix shortly!

**Comment by dansup** [comment]
@technicat Fix deployed on pixelfed.social and .art :)

**Comment by technicat** [comment]
> @technicat Fix deployed on pixelfed.social and .art :)

Fast work!
