### ISSUE TITLE
TODO list?

### ISSUE THREAD

**Issue by tigers-are-cool** [pixelfed/pixelfed#486]
I want to contribute with code, what can I do? I know JS, TS, HTML and CSS and can quickly get back at PHP. I would prefer to contribute to back end.

**Comment by dansup** [comment]
@tigers-are-cool Hi, I would hold off for now. I still have a lot of back end commits to push!

**Comment by trwnh** [comment]
Issue #73 is currently tracking missing functionality. I haven't updated it in some time, but it should still be mostly relevant.
