### ISSUE TITLE
Dockerfile.apache fails build, with missing package, libwebp7

### ISSUE THREAD

**Issue by gangrif** [pixelfed/pixelfed#4860]
I am attempting to build the pixelfed apache container using the provided contrib/docker/Dockerfile.apache, and it is failing with a package error, apt finds no package matching libwebp7. 

The proper package appears to be libwebp6?  

Error:
`E: Unable to locate package libwebp7
Error: error building at STEP "RUN apt-get update   && apt-get upgrade -y   && apt-get install -y --no-install-recommends       locales       locales-all       git       gosu       zip       unzip       libzip-dev       libcurl4-openssl-dev       optipng       pngquant       jpegoptim       gifsicle       libjpeg62-turbo-dev       libpng-dev       libmagickwand-dev       libxpm4       libxpm-dev       libwebp7       libwebp-dev       ffmpeg       mariadb-client   && sed -i '/en_US/s/^#//g' /etc/locale.gen   && locale-gen   && update-locale   && docker-php-source extract   && pecl install imagick   && docker-php-ext-enable imagick   && docker-php-ext-configure gd       --with-freetype       --with-jpeg       --with-webp       --with-xpm   && docker-php-ext-install -j$(nproc) gd   && pecl install redis   && docker-php-ext-enable redis   && docker-php-ext-install pdo_mysql   && docker-php-ext-configure intl   && docker-php-ext-install -j$(nproc) intl bcmath zip pcntl exif curl   && a2enmod rewrite remoteip  && {     echo RemoteIPHeader X-Real-IP ;     echo RemoteIPTrustedProxy 10.0.0.0/8 ;     echo RemoteIPTrustedProxy 172.16.0.0/12 ;     echo RemoteIPTrustedProxy 192.168.0.0/16 ;     echo SetEnvIf X-Forwarded-Proto "https" HTTPS=on ;    } > /etc/apache2/conf-available/remoteip.conf  && a2enconf remoteip   && docker-php-source delete   && apt-get autoremove --purge -y   && apt-get clean   && rm -rf /var/cache/apt   && rm -rf /var/lib/apt/lists/": error while running runtime: exit status 100`

Troublehsooting:
I ran the PHP:8.1-apache container that the Dockerfile sources from, and connected to a shell. I did some apt searches, and did not find a libwebp7 package, rather libwebp6. 

`root@7551e0653baa:/var/www/html# apt-get update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8062 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [264 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [18.8 kB]
Fetched 8554 kB in 2s (3476 kB/s)
Reading package lists... Done
root@7551e0653baa:/var/www/html# apt-cache search libwebp
libwebp-dev - Lossy compression of digital photographic images.
libwebp6 - Lossy compression of digital photographic images.
libwebpdemux2 - Lossy compression of digital photographic images.
libwebpmux3 - Lossy compression of digital photographic images.
root@7551e0653baa:/var/www/html# exit`

I replaced libwebp7 with libwebp6 in the dockerfile's package installation list, and the build appears to complete, or at least passes the package installations.  I am still waiting on the full build to finish. 

I see other issues suggesting that libwebp6 should be changed to libwebp7 in the fpm container, and have not tested that, but in the case of the apache container, the build fails if you use 7.

**Comment by gangrif** [comment]
update, the build did complete using libwebp6, and i have the new container up and running.

**Comment by jippi** [comment]
this is fixed in #4844 as well

**Comment by saschafoerster** [comment]
Thank you, had this issue as well when upgrading my own docker build to v11.11

**Comment by leafonthewind** [comment]
Same, thanks for the tip!  Was upgrading to v0.11.11 and hit this error when running `docker compose build`.  I made the below change, and then it ran successfully.

```diff
diff --git a/contrib/docker/Dockerfile.apache b/contrib/docker/Dockerfile.apache
index a400f879..9c33aee1 100644
--- a/contrib/docker/Dockerfile.apache
+++ b/contrib/docker/Dockerfile.apache
@@ -33,7 +33,7 @@ RUN apt-get update \
 # Required for GD
       libxpm4 \
       libxpm-dev \
-      libwebp7 \
+      libwebp6 \
       libwebp-dev \
 ## Video Processing
       ffmpeg \
```

**Comment by ThisIsMissEm** [comment]
I think this can be closed now the docker setup has been completely rewritten
