### ISSUE TITLE
New install failes

### ISSUE THREAD

**Issue by markim** [pixelfed/pixelfed#4863]
Following the install instructions fresh today, I failed to install pixelfed.

I failed on the first migrating data. 2024_01_09_052419_create_parental_controls_table failed at dropIndex('user_roles_profile_id_unique') on the up() function.

Was it supposed to be `dropForeign('user_roles_profile_id_unique')` on https://github.com/pixelfed/pixelfed/blob/187d1e1af995d174f15fddb8796c5afb8ed0e2e6/database/migrations/2024_01_09_052419_create_parental_controls_table.php#L28 ?
dropForeign instead of dropIndex works for me.

**Comment by pitbuster** [comment]
I confirm that `dropForeign` works for fixing the migration.

**Comment by drallgood** [comment]
oh cool.. running into that issue. I'm on docker so fixing it by hand ain't that easy. 
I'll see what I can do

**Comment by drallgood** [comment]
Easiest fix: `ALTER TABLE user_roles DROP CONSTRAINT user_roles_profile_id_unique;` (for Postgres)
