### ISSUE TITLE
 "No preview available" on all pixelfed.social posts when browsing from Firefox

### ISSUE THREAD

**Issue by nehemiagurl** [pixelfed/pixelfed#4873]
When opening a direct pixelfed.social link in Firefox, not signed in to an account, it always appears as "no preview available", regardless of the account posting.
[This post from pixelfed](https://pixelfed.social/p/pixelfed/647553602914775987) appears as:
<img width="1409" alt="Screenshot 2024-01-22 at 13 52 22" src="https://github.com/pixelfed/pixelfed/assets/109424320/02c37a11-0cc9-43e8-89b2-033bd37491c8">
And [this one from TLENick](https://pixelfed.social/p/TLENick/649164566507970710) appears as:
<img width="1426" alt="Screenshot 2024-01-22 at 13 52 27" src="https://github.com/pixelfed/pixelfed/assets/109424320/6f3cd5e8-a970-4ed8-9c79-0e85f354f971">
I have uBlock Origin, Privacy Badger and Canvas Blocker installed on my browser, however, none of the three block any element and disabling them doesn't help.

I cannot reproduce this issue on Safari or on Firefox Mobile. I cannot reproduce this issue on any other instance other than pixelfed.social.

I believe this issue is related to #4853. In fact I am almost certain the two are related since all parameters - pixelfed.social only, Firefox desktop only - are true for #4853 as well.

**Comment by nehemiagurl** [comment]
Note that as mentioned in [this comment](https://github.com/pixelfed/pixelfed/issues/4853#issuecomment-1994193826), I'm getting requests from pxscdn.com rejected.

<img width="769" alt="screenshot from network tab showing rejected requests" src="https://github.com/pixelfed/pixelfed/assets/109424320/905759f2-754d-4576-9b87-6a6d1eb0aaca">

**Comment by nehemiagurl** [comment]
_not planned_? is Firefox support for pixelfed.social _not planned_? @trwnh

**Comment by trwnh** [comment]
Cannot reproduce

**Comment by nehemiagurl** [comment]
did you see the linked issue where more people reproduced and gave potential hypotheses?
-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


31 May 2024, 09:22 by ***@***.***:

**Comment by trwnh** [comment]
I am using Firefox right now and pxscdn.com is loading previews for me for all posts, including the posts you cited as an example.

**Comment by nehemiagurl** [comment]
@trwnh I think I found the source of the block - pxscdn might be blocking some VPNs - when I disconnect and reload, I get those posts to load perfectly fine.
