### ISSUE TITLE
Migration fails on new install - Cannot drop unique index

### ISSUE THREAD

**Issue by MrRoyce** [pixelfed/pixelfed#4883]
Hey there, a new install is failing in the initial migration - Is this related to the change at https://github.com/pixelfed/pixelfed/issues/4863 ?

I verified that the code matches the latest change, but the migration still fails for me with:

```
SQLSTATE[2BP01]: Dependent objects still exist: 7 ERROR:  
cannot drop index user_roles_profile_id_unique 
because constraint user_roles_profile_id_unique on table user_roles requires it
```

**Comment by Borks** [comment]
Same here. Not new install, upgrading from older version. 

Edit: `ALTER TABLE user_roles DROP CONSTRAINT user_roles_profile_id_unique;`
works to allow running migrations. Stolen from #4863

**Comment by MrRoyce** [comment]
@Borks where would that statement be executed?  

I run automated installations with an Ansible Playbook that downloads the latest Pixelfed zip and executes the migration files.  Would that ALTER statement have to built into a new migration file or do you execute it manually during a manual upgrade/migration?

Thanks!

**Comment by dansup** [comment]
The fix was shipped in [8a9a7c0](https://github.com/pixelfed/pixelfed/pull/4884/commits/8a9a7c0e478386dda2b705c64b30075c3133845b) and was a simple typo! 

I've tested on postgres and everything is working properly now!

**Comment by Borks** [comment]
@MrRoyce seems you can just git pull now and I suppose should work fine. 
Otherwise I just accessed the postgresql instance directly.

**Comment by MrRoyce** [comment]
Thanks @Borks  @dansup  That worked
