### ISSUE TITLE
Username validation

### ISSUE THREAD

**Issue by Grayswandir** [pixelfed/pixelfed#489]
Hello,
We have an issue in our Mastodon instance (v2.5.0):
Sidekiq: "ActiveRecord::RecordInvalid: La validation a échoué : Username seulement des lettres, des nombres et des tirets bas"
The link related: https://pix.hostux.social/p/Ma%C3%AFa/2553
But not sure if it's Pixelfed or Mastodon issue, 'cause Mastodon should accept it?
Or maybe it's a question for Fedivers, should the username be compose of only letter without accent?
++

**Comment by trwnh** [comment]
I think this is a Mastodon issue. Mastodon usernames are Aa-Zz + 0-9 + underscores.
