### ISSUE TITLE
Comment permalink doesn't show the presence of other comments

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#49]
https://pixelfed.social/p/mike/34 (only caption and linked comment is visible)
vs
https://pixelfed.social/p/ansuz/16 (all comments visible)

There should be some indication that only the linked comment is being displayed, in order to clarify that this isn't the only comment.

Also a bit confusing that /p/ is used both for images and for comments... perhaps rethink your permalink structure? (Separate issue #51 for that will go in-depth...) With a better permalink structure, this issue can be side-stepped by simply highlighting the linked comment.

**Comment by dansup** [comment]
@trwnh That is on purpose, so you can link to a specific comment.

**Comment by trwnh** [comment]
@dansup I know that the purpose is to link to a specific comment, but the issue is specifically that this view does not indicate that there are other comments, does not let you interact with the image, etc.

**Comment by trwnh** [comment]
Perhaps a minor rethink: with the comments button being currently useless and linking to nothing, it might be worth adopting the following logical flow for comments:

- On the full post (e.g. /ansuz/16), show only the recent comments that will fit in the given height? You may already be doing some variant of this, because it looks noticeably off right now (#161)
- Comment button links to a dedicated page for comments (with #51 in mind, it could look like /ansuz/16/comments or /ansuz/16/c) that shows all comments received, allows for nesting, etc.
- Linking to individual comments would still be possible from this comments page, and would take the form e.g. /ansuz/16/comments/34 or /ansuz/16/c/34

**Comment by trwnh** [comment]
Mockup
![image](https://user-images.githubusercontent.com/10606431/41880377-6501a20a-78a3-11e8-8eb0-0aecab2b4cb5.png)

**Comment by dansup** [comment]
Fixed in latest commits!
