### ISSUE TITLE
Missing entries in local timeline (metapixl.com)

### ISSUE THREAD

**Issue by andre-dierker** [pixelfed/pixelfed#4905]
Hello,

on metapixl.com the local feed is loosing entries over the time. The posts are still findadable in home feed and in profiles.

Version is latest dev

**Comment by marcelcosta** [comment]
Hi!

It happens to us, too. picto.anartist.org

**Comment by marcelcosta** [comment]
Hi,

After reading the solution in the Matrix Pixelfed Room, its working again.

1. I have added this line to the .env (I'm not sure if it is necessary):
```bash
INSTANCE_PUBLIC_TIMELINE_CACHED=true
```
2. I have updated the code (last time was two days ago but there were already changes).

Now I see the full local timeline.

**Comment by shleeable** [comment]
Same issue on pixelfed.au

**Comment by andre-dierker** [comment]
For me this worked as a workaround:
comment out if enabled `INSTANCE_PUBLIC_TIMELINE_CACHED=true` and do so for `EXP_CHT=true`

After that in the app the local timeline won't load but in web UI the timeline is back and complete. Users don't see the followed hashtags anymore but reblogs are visible. I think this disables the redis cache for the local timeline.

My related config:

```
INSTANCE_DISCOVER_PUBLIC=true
INSTANCE_NETWORK_TIMELINE_CACHED=true
#INSTANCE_PUBLIC_TIMELINE_CACHED=true


## Redis
BROADCAST_DRIVER=log
CACHE_DRIVER=redis
SESSION_DRIVER=database
#Session_driver=redis
QUEUE_DRIVER=redis
REDIS_CLIENT=phpredis

## experimental home feed
#EXP_CHT=true

```
If I set  `INSTANCE_PUBLIC_TIMELINE_CACHED=true` the timeline is empty except like 12 hours old posts. With new posts the timeline fills up but then looses random entries.

metapixl.com can use up to 32 ram, redis is configured to use max 2gb but never reaches more than 250mb. So no memory issues on this side.

**Comment by oculos** [comment]
Same issue for pixelfed.babb.no

**Comment by marcelcosta** [comment]
>If I set INSTANCE_PUBLIC_TIMELINE_CACHED=true the timeline is empty except like 12 hours old posts. With new posts the timeline fills up but then looses random entries.

Curious, I read to include that line from dansup in the Matrix Room. In my case, it doesn't affect your way.

Maybe is a stupid question, but have you updated to v.0.11.12, from yesterday?

**Comment by dansup** [comment]
Can you all confirm you are running v0.11.12 released yesterday?

**Comment by dansup** [comment]
Try setting `PF_NETWORK_TIMELINE_DAYS_FALLOFF=30` then running `php artisan config:cache && php artisan cache:clear`

**Comment by andre-dierker** [comment]
I'm sorry to say that but it's still happening on metapixl.com. 
I'm running the latest commits.
I've added `PF_NETWORK_TIMELINE_DAYS_FALLOFF=30` to .env but over night a lot of posts, like 20 to 30 got removed
