### ISSUE TITLE
Federation posts missing after update on  v0.11.11

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#4916]
Hello,

I'm trying to update .fr from v0.11.9 following the official doc : 
https://docs.pixelfed.org/running-pixelfed/administration/

After the update, all the federation stuff disapear. The global timeline and the notifications only shows the local posts and reactions.
Do you know what I'm missing ?

I actually downgraded and waiting for an answer. Thanks !

**Comment by dansup** [comment]
Have you enabled `EXP_CHT` or `EXP_CPT`? You may need to flush redis, and make sure you have enough RAM for redis.

**Comment by raphgilles** [comment]
No, I didn't eneabed EXP_CHT & CPT.
I'm only using 2G/6G of RAM & 5% of the VCPU.

It's "php artisan cache:clear" to flush redis that's right ?

I tried that, and the global timeline continue to display only locals posts. But according to the admin panel, posts are corectly imported.

**Comment by raphgilles** [comment]
UPDATE : The global timeline works on the app. But not on the https.
And "php artisan cache:clear" fixed the notifications thing.

**Comment by escuco** [comment]
Same at pixelfed.cafe. No federated posts in the global timeline.

**Comment by Zir0h** [comment]
Same issue on pixelfed.eu, I do see federated posts though, just not on the global timeline. With discover or my home feed I can see remote content.

**Comment by kerbergay** [comment]
And pixelfed.ru has the same problem.

**Comment by raphgilles** [comment]
Thanks but... It still broken, and also on the app now ! 😅

**Comment by dansup** [comment]
@raphgilles Please try updating now, this has been fixed in #4924

**Comment by raphgilles** [comment]
> @raphgilles Please try updating now, this has been fixed in #4924

Here we go ! That's working fine now.
Thanks you !

**Comment by escuco** [comment]
Thank you, works now!
