### ISSUE TITLE
Not the right number of photos

### ISSUE THREAD

**Issue by DansLeRuSH** [pixelfed/pixelfed#492]
Hi,

I did some tests including a .png transparent pic. I decided to delete it and, even if there's no more this pic I still have the previous number of "posts" on my profile.

Please have a look on https://pixelfed.social/DansLeRuSH

Best regards,
Franck

**Comment by DansLeRuSH** [comment]
Hi Daniel, I no longer have the problem :vulcan_salute: :sunglasses:

**Comment by hellcp** [comment]
Fixed :+1:
