### ISSUE TITLE
Two-factor authentication is asked on already logged in accounts

### ISSUE THREAD

**Issue by jaranta** [pixelfed/pixelfed#497]
I enabled two-factor authentication assuming it would work like it does in most other cases: new logins get shown a two-factor authentication screen. It seems Pixelfed currently asks it whenever I try to load the page, which is an enourmous hassle, especially on mobile. I only use Pixelfed on 2 machines that I trust, so there is no need to ask it every time I load the page.

I tried turning it off, but that doesn't currently seem like an option.

Short-term solution: allow disabling two-factor authentication.

Long-term solution: only ask two-factor authentication on previously unseen logins.

**Comment by dansup** [comment]
@jaranta Two-factor uses a session flag that only expires when the session expires. It can vary instance to instance, on pixelfed.social the session timeout is 2 days. It could be your browser that is clearing the session when you close it.

**Comment by jaranta** [comment]
I haven't checked Pixelfed daily, so I think I hit the 2 day session timeout between opening Pixelfed. The session flag seems separate from login session, since I'm not logged out, only asked for the two-factor?

I know it's a security feature, but 2 days seems like an awfully short time at least for my use case.

Edit: Sorry for the open-close of this issue, but for some reason the button was "reply and close".

**Comment by veb** [comment]
Yes, I'd like to see this increased as well if possible @dansup 👍

**Comment by dansup** [comment]
@jaranta @veb Please respond with the browser, version and any extensions or add-ons you have enabled. I can't reproduce this issue.

**Comment by dansup** [comment]
Oh I understand, so what do you think is a good session timeout limit? 1 week?

I will add a checkbox to the login that ensures the session ends when the browser is closed for public computers.

**Comment by veb** [comment]
I think one week should be fine. 👍

**Comment by trwnh** [comment]
Is there a reason why a session shouldn't be technically indefinite on trusted devices? I suppose that means that it would be best to have a session management page in settings, to force-logout any devices you don't recognize or no longer own.

**Comment by dansup** [comment]
Fixed in latest commits.
