### ISSUE TITLE
php artisan backup:run - seems to have MySQL hard coded

### ISSUE THREAD

**Issue by maxheadroom** [pixelfed/pixelfed#4971]
I'm running Pixelfed with PostgreSQL database. When executing the ```php artisan backup:run``` command I'm eventually getting an error message that the mysqldump tool couldn't finish the database backup.

I'd assume that with a PostgreSQL database a different backup tool than mysqldump would be used.

**Comment by dansup** [comment]
Edit the following line accordingly

https://github.com/pixelfed/pixelfed/blob/57df06a0b6efb6c050b7143d8d5de6001478c408/config/backup.php#L69
