### ISSUE TITLE
Docker: Allow configuring [MARIADB | MYSQL]_ROOT_PASSWORD independently 

### ISSUE THREAD

**Issue by jippi** [pixelfed/pixelfed#4980]
The Docker Compose setup assume the `DB_PASSWORD` is also used for the `ROOT_PASSWORD` - however, in migration situations, or for security focused people, this is not true - so add a `DB_ROOT_PASSWORD` field setting that uses `DB_PASSWORD` as default value

Discussed in https://github.com/pixelfed/pixelfed/discussions/4977

**Comment by lnlyssg** [comment]
I have a related question on the healthcheck... I can see it's using the ID mysql however that ID doesn't seem to exist on my (migrated) set-up, assuming I have used the right queries then I have `pixelfed` `root` and `mariadb.sys`:

```
MariaDB [(none)]> use mysql;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [mysql]> select user,host from user;
+-------------+-----------+
| User        | Host      |
+-------------+-----------+
| pixelfed    | %         |
| root        | %         |
| mariadb.sys | localhost |
| root        | localhost |
+-------------+-----------+
7 rows in set (0.001 sec)
```
