### ISSUE TITLE
Unable to delete server rules

### ISSUE THREAD

**Issue by gramakri** [pixelfed/pixelfed#4990]
Pixelfed 0.11.13

When attempting to delete a rule, the server responds with an error saying that regs is required . Look like an invalid validation for the delete rule rest route.

The request to delete is only sent with `{"rule_delete":"2"}`

![image](https://github.com/pixelfed/pixelfed/assets/82041/67f8d02d-9535-4a02-8467-4ddccf8b028a)

**Comment by dansup** [comment]
Fixed in the latest commits!
