### ISSUE TITLE
ActivityPub Jobs

### ISSUE THREAD

**Issue by dansup** [pixelfed/pixelfed#5]
- [ ] SharedInbox Listener
- [x] ~InboxWorker (Responds to inbox requests)~
- [ ] SharedInboxWorker
- [x] ~RemoteFollowImport (Imports last 9 images for new remote profiles)~
- [ ] Accept/Reject Workers

Incoming:
- [ ] Posts: `Create Note` should be visible in your timeline
- [x] Comments: `Create Note.inReplyTo` should be visible on your post
- [x] Delete post: `Delete Note` should remove a post from your timeline
- [x] Delete comment: `Delete Note.inReplyTo` should remove a comment from your post
- [ ] Update post: `Update Note` should change caption/metadata of post in your timeline
- [ ] Update comment: `Update Note.inReplyTo` should change text of comment on your post
- [x] Like post: `Like Note` should +1 the likes count and add their account to the likes list on your post
- [x] Like comment: `Like Note.inReplyTo` should +1 the likes count and add their account to the likes list on your comment
- [x] Unlike post: `Undo Like Note` should -1 the likes count and remove their account from the likes list on your post
- [x] Unlike comment: `Undo Like Note.inReplyTo` should -1 the likes count and remove their account from the likes list on your comment
- [x] Boost post: `Announce Note` should +1 the reshare count and add their account to the boosted list on your post
- [ ] Boost comment: `Announce Note.inReplyTo` should +1 the reshare count and add their account to the boosted list on your comment
- [x] Unboost post: `Undo Announce Note` should -1 the reshare count and remove their account from the boosted list on your post
- [ ] Unboost comment: `Undo Announce Note.inReplyTo` should -1 the reshare count and remove their account from the boosted list on your comment
- [x] Follow: `Follow` should send an outgoing `Accept Follow`, add their account to your follower list, and start delivering to their inbox
- [ ] Follow approved: `Accept Follow` should start showing their posts in your feed, and add their account to your following list
- [ ] Unfollow: `Undo Follow` should remove their account from your follower list and stop delivering to their inbox
- [ ] Force-unfollow (e.g. when blocked): `Reject Follow` should remove their account from your follower list and their posts from your feed
- [ ] Block: `Block` should prevent you from following, liking, resharing, or commenting them

Outgoing:
- [x] Posts: `Create Note` should be delivered to their inbox and show up in their feed
- [x] Comments: `Create Note.inReplyTo` should be delivered to their inbox and show up in a thread
- [x] Delete post: `Delete Note` should be delivered to their inbox and remove a post from the feed
- [x] Delete comment: `Delete Note.inReplyTo` should be delivered to their inbox and remove a comment from a thread
- [ ] Update post: `Update Note` should be delivered to their inbox and change the contents of a post (if supported)
- [ ] Update comment: `Update Note.inReplyTo` should be delivered to their inbox and change the contents of a comment (if supported)
- [x] Like post: `Like Note` should be delivered to their inbox and locally add a post to your liked posts
- [x] Like comment: `Like Note.inReplyTo` should be delivered to their inbox and locally add a comment to your liked comments
- [x] Unlike post: `Undo Like Note` should be delivered to their inbox and locally remove a post from your liked posts
- [x] Unlike comment: `Undo Like Note.inReplyTo` should be delivered to their inbox and locally remove a comment from your liked comments
- [x] Boost post: `Announce Note` should be delivered to their inbox and locally add their post to your reshares
- [-] Boost comment: `Announce Note.inReplyTo` should be delivered to their inbox and locally add their comment to your reshares (unnecessary in Pixelfed?)
- [x] Unboost post: `Undo Announce Note` should be delivered to their inbox and locally remove their post from your reshares
- [-] Unboost comment: `Undo Announce Note.inReplyTo` should be delivered to their inbox and locally remove their comment from your reshares (unnecessary in Pixelfed?)
- [x] Follow: `Follow` should wait for an incoming `Accept Follow`
- [x] Follow approved: `Accept Follow` should be delivered to their inbox to let them know the follow was successful
- [ ] Unfollow: `Undo Follow` should be delivered to their inbox, remove their account from your following list, and remove their posts from your feed
- [ ] Force-unfollow (e.g. when blocked): `Reject Follow` should be delivered to their inbox, remove their account from your follower list, and stop delivering posts to their inbox.
- [ ] Block: `Block` should be delivered to their inbox (debatable -- perhaps optional?), and then immediately be followed up by an outgoing `Reject Follow`; incoming activities from that account should be discarded and return a `Reject Activity` that gets delivered to their inbox.

**Comment by trwnh** [comment]
Possibly missing?

- Like Comment -> Announce

**Comment by dansup** [comment]
@trwnh I don't think its possible to like a comment on Instagram?

**Comment by trwnh** [comment]
It's been possible since 2016: https://later.com/blog/like-instagram-comments/

The more pressing reason would be to support comment federation; commenting on an image post is the same as replying to a text post.

**Comment by dansup** [comment]
@trwnh Thanks, I will add that to the roadmap.

**Comment by dadall** [comment]
Hey @dansup, is it up to date ?

**Comment by arjenpdevries** [comment]
Remote follow from Mastodon does not work yet.

**Comment by tribela** [comment]
Deleting post is not forwarded to other servers.

(edit by @trwnh: both incoming and outgoing Deletes are not yet supported)

**Comment by ghost** [comment]
Hello,

InboxWorker is failing on 0.8.4:
<img width="941" alt="Screenshot 2019-04-02 at 14 28 37" src="https://user-images.githubusercontent.com/41020854/55402461-ceb31480-5553-11e9-81bb-f539fdf5ef22.png">

**Comment by ghost** [comment]
> Hello,
> 
> InboxWorker is failing on 0.8.4:
> <img alt="Screenshot 2019-04-02 at 14 28 37" width="941" src="https://user-images.githubusercontent.com/41020854/55402461-ceb31480-5553-11e9-81bb-f539fdf5ef22.png">

Does someone know if it is related? The problem occurs on the last versions too.
