### ISSUE TITLE
 Restricted access to the signup page

### ISSUE THREAD

**Issue by Grayswandir** [pixelfed/pixelfed#500]
Hello,
It would be nice to be able to configure a few ip range allowed to access the signup page.
Signup page only, not login page (full access).

Use case, who can create an account:

    Family at home
    Collegues in office
    Students at school
    Customers in an ISP
    ...

ps: It's also a way to have a small protection from spam account.
pps: same functionality in peertube, with whitelist/blacklist ip range.

Best regards,
Grays

**Comment by Granitosaurus** [comment]
I'm not sure how is this not a job of a general firewall? Nginx already allows that: https://stackoverflow.com/questions/17264995

**Comment by carbontwelve** [comment]
I can see the following use cases for adding whitelist/blacklist ip range functionality to Pixelfed:

* It simplifies configuration for people tech savvy enough to set up a Pixelfed instance but whom don't have deep enough knowledge of their firewall/HTTP server config to feel comfortable in using that for ip whitelist/blacklisting.
* In the future someone may, as has been done with Mastodon, provide a hosted solution where the admin of the Pixelfed install may not have access to the servers firewall/HTTP server config.

It is my personal preference to use the servers firewall for IP whitelist/blacklist however having thought this through I believe given the above that the request has merit and would too like to see it included in Pixelfed.
