### ISSUE TITLE
Hashtags point to a missing page

### ISSUE THREAD

**Issue by yo-scottie-oh** [pixelfed/pixelfed#5006]
## Steps to reproduce the issue

1. Go to the Explore page. For example, https://pixelfed.social/web/explore.
2. Click the link for any hashtag in any photo caption. For example, one of the hashtags in the current top photo is #wilderness. Clicking the link for #wilderness points to https://pixelfed.social/discover/tags/wilderness.

**EDIT:** Tested in Firefox v118.0.1 and Chromium v118.0.5993.117 on Nobara Linux 38, and Chrome v122.0.6261.89 on iOS—got the same result in all three browsers.

**EDIT 2:** This issue seems to be specific to the pixelfed.social instance. On other instances (e.g. gram.social or metapixl.com) I'm able to browse hashtags as expected.

## Actual result

"Sorry, this page isn't available. The link you followed may be broken, or the page may have been removed. [Go back to Pixelfed.](https://pixelfed.social/)"

## Expected result

Show me photos with that hashtag.

## Screenshots

![screenshot_2024-03-11_112350_pixelfed_hashtags-missing-page_1](https://github.com/pixelfed/pixelfed/assets/163016297/a98c3b69-4a10-41e9-9259-4271bbfe7121)

![screenshot_2024-03-11_112425_pixelfed_hashtags-missing-page_2](https://github.com/pixelfed/pixelfed/assets/163016297/f48da7e1-3a85-4a27-a8fb-ed2d81446cd0)

**Comment by MuhammadSaim** [comment]
@yo-scottie-oh seems like your events are not triggering when you are creating new posts please check your configurations.

**Comment by yo-scottie-oh** [comment]
> seems like your events are not triggering when you are creating new posts please check your configurations.

@MuhammadSaim I'm sorry, but I'm not following. Are you suggesting this may be an issue with my browser settings?

FWIW I've tested in Firefox v118.0.1 and Chromium v118.0.5993.117 on Nobara Linux 38, and Chrome v122.0.6261.89 on iOS—got the same result in all three browsers (I'll edit this info into my OP).

**Comment by MuhammadSaim** [comment]
@yo-scottie-oh its not a browser issue somehow your App is not able to run the Events please verify your App configurations and the installations.

**Comment by yo-scottie-oh** [comment]
> its not a browser issue somehow your App is not able to run the Events please verify your App configurations and the installations.

@MuhammadSaim I'm not an instance owner, just a user of the public facing web site.

**EDIT:** Oh, I think I get it. This issue seems specific to pixelfed.social b/c when I follow the same steps on another instance (e.g. gram.social), I can browse hash tags as expected. Is there a recommended way of contacting the owner of a specific instance?

**Comment by MuhammadSaim** [comment]
Yes, this is the specific issue to pixelfed.social some background jobs are not running that's why they are not able to parse the hashtags from the captions.

**Comment by yo-scottie-oh** [comment]
Gotcha. I've reached out directly via the contact info on pixelfed.social. Thanks for your help.
