### ISSUE TITLE
docker/shared/root/docker/entrypoint.d/12-migrations.sh needs to use the DB port specified in .env. 

### ISSUE THREAD

**Issue by jamespanic** [pixelfed/pixelfed#5023]
The title sums it up. The db startup check doesn't specify the db port so if you use a custom one the startup will hang.

**Comment by jippi** [comment]
@jamespanic  this should be fixed in https://github.com/pixelfed/pixelfed/pull/5035

**Comment by jippi** [comment]
This should be fixed now via #5035
