### ISSUE TITLE
profile picture from Friendica friend not displaying

### ISSUE THREAD

**Issue by wakest** [pixelfed/pixelfed#5026]
how it looks on Pixelfed.social
<img width="403" alt="image" src="https://github.com/pixelfed/pixelfed/assets/7890201/cbae3685-69a3-4cef-bd71-4daf521e12d7">

and how it looks on Friendica
<img width="339" alt="image" src="https://github.com/pixelfed/pixelfed/assets/7890201/a66a3781-f59c-4e9c-96d8-5f89e3bab3ae">

heres the account I am referring to https://friendica.mrpetovan.com/profile/hypolite 
hi @MrPetovan

we have been following each other for a long time as well so its not an issue of time.

**Comment by xundeenergie** [comment]
Can not reproduce this.

My pixelfed shows my friendica-avatar.
