### ISSUE TITLE
package:discover needs database connection

### ISSUE THREAD

**Issue by silsha** [pixelfed/pixelfed#5033]
As of one of today's commits, it appears that `package:discover --ansi' requires a working database connection, which doesn't exist when the container is being built.

```
#13 9.286 Generating optimized autoload files
#13 13.35 > Illuminate\Foundation\ComposerScripts::postAutoloadDump
#13 13.37 > @php artisan package:discover --ansi
#13 13.49 
#13 13.49 In Connection.php line 829:
#13 13.49                                                                                
#13 13.50   SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select *  
#13 13.50    from `config_cache` where `k` = pixelfed.oauth_enabled limit 1)             
#13 13.50                                                                                
#13 13.50 
#13 13.50 In Connector.php line 65:
#13 13.50                                              
#13 13.50   SQLSTATE[HY000] [2002] Connection refused  
#13 13.50                                              
#13 13.50 
#13 13.51 Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

@dansup Since you're working on this right now, I hope this looks "obvious" to you. If not, I'll do some more research later today and get back to you with more details.

**Comment by dansup** [comment]
@jippi We could solve this by setting `ENABLE_CONFIG_CACHE=false` in the docker .env, and later setting to `true`.

Wdyt?

**Comment by dansup** [comment]
@silsha Can you pull the latest commits and try again? Lmk

**Comment by silsha** [comment]
@dansup Unfortunately I still get the same error.
But it is also possible that something in my deployment setup needs to be updated after recent commits.

**Comment by jippi** [comment]
@silsha https://github.com/pixelfed/pixelfed/pull/5035 should hopefully fix this :)

**Comment by silsha** [comment]
@jippi That worked, thanks for the quick fix! :)
