### ISSUE TITLE
Missing env.example file?

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [pixelfed/pixelfed#5039]
Hello, 

The .env.example file appears to be missing. The installation instructions at https://docs.pixelfed.org/running-pixelfed/installation.html reference this file, but it's not available in the current dev branch. 

There is .env.docker and .env.testing, neither of which seem correct for a production non-docker installation.

**Comment by iamperfor** [comment]
It was deleted in v0.11.13 (Mar 5) for some reason 

You can reference .env.example here
https://github.com/pixelfed/pixelfed/blob/1251bf532ceaae0d1a1ce8b689135f5ddf9fbc8b/.env.example

**Comment by dansup** [comment]
Fixed!

**Comment by jSML4ThWwBID69YC** [comment]
@dansup 

Thank you.
