### ISSUE TITLE
Posts that have been reblog share lose icon status

### ISSUE THREAD

**Issue by iamperfor** [pixelfed/pixelfed#5040]
When I boost / share a post, the icon is highlighted. Later (maybe a week), the icon goes back to normal status

Confirmed on Pixelfed Android app and third party app

The share list shows my username so it knows I boosted it

Since web app and mobile apps have the same issue, could be php code causing this?

![pixelfedbrokensharebutton](https://github.com/pixelfed/pixelfed/assets/159505379/c596787b-f7c7-4604-aefe-478b19a62a5c)

**Comment by iamperfor** [comment]
FWIW @dansup this is also a problem on the official Pixelfed app

Same issue with PixelDroid (Android app) and also Phanpy (web app)

**Comment by iamperfor** [comment]
Could the issue reported by @technicat here https://github.com/pixelfed/pixelfed/issues/5059 be related?

**Comment by trwnh** [comment]
> Later (maybe a week)

I think that what is happening is that the old reshare is dropping out of the active window on the home feed. Posts can be reshared multiple times.
