### ISSUE TITLE
Pixelfed Stories wont accept macOS screen recordings (.mov)

### ISSUE THREAD

**Issue by wakest** [pixelfed/pixelfed#5055]
I took a screen recording of a website and uploaded it to my mastodon just fine, then I wanted to post it to my Pixelfed Stories and got this:
<img width="622" alt="image" src="https://github.com/pixelfed/pixelfed/assets/7890201/41460ba6-91eb-4e26-9f00-33e6b95871f2">
Doesn't seem like there is even a way to convert an .mov to an .mp4 without installing another app or importing it into iMovie first which is a whole ordeal.

I have now installed ffmpeg in order to convert it which works with a single argument really easy, this seems like the best way to integrate all sorts of media types people might want to post to their Stories...

**Comment by Wild1145** [comment]
Related to #3614
