### ISSUE TITLE
Collections Bug - Photos count is post count

### ISSUE THREAD

**Issue by Wild1145** [pixelfed/pixelfed#5058]
When viewing a collection that contains posts with multiple photos in the post, the count on the Collection overview appears to be that of posts, not pictures. 

For example https://pixelfedapp.uk/c/690233304775757383 has multiple posts with multiple pictures in and is only showing (at the time of creating this bug) 2 Photos despite there being 8 actually in the collection as they are two posts with 4 photos in each. 

This may be due to legacy setups where only a single photo could be added to a post given some of the other open issues?

**Comment by trwnh** [comment]
Duplicate of #3703
