### ISSUE TITLE
Can't follow/be followed by any accounts

### ISSUE THREAD

**Issue by blacklight** [pixelfed/pixelfed#5081]
Not sure if this is a Pleroma/Akkoma or Pixelfed issue, but my Akkoma account seems able to follow any other accounts except for Pixelfed.

Logs on my Akkoma instance when I try and follow my Pixelfed account:

```
May 07 16:58:38 shannon pleroma[1617067]: 16:58:38.903 [error] Object rejected while fetching https://photos.manganiello.social/users/fabio/following {:strict_id, :error}
May 07 16:58:38 shannon pleroma[1617067]: 16:58:38.903 [error] Follower/Following counter update for https://photos.manganiello.social/users/fabio failed.
May 07 16:58:38 shannon pleroma[1617067]: {:error, :id_mismatch}
May 07 16:58:39 shannon pleroma[1617067]: 16:58:39.647 [error] Object rejected while fetching https://photos.manganiello.social/users/fabio/following {:strict_id, :error}
May 07 16:58:39 shannon pleroma[1617067]: 16:58:39.647 [error] Follower/Following counter update for https://photos.manganiello.social/users/fabio failed.
```

Response I get when I call the `/following` endpoint on my Akkoma profile:

```
❯ http 'https://manganiello.social/users/fabio/following'
HTTP/1.1 200 OK
Content-Type: application/activity+json; charset=utf-8
...

{
    "@context": [
        "https://www.w3.org/ns/activitystreams",
        "https://manganiello.social/schemas/litepub-0.1.jsonld",
        {
            "@language": "und"
        }
    ],
    "first": {
        "id": "https://manganiello.social/users/fabio/following?page=1",
        "next": "https://manganiello.social/users/fabio/following?page=2",
        "orderedItems": [
          ...
        ],
        "partOf": "https://manganiello.social/users/fabio/following",
        "totalItems": 976,
        "type": "OrderedCollectionPage"
    },
    "id": "https://manganiello.social/users/fabio/following",
    "totalItems": 976,
    "type": "OrderedCollection"
}
```

Response I get when I call `/following` for my Pixelfed profile:

```
❯ http 'https://photos.manganiello.social/users/fabio/following'
HTTP/1.1 200 OK
Content-Type: application/activity+json
...

{
    "@context": "https://www.w3.org/ns/activitystreams",
    "id": "http://photos.manganiello.social/users/fabio/following",
    "totalItems": 0,
    "type": "OrderedCollection"
}
```

Not sure if it's the lack of a `first` item or something else that makes Akkoma complain.

It could also be related to https://github.com/pixelfed/pixelfed/issues/3613, as the counter of followed/following users is zero on my Pixelfed profile, but the `show_profile_followers*`/`show_profile_following*` settings are enabled for my Pixelfed user.

Not sure if it could be related to this Pleroma issue too https://git.pleroma.social/pleroma/pleroma/-/issues/2790, but that should have been fixed here https://github.com/pixelfed/pixelfed/pull/3411

**Comment by blacklight** [comment]
Seems also related to https://github.com/pixelfed/pixelfed/issues/1850.

In my case all ActivityPub settings are also enabled:

```bash
ACTIVITY_PUB="true"
AP_REMOTE_FOLLOW="true"
AP_INBOX="true"
AP_OUTBOX="true"
AP_SHAREDINBOX="true"
```

**Comment by blacklight** [comment]
The symptoms are the same as https://github.com/pixelfed/pixelfed/issues/866 too in my case.

And I can also reproduce the issue on Mastodon.

My Pixelfed account: [@fabio@photos.manganiello.social](https://photos.manganiello.social/@fabio)
Akkoma account: [@fabio@manganiello.social](https://manganiello.social/@fabio)
Mastodon account: [@blacklight@mastodon.online](https://mastodon.online/@blacklight)

I can now confirm that my Pixelfed account can't be followed by either my Akkoma and Mastodon accounts - the follow button briefly becomes "Unfollow", but when the page is refreshed it just renders as "Awaiting approval".

No follow notification is received on my Pixelfed account. And fetching the number of followed/following accounts fails on all the ends, despite the `show_profile_follow*` settings set to true for my account, the account being public and federation being enabled.

@dansup any chance you could take a look at this? There seems to be quite a number of issues involving the inability of following Pixelfed accounts, maybe it's worth taking a look a better look at the whole mechanism?

**Comment by blacklight** [comment]
Just tested from the official Pixelfed instance too: same issue.

[@blacklight@pixelfed.social](https://pixelfed.social/@blacklight) can't follow [@fabio@photos.manganiello.social](https://photos.manganiello.social/@fabio) either.

**Comment by ghost** [comment]
```
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "id": "http://photos.manganiello.social/users/fabio/following",
    "totalItems": 0,
    "type": "OrderedCollection"
}
```
Is your Pixelfed URL "http**s**://photos.manganiello.social"?
The URL scheme displayed in the ID field is **http://**.

I think it's probably because the value of APP_URL in the .env file is "http://photos.manganiello.social" that you can't follow/be followed from/by other instances.
Please check the settings in your .env file.

**Comment by dansup** [comment]
As @7shironana correctly pointed out, this is a configuration issue.

**Comment by ghost** [comment]
@dansup 
I also had trouble with the same issue. I would like the default description in the configuration file to be corrected to make it easier to understand.

Example;
```
# Instance URL Configuration
APP_URL="https://example.com"
APP_DOMAIN="example.com"
ADMIN_DOMAIN="example.com"
SESSION_DOMAIN="example.com"
TRUST_PROXIES="*"
```

If there is a separate file called .env.testing for the test environment, I believe that the settings in .env.example should be appropriate for production operations.

**Comment by blacklight** [comment]
@7shironana thanks for the investigation! My `.env` file seems alright though:

```shell
# Instance URL Configuration
APP_URL="https://photos.manganiello.social"
APP_DOMAIN="photos.manganiello.social"
ADMIN_DOMAIN="photos.manganiello.social"
SESSION_DOMAIN="photos.manganiello.social"
TRUST_PROXIES="*"
```

Is there any other setting that can modify the published URL? Or could it be caused by the fact that Pixelfed runs on HTTP and it's proxied over HTTPS via nginx?

**Comment by ghost** [comment]
@blacklight 
I think that probably only the delivery to other instances becomes http. (@dansup doesn't give an accurate answer about how it happened, so it's just a guess)
All you have to do is update the .env file, run the artisan command, and restart nginx just to be sure.
