### ISSUE TITLE
Domain for App-Updates has expired 

### ISSUE THREAD

**Issue by Outlet2048** [pixelfed/pixelfed#5084]
I was gonna download the latest version of the pixelfed app to update my existing app and the app redirected me to this link:

https://dl.apps.pixelcdn.net/pixelfed-android-beta/cwhyoi1dl-v1.0.0.44/pixelfed-for-android-arm64-v1.0.0.44.apk

It seems like the domain has expired
Please consider renewing it before someone else buys it and uses it to distribute unverified apks

"pixelcdn.net
expired on 05/05/2024 and is not available at this time"

**Comment by dansup** [comment]
The domain has been renewed.
