### ISSUE TITLE
Incorrect number of seconds

### ISSUE THREAD

**Issue by Pikamander2** [pixelfed/pixelfed#5093]
Hi there, I used a code search and found an incorrect number of seconds in a day (84600 instead of 86400) listed in one of your files. I recommend fixing it to avoid incorrect timings that could potentially lead to unexpected behavior.

https://github.com/pixelfed/pixelfed/blob/4e023d7a7a78eb15925d46e0e1e19f4231a25fbf/app/Http/Controllers/ProfileController.php#L272

**Comment by dansup** [comment]
@Pikamander2 Thanks for reporting this, while it's not a huge issue as it's only used for the atom feed cache TTL, I will ship a fix!

**Comment by Pikamander2** [comment]
Awesome, glad it's fixed. Thanks for the quick turnaround time.

Credit to Jonathan Rockway @jrockway for the idea: https://news.ycombinator.com/item?id=40393846
