### ISSUE TITLE
Tags in description are not listed on hashtag page

### ISSUE THREAD

**Issue by Nico207** [pixelfed/pixelfed#518]
Hi,

even if I edit a post and add some hashtags in the description, it doesn't appear in the hashtag page.

Thanks.

**Comment by dansup** [comment]
@Nico207 What instance are you on? This could be a deployment issue if the redis job queue is not running.

**Comment by Nico207** [comment]
I'm on pixelfed.social

**Comment by dansup** [comment]
@Nico207 What is the hashtag?

**Comment by Nico207** [comment]
Try with #Arbres

**Comment by dansup** [comment]
@Nico207 Can you confirm the hashtag is ```#Arbres``` and not ```#Arbre``` because I can only find captions with the hashtag ```#Arbre```

**Comment by Nico207** [comment]
Yes `#Arbres`
You can see it here : https://pixelfed.social/p/Nicoledit/5651

**Comment by d1vanloon** [comment]
I think this comes down to the ability to edit the image caption, but not the post description. I've posted an image, then I want to add some hashtags. Unfortunately, the post description is not editable. Only the image caption is editable, and hashtags don't apply there. Maybe a new ticket to make the post description editable would be appropriate.

**Comment by dansup** [comment]
@Nico207 I understand what you mean now, it is not possible to update the post caption and will never be. The description you see on the edit page is to edit the media description, not the caption. In addition, media descriptions that contain hashtags are not parsed either.

**Comment by Vertux** [comment]
I just stumbled over this issue today too. At the moment it looks like, as ii it is impossible to edit a picture afterwards to add some hashtags (tested on [https://pixelfed.social/](https://pixelfed.social/)

![Bildschirmfoto 2019-04-07 um 13 03 59](https://user-images.githubusercontent.com/10457918/55683859-ce948980-5944-11e9-853b-4c6b432d0264.png)

![Bildschirmfoto 2019-04-07 um 13 04 45](https://user-images.githubusercontent.com/10457918/55683863-d3593d80-5944-11e9-844f-bcaa33781304.png)
