### ISSUE TITLE
confirmVerifyEmail doesn't work on PostgreSQL

### ISSUE THREAD

**Issue by carbontwelve** [pixelfed/pixelfed#519]
In the `confirmVerifyEmail ` method  https://github.com/pixelfed/pixelfed/blob/dev/app/Http/Controllers/AccountController.php#L113-L126 the `user_id` returned from `EmailVerification` is incorrectly cast to a string when the database is set to PostgreSQL.

This results in a broken route because `Auth::id()` returns an integer and therefore the absolute comparison `Auth::id() === $verify->user_id` will not evaluate as true.

A few questions come to mind:
* Why does this route require the user be signed in, or authenticated at all? Should it not instead simply look up the user record to be verified by the `$userToken` do so and then redirect to an authenticated route (which will then bounce to login if they aren't already)
* Why is there no default "that `$userToken` wasn't found" response?
* Why isn't this using [signed urls](https://laravel.com/docs/5.6/urls#signed-urls)?

It seems that maybe this is being developed with a MySQL backend, in which case I know from experience the casting of `$verify->user_id` would be correct. However with PostgreSQL its being cast to a string :/

I have fixed it on my install with the following hammy hack `(Auth::id() === (int) $verify->user_id)` but in reality it should be done via [attribute casting](https://laravel.com/docs/5.6/eloquent-mutators#attribute-casting) configured on a per model basis.

I am happy to help out with a PR if you have answers for any of the three questions above.

**Comment by dansup** [comment]
Hi,

> Why does this route require the user be signed in, or authenticated at all? Should it not instead simply look up the user record to be verified by the $userToken do so and then redirect to an authenticated route (which will then bounce to login if they aren't already)

The controller that contains this method has the auth middleware in the constructor, requiring auth for all methods. It could be moved to another controller that doesn't require auth for every method.

> Why is there no default "that $userToken wasn't found" response?

It responds with a 403 (findOrFail()) response when it cannot find a matching userToken/randomToken problem.

> Why isn't this using signed urls?

I've used this in past Laravel projects before, it works ok for our needs. In the latest version of Laravel, they added this feature too. https://laravel.com/docs/5.7/verification#introduction


I do agree that I need to start testing against other database drivers besides MySQL, I don't want to restrict pixelfed to just pg or mysql so I will work on improving this and add a change to models to cast ids as int.

**Comment by carbontwelve** [comment]
> I've used this in past Laravel projects before, it works ok for our needs. In the latest version of Laravel, they added this feature too. https://laravel.com/docs/5.7/verification#introduction

Ah, I didn't know that; useful to know. I have used signed urls for on-boarding thousands of users when rolling a saas app to a new customer. Always had them hit an endpoint that didn't need authentication, but would log them in with a valid on-boarding link and redirect to the welcome tutorials.

>I do agree that I need to start testing against other database drivers besides MySQL, I don't want to restrict pixelfed to just pg or mysql so I will work on improving this and add a change to models to cast ids as int.

From a quick glance at the migrations I am guessing that MariaDB and SQLite support is hindered by the use of json column types. I'm actually surprised that Laravel doesn't cast id's to `int` already - I have had similar problems in the past with tests running against SQLite but the app running in MySQL with number based columns from SQLite being cast as `string` but the same columns from MySQL being cast as `int`... odd.
