### ISSUE TITLE
Site not accessible

### ISSUE THREAD

**Issue by glitchbirdnew** [pixelfed/pixelfed#5202]
Hi, so, after upgrading to the latest version my site is not reachable anymore. I cant even run composer install if the server php is set to 8.2. composer install is working only with 8.3 version. 

composer install with php 8.2

Problem 1
    - Root composer.json requires PHP extension ext-intl * but it is missing from your system. Install or enable PHP's intl extension.
  Problem 2
    - aws/aws-sdk-php is locked to version 3.315.2 and an update of this package was not requested.
    - aws/aws-sdk-php 3.315.2 requires ext-simplexml * -> it is missing from your system. Install or enable PHP's simplexml extension.
  Problem 3
    - spatie/laravel-backup is locked to version 8.8.1 and an update of this package was not requested.
    - spatie/laravel-backup 8.8.1 requires ext-zip ^1.14.0 -> it is missing from your system. Install or enable PHP's zip extension.
  Problem 4
    - tijsverkoyen/css-to-inline-styles is locked to version v2.2.7 and an update of this package was not requested.
    - tijsverkoyen/css-to-inline-styles v2.2.7 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 5
    - laravel/pint is locked to version v1.16.1 and an update of this package was not requested.
    - laravel/pint v1.16.1 requires ext-xml * -> it is missing from your system. Install or enable PHP's xml extension.
  Problem 6
    - phar-io/manifest is locked to version 2.0.4 and an update of this package was not requested.
    - phar-io/manifest 2.0.4 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 7
    - phpunit/php-code-coverage is locked to version 11.0.4 and an update of this package was not requested.
    - phpunit/php-code-coverage 11.0.4 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 8
    - phpunit/phpunit is locked to version 11.2.5 and an update of this package was not requested.
    - phpunit/phpunit 11.2.5 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 9
    - sebastian/comparator is locked to version 6.0.0 and an update of this package was not requested.
    - sebastian/comparator 6.0.0 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 10
    - theseer/tokenizer is locked to version 1.2.3 and an update of this package was not requested.
    - theseer/tokenizer 1.2.3 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 11
    - aws/aws-sdk-php 3.315.2 requires ext-simplexml * -> it is missing from your system. Install or enable PHP's simplexml extension.
    - league/flysystem-aws-s3-v3 3.28.0 requires aws/aws-sdk-php ^3.295.10 -> satisfiable by aws/aws-sdk-php[3.315.2].
    - league/flysystem-aws-s3-v3 is locked to version 3.28.0 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.2/cli/php.ini
    - /etc/php/8.2/cli/conf.d/10-opcache.ini
    - /etc/php/8.2/cli/conf.d/10-pdo.ini
    - /etc/php/8.2/cli/conf.d/20-bcmath.ini
    - /etc/php/8.2/cli/conf.d/20-calendar.ini
    - /etc/php/8.2/cli/conf.d/20-ctype.ini
    - /etc/php/8.2/cli/conf.d/20-curl.ini
    - /etc/php/8.2/cli/conf.d/20-exif.ini
    - /etc/php/8.2/cli/conf.d/20-ffi.ini
    - /etc/php/8.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.2/cli/conf.d/20-ftp.ini
    - /etc/php/8.2/cli/conf.d/20-gettext.ini
    - /etc/php/8.2/cli/conf.d/20-iconv.ini
    - /etc/php/8.2/cli/conf.d/20-phar.ini
    - /etc/php/8.2/cli/conf.d/20-posix.ini
    - /etc/php/8.2/cli/conf.d/20-readline.ini
    - /etc/php/8.2/cli/conf.d/20-shmop.ini
    - /etc/php/8.2/cli/conf.d/20-sockets.ini
    - /etc/php/8.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.2/cli/conf.d/20-tokenizer.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.

Any suggestions?

**Comment by glitchbirdnew** [comment]
Now, I am getting the following 
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0".

**Comment by d1gg** [comment]
Pixelfed docs state "Make sure you are running PHP >= 8.1." and with this version I am having having the issues you mentioned. Going to switch PHP version tomorrow.
