### ISSUE TITLE
API bookmarking posts is not working

### ISSUE THREAD

**Issue by daniebeler** [pixelfed/pixelfed#5216]
Calling the API Route \<baseUrl\>/api/v1/statuses/\<postId\>/bookmark returns the error: "Undefined variable $user"

![Screenshot from 2024-07-11 14-05-57](https://github.com/pixelfed/pixelfed/assets/53303157/ad6e0bba-9ba3-4d2a-adfc-2fb4feadd948)

**Comment by technicat** [comment]
just looking at the code, the problem seems to be this line in the function `bookmarkStatus` in APIV1Controller.php

```php
abort_if($user->has_roles
```

missing the variable assignment that's in the similar section of the favourite function in the same file

```php
$user = $request->user();
abort_if($user->has_roles 
```
