### ISSUE TITLE
Sudo page has incorrect autocomplete hint, causing Safari’s password manager to overwrite the saved password with a non-working one

### ISSUE THREAD

**Issue by daprice** [pixelfed/pixelfed#5258]
The password field on the sudo page has `autocomplete="new-password"` but it should be `autocomplete="current-password"`

Steps to reproduce (in Safari 17.6/macOS 14.6, probably other platforms/browsers too):
1. Navigate to `/settings`
2. Click the link to a settings page that requires authentication, like Applications

Expected result: if you have a saved password, the browser should offer to fill it

Actual result: Because the password field has `autocomplete="new-password"`, the browser automatically populates the password field with a newly generated, non-working password. If you follow the prompts, it will overwrite your saved password with the incorrect one and lock you out of your account.
 
<img width="1386" alt="Screenshot 2024-08-08 at 5 22 03 PM" src="https://github.com/user-attachments/assets/040169b3-933e-42f0-9173-1a3089094cd0">
<img width="652" alt="Screenshot 2024-08-08 at 5 22 30 PM" src="https://github.com/user-attachments/assets/7404b540-1a0a-420d-b010-06e3b33508a5">

**Comment by Zolotkey** [comment]
Tested the PR to fix this issue and it works great. :) 
![Screenshot 2024-08-12 at 11 33 54](https://github.com/user-attachments/assets/9b1f7bdc-0e6e-4add-830b-2a654704f437)
