### ISSUE TITLE
hCaptcha Incorrect Sitekye

### ISSUE THREAD

**Issue by 0xCyberFortress** [pixelfed/pixelfed#5266]
Hello! I'm setting up my instance of pixelfeda. I decided to test out if my email smtp settings were correct or not, so I signed out and went to create a new account and ... I get this error for hcaptcha:

The sitekey for this hCaptcha is incorrect. Please contact the site admin if you see this.

Ok, no biggie, I'll just disable hcaptcha and try again with that later, except ... I don't have another session where I'm logged into my account to access the admin dashboard, and I see no settings whatsoever for this in the .env. In fact, I've found the .env to be missing several settings altogether which are mentioned in the admin panel. I had to manually enter them myself. I've tried various entries to see if any would work, but I'm getting nowhere.

site: https://pixelfed.seceric.io/ you can also find me on mastodon, I pinged your account on there just now as well. I'm eric@mastodon.seceric.io/

**Comment by 0xCyberFortress** [comment]
I saw your message on mastodon, but I'm afraid you misunderstand. I can't login to the site, so I can't access the admin dashboard. I need a way to disable this from the .env or cli.

**Comment by 0xCyberFortress** [comment]
Resolved with: https://gist.github.com/dansup/bf2170bbda3dff2a44a730637cc3f909

Thanks dan!!

**Comment by nikkehsolaris** [comment]
For others who have similar issues; 
I ended up adding the following to my .env file and it worked.
CAPTCHA_SITEKEY=XXXXXX
CAPTCHA_SECRET=XXXXXXX
CAPTCHA_ENABLED=true
CAPTCHA_ENABLED_ON_LOGIN=true
CAPTCHA_ENABLED_ON_REGISTER=true

**Comment by Shizanit** [comment]
> For others who have similar issues; I ended up adding the following to my .env file and it worked. CAPTCHA_SITEKEY=XXXXXX CAPTCHA_SECRET=XXXXXXX CAPTCHA_ENABLED=true CAPTCHA_ENABLED_ON_LOGIN=true CAPTCHA_ENABLED_ON_REGISTER=true

Thanks, same problem.
