### ISSUE TITLE
Error when trying to catch posts of user via API

### ISSUE THREAD

**Issue by kevinveenbirkenbach** [pixelfed/pixelfed#5287]
Hey guys, 

I'm right now on a big adventure and my friends want that I keep them updated via Instagram, Youtube, etc. 
So I'm writing a software to use my fediverse application as SPOT and from there it gets distributed to the centralized social media platforms, to keep everybody updated. 

The software can be found here:
https://github.com/kevinveenbirkenbach/federated-to-central-social-network-bridge

Somehow it leads to this errors when I execute it:

`    ~/R/gith/k/federated-to-central-social-network-bridge    main  python main.py 2024-11-09 2024-12-24 --verbose                                        ✔ 
INFO:root:Retrieving posts from Pixelfed between 2024-11-09 00:00:00 and 2024-12-24 00:00:00.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): picture.veen.world:443
DEBUG:urllib3.connectionpool:https://picture.veen.world:443 "GET /api/v1/accounts/498496141291315201/posts HTTP/1.1" 404 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): picture.veen.world:443
DEBUG:urllib3.connectionpool:https://picture.veen.world:443 "GET /api/v1/instance HTTP/1.1" 200 None
INFO:root:Instance is reachable. URL: https://picture.veen.world/api/v1/accounts/498496141291315201/posts
ERROR:root:Post endpoint not found. Possible issues: incorrect endpoint or user not found. URL: https://picture.veen.world/api/v1/accounts/498496141291315201/posts
    ~/R/gith/k/federated-to-central-social-network-bridge    main  python main.py 2024-11-09 2024-12-24 --verbose                                        ✔ 
INFO:root:Retrieving posts from Pixelfed between 2024-11-09 00:00:00 and 2024-12-24 00:00:00.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): picture.veen.world:443
DEBUG:urllib3.connectionpool:https://picture.veen.world:443 "GET /api/v1/accounts/kevinveenbirkenbach/posts HTTP/1.1" 404 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): picture.veen.world:443
DEBUG:urllib3.connectionpool:https://picture.veen.world:443 "GET /api/v1/instance HTTP/1.1" 200 None
INFO:root:Instance is reachable. URL: https://picture.veen.world/api/v1/accounts/kevinveenbirkenbach/posts
ERROR:root:Post endpoint not found. Possible issues: incorrect endpoint or user not found. URL: https://picture.veen.world/api/v1/accounts/kevinveenbirkenbach/posts
`

For me it's hard to figure out if this is my mistake or an error of the API.

Can you please tell me how to use the API on the correct way, or solve the API bug. 

I also really appreciate links to a good API documentation. Didn't found one :(

Best 

Kevin :)

**Comment by dansup** [comment]
https://beta-preview.pixelfed.io/resources/statuses

**Comment by dansup** [comment]
@kevinveenbirkenbach From the logs, it appears you are trying to fetch posts using the wrong endpoints and parameters, please refer to the documentation regarding this!

**Comment by kevinveenbirkenbach** [comment]
> @kevinveenbirkenbach From the logs, it appears you are trying to fetch posts using the wrong endpoints and parameters, please refer to the documentation regarding this!

Thanks a lot! Yes. Was my mistake! :)

**Comment by dansup** [comment]
Okay, glad you got it resolved! I will close this now!
