### ISSUE TITLE
Notifications for deleted content aren't deleted

### ISSUE THREAD

**Issue by sirber** [pixelfed/pixelfed#5290]
I'm on pixelfed.social. I added a post. I shared it and others liked it. I removed the post, and the notifications remains. 

![IMG_20240908_161519](https://github.com/user-attachments/assets/90af2f12-765e-4530-a0e7-b955cbf5240d)

I'll try to fix it. Could be the cache or database entries.

**Comment by dansup** [comment]
@sirber Are you sure horizon is running?

**Comment by sirber** [comment]
I'm on pixelfed.social, I'm not hosting or running anything. I'll update my post to make it clearer.

**Comment by dansup** [comment]
@sirber Thanks for the update, I am looking into this!

**Comment by sirber** [comment]
I don't see them anymore. Did you change something?

**Comment by dansup** [comment]
@sirber Nope, it turns out nothing was amiss, the job queue was just a bit backlogged. Closing this for now!
