### ISSUE TITLE
Explore Feed Squishes Images

### ISSUE THREAD

**Issue by nikhiljha** [pixelfed/pixelfed#53]
<img width="947" alt="screen shot 2018-05-31 at 11 04 23 pm" src="https://user-images.githubusercontent.com/2773700/40823912-ff705696-6526-11e8-9f9c-9294c6607176.png">
<img width="956" alt="screen shot 2018-05-31 at 11 04 14 pm" src="https://user-images.githubusercontent.com/2773700/40823913-ff88fa16-6526-11e8-9266-35e5cfe903c1.png">

Should be self explanatory, but here are some pictures to illustrate.

**Comment by dansup** [comment]
@nikhiljha Yes, the thumbnail logic needs work.

**Comment by dansup** [comment]
Fixed in latest commits
