### ISSUE TITLE
Is it normal that "Remote Reports" cannot be managed or ignored?

### ISSUE THREAD

**Issue by informapirata** [pixelfed/pixelfed#5332]
I found an anomaly in the Pixelfed moderation panel (ver. 0.12.3)

Currently, in fact, it is impossible to intervene on Remote Reports and it is even impossible to delete or ignore them.

Therefore, for weeks the panel has always shown the same 8 notifications, and if I click on "View", nothing happens…

![image](https://github.com/user-attachments/assets/7b59e115-9b7b-46d5-8582-6a303e442882)

Is this normal or is it an anomaly of my instance? And, if so, is there a way to solve the problem?

**Comment by dansup** [comment]
Looks like a bug, you can press the ID number to load the modal to manage!

**Comment by informapirata** [comment]
I checked just now and I confirm that by clicking on the number I was able to correctly manage the remote reports.

Thank you so much for the support
