### ISSUE TITLE
How to update pixelfed?

### ISSUE THREAD

**Issue by SchBenedikt** [pixelfed/pixelfed#5336]
I run Pixelfeld via Docker.

Now I get an error message saying that I have version 11.3 installed and should update to 12.3 (I only installed Pixelfed today).

How can I perform the update?

Best regards,
schBenedikt
![image](https://github.com/user-attachments/assets/65a1325d-385b-4424-9619-1fcc5c001b9d)

**Comment by dansup** [comment]
https://docs.pixelfed.org/running-pixelfed/administration.html#updating-pixelfed
