### ISSUE TITLE
Pixelfed release needed to help adoption

### ISSUE THREAD

**Issue by sunjam** [pixelfed/pixelfed#534]
Please formally release Pixelfed so it can be installed and maintained without having to use Git.

**Comment by trwnh** [comment]
1.0.0-beta is coming soon; I don't think you need to measure adoption of a pre-release software, as it's much more important to have working software than it is to have released software. You only get one "first release", so it should be a good one!

**Comment by sunjam** [comment]
My interest is in Softaculous adding Pixelfed to their app store.  They do not support manually building off of Github.  Exciting to hear a 1.0.0-beta is in the works!

**Comment by dansup** [comment]
I created a release based on the current "stable" dev commit.

https://github.com/pixelfed/pixelfed/releases/tag/v0.1.9
