### ISSUE TITLE
[Proposal] Notify Admins about new Reports and Messages

### ISSUE THREAD

**Issue by nesges** [pixelfed/pixelfed#5349]
We currently only receive new messages and news if we actively check the admin dashboard. Administrators should be notified when new messages or news are received. In any case in the Pixelfed notifications and optionally also by e-mail.

**Comment by dansup** [comment]
You can configure email notifications for Autospam and User reports.

See https://github.com/pixelfed/pixelfed/blob/4ba350086a6abf6f8993aa326b75da95accdc77f/config/instance.php#L119
