### ISSUE TITLE
Discover suggesting me to follow people who I already follow

### ISSUE THREAD

**Issue by Whaxion** [pixelfed/pixelfed#537]
Also, if I follow on Discover page, the follow button is still there
![issue1](https://user-images.githubusercontent.com/24496063/47617786-44114980-dacb-11e8-95c8-a645af320be8.png)
![issue2](https://user-images.githubusercontent.com/24496063/47617787-44114980-dacb-11e8-9ed9-37613b0b3c91.png)

**Comment by trwnh** [comment]
Discover no longer suggests people, it now suggests posts. Closing
