### ISSUE TITLE
Email confirmation is not working

### ISSUE THREAD

**Issue by tigransimonyan** [pixelfed/pixelfed#5373]
When I send a confirmation email from my server, Gmail marks it as spam and removes the confirmation link. Other platforms send a confirmation link as text under the button for such cases, which the user can copy into the browser.

**Comment by tigransimonyan** [comment]
Also, please add the ability for the admin to mark a user's email address as verified.

**Comment by dansup** [comment]
Fixed!

Btw, you can update to the latest commits, then run

```
php artisan user:verifyemail
```

And then enter the username of the account you want to manually verify the email of!
