### ISSUE TITLE
Compose UI

### ISSUE THREAD

**Issue by letkan** [pixelfed/pixelfed#541]
Another UI improvement: In desktop browser after selecting an image to be uploaded the popup stretches vertically and you need to scroll the window to get to the Create Post button. I think the popup should resize horizontally also repositioning some of the elements so that you don't have to scroll the window in order to see them all.

**Comment by dansup** [comment]
@letkan Have you seen the experimental compose UI? Eventually that will become the default. I will leave this issue open until this gets resolved.

**Comment by letkan** [comment]
> Have you seen the experimental compose UI?
I have, looks good and I know this is WIP.
