### ISSUE TITLE
Add keyword filters for captions and descriptions

### ISSUE THREAD

**Issue by cryptomilk** [pixelfed/pixelfed#542]
Please add a global filter in the settings to filter out all pictures with 'cat' in the caption or description!

**Comment by dansup** [comment]
@cryptomilk Yes, the filter system will be ready soon.

**Comment by aurelienpierre** [comment]
"cat" in the description ? I'm disappointed, I would expect at least an AI with neural networks and deep learning. This is so bayesian spam filter from the 90's :rofl:

**Comment by dansup** [comment]
Moving this to v0.11 since it involves a significant refactor of APIs

**Comment by cryptomilk** [comment]
Why was this closed now?
