### ISSUE TITLE
Automatically Remove EXIF Metadata from Uploaded Images

### ISSUE THREAD

**Issue by 0verk1ll** [pixelfed/pixelfed#544]
To protect user privacy, it would be great if there was an option to remove the EXIF metadata from uploaded images. Mastodon has implemented this feature.

https://github.com/tootsuite/mastodon/blob/0fb0037ca7ea9910b490818a1cc13f4005ba6134/app/javascript/mastodon/utils/resize_image.js

**Comment by trwnh** [comment]
I'm pretty sure this is already done: https://github.com/pixelfed/pixelfed/blob/3b4705b4e023da057cc5c90e988c0e37a05f7984/config/image-optimizer.php#L18

**Comment by dansup** [comment]
@0verk1ll As @trwnh mentioned, pixelfed already strips exif data.

**Comment by fofwisdom** [comment]
The current latest development release version only has variables and doesn't work, is that normal?
![image](https://github.com/pixelfed/pixelfed/assets/205521/83870be8-46d2-49d2-a445-401f91a65508)
![image](https://github.com/pixelfed/pixelfed/assets/205521/7290854b-b4fd-47ae-86f7-ec318c2a50e6)
