### ISSUE TITLE
Embed images in Atom feeds and expose feed link

### ISSUE THREAD

**Issue by Matthias84** [pixelfed/pixelfed#549]
For non fediverse-people, the RSS feed is a easy way to follow artists. Thus I have a few suggestions:

* add RSS Icon on profile page
* Embed images for preview 
```
<description>
    <![CDATA[<img src="http://eu.techcrunch.com/wp-content/uploads/startupbritain.jpg" alt="" />]]>
</description>
```
* broken Links, which refer to comments. e.g. https://pixelfed.social/p/mrsmarshmello/18140/c/18228
(Maybe it's useful to offer an separated feed for comments?)

**Comment by dansup** [comment]
Fixed in latest commits
