### ISSUE TITLE
No displayed number limit when unliking posts

### ISSUE THREAD

**Issue by bremensaki** [pixelfed/pixelfed#55]
Hitting the heart increments the number of likes by one, clicking again removes the like. Further clicks continue to decrement the displayed like count by one with seemingly no bottom limit.

![2018-06-01-16-08-pixelfed social](https://user-images.githubusercontent.com/4737927/40824139-59ed8460-65b6-11e8-8565-41df568532f3.png)

**Comment by dansup** [comment]
@bremensaki This has been fixed in 1d3482a please clear your browser cache.
