### ISSUE TITLE
API for sharing by desktop applications

### ISSUE THREAD

**Issue by Matthias84** [pixelfed/pixelfed#551]
To encourage more (semi)professional photoraphers to share their media with pixelfed, I suggest to simplify the publishing workflow. Usually they use desktop applications to polish their photos and this tools already have publishing features that could be extended to work with pixelfed.

Some examples for applications:
* digikam, gwenview, kphotoalbum,  - by [kipi-plugins](https://github.com/KDE/kipi-plugins) in C++ 
* pix - by [extensions](https://github.com/linuxmint/pix/tree/master/extensions) in C
* Nautilus filemanager - by [extensions](https://github.com/GNOME/nautilus/tree/master/extensions) in C
* Nemo filemanager - by [extensions](https://github.com/linuxmint/nemo-extensions) in python

More over, this could be done easily, by emulating an API of existing portals [like piwigo](https://piwigo.org/doc/doku.php?id=dev:webapi:start). This would also enable a lot of tools to share their media, withoout the need to touch their code.

**Comment by bilelmoussaoui** [comment]
I can help with writing an extension for both Nautilus & Nemo if you can help me with the API part (not sure if it does exists already and how it works)
