### ISSUE TITLE
Compile GD with WebP in Docker image

### ISSUE THREAD

**Issue by dereckson** [pixelfed/pixelfed#556]
WebP support has been suggested in #535.

Currently, the Docker image offers a GD configuration compatible with webp for PHP 5, but not PHP 7, as libvpx has been superseded by libwebp.

See for example this PHP commit: http://svn.php.net/viewvc?view=revision&revision=339664 for the documentation change.

**Comment by dereckson** [comment]
On another hand, if WebP isn't welcome, another solution to remove the unused libxpm packages and the --with-xpm flags.

**Comment by urtzai** [comment]
Sorry for writing here.... I'm trying to build a docker image with the FPM dockerfile to then compose it with nginx, but I get this error when I run it isolated. I'm very new on docker and pixelfed... can you help me please?

[2018-11-29 22:20:19] production.ERROR: symlink(): No such file or directory {"exception":"[object] (ErrorException(code: 0): symlink(): No such file or directory at /var/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:252)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'symlink(): No s...', '/var/www/vendor...', 252, Array)
#1 /var/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(252): symlink('/var/www/storag...', '/var/www/public...')
#2 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/StorageLinkCommand.php(35): Illuminate\\Filesystem\\Filesystem->link('/var/www/storag...', '/var/www/public...')
#3 [internal function]: Illuminate\\Foundation\\Console\\StorageLinkCommand->handle()
#4 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#5 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#7 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#8 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#9 /var/www/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#10 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#11 /var/www/vendor/symfony/console/Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /var/www/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\StorageLinkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /var/www/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 {main}
"} 

   ErrorException  : symlink(): No such file or directory

  at /var/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:252
    248|      */
    249|     public function link($target, $link)
    250|     {
    251|         if (! windows_os()) {
  > 252|             return symlink($target, $link);
    253|         }
    254| 
    255|         $mode = $this->isDirectory($target) ? 'J' : 'H';
    256|

  Exception trace:

  1   symlink("/var/www/storage/app/public", "/var/www/public/storage")
      /var/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:252

  2   Illuminate\Filesystem\Filesystem::link("/var/www/storage/app/public", "/var/www/public/storage")
      /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/StorageLinkCommand.php:35

  Please use the argument -v to see more details.
