### ISSUE TITLE
forgot password abuse

### ISSUE THREAD

**Issue by nadszeg** [pixelfed/pixelfed#56]
hi! i woke up too late and i found out the admin closed the registration... i tried this method where you click on forgot password, type your email address, you get an email where you add your new password and it registered me. after that i could log out and log in back

**Comment by dansup** [comment]
@nadszeg You must have signed up to the reserved username list! You cannot send a password request to an email not associated with a user, you see this error "We can't find a user with that e-mail address.".

**Comment by nadszeg** [comment]
oh okay :) thanks for the info - that could be it that i reserved my username yesterday
