### ISSUE TITLE
Notifications dropdown doesn’t fit the screen (mobile)

### ISSUE THREAD

**Issue by mkljczk** [pixelfed/pixelfed#560]
Device: Pixel 2 XL
Resolution: 2880x1440

![screenshot_20181119-090703](https://user-images.githubusercontent.com/21127288/48693734-bb259380-ebda-11e8-8b70-a4e79e049b46.png)

**Comment by poshaughnessy** [comment]
Same thing here, using Samsung Internet browser:

<img width="408" alt="screenshot_20181119-232251" src="https://user-images.githubusercontent.com/151207/48741236-5574ee00-ec52-11e8-9d9c-a771f695e5d9.png">

I can't scroll over to see them, so it makes notifications impossible to use on mobile.

I can also replicate this in Firefox on the desktop when I activate Responsive Design Mode:

<img width="408" alt="screen shot 2018-11-19 at 23 26 05" src="https://user-images.githubusercontent.com/151207/48741324-94a33f00-ec52-11e8-9080-bbe03c08cc1d.png">

**Comment by dansup** [comment]
Fixed in latest commits.
