### ISSUE TITLE
Mobile zoom on forms

### ISSUE THREAD

**Issue by SnDer** [pixelfed/pixelfed#564]
Please fix the zoom on mobile forms. This can be fixed by putting in the following metatag in the header:

`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />`

**Comment by dansup** [comment]
@SnDer We already have a [viewport meta tag](https://github.com/pixelfed/pixelfed/blob/dev/resources/views/layouts/app.blade.php#L7).

> It's generally recommended that you don't prevent scaling, as that's annoying and potentially an accessibility problem.
[CSS-Tricks on this](https://css-tricks.com/snippets/html/responsive-meta-tag/)
