### ISSUE TITLE
GIF posts have no preview

### ISSUE THREAD

**Issue by SnDer** [pixelfed/pixelfed#567]
The thumbnails for GIFs are not loading.

There is also a little problem with the heart and comment alignment on the explore page.

![Image](https://i.imgur.com/4ZsgnQs.jpg)

**Comment by tie-rack** [comment]
As someone who mostly posts gifs, it's frustrating that my profile page looks so empty and that my images don't display on the discover page.

**Comment by spaceottercode** [comment]
I just wanted to add, besides the Discover and User Profile pages, gif thumbnails will need to be fixed in the My Notification page as well.

- [ ] Discover page
- [ ] User Profile page
- [ ] My Notifications

Thank you.

**Comment by trwnh** [comment]
Should probably mention this is because GIF posts are currently unoptimized, so no thumbnail is generated anywhere.

As for the layout issue on hover, that should be fixed soon:

![image](https://user-images.githubusercontent.com/10606431/57008460-f7abe100-6bb5-11e9-9956-15bb0f8dc348.png)

**Comment by dansup** [comment]
Gif support will be replaced with gifv, we do not plan on supporting gif previews.

**Comment by trwnh** [comment]
Wait, I thought we already agreed on the following:

- non-animated gif gets converted to png
- transparent animated gif remains as gif
- animated gif with no transparency gets converted to video

as for previews, thumbnailer can use first frame or let users select custom frame via the API. But leaving an ugly blank square is a bad idea.

**Comment by glukose** [comment]
A nice and discreet gif icon on the thumbnail would also work like a charm ! 
[gif icon](https://cdn1.iconfinder.com/data/icons/hawcons/32/699575-icon-65-file-gif-512.png)

**Comment by dansup** [comment]
This is intentional, gifs are a deprecated format.

**Comment by dariusj18** [comment]
When you say gif is a deprecated format, in what way?

**Comment by alexopus** [comment]
Reconsider the removal of gif support/auto-conversion. [Relevant discussion](https://github.com/tootsuite/mastodon/issues/6403).
There are cases where gif is still better than video, unless you opt to not compress video at all.
Inclusion of GIFs should be at least a configurable option.

And for previews, at least a single frame should be shown in any case.

**Comment by Casuallynoted** [comment]
If this does happen, a command to automatically convert already updated GIFs to GIFV/MP4 with a thumbnail without having to delete the original post would be really good.

**Comment by spaceottercode** [comment]
gif thumbnails are now generated and supported under the new ui.

**Comment by aneillans** [comment]
Any indication on when gif thumbnails would be supported on the app etc? I've spotted that while they are on the new ui, there are a few places they aren't pulled through (.e.g on the Mastodon federation, app, and a few other places)
