### ISSUE TITLE
[Performance] Discover takes long time to load

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#580]
![image](https://user-images.githubusercontent.com/10606431/48885224-2050d300-eded-11e8-9a26-d7d146bab614.png)

The Discover page takes about 22-23 seconds to load on a fast internet connection (50Mbps down).

**Comment by dansup** [comment]
This is due to inefficient SQL queries. Will fix soon!

**Comment by dansup** [comment]
Fixed in latest commits.
