### ISSUE TITLE
Mailgun eu domains need different API url

### ISSUE THREAD

**Issue by jeroensmeets** [pixelfed/pixelfed#586]
Mailgun has the option to choose European servers. The API url in Pixelfed is (as far as I can see in the code) fixed on their American servers. Can this be an option in the .env file?

`https://api.eu.mailgun.net/v3/` followed by domain name.

**Comment by Whaxion** [comment]
You should watch this https://laravel.com/docs/5.7/mail

**Comment by jeroensmeets** [comment]
@whaxion Thank you very much.
