### ISSUE TITLE
[Bug][UI] Comment permalinks have incorrectly-sized avatars

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#598]
![image](https://user-images.githubusercontent.com/10606431/49001252-c9ffcf00-f121-11e8-9590-daa5207829e9.png)

This is due to the following rule:
```
*, ::after, ::before {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}
```

Disabling those two rules fixes the issue, but likely will have side effects due to other elements expecting border-box. It's inadvisable to set *every* element to border-box, because it means having to subtract padding for everything. Unfortunately, it seems Bootstrap defaults to border-box for everything, so one of the following needs to be done:
a) exact sizing of `width="60px"` must be accompanied with an exact height as well -- `height: auto` assigns the wrong height
b) avatar elements should override bootstrap and declare `box-sizing: content-box`

![image](https://user-images.githubusercontent.com/10606431/49001440-4c888e80-f122-11e8-8633-ded747c89a47.png)

**Comment by carlydotwebsite** [comment]
Seems like this might have been resolved? Below screenshot from Chrome 71:
<img width="575" alt="Image of comment permalink page. The avatar is a circle, not an ellipse." src="https://user-images.githubusercontent.com/267841/50542800-553e0b80-0b8b-11e9-8abe-f80a1859599a.png">

**Comment by trwnh** [comment]
Nope, still happening in Firefox for me.

**Comment by carlydotwebsite** [comment]
Ah, thanks, I was able to replicate it in Firefox. PR incoming.
