### ISSUE TITLE
No word wrapping on post's text caption on individual post page (wraps on character)

### ISSUE THREAD

**Issue by KyleRConway** [pixelfed/pixelfed#619]
This seems to happen only on the post page (e.g. https://pixelfed.social/p/K_REY_C/21126) not the overview page.

Attached is an animated gif showing screen resize and the issue.
![pixelfed-resize-word-wrap](https://user-images.githubusercontent.com/5899012/49456022-db924800-f7ad-11e8-8ff9-0fbf42b7f6fb.gif)

**Comment by trwnh** [comment]
Fixed word-wrap CSS
