### ISSUE TITLE
Menu looks strange on mobile (Android, FF)

### ISSUE THREAD

**Issue by Zatnosk** [pixelfed/pixelfed#62]
![screenshot_20180601-082855](https://user-images.githubusercontent.com/472541/40824960-61335aa0-6576-11e8-9b48-fe9ece0e0613.png)
The menu looks misaligned and as if it's missing text or have too wide buttons.

Android 6.0.1
FireFox 60.0.1

**Comment by dansup** [comment]
Fixed in #113
