### ISSUE TITLE
[UI] Aspect ratio normalization is not consistent

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#638]
Example of a 16:9 video awkwardly floating in a sea of black: ![image](https://user-images.githubusercontent.com/10606431/49937123-699bbc00-fe9b-11e8-8deb-bf2eb85b8d01.png)

But portrait photos physically take up more space and stretch the container: 
![image](https://user-images.githubusercontent.com/10606431/49937184-96e86a00-fe9b-11e8-8f22-2437e46a145b.png)

This is because `.postPresenterContainer` has a `min-height: 600px` applied to it.

https://github.com/pixelfed/pixelfed/blob/ade7a51a4d3202164471e8c5e9f4b848b5d06de2/resources/assets/js/components/Timeline.vue#L349

https://github.com/pixelfed/pixelfed/blob/7209e64bc4254faddfdfef33f9dce39fe5b178d1/resources/assets/js/components/PostComponent.vue#L16

**Comment by dansup** [comment]
@trwnh I added the min-height on the PostComponent so the comment section isn't so small. I also changed the background from white to black to match the IG UI.

**Comment by trwnh** [comment]
@dansup comment section height is independent in the timeline view, where comments are placed below the image container instead of to the side (as in the permalink). Am I to interpret that 1) the timelines will be refactored to start showing comments on the side at larger widths, or that 2) this was only intended for the PostComponent and not the Timeline?

**Comment by dansup** [comment]
@trwnh Fixed in latest commits.
