### ISSUE TITLE
Error when register new user

### ISSUE THREAD

**Issue by andre-dierker** [pixelfed/pixelfed#641]
Pixelfed (0.5.4)
Debian 9
Mysql 5.6
PHP 7.3.0-1+0~20181206202713.23+stretch~1.gbp076afd

I got an error when registering new user, after refresh page everything works like expected. Maybe it's related to https://github.com/pixelfed/pixelfed/issues/482
![selection_003](https://user-images.githubusercontent.com/6938843/49998152-d0040580-ff93-11e8-9d84-79a14c977139.png)

**Comment by dansup** [comment]
@andre-dierker PHP 7.3 is not yet supported by the framework we use.

**Comment by andre-dierker** [comment]
I am building an installer. I switched to 7.2 and got the same issue.

Am 16. Dezember 2018 02:01:57 schrieb daniel <notifications@github.com>:
