### ISSUE TITLE
bcmath is required but not listed in the requirements in the wiki

### ISSUE THREAD

**Issue by Roelofpieter** [pixelfed/pixelfed#642]
Not even an issue: Trying to install pixelfed for testing on my elementaryos laptop. Running `composer install` complained: the requested PHP extension bcmath is missing from your system . After running `apt-get install php-bcmath` installation now continues. bcmath is not listed in the php requirements in the readme.md file

**Comment by CorentinB** [comment]
Just dropped a little PR for this change: https://github.com/pixelfed/pixelfed/pull/651 :)
Thanks for the issue bro.

**Comment by dansup** [comment]
@CorentinB Merged, thanks!
