### ISSUE TITLE
No option to delete account under profile settings

### ISSUE THREAD

**Issue by v7rzlhb3xg** [pixelfed/pixelfed#655]

**Comment by dansup** [comment]
@dar-irl Account deletion will be released soon, it depends on proper federation support to send a ```Delete``` ActivityPub object to every server it knows (to delete data from remote instances).

**Comment by mcrosson** [comment]
@dansup why does this hinge on federation? If I run a non-federated instance I'd need my users to be able to delete accounts.

I sure as hell wouldn't want to hold friends/family/others hostage with account deletions on even a private instance...

**Comment by dansup** [comment]
@dar-irl @mcrosson Please see https://mastodon.social/@dansup/101277093110879701

**Comment by dansup** [comment]
You can delete your account if your instance supports it. Please check the "Your Profile" section in the Help Center of your instance.
