### ISSUE TITLE
Discover page show private pictures

### ISSUE THREAD

**Issue by Whaxion** [pixelfed/pixelfed#656]
On discover page, I tried to click on a picture.
Then, I got a 403 Forbidden. I'm not able to check in database now, but I'm almost sure that it's a private post.
So, you probably should solve that soon.

**Comment by dansup** [comment]
@Whaxion Can you confirm the post or account is actually private? This was fixed about a month ago.

**Comment by Whaxion** [comment]
It looks like it's public, so I don't understand why I get 403 when trying to see it

![](https://i.imgur.com/ugFmCE2.jpg)

```
App\Status {#3329
     id: 501,
     uri: null,
     caption: "CENSURED",
     rendered: "CENSURED",
     profile_id: 133,
     type: "photo",
     in_reply_to_id: null,
     reblog_of_id: null,
     url: null,
     is_nsfw: 0,
     scope: "public",
     visibility: "public",
     reply: 0,
     likes_count: 0,
     reblogs_count: 0,
     language: null,
     conversation_id: null,
     local: 1,
     application_id: null,
     in_reply_to_profile_id: null,
     entities: "{"hashtags":[],"urls":[],"mentions":[],"replyto":null,"hashtags_with_indices":[],"urls_with_indices":[],"mentions_with_indices":[]}",
     created_at: "2018-12-14 10:29:31",
     updated_at: "2018-12-14 10:29:31",
     deleted_at: null,
     cw_summary: null,
   }
```

**Comment by dansup** [comment]
@Whaxion Okay so the post itself is public but the account is private. This is an edge case that will be fixed in upcoming commits.

**Comment by trwnh** [comment]
Does this still happen? I can't replicate this anymore. Please confirm that it has been fixed.

**Comment by dansup** [comment]
@trwnh I can confirm this has been fixed!
