### ISSUE TITLE
Show metadata of posts in admin media view

### ISSUE THREAD

**Issue by Whaxion** [pixelfed/pixelfed#657]
NSFW on media list is also hidden.
I assume it's a bug.

**Comment by dansup** [comment]
@Whaxion NSFW status is already shown as ```content warning``` on media list mode in the admin dashboard.

<img width="1039" alt="Screen Shot 2019-04-12 at 11 14 24 PM" src="https://user-images.githubusercontent.com/877217/56075002-c2f7f700-5d78-11e9-972b-8ca59b1b2bca.png">
