### ISSUE TITLE
Thumbnails 404

### ISSUE THREAD

**Issue by alex-phillips** [pixelfed/pixelfed#660]
Running latest - fresh install. Uploading works successfully and the post page to view the image works, but the thumbnails on the user profile pages are 404ing.

The requested thumbnail URL: `https://pixelfed.example.com/storage/m/2c947e771f8c9b728a8908ee906850bafe029c8f/ac79a644240c89061bcd7f56beb9edb375434ed4/OlPGjNsrwiFjHyxnlObWXKWDSepl04XcNjjGGoXK_thumb.jpeg`

Actual file that exists: `public/storage/m/2c947e771f8c9b728a8908ee906850bafe029c8f/7406a9efd20b83cb13fe7c48b1c983cf432ecfc8/GVW9ayHvnr92fpiHg4m3rPCnOu2ari99QUyHDjju_thumb.png`

**Comment by dansup** [comment]
@alex-phillips Did you run ```php artisan storage:link``` ?

**Comment by alex-phillips** [comment]
I did.

**Comment by alex-phillips** [comment]
@dansup looks like it could be an issue with me symlinking the storage directory? Everything works fine except the thumbnails when I do this, but removing the symlink fixes the issue.

See my dockerfile setup and symlink line here: https://github.com/alex-phillips/docker-pixelfed/blob/master/root/etc/cont-init.d/50-config#L38

**Comment by trwnh** [comment]
@alex-phillips Is this still occurring? If so, the issue can be re-opened.
