### ISSUE TITLE
Follow from mastodon to pixelfed

### ISSUE THREAD

**Issue by severak** [pixelfed/pixelfed#664]
I tried to follow my [pixelfed account](https://pixelfed.social/severak/) from my [mastodon account](https://tiny.tilde.website/@severak) and it obvisously not works.

In mastodon it looks like I requested follow/friendship but in pixelfed there is no notification about it at all.

Also there is no remote follow UI in pixelfed yet.

**Comment by Whaxion** [comment]
It's currently a WIP, full federation isn't ready right now

**Comment by dansup** [comment]
Fixed in latest commits.

**Comment by maznu** [comment]
I must be missing something, then, because I'm on bleeding edge of git, and I can't search from Mastodon for users on my Pixelfed instance. (see also my comment in #674)

```
SNIP - - [25/Dec/2018:23:54:50 +0000] "GET /.well-known/host-meta HTTP/1.1" 200 232 "-" "http.rb/3.3.0 (Mastodon/2.6.5; +https://toot.host/)"
SNIP - - [25/Dec/2018:23:54:50 +0000] "GET /.well-known/webfinger?resource=acct:networkmoose@shared.graphics HTTP/1.1" 404 3436 "-" "http.rb/3.3.0 (Mastodon/2.6.5; +https://toot.host/)"
```

Have I missed something in my nginx configuration? Or is there something meant to go in `.env` to make federation work?

**Comment by maznu** [comment]
…turns out that this is because Pixelfed is looking for users with a case-sensitive match.

**Comment by giromide** [comment]
@dansup Trying to follow [my pixelfed account](https://pixelfed.social/giromide) from [my mastodon account](https://mastodon.social/@pantse_macabre), and mastodon UI tells me that the follow request is pending, though my pixelfed account is not private and shows that my mastodon account is following. Recent avatar change and post to my pixelfed are not appearing in mastodon.

**Comment by mcg** [comment]
Similar issues as @giromide . Trying to refollow some Pixelfed account on a new Pleroma instance and getting "request is pending". Nothing shows up on Pixelfed to approve. Also not seeing Pixelfed profile changes show up on Mastodon.

**Comment by lapineige** [comment]
I have the same issue, with several pixelfed instances (including pixelfed.social), it's impossible to follow some account.
I follow from Mastodon, it's labelled as if it was successful, but if I reload the page, it's in Waiting for approval state.

I know around 10 other people on different Mastodon instance who have the same issue.

On my Pixelfed instance, the number of follower is still 0 even after "following" from Mastodon. And I have no notification to accept that follow request.

**Comment by Zerolemis** [comment]
Same issue here. Trying to follow my own pixelfed account and shows "pending".

**Comment by Vitriia** [comment]
Same issue here (from mastodon to pixelfed)

**Comment by antiorario** [comment]
@dansup You closed this issue a while back, but as far as I can tell it’s still happening (or at least it’s happening on my insteance running 0.11.4). If it is actually fixed, could you add some details on how to make it work? Thanks!

**Comment by mokkun** [comment]
I’m able to follow my Pixelfed from my Mastodon account, but not the other way around.

**Comment by dunn** [comment]
this is probably related to https://github.com/pixelfed/pixelfed/issues/1850
