### ISSUE TITLE
Thumbnail regeneration sometimes fails

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#67]
![image](https://user-images.githubusercontent.com/10606431/40825442-2617e03c-653d-11e8-9dcc-550acce1ffd4.png)

Profile: https://pixelfed.social/claus
Post: https://pixelfed.social/p/claus/160

The thumbnail URL is pointing toward `src="https://pixelfed.social/storage"` rather than something like `src="https://pixelfed.social/storage/m/e64c75f2f4e9a621bb7c43ec9b04a165add6493b/e8033528d3b716f3e92d73c33d483cd7150b3858/1jzFGTGqOeuny9ThAgzUZdtQidLv8Em4HwN11R9k_thumb.jpeg"`. It seems generating and linking to a thumbnail somehow failed.

**Comment by dansup** [comment]
@trwnh I created a cron job that runs hourly to optimize images that failed to optimize. By chance, was that an SVG image?

I will enable the [cronjob](https://github.com/dansup/pixelfed/blob/dev/app/Console/Kernel.php#L27) on pixelfed.social.

**Comment by trwnh** [comment]
It was not an SVG -- seems like a regular JPEG photo, but you'd have to ask claus
