### ISSUE TITLE
Replies don't federate to other instances

### ISSUE THREAD

**Issue by j1t** [pixelfed/pixelfed#673]
A reply to a comment doesn't federate.

**Comment by xmgz** [comment]
In my opinion, it does federate. The message shows up on public TLs, but when clicking on "Reply" the recipient handle (from other servers) get double "@"

like
`@@user@fediverse.server`

I've tried to reply using

user@fediverse.server
@user@fediverse.server

None of the three formats notifies the external user about the reply

Just for inform you and add real use context. Thank you.

**Comment by trwnh** [comment]
They do now!
