### ISSUE TITLE
Federation doesn't work for test account

### ISSUE THREAD

**Issue by jeroenpraat** [pixelfed/pixelfed#674]
Federation with the account @jeroentest@pixelfed.social is for the most part not working. I tested it with 2 accounts on todon.nl and 1 account on newsbots.eu (both no difference in behavior). 

Posts

- image posts from Mastodon are not seen on Pixelfed
- posts from Pixelfed are not seen on Mastodon, only when I fetch the post with the url manually (in the search field of Mastodon) it shows up.

Liking/commenting

- liking a Pixelfed post from Mastodon does work (incl. notifications)
- commenting does not work

Avatars

- avatars are not fetched

Following

- can follow from Mastodon, seen on Pixelfed in the follower list (but not a notification)
- when refresh browser window on Mastodon the follow button in the web-app shows a ⏳ (it waits on approval), but on Pixelfed private account is disabled (also no follower request showing). 
- when unfollowing from Mastodon, the list of followers on Pixelfed is not updated
- can follow Mastodon accounts from Pixelfed (using the follow button in the follower list), but not seen on Mastodon

Searching remote Mastodon accounts

- can't find a remote Mastodon account using search (like: @user@instance.tld)
-  but can find the Mastodon user after this user liked a post on Pixelfed (when searching only the username)

**Comment by ajdunevent** [comment]
I'm having many of these same issues.
I did not get the hourglass when following my Pixelfed (@ajdunevent@pixelfed.social) account from my Mastodon account (@ajdunevent@linuxrocks.online) initially today but (after testing if my followers on Pixelfed got updated when unfollowing from Mastodon then refollowing my Pixelfed account from Mastodon) I do now.

**Comment by maznu** [comment]
I'm unable to search in Mastodon for myself on Pixelfed.  My Pixelfed instance (manually installed, tracking the github repo) is getting a 404 error for the WebFinger URL, but the host-meta is ok:

```
SNIP - - [25/Dec/2018:23:54:50 +0000] "GET /.well-known/host-meta HTTP/1.1" 200 232 "-" "http.rb/3.3.0 (Mastodon/2.6.5; +https://toot.host/)"
SNIP - - [25/Dec/2018:23:54:50 +0000] "GET /.well-known/webfinger?resource=acct:networkmoose@shared.graphics HTTP/1.1" 404 3436 "-" "http.rb/3.3.0 (Mastodon/2.6.5; +https://toot.host/)"
```

I'm guessing I've got something set up wrongly, but as far as I can tell from what I saw in #378 I've got nginx set up correctly.

**Comment by maznu** [comment]
> I'm guessing I've got something set up wrongly, but as far as I can tell from what I saw in #378 I've got nginx set up correctly.

Turns out that this is because Pixelfed is searching for users case-sensitively. D'oh, silly me!

**Comment by jeroenpraat** [comment]
In the meantime I have set-up my own Pixelfed instance and am testing with @jeroepraat@pixelfed.nl. Everything works, except federation is partly a problem.

This works:

  * Can follow Pixelfed account from Mastodon and it arrives on Pixelfed
  * Pixelfed posts are federated with Mastodon
  * Can favorite this post from Mastodon and it arrives on Pixelfed
  * Can reply on this post from Mastodon and it arrives on Pixelfed
  * Favorites and replies (from other Mastodon instances and Pixelfed) are displayed on Mastodon

This doesn't work:

  * Can follow Mastodon account from Pixelfed, but it doesn't arrive on Mastodon (no notification, not listed as follower)
  * Can't follow remote Pixelfed accounts (from pixelfed.nl to pixelfed.social and back)! 
  * Image posts from Mastodon won't arrive on Pixelfed (but I suspect this isn't implemented yet)

**Comment by dansup** [comment]
@jeroenpraat Outbound follows (ie: pixelfed -> pixelfed/mastodon/pleroma) has a few bugs that will be fixed in the v0.8.0 release

**Comment by jeroenpraat** [comment]
I had to re-open this issue, becayse 0.8.0 RC1 (current code in dev) has a regression.

* can follow from Mastodon, seen on Pixelfed in the follower list (but not a notification)

* when refresh browser window on Mastodon the follow button in the web-app shows a hourglass_flowing_sand (it waits on approval), but on Pixelfed private account is disabled (also no follower request showing).

* when unfollowing from Mastodon, the list of followers on Pixelfed is not updated

Because of this (follower can't (and shouldn't) be approved) posts are arriving on Mastodon, but not on the home timeline (only on federated timeline and pixelfed user's timeline).

**Comment by jeroenpraat** [comment]
Works now! Thanks!
