### ISSUE TITLE
[API] - Some remarks about returned values

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#689]
Hello there,

First, I want to thank you for your work with the API. I tested a point yesterday and it works great. I just noticed few elements, that might be fixed.

- The date format for created_at doesn't seem to follow: `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`
- ~~Is it possible to return empty values instead of `null`?~~
- Make the endpoint `/timelines/public` accessible without token
- Lower case the first letter for media type: `"type":"Image"`
- For default avatar, it would be nice to have a png version.
- Gif images return type "image", that's quite a problem for playing them in a video player (we can't detect them).

If you want me to drop separated issues for each element, let me know.

**Comment by dansup** [comment]
> The date format for created_at doesn't seem to follow: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

Pixelfed uses ISO 8601 timestamps.

> Make the endpoint /timelines/public accessible without token

That will be possible soon.

> Lower case the first letter for media type: "type":"Image"

We use [ActivityStream verbs](https://www.w3.org/TR/activitystreams-vocabulary/#object-types), part of ActivityPub.

> For default avatar, it would be nice to have a png version.

We will be deprecating the current svg avatars in favour of a single default avatar png in a future release.

> Gif images return type "image", that's quite a problem for playing them in a video player (we can't detect them).

We do not transcode gifs to videos or gifv at the moment.

**Comment by sschueller** [comment]
Is there an API documentation already or planned layout? All I found was what's defined in here: https://github.com/pixelfed/pixelfed/blob/137788b00c64e382d43655ef3714ec49a09f7397/routes/web.php#L35.

Also will authentication be possible with a token? Right now I can only authenticate and use the API with a cookie.

Something like https://docs.joinpeertube.org/api.html would be great.

**Comment by ghost** [comment]
> Is there an API documentation already or planned layout?

@sschueller The API should be similar to this of Mastodon: https://docs.joinmastodon.org/
