### ISSUE TITLE
Hashtag pages avatar is blank

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#69]
https://pixelfed.social/discover/tags/cat
![image](https://user-images.githubusercontent.com/10606431/40825634-cd61d974-653d-11e8-9b92-bebc36c04258.png)

**Comment by trwnh** [comment]
```
<@dansup> yes they should, just like IG
<@dansup> I haven't finished the algorithm that picks the best one yet
```

TIL.  Example Instagram tag page: https://www.instagram.com/explore/tags/sunset/

The avatar actually links to a story of popular posts with that hashtag.

**Comment by dansup** [comment]
Fixed in latest commits
