### ISSUE TITLE
Deprecated filters in PHP 7.3

### ISSUE THREAD

**Issue by hnrd** [pixelfed/pixelfed#691]
Hi,
so `app/Util/ActivityPub/Helpers.php:139` reads:

    $valid = filter_var($url, FILTER_VALIDATE_URL, FILTER_FLAG_SCHEME_REQUIRED|FILTER_FLAG_HOST_REQUIRED);

Which leads to failed jobs on incoming ActivityPub messages:

ErrorException: filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated

As Dockerfile.apache specifies php:7-apache as it's base, PHP 7.3 is used. (See [Dockerhub](https://hub.docker.com/_/php?tab=tags))

Quickfix: Use php:7.2-apache as base, which mitigates the exception, but as soon as more distributions switch to 7.3 the issue will widen.

**Comment by dansup** [comment]
PHP 7.3 is not supported by Laravel or pixelfed yet.
