### ISSUE TITLE
error 500 when getting api/v1/timelines/* or api/v2/*

### ISSUE THREAD

**Issue by salvadorpla** [pixelfed/pixelfed#694]
My instance throws 500 error when getting:

/api/v1/timelines/public?page=1
/api/v1/timelines/home?page=1

and

/api/v2/comments/*
/api/v2/profile/*
/api/v2/discover/posts

I did try a fresh install following https://github.com/pixelfed/pixelfed/blob/dev/README.md and by using also a new fresh database but same errors.

No errors when accesing:

/api/v1/notifications
/api/v1/accounts/verify_credentials

Any clue?
Thank you

**Comment by FranzShaach** [comment]
Got rid of this by removing the comma after **`StatusTransformer`** at **app/Http/Controllers/PublicApiController.php** line 22. PHP 7.1 if it helps.

**Comment by salvadorpla** [comment]
@FranzShaach oh nice! that solve it! Thanks!
Closing this.

**Comment by salvadorpla** [comment]
I was getting error 500 when trying to get api/v2/discover/posts but thanks to @FranzShaach figure out how to solve it too:
- by removing extra comma after **UserFilter** at **app/Http/Controllers/InternalApiController.php** line 16
- by removing extra comma after **StatusTransformer** at **app/Http/Controllers/InternalApiController.php** line 23.

Now errors 500 are gone ;-)

**Comment by salvadorpla** [comment]
Just updated to 0.10.6 and this issue reappeared again

**Comment by trwnh** [comment]
It seems to work fine in most other deploys, with no changes. FWIW Pixelfed soft-requires PHP 7.3, and previously soft-required 7.2, so PHP 7.1 would be unsupported. Presumably it *could* work with some other modifications on lower PHP versions, but this is currently out-of-scope.
