### ISSUE TITLE
My profile shows no posts

### ISSUE THREAD

**Issue by jonnybarnes** [pixelfed/pixelfed#695]
I tried setting up my own instance of pixelfed ad https://pixelfed.jonnybarnes.uk

If I log in and go to the home page it shows my account as having 3 posts, and indeed shows them

<img width="1001" alt="screen shot 2018-12-26 at 20 30 04" src="https://user-images.githubusercontent.com/108303/50456545-1e7ab200-094d-11e9-9fc4-52065f22a848.png">

However, going to the any of the indiviual posts results in a post not found page, then clicking through the `@jonny` link says I have no posts yet, and has a different profile picture

<img width="683" alt="screen shot 2018-12-26 at 20 32 20" src="https://user-images.githubusercontent.com/108303/50456580-5e419980-094d-11e9-9593-b09d931dcf11.png">

Anyone know what’s going on?

**Comment by dansup** [comment]
@jonnybarnes When you created the posts, did you change the visibility from public?

**Comment by jonnybarnes** [comment]
@dansup nope, they are all set to visible

If I try and view an individual post I get a post not found page with a cute gif. Doing a little debugging its happening at this line: https://github.com/pixelfed/pixelfed/blob/dev/app/Http/Controllers/StatusController.php#L28

**Comment by dansup** [comment]
@jonnybarnes I can't reproduce this, and there is something wrong with your instance.

**Comment by SinaCutie** [comment]
This is also happening on my instance for one of my users, but not for myself.

**Comment by SinaCutie** [comment]
This is also happening on my instance for one of my users, but not for myself. All of their posts are public.

Additionally, their post shows up in the Public timeline, but not on their own profile. Clicking the image in Explore and in the public timeline brings up the "Page Not Found" as per the OP.

![screenshot_20190108_101042](https://user-images.githubusercontent.com/44652241/50818059-bd27eb00-131d-11e9-9888-149ddc045b88.png)
![screenshot_20190108_101124](https://user-images.githubusercontent.com/44652241/50818061-bdc08180-131d-11e9-9ffe-f60038687a14.png)
![screenshot_20190108_101137](https://user-images.githubusercontent.com/44652241/50818063-bdc08180-131d-11e9-9c26-9852c384c16e.png)
![screenshot_20190108_101101](https://user-images.githubusercontent.com/44652241/50818060-bdc08180-131d-11e9-962c-e1b908009d43.png)

**Comment by jonnybarnes** [comment]
I don’t really have any actual pictures on my instance yet, this weekend I’ll redeploy and see if I can get a working instance.

**Comment by jonnybarnes** [comment]
Just adding, I don’t know what I’ve done other than the server being restarted a few times, and updating to `v0.7.10` recently. But posts are displaying as I’d expect… 🤷‍♂️
