### ISSUE TITLE
Pixelfed account can't be found from Mastodon

### ISSUE THREAD

**Issue by Findus23** [pixelfed/pixelfed#699]
similar to #674, but I can't even get the account to show up in Mastodon.

Hi, this has absolutely no urgency, but maybe by reporting more details it helps to fix federation bugs.

I have recently set up a pixelfed instance using PHP 7.2 on debian. (https://photos.lw1.at/)
Everything seems to be working fine locally, but I can't get any of the federation features to work.

When I search for `@lukas@photos.lw1.at` in Mastodon I get the following requests in the access.log, but nothing is found.
```log
88.99.14.81 - - [27/Dec/2018:15:30:07 +0100] "GET /.well-known/webfinger?resource=acct:lukas@photos.lw1.at HTTP/1.1" 200 725 "-" "http.rb/3.3.0 (Mastodon/2.6.5; +https://mastodon.lw1.at/)"
88.99.14.81 - - [27/Dec/2018:15:30:07 +0100] "GET /users/lukas HTTP/1.1" 302 364 "-" "http.rb/3.3.0 (Mastodon/2.6.5; +https://mastodon.lw1.at/)"
88.99.14.81 - - [27/Dec/2018:15:30:07 +0100] "GET /lukas HTTP/1.1" 200 2157 "-" "http.rb/3.3.0 (Mastodon/2.6.5; +https://mastodon.lw1.at/)"
```

Some other things that might be relevant:
- I am using nginx with a config similar to the recommended one (`/.well-known/webfinger` seems to work fine)
- I am using Mariadb `10.3.11` and didn't had any issues during setup or needed workarounds like in #132
- I have only tested my Mastodon instance, so it is of course also possible that the issue is there, but I think it is unlikely as I can follow `@earth@pixelfed.social` without issue. 
- There are no errors in the PHP error log
- There are no errors (apart from misspelled commands by me) in the `storage/logs/laravel.log`
- horizon is running (btw: What's the recommended way to make sure it is running all the time? Should I create a systemd service?)
- I am using the latest master (so 6c2ead051660419099f9b21364d37c7f7584ce1e)
- I ran `php artisan cache:clear` after upgrading to be sure there is nothing outdated left

If someone has a similar issue, please comment, so the source of the error can be narrowed down. 
If you need more details, just comment.

**Comment by noplanman** [comment]
Have you set `ACTIVITY_PUB=true` in your `.env` file?

Because it looks like the follow isn't being posted to your instance.

**Comment by trwnh** [comment]
if your issue is solved, then you can close it :)

**Comment by jeroenpraat** [comment]
@trwnh @dansup I see more than one settings related to AP in config/pixelfed.php

```
    'remote_follow_enabled' => env('REMOTE_FOLLOW', false),
    'activitypub_enabled' => env('ACTIVITY_PUB', false),

    'ap_inbox' => env('ACTIVITYPUB_INBOX', false),
    'ap_shared' => env('ACTIVITYPUB_SHAREDINBOX', false),
```

Shouldn't they all set to 'true' ?

**Comment by jeroenpraat** [comment]
With all these set to true, I still have not working federation with my own Pixelfed instance. I think this issue needs to be reopened.

**Comment by jeroenpraat** [comment]
@trwnh That doesn't make any difference.

**Comment by jeroenpraat** [comment]
Federation now works partly for me now.  The account @jeroenpraat@pixelfed.nl can be found from Mastodon.
