### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by dansup** [pixelfed/pixelfed#7]
- [x] Project website (pixelfed.org)
- [ ] Nice landing page 
- [ ] First time login tour

**Comment by trwnh** [comment]
>Right after creating an account and confirming its email address, the user enters Pixelfed to an empty timeline and no directions.
>
>Possible improvements: (I'm aware some are massive new features!)
>
> - Display the "Discover" tab to start
> - Encourage the user to post their first picture
> - Encourage the user to go take a look at the local timeline of the current instance (but only if there are posts in there! Redirecting to an empty local timeline is not better! haha!)
> - Offer a way to import/find friends from Mastodon and other social network (I don't know if that's possible)
> - Encourage the user to fill their profile
> - Display a list of popular accounts to follow
> - Display a list of popular bots posting beautiful pictures
> 
> I think implementing at least 1 or 2 of the easy ones in this list would make for a much better onboarding experience!

https://github.com/pixelfed/pixelfed/issues/794#issue-402477897
