### ISSUE TITLE
Confirm deletion UI/UX

### ISSUE THREAD

**Issue by spaceottercode** [pixelfed/pixelfed#702]
When deleting a post, it might be advantageous to give the user the ability to bail out. Possibilities that come to mind are clicking or tapping outside the popup aborts the request, or a cancel button. What do you guys think?

**Comment by spaceottercode** [comment]
@cmho Thank you Carly! Closing this one out as soon as @dansup gives 👍

**Comment by dansup** [comment]
Added in #718
