### ISSUE TITLE
Private/Followers-Only post not visible to author outside the Home Timeline

### ISSUE THREAD

**Issue by spaceottercode** [pixelfed/pixelfed#703]
## Summary
I get the impression the PixelFed team may already be aware of this issue but to be safe I am reporting/documenting it here. Note this could be related to #695 but the title makes it unclear if so.

## Reproduce
To reproduce upload an image using the older upload dialog. Set the Visibility to Followers Only. 

For public accounts:

Image only appears in the Home Timeline. It does not appear in your gallery. The post tally is properly incremented.

For private/locked accounts:

Neither the Home Timeline or gallery are updated. Tallies are. Unlocking a locked account will cause the follwers-only post to appear in the Home Timeline again.

## Expectation

Image/video to be visible in one's own gallery view.

tested on pixelfed.social v 0.7.7 on Firefox

**Comment by trwnh** [comment]
This got fixed at some point, so closing!
