### ISSUE TITLE
[Enhancement] Set the default visibility of posts to Followers Only for (and when) locked/private accounts 

### ISSUE THREAD

**Issue by spaceottercode** [pixelfed/pixelfed#704]
I think it's pretty common for people new to the fediverse to think: my account is private => my posts are private, my account is public => my posts are public. Especially if they're coming from IG. This request alleviates some of that by defaulting the Visibility option in the upload dialog to Followers Only whenever the account is locked. Users are free to set the Visibility to whatever while authoring their post. Not to mention, should a user not set it, I would rather a private account err on posting an image or video as private/followers-only than public.

notwithstanding, former IG users need to be aware that locking does not grandfather/retroactively apply to prior posts. That is, public posts remain public. once public, always public.

**Comment by ghost** [comment]
A setting for your default that automatically changes (like Mastodon) when you lock your account could be a helpful version of this, but we absolutely agree.

**Comment by ghost** [comment]
(That kind of granular control could also be very nice for those who never want to post to public timelines, but are fine with any followers, for example.)

**Comment by spaceottercode** [comment]
Thank you @Fidgetcetera. For now, my request is just to default the Visibility option in the upload dialog box to Followers Only when the account is locked.

(atm I'm not a big fan of Mastodon's default privacy settings.)

**Comment by dansup** [comment]
@spaceottercode I agree this should have already been added. Will fix soon!

**Comment by spaceottercode** [comment]
@dansup Thank you 🙌

**Comment by dansup** [comment]
@spaceottercode Fixed in #1136 !
