### ISSUE TITLE
[Enhancement] Automatically Delete Posts after X Months

### ISSUE THREAD

**Issue by 0verk1ll** [pixelfed/pixelfed#708]
To save storage space on servers and protect user privacy. There could be an option in settings where users can automatically delete their posts after X amount of time. The time should probably be at least one week to avoid abuse and harrassment like on Yik Yak.
A picture of a trip to a shopping mall or sports event is unlikely to be needed at a later point, so removing it can protect users against bad actors retroactively creating a detailed profile of their activities.

**Comment by SnueSnue** [comment]
This has been marked as completed, but I can't figure out, how to turn it on and when researching how to, I only found conversations where people said it wasn't implemented. 

Is it implemented ?

I think it is an important feature, so it would be nice to have it implemented :)
