### ISSUE TITLE
[Enhancement] Option to automatically unfollow unfollowers

### ISSUE THREAD

**Issue by spaceottercode** [pixelfed/pixelfed#710]
Among one of the most annoying and antisocial behaviors rampant in IG are accounts that follow you relying on the target's good will & reciprocity only to silently unfollow the target all in the name of boosting their numbers. While PixelFed does not prioritize accounts, this practice erodes trust (second guessing). Note people engaging in this practice may in fact contain content that interests the target (bait). Many social networks make no announcement  when someone unfollows you,  and I'm guessing that's for very valid reasons, so instead I'm proposing an option that is toggled off by default but when toggled on it silently removes an unfollowing followed account.

PS submitting this request with pixelfed 1.0 or later in mind

**Comment by trwnh** [comment]
This would also place extra anxiety on people who decide to unfollow you, though. I don't think there should be any pressure on who you follow; if the concern is with followbots, then I think it'd be much better to simply not follow any accounts you don't find interesting in the first place. There should not be any expectation of reciprocity in following others; that follow-for-follow / followback behavior is ideally something that should not be emphasized or supported by default.

**Comment by spaceottercode** [comment]
It's an option that I recommend off by default. It would be a decision in the hands of the account owner. And yes the removal should pretty much be silently done,  behind the scenes sans any announcement to reduce concerns.

**Comment by dansup** [comment]
Shipped in latest commits
