### ISSUE TITLE
Add more robust setup instructions for developers

### ISSUE THREAD

**Issue by carlydotwebsite** [pixelfed/pixelfed#713]
A few things I've found could use clarification, based on figuring out how to set up the development environment for QA on my local machine:

* Using the Homestead VM with Pixelfed
* Setting up configuration for the site in Homestead
* Installing Redis in Homestead
* Updating the nginx site configuration file
* Opening the application from the VM in a browser

(As an aside, I've gotten through all of the above, but I keep getting a 419 error ("Sorry, your session has expired. Please refresh and try again.") when trying to register an account.)

**Comment by swentel** [comment]
> (As an aside, I've gotten through all of the above, but I keep getting a 419 error ("Sorry, your session has expired. Please refresh and try again.") when trying to register an account.)

I've had that problem too. Can't tell anymore how I got around it, but I remember hacking into Http/Controllers/Auth/RegisterController.php ::register - not sure anymore exactly what I commented out, but at some point, I saw a user entry in the db and I could login. I manually updated this user also in the db to be admin (set is_admin to 1)

**Comment by carlydotwebsite** [comment]
@swentel I did eventually fix it—the problem for me seemed to be needing to remove the quotes around APP_DOMAIN and ADMIN_DOMAIN in the .env file. I also switched the cache method to `cookie` from `redis`, but I don't know if that did anything.

**Comment by hellcp** [comment]
We should probably have a variable somewhere to switch between production and development environment, and set default to be development, so the developers don't have to mess around with env file. The commands for setting up development environment should be in CONTRIBUTING.md when that happens.

**Comment by cronburg** [comment]
I'm having a similar issue with getting 419 errors upon trying to register an account on a freshly installed pixelfed instance. I've followed the WIP documentation for configuration and installation. Is there any documentation somewhere yet to help with debugging any common misconfiguration issues? Or at least, what setting can I change or command can I run to narrow down the source of my issue?

**Comment by trwnh** [comment]
@cronburg I think you can try `php artisan self-diagnosis`? But 419 error sounds like bad auth, and may be due to proxying errors.

**Comment by cronburg** [comment]
@trwnh Thanks, that helped in other respects (I was missing locales and cached versions). What fixed it for me though was remembering to set `SESSION_DOMAIN=dev.example.com` appropriately: https://stackoverflow.com/a/54561833/1542000. Laravel seems to trigger a 419 error when the domain you're serving on doesn't match the value of `SESSION_DOMAIN`.
