### ISSUE TITLE
Cannot Favourite Posts Without Changing Page

### ISSUE THREAD

**Issue by BrainBlasted** [pixelfed/pixelfed#72]
Currently when clicking the favourite button, pixelfed takes you to the page of the favourited item, which is quite jarring. Video [here](https://peertube.xyz/videos/watch/31c0c415-84b9-4565-ad47-b22797c33df0).

**Comment by jordan31bit** [comment]
I agree, was a little strange to be taken to the post to fav it.

**Comment by dansup** [comment]
See #87
