### ISSUE TITLE
Disable rate limitation (i.e. throttle) for entire site

### ISSUE THREAD

**Issue by gslin** [pixelfed/pixelfed#721]
I would like to ask if we can have this feature to disable rate limitation completely (i.e. throttle), because I hit this issue (code 429) quite often, even just in installation.

**Comment by idanoo** [comment]
Might be unrelated but I get that when I try to click "verify account" :thinking:

**Comment by dansup** [comment]
@gslin Yes, I will make the rate limiting optional and set more realistic limits by default. You can clear rate limits by running ```php artisan cache:clear```

**Comment by dansup** [comment]
Rate limits have been removed in the latest commits.
