### ISSUE TITLE
Add vue-loader to package.json tagged at 14.2.2

### ISSUE THREAD

**Issue by carlydotwebsite** [pixelfed/pixelfed#728]
Assets can't be compiled without a version of vue-loader installed, and vue-loader 15+ doesn't work very well with laravel-mix since it requires extra configuration.

**Comment by dansup** [comment]
vue-loader will be removed in an upcoming commit! Bootstrap and vue-infinite-scroll both support it so it isn't needed anymore.

**Comment by dansup** [comment]
Fixed in latest commits!
