### ISSUE TITLE
Filter effects do not federate to Mastodon

### ISSUE THREAD

**Issue by renatolond** [pixelfed/pixelfed#730]
If you choose a filter effect to be applied to pictures, the picture itself is federated to Mastodon, but no effect is applied.

Original: https://pixelfed.social/p/renatolond/28081
Federated: https://masto.donte.com.br/@renatolond/101346251505180944

**Comment by carlydotwebsite** [comment]
I think this is because currently the filters are being applied as CSS classes with blend modes, but it seems like it's possible to do something similar to instagram's filters with Imagemagick: https://code.tutsplus.com/tutorials/create-instagram-filters-with-php--net-24504

**Comment by dansup** [comment]
@renatolond What @cmho said is true, we are using CSS filters for now. In the near future we will be handling that server side and filters will federate properly.

**Comment by carlydotwebsite** [comment]
@dansup if no one's started work on this yet, I have a few of the filters figured out in imagemagick and can start trying to implement it into the workflow; it just doesn't have super good performance yet

**Comment by dansup** [comment]
Added in 0a5a0e86
