### ISSUE TITLE
Account creation hiccups

### ISSUE THREAD

**Issue by CR0CKER** [pixelfed/pixelfed#732]
I initially created an account on pixelfed.social, but never received an activation email. @dansup then manually confirmed my email address and I started using my account and uploaded photos. At some point, I got logged out and then received the error "These credentials do not match our records." whenever I tried to log in with my email address, even though I was still logged into the account on another device. Once the session on that other device also timed out, I was unable to log in at all. When I tried to reset my password by clicking "Forgot Password" on the login page, I received the same error ("We can't find a user with that e-mail address."). 

Suddenly today, trying again to reset my password, I got the message that a reset link had been emailed (using the same email address that had previously been rejected as non-existent). I receive the email and reset my password. I then logged in, but instead of regaining access to my old account, Pixelfed had created a new account with a new username and no photos in it. 

Now, I have a new account that's attached to my email address with a username I didn't choose, and still cannot access my old account which either uses the same email address or no email address at all.  Since login and password reset are only possible using an email address, I have no idea how to regain access to the username I had initially registered and would like to continue using. 

Edit: I am happy to share my account details in PMs with @dansup but do not want to post them here publicly.

**Comment by dansup** [comment]
@CR0CKER This isn't the right place to report instance level issues. Please DM https://mstdn.io/@pixelfed in the future.

If you noticed a new username, it is probably because it was restricted but not enforced when you signed up.
