### ISSUE TITLE
The first hashtag is federated to Mastodon, but all the other are not, and are not tagged in the body

### ISSUE THREAD

**Issue by renatolond** [pixelfed/pixelfed#734]
Posts containing hashtags can be searched on the first hashtag, but the hashtags are not marked in the post body, and every other hashtag but the first is not searchable
Pixelfed : https://pixelfed.social/p/renatolond/28634
Mastodon : https://masto.donte.com.br/@renatolond/101353988643825455
https://masto.donte.com.br/tags/nofilter
https://masto.donte.com.br/tags/tbt

**Comment by renatolond** [comment]
The last picture I posted seems to have this fixed, is the change only on pixelfed.social? ( https://pixelfed.social/p/renatolond/30865 / https://masto.donte.com.br/@renatolond/101392074561899728 )

**Comment by dansup** [comment]
Fixed in f0425ca0
