### ISSUE TITLE
 no preview picture via activitypub

### ISSUE THREAD

**Issue by Matthias84** [pixelfed/pixelfed#738]
If you follow pixelfed users via activitypub (e.g. Mastodon) there seem to be no image preview, for example
![screenshot_2019-01-05 norden social](https://user-images.githubusercontent.com/217511/50715319-0d345280-107d-11e9-9a52-05b4d071ce84.png)
https://pixelfed.social/p/mrsmarshmello/28933

**Comment by dansup** [comment]
@Matthias84 Your mastodon instance might have had an issue fetching it maybe? I can see it fine from mastodon.social.

<img width="333" alt="screen shot 2019-01-05 at 12 33 27 am" src="https://user-images.githubusercontent.com/877217/50721737-a06f8700-1081-11e9-98af-83e0f75d54b8.png">
