### ISSUE TITLE
blindKeyRotation doesn't work for local users

### ISSUE THREAD

**Issue by asonix** [pixelfed/pixelfed#739]
Since the `blindKeyRotation` function in the federation controller relies on the presence of `remote_url`, it doesn't work for local profiles.

**Comment by dansup** [comment]
@asonix Blind key rotation only affects remote profiles. The inbox is for remote instances only.

**Comment by asonix** [comment]
I opened this issue because I have logs of my instance trying to run blind key rotation on a local user. If this shouldn't be happening, that's still an issue.

**Comment by dansup** [comment]
@asonix Ok, I will look into this!
