### ISSUE TITLE
Bug Public Timeline on Pixelfed.social instance

### ISSUE THREAD

**Issue by enfief** [pixelfed/pixelfed#742]
Hello, 
I can only see the same 3 posts on the publictime and they appear in loop. 
On the pixelfed.social instance

**Comment by dansup** [comment]
@enfief This has been fixed, if you still experience this bug please clear your browser cache and try again.

**Comment by enfief** [comment]
@dansup That's good is has been fixed :) 
 But an another bug appears.
 In the public timeline I only can see 10 posts and can't go further. and you?
