### ISSUE TITLE
Animated avatars

### ISSUE THREAD

**Issue by spaceottercode** [pixelfed/pixelfed#759]
low priority if accepted. potentially post version 1.0. Enhancement.

This request, if accepted, would probably entail an "autoplay anim gif" setting like in Mastodon (or possibly overloading the CSS-animation related "reduced animation" option). As to which avatars: At a minimum the gallery one (large avatar), or possibly all, or down to a minimum size.

**Comment by dansup** [comment]
We do not plan on supporting animated avatars.
