### ISSUE TITLE
Search suggestions for some hashtags stop after entering n characters or a #

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#76]
Example hashtag: `#cat`

Entering the following will load the hashtag as a suggestion:
`c`
`ca`

Entering the following will say "unable to find any matches"
`cat`
`#cat`
`#c`
`#ca`
`#cat`

**Comment by trwnh** [comment]
This doesn't happen with usernames for some reason, only tags. Typing any substring of usernames will usually get them to load (but not every single match will be displayed -- see #88)

**Comment by dansup** [comment]
Possible fix in #137

**Comment by dadall** [comment]
Still present after today's update.

**Comment by trwnh** [comment]
The threshold seems to have increased, but it's inconsistent.

'c' / 'ca' / 'cat' will load #cat as a suggestion. 'cats' will load #catsofpixelfed as a new suggestion, but typing 'catso' and all further substrings will produce no suggestions.

Meanwhile, the hashtag for #pixelfed will be suggested for all substrings.

**Comment by dansup** [comment]
Fixed in 958b5b4
