### ISSUE TITLE
attributedTo can be an array instead of a string as well

### ISSUE THREAD

**Issue by swentel** [pixelfed/pixelfed#761]
statusFirstOrFetch assumes the attributedto property is a string/url. However, this can be an array too which why we currently can't send replies from Bridgy Fed - see https://github.com/snarfed/bridgy-fed/issues/39

See also https://www.w3.org/TR/activitystreams-vocabulary/#dfn-attributedto

**Comment by trwnh** [comment]
closing as a functional duplicate of #722
