### ISSUE TITLE
Images are federated to mastodon but media description is not

### ISSUE THREAD

**Issue by renatolond** [pixelfed/pixelfed#764]
Even if media description is added to a picture, the description is not federated over to Mastodon.

Original: https://pixelfed.social/p/renatolond/308650o87
Federated: https://masto.donte.com.br/@renatolond/101392074561899728

**Comment by JulesTheFairy** [comment]
Could you please deal with the (one line!) pull request to solve this major federation issue? Accessibility isn't a bonus, if your image descriptions don't federate, the whole federation feature is broken. And the solution is already there. Please deal with it soon! Thanks.

**Comment by trwnh** [comment]
@JulesTheFairy This should be fixed with v0.8.0 -- there are some breaking changes that need to be resolved first in the `frontend-ui-refactor` branch before merging into `dev`, so all PRs are currently on hold until that's fixed. Rest assured it's not an oversight!

**Comment by dansup** [comment]
It appears that #767 did not resolve this issue, I am investigating.
