### ISSUE TITLE
Import from Instagram

### ISSUE THREAD

**Issue by madranet** [pixelfed/pixelfed#765]
I don't want to sound overly-critical. I'm all in favour of Open-Sourcery and providing alternatives to the big data-slurping websites out there. So I was excited to learn about Pixelfed. But...

That excitement lasted for as long as it took me to realise there's no way to import existing photos from Instagram.  

It never fails to amaze me that so many developers seem to think that simply providing a more ethical alternative to the privacy-raping big boys out there is sufficient incentive to get people to switch to your new product. Even if doing so means they need to abandon all the time and effort they've put into building up a 'portfolio' / 'archive' / 'following' / 'history' [call it what you will] on the sites you're hoping to replace. Almost all such open source projects make a point of emphasising _"no lock in"_ and assuring you you can get your data out at any time. Yet none of  them seem to provide any strategy for importing your existing data from rival sites, in the first place.

And yet, this keeps on happening:

 App.net, Diaspora, Quitter... [to name but three that I've used in the past] ...all offering open-source or ad-free alternatives to the big players. But none of them considering it important to provide any way for new users to bring their _"stuff"_ with them from the existing sites. And all three projects subsequently dead or dying from lack of interest and users.  [and I fully expect the current poster boy for open source Social Networking, Mastodon, to go the same way, for the same reason].

Seriously devs. I know this isn't a specific issue _per se_. But you really need to consider this as a top priority, if Pixelfed is to have a snowball's chance in hell  of gaining any traction at all. 

Your product might be the most ethical, most open-source, most libertarian project in the world. But Instagram have several years and several hundred million users' head start on you. Expecting people to just abandon everything they've put into their Instagram accounts over the years and flock to Pixelfed instead is both incredibly naive and borders on insulting. It's effectively saying to them that you consider all that prior work they've done to be worthless.

Just my well-meaning tuppence worth. Feel free to close and mark as irrelevant, if you wish.

**Comment by dansup** [comment]
@madranet IG import has been on the roadmap for awhile, https://mastodon.social/@pixelfed/100087667113289786

**Comment by jaredmoody** [comment]
What does "on the roadmap" mean? I don't see an import function on pixelfed.social and I don't see an open issue to implement this, so I'm not sure. Was an import feature completed? Still to be completed?

Thanks!

**Comment by trwnh** [comment]
It's currently delayed, because having a stable release is a prerequisite for importing content from other platforms. Importing from Instagram when the background workers aren't done yet would be a bad move. Reopened this issue to track updates to the Instagram importer!

**Comment by jaredmoody** [comment]
Thanks for the update!

**Comment by MrPetovan** [comment]
Now that I've set up a permanent single-user instance, is this still possible and planned for after the stable release?

**Comment by trwnh** [comment]
Yep, still on the roadmap. See also #1046

**Comment by MrPetovan** [comment]
Aaah, I tried the route but it didn't give anything, makes sense seeing the PR, thanks for the answer!

**Comment by madranet** [comment]
Exactly one year [and a week] since I originally posted this request and there's still no hint of being able to import our existing Instagram posts [of which we now have an extra 12 months' worth!] into PixelFed. Not even a 'hacky' unofficial method we could try, never mind a user-friendly one.

All we ever hear is that it's "on the roadmap". 

Oh well. That's me lost interest then.  12 months+ is more than enough time for some signs of progress to have been made. So I guess it's not going to happen.

Yet another promising new web project doomed to failure from the outset; because the developers decided that people's pre-existing user-generated content, on other rival sites, is completely worthless.

**Comment by MrPetovan** [comment]
From OP

> I don't want to sound overly-critical.

I guess you spectacularly failed in that regard.

**Comment by madranet** [comment]
> From OP
> I guess you spectacularly failed in that regard.

Possibly. 

I sometimes forget that the online world is so over-populated with Special Snowflakes these days that offering constructive criticism practically constitutes Hate Crime.

**Comment by MrPetovan** [comment]
You're saying this, but you were the one disowning your bitter overly-critical tone. Which is very different from constructive criticism. You're of course free to voice your opinions, but your evident lack of self-awareness about their 1) tone and 2) relative usefulness is harder to bear than the actual words you're writing.
