### ISSUE TITLE
Support Embedding of Pixelfed Posts

### ISSUE THREAD

**Issue by 0xvividmirage** [pixelfed/pixelfed#776]
I would like to embed a particular Pixelfed post in my website that is a slideshow of images. There doesn't seem to be a way to do this. Here is a link to my post:

[https://pixelfed.social/p/davidpgil/31163](url)

**Comment by sikkdays** [comment]
Just want to add that I think embed is a great idea. InstaSpam, Twitter, FB, and the other centralized services are obsessed with getting eyeballs on their pages and rarely allow this anymore. Now that we have loops, I would love to embed my images and loops on my blogs.

**Comment by dansup** [comment]
We have added Post and Profile embeds! You can see an example [here](https://dansup.github.io/pixelfed-embed/)

**Comment by bristow** [comment]
I think there is a bug on embed code when the post has 2 or more pictures.

With only 1 picture, it's ok, 2 or more is ko :(

You can test with this post : https://pix.diaspodon.fr/p/Bristow_69/197409107056136192 

Thanks for your fabulous software !

PS : i can open a new issue if you prefer
