### ISSUE TITLE
Post counter is off by 1

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#785]
![image](https://user-images.githubusercontent.com/10606431/51091536-46418680-1751-11e9-81e2-75a12b605733.png)

9 posts, but only 8 thumbnails. Either a 9th post has become invisible, or the counter is off-by-one.

**Comment by carlydotwebsite** [comment]
Question after looking at the code: have you ever deleted a post you made? I noticed there's a deleted_at column in the database, so I'm not sure if it might have gotten soft-deleted but still counted in your number of posts, in which case I think we'd have to add a `->whereNull('deleted_at')` to the query sequence.

**Comment by dansup** [comment]
@trwnh You have 1 private post, the count is based on posts with media (ie: not shares or replies). I will update the statusCount() logic to only count public and unlisted posts.

**Comment by trwnh** [comment]
@dansup I think the better solution is to allow authenticated users to see private posts on profile pages.

**Comment by spaceottercode** [comment]
This might be related to #703 

And I agree with @trwnh. please allow private posts to be visible in the profile page (for authenticated user, including self), if possible. They should be visible in your Home page too (when your account is locked, not just unlocked).

**Comment by trwnh** [comment]
Closing this as a duplicate of #703
