### ISSUE TITLE
Creating new posts often fails

### ISSUE THREAD

**Issue by kenokenobingo** [pixelfed/pixelfed#786]
Uploading a new post often fails. After clicking `Create Post`, it reloads the feed without displaying or creating a new post.

Instance: `pixelfed.social`
Browser: Firefox on macOS

Edit: The experimental interface seems to work properly.

**Comment by trwnh** [comment]
Are you including a caption? Posts currently cannot be uploaded without a caption.

**Comment by kenokenobingo** [comment]
Yes, I’ve always included a caption. As I said, the experimental interface works for me.

**Comment by ghost** [comment]
It happens to me too, in a just created instance. The experimental uploader let me upload a picture once, but no more

**Comment by dansup** [comment]
Fixed in #893
