### ISSUE TITLE
[Feature Request] Use PGP to Encrypt Notification Emails

### ISSUE THREAD

**Issue by 0verk1ll** [pixelfed/pixelfed#789]
### Pitch

Facebook allows users to encrypt notification emails with PGP (https://www.facebook.com/notes/protect-the-graph/securing-email-communications-from-facebook/1611941762379302). Allowing Pixelfed users to add their PGP public key to their Pixelfed account would enable all email communication to be encrypted.

### Motivation

Since email notifications can contain sensitive information (ie. password reset information), encryption would significantly increase the security and privacy of notification emails.

**Comment by dansup** [comment]
@0verk1ll We don't support email notifications yet, will keep this issue open until we do!

**Comment by 0verk1ll** [comment]
@dansup would PGP encrypting password reset emails be feasible? Facebook does this.
