### ISSUE TITLE
[Accessibility] voice/audio support in toots

### ISSUE THREAD

**Issue by todoneunl** [pixelfed/pixelfed#790]
Audio support is asked many times (although odd enough I didn't find an issue about it), but not voice support.

A blind person on Todon.nl (a new user) asked the question if it would be possible to record voice introductions and messages. This would be very helpful for blind people. Here is the complete thread:

https://todon.nl/@YellowAsFreedom/101434319273303773

I suggest an option to record a voice message and upload a pre-existing voice message. 

This is not exactly the same as complete audio file support, but it can be combined of course.

**Comment by dansup** [comment]
@jeroenpraat This is a very interesting idea, I opened an issue for audio support via FunkWhale (#315). Will try and get this into v0.9.0!

Implementation Todo:
- [ ] ActivityPub (add to actor object)
- [ ] Easy discoverability via Profile UI
- [ ] User settings to add a voice introduction
- [ ] Help Center Documentation

**Comment by todoneunl** [comment]
Oops, this was originally intended for Mastodon. I will create it over there as well.

**Comment by todoneunl** [comment]
https://github.com/tootsuite/mastodon/issues/9878
