### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by capmisson** [pixelfed/pixelfed#791]
How can be set the language for the instance?

**Comment by dansup** [comment]
@capmisson Localization isn't ready yet. Will keep this issue open to track progress of this.

**Comment by capmisson** [comment]
Perfect, thanks.
Also, is there a way to start translating to Spanish and Catalan the sections of Pixelfed, I saw some translations but I would like to translates pages as https://github.com/pixelfed/pixelfed/blob/dev/resources/views/site/about.blade.php

**Comment by dansup** [comment]
Fixed in latest commits!

**Comment by AnonymousWebHacker** [comment]
@dansup my instance I select Spanish, however, nothing changes
![esp](https://user-images.githubusercontent.com/43164089/101846734-eabad780-3ae4-11eb-8ca2-547edd866b99.png)
![esp3](https://user-images.githubusercontent.com/43164089/101846737-eb536e00-3ae4-11eb-8d46-afe5cefd864e.png)
