### ISSUE TITLE
Allow reordering albums before posting (when uploading multiple pictures)

### ISSUE THREAD

**Issue by narFnarF** [pixelfed/pixelfed#798]
When creating or editing a post that contain 2 or more pictures, it would be useful to be able to reorder the pictures. For example, to bring the 3rd picture in 1st place as the "cover" picture.

Suggested interface:
- Enter "reorder" mode where small thumbnails are displayed and allow to drag-and-drop them to reorder them.

Other alternative:
- Put arrow buttons (up/down) to switch the picture with the previous/next one.

**Comment by trwnh** [comment]
I could've sworn there was an issue for this already but it looks like there isn't officially one! Anyway, this would probably fall under the general request of being able to Update a post after it's been made, e.g. to change filters or change the order of albums, which has been asked before but not been filed as a Github issue until now.

Current blockers would be other ActivityPub implementations that don't recognize Update activities and treat all posts as immutable, so it's possible that any such changes may only be reflected on compatible services, e.g. only on Pixelfed instances but not on Mastodon instances.

**Comment by narFnarF** [comment]
At the very least, we could start by letting the user reorder pictures when creating the new post (after uploading 2+ photos but before submitting). To my knowledge, that's not possible yet.

**Comment by trwnh** [comment]
Can now change filters by clicking "Edit" from the post permalink, but it doesn't seem to take full effect. The new filter is only applied within the edit UI -- the actual post is unchanged, and the thumbnail is unchanged as well.

**Comment by narFnarF** [comment]
My ticket was originally about being able to change the order of pictures before submitting the post, not updating an existing post. I understand the complexity about updating existing ActivityPub posts. Should these be 2 different tickets?

**Comment by trwnh** [comment]
My bad, I must've misunderstood. I'll edit this ticket to reflect your original request and make a different one for updating.

**Comment by stevenroose** [comment]
Just a heads-up that this is still very much a desired feature to me. It also seems that if you select multiple files in the upload dialog, the order of selection is not followed (I don't know if this is something that is even possible, i.e. if the interface communicates the order of selection). But anyhow, ordering photos in a post is very often desired and right now one has to upload files one by one in order to do this.

**Comment by Danie10** [comment]
This is very much needed, as there is usually one specific photo at least that you'd like to feature. I've tried selecting the one first that I'd like, but it seems to change the order anyway and I end up with one of my more obscure supporting photos as the featured one on the post.

**Comment by dansup** [comment]
Added in the latest commits!

**Comment by ElaineCBaker** [comment]
This is marked as done, but how do you do it ?  I can't seem to drag and drop to re-order photos in a collection, and when I edit collection it only gives me option to edit the meta data or delete photos, but not re-order.  Thanks

**Comment by ElaineCBaker** [comment]
Just  following up on this.  I am using pixelfed.social.  This issue marked as done but I don't see how to re-order the photos I upload, before publishing - how do I do this ? @dansup
