### ISSUE TITLE
Add validation for status form

### ISSUE THREAD

**Issue by carlydotwebsite** [pixelfed/pixelfed#799]
I see a closed issue for this, but it doesn't seem to be fixed—the status form can be submitted without either a caption or any attached media. The former fails silently and just returns the user to the homepage; the latter throws an error due to trying to iterate over a non-array.

I'd suggest adding the `required` attribute to the file field and the caption field in the status form, as well as adding an edge case check around the foreach on the files in the status store function.

**Comment by dansup** [comment]
@cmho The compose UI requires a caption but when I released the experimental compose UI, I made captions optional. The experimental UI will replace the old UI in v0.8.0.

**Comment by dansup** [comment]
Fixed in #893
