### ISSUE TITLE
Nodeinfo endpoint

### ISSUE THREAD

**Issue by rhaamo** [pixelfed/pixelfed#8]
Hello,

For fediverse statistics and discovery, it would be great to have pixelfed implementing nodeinfo [1] API endpoint.

```/.well-known/nodeinfo``` would returns:
```json
{
  "links": [
    {
      "rel": "http://nodeinfo.diaspora.software/ns/schema/2.0",
      "href": "https://blah.tld/whatever/api/something/2.0"
    }
  ]
}
```
With a content-type of ```application/json; profile=http://nodeinfo.diaspora.software/ns/schema/2.0#; charset=utf-8```

And ```/whatever/api/something/2.0``` should be conform from the 2.0 schema in the nodeinfo spec.

[1] https://github.com/jhass/nodeinfo

**Comment by dansup** [comment]
@rhaamo Hello, I am planning to implement NodeInfo, just added it to my todo list!

**Comment by dansup** [comment]
@rhaamo I added nodeinfo support! 

https://mastodon.social/@pixelfed/100060118873990698

<img width="1086" alt="screen shot 2018-05-20 at 12 01 12 am" src="https://user-images.githubusercontent.com/877217/40276239-1428d536-5bc2-11e8-8a2e-c38b7a5b0689.png">

**Comment by rhaamo** [comment]
Hi, great !

Just some side notes:

the ```software``` node doesn't allow any other field inside it, you should put ```url``` in ```metadata```.

the nodeinfo repository does have a ruby CLI validator for this schema.

except that it seems good !

**Comment by dansup** [comment]
@rhaamo Interesting, thanks for the heads up. I will fix this.
