### ISSUE TITLE
Logging in with an email address is confusing when federated usernames follow the same structure

### ISSUE THREAD

**Issue by bgpugh** [pixelfed/pixelfed#80]
Understanding that the ActivityPub work isn't yet complete, I think it could be confusing to users to log in to federated_username@pixelfed.instance by typing in email_username@mail.provider.

Mastodon is the closest federated cousin I have personal familiarity with, but there you have a recovery email account added during account creation and log in to pixelfed.instance with federated_username.

**Comment by bgpugh** [comment]
Possibly relevant to the work being done in https://github.com/dansup/pixelfed/issues/7

**Comment by trwnh** [comment]
Some security considerations need to be given here -- allowing login with username is convenient but dangerous because the username is public knowledge. Logging in with an email means an attacker has to know both your email AND your password.

**Comment by NoraCodes** [comment]
It would be far better to mitigate that risk with a true two factor solution, imo

**Comment by mal0ki** [comment]
Federated usernames don't entirely follow the same structure, as you should always write the [at] at the start: [at]name[at]instance.domain to get the full url to an instance address. 

And the AP format is .... a URL? Or something.

**Comment by dansup** [comment]
Federated usernames do not use the same format as emails, you are thinking of webfinger. Almost every website uses email for authentication.
