### ISSUE TITLE
Portrait photos appear as landscape

### ISSUE THREAD

**Issue by ricardojmendez** [pixelfed/pixelfed#802]
Photos taken with an iPhone 6s in portrait mode appear as landscape, both on the preview and when finally uploaded.

**Comment by ricardojmendez** [comment]
Has this been deployed to Pixelfed.social? It still appears on the preview when creating a post, even if the image on the final post is has the right orientation.

**Comment by dansup** [comment]
@ricardojmendez Yeah, it uses the exif orientation during image optimization to orientate it the right way. The new compose UI fixes this on the client side too.

**Comment by muesli** [comment]
This isn't working for me. Both the preview as well as the actual post show the picture in the wrong orientation.
