### ISSUE TITLE
Add ability to toggle invite-only registration from admin features

### ISSUE THREAD

**Issue by carlydotwebsite** [pixelfed/pixelfed#805]
Might already be in the works? But several people I've talked to have expressed interest in being able to more easily toggle the open_registration config value so that they can more easily swap to and from being invite-only as needed.

**Comment by dansup** [comment]
Done!

![Screenshot 2024-10-14 at 5 15 23 PM](https://github.com/user-attachments/assets/9a596237-35c6-403d-b3f0-2633bef9e5c5)
