### ISSUE TITLE
Reserved username with email address using + notation. Now can't reset password

### ISSUE THREAD

**Issue by bgpugh** [pixelfed/pixelfed#81]
I put my name in the ~~sorting hat~~ google forms document to reserve a username earlier this morning. The email address I entered contained the + character (https://www.cs.rutgers.edu/~watrous/plus-signs-in-email-addresses.html) and when I attempt reset, I get "We can't find a user with that e-mail address"

When I try to create a new username, I get "The username has already been taken"

**Comment by dansup** [comment]
@bgpugh What username?

**Comment by bgpugh** [comment]
IIRC, it was bpugh

**Comment by dansup** [comment]
@bgpugh Please check your email, I initiated a manual password reset request to the email you provided.

**Comment by bgpugh** [comment]
The password reset page still responds with "We can't find a user with that e-mail address."
