### ISSUE TITLE
Avatar changes are not federated?

### ISSUE THREAD

**Issue by cassidyjames** [pixelfed/pixelfed#810]
I might be missing something here, but I changed my avatar in the last couple of days, and when viewing my profile from a Mastodon instance, I still see my old avatar.

**Comment by trwnh** [comment]
I think this is a Mastodon issue. Mastodon caches media and doesn't refresh account avatars/banners/etc except when a scheduled task is run. Try re-fetching the profile by searching for the direct profile link within Mastodon, e.g. by pasting `https://pixelfed.social/trwnh` into the search bar and hitting Enter on your keyboard.

**Comment by cassidyjames** [comment]
@trwnh looks like that was the issue. Thanks!
