### ISSUE TITLE
Post not saved after submission

### ISSUE THREAD

**Issue by aschrijver** [pixelfed/pixelfed#812]
I would have asked this on mastodon.social, but that instance is down for a while now.

Just created a carefully worded post for https://pixelfed.social/humanetech only to have it 'disappear' after submission of the post. Was typing from Firefox 61.01 on Ubuntu 16.

No error occurred or something logged (that I can see). I will try again later, see if it'll work then.
Feel free to close this issue, if it does not add enough useful info to you. I just had to mention, helping you improve even further :)

**Comment by trwnh** [comment]
Some more information would be helpful, yes. What is meant by "disappear"? Do you mean the post does not show up on your profile page? What was the privacy of the post? Etc.

**Comment by aschrijver** [comment]
Yes, I agree, but there is not much more, I' afraid. Created regular post with defaults (Public). Filled in heaer text, attach image, submit.. nothing happened. The dialog just disappeared. Not trace of what I typed. Sorry.

I'll try again tomorrow (CET, typing quickly now), and it it works allright, I'll close the issue. Thx.

**Comment by aschrijver** [comment]
The same just happened again. Doing nothing special. Press 'Create new post', add image, add text, submit ---> no entry created, no visual error message.

There is something I saw in Firefox Developer Tools log (opened after the error, not sure if/how it is related):

```
Bad InfiniteScroll path option. Next link not found: .pagination__next components.js:1:293121
  KLU//</r</</a.updateGetPathSelector         https://pixelfed.social/js/components.js:1:293121
  KLU//</r</</a.updateGetPath                 https://pixelfed.social/js/components.js:1:292142
  KLU//</r</</a.create                        https://pixelfed.social/js/components.js:1:290560
  o                                           https://pixelfed.social/js/components.js:1:290277
  <anonymous>                                 https://pixelfed.social/humanetech:293:21
  c                                           https://pixelfed.social/js/app.js:1:54297
  s/</l<                                      https://pixelfed.social/js/app.js:1:54601

Disabling InfiniteScroll components.js:1:290767
  KLU//</r</</a.create                        https://pixelfed.social/js/components.js:1:290767
  o                                           https://pixelfed.social/js/components.js:1:290277
  <anonymous>                                 https://pixelfed.social/humanetech:293:21
  c                                           https://pixelfed.social/js/app.js:1:54297
  s/</l<                                      https://pixelfed.social/js/app.js:1:54601
```

I then tried it another time with the same text and with Developer Tools opened... and: success this time. After submitting there was a longer time passing.

Deleted, and tried again. Then some other posts. Everything worked fine afterwards. Not able to reproduce a 3rd time.

**Comment by bungabunga** [comment]
same with me. i'm trying to post something for a month, it seems everything is working fine but nothing gets posted.

**Comment by dansup** [comment]
@aschrijver @bungabunga What type of image did you try posting? What is the file size?

**Comment by aschrijver** [comment]
Hi @dansup as you see I managed to upload without issue, after a couple of misses. The images are now on my account. They are the pyramid images on https://pixelfed.social/humanetech and all PNG. Specifically this one failed https://pixelfed.social/p/humanetech/37603 and is 125kb.

**Comment by bungabunga** [comment]
@dansup hi, i tried to post this one yesterday for testing purposes.

![tri](https://user-images.githubusercontent.com/2994878/52774453-81c7bd00-303d-11e9-8bb6-a2cc046209ef.jpg)

**Comment by aschrijver** [comment]
Do yo have same browser, OS, etc, @bungabunga ? And any error messages?

**Comment by bungabunga** [comment]
Both, FF and Chromium on Ubuntu 18.10, no error messages anywhere.
