### ISSUE TITLE
The first post I made after creating my account doesn't appear in my profile

### ISSUE THREAD

**Issue by narFnarF** [pixelfed/pixelfed#816]
For some reasons I don't understand, the first post I made right after creating my account on pixelfed.social doesn't show up on my profile. It does show up on my timeline though. That's how I was able to find it. 

The problematic post:
https://pixelfed.social/p/narF/34463

**Things I tried:**
I tried Re-sharing using my own account doesn't make it show up on my profile either.

I tried bookmarking it (saving it) with my account and that work as expected (it appears in my list of saved post on my profile)

I tried searching for it from mastodon and it doesn't appear.

I tried to open it in another browser, without logging into pixelfed.social and the post is not accessible. It only show "error 404".

This looks like the post is private and only visible to me, but if that's the case, I don't see this state displayed anywhere.

**Comment by leuc** [comment]
Does it appear after a second photo is published?

**Comment by dansup** [comment]
@narFnarF This bug will be fixed soon!
