### ISSUE TITLE
Can't edit post caption after publishing

### ISSUE THREAD

**Issue by thomas-kuntz** [pixelfed/pixelfed#822]
The post description can be edited after publishing the post but not the caption. Would be good to be able to edit the caption too.

By the way, I think having two different fields for the caption and fo the description can be confusing. People might not get that the description is the `alt` attribute of the image used by accessibility tools or when the image can't be viewed. The difference is subtle and I think it might not be necessary to have two different fields (or at least the difference should be made explicit).

**Comment by dansup** [comment]
Lets move this to #823 as it covers more than just post caption.
