### ISSUE TITLE
Post counter includes comments

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#84]
![image](https://user-images.githubusercontent.com/10606431/40830264-92cac196-654b-11e8-9198-00398e6ec347.png)

3 posts is actually just 1 post (and 2 comments)

Comments should not be included in the post counter, and I assume this is an artefact of #51

**Comment by dansup** [comment]
@trwnh That is an easy fix, one moment please!

**Comment by trwnh** [comment]
@dansup This is happening again:
![image](https://user-images.githubusercontent.com/10606431/45812588-d08f4780-bc95-11e8-9fa1-2db3973e93cf.png)
