### ISSUE TITLE
Notification wheel keeps spinning

### ISSUE THREAD

**Issue by todoneunl** [pixelfed/pixelfed#856]
Running today's code.

See (bad quality GIF) for what I mean.
![kazam_screencast_00006 1](https://user-images.githubusercontent.com/41594439/52904452-c2d1f400-322c-11e9-97d9-9213027a1c31.gif)

P.S. There are no notifications.

**Comment by tyrosinase** [comment]
![2019-02-16--1550350191_1920x1080_scrot](https://user-images.githubusercontent.com/9473609/52905077-b9cc2d00-3202-11e9-8964-1dbda007460b.png)

(Linux Firefox 65.0.1)

**Comment by todoneunl** [comment]
Update: when I disable notifications and re-enable them, the spinning wheel is gone, and it shows '0 notifications!'.

**Comment by todoneunl** [comment]
Update: A new user didn't had this problem. You can change it to low priority.

**Comment by tyrosinase** [comment]
Counterpoint: I still have this problem, and even the SuperStop plugin doesn't kill the spinner. On-screen motion is sooooooooper-distracting for some people (:wave:) so this is actually kind of a big deal.

**Comment by dansup** [comment]
This has been fixed in the latest commits!
