### ISSUE TITLE
Irregular suggestions

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#88]
Some strings generate 14 suggestions, some generate 9, some generate only 1 or two -- and there doesn't seem to be a fully discernible pattern for this.

Examples:
- Typing `ab` will suggest the account `c0debabe` but not `abdullah` -- which instead appears after you type at least `abd`.
- Typing `rw` will suggest `#vaporwave` and `trwnh`, but typing `orw` will give no suggestions. (See also: #76)
- `#vaporwave` will load as a suggestion for v/p/o/r/w, but not a/e

**Comment by dansup** [comment]
I think this might be due to the LIKE wildcard query, will investigate.

**Comment by dansup** [comment]
Fixed in latest commits
