### ISSUE TITLE
Separate posting UI / flow

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#89]
Especially for mobile, but also for desktop, having an attach form and a textbox at the top of the timeline is a bit awkward because

1) it takes up too much space
2) it doesn't allow for easy posting
3) it will not work when post editing gets implemented.

Posting should be done from its own UI -- as a separate page on mobile or for non-JS users, with a button somewhere (floating action button?)

For JS users on desktop, clicking that button should open a modal window.

**Comment by jordan31bit** [comment]
Agreed, its a bit jarring to see the upload box on public and personal timeline.

**Comment by dansup** [comment]
Added in latest commits!
