### ISSUE TITLE
Wrong hashtag link in post view

### ISSUE THREAD

**Issue by sanpii** [pixelfed/pixelfed#895]
The hashtag link in the post view ([here](https://photos.homecomputing.fr/p/sanpi/115) for example) uses the hashtag name instead of the slush to build the link. Therefore with an uppercase hashtag the link lead to a 404 page.

**Comment by trwnh** [comment]
I'm not sure what you mean. I just made a test post on pixelfed.social with the caption `#test #Test #TEST` and all 3 hashtags worked correctly.

**Comment by sanpii** [comment]
I use postgresql, it’s probably the *problem*: http://sql-info.de/mysql/gotchas.html#1_4
