### ISSUE TITLE
image distortion

### ISSUE THREAD

**Issue by nadszeg** [pixelfed/pixelfed#90]
i posted an image and when i first opened it, it looked okay, but i checked back later and it looks distorted - look at the cat's face and it's body, the proportions look weird

screenshot and original picture:
https://imgur.com/a/yAgL22b

**Comment by nadszeg** [comment]
when i look at the photo in the timeline, it keeps the photo's actual size, but when i click on it and open it, the distortion is still present

**Comment by stephenburgess8** [comment]
I am experiencing the same thing. In my case, my image was quite large, but in a landscape view. The styles being applied to the image are `width: 100%` (this is set in the HTML, but would probably be better to put it in a stylesheet) and `max-height: 451px !important`. When I add `object-fit: contain` to the image, it does maintains the aspect ratio. However this does not work in IE and results in some odd negative space issues in mobile. https://pixelfed.social/p/stephen/939

**Comment by trwnh** [comment]
Likewise; it seems to depend on the viewport resolution, which frankly it should not do at all.

![image](https://user-images.githubusercontent.com/10606431/40869890-e25bcd02-65e8-11e8-897b-d3e9e4ee4f1b.png)

The proper and responsive way to do this is probably to set a height of 0 and a padding-bottom of the desired aspect ratio. For example,
```
div.16to9 {
    height: 0;
    padding-bottom: calc(100% / 16 * 9)
}

img.inside {
    object-fit: contain;
}
```

**Comment by hellcp** [comment]
Please post links to images on the site, it's much easier to validate based on something existing up there ;)

**Comment by trwnh** [comment]
@hellcp The exact image does not really matter, since they all exhibit this behavior when scaling the page, but in any case, the one in the screenshot is https://pixelfed.social/p/eloisa/938

**Comment by hellcp** [comment]
@trwnh: I just wanted to confirm something, it's not an issue with Firefox, just Chrome and related most likely ;)

**Comment by hellcp** [comment]
@trwnh the easiest way to fix it on Chrome is to use "m-auto" class on image itself, that however causes Firefox to stretch image (by 15px on left and right side), because of width="100%".

**Comment by n33l33m3lj** [comment]
I'm experiencing the same problem with chromium (Debian stretch)

**Comment by hellcp** [comment]
I'm working on a full fix, will be delivered alongside image view redesign ;)

**Comment by trwnh** [comment]
@hellcp The proper fix would be to apply `object-fit: contain` to the img and set a fixed height/width for the container. Thumbnails can instead use `object-fit: cover` with regards to #118 and #152

**Comment by moshpirit** [comment]
Something similar just happened on [Discover vs. post](https://imgur.com/a/tCOKQNm) (not mine so I don't own the original picture)

**Comment by hellcp** [comment]
Yeah, there is max-height set, we need to get rid of it ;0
