### ISSUE TITLE
Missing official production setup/installation manual

### ISSUE THREAD

**Issue by Vertux** [pixelfed/pixelfed#915]
Do not get me wrong, I am glad that you make great progress in development, but I think it would be really the time to make a complete manual for an official fully funcional production installation/setup including recurring maintenance tasks (I know it is a beta application). I think you would get much more usefull feedback if you would define a solid official installation to give non programmers, who would like to host Pixelfed the chance to support you with feedback and bug reports. Furthermore it would substantially reduce the ammount of redundant questions in IRC and Mastodon.

**Comment by ghost** [comment]
I suffered from the same problem, the lack of documentation made it quite hard to get it setup, especially there was contradicting information out there (e.g. with regards to supported databases). Through trial and error I built a playbook for Ansible (see [here](https://github.com/ar-i/Pixelfed-Ansible)), maybe that could be of help to some people, I'm open for any criticism because it definitely needs improvement.

**Comment by shleeable** [comment]
Production Docker/docker-compose most definitely needs to ready sooner than later.

**Comment by ghost** [comment]
As I am also currently trying to get my instance running, I cannot access https://docs.pixelfed.org/ at all. What's wrong here? This is is definitely a great project which needs to be shaped when it comes to the documentation to spread its word ;) !

**Comment by trwnh** [comment]
docs.pixelfed.org was unfortuantely taken down temporarily until several issues with the instructions can be fixed. Updated/fixed docs should be coming in the future!

**Comment by ghost** [comment]
> docs.pixelfed.org was unfortuantely taken down temporarily until several issues with the instructions can be fixed. Updated/fixed docs should be coming in the future!

Alright - thanks for the info, hoping that it will be online again soon as I want to give my own instance a first real try 😉 !

**Comment by trwnh** [comment]
Docs are back online! Still WIP for now but shouldn't cause any system problems
