### ISSUE TITLE
Followers-only posts don't federate

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#932]
Setting a post to followers-only finally works in profile view and in timelines (at least for the original poster), but the corresponding status never shows up in external feeds.

### Actual behavior 
1. Make a followers-only post
2. Post visible in profile
3. Post visible in timeline 
4. Post not visible in Mastodon from account following my Pixelfed account

### Expected behavior
4. Post is visible to followers from Mastodon

**Comment by dansup** [comment]
@trwnh Good find, looks like I need to [finish this code](https://github.com/pixelfed/pixelfed/blob/dev/app/Status.php#L351-L365). Will push a fix shortly!
