### ISSUE TITLE
Dark mode is not persistent

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#933]
1. Enable "Dark Mode" toggle from your timeline view.
2. Navigate to any other page, or simply refresh.

### Expected behavior
Dark mode should remain enabled.

### Actual behavior
Dark mode is reset and the default light theme is loaded instead; toggle is disabled again.

**Comment by dansup** [comment]
@trwnh I'm delaying this until v0.12. It will require a lot of refactoring to be properly supported.

**Comment by dansup** [comment]
@trwnh Persistent dark mode was added in 6d9c30e7
