### ISSUE TITLE
Deleting a picture does not work

### ISSUE THREAD

**Issue by Seestern** [pixelfed/pixelfed#941]
When deleting a picture (1) no comformation box appears and the (2) count of posts will not be updated.
But for me these are two minor issues...

**Comment by lawjeremy** [comment]
I have also observed that images don't actually get deleted. When I refresh they come back.

**Comment by trwnh** [comment]
Which instance is this occurring on?

**Comment by Seestern** [comment]
My instance is: https://pixelfed.de

**Comment by dansup** [comment]
Fixed in #968
