### ISSUE TITLE
 [F.R.] Less space between lines

### ISSUE THREAD

**Issue by moshpirit** [pixelfed/pixelfed#96]
Since comments are from newer (up) to older (down), it's difficult to read them, specially when the space between lines from the same comment is the same than the space between lines from different comments: 

**PixelFed**:   
![](https://i.imgur.com/2xWreX6.png)

**Instagram**:
![](https://i.imgur.com/SC64kq3.png)

**Comment by kpcyrd** [comment]
Your font configuration seems a bit odd, the comments are usually less bold. :)

**Comment by moshpirit** [comment]
Shoulnd't PF use then its own font then?

**Comment by moshpirit** [comment]
I played with using different fonts on my computer and didn't change at all. Is there anything that could fix this?
