### ISSUE TITLE
"Delete" from comment 3-dot menu does nothing

### ISSUE THREAD

**Issue by kevinflo** [pixelfed/pixelfed#974]
Currently there is a delete button in the list of post actions, but on click it has no effect.

Steps to repro:
1. Comment on a post
2. Click the triple dot on the top right of the comment to open the actions modal
3. Click `Delete`

Expected: comment is deleted
Actual: no effect

<img width="314" alt="screen shot 2019-03-07 at 1 50 53 pm" src="https://user-images.githubusercontent.com/661291/53933080-0ad39080-40e0-11e9-8f99-3950db46332d.png">

**Comment by trwnh** [comment]
This is a regression in one of the latest UI updates. The three-dot menu's Delete button does not work, but if you click "Go to post" then there will be a "Delete" button there that still works.
