### ISSUE TITLE
Can't remove photos

### ISSUE THREAD

**Issue by moshpirit** [pixelfed/pixelfed#98]
Probably related with #97

**Comment by kpcyrd** [comment]
It would be interesting how this is handled in mastodon. Deletion in federated context is difficult, diaspora had pretty big problems with this as well.

**Comment by jordan31bit** [comment]
Deleting would be an awesome feature. Since for some reason my photos are rotated :/

**Comment by trwnh** [comment]
@kpcyrd Federation in Mastodon sends an ActivityPub `Delete` Activity. If Pixelfed was following the AP client-to-server API, then the client would send a `Delete` to their server, and the server would forward that `Delete` to that user's followers' servers.

**Comment by trwnh** [comment]
You can delete photo posts now, they just leave the thumbnail on your profile until you refresh the page.

Click the trash bin | Profile loads with stub thumbnail
--- | ---
![image](https://user-images.githubusercontent.com/10606431/40897435-b7708d3c-6780-11e8-8ba3-d20d08b11634.png) | ![image](https://user-images.githubusercontent.com/10606431/40897440-c7da0a40-6780-11e8-9477-09ca5cec1921.png)
